### ISSUE TITLE
Storing variables in a well-known location

### ISSUE THREAD

**Issue by F21** [GoogleContainerTools/skaffold#1002]
This is feature request is somewhat similiar to https://github.com/GoogleContainerTools/skaffold/issues/543, but I think the spirit is somewhat different.

As mentioned in #543, it would be extremely useful to be able to interpolate environment variables into `skaffold.yml`. For a lot of use-cases this works well. However, I have a use-case where I want to interpolate some git credentials into my `skaffold.yml` file. I do not want to store the credentials as an environment variable as it can be printed out with `env`.

It would be nice if skaffold can look in a well-known location such as `~/.skaffold/vars` and use the variables defined in there (in addition to the environment variables) for interpolation.

**Comment by tstromberg** [comment]
As this issue has been around for 18 months without much in the way of updates, I'm going to close this now as stale. It's unclear to me whether or not this is as important as it once was given the changes to Skaffold since it was opened.

We may reopen this in the future.
