### ISSUE TITLE
Latest Binary Out Of Date

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#1003]
The latest binary download for Linux in the manual is for API version 2. All the examples use 3, and the help they provide "skaffold fix" doesn't work.

**Comment by terabyte** [comment]
I also ran into this, I ended up building skaffold locally to get the new version.

**Comment by terabyte** [comment]
For the future, if the version is not recognized, how about a better error message than just "couldn't parse config, try fix"?

**Comment by balopat** [comment]
+1 on better error messaging. 
@terabyte if you want to use the head version, you could use the latest published binaries as well: 

````
 gsutil ls -l gs://skaffold/builds/latest/
  48836048  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-darwin-amd64
        92  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-darwin-amd64.sha256
  49379507  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-linux-amd64
        91  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-linux-amd64.sha256
  49361408  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-windows-amd64
  49361408  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-windows-amd64.exe
        97  2018-09-19T22:34:29Z  gs://skaffold/builds/latest/skaffold-windows-amd64.exe.sha256
                                 gs://skaffold/builds/latest/docs/
````

For example:

- the latest docs: 
https://storage.googleapis.com/skaffold/builds/latest/docs/index.html
- the latest linux binary:
https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-amd64

**Comment by balopat** [comment]
The better error message could be: 

"The version of this skaffold.yaml is <xyz> you are trying to run and skaffold was expecting an older <abc> version. If this is a skaffold example, we might have a newer version in master than the latest release of skaffold. You are on the current latest release (<latest release>). If this is an example from the skaffold github repo, try checking out the matching version <latest release>. If you want to use <xyz> version skaffold.yaml, try to download the latest build from: https://storage.googleapis.com/skaffold/builds/latest/skaffold-<operating system> "

**Comment by r2d4** [comment]
ref https://github.com/GoogleContainerTools/skaffold/issues/367

**Comment by dlorenc** [comment]
I have a code fix coming with a better error message.
