### ISSUE TITLE
Cleanup Dockerfile parsing code

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1009]
It's currently a big mess!
@r2d4: "they moved all that code to buildkit/dockerfile"

**Comment by r2d4** [comment]
https://github.com/moby/buildkit/tree/master/frontend/dockerfile should help!

**Comment by dgageot** [comment]
@r2d4 This is what we are using already, right?

**Comment by nkubala** [comment]
To what extent was this addressed by https://github.com/GoogleContainerTools/skaffold/pull/1053? Can we close this?
