### ISSUE TITLE
Remove $ from example commands

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1011]
Inspired by:

https://twitter.com/krisnova/status/1041707656761761794

https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output

WDYT?

**Comment by nkubala** [comment]
Seems reasonable, but I agree with the second link that we should use `$` in places where we also display the output, e.g. 
```bash
$ skaffold run
[some output]
```
