### ISSUE TITLE
Add option to not port forward in `skaffold dev`

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1038]
#1037 but for port-forward

**Comment by Atul9** [comment]
I would like to work on this

**Comment by r2d4** [comment]
Excellent! I can't assign you directly, but I assigned the container-tools-bot as a placeholder. Let me know if you need any extra help or pointers. The code should be fairly similar, and the port forwarder is right next to the logger.

**Comment by Atul9** [comment]
@r2d4 Can you please suggest the message to pass to `cmd.Flag().BoolVar`?  
Is this fine? - `Selecting pods satisfying a certain condition and port-forwarding the exposed
 container ports within those pods`
