### ISSUE TITLE
Document the environment variables that skaffold accepts

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1042]
SKAFFOLD_DEPLOY_NAMESPACE

SKAFFOLD_UPDATE_CHECK

Are the ones I can remember

**Comment by r2d4** [comment]
Looks like SKAFFOLD_DEPLOY_NAMESPACE is deprecated in favor of SKAFFOLD_NAMESPACE

**Comment by dgageot** [comment]
This is now documents on skaffold.dev
