### ISSUE TITLE
Using git commit sha1 in envTemplate

### ISSUE THREAD

**Issue by remoe** [GoogleContainerTools/skaffold#1068]
Want to use git commit sha1 in "envTemplate":

```yaml
        envTemplate:
          template: "127.0.0.1:5000/{{.IMAGE_NAME}}:{{.GIT_COMMIT}}"
 ```

Because with private docker registry one need to define the server in "envTemplate". 

### Expected behavior
Using git commit sha1 in template.

### Actual behavior
git commit sha1 is not exported to template variable.

### Information

- Skaffold version: 0.15

**Comment by remoe** [comment]
similar https://github.com/GoogleContainerTools/skaffold/pull/929

**Comment by balopat** [comment]
I'm not sure this still makes sense. I wonder if the  the git tagging policy be sufficient. Please reopen if it isn't.
