### ISSUE TITLE
Add new features to README

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1076]
**Automatic port-forwarding**
Skaffold automatically port-forwards any container ports in pods.

**File syncing**
Skaffold can automatically sync files to a running container and skip a rebuild. Runs your pods 

**skaffold init**
Skaffold can generate its own skaffold configuration file for "source-to-deployment"

**deployment labeling**

Probably some others I missed. We should incorporate these into our new site/README

**Comment by cliffburdick** [comment]
@r2d4 I'm interested in a couple of these. Looking forward to it.

**Comment by balopat** [comment]
+ testing phase

**Comment by radityasurya** [comment]
looking forward for the `File Syncing`

**Comment by haf** [comment]
When does it port-forward?

**Comment by rangelfinal** [comment]
The Testers "How-to Guide" links to this issue: https://skaffold.dev/docs/how-tos/testers/  
As this issue is currently closed, is there a open issue for this documentation?

**Comment by bhack** [comment]
For filesync is it documented if it is possible to use with `NoDockerfile` https://github.com/GoogleContainerTools/skaffold/issues/1396?

**Comment by nkubala** [comment]
scoped this down to a few individual issues.
