### ISSUE TITLE
Upgrade kubectl version in docker image.

### ISSUE THREAD

**Issue by albertkang** [GoogleContainerTools/skaffold#1081]
### Expected behavior
expect `kubectl` to create secrets when using the image `gcr.io/k8s-skaffold/skaffold:v0.15.0`

### Actual behavior
the following error happens
`error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

### Information
I think the `kubectl` version needs to be updated in the docker image needs to be updated from 1.10. https://github.com/kubernetes/kubectl/issues/401.

**Comment by priyawadhwa** [comment]
@albertkang kubectl will be updated to 1.12.0 once #940 goes through.

**Comment by priyawadhwa** [comment]
Hey @albertkang, #940 was merged and kubectl v1.12.0 should be in all skaffold images v0.16.0+

I'll go ahead and close this issue, please comment or open another if you run into any more issues.
