### ISSUE TITLE
Port-forwarder and Logger should not watch every pod

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1083]
They should watch only pods that have the skaffold default label applied. This will make it so that theres a little less work being done.

```golang
func labelSelector() string {
	var reqs []string
	for k, v := range constants.Labels.DefaultLabels {
		reqs = append(reqs, fmt.Sprintf("%s=%s", k, v))
	}
	return strings.Join(reqs, ",")
}
```
```golang
pods, err := client.CoreV1().Pods("").List(meta_v1.ListOptions{
 	LabelSelector: labelSelector(),
})
```

Should be applied to

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/watcher.go#L33-L36

**Comment by dgageot** [comment]
I'm afraid this won't work. What I see is that when I use a deployment, this deployment gets the labels but not the pods.

**Comment by nkubala** [comment]
@dgageot that seems like an issue with the labeller then. If we can stream logs from pods created through deployments we should also be able to set labels on them

**Comment by dgageot** [comment]
I'm going to close this one. Since we apply labels after the manifests are deployed, we would lose the logs for resources that are not yet labelled.
