### ISSUE TITLE
use `kubectl replace --force` for one-off pods

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1099]
when a "one-off" (short lived) pod is defined with `RestartPolicy: Never`, the following happens with `skaffold dev`:  

1.) image is built 
2.) kubectl apply succeeds - pod is deployed, pod completes 
3.) code change triggers loop
4.) image is built 
5.) `kubectl apply` succeeds - pod does not restart, skaffold just says "Waiting for changes...", there are no logs, and the pod will still have the old version of the image 

Proposed behavior: 

1...4.. same 
5.) `kubectl apply` succeeds, skaffold recognizes that pod's image is not the same tag as the latest build - prints warning, and runs a `kubectl replace --force` instead. Pod gets deleted and redeployed, skaffold streams new logs.   

Open question(s):  
* should this be only for `skaffold dev` or `skaffold run` as well? 

cc #891 
cc #940 
cc @coollog

**Comment by coollog** [comment]
I think it makes sense for `skaffold run` as well since a successful skaffold deployment should probably give the promise of the intended running pod(s) using the image built during the build stage.

**Comment by balopat** [comment]
With the --force flag this is covered I believe.
