### ISSUE TITLE
GKE Quickstart Guide is confusing

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1126]
Reported by @m-okeefe:

"The first instructions were to go into Cloud Shell, but I wanted to run this on my mac, where I'd just installed the Skaffold CLI. 
I ended up using my teammate Ahmet's [guide](https://github.com/ahmetb/skaffold-from-laptop-to-cloud/tree/master/30-remote-build-to-gke) instead, which was the first result of googling "skaffold gke".

**Comment by balopat** [comment]
We don't have this anymore on skaffold.dev, closing.
