### ISSUE TITLE
Jib builder should autodetect Maven vs Gradle

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#1134]
From #1096:

@dgageot:
> Is there a way to add a single type of artifact called Jib that auto-detects if it's a gradle or a maven build? That would make the config easier to read/write. I know the maven and gradle configs don't have the same parameters though.

@coollog:
> Yep, we can definitely auto-detect Gradle/Maven (via detection of pom.xml or build.gradle or the respective wrappers). However, the concern is which priority to detect these in. For example, someone could have both pom.xml and build.gradle and those files could be named differently as well. The wrappers could also both be present. In any case, we would also need to provide a user configuration for Maven or Gradle as a fallback in case the auto-detection was incorrect. This detection could probably be specified via a buildFile parameter where passing in an .xml file would mean Maven and .gradle file would be Gradle.

@dgageot:
> Maybe have a jib artifact with a type property. Type would be auto-detected unless the user specifies maven or gradle. Once again, it can be changed later but I think it makes the configuration simpler.

@briandealwis:
> For the Maven case we need to look for a pom.xml or a .mvn/ directory — Maven now supports a polyglot mode (e.g., using groovy or Scala or other formats for expressing the project model), so pom.xml may not exist.

@loosebazooka:
> Maven and Gradle will probably have different configuration parameters. We might need to make it nested to handle a single jib artifact.
> ```
> jib {
>   maven {
>     profile = "asdf"
>     ...
>   }
> }
> 
> // or
> 
> jib {
>   gradle {
>     ...
>   }
> }
> ```

**Comment by briandealwis** [comment]
@coollog have you seen situations in the wild with both a `build.gradle` and `pom.xml`?  What are they trying to do?

**Comment by coollog** [comment]
I haven't seen that personally - I just sometimes have both in example projects to show using Maven and Gradle. I think this autodetect would be useful for `init` as well #1264 so that init creates the `skaffold.yaml` with the right artifact configuration.

**Comment by dgageot** [comment]
Let's close this one. This is not something considered in the near future.
