### ISSUE TITLE
Add rsync syncer

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1137]
If kubectl syncer does not perform well. Need to do some benchmarks.

Should only need to modify these few lines

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/sync.go#L51-L57

**Comment by bhack** [comment]
Take an overview to https://github.com/vapor-ware/ksync/blob/master/docs/architecture.md#syncthing

**Comment by bhack** [comment]
Check also https://github.com/ernoaapa/kubectl-warp

**Comment by bhack** [comment]
See also upstream https://github.com/kubernetes/kubectl/issues/551

**Comment by balopat** [comment]
Based on usage data and feedback, currently the sync is performant enough, at least I am not aware of any performance issues. 
Closing this for now.

**Comment by rupurt** [comment]
Is there any way to add this as a plugin or configure the docker builder to ksync instead of rebuilding the image?
