### ISSUE TITLE
Log which files changed whenever a rebuild is triggered

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1140]
Skaffold should log (DEBUG/INFO level) which files the watcher sees as changed each time it triggers a rebuild. This can help us debug cases where Skaffold is triggering unwanted rebuilds.

**Comment by r2d4** [comment]
it does this https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/watch/changes.go#L109

**Comment by nkubala** [comment]
ahh missed that, thanks
