### ISSUE TITLE
Support deletion of images

### ISSUE THREAD

**Issue by mxey** [GoogleContainerTools/skaffold#1143]
I use Skaffold in my pipelines, including feature branches. After merging a feature branch, I'd like to remove Docker images that were created for the branch. A Skaffold command to delete the image(s) according to the tagPolicy would be useful.

**Comment by nkubala** [comment]
Hey @mxey, agreed that this is something that should be supported in skaffold. I'd also personally like to see an option to automatically prune the images skaffold creates once they're no longer being used in any k8s deployments. We'll be working on this soon.

**Comment by nkubala** [comment]
we added image pruning a while back, so I'm going to close this issue. if anyone has other things they'd like to see related to image deletion, feel free to reopen this.
