### ISSUE TITLE
Provide a "fast build" mode

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1150]
When Skaffold is stopped and restarted, it has to rebuild all artifacts. Even if most builder have cache mechanism, it can be slow to realize that nothing has to be built. For example, `docker build` needs to be sent the whole context before even starting.

We could maybe keep a state on disk that lists the images that are built and the digest of the files that were used for the build. This way, when Skaffold is restarted, all it has to do is list the files for each artifact, compute a digest (locally) and trigger or not a rebuild.

Those checks could run in // and would benefit bigger projects.

A command line flag would enable this behavior that, by default, would be disabled to ensure the best possible consistency.

**Comment by balopat** [comment]
This is implemented in #1632.
