### ISSUE TITLE
Docker deployer

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1153]
A generic image-based deployer. You could even build the image in the build part of the pipeline and use it later in the deploy step.

Skaffold will mount your kubeconfig(s), and a serialized build artifacts file.

**Comment by balopat** [comment]
Thanks for the suggestion, can you please elaborate on benefiting use cases?

**Comment by balopat** [comment]
We support this now - `skaffold deploy` takes a list of images or a JSON output from `skaffold build`
