### ISSUE TITLE
Wait utils should switch to event based watchers instead of polling

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1170]
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/wait.go

Should use a watcher like:

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/watcher.go

This will be more efficient and responsive.

**Comment by dgageot** [comment]
+1000 on that. I wanted to do it today.

**Comment by g-harel** [comment]
I've just opened a [draft PR for this issue](https://github.com/GoogleContainerTools/skaffold/pull/1811). I still need to run/write some tests, but I'd love some early feedback on the approach.

**Comment by g-harel** [comment]
@dgageot I believe this issue can be closed after #1811

**Comment by dgageot** [comment]
Thank you!
