### ISSUE TITLE
Add a React example with file-sync

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1173]
Changes to javascripts files should be synced and applications behavior should be immediately reflected in the application. This would show a powerful feature of skaffold. It should follow the same pattern as https://github.com/GoogleContainerTools/skaffold/tree/master/examples/hot-reload

**Comment by nkubala** [comment]
@foodaka if you're seeing issues with file sync with react, could you open a separate issue? if there's a bug there we'll want to track that separately.

**Comment by ev-dev** [comment]
Would skaffold file sync apply to the typical react development model with HMR?

Development modes in most common react starters/boilerplates have the transpile step via babel involved (ie. react-scripts in create-react-app). I would think that the file watcher listening within the node container running during dev would have trouble receiving signals for file changes in the same way as running on a local machine. May also have to do with websocket issues possibly? 

Has anyone successfully pulled of a dream dev environment for react apps w/HMR running in cluster?

**Comment by ev-dev** [comment]
One way to get Skaffold + React HMR working would be to modify the default behavior of the HMR mechanism to use polling. I believe in most setups the default is to attempt to use various implementations of detecting file-system changes per OS.

If you are using create-react-app there's a convenient environment variable, CHOKIDAR_USEPOLLING found in their docs at https://facebook.github.io/create-react-app/docs/advanced-configuration that sets this behavior. Setting this to true in a Dockerfile specified for development use should work with Skaffold, and there are probably other methods of ensuring the node process within the container has the value set during runtime (ie. in package.json start script).

If you are not using create-react-app there should still be some way of setting the HMR mechanism to poll either via webpack-dev-middleware as seen in this example https://github.com/jumoel/react-hmr-k8s/blob/master/devserver.js and probably other methods if you use Parcel or some other dev setup. 

Haven't gotten around to testing this tho, so be warned this is for sure speculation

**Comment by ev-dev** [comment]
Also just noticed that @foodaka was speaking about issues with `skaffold dev` not registering changes to local files so everything I commented about might not apply 😖

**Comment by michaelfig** [comment]
@ev-dev, I have a PR that fixes the HMR working... instead of just `kubectl cp`-ing the file into place, also run a `kubectl exec ... touch $dst` so that inotify/dnotify detect that the file changed.  This makes chokidar work without need for `CHOKIDAR_USEPOLLING`, and all just works as expected (for my testing, at least).

You can have a look at #1627.

**Comment by ev-dev** [comment]
Ah that's a much better idea! good stuff @michaelfig 👍

**Comment by balopat** [comment]
Added a separate issue to denote HMR related issues. This issue should be about the React example with filesync.

**Comment by balopat** [comment]
@foodaka do you still see the HMR issue?

**Comment by corneliusweig** [comment]
In addition to the example I have also created a small demo application with a step-by-step guide to get started with `create-react-app` and Skaffold: https://github.com/corneliusweig/skaffold-create-react-app
