### ISSUE TITLE
Add a local builder that uses Kaniko

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1176]
The idea is to use kaniko locally, without the Docker daemon, to build images.

**Comment by r2d4** [comment]
What would this be useful for? skaffold in a container?

**Comment by dgageot** [comment]
Skaffold on Linux for eg
Le jeu. 18 oct. 2018 à 19:13, Matt Rickard <notifications@github.com> a
écrit :

**Comment by cedrickring** [comment]
Something similar to [run_in_docker.sh](https://github.com/GoogleContainerTools/kaniko/blob/master/run_in_docker.sh) ?

**Comment by dgageot** [comment]
Let's close this one for now
