### ISSUE TITLE
support --tiller-namespace

### ISSUE THREAD

**Issue by Morriz** [GoogleContainerTools/skaffold#1183]
Some of us put tiller in another namespace with `--tiller-namespace`. Is that configurable in `skaffold.yaml`?

**Comment by balopat** [comment]
Thank you for opening this issue! This is not supported yet, but it shouldn't be too bad to add support (see [namespace support](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/helm.go#L193)). See  PR's are more than welcome!

**Comment by balopat** [comment]
Nice, thank you for the tip @rootd00d!

**Comment by corneliusweig** [comment]
@Morriz #1284 added the possibility to pass arbitrary flags to helm. Can you try with 

```yaml
deploy:
  helm:
    flags:
      global: ["--tiller-namespace=foo"]
```

**Comment by Morriz** [comment]
Tnx @corneliusweig! I have not been into skaffold for a while now...but I might soon :)

**Comment by corneliusweig** [comment]
So if anybody can confirm this is working, this issue can be closed.

**Comment by dgageot** [comment]
Let's close this issue.
