### ISSUE TITLE
Ability to takeout the processed kubernetes YAML file

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#1187]
I think "skaffold build" command should allow doing something like:

```
skaffold build \
    --build-receipt out.json \
    --kubectl-manifests manifests.yaml
```

So I can actually decide whether I want to apply the `manifests.yaml` myself. Similarly, I can use `out.json` to parse out the built artifacts and store their names/tags for my own purposes.

Right now, "skaffold {build,run}" outputs aren't very usable. There should be a contract for those willing to parse output –or flags like this saving the results to a file.

This would solve #922 as well if the produced `--build-receipt` and `--kubectl-manifests` could be fed back into `skaffold deploy` command.

**Comment by r2d4** [comment]
This is somewhat of what I envisioned https://github.com/GoogleContainerTools/skaffold/issues/726 providing. But this is a great idea.

**Comment by dgageot** [comment]
Could it be a `skaffold run --dry-run` that outputs the manifests to stdout?

**Comment by r2d4** [comment]
How about “skaffold show build” to output what would be built + tags and “skaffold show deploy” to output what would be applied. “skaffold show” would return both?

**Comment by ahmetb** [comment]
Sorry for not replying earlier, these are good ideas.

Some form of reliable process to take out either the build artifacts and/or the compiled manifest would be very interesting.

**Comment by alnr** [comment]
Note you can pass the `--dry-run` flag to your deployer of choice, but output is interleaved with skaffold logging (see https://github.com/GoogleContainerTools/skaffold/issues/1937#issuecomment-509255138)

**Comment by balopat** [comment]
That sounds great @edwin-zvs - thanks for sharing your use case, I'm excited to see Skaffold in your product (FYI the link on your main page is pointing to buildpacks.io ;)).

**Comment by edwin-zvs** [comment]
Thanks @balopat for the feedbacks. I just fixed the link in our website. Internally, we even use Skaffold's custom buildCommand to build project with buildpacks. Works like a charm!
Thanks again.
