### ISSUE TITLE
Filewatching based on git repository

### ISSUE THREAD

**Issue by jagan1333** [GoogleContainerTools/skaffold#1192]
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by r2d4** [comment]
ref https://github.com/GoogleContainerTools/skaffold/pull/806

**Comment by balopat** [comment]
I think this is a great idea, we have to flesh out the details but I'd be open to put it on the roadmap.

**Comment by dlorenc** [comment]
Is this the same usecase as what @priyawadhwa is working on now?

**Comment by priyawadhwa** [comment]
Yup, if the intention is to run "skaffold run" whenever code is merged then the pipeline I'm working on will accomplish this.

**Comment by dlorenc** [comment]
Thanks, Priya! Do you have a separate bug/issue for that?

**Comment by priyawadhwa** [comment]
Just opened #1218 to track it! :)

**Comment by jagan1333** [comment]
Thanks a lot guys !

**Comment by balopat** [comment]
@jagan1333  what was your exact scenario here? 
@priyawadhwa is working on a GCB based setup: git push -> github GCB app -> GCB builds and deploys to your cluster.  
I thought this use case was for local setup: skaffold dev -> a new git watcher sees a change, pulls it down locally, merges things if necessary -> builds as usual -> deploys as usual

**Comment by dlorenc** [comment]
@balopat - you're right that they're sightly different. I'd be interested in understanding some of the reasons users would prefer one to the other.

**Comment by balopat** [comment]
Just throwing out another idea: I could imagine this to be useful in a `skaffold dev` situation when working in a larger team, and then skaffold could warn the user, pull down changes based on new commits in the git repos and redeploy. 

If this is still useful for someone please let us know.

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.
