### ISSUE TITLE
Runner should have single pod watcher

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1193]
Currently we open up separate watches on the same set of pods for both the logger and the port-forwarder. There should only be one.

Logger
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/log.go#L66-L105

Port-forwarder
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/port_forward.go#L121-L162

**Comment by priyawadhwa** [comment]
After redesigning port forwarding (#2215) I don't think we will make this change anymore. I'm going to go ahead and close this issue!
