### ISSUE TITLE
Processing only a subset of defined artifacts

### ISSUE THREAD

**Issue by gintautassulskus** [GoogleContainerTools/skaffold#1199]
It would be great if `scaffold` supported processing only a subset of defined artefacts. Suppose I have the following gradle multi-project build structure:

```
root-project:
-microservices-a   \\common stuff for 'a'
  - a-1
  - a-2
- microservices-b   \\common stuff for 'b'
  - b-1
  - b-2 
```

How do I process only a subset of projects, e.g. `b-1` and `b-2` under `microservices-b`?
@balopat suggested `skaffold dev --artifacts b-1,b-2` could potentially do the trick.

I am new to `skaffold`, therefore, at the moment I am not able to provide you with a sample project or a `skaffold.yaml` config file.

**Comment by nkubala** [comment]
Closing this as a dupe of #521
