### ISSUE TITLE
Container Printing Truncated in Dev Mode

### ISSUE THREAD

**Issue by cliffburdick** [GoogleContainerTools/skaffold#1200]
I have an application that catches a SIGINT, and displays some information before exiting. Kubernetes specifies that docker sends a SIGTERM to the container before killing it, so I'm catching that as well. However, skaffold dev seems to catch the SIGINT and cease to print any new information from the container. It might be useful to have a grace period (like kubernetes) where we can optionally specify the amount of time to let the container finish after a SIGINT and before closing the logger.

### Expected behavior
All container output before exiting is printed
### Actual behavior
Skaffold terminates before container finishes printing
### Information

- Skaffold version: v0.15.1
- Operating system: Ubuntu 18.04

### Steps to reproduce the behavior

1. Create a container that prints information on SIGINT
2. Run skaffold dev with that container, and notice there is no printing.

**Comment by dgageot** [comment]
@cliffburdick have you tried with more recent version of Skaffold. I remember fixing a similar problem

**Comment by balopat** [comment]
@cliffburdick  friendly ping, is this something you are still having issue with?

**Comment by cliffburdick** [comment]
Hi @balopat I think you can close it. I meant to reply that it appears to be fixed.

**Comment by rstoermer** [comment]
Is this really fixed? When starting my node.js service with "node service.js" and then CTRL + C I get:

![image](https://user-images.githubusercontent.com/5518072/132023035-f4736fb3-cde4-4cd4-8efe-1a5da44f438a.png)

With skaffold dev I get:

![image](https://user-images.githubusercontent.com/5518072/132023201-1733d47e-e430-4ec3-a8bb-029bd2f098a6.png)

So the container doesn't print any cleanup statements...
