### ISSUE TITLE
FR: Use skaffold to set up a pipeline to watch a remote repository

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#1218]
This pipeline will use managed services like GCB to watch a Github repo for changes and run "skaffold run" whenever code is merged in a remote repository.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
