### ISSUE TITLE
Allow port-forwarding to services instead of pods

### ISSUE THREAD

**Issue by harrisjoseph** [GoogleContainerTools/skaffold#1245]
Some existing issues with port-forwarding could be resolved by port-forwarding to a k8s service instead of pods
* Trying to port-forward from privileged ports on the host
* Port clashing between different pods
  * Especially problematic if you can't configure the port on your application
Issue https://github.com/GoogleContainerTools/skaffold/issues/969 mentions these

You shouldn't have to change your application port for local development - it makes more sense to use services and configure the listening ports independently from the pods.

A cli argument / yaml config value should be used to make 'services-mode' optional - as existing users may not be using services with skaffold

This looks reasonably easy to implement on top of the existing functionality.
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/port_forward.go#L121-L162

- Skaffold version: latest
- Operating system: osx

**Comment by yeDor** [comment]
Vote for this feature because of solving the problem "Port clashing between different pods"

**Comment by priyawadhwa** [comment]
Hey @harrisjoseph I just merged #2215, which now automatically port forwards services for `debug` and `dev` when the `--port-forward` flag is set. Additional resources to port forward can be defined in the skaffold config as of #1311. 

Does this solve your use case?

**Comment by harrisjoseph** [comment]
It does. Thanks!On 28 Jun 2019 17:56, priyawadhwa <notifications@github.com> wrote:Hey @harrisjoseph I just merged #2215, which now automatically port forwards services for debug and dev when the --port-forward flag is set. Additional resources to port forward can be defined in the skaffold config as of #1311.
Does this solve your use case?
