### ISSUE TITLE
Skaffold Event API

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1265]
Expose lifecycle events through gRPC/HTTP endpoint through what subscribers can get notified. 

This would alleviate the need to parse logs for events like: 
- build started for artifact  
- build finished for artifact
- build error for artifact
- deployment started 
- deployment finished 

The main use case has IDEs as consumers.

**Comment by briandealwis** [comment]
IDEs would also like to control Skaffold, such as to disable file-watch/rebuilding for a particular artifact.  This is necessary for Java projects, for example, that have alternative mechanisms for replacing content (JDWP).

**Comment by balopat** [comment]
Fixed by #1574.
