### ISSUE TITLE
Profile auto-activation

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1271]
Profiles could be made more powerful with some kind of auto-activation.
In Maven, profiles can be activated automatically based on some configuration.
I think we should implement this feature too. Here are a few use cases:
 + Activate a profile based on local/remote
 + Activate a profile based on the context
 + Activate a profile based on the command: skaffold dev|run

**Comment by balopat** [comment]
cc https://github.com/GoogleContainerTools/skaffold/issues/488 for the last point
