### ISSUE TITLE
Transparent `skaffold init`

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1273]
When no skaffold configuration is found on disk, maybe we could run `skaffold init` in memory and use that.
I think it would be a very simple way of getting started with Skaffold and also a good way of supporting things like compose files transparently.
We’d, of course, print a warning to explain what’s going on and which configuration Skaffold is using.

**Comment by tejal29** [comment]
@TadCordle, since you are the `init` expert, let us know if this is something you are planning to do soon.

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.

**Comment by balopat** [comment]
I'd reopen this, as the lack of signal here doesn't mean it would help a lot of people.
