### ISSUE TITLE
Document JIB maven and gradle on the new site

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1299]
ref #1060

**Comment by patflynn** [comment]
@balopat 
@loosebazooka 

Should we assign this to someone on the jib team?

**Comment by patflynn** [comment]
@balopat 
@loosebazooka 
@tadcordle 

friendly ping :)

**Comment by loosebazooka** [comment]
Oh right, yeah, @TadCordle can probably own this for now, as he'll be doing the jib optimizations.

**Comment by briandealwis** [comment]
I'm taking a stab at this.

**Comment by briandealwis** [comment]
- [ ] create example multi-module projects too.
- [ ] document GCB + Jib

**Comment by tejal29** [comment]
@briandealwis would you be able to do this by Nov 7th?
