### ISSUE TITLE
User defined port-forwarding

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1311]
It would be useful to let the developer remap ports to be forwarded locally, say when they want to work on deeper level components that are using the same port.

**Comment by demisx** [comment]
Would be also very helpful if skaffold could bind to any interface, not just localhost. Similar to `--address` param in `kubectl`:

```
kubectl port-forward --address 0.0.0.0 dl-org-api-7c687466cf-xpmzb 3000:3000
```

 Unless this is already possible and I just can't figure out how. Default skaffold port forwarding in v0.28 seems to map to `127.0.0.1` only and I have outside SNS service that's doing POST to a local IP address instead.

**Comment by priyawadhwa** [comment]
Hey @demisx , thanks for the suggestions. We have an issue open for this at #1358 which you can track. We're currently working on developing a solution.

**Comment by demisx** [comment]
Great! Sorry, didn't notice it.

**Comment by priyawadhwa** [comment]
Done with #2336 !
