### ISSUE TITLE
Support post-sync hooks

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1312]
When a local file is synced into a running container, it would be useful to run a command inside the container., either to tell the running process to reload that file or to perform some post-processing such as minification.

**Comment by nthypes** [comment]
Maybe close in favor of #1441 ?

**Comment by nkubala** [comment]
@nthypes I don't think it's quite the same issue. this one refers to running a hook inside the container that the files were synced to - that issue is around running commands on the host that skaffold is running on.

**Comment by nthypes** [comment]
> @nthypes I don't think it's quite the same issue. this one refers to running a hook inside the container that the files were synced to - that issue is around running commands on the host that skaffold is running on.

Gotcha!

**Comment by ramukima** [comment]
Not sure about any milestone set for this. My use case as well requires a command to be executed within my container after sync has been performed.

If post-sync hooks are allowed, will the hook be called a single time or multiple times for each file change ? I believe, all changes at a given time are tar'ed and copied in one go into the container.

`
sync:
  infer:
  - 'workdir/compiled/packages/foo'
       command: [ 1. Reload config, 2. Ensure reloaded config ]
  - 'workdir/**/*'
` 

Note that, I would like to run commands only when my 'config.json' file is synced and not when rest of the files from the same directory are synced (to avoid reload multiple times).

**Comment by tejal29** [comment]
@loosebazooka This could be addressed in #2357. adding same priority as #2357
Can we close this as dupe if it something we could implement as #2357

**Comment by gabor-boros** [comment]
👍

**Comment by mark-ambrazhevich-spiral** [comment]
We also reallly would like to see this feature. Our use cases is once files get updated, we need to issue command to gracefully reload application.

**Comment by nkubala** [comment]
@mark-ambrazhevich-spiral and everyone else here, just a quick update that this is now being prioritized by our team. we'll provide updates as we make progress!

**Comment by tstromberg** [comment]
Any update? The priority on this seems unusually high compared to the progress seen here so far.

**Comment by nkubala** [comment]
the design for this is being actively worked on. I think it's fine to leave this as P1

**Comment by dgageot** [comment]
Closing in favour of more generic #1441
