### ISSUE TITLE
Specifying Dockerfiles locations and docker build arguments

### ISSUE THREAD

**Issue by ksbeking** [GoogleContainerTools/skaffold#1315]
### Expected behaviour

Not an issue. Is an idea for a feature. It would be nice to be able to specify context and the docker file separately. It would be nice in the config file to have the ability to specify docker build arguments and the location of the Dockerfiles.

It might exist, I could not find it in the docs.

### Actual behaviour

Does not have the feature

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by aleksamagicka** [comment]
You can specify Docker `[buildArgs](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml#L49)` in skaffold.yaml.

**Comment by priyawadhwa** [comment]
@ksbeking you can also specify the path to the Dockerfile [here](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml#L45) and the context [here](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml#L41). Is that what you were looking for?

**Comment by dgageot** [comment]
@ksbeking I'm going to assume that this is already possible and close the issue. Feel free to reopen it in case we misunderstood you!

**Comment by toby-1-kenobi** [comment]
The docs for this have all gone missing

**Comment by nkubala** [comment]
@toby-1-kenobi should be fixed now
