### ISSUE TITLE
Bazel query should specify --output

### ISSUE THREAD

**Issue by dicarlo2** [GoogleContainerTools/skaffold#1322]
### Expected behavior

`skaffold dev` with a bazel target should watch files

### Actual behavior

it does not

### Information

- Skaffold version: v0.18.0
- Operating system: macOS

### Steps to reproduce the behavior

1. `clone https://github.com/GoogleContainerTools/skaffold.git`
2. `cd examples/bazel`
3. `echo "query --output=label_kind" > .bazelrc`
4. `skaffold dev`

**Comment by balopat** [comment]
Thank you for the issue! Should be relatively simple to add `--noworkspace_rc` to our bazel query.

**Comment by dgageot** [comment]
Fixed with #1339
