### ISSUE TITLE
Purge helm release option on skaffold delete

### ISSUE THREAD

**Issue by bholemt** [GoogleContainerTools/skaffold#1328]
In case of change in helm template, one needs to helm delete --purge. Otherwise helm upgrade tries to reuse the template from the old delete release. Wish this option is available somehow with skaffold delete.

**Comment by bholemt** [comment]
I need to catch up on Go. Let me try but will need time.

**Comment by tjerkw** [comment]
I think the --force flag for "helm upgrade" also solves this, right?

https://github.com/helm/helm/pull/2280

**Comment by tejal29** [comment]
This is addressed in #2280
