### ISSUE TITLE
Add ROADMAP.md

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#134]

**Comment by Eronarn** [comment]
I'd love to see a roadmap. Especially odd that the README has a "Future" heading that doesn't link to anything... https://github.com/GoogleCloudPlatform/skaffold

**Comment by r2d4** [comment]
Hey sorry @Eronarn I started the work on this, but I'll send a PR shortly

**Comment by dgageot** [comment]
Fixed by #1530
