### ISSUE TITLE
"skaffold test"?

### ISSUE THREAD

**Issue by tmc** [GoogleContainerTools/skaffold#1363]
I wanted to start a discussion around whether or not skaffold should have a test subcommand.

Both bazel and helm have this concept and one could imagine jibMaven and jibGradle adding these.

**Comment by tstromberg** [comment]
As this issue is over a year old without much in the way of updates, I'm going to close this now as stale. It's unclear to me whether or not this is as important as it once was given the changes to Skaffold since it was opened.
