### ISSUE TITLE
Docs for knative usage?

### ISSUE THREAD

**Issue by csantanapr** [GoogleContainerTools/skaffold#1369]
@dgageot Is there some doc or example on how to use it with knative?

Are there any docs or better yet an example on how to use with knative with the recent PR merged #851

**Comment by balopat** [comment]
Hi, that PR was not merged, it got closed as knative Build/Task is going through a lot of changes. Currently we don't support knative, but we are definitely planning to provide integration multiple ways.

**Comment by csantanapr** [comment]
My bad @balopat didn’t notice it was not merged. Now it make sense I was not able to find docs. 

Yes I agree that now build have switched over a different architecture with Knative-pipeline, I think is safe to take another stab that is much stable now. 

Thanks for the quick reply 👍🏻
