### ISSUE TITLE
Add parallel local image building.

### ISSUE THREAD

**Issue by tmc** [GoogleContainerTools/skaffold#1380]
#248 added parallel building to gcb+kaniko, but not local builds.

### Expected behavior
That local builds use InParallel

### Actual behavior
Local builds use InSequence

**Comment by balopat** [comment]
I would love to have this somehow. 

Thoughts: 

This is only for `local` builds. 
On `cluster` and `gcb` builds we have parallel builds. 

1. We experimented with this before for local builds but things were breaking back then . @dgageot maybe it's worth having another look now
2. There _are_ people who depend on sequenced builds - they use it as a poor man's dependency management solution.
