### ISSUE TITLE
[proposal] Kubernetes cluster management

### ISSUE THREAD

**Issue by stasiek** [GoogleContainerTools/skaffold#1388]
First of all Great Thanks for Your work on the project!
I would find it useful if I could set up cluster with Skaffold. For example the loadbalancer, urlMapper, a static IP?

I understand it's beyond the fast rebuild-deploy functionality most would use Skaffold for, but it would mostly eliminate need for `kubectl` usage and under version control leave history of changes.

Using @balopat's words
> So in this scenario you’d depend entirely on skaffold to
> 1.) bootstrap/update your GKE cluster based on some config
> 2.) to deploy the app as a single point of entry

Beside obviously keeping track of configuration in VCS it would be really useful in situation I'm facing at work.
There's this team of analyst we want to be able to freely create their dashboards with bokeh and deploy them on GKE. I'd like them to be able to handle some part of their clusters configuration, like enter the domain You want Your service hosted under and run `skaffold` as usual to get it on GKE.
If skaffold handled it they'd just clone a template project repo, fill some basic config and start working on their own, not having to ask anyone to run all the `kubectl *` commands that confuse them quite  a bit.

**Comment by tstromberg** [comment]
As this issue is over a year old without much in the way of updates, I'm going to close this now as stale.  It isn't clear to me that others felt strongly about this issue one way or another.

We may revisit this feature-request in the future.
