### ISSUE TITLE
NoDockerfile

### ISSUE THREAD

**Issue by bhack** [GoogleContainerTools/skaffold#1396]
How we could use [`NoDockerfile`](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/init.go#L48) with `sync:` key? Is it possible?

**Comment by priyawadhwa** [comment]
Hey @bhack, just to clarify, do you want to be able to sync files into a container which is deployed by but not necessarily built via skaffold?

**Comment by bhack** [comment]
Yes. I.e. It was built by CI

**Comment by bhack** [comment]
Another use case is where I checkout the code from the initcontainer but then I want to sync local changes without commit and restarting the pod.
So it is mainly a sync mode where images are built somewhere else or initial code is provisioned by git.

**Comment by nkubala** [comment]
this could be another use case for having a manual sync trigger exposed through a control API. ref https://github.com/googlecontainertools/skaffold/issues/1520

**Comment by bhack** [comment]
Any news about this?

**Comment by balopat** [comment]
hey @bhack, is this for super large images, e.g. machine learning use case? Why can't you just rebuild the image? 

We will need some time to get consensus on this as it doesn't seem like something core to skaffold workflows. I am not convinced yet: the user would have to specify all the watched dependencies, introduce "prebuilt" images to the dev workflow, that you have to pass in, multiple users interacting with this feature can cause issues...I'm not fully convinced yet myself.

**Comment by bhack** [comment]
Yes generally is for large images for machine learning generally built from Ci.

**Comment by bhack** [comment]
@balopat I.e. see kube warp use case:
`https://itnext.io/introducing-kubectl-warp-live-develop-code-in-kubernetes-9846c16d4bec`
But it still has many limitation:
https://github.com/ernoaapa/kubectl-warp/issues/11
https://github.com/ernoaapa/kubectl-warp/issues/10

And upstream:
https://github.com/kubernetes/kubectl/issues/551

So currently doesn't exist any solution when images are already pushed in the registry from CI/CD.

**Comment by bhack** [comment]
Probably one of the few tool that support these use cases is https://devspace.cloud/docs/cli/development/synchronization

**Comment by corneliusweig** [comment]
@bhack Have a look at https://github.com/vapor-ware/ksync. Sounds similar to kube-warp, but maybe it solves your problem better.

**Comment by bhack** [comment]
@corneliusweig I've already commented at https://github.com/kubernetes/kubectl/issues/551#issuecomment-477568741 about ksync.
