### ISSUE TITLE
Create a detailed architecture diagram 

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1411]
The diagram should describe how the skaffold CLI, the builder and deployer binaries interact and work with the pods for port forwarding and logging. It's component focused instead of workflow - hence it's a bit different view compared to the current diagram we have.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
