### ISSUE TITLE
Add best practices docs around setting up infrastructure around the app

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1412]
Besides the app there are usually other infrastructure pieces that projects want to deploy, e.g.:
- databases + init scripts (how to seed with data)
- caches 
- message queues
- monitoring solutions (elk/graphana/prometheus)

We should document/point to a couple of recommended directions and how they tie back to Skaffold.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.

**Comment by morgs32** [comment]
Well I've been subscribed to this hoping that some documentation or examples would show up eventually. Maybe log something in the cli tool that begs people to add any open source implementations they are doing to a list somewhere in this repo?
