### ISSUE TITLE
mortar deployer

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#1419]
Please have a look at https://github.com/GoogleContainerTools/skaffold/pull/1382

Mortar (https://github.com/kontena/mortar) solves many problem mentioned for example in https://github.com/GoogleContainerTools/skaffold/issues/543

**Comment by tejal29** [comment]
Thank you for opening this feature. I don't we have plans to support this deployer in near future. 
We would definitely want to solve #543 so users can use skaffold across all stages from dev to prod.
I am going to close this.
