### ISSUE TITLE
Skaffold should support configuration options for normal docker credentials

### ISSUE THREAD

**Issue by robbert229** [GoogleContainerTools/skaffold#1420]
### Expected behavior
I should be able to use Skaffold to push to private docker registries.

### Actual behavior
Authentication with normal private docker registries doesn't function. Skaffold doesn't provide the configuration hooks to allow me to configure kaniko to push to my private registry. I would like to be able to pass down docker credentials to the kaniko instance, but currently there is no option to do so.

There is a bit of conversation in here -> https://github.com/GoogleContainerTools/kaniko/pull/129 about how providing credentials to kaniko works.

In #1421 I provide an example of what fixes my current issues.

**Comment by dgageot** [comment]
Fixed with #1466
