### ISSUE TITLE
The html and pdf documentation from the releases page is missing from the GCE bucket

### ISSUE THREAD

**Issue by stefancocora** [GoogleContainerTools/skaffold#1432]
### Expected behavior
The html and pdf docs from the release page should exist in the GCE storage bucket.

### Actual behavior
In `v0.20.0` the docs are missing from the GCE storage bucket. Here is the log output for the html version, I've omitted the pdf version for brevity ( it too is missing from the GCE bucket )
```
curl "https://storage.googleapis.com/skaffold/releases/v0.20.0/docs/index.html"

HTTP/2 404 
x-guploader-uploadid: AEnB2UokZd86F5AEqN0faXB_w64MhbPrBPXMrG4aQqJFPG8DlmbS1NOgkrX21G_S3yLNxinyQ0nXHKxlDKkQtGG_GR5NL4QtfA
content-type: application/xml; charset=UTF-8
content-length: 203
date: Fri, 28 Dec 2018 10:32:05 GMT
expires: Fri, 28 Dec 2018 10:32:05 GMT
cache-control: private, max-age=0
server: UploadServer
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"

<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: skaffold/releases/v0.20.0/docs/index.html</Details></Error>---
```

### Information

- ~~Skaffold version: version...~~ N/A
- ~~Operating system: ...~~ N/A
- ~~Contents of skaffold.yaml:~~ N/A

### Steps to reproduce the behavior
Repeat the curl command form the **Actual behaviour** section above.

**Comment by balopat** [comment]
Thanks for filing this - this is actually something that we don't publish anymore and I should have just removed the links from the release description.

**Comment by balopat** [comment]
I updated the release notes.
