### ISSUE TITLE
Use Istio Servicegraph for dependencies if present

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1434]
Feature Request:

If present, use the Istio service graph to create an in-process dependency map of k8s services. With a configuration toggle, skaffold could restart/redeploy dependent services.

1. Fetch servicegraph
2. If a dependency changes - (rebuild or redeploy) and `cascade: true` (or some other option) and istio servicegraph installed, then redeploy (or restart?) all dependent services.

**Comment by tstromberg** [comment]
As this issue is over a year old without much in the way of updates, I'm going to close this now as stale.  It isn't clear to me that others felt strongly about this issue one way or another.

We may revisit this feature-request in the future.
