### ISSUE TITLE
Skaffold 0.20 local bazel build process doesn't respect compilation mode

### ISSUE THREAD

**Issue by kolotaev** [GoogleContainerTools/skaffold#1467]
Skaffold's v0.20.0 local bazel build process now always takes `bazel-bin` folder from 'bazel info' and doesn't respect compilation mode specified as an argument to an artifact's build spec.

For my system it always takes `/private/var/tmp/_bazel_John/7d101f4ca99a2dca3757570c24be95af/execroot/io_mycompany_superrepo/bazel-out/darwin-fastbuild/bin`, which is correct for fastbuild, but not for `dbg` mode in which the path should be smth like this: `/private/var/tmp/_bazel_John/7d101f4ca99a2dca3757570c24be95af/execroot/io_mycompany_superrepo/bazel-out/darwin-dbg/bin`

If there is already a binary in darwin-fastbuild (suppose, I've run skaffold build without --compilation_mode=dbg) there is no error on skaffold run, but the image has no debug symbols.
If there is no previously built binary in darwin-fastbuild the error of "no such file or directory" occurs.

This worked OK in skaffold v0.19.
Seems, this was introduced in [this commit](https://github.com/GoogleContainerTools/skaffold/commit/5a519d35fed71e44a912affdb6829a2e1c00d33d#diff-8e0ee4a19278809e9202763f99b7a3b9)

Because previously it took `bazel-bin` folder directly which always pointed to a correct current run/compilation mode.

### Expected behavior

Image is deployed in minikube
Image is built with a binary that has debug symbols (as per `--compilation_mode=dbg`)

### Actual behavior

Image is not deployed in minikube
Error occurs:
```
FATA[0001] build failed: building [quay.io/mycompany/router]: build artifact: opening image tarball: open /private/var/tmp/_bazel_John/7d101f4ca99a2dca3757570c24be95af/execroot/io_mycompany_superrepo/bazel-out/darwin-fastbuild/bin/projects/router/docker.tar: no such file or directory 

```

### Information

- Skaffold version: version v0.20.0
- Operating system: OSX 10.11.6
- Bazel version:  0.19.2
- Minikube version: v0.28.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: quay.io/mycompany/router
    context: ../../..
    bazel:
      target: //projects/router:docker.tar
      args:
      - --compilation_mode=dbg
      - --features=pure
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  kustomize:
    path: minikube
```

- Full log after running `skaffold run`
```
INFO[0000] Skaffold &{Version:v0.20.0 ConfigVersion:skaffold/v1beta2 GitVersion: GitCommit:837e53b260a8fbc35765ed8b5f3c41de6a3242b1 GitTreeState:clean BuildDate:2018-12-21T19:08:08Z GoVersion:go1.10.7 Compiler:gc Platform:darwin/amd64} 
INFO[0000] no config entry found for kube-context minikube 
INFO[0000] Using kubectl context: minikube              
INFO[0000] no config entry found for kube-context minikube 
DEBU[0000] Using builder: local                         
DEBU[0000] Running command: [minikube docker-env --shell none] 
DEBU[0000] Command output: [DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/John/.minikube/certs
DOCKER_API_VERSION=1.35
] 
DEBU[0000] setting Docker user agent to skaffold-v0.20.0 
DEBU[0000] push value not present, defaulting to false because localCluster is true 
Starting build...
Found [minikube] context, using local docker daemon.
Building [quay.io/mycompany/router]...
(14:00:01) INFO: Current date is 2019-01-15
(14:00:01) INFO: Analysed target //projects/router:docker.tar (0 packages loaded, 0 targets configured).
(14:00:01) INFO: Found 1 target...
Target //projects/router:docker.tar up-to-date:
  bazel-bin/projects/router/docker.tar
(14:00:01) INFO: Elapsed time: 0,751s, Critical Path: 0,02s, Remote (0,00% of the time): [queue: 0,00%, setup: 0,00%, process: 0,00%]
(14:00:01) INFO: 0 processes.
(14:00:01) INFO: Build completed successfully, 1 total action
DEBU[0001] Running command: [bazel info bazel-bin]      
DEBU[0001] Command output: [/private/var/tmp/_bazel_John/7d101f4ca99a2dca3757570c24be95af/execroot/io_mycompany_superrepo/bazel-out/darwin-fastbuild/bin
], stderr:  
FATA[0001] build failed: building [quay.io/mycompany/router]: build artifact: opening image tarball: open /private/var/tmp/_bazel_John/7d101f4ca99a2dca3757570c24be95af/execroot/io_mycompany_superrepo/bazel-out/darwin-fastbuild/bin/projects/router/docker.tar: no such file or directory 
```

### Steps to reproduce the behavior

1. Create skaffold.yaml file from description
2. Run `skaffold run`

**Comment by dgageot** [comment]
Hi @kolotaev, is there a chance you can try out https://github.com/GoogleContainerTools/skaffold/pull/1487?
