### ISSUE TITLE
Release v0.21.0

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1481]

**Comment by NicklasWallgren** [comment]
Great, when will the binaries be updated?

https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.21.0
https://skaffold.dev/docs/getting-started/#installing-skaffold

**Comment by r2d4** [comment]
@NicklasWallgren binaries are uploaded on every PR and every commit. You can get them here

https://github.com/r2d4/skaffold/blob/606a4ad95e121fde3475a54efe8121fe3a8467dc/docs/published-artifacts.adoc

It seems like this document was deleted during the cutover to the new site. cc @balopat

**Comment by nkubala** [comment]
@NicklasWallgren we're having an issue with our CI system right now, so the build is broken and the binaries haven't been updated yet. We're looking into it and should have the v0.21.0 binaries uploaded soon.
