### ISSUE TITLE
How does this compare with Azure's draft?

### ISSUE THREAD

**Issue by jason-riddle** [GoogleContainerTools/skaffold#150]
It would be nice to compare and list the differences with [draft](https://github.com/Azure/draft).

**Comment by viglesiasce** [comment]
Howdy @jason-riddle!!

Skaffold allows you to choose the tools that map best to your workflow for building images, pushing them, and deploying things to Kubernetes. Skaffold can also be used in CI/CD flows to align with your dev process.

**Comment by bhack** [comment]
https://blog.hasura.io/draft-vs-gitkube-vs-helm-vs-ksonnet-vs-metaparticle-vs-skaffold-f5aa9561f948
