### ISSUE TITLE
Ability to prevent redeploy-on-change in Skaffold dev mode to support debugging

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#1511]
When debugging in Java, source changes should attempt to be propagated over the debugger protocol. Having Skaffold redeploy-on-change will kill the debug session. This issue it to track adding a mechanism to disable Skaffold's redeploy-on-change to support this use-case.

**Comment by etanshaul** [comment]
seems like this is already be supported via `--watch-image none`?

**Comment by cpoole** [comment]
seems like this is also satisfied with the `--trigger manual` arg to skaffold dev

**Comment by tejal29** [comment]
That is correct. We don't have trigger API documented so keep it open.

**Comment by nkubala** [comment]
@etanshaul you should be able to start skaffold with the `--auto-deploy=false` flag, which will still trigger builds/syncs when source files are changed but will skip the deploy phase. the `--trigger` flag is to control the notification mechanism in the file monitor so you probably don't want to use this, unless you want to skip builds and syncs as well. 

i'm gonna close this issue for now, let me know if y'all need anything else to support your use case.
