### ISSUE TITLE
[release process] Publish Cloud Build statuses on GitHub

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1519]
Currently Cloud Build builds every commit and PR but keeps the statuses secret.

**Comment by priyawadhwa** [comment]
The [GCB Github App](https://cloud.google.com/cloud-build/docs/run-builds-on-github), which we could run on every PR to make sure the images can be built before merging.

**Comment by balopat** [comment]
Other approaches: 

1. From Cloud Build - We could also do similar to what minikube is doing - just script up a commit status at the end of the build. For this we'll need a wrapper around the build steps and if they fail we need to report failure from the cloud build itself before returning. Showstopper: we could have a problem when Cloud Build jobs fail before running our scripts.  
2. Use a Cloud Function to subscribe to Cloud Build PubSub events - we actually already have a function setup to send emails. I could use that to send status checks...let me see...

**Comment by balopat** [comment]
![image](https://user-images.githubusercontent.com/635073/63119618-70f8f500-bf55-11e9-9b2e-7174ce4d8401.png)
This started working ... more work: setting it up with container-tools-bot + better build context name instead of "default"

**Comment by balopat** [comment]
But yeah, actually if we'd setup the GCB Github App to trigger the builds properly, instead of relying on the GCB cloned source repo functionality, then maybe we could get rid of the cloud function magic.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
