### ISSUE TITLE
Skaffold needs to support additional builders: Cri-O, Cri-Containerd, ...

### ISSUE THREAD

**Issue by OlivierDupre** [GoogleContainerTools/skaffold#1524]
### Expected behavior
Being able to build with "new" container engines. e.g. Cri-O & Cri-Containerd, Rkt and even Frakti.

### Actual behavior
Docker, Jib & Bazel are the 3 builders currently supported.

Thanks for considering this.

**Comment by dgageot** [comment]
Hi @OlivierDupre, I'm afraid those are container runtimes, not container builders. It's what you'd use to run container rather than what you'd use to build containers.

Could you be more specific about your use case?

**Comment by dgageot** [comment]
I'm going to close this one.

We're currently working on implementing a builder plugin model in skaffold, which would allow users to write plugins for whatever builder they wish to use. Once that's ready this should definitely be possible, you can track the main issue for it at #1551!
