### ISSUE TITLE
Figure out builder plugin distribution

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#1555]
Open Questions/Things to make sure we include:
* Versioning between manifests
* How to handle the case in which a new skaffold upgrade no longer corresponds with the builder plugin version installed
* Clear error messages and guidance for unsupported architectures
* The manifest should point to source code, or explain how a user can build the plugin binary themselves 

Currently looking at krew or kubectl plugins as inspiration.

**Comment by balopat** [comment]
Closing due to https://github.com/GoogleContainerTools/skaffold/issues/1988
