### ISSUE TITLE
Namespace field missing in watcher.go

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#1560]
### Expected behavior 
Running Skaffold  in Dev mode, it should monitoring the code base and create a new kaniko image with changes and push to cluster.
### Actual behavior
Skaffold breaking with message 
error initializing pod watcher

### Information
This is happening due to namespace field missing in following file.
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/kubernetes/watcher.go

- Skaffold version: 1.11
- Operating system: linux and windows
- Contents of skaffold.yaml: NA

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. Any valid skaffold.yaml, deploy,yaml and Dockerfile would do
2. Run skaffold in dev mode.

**Comment by nkubala** [comment]
hey @prary, do you mean version `0.11`? this would be a pretty old version of skaffold, if so can you try upgrading? otherwise, could you paste your skaffold.yaml here? I'm not seeing this issue on version 0.22.0.
