### ISSUE TITLE
Checksum mismatch - windows binary

### ISSUE THREAD

**Issue by colonelpopcorn** [GoogleContainerTools/skaffold#1567]
### Expected behavior
Expect the checksum for the windows binary to match the published version

### Actual behavior
```bash
!!! shasum verify check failed: checksums differ for /Users/travis/Library/Caches/Fish/skaffold-0.20.0-windows-amd64.exe: expected '963af57b5331ba2cc4dc84b98ec667b4a8e7fca100c8f43491fc6e5d4bd7b19d', got '151d74b835d484ada46775785da2f87badc5487aa7a13830565827b29e98bbbe'
```

### Information

Failing Builds:
[Travis](https://travis-ci.org/fishworks/fish-food/builds/486613716)
[Circle CI](https://circleci.com/gh/fishworks/fish-food/261)

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by dgageot** [comment]
ping @balopat

**Comment by nkubala** [comment]
@colonelpopcorn are you installing skaffold with brew? I can't quite tell from the logs in your Travis build but it looks like you might be

**Comment by colonelpopcorn** [comment]
It's actually being installed with a tool called gofish. It aims to be a cross platform package manager. I was trying to add skaffold to their package repository when I ran into this issue with the checksum listed on the release pages for windows. I'm pretty sure it's just the checksum for Windows because the ones for Linux and Darwin were fine, but I could be wrong. Are the checksums for linux, mac, and windows generated differently?

**Comment by nkubala** [comment]
@colonelpopcorn sorry the long delay here. I checked the checksums for v0.20.0 and everything looks fine to me:

```
➜  curl -LO https://github.com/GoogleContainerTools/skaffold/releases/download/v0.20.0/skaffold-windows-amd64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1550      0 --:--:-- --:--:-- --:--:--  1550
100 47.2M  100 47.2M    0     0  10.7M      0  0:00:04  0:00:04 --:--:-- 12.8M
➜  shasum -a 256 skaffold-windows-amd64.exe                                                                      
963af57b5331ba2cc4dc84b98ec667b4a8e7fca100c8f43491fc6e5d4bd7b19d  skaffold-windows-amd64.exe
➜  curl -LO https://github.com/GoogleContainerTools/skaffold/releases/download/v0.20.0/skaffold-windows-amd64.exe.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   624    0   624    0     0   1567      0 --:--:-- --:--:-- --:--:--  1563
100    97  100    97    0     0    114      0 --:--:-- --:--:-- --:--:--   114
➜  cat skaffold-windows-amd64.exe.sha256                                                                                
963af57b5331ba2cc4dc84b98ec667b4a8e7fca100c8f43491fc6e5d4bd7b19d  out/skaffold-windows-amd64.exe
```
Maybe gofish is using a different hashing algorithm, or possibly downloading the wrong binary for Skaffold? Sorry I can't be more help, but I'll close this for now.
