### ISSUE TITLE
Skaffold own-text colours are hard to read

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#1583]
Skaffold's output text is coloured dark blue which is very difficult to see on black.

![screen shot 2019-02-01 at 1 11 25 pm](https://user-images.githubusercontent.com/202851/52141525-04a34d80-2624-11e9-9adb-0cfe1a006006.png)

It would be nice to at least make this value configurable?

### Information

- Skaffold version: 0.22.0
- Operating system: macOS 10.14

**Comment by corneliusweig** [comment]
@briandealwis does the `--color` option solve this for you?

**Comment by briandealwis** [comment]
`--color` for the win!
