### ISSUE TITLE
Add a registry source for kaniko

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1595]
https://github.com/GoogleContainerTools/skaffold/tree/master/pkg/skaffold/build/kaniko/sources

Instead of uploading to GCS and requiring yet another credential, store the context in the registry by pushing a single layer image and retrieving the context by pulling/untar

**Comment by priyawadhwa** [comment]
We added support for [localDir](https://skaffold.dev/docs/how-tos/builders/#dockerfile-in-cluster-with-kaniko) which uses an init container to untar the buildcontext & doesn't require any credentials.

Closing this as we have an alternative!
