### ISSUE TITLE
reload skaffold.yaml

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#161]
I think as users change skaffold.yaml, running `skaffold dev` process should be able to detect it and reload the config instead of using the old config content when the process first started.

I hit this while playing with `tagPolicy: gitCommit` vs `: sha256`.

**Comment by gtseres** [comment]
I have an issue with `skaffold dev` as well. I followed the steps documented in the [README file](https://github.com/GoogleCloudPlatform/skaffold/blob/master/README.md), using the `getting-started` example. 

Environment:
OS: MacOS High Sierra 10.13.3
Skaffold version: v0.2.0
minikube version: v0.25.0 (driver: virtualbox)

Steps followed:
1. Edited the `skaffold.yaml` file and changed image name to `skaffold-example`
2. Run `skaffold dev`. Image deployed successfully in minikube, the pod has been created and the `Hello world!` message is displayed.
3. Edited the `skaffold.yaml` file again, changing `Hello world!` to `Hello George!`. Saved it.
4. Waited for a couple of minutes to see the new message in the output of the `skaffold dev` command, no luck though.
5. Interrupted and re-executed the `skaffold dev` command. After a couple of seconds the `Hello George!` message started to appear.

Please let me know if you need any more information from my end.

**Comment by ahmetb** [comment]
@gtseres please open a new issue. your problem description doesn't seem to be what I reported, which is a Feature Request for detection of changes in "skaffold.yaml" file itself.

**Comment by gtseres** [comment]
Yeap, sorry for that. Didn't notice that you were talking about the `skaffold.yaml` file. Thanks.

**Comment by dgageot** [comment]
This is fixed with #620
