### ISSUE TITLE
googleCloudBuild fails when Dockerfile is in sub-directory

### ISSUE THREAD

**Issue by wstrange** [GoogleContainerTools/skaffold#1612]
I suspect this is the same issue as https://github.com/GoogleContainerTools/skaffold/issues/1611 

`skaffold build -p gcb` fails with:

`FATA[0000] build failed: building [gcr.io/engineering-devops/sk-ig]: uploading source tarball: uploading targz to google storage: creating tar gz: lstat /Users/warren.strange/tmp/forgeops-init/cicd/ig/docker/docker/Dockerfile: no such file or directory`

### Information

- Skaffold version: 0.22.0

- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-ig
    context: docker
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    path: overlays/gke
profiles:
  # This profile works for git commits, not for manually submitted cloud builds
  - name: gcb
    build:
      tagPolicy:
        gitCommit: {}
      googleCloudBuild:
        projectId: engineering-devops```

**Comment by dgageot** [comment]
Sorry. A fix is coming soon. Until then, you can rollback to using Skaffold v0.20.0.
