### ISSUE TITLE
Feature Request: Allow docker build arg to pick values up from the environment values also

### ISSUE THREAD

**Issue by rahulwa** [GoogleContainerTools/skaffold#1619]

**Comment by jomarinb** [comment]
I'm currently using `envsubst` as a workaround.

```
envsubst '\$ENV1 \$ENV2' < skaffold.yaml | skaffold run -f -
```

**Comment by balopat** [comment]
Hi @rahulwa can you provide more information about your use case?

**Comment by rahulwa** [comment]
I want to use same dockerfile for different environments (staging, production) [this case is easily handled through  skaffold profiles] and some variables are even different in same environment(like some base links in reacts assets, even though react supports these variables through environment, I cannot pass it through dockerfile because skaffold doesn’t handle it). Hope it makes sense.

Anyway if we are allowing environment variables for others configs, why not for this also?
It will provide consistency and intuitiveness.

**Comment by nkubala** [comment]
@rahulwa that sounds reasonable, it shouldn't be too difficult to plumb env vars through to the docker build args. would you be interested in sending a PR?
