### ISSUE TITLE
skaffold dev fails on COPY when targeting a certain stage by name

### ISSUE THREAD

**Issue by gbates101** [GoogleContainerTools/skaffold#1633]
### Expected behavior
`skaffold dev` should support COPY statements when building a multistage dockerfile at a certain target.

### Actual behavior
```
gbates@Work /mnt/c/Projects/Tartan/PlaidClient (master) $ skaffold dev
Starting build...
Found [minikube] context, using local docker daemon.
Building [plaidcloud/client]...
Sending build context to Docker daemon  3.333MB
Step 1/19 : FROM python:2.7 AS build-image-maps
 ---> 993072fdd9f8
Step 2/19 : RUN apt-get update  && apt-get install -y git  && pip install      jsmin      simplejson  && mkdir -p      /www/framework/jslib/resource      /www/PlaidClient/plaid/source/resource/plaid/
 ---> Using cache
 ---> 25becbe7da45
Step 3/19 : RUN curl -LO http://www.imagemagick.org/download/delegates/libpng-1.6.31.tar.xz  && tar -xf libpng-1.6.31.tar.xz  && cd libpng-1.6.31  && ./configure --prefix=/usr/local  && make  && make install
 ---> Using cache
 ---> 1e378ebfb7cb
Step 4/19 : RUN curl -Lo magic https://sourceforge.net/projects/imagemagick/files/old-sources/6.x/6.7/ImageMagick-6.7.8-10.tar.gz/download  && tar -xzvf magic  && cd ImageMagick-6.7.8-10  && ./configure  && make  && make install
 ---> Using cache
 ---> 5ab9487241d5
Step 5/19 : ENV LD_LIBRARY_PATH /usr/local/lib/
 ---> Using cache
 ---> f43eff5dfb35
Step 6/19 : RUN mkdir -p /www/framework/qooxdoo  && cd /www/framework/qooxdoo  && git init  && git remote add origin https://github.com/qooxdoo/qooxdoo.git  && git fetch origin master  && git checkout a3c2b0b5bd02867a1b41f44fbef26302574b5f17  && rm -rf .git
 ---> Using cache
 ---> cca444b95e49
Step 7/19 : RUN mkdir -p /www/framework/jslib/resource/fugue  && cd /www/framework/jslib/resource/fugue  && git init  && git remote add origin https://github.com/yusukekamiyamane/fugue-icons.git  && git fetch origin master  && git reset --hard FETCH_HEAD  && rm -rf .git
 ---> Using cache
 ---> 1fe0526100de
Step 8/19 : COPY plaid.conf /etc/plaid/
FATA[0004] exiting dev mode because first run failed: build failed: building [plaidcloud/client]: build artifact: COPY failed: stat /var/lib/docker/tmp/docker-builder864142084/plaid.conf: no such file or directory 
```

### Information
I upgraded from 0.21.1 to 0.22.0 hoping I could resolve some file globbing issue I'm having with defining my sync map (really wish there was better documentation on how it works), and my Dockerfile now fails to build on any COPY statement. I'm building and deploying to a local minikube cluster.

Troubleshooting steps I've taken:
- Commented out the COPY statement above. Build fails at the next COPY statement.
- Ran `docker build .`  from the same session in the same folder. Completes without issue. 
- Rolled back to 0.21.1. This fixes the issue.
- Ran a `docker system prune` to evict my image cache. Build still fails at first COPY statement. 
- **Removed the `target: source` declaration in my `skaffold.yaml` file. This fixes the issue.**

Skaffold version: **0.22.0**
Operating system: **WSL on Windows**
Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: plaidcloud/client
    sync:
      '*.js': .
    docker:
      target: source
  tagPolicy:
    envTemplate:
      template: plaidcloud/client:dev
deploy:
  kubectl:
    manifests:
    - kubernetes/*.yaml

```

### Steps to reproduce the behavior

1. Have a Dockerfile with COPY statements and named stages.
2. Target a specific stage using `target: <target-name>`  in the `docker` section of your `skaffold.yaml`
3. Build using `skaffold build` or `skaffold dev`

**Comment by dgageot** [comment]
@gbates101 this is fixed in master branch. Sorry for the regression. Until it's released, you can try v0.20.0
