### ISSUE TITLE
build sha256 artifact image without a tag pushes all tags

### ISSUE THREAD

**Issue by michaelfig** [GoogleContainerTools/skaffold#1638]
(The #1634 PR fixes this issue.)

### Expected behavior

When using the `sha256` `tagPolicy`, and supplying an artifact image without a tag, only the built artifact should be pushed:

```
Successfully built 16811c9a3d62
Successfully tagged michaelfig/skaffold-sha-latest:latest
The push refers to repository [docker.io/michaelfig/skaffold-sha-latest]
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
423678709065: Preparing
cd7100a72410: Preparing
423678709065: Waiting
cd7100a72410: Waiting
91295ee17337: Layer already exists
e3cf3bbc5223: Layer already exists
249c61ed1505: Layer already exists
47a91d4a2b2d: Layer already exists
951c1d7bace7: Layer already exists
cd7100a72410: Layer already exists
423678709065: Layer already exists
latest: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
Build complete in 2.814111067s
Starting test...
Test complete in 20.877µs
michaelfig/skaffold-sha-latest -> michaelfig/skaffold-sha-latest:latest@sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3```

### Actual behavior

Artifacts without a tag name push the entire image (all its tags):

```
Successfully built 16811c9a3d62
Successfully tagged michaelfig/skaffold-sha-latest:latest
The push refers to repository [docker.io/michaelfig/skaffold-sha-latest]
sha256:37352cb52fd6f3b823e187b530aaba2f2a3faf57b96e205895928aef0860a56a size: 1360
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
423678709065: Preparing
cd7100a72410: Preparing
423678709065: Waiting
91295ee17337: Layer already exists
423678709065: Layer already exists
951c1d7bace7: Layer already exists
cd7100a72410: Waiting
cd7100a72410: Layer already exists
e3cf3bbc5223: Layer already exists
249c61ed1505: Layer already exists
47a91d4a2b2d: Layer already exists
latest: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
423678709065: Preparing
cd7100a72410: Preparing
91295ee17337: Layer already exists
47a91d4a2b2d: Layer already exists
249c61ed1505: Layer already exists
e3cf3bbc5223: Layer already exists
cd7100a72410: Layer already exists
423678709065: Layer already exists
951c1d7bace7: Layer already exists
tagA: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
47a91d4a2b2d: Layer already exists
249c61ed1505: Layer already exists
951c1d7bace7: Layer already exists
e3cf3bbc5223: Layer already exists
423678709065: Preparing
cd7100a72410: Preparing
91295ee17337: Layer already exists
423678709065: Layer already exists
cd7100a72410: Layer already exists
tagB: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
47a91d4a2b2d: Layer already exists
423678709065: Preparing
cd7100a72410: Preparing
423678709065: Layer already exists
e3cf3bbc5223: Layer already exists
91295ee17337: Layer already exists
951c1d7bace7: Layer already exists
cd7100a72410: Layer already exists
249c61ed1505: Layer already exists
tagC: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
423678709065: Preparing
cd7100a72410: Preparing
951c1d7bace7: Layer already exists
423678709065: Waiting
249c61ed1505: Layer already exists
cd7100a72410: Waiting
423678709065: Layer already exists
91295ee17337: Layer already exists
cd7100a72410: Layer already exists
e3cf3bbc5223: Layer already exists
47a91d4a2b2d: Layer already exists
tagD: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
47a91d4a2b2d: Preparing
249c61ed1505: Preparing
e3cf3bbc5223: Preparing
951c1d7bace7: Preparing
91295ee17337: Preparing
423678709065: Preparing
cd7100a72410: Preparing
91295ee17337: Layer already exists
423678709065: Waiting
47a91d4a2b2d: Layer already exists
423678709065: Layer already exists
249c61ed1505: Layer already exists
e3cf3bbc5223: Layer already exists
cd7100a72410: Waiting
cd7100a72410: Layer already exists
951c1d7bace7: Layer already exists
tagE: digest: sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3 size: 1774
Build complete in 11.466732102s
Starting test...
Test complete in 8.966µs
michaelfig/skaffold-sha-latest -> michaelfig/skaffold-sha-latest@sha256:3007072f35e369bd5e8c6befb0facdd61f6ecdffae5695a792eeda37775722a3
```

### Information

- Skaffold version: v0.22.0-85-g19edc4ed
- Operating system: darwin-amd64
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: michaelfig/skaffold-sha-latest
```

- Contents of Dockerfile:

```
FROM scratch
```

### Steps to reproduce the behavior

1. Run `skaffold build` once.
2. Generate some tags for the image, by running:
```
for tag in tagA tagB tagC tagD tagE; do docker tag michaelfig/skaffold-sha-latest:latest michaelfig/skaffold-sha-latest:$tag; done
```
3. Run `skaffold build` again.

**Comment by dgageot** [comment]
Fixed with https://github.com/GoogleContainerTools/skaffold/pull/1634
