### ISSUE TITLE
Single exec command for sync

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1639]
### Expected behavior
Sync should only make one exec call per sync round

### Actual behavior
Sync makes a call per copy and a call per delete

### Information

Step 1: Bunch the delete operations into a single exec command
Step 2: Replace `kubectl cp` command with 

- Tar (in Go) all files-to-be-copied with the correct destination path
- Exec a single `cp sync.tar / && tar -xvf /sync.tar && rm /sync.tar` for all copies

Step 3 (maybe?): Combine delete and copy operations into a single large command

**Comment by michaelfig** [comment]
#1641 implements steps 1 and 2.

**Comment by corneliusweig** [comment]
@r2d4 Do you really think combining copy & delete (step3) would achieve much? It would not be trivial to combine both, because copy needs to read the tar from stdin, whereas delete does not. Probably not worth the complexity..

**Comment by r2d4** [comment]
Agreed @corneliusweig
