### ISSUE TITLE
Default repo substitution doesn't work with the examples

### ISSUE THREAD

**Issue by WoLfulus** [GoogleContainerTools/skaffold#1657]
### Expected behavior

Values from the examples matches the return value from `SubstituteDefaultRepoIntoImage` function

### Actual behavior

The last two examples doesn't return the same value.

Example 3 returns `gcr.io/k8s-skaffold/gcr.io/k8s-skaffold/skaffold-example1` instead of `gcr.io/k8s-skaffold/skaffold-example1`
Example 4 returns `gcr.io/k8s-skaffold/myimage/gcr.io/k8s-skaffold/skaffold-example1` instead of `gcr.io/k8s-skaffold/myimage/skaffold-example1`

Also, shouldn't `-` and `_` be accepted as a valid character here 
https://github.com/GoogleContainerTools/skaffold/blob/96ac37e30ee94b3f015a5eda14c7e7b1d99b0a34/pkg/skaffold/util/image.go#L28 

?

**Comment by balopat** [comment]
Thanks for filing the issue! 
What is your default-repo setting?

**Comment by WoLfulus** [comment]
I wasn't using skaffold at the time I saw this. I just compiled the code and invoked it with the given examples on the website.

I was trying to replicate the behaviour in JavaScript because I'm working on a project that needs the image name that matches what skaffold generates. BTW: It would be nice to have a way to specify the FQIN for each container (skipping taggers)

**Comment by nkubala** [comment]
@WoLfulus thanks for pointing this out. opened a PR to fix the regex.

**Comment by WoLfulus** [comment]
Thank you!
