### ISSUE TITLE
Skaffold v0.23 log tail unreadable

### ISSUE THREAD

**Issue by casret** [GoogleContainerTools/skaffold#1664]
### Expected behavior

During a skaffold dev, I should be able to see the log output.  Before 0.23 it was printing in black.  

### Actual behavior

Now, it is printing in a light color which is almost indistinguishable with my background (solarized light).  I tried passing --color 30, but that only affects some of the status messages, not the log output.

### Information

- Skaffold version: 0.23
- Operating system:  Mac OS

**Comment by dgoldssfo** [comment]
Me, too. Same problem.
