### ISSUE TITLE
Describe how to manually test configuration after build

### ISSUE THREAD

**Issue by soullivaneuh** [GoogleContainerTools/skaffold#1666]
I'm trying to handle #1665 right now, but I'm facing at a problem: What should I put on my `apiVersion` to make it working with my new one?

I tried `skaffold/latest`, `latest`, `*`... nothing work. And if I go back to the last version it simply ignore my new configuration field.

Maybe it's easier to know but it's not obvious for go newbies like me who want to add some little contributions... :wink: 

A note about that on the development doc would be great! :+1:

**Comment by priyawadhwa** [comment]
Hey @Soullivaneuh the current api version is `skaffold/v1beta5`, which should work if you're building @ HEAD.

Agree that some better documentation around this would be useful!

**Comment by nkubala** [comment]
should be fixed by https://github.com/GoogleContainerTools/skaffold/pull/1982
