### ISSUE TITLE
Get started doc should mention changing the `skaffold.yaml` to your own GCP project

### ISSUE THREAD

**Issue by incfly** [GoogleContainerTools/skaffold#1669]
https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/skaffold.yaml#L5

Uses a hardcoded gcp project, which will fail at client side when trying `Get Started` tutorial.

**Comment by briandealwis** [comment]
Maybe we should change the docs to use the `-d` option, and use it as an opportunity to explain how to push to alternative locations without having to amend the `skaffold.yaml`.

**Comment by balopat** [comment]
In fact `--default-repo` should be used. It is currently only explained here: https://github.com/GoogleContainerTools/skaffold/tree/master/examples
