### ISSUE TITLE
ZSH completion load: can only be called from completion function

### ISSUE THREAD

**Issue by Soullivaneuh** [GoogleContainerTools/skaffold#1671]
### Expected behavior

ZSH completion loading.

### Actual behavior

```
~ at ☸️  microk8s 
➜ source <(skaffold completion zsh)
_arguments:comparguments:325: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
```

### Information

- Skaffold version: v0.23.0
- Operating system: Linux sweethome 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Contents of skaffold.yaml: Not related.

### Steps to reproduce the behavior

1. `source <(skaffold completion zsh)`

**Comment by corneliusweig** [comment]
I guess that's my fault. I didn't realize that zsh completion was utterly broken in cobra, when I enabled it. Would a static zsh completion file be fine for the time being? There is an open PR in cobra which will fix this, but it's been quiet for some time now :(

**Comment by Soullivaneuh** [comment]
@corneliusweig Sorry for the respond time and thanks for the fix! As it works, it's already a good news! :+1:
