### ISSUE TITLE
Don't require reconnection during config change

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1695]

**Comment by balopat** [comment]
For Skaffold RPC config change requires a bit more thought: 
- on config change we shutdown the server? How will the IDE know that it needs to reconnect? Can we keep the server alive? I think that would be beneficial. 
- `ConfigurationChanged` probably should be another event

**Comment by dgageot** [comment]
It should be kept alive right now

**Comment by dgageot** [comment]
I'm going to close this issue. It was fixed with https://github.com/GoogleContainerTools/skaffold/pull/2382
