### ISSUE TITLE
Add Event API support for build/run/deploy

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1696]

**Comment by balopat** [comment]
Context: https://github.com/GoogleContainerTools/skaffold/pull/1574
Ideas to enable IDE integration for short lived commands: 

* flip the server/client roles - the caller of skaffold could pass in one (or more) RPC server endpoint(s) that Skaffold RPC could connect as a client to and _push_ notifications to. This connection step would be the first thing - and could ensure that build/deploy/delete/run send all the info required.
* `skaffold serve` - Maybe we could introduce a `skaffold serve` command that could then run _only_ the RPC server, and the client would be able to trigger different commands and listen to events. But that's a bigger implementation.

**Comment by balopat** [comment]
Another option: hold back execution until at least configured number of clients connected to the RPC server for `GetEvents()`

**Comment by tejal29** [comment]
Relates to #2912 
i think the first part is already done. 
@nkubala Can you assign priority for this feature (or close)? Are we planning to work on skaffold serve in next months.

**Comment by nkubala** [comment]
this is closed with the addition of both the event and control APIs.
