### ISSUE TITLE
Add `DeploymentCleanedUp` event to Event API

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1698]

**Comment by balopat** [comment]
It would be great to know on the IDE side when the deployment is cleaned up properly.

**Comment by tejal29** [comment]
@nkubala added this is p1. Feel free to change it to p0 if you plan to work on it this quarter.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
