### ISSUE TITLE
Detailed Event API  + Control API documentation on proto

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1703]
Will fix also #1954, #1511

**Comment by balopat** [comment]
cc @nkubala this would be great to have - at least the proto level comments. An example well document proto: https://github.com/grpc/grpc/blob/master/third_party/nanopb/generator/proto/plugin.proto

**Comment by balopat** [comment]
we can do the generation of a reference doc into skaffold.dev later or skip it.

**Comment by tejal29** [comment]
this is done now :)
