### ISSUE TITLE
Kaniko build and push to an insecure registry completes successfully but skaffold errors anyway

### ISSUE THREAD

**Issue by s-irvine** [GoogleContainerTools/skaffold#1705]
### Expected behavior

A Skaffold driven Kaniko build should complete successfully even if the image has been pushed to an insecure registry.

### Actual behavior

Skaffold errors on pulling the digest for the new image after it has been pushed. The image has been pushed successfully as it can be found in the registry but Skaffold assumes the registry uses HTTPS so the manifest pull fails:

```
2019/02/28 13:36:12 existing blob: sha256:33de1c244a6173453e6338c4b5624c09ea9da8307e4d2ad0eca7484877a687e9
2019/02/28 13:36:12 existing blob: sha256:ecf0544735d4b35d9ad53ce64e406b61981787f4467f519e739fc649da7ac284
2019/02/28 13:36:12 pushed blob sha256:329424ce3af3c9bc256cdd2786602d0063de98a8f3d1d1909dfc0b9056989009
2019/02/28 13:36:12 pushed blob sha256:01377b6fa7a813f16cf69467d3f837404e4cee53f84b730afddd213634714941
2019/02/28 13:36:12 pushed blob sha256:3bc2b080809e76fc3d26aeee84e4996f8886079d8c0e05b857e06db9ffa3c4be
2019/02/28 13:36:12 pushed blob sha256:84e43156444bcce1963218a06329fe4fb576f58732b4c0511d588bf404058275
2019/02/28 13:36:12 pushed blob sha256:ea5a02a830b8eb8a06f67af31f530a3c1930bc5ae3b7b53b8dc661e6566619c4
2019/02/28 13:36:12 <redacted-image>:latest: digest: sha256:81f1a446526840506ccb9172d8cebfbebbae8e3cdc91906c29bd7b7ceee26aad size: 1238
FATA[0044] build failed: building [<redacted-image>]: kaniko build for [<redacted-image>]: getting image: Get https://<redacted-registry>/v2/: http: server gave HTTP response to HTTPS client 
```
I get the exact same behaviour no matter whether my docker daemons (local and/or cluster) are configured to recognise that registry as insecure or not.

### Information

- Skaffold version: v0.23.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: <redacted-image>
  kaniko:
    buildContext:
      localDir: {}
    namespace: kaniko
    cache:
     repo: <redacted-image-cache>
    flags:
     - --insecure
    dockerConfig:
      secretName: docker-bot
deploy:
  kustomize:
    path: deploy/overlays/user-dev
```

### Steps to reproduce the behavior

1. Set up Kaniko to build an image for an insecure registry
1. Run `skaffold build`

**Comment by nkubala** [comment]
@s-irvine thanks for the issue. this is indeed a bug and we're looking into the right way to fix it. I know your issue was first, but there's a bit more discussion on #1732 and this is not a Kaniko-specific issue so I'm going to close this as dupe.
