### ISSUE TITLE
Flaky test for TestDev

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1711]
TestDev keeps flaking out with a timeout. We should fix it, it's demoralizing.

**Comment by nkubala** [comment]
The problem could be that we start up Skaffold, then immediately change a file to kick off a dev cycle, but Skaffold may not have had time to start up the watcher before we changed the file, so it never gets picked up and a rebuild/redeploy never happens.

**Comment by balopat** [comment]
Still failing: https://source.cloud.google.com/results/invocations/272de578-6f42-4afc-a960-919289372a80/targets/runtimes-common%2Fskaffold%2Fpresubmit/log

**Comment by dgageot** [comment]
I think I finally fixed it with #1750
