### ISSUE TITLE
Private registries in guest OS:es auth fails

### ISSUE THREAD

**Issue by haf** [GoogleContainerTools/skaffold#1714]
ref: https://github.com/GoogleContainerTools/skaffold/pull/1355

![screenshot 2019-03-01 at 15 21 55](https://user-images.githubusercontent.com/193115/53644005-cd7d8780-3c35-11e9-96e0-994746643adc.png)

**Comment by balopat** [comment]
Hi @haf - this issue is got stale - do you still see the problem? 
If yes, can you share how you're configuring the docker build in your `skaffold.yaml` (useDockerCLI:true/false or buildkit)? 
Thank you for your patience!

**Comment by haf** [comment]
Hi, I’m sorry but I’m no longer using minikube for this reason (and the startup issues it was having).
