### ISSUE TITLE
Running multiple instances of skaffold no longer possible

### ISSUE THREAD

**Issue by pre** [GoogleContainerTools/skaffold#1733]
### Expected behavior

Have two projects with `A/skaffold.yml` and `B/skaffold.yml`. 

Expected: running `skaffold dev` in both directories A and B would work. This used to work in an earlier version still in January 2019. 

### Actual behavior

Running `skaffold dev` for project A will work as expected, but `skaffold dev` for project B will fail.

The error message is: 

`FATA[0000] creating runner: creating runner: initializing skaffold event handler: creating status server: creating listener: listen tcp :50051: bind: address already in use`

### Information

- Skaffold version: fails with v0.24.0
- Operating system: MacOS Mojave
- Contents of skaffold.yaml: anything

### Steps to reproduce the behavior

1. Create A/skaffold.yml 
2. Create B/skaffold.yml
3. Run `skaffold dev` under A
4. Run `skaffold dev` under B
-> fails with `listen tcp :50051: bind: address already in use`  (this used to work still in January 2019)

**Comment by matti** [comment]
```
skaffold dev --rpc-port 50052
```
seems to work.

**Comment by tejal29** [comment]
cc @nkubala  who might have a better idea since this seems relevant to the Event API work he did.

**Comment by nkubala** [comment]
@pre thanks for the issue. I opened a PR that will fix this, but in the meantime you can use @matti's workaround to keep running skaffold.

**Comment by tejal29** [comment]
@nkubala Can you point us to the workaround? is it same as using --rpc-port flag?

**Comment by nkubala** [comment]
@tejal29 yeah specifying another rpc port fixes it. the previous logic to choose a new port if the provided/default one is already in use was busted.
