### ISSUE TITLE
sync is broken on local cluster

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#1734]
Sync is broken when images have not been pushed.

The code now tries to retrieve the remote image to check the working dir.
Because the image was never pushed, this fails hard.

**Comment by aasm-moura** [comment]
same here!

`FATA[0034] calling final callback: sync: retrieving working dir for hub-api:b5f8168bb1bc595174f01810d8e3cc47cf9bc22404b4253e2baf77baf63b83c1: retrieving remote config: UNAUTHORIZED: "authentication required"`

**Comment by ayyazzafar** [comment]
> same here!
> 
> `FATA[0034] calling final callback: sync: retrieving working dir for hub-api:b5f8168bb1bc595174f01810d8e3cc47cf9bc22404b4253e2baf77baf63b83c1: retrieving remote config: UNAUTHORIZED: "authentication required"`

@aasm-moura did you get any solution for this issue? I am also facing same problem.

**Comment by aasm-moura** [comment]
@ayyazzafar we have disabled the sync until the new skaffold release.

**Comment by paulohac** [comment]
Still facing the same issue with the latest release 0.24.0

**Comment by akatsero** [comment]
I'm encountering the same issue on 0.24.0.

**Comment by adrian-gl** [comment]
> I'm encountering the same issue on 0.24.0.

same me :(

**Comment by jasonwc** [comment]
Just ran into the same thing on edge:

```
> skaffold version
7152e30
```

```
