### ISSUE TITLE
How does Skaffold compares with Helm?

### ISSUE THREAD

**Issue by gsemet** [GoogleContainerTools/skaffold#174]
For example in gitlab we can automatize deployment from CI using helm, and it appears helm chart are becoming the defacto standard for reusing existing opensource component. Internally the question to use helm in our own internal application is still open, and I wonder if skaffold can make life simpler than helm (especially no need to have a Tiller installed on the cluster). How safe is it? Can it be templatized to differentiate between a staging env and a prod env, and so on.

Thanks

**Comment by viglesiasce** [comment]
Hey @gsemet!

Skaffold is a tool that wraps the workflow for building/pushing images and deploying to Kubernetes. One mode of operation, `skaffold dev`, is tailored for local iterative development. The other mode `skaffold run` is for one shot runs of the workflow which would be useful for running as a step in a CI process.

You can use Skaffold with Helm as the deployment mechanism. If you didn't need the added complexity of Helm (ie your manifests are relatively static) you could use Skaffold with `kubectl` directly.
