### ISSUE TITLE
flake: kaniko_local

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1746]
We need much better logging and error message and also determine what causes the flake: 

https://source.cloud.google.com/results/invocations/065518a2-8914-41b2-8a05-c2694218975c/targets/runtimes-common%2Fskaffold%2Fpresubmit/log

```
    --- FAIL: TestRun/kaniko_local (5.85s)
    	util.go:34: skaffold delete: exit status 1
```

**Comment by dgageot** [comment]
This test has not been failing for quite some time. Let's close this issue
