### ISSUE TITLE
Custom annotations for Kaniko pods?

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#1759]
### Feature request
It would be helpful to add custom annotations to Kaniko pods through skaffold.yaml. Does this seem like something Skaffold should support/would it seem like a welcome addition?

In general, it may also be nice to be able to specify labels and/or parts of the Kaniko pod spec as well, like resource usage. I know it's possible to attach default resource request/limits to pods in a namespace, but granular resource requests within a single namespace would be helpful

**Comment by tejal29** [comment]
@tbarrella want to know more what would this custom annotations be used for?

**Comment by tbarrella** [comment]
This came to mind for me specifically to specify IAM roles for Kaniko pods using kube2iam or kiam. Potentially if https://github.com/GoogleContainerTools/skaffold/issues/731 were resolved, credentials could be provided via `kaniko-secret`, although I'd prefer avoiding creating and distributing those credentials

I didn't think too hard about how else they might be used

**Comment by jorgex1** [comment]
This would be really useful :heart:

**Comment by pbecotte** [comment]
I don't see any way to really customize anything about the pod that kaniko runs in? We need annotations for kiam + ecr to to work - but will also need things like overriding the image (no public internet access), tolerations, node selectors... is there a way to do stuff like this that I am just missing?

**Comment by rlangfordBV** [comment]
Count me in as someone who wants this for `kiam` + `ecr`

**Comment by nkubala** [comment]
I think this would be useful, but our team doesn't have the bandwidth to work on this any time soon. contributions certainly welcome though!
