### ISSUE TITLE
Wait for deployed resources to reach their intended state 

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#176]
In the case of `skaffold run` there are times where you will want to ensure that the resources that were deployed have reached their intended state. For example, after applying a change to a deployment you will want to check the rollout status and ensure that it completed successfully. This would most likely be the mode you would want when running in a CD pipeline.

**Comment by Place1** [comment]
I'd be happy to put up a PR that adds `rollout status` support for the kubectl deployer

**Comment by balopat** [comment]
cc @tejal29

**Comment by tejal29** [comment]
@Place1 Thank you for helping us out. I am working on a PR #2750 which does implement kubectl rollout

**Comment by Place1** [comment]
Oh fantastic. Looks like your pr is doing what’s needed. Nice one.

**Comment by tstromberg** [comment]
Closing as I believe this to be fixed.
