### ISSUE TITLE
annotated-skaffold.yaml missing since v0.24.0

### ISSUE THREAD

**Issue by sniederm** [GoogleContainerTools/skaffold#1768]
### Expected behavior

The best docs reference to the skaffold.yaml was in https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml 

### Actual behavior

Since tag v0.24.0 this file is gone, but a lot of external resources refer to this location. All of them now get a 404. And its not clear where the reference documentation now can be easily found.

You should leave the file there and refer to the new documentation location (hopefully if there is any). At least for some time.

**Comment by dgageot** [comment]
Hi @sniederm, this piece of documentation has been moved to https://skaffold.dev/docs/references/yaml/

I'm going to push an empty `annotated-skaffold.yaml` with this information
