### ISSUE TITLE
Changelog Generator

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#178]
Does anyone know of any good changelog generation tools? We should automate ours for ease of release as well as consistent formatting. It shouldn't be that hard to roll our own, but I'd rather use something that already exists.

Any suggestions?

**Comment by nouney** [comment]
WDYT of https://github.com/goreleaser/goreleaser?

**Comment by jstrachan** [comment]
Incidentally we just went through a similar exercise recently; we tried a few tools and were not totally happy with the generated changelogs. In particular we wanted to allow folks to use https://conventionalcommits.org/ to get nicer formatted changelogs; but still permit any commit message format too and to try gently nudge folks into nicer commit messages/changelogs.

So we ended up creating a little CLI tool in go to create the changelogs and create/update the github release. You can download a binary and see the generated changelogs here:
https://github.com/jenkins-x/jx/releases

We're using it in our release pipeline here:
https://github.com/jenkins-x/jx/blob/master/Makefile#L97

Command line help:
http://jenkins-x.io/commands/jx_step_changelog/

**Comment by r2d4** [comment]
Fixed in https://github.com/GoogleContainerTools/skaffold/pull/662
