### ISSUE TITLE
test bug: Cache test depends on global config

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1794]
### Expected behavior
The test should be independent of any global configuration settings.

### Steps to reproduce the behavior
0. `git checkout master`
1. `skaffold config set local-cluster -k cluster1 true`
2. `go test github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache`

**Comment by dgageot** [comment]
This was fixed by #1788
