### ISSUE TITLE
Official DockerHub/GCR image

### ISSUE THREAD

**Issue by Trane9991** [GoogleContainerTools/skaffold#180]
Would be nice to have official DockerHub/GCR repo, where ready to use Image can be pulled to use with docker based CI systems (GitLab CI, Bitbucket Pipelines, etc.)

**Comment by r2d4** [comment]
This is something we're actively working on, but we haven't published anything yet

https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/42

https://github.com/GoogleCloudPlatform/skaffold/blob/master/deploy/skaffold/Dockerfile

**Comment by r2d4** [comment]
This is published at gcr.io/k8s-skaffold/skaffold

Available tags are:
- any commit SHA
- "latest" for HEAD
- any tag (v0.8.0, etc.)

**Comment by r2d4** [comment]
See https://github.com/GoogleContainerTools/skaffold/blob/master/docs/published-artifacts.adoc for more info
