### ISSUE TITLE
support releasing a chart to a chart repository / chart museum

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#183]
It would be nice to support releasing versioned helm charts. e.g. if someone did:

```
skaffold run -f skaffold.yaml -t 1.23
```
then with the right `skaffold.yaml` it could modify the local `values.yaml` of the chart with the image tag `1.2.3`, lint & build the helm tarball and post it to some chart museum repository - so that anyone could then use `1.2.3` of the chart - or if they'd installed the chart they could run `helm update` etc.

I guess releasing a helm chart to a chart repository could be considered a kind of `deploy` or should we add another kind of step to the yaml like  `release` or `package` step?

Am happy to submit a PR if noone fancies contributing this; I just wanted some feedback on where folks felt this should fit (and if it should fit at all ;) before I dive in.

**Comment by nkubala** [comment]
Hey @jstrachan, sorry this never got much attention. I'm not sure this fits into skaffold's design paradigms at least right now. It doesn't have any analogues for the other deploy strategies (what would a `skaffold release` or `skaffold commit` look like for kubectl, or GCB?), and I'm not sure we want to add anything helm-specific. Is this something that you're still actively interesting in seeing in Skaffold?

**Comment by balopat** [comment]
I think this is not entirely out of scope - given that we share the artifacts through pushing - helm charts publishing could be another type of CI/CD use case. It would be great to see if anyone else is interested in this in the community to bump the priority.

**Comment by nkubala** [comment]
realistically, I don't think our team is going to get to this one any time soon, so I'll close it. that said, if anyone is interested in submitting a design and implementation for this, we'd be open to considering it.
