### ISSUE TITLE
Sync: subtree sync needs documentation

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1837]
### Information
PR #1813 introduced the triple-star syntax for the sync map:
```
sync:
  'foo/***/*.js': /usr/src/app/
```
Its purpose is to recreate the directory structure under foo at the destination (see also #1807).

This feature needs some documentation. But where should it be documented?

**EDIT** The syntax may be changed. See #1844 and #1847.

**Comment by balopat** [comment]
well - the best place would be https://skaffold.dev/docs/how-tos/filesync/ but it's lacking a bit of documentation still :)

**Comment by balopat** [comment]
Also, I'm not fully convinced about triple star just yet...it's so non-standard...not that globs have any kind of standard (especially with docker's lack of ability to do preserved subtrees https://github.com/moby/moby/issues/15858), but I feel like we are adding to the confusion with triple star.

**Comment by corneliusweig** [comment]
Should be put on hold until #1844 is settled.

**Comment by tejal29** [comment]
@balopat dont' worry @corneliusweig  is taking that in to consideration in the design proposal something we can discuss later.

**Comment by tejal29** [comment]
Sorry, closed by accident

**Comment by pulse14** [comment]
Is there a way to do sync subtrees with v0.25.0 ?

**Comment by corneliusweig** [comment]
> Is there a way to sync subtrees with v0.25.0 ?

@pulse14 Yes, as of v0.25.0 you can do for example
```
sync:
  'src/***/*.py': dest/
```
This will sync all py-files below `src` and recreate the folder structure _below_ `src` at `dest`. The syntax might change in future.

**Comment by 747823** [comment]
@corneliusweig That syntax does not work for me in v0.25.0, the files are all copied to the root of the dest folder without the folder structure preserved. Is there a separate issue open for this?

**Comment by pulse14** [comment]
I agree. I have `'packages/server/***/*.js': ./`. The container workdir is `/app/packages/server/`. 
When I edit `packages/server/src/index.js` it syncs it to `/app/packages/server/index.js`.
When I edit `packages/server/src/somefolder/somefile.js` it triggers a rebuild.

**Comment by 747823** [comment]
@pulse14 @corneliusweig Nevermind, I see that the pull request to add `***` was only merged after v0.25.0 was released. Maybe update your comment to say that you will be able to do that in the next release.

**Comment by corneliusweig** [comment]
@747823 :man_facepalming: you are right, sorry for that confusion!

**Comment by casret** [comment]
I'm really curious about what the use case is for the current way ** works?  I just don't see when you would want to flatten out a directory like that.

**Comment by corneliusweig** [comment]
@casret As discussed in #1844 the flattening will most likely be fixed with some other sync improvements ;)

**Comment by corneliusweig** [comment]
Superseded by #1994
