### ISSUE TITLE
Event API v2

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1854]
This is a design proposal for a redesign of the skaffold event API. The goal here is to retain 100% of the functionality that already exists in skaffold, while make the code significantly cleaner and easier to maintain.

Currently there are two major pain points with the event API:
1) calling code is clunky, ugly, and not very portable
2) event handler is racey and generally not concurrency-friendly

The second issue here comes more from bad execution rather than bad design. Some fixes for this have already been proposed and/or merged (#1786 and #1801), so progress has already been made, but we can probably improve on this more. 

The first issue is what I'll be focusing on in this issue. @dgageot has already merged one improvement to the design [here](https://github.com/GoogleContainerTools/skaffold/pull/1829), but this is only improving on an already flawed design. My goal for this redesign will be to reduce and potentially eliminate the overhead the event API has on maintainers and contributors to continue evolving the skaffold codebase.

Right now, events are handled directly through the main loop for each builder and deployer. The internal state is directly updated through the the individual builder/deployer, and anyone adding a new one is responsible for ensuring that these events are passed to the event handler correctly. Example:

https://github.com/GoogleContainerTools/skaffold/blob/e8ba04530b9849bacc40539c00688f4a6da6bacd/pkg/skaffold/build/sequence.go#L46-L51

https://github.com/GoogleContainerTools/skaffold/blob/e8ba04530b9849bacc40539c00688f4a6da6bacd/pkg/skaffold/deploy/kubectl.go#L72-L88

Even though the event handling functions have been reduced to one line, the fact that they still have to be manually called from the build or deploy code is a lot of overhead for contributors, especially people who are considering adding a new builder and deployer.

Every build or deploy that skaffold performs always comes through the runner, so it would make sense that the runner could handle all of the eventing for builds and deploys, as long as it can retrieve the necessary information from the builder or deployer.

* For deployers, this is easy: we just need to know whether or not the deploy completed successfully, and if not, what the error encountered was. This is already passed back to the runner.

* For builders, it's a little less straightforward. For **each artifact**, we'll need to know whether or not the build was successful, and if not, the error encountered. Currently, the `Build()` interface returns a single error back to the runner, containing information about the *first unsuccessful build* that it saw during the build process. Based on this, if we were building two artifacts, and one completed while the other failed, the runner has know way to know this, and assumes both failed to build.

To address this, I propose that we **change the `Build()` interface to return a list of build results, one for each artifact, with information about the original artifact skaffold attempted to build, and either the built artifact, or the error the builder encountered.**

This will allow the runner to
* know which artifacts were built successfully, and which failed
* log events for each artifact, complete with a detailed error message passed back from the runner in the event that the build didn't complete successfully

With this information, we could move all of the event handling code into a decorator that we wrap the builders and deployers in during the creation of the runner, similar to the way we handle timings currently. The semantics for each event (`In Progress`, `Complete`, `Failed`) should all be the same between builders and deployers, and we can share the logic for handling each of these events in a separate location. This has the added bonus of **not requiring any event-related code to be written by contributors** if/when they add new builders/deployers, or make changes to existing ones.

**Comment by corneliusweig** [comment]
Sounds much cleaner, but it is not completely equivalent. For example, artifact build currently also emits an `InProgress` event just before starting a build. In your new approach, this will no longer be possible, because events are emitted in the caller once all builds are complete. Therefore: has the `InProgress` event a relevant use-case?

**Comment by nkubala** [comment]
@corneliusweig thanks for the feedback. `InProgress` should still be covered by the runner, whenever a build is kicked off it will trigger the event. Then it will handle the event triggering for each build artifact once the builds are complete. see https://github.com/GoogleContainerTools/skaffold/pull/1949 for a more detailed explanation
