### ISSUE TITLE
Provide an api to get the supported build and deploy types

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#1859]
As the build type for the default profile defaults to local when no build types are specified, it is hard to figure out whether the build type is local or if a new build type is added.

Ex: Lets say in the future, a new build type 'abc' is introduced along with local, googleCloudBuild and kaniko. How do we figure out if the build type is abc or its defaulted to local?
build:
   abc: {}

Can we have an api to get the currently supported build and deploy types?

**Comment by balopat** [comment]
interesting idea - wouldn't the schemas help? do we really need to implement an API for this?

**Comment by sujit-kamireddy** [comment]
I think the problem will persist with the schemas as well. How can we differentiate between a build type such as local, googleCloudBuild, abc (a new build type) vs some property on build by looking at the schema?

**Comment by sujit-kamireddy** [comment]
I find the buildType property in the schema can be used for this purpose. Thanks.
