### ISSUE TITLE
Use env variables provided by CI systems

### ISSUE THREAD

**Issue by Trane9991** [GoogleContainerTools/skaffold#187]
All CI system provides git info in the env variables. I guess it makes sense to define the list of most common ones and use them to build image tag.

For example:
- [CodeShip](https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#default-environment-variables): `CI_BRANCH` and `CI_COMMIT_ID`
- [GitLab](https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables): `CI_COMMIT_REF_NAME` and `CI_COMMIT_SHA`
- [BitBucket Pipelines](https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html): `BITBUCKET_BRANCH` and `BITBUCKET_COMMIT`
- [TravisCI](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables): `TRAVIS_BRANCH` and `TRAVIS_COMMIT`
- [CircleCi](https://circleci.com/docs/1.0/environment-variables/): `CIRCLE_BRANCH` and `CIRCLE_SHA1`
- [SemaphoreCI](https://semaphoreci.com/docs/available-environment-variables.html): `BRANCH_NAME` and `REVISION`
- and more
Links above leads to the Env variables documentation for specific CI system.

**Comment by dlorenc** [comment]
Nice idea! We've talked a bit about an "environment variable" tagger that would let you specify a template that we'd run the environment variables through to generate a tag.

Would that meet the use case here?

**Comment by Trane9991** [comment]
Yep, I think that would do!

**Comment by r2d4** [comment]
Yep, we have the environment variable tagger that @dlorenc mentioned
