### ISSUE TITLE
[Idea] Track retries/sleep in skaffold integration tests.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#1880]
In PR for fixing flakes, i saw we increased the [number of retries](https://github.com/GoogleContainerTools/skaffold/pull/1860/files/cf948314638783119949d448bd5ead6596b22143#r268897376).
Retries are great, but sometimes they mask unstable code.
We should try and collect metrics when such re-tries happen or increased sleep. It could be a good way to understand code unstability.

**Comment by balopat** [comment]
I'm down for this but I think we need more understanding if it's worth it: instability in our code vs in the  the test setup / infrastructure (i.e network errors)?
Can you dig in a bit deeper here to explain what are the risky cases you would like to mitigate?
