### ISSUE TITLE
Add 'skaffold watch' command

### ISSUE THREAD

**Issue by bartdeboer** [GoogleContainerTools/skaffold#1890]
It would be nice if we could run the build and watcher separately ('skaffold dev' but without the build step using a previously built image). This would also allow for custom deploy scripts before hooking the watcher into it:

```
skaffold build
./my-custom-deploy-script
skaffold watch
```

**Comment by tejal29** [comment]
@bartdeboer Sounds like you want pull in some code which is not part of your local development? Is that true?
If not, can you provide an example of what the the custom deploy script looks like?

Right now, we need more information in order to decide if this should be part of skaffold.

**Comment by casret** [comment]
Even without the custom deploy script use case, it would be great to separate the activities of deploying, watching/syncing and destroying.  I hit a situation where I have to restart `skaffold dev` every day and then having it stop and restart the environment is painful (especially if there are some very expensive builds that happen only when you first start up).  Some examples:
- When changing networks, skaffold will die or get into a bad state.
- Port forward will sometimes just drop (or use a different number).
- If pods die, sometimes skaffold won't tail logs any more.

**Comment by bartdeboer** [comment]
@tejal29 In my particular use case I was experimenting with my own dynamic yaml solution where parameter placeholders get replaced (a poor mans version of kustomize). I would like to standardize some of my deployment configurations and be able to reuse them for different projects. I was also trying to include my own custom tagging scheme. It seems this is currently only possible if the dynamic system is supported by skaffold (for example like kustomize).

It would be nice if these concerns could be separated somehow. So I could use something else like kustomize. I understand skaffold most likely needs to add some magic to keep track of those images it is managing (for sync etc).  It's probably the reason why the build and watch are currently integrated.

For me it's a nice to have. I have the feeling it might be more elegant and solve some other complexities?

**Comment by balopat** [comment]
>  having it stop and restart the environment is painful (especially if there are some very expensive builds that happen only when you first start up)

To alleviate the build pain - did you try `--artifact-cache=true`? 

> * When changing networks, skaffold will die or get into a bad state.
This is interesting, can you elaborate? 

> * Port forward will sometimes just drop (or use a different number).
Yeah, port forward is a bit unstable still, we will actively work on fixing this this quarter :/ 

> * If pods die, sometimes skaffold won't tail logs any more.
This should be a separate issue opened up as well, very useful feedback!

**Comment by balopat** [comment]
I would be wary of opening up Skaffold to become a generic file-watcher - that can introduce a flood of use cases that we don't necessarily want to support, also I think all the pain you mentioned are real issues - we should fix those rather than creating an escape route.

**Comment by tjk** [comment]
> To alleviate the build pain - did you try `--artifact-cache=true`?

It looks like the option is actually `--cache-artifacts`... why isn't this enabled by default?

**Comment by nkubala** [comment]
@tjk we didn't enable it by default because the feature is relatively new, so we wanted to give it some time to work out the kinks. it will likely become the default in the (potentially near) future.

**Comment by casret** [comment]
--cache-artifacts does help quite a bit (70 seconds to 10, though doesn't seem to work with jib).

The network problem thing is if I'm connected to my cluster over wired and I unplug, or if I have to switch wifi networks, skaffold will stop.  Our setup is slightly non-conventional in that we use GKE in development as well.

**Comment by tejal29** [comment]
@bartdeboer Thank you for opening this issue. 
We would definably want a good user experience story around:- 
-  When changing networks, skaffold will die or get into a bad state. 

However, i am not sure if implementing it through a `skaffold watch` command is the solution.


Regarding port-forwarding: 
This quarter in skaffold version 0.34 onwards we have a done a bunch of changes to port-foward to make it stable. @priyawadhwa Can we also do some manual testing to see what happens when 
users run `skaffold dev` and then looses internet connectivity and it comes back again.
Maybe we should track this scenario of "skaffold should recover by itself when user  internet connection is intermittent" as a new feature issue #2698



Right now, the team does not see this fit. i am closing this.
