### ISSUE TITLE
Ctrl-C on Windows does not perform cleanup

### ISSUE THREAD

**Issue by hach-que** [GoogleContainerTools/skaffold#1907]
### Expected behavior

Ctrl-C should cleanup resources when Skaffold exits.

### Actual behavior

Ctrl-C just causes Skaffold to exit immediately.

### Information

- Skaffold version: version v0.26.0
- Operating system: Windows 10
- Contents of skaffold.yaml: n/a due to private work, but this should replicate on any skaffold.yaml

### Steps to reproduce the behavior

1. `skaffold dev --port-forward=false`
2. Hit Ctrl-C
3. Observe cleanup not happening

**Comment by dgageot** [comment]
Hi @hach-que, I've just tested it on Windows and it does the cleanup. Have you tried a more recent version of Skaffold?

**Comment by dgageot** [comment]
I'm going to close this issue because it seems to work as expected
