### ISSUE TITLE
Improve documentation on port forwarding

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#1916]
https://skaffold.dev/docs/how-tos/portforward/ only has minimal documentation on how port forwarding is done by skaffold. we should expand on this to detail

* how skaffold chooses ports
* when port forwarding is done
* how to disable/enable it
* where skaffold tracks open ports
* add info about how port forwarding works in getting started documentation

ref #1076

**Comment by priyawadhwa** [comment]
Done in #1311, #2353 , and #2336.
