### ISSUE TITLE
`yamltags.ProcessStruct` is insufficient

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1920]
### Information
`yamltags.ProcessStruct` was intended to set defaults in the schema and validate tags such as `required` and `oneOf`. However, in its current shape, it only processes structs and child fields which are structs. This means that config fields of kind `slice` or `Ptr` are not processed. This means that validation of `yamltags=required` is currently broken.

This is also the reason why it appeared that Skaffold did not validate `oneOf` tags at all (#1836 & #1881). I tried to fix this and recurse into arrays&pointers as well, but it seems there is a fundamental problem here. The reason why it cannot work is that `ProcessStruct` tries to set default values, however if we include slices here, we would try to set a value in a non-addressable value (you can play around with this [yamltags-patch.txt](https://github.com/GoogleContainerTools/skaffold/files/3043099/yamltags.txt)).

### Proposal
- I checked if `yamltags=default` is being used at all and I didn't find anything. My suggestion is therefore to remove `yamltags=default`, unless somebody comes up with an idea how to fix this. Thus, `yamltags.ProcessStruct` should only do validation.
- `yamltags.ProcessStruct` is a much cleaner code than `validation.ValidateSchema`. However, validation needs to be done after applying Skaffold config profiles (cmd/skaffold/app/cmd/runner.go:35). I therefore suggest to keep `validation.ValidateSchema` but use the validation implementation from `yamltags.ProcessStruct`. This will ensure that we also have a place to add new validation requirements which has nothing to do with `yamltags`. 

I'm happy to submit a PR for this, if you agree with that proposal.

**Comment by nkubala** [comment]
@corneliusweig this seems fine to me, as long as we're pretty confident nobody is trying to use `yamltags=default`. how did you check to see if it's being used? validation is the more important part of this anyway.

**Comment by corneliusweig** [comment]
@nkubala I checked using regexp, for example `git grep 'yamltags.*default'`. This only yields matches in the tests :)
Yeah, and validation is pretty broken right now, because `required` is not validated.

**Comment by nkubala** [comment]
👍 sounds good! PR definitely welcome :)
