### ISSUE TITLE
Sync does not work for Skaffold-Jib

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#1921]
For Maven and Gradle, `src/main/resources` is a standard location for placing static files.  But attempting to enable sync files from `src/main/resources` fails with Skaffold+Jib. 
```diff
+    sync:
+      'src/main/resources/**': '/app/resources'
```

### Expected behavior

The `README.md` file should be sync'd.

### Actual behavior

I have `~/go/src/github.com/GoogleContainerTools/skaffold` linked to `~/Projects/GPE/repo-skaffold`, and normally do my builds from `~/Projects/GPE/repo-skaffold`.

With `skaffold dev`, a change to a file with a sync rule will fail with:
```
FATA[0094] calling final callback: sync: intersecting sync map and added, modified files: changed file /Users/bsd/go/src/github.com/GoogleContainerTools/skaffold/examples/jib/src/main/resources can't be found relative to context .: Rel: can't make /Users/bsd/go/src/github.com/GoogleContainerTools/skaffold/examples/jib/src/main/resources relative to . 
```

### Information

The Jib builder's `GetDependencies` works by invoking an internal Jib build goal (`_skaffold-files` on Maven, `_jibSkaffoldFiles` on Gradle) that returns the build files and directories to source files.  The Jib Builder then expands the source directories to return the contents.

In digging into the problem, there are two issues:
  1. When expanding the paths returned by Jib's `skaffold-files`, `getDependencies()` returns both files and directories.  In the example below, the binding returns the directory `src/main/resources` and its contents `src/main/resources/README`.  But the directory doesn't match a sync-rule and so the attempt to sync fails.  
  1. The Jib's `skaffold-files` goal returns absolute canonical paths (where symlinks are expanded), which can be a problem when the context is actually in a symlinked directory (either itself or the parent) as neither `filepath.Abs()` nor `filepath.Rel()` expand symlinks.  So the attempt [in `sync.go`'s `intersect()` to relativize the paths fails](https://github.com/GoogleContainerTools/skaffold/blob/b1dce640bd28bbf80f4097c5eb04ae3531f11628/pkg/skaffold/sync/sync.go#L142).

### Steps to reproduce the behavior

1. `mkdir examples/jib/src/main/resources`
2. `cp README.md examples/jib/src/main/resources/`
3. Apply the following diff to add a sync rule.
4. `cd examples/jib; skaffold dev` and then make a change to `src/main/resources/README.md`

```diff
--- a/examples/jib/skaffold.yaml
+++ b/examples/jib/skaffold.yaml
@@ -4,6 +4,8 @@ build:
   artifacts:
   - image: gcr.io/k8s-skaffold/skaffold-jib
     jibMaven: {}
+    sync:
+      'src/main/resources/**': '/app/resources'
 
 # optional profile to run the jib build on Google Cloud Build
 profiles:
```

### Proposed Fix

Fixing Problem 1 is straightforward: fix Jib's [`getDependencies()`](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/jib/jib.go#L70) to only return files.

I can fix Problem 2 by processing changing Jib's `getDependencies()` to apply `filepath.EvalSymlinks()` to the context directory prior to relativizing the files.  But the code in `sync.go`'s `intersect()` looks like it's trying to handle absolute files anyways.  Perhaps I should push this expansion here?

https://github.com/GoogleContainerTools/skaffold/blob/b1dce640bd28bbf80f4097c5eb04ae3531f11628/pkg/skaffold/sync/sync.go#L135-L142

**Comment by corneliusweig** [comment]
@briandealwis I encountered a similar problem in https://github.com/GoogleContainerTools/skaffold/pull/1905#issuecomment-478973309. This seems to be a general problem when working with absolute paths out of different sources (jib/Skaffold here, git/Skaffold in my case). However, Skaffold's convention for absolute paths is to use `filepath.Abs()` which does not expand symlinks. I think we should try to stick with that convention. Therefore, I think it would be preferable to apply the `filepath.EvalSymlinks()` only for relativizing in Jib's `getDependencies()`.

**Comment by briandealwis** [comment]
I agree @corneliusweig.  Usually symlinks aren't expanded, so `filepath.Abs()` is the right thing.
