### ISSUE TITLE
Enable contributors to run integration tests locally/on their projects

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1925]
Except for the cloud specific tests - e.g. GCB builder - most of the integration tests should be runnable on a minikube + docker setup. It would be very useful for all of these to be moved off of GKE clusters so that contributors can run them too locally or potentially even on travis.

**Comment by tejal29** [comment]
@balopat  this can be part of the OKR Epic.

**Comment by dgageot** [comment]
I don't understand. It's currently the case.

**Comment by balopat** [comment]
@dgageot - which part is the current case? 

1. if we can run integration tests locally with minikube then we should document it clearly in the development.MD, currently it says: 
```
Integration tests
The integration tests live in integration and run the examples as tests. They can be run with:

make integration-test
These tests require push access to a project in GCP, and so can only be run by maintainers who have access. These tests will be kicked off by reviewers for submitted PRs
```
I guess you can set the default-repo to yours and that would push to wherever - but I would be surprised if everything would be seamless - maybe I'm wrong - can you shed some light on how to run `make integration` on minikube if you are already doing it? 
2. travis and appveyor tests are currently not running integration tests.

**Comment by nkubala** [comment]
setting the default-repo to your own and pointing kubectl to your cluster allows you to run integration tests locally no problem. i've been doing it for months. i'm confused what the problem is here?

**Comment by balopat** [comment]
This would be more about documentation than anything then. 
The last time I ran it on minikube it failed. I'll try this out again and report back.
