### ISSUE TITLE
Add a bot to close issues with low activity

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1929]

**Comment by corneliusweig** [comment]
Can we have a special label that the bot assigns to issues it closes automatically? That way we can easily search for auto-closed issues.

**Comment by nkubala** [comment]
+1 for that suggestion.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
