### ISSUE TITLE
[epic] Redesign default-repo behavior

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1930]
Based on user feedback the default-repo behavior is confusing, for example the prefixing logic creates surprising image names that people care about and underscore replacement might lose structure that people are interested in.

This issue is an epic that represents the work to redesign the default-repo behavior: 
- collect requirements / user feedback 
- create design proposal 
- implement the design

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
