### ISSUE TITLE
Automate the CGO=1 binary release 

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1936]

**Comment by corneliusweig** [comment]
I'm curious: why is CGO the better option here?

**Comment by nkubala** [comment]
@corneliusweig using CGO in our binaries allows us to use the `fsnotify` watch trigger, which is orders of magnitude faster in some cases (particularly projects with lots of files).

https://github.com/GoogleContainerTools/skaffold/pull/2213 will make this trigger the default for skaffold
