### ISSUE TITLE
Create an ImageManager type

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1943]
With `insecureRegistries`, `prune` we solved plumbing through configuration through arguments of one-off methods that are scattered around the codebase. These should be collected into an `ImageManager` that can handle and retrieve image information may it be on the local daemon or remote registry. 

* Probably this should be instantiated at the beginning in the runner. 
* Probably `skaffold debug` when retrieving image config can benefit from this as well. 

We have to be mindful sharing docker client across multiple processes though.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
