### ISSUE TITLE
Only send the build context for changed files to the Docker daemon

### ISSUE THREAD

**Issue by TheOriginalAlex** [GoogleContainerTools/skaffold#195]
Currently, the full  build context is being sent to the minikube Docker daemon whenever a change is made.  It'd be cool if we could somehow make it more intelligent by only sending files for the stages that are not cached/will need to rerun with the changes made.

**Comment by mumoshu** [comment]
FYI: Perhaps the recent improvement in docker for [sending build context incrementally](https://github.com/moby/moby/issues/31829) would help.

**Comment by dgageot** [comment]
Since docker v17.07, there's an experimental `--stream` flag that caches the context on the daemon side. We could try to leverage this flag.

**Comment by dlorenc** [comment]
AFAICT the incremental upload API is still very experimental: https://docs.docker.com/engine/api/v1.36/#operation/Session
https://github.com/moby/moby/pull/32677

and requires the daemon be started with specific flags.

**Comment by mumoshu** [comment]
@dlorenc Thx for the info! Just started playing with it:

```console
$ minikube delete && minikube start --memory 4096 --cpus 2 --docker-opt experimental
$ eval $(minikube docker-env)
$ DOCKER_API_VERSION=1.31 docker version
Client:
 Version:	18.02.0-ce
 API version:	1.31
 Go version:	go1.9.4
 Git commit:	fc4de44
 Built:	unknown-buildtime
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.09.0-ce
  API version:	1.32 (minimum version 1.12)
  Go version:	go1.8.3
  Git commit:	afdb6d4
  Built:	Tue Sep 26 22:45:38 2017
  OS/Arch:	linux/amd64
  Experimental:	true
$ DOCKER_API_VERSION=1.31 docker build --help | grep stream
      --stream                  Stream attaches to server to negotiate build context
```

**Comment by bhack** [comment]
What about a direct file sync phase like https://github.com/vapor-ware/ksync?
Sometime run on the remote cluster is mandatory cause specific resource. So the "build only" approach can create too much lag.

**Comment by dlorenc** [comment]
This is how we could do it with GCB: https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher

**Comment by dgageot** [comment]
Let's close this one. It's possible to enable this feature by using `useDockerCLI:true` on the local builder and #568 is here to implement that in the GCB builder
