### ISSUE TITLE
Add documentation for non-standard local setups

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1957]
### Current situation
Skaffold has a great out-of-the box experience for standard local setups, such as `minikube` and `docker-for-desktop`. However, when somebody leaves the standard path, there are some steps to take that new users may struggle with (e.g. #1205).

### Example
When using minikube with a profile:
1. Start minikube with `minikube start -p my-custom`
2. Set up docker env on host to use the minikube instance with `source <(minikube docker-env -p custom)`
3. Configure the context as local `skaffold config set -k my-custom local-cluster true`

### Where?
Maybe https://skaffold.dev/docs/tutorials/, WDYT?

**Comment by balopat** [comment]
This sounds great! How about a "Minikube and Docker for Desktop" section under  https://skaffold.dev/docs/concepts"?
