### ISSUE TITLE
Support for `ko`?

### ISSUE THREAD

**Issue by evankanderson** [GoogleContainerTools/skaffold#1958]
I'd like to be able to use `ko` to build binaries with Skaffold

### Expected behavior

There are some docs about how to use `ko` with `skaffold`.

### Actual behavior

No docs.

### Information

- Skaffold version: head / current docs
- Operating system: Windows

/kind feature-request

**Comment by balopat** [comment]
Thanks for opening this! Yes, this came up before, I'd love to see `ko` integrated. One tricky bit is that `ko` is a builder and a deployer at the same time, but probably we can work something out. 

We are working on the extensibility model for skaffold builders currently, so things are a bit up in the air, as soon as that settled, we will be able to fit `ko` in theoretically.

**Comment by evankanderson** [comment]
There is a `ko publish` mode which performs build and yaml replacement but
does not perform an apply.

**Comment by tejal29** [comment]
We should try to add an example for ko custom builder. Maybe we could add this for github.com/tektoncd/pipelines

**Comment by tejal29** [comment]
@evankanderson please feel free to take a stab as per the docs mentioned  https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally

**Comment by tstromberg** [comment]
I'm closing this as it's been a while, and there are still no plans to create a 'ko' builder.

That said, we now show how to use `ko` as a custom builder in `examples/custom`.
