### ISSUE TITLE
I would like to have a way to toggle the cleanup step

### ISSUE THREAD

**Issue by Alos** [GoogleContainerTools/skaffold#1962]
### Expected behavior
I can add a configuration change to my skaffold.yaml to stop the cleanup process that deletes my services while in development more.  
### Actual behavior
Skaffold cleans up and deletes my services and deployments.
### Information

- Skaffold version: v0.26.0
- Operating system: macOS 

### Steps to reproduce the behavior
Use Skaffold with Cloud Code. Start development mode. After your services and build, images pushed and deployed to K8s. Stop `Developing with Kubernetes`. Skaffold will start `"Cleaning up..."`

**Comment by nkubala** [comment]
@Alos thanks for the issue. this is possible today using skaffold directly by passing the `--cleanup=false` flag to `skaffold dev`. it's up to the cloud code team to expose the feature to users :) we had a sync today and we're working on the best way to do that (i.e. the default behavior for cloud code users), so stay tuned for updates from them!
