### ISSUE TITLE
Skaffold version in brew is old

### ISSUE THREAD

**Issue by Alos** [GoogleContainerTools/skaffold#1963]
### Expected behavior
Skaffold's latest version should be available in brew
### Actual behavior
Only version 0.26.0 is available

- Operating system: MacOS

**Comment by balopat** [comment]
Thanks for opening this, yes, this slipped through the cracks in our last release! (we should automate this :))

**Comment by balopat** [comment]
https://github.com/Homebrew/homebrew-core/pull/38956 this should fix it
