### ISSUE TITLE
Add documentation for insecure registries

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1968]
Commit 26ae49f15a2376176d88276f58e1708ff828b81f introduced a new global configuration `insecure-registries []string` to enable http communication with insecure registries. This needs some documentation, for example in https://skaffold.dev/docs/concepts/.

**Comment by balopat** [comment]
+1 - concepts sounds like the right place - it can fit nicely under the image registries section.
