### ISSUE TITLE
v0.27.0 SHA256 Checksums Not Included With Release

### ISSUE THREAD

**Issue by dsutphin** [GoogleContainerTools/skaffold#1972]
Previous Skaffold releases have included SHA256 checksums. But v0.27.0 does not have these. Would it be possible to have them added?

**Comment by tejal29** [comment]
Done! Thanks @dsutphin for bringing this to our attention.
https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.27.0 should have them
