### ISSUE TITLE
Skaffold filesync should test explicitly for `tar` executable in the container before syncing

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#1981]
When there is no `tar` in the developed image filesync fails with a mysterious `exit status 2` error. 
This can be ambiguous (see #1950) to debug. 

Skaffold should: 

1. check explicitly for tar 
2. if no `tar` return an explicit error

**Comment by briandealwis** [comment]
Just a note that #1950 did have `tar` available but the permissions on the files prevented the files from being updated.  What complicated the diagnosis was that [skaffold doesn't log the output of the tar command](https://github.com/GoogleContainerTools/skaffold/issues/1950#issuecomment-482673031). (and sorry, I should have opened an issue for that.)

My naive attempt to follow [the approach in `port_forward.go`](https://github.com/GoogleContainerTools/skaffold/blob/7ddbe578ef60da97739006b401db37846d2b353d/pkg/skaffold/kubernetes/port_forward.go#L87), to only show output when the tar fails, didn't produce any output.  Unfortunately `tar` is a bit chatty when using `-C /`, so [my hack](https://github.com/GoogleContainerTools/skaffold/issues/1950#issuecomment-482681921) to pass along `os.Stdout` and `os.Stderr` isn't great.

**Comment by corneliusweig** [comment]
@briandealwis There is also #1960 from @prary concerning the log output from `tar` when sync fails.

**Comment by balopat** [comment]
Ah cool - I guess I will close this in favor for #1960. Thanks!
