### ISSUE TITLE
Add configurable ignore-list for watched dependencies

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#20]
Even though we can calculate all the dependencies, users might not want to (or be able to) watch all dependencies for a large project.  We should figure out how we want to expose a ignore functionality to the user

https://github.com/GoogleCloudPlatform/skaffold/pull/15#discussion_r165719716

**Comment by l2silver** [comment]
And similarly, perhaps a regex include option configurable for each artifact? I've got a node monorepo that requires me to bundle files before running docker build.

**Comment by faraazkhan** [comment]
+1 This feature is kind of important, but also there may be some default optimizations that can go within skaffold, for example right now, simply adding a file to the git index with `git add` triggers a rebuild in skaffold, which is wasteful to say the least.

**Comment by hach-que** [comment]
We use .dockerignore to ignore some development symlinks, and skaffold tries to walk them and fails on this line https://github.com/GoogleContainerTools/skaffold/blob/master/vendor/github.com/karrick/godirwalk/walk.go#L197, even though it builds just fine in Docker. It would be great if Skaffold could honor existing .dockerignore files.

**Comment by dgageot** [comment]
@hach-que Skaffold does try to honor existing .dockerignore files. Do you have an example of a failure?

**Comment by nkubala** [comment]
hey everyone, this issue is one of our oldest still around! i'm not totally convinced based on the evidence here that this is a feature we **need** in skaffold, and our team likely won't be prioritizing it anytime soon. i'm going to mark it for closure now - that said, if anyone has evidence for why we need to build this in skaffold or examples of where we're falling short, please drop them in here!

**Comment by maxtuzz** [comment]
Would love to see this feature. I have to delegate build step to a custom script and every time the `target/` directory is regenerated for maven projects it'll just get stuck in an infinite loop of building and deploying.

**Comment by luchillo17** [comment]
@nkubala can you elaborate? can't find any way to tell skaffold to ignore a specific folder, either that or the docs are not updated with it.

**Comment by pre** [comment]
Follow up https://github.com/GoogleContainerTools/skaffold/issues/3935
