### ISSUE TITLE
Should all Skaffold labels be prefixed with `skaffold-`?

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2002]
Skaffold applies custom labels to every resource that it deploys.

I think that every label that it applies should be prefixed with `skaffold-` to avoid conflicts with user labels.

**Comment by nkubala** [comment]
seems like a good idea to me.

**Comment by balopat** [comment]
+1

**Comment by corneliusweig** [comment]
Does that count as a breaking change?

**Comment by nkubala** [comment]
@corneliusweig good point, unfortunately we don't really have insight into who is using these labels currently or what they're being used for. it would be pretty trivial to keep the old labels around for a while though, so I'd say being safe here doesn't really cost us anything. we could document it in the release notes, and then give a deprecation period (maybe two releases) after which the old labels would disappear.

**Comment by tejal29** [comment]
except for this one #2045

**Comment by corneliusweig** [comment]
This issue was fixed with #2062.
