### ISSUE TITLE
v1beta8 broke schema validation in Cloud Code for VSCode

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2005]
When `v1beta8` of the schema was introduced, `SkaffoldPipeline` was renamed `SkaffoldConfig`. That breaks the validation in Cloud Code for VSCode.

If I manually change the name back to `SkaffoldPipeline` in `~/.vscode/extensions/googlecloudtools.cloudcode-0.0.7/schema/skaffold/v1beta8.json`, it fixes the issue.

**Comment by tejal29** [comment]
We discussed this with the VS code team before merging this in.
See https://github.com/GoogleContainerTools/skaffold/pull/1899#issuecomment-479580673 for history.
I think we should have collaborated better for the team to also do a VS code plugin release.

**Comment by balopat** [comment]
Yeah, this is unfortunate - I think we should raise an issue/PR on cloud-code instead here though. Closing this for now.

**Comment by dgageot** [comment]
I'm reopening the issue because it'll require changes to Skaffold. I'll make sure `SkaffoldPipeline` is renamed `SkaffoldConfig` everywhere, even on older schema versions.
