### ISSUE TITLE
Google Cloud Build Question

### ISSUE THREAD

**Issue by Red-Five** [GoogleContainerTools/skaffold#2008]
(Using latest stable Google Cloud Code plugin on latest stable VS Code) 

Does the skaffold googleCloudBuild support using cloudbuild.yaml?

I'm new to skaffold and attempting to build an existing app that has a cloudbuild.yaml. It doesnt appear there is a way to reference the cloudbuild.yaml file from the skaffold.yaml

I'm guessing it might be necessary to fully reproduce all the cloudbuild steps in the skaffold.yaml file and I'm having difficulty finding examples on how to do this.

**Comment by balopat** [comment]
Hi @Red-Five, 
the GCB builder builds a Dockerfile or JIB artifact and publishes an image.
Skaffold _generates_ a single step Cloud Build build definition (~ "cloudbuild.yaml" ) and uses the GCB API to submit the build. 
It does not do any deployment or anything else. 
I hope this clears it up! Thank you for trying out skaffold!

**Comment by Red-Five** [comment]
@balopat Thanks.

So for the example cloudbuild.yaml
https://github.com/forseti-security/forseti-security/blob/dev/install/docker/cloudbuild.yaml
We have 3 steps
Build a base image, main image and optional unit test suite step.

Is there an example somewhere showing how to do the same via Skaffold?

(I am attempting to set up a development environment for Google Forseti Security that allows for continuous deployment to GKE, in pod debugging and application profiling.)

**Comment by balopat** [comment]
> @balopat Thanks.
> 
> So for the example cloudbuild.yaml
> https://github.com/forseti-security/forseti-security/blob/dev/install/docker/cloudbuild.yaml
> We have 3 steps
> Build a base image, main image and optional unit test suite step.
> 
> Is there an example somewhere showing multi step cloud builds via Skaffold?
> 
> (I am attempting to set up a development environment for Google Forseti Security that allows for continuous deployment to GKE, in pod debugging and application profiling.)

This is an interesting use case for Skaffold but you'll have to use Skaffold as a cloud build step. We publish an image: ` docker run gcr.io/k8s-skaffold/skaffold:latest skaffold version` that you can use as part of your pipeline to deploy your app to GKE. You will also need a step to get the cluster credentials using gcloud and save it to the workspace.

**Comment by balopat** [comment]
I'll close this for now, please reopen if you need more information.
