### ISSUE TITLE
Add option to always use terminal color escape sequence

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#2021]
For now, Skaffold seems to check if TTY is attached and only uses colored formatting if it is. For  Cloud Code IntelliJ IDE output, we run in non-TTY mode but still support escape sequences in the console view. If we can have a flag to always enable them, that could make console output prettier for IJ/JetBrains developers.

**Comment by corneliusweig** [comment]
This will probably not be useful for end-users. Should such a flag be hidden?
