### ISSUE TITLE
[Deploy] Add `helm repo update`

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2039]
I'm using helm to deploy the Elasticsearch chart that's then used by my application.

I think for this use-case it would make sense for Skaffold to support running these Helm commands. So allow setting the repo as part of the skaffold.yaml in Helm deploy section
```
helm repo add elastic https://helm.elastic.co
helm repo update
```

**Comment by tejal29** [comment]
adding `helm repo add` would also involve supporting authentication and secure connection. 
```
     --ca-file string     verify certificates of HTTPS-enabled servers using this CA bundle
      --cert-file string   identify HTTPS client using this SSL certificate file
  -h, --help               help for add
      --key-file string    identify HTTPS client using this SSL key file
      --no-update          raise error if repo is already registered
      --password string    chart repository password
      --username string    chart repository username
```

`Skaffold` assumes your deploy tool is set up correctly and you can develop you app  and continuously iterate.
Adding helm repositories is a one time set up which you can done once.
This feature could be something we might pick up later for `skaffold init` where you set up your cluster correctly.

**Comment by dkirrane** [comment]
Yip makes sense to do the `repo add` part in `skaffold init`

The other commands are probably already run during skaffold deploy?
```
helm repo update
# And if the chart has a requirements.yaml
helm dependency update
```

**Comment by tejal29** [comment]
>The other commands are probably already run during skaffold deploy?

I don't think we do that right now. 
We run `helm upgrade --force` and `helm dep build`

**Comment by dahovey** [comment]
+1 for `helm repo update`

This is related to #1665

**Comment by levkov** [comment]
+1 for helm repo update

**Comment by guram-sigua** [comment]
+1 for 'helm repo update'

**Comment by balopat** [comment]
Let's split this into two - I opened https://github.com/GoogleContainerTools/skaffold/issues/2653 for adding `repo add` to `skaffold init`
I'll rename this to `helm repo update` that seems like we could run at the start of the dev loop / skaffold run.

**Comment by tstromberg** [comment]
Decreasing the priority, as no one is currently working on this feature. If someone is interested in making this happen, we would be welcome to review a PR adding support for it.

**Comment by briandealwis** [comment]
When the `skaffold.yaml` doesn't specify `skipBuildDependencies: true` then Skaffold will run `helm dev build`, which updates the Helm repositories.

```
$ skaffold dev -vdebug
[...]
INFO[0000] Building helm dependencies...                 subtask=0 task=Deploy
DEBU[0000] Running command: [helm --kube-context minikube dep build skaffold-helm]  subtask=-1 task=DevLoop
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "xxx" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading elasticsearch from repo https://helm.elastic.co
Deleting outdated charts
DEBU[0005] EnvVarMap: map[DIGEST:skaffold-helm:61dd30d467c2638987aaa898d147cd0fd9c356ccda545222577896fad332339b DIGEST_ALGO:skaffold-helm DIGEST_HEX:61dd30d467c2638987aaa898d147cd0fd9c356ccda545222577896fad332339b IMAGE_DIGEST: IMAGE_NAME:skaffold-helm IMAGE_REPO:skaffold-helm IMAGE_TAG:61dd30d467c2638987aaa898d147cd0fd9c356ccda545222577896fad332339b]  subtask=-1 task=DevLoop
DEBU[0005] Running command: [helm --kube-context minikube install skaffold-helm skaffold-helm --set-string image=skaffold-helm:61dd30d467c2638987aaa898d147cd0fd9c356ccda545222577896fad332339b]  subtask=-1 task=DevLoop
NAME: skaffold-helm
LAST DEPLOYED: Sun Aug 22 12:39:31 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
```

Closing as I think this request — to run `helm repo update` on a build — is supported.
