### ISSUE TITLE
Port forwarding is working with build artifacts defined in the skaffold.yaml, but not with additional containers in pods defined in the k8s manifests yaml.

### ISSUE THREAD

**Issue by botwhytho** [GoogleContainerTools/skaffold#2046]
I think this is legitimately a different bug than all the other related port-forward bugs. Either this is a bug, or expected behavior, where there is a discrepancy between the documentation (slim to none) and user's expectations.

Using skaffold version 0.23 (because of this other port-forward bug https://github.com/GoogleContainerTools/skaffold/issues/1815), and kubectl as the deploy mechanism, port-forwarding and logs forwarding only happen for images that are defined under the artifacts section. I have not tested with using kustomize as the deploy mechanism (which I will be switching to soon, will update ticket if the functionality is different there).

As port-forwarding is a dev feature, I have additional manifests, for local dev Postgres & Kafka, which in production may be managed services outside of kubernetes. I am using external official images for these components but definitely want port-forwarding so that developers can work with any PG/Kafka client tools they use in their daily workflows as if these services were running 'locally' on their machines

As it stands now I might need to manage these services outside of skaffold and manually enable port-forwarding, which is less than ideal.

If this is not a bug, but expected behavior, could not find documentation about this anywhere. If it is expected then I'll open a feature request ticket as I would expect (and is very useful) that port-forwarding (and logs) would work for anything I specify under manifests.

_Originally posted by @masonlr in https://github.com/GoogleContainerTools/skaffold/issues/1663#issuecomment-482807251_

**Comment by priyawadhwa** [comment]
Hey @botwhytho thanks for submitting this. I've been working on fixing up port forwarding and this is super helpful. Some thoughts:

>Using skaffold version 0.23 (because of this other port-forward bug #1815)

I just merged a fix for #1815, so the next release (scheduled for this week) should solve this problem. If you'd like to test it out now, you can find instructions for installing the latest version of skaffold at HEAD [here](https://skaffold.dev/docs/getting-started/#installing-skaffold) under `Latest bleeding edge binary`

> As port-forwarding is a dev feature, I have additional manifests, for local dev Postgres & Kafka, which in production may be managed services outside of kubernetes. I am using external official images for these components but definitely want port-forwarding 

I've been working on figuring out the best way to implement user defined port forwarding; this seems related to #2066 as well. Would being able to specify additional images for skaffold to port-forward be sufficient for your use case (perhaps as a `--images` flag to pass in), or would you also want to be able to specify which local port you want to forward too?

> If this is not a bug, but expected behavior, could not find documentation about this anywhere.

 #2078 added some documentation around how port forwarding currently works. [skaffold.dev](skaffold.dev) will be updated with the next release. However, please do open an issue if you think more documentation would be useful.

**Comment by botwhytho** [comment]
@priyawadhwa Thank for the great work on PRs and triaging tickets. Will be updating to 0.29. 

The documentation change from #2078 definitely makes current functionality clear now.

Can you elaborate a bit on how an `--images` flag would work? How would skaffold translate a list of images into port-forwarding? Would it detect pods/deployments depending on those images and check for ports/containerPorts in the k8s manifests?

Could you provide links to current implementation and any design proposals for user defined port-forwarding? I'd like to understand a bit more why the current implementation has the limitations it has. For my use-cases, I wouldn't necessarily need port re-mapping but could see how it would be useful for people, and think I've seen discussion about that in tickets.

This is an issue I'd be willing to assist with design discussion, code review, testing or even submitting PRs if I can get proper context. Rolling out skaffold to some teams and developers make heavy use of client tools that assume services are just deployed on `localhost`. Currently having to wrap skaffold with some bash glue to call `kubectl port-forward` for services that depend on official upstream images (Postgres, Kafka, etc.). These are workarounds I'd rather not have to support going forward.

**Comment by priyawadhwa** [comment]
Hey @botwhytho for sure, I'm working on finishing up my plan for user defined port-forwarding & can definitely open up a PR with a design doc. Once it's ready would really appreciate your feedback, hopefully I'll have it open in the next few days. 

re: the `--images` flag, skaffold would port forward any containers that ran one of the images passed in. However, I think it's unlikely we will proceed in that direction. I'm learning towards letting users specify resources (pod/deploy/replicaset etc) to port-forward directly in the skaffold.yaml, and then skaffold can run a simple `kubectl port-forward` on them.

**Comment by priyawadhwa** [comment]
Hey @botwhytho I just merged a PR for user defined port forwarding in the skaffold config (#1311) which should be available in the next release. Since this seems to solve your use case, I'm going to go ahead and close this issue, but please comment or reopen if you need!
