### ISSUE TITLE
Use image name from jib configuration

### ISSUE THREAD

**Issue by danielsonjh** [GoogleContainerTools/skaffold#2061]
Hi, is it possible to make the `image` field optional when using jib, and use the image property from the jib config instead?

Definitely a nitpick, but it would be nice to not have to repeat the image name

**Comment by priyawadhwa** [comment]
Hey @danielsonjh, thanks for starting this discussion. We are not yet convinced that this would be worth the effort. The current model is that skaffold passes in the expected image name to jib, and this would be the other way around. We could be potentially convinced if we see a larger need for this feature. 

 I'm going to go ahead and close this issue, but if anyone is passionate about it please feel free to comment here and we can reopen it.
