### ISSUE TITLE
"Error response from daemon: invalid reference format" for --default-repo with port

### ISSUE THREAD

**Issue by Rundowner** [GoogleContainerTools/skaffold#2073]
### Expected behavior

- `getting_started` example works when running `skaffold dev --default-repo k8s-master-and-docker-registry`, assuming `k8s-master-and-docker-registry` is a bare metal server with K8S and a private docker registry running (https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-18-04).

### Actual behavior

- `getting_started` example doesn't run (details below).

### Information

- Skaffold version: v0.28.0
- Operating system: Ubuntu 16.04 LTS (amd64).
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

**`# Specify HTTPS and port number. Can't deploy image at all.`**
```
$> skaffold dev --default-repo https://k8s-master-and-docker-registry:5000
Generating tags...
 - https://k8s-master-and-docker-registry:5000/gcr_io_k8s-skaffold_skaffold-example -> https://k8s-master-and-docker-registry
:5000/gcr_io_k8s-skaffold_skaffold-example:v0.28.0-80-g25f1b66-dirty
Tags generated in 8.404032ms
Starting build...
Found [kubernetes-admin@kubernetes] context, using local docker daemon.
Building [https://k8s-master-and-docker-registry:5000/gcr_io_k8s-skaffold_skaffold-example]...
Sending build context to Docker daemon  3.072kB
Pruning images...
Image prune complete in 8.87µs
FATA[0000] exiting dev mode because first run failed: build failed: building [https://k8s-master-and-docker-registry:5000/gcr_io
_k8s-skaffold_skaffold-example]: build artifact: docker build: Error response from daemon: invalid reference format
```

**`# Specify port number: defaults to HTTP: get the same response when I attempt to "docker login k8s-master-and-docker-registry", but don't have this problem when I attempt to "docker login k8s-master-and-docker-registry:5000".`**
```
$> skaffold dev --default-repo k8s-master-and-docker-registry:5000
Successfully tagged k8s-master-and-docker-registry:5000/gcr_io_k8s-skaffold_skaffold-example:v0.28.0-80-g25f1b66-dirty
Build complete in 533.663704ms
Starting test...
Test complete in 25.614µs
Starting deploy...
kubectl client version: 1.14
pod/getting-started created
Deploy complete in 932.374168ms
Watching for changes every 1s...
rpc error: code = Unknown desc = Error response from daemon: Get http://k8s-master-and-docker-registry:5000/v2/: net/http: HTTP/
1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
Back-off pulling image "k8s-master-and-docker-registry:5000/gcr_io_k8s-skaffold_skaffold-example:891b4ca248c488c30f1dd4225398593
6128f7f6c03475ad51299ecf137d0e880"
```

**`# Don't specify port or protocol: appears to be able to reach the master/registry, but fails "no basic auth credentials".`**
```
$> skaffold dev --default-repo k8s-master-and-docker-registry
Deploy complete in 1.372383481s
Watching for changes every 1s...
rpc error: code = Unknown desc = Error response from daemon: Get https://k8s-master-and-docker-registry/v2/gcr_io_k8s-skaffold_skaffold-example/manifests/14a18872a54ffd2e7033b9a5fb188be3c4091631265a179ad5c2e6facf2d1568: no basic auth credentials
Back-off pulling image "k8s-master-and-docker-registry/gcr_io_k8s-skaffold_skaffold-example:14a18872a54ffd2e7033b9a5fb188be3c4091631265a179ad5c2e6facf2d1568"
```

**Comment by Rundowner** [comment]
It seems that the only approach(es) that get skaffold (partially) up and running fail to actually pull the container image.

**Comment by tejal29** [comment]
@Rundowner Our tutorials mention, how to run the examples in your own private repository. 
https://skaffold.dev/docs/tutorials/

Can you try that?

**Comment by c410-f3r** [comment]
> build artifact: docker build: Error response from daemon: **invalid reference format**

This also happens with me whenever I explicit declare a port, e.g., `--default-repo some.domain:5000`

**Comment by balopat** [comment]
I think we should probably look into the `invalid reference format` but the rest with the `rpc error` shows that the nodes in your k8s cluster can't pull the image for the pod.

**Comment by dgageot** [comment]
@Rundowner have you solved your issue?

For me, the solution is to:
 + Use the `skaffold dev --default-repo k8s-master-and-docker-registry:5000` syntax
 + Verify the way you've setup `registrypullsecret`. It should point at `https://k8s-master-and-docker-registry:5000`, not `http://k8s-master-and-docker-registry:5000`
 + Maybe you could push an image to this registry and use that image on k8s, without using skaffold. This is to identify if the problem comes from Skaffold or from the configuration.

**Comment by dgageot** [comment]
I'm going to close this ticket because I don't think there's an issue in skaffold. Since I can be very wrong, feel free to reopen!

**Comment by patsevanton** [comment]
```
skaffold dev --default-repo login-on-hub-docker
```
Example for me:
```
skaffold dev --default-repo antonpatsev
```
