### ISSUE TITLE
Helm deployments do not add labels to PodTemplates

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2074]
### Expected behavior
Skaffold should also label pods created via Deployment resources.

### Actual behavior
Skaffold adds labels to the `deployment.metadata.labels` but not to `deployment.spec.template.metadata.labels`.

### Information

- Skaffold version: HEAD

This clearly comes from this function where the live api-resource is patched: https://github.com/GoogleContainerTools/skaffold/blob/25f1b66402507440a12a0c1173806b190ff76eb8/pkg/skaffold/deploy/labels.go#L95
It's clear, that it only adds labels to the owning resource, but not to the pods it manages.

### Steps to reproduce the behavior

1. `cd examples/helm-deployment`
2. `skaffold dev`
3. `kubectl get deploy skaffold-helm -o jsonpath='{..labels}'` -> yields the expected set of skaffold labels:
    ```go
    map[app:skaffold-helm app.kubernetes.io/managed-by:skaffold-v0.28.0-80-g25f1b664 chart:skaffold-helm-0.1.0 cleanup:true docker-api-version:1.38 heritage:Tiller release:skaffold-helm skaffold-builder:local skaffold-deployer:helm skaffold-tag-policy:sha256 tail:true] map[app:skaffold-helm release:skaffold-helm]
    ```
4. `kubectl get pod skaffold-helm-XYZ -o jsonpath='{..labels}' yields _only the helm labels_
    ```go
    map[app:skaffold-helm pod-template-hash:6b75889977 release:skaffold-helm]
    ```

I think it would be preferrable, if also the dependent resources have the Skaffold labels.

**Comment by corneliusweig** [comment]
@tejal29 would you like to assign yourself?

**Comment by dgageot** [comment]
@corneliusweig Is this PR still active? I'd like to close stalled PRs so that we have a better idea of which PR needs a review

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.
