### ISSUE TITLE
Publish latest master on brew

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#2081]
Would it be possible to start publishing the latest `master` build on brew as `skaffold@latest` maybe? Would be helpful to be able to quickly switch to this version sometimes to confirm bug fixes instead of downloading and installing the binary each time. 

Thank you for such an excellent tool!

**Comment by nkubala** [comment]
@briandealwis to confirm but I believe all of our brew packages are published through manual PRs made to the homebrew project, so it would be impossible to do on every merge to master :( maybe there is a way to automate publishing to brew?

**Comment by balopat** [comment]
Hi, yeah, just checked and brew is very PR oriented - even having a nightly build would be a stretch for that model. We can make the skaffold upgrade command more accessible / easier to run potentially. I'm closing this. Thank you for the discussion!
