### ISSUE TITLE
Investigate issues with shared grpc channel and multiple skaffold processes

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#2086]
The Skaffold Event API seems to have unexpected behavior when multiple skaffold processes are executed.

I'm still investigating exactly what is happening, but I'm opening this issue to start the discussion on what actually is intended to happen.

Overview:

the grpc channel is shared across all running skaffold processes. It appears as though only the first Skaffold process is reporting events via the API. Furthermore, it appears as though the events reported by the first process are duplicated. Here is a snippet from the event output after running two skaffold processes:

```
deployEvent {
  status: "Complete"
}

deployEvent {
  status: "Complete"
}

portEvent {
  localPort: 8080
  remotePort: 8080
  podName: "java-hello-world-foo2-79c9db69c6-bvxh9"
  containerName: "server"
  namespace: "default"
}

portEvent {
  localPort: 8080
  remotePort: 8080
  podName: "java-hello-world-foo2-79c9db69c6-bvxh9"
  containerName: "server"
  namespace: "default"
}
```

@nkubala perhaps you can correct my understanding of what is expected to happen under these scenarios?

**Comment by balopat** [comment]
Can you try with `--rpc-port`?

**Comment by etanshaul** [comment]
thanks @balopat, as discussed, this definitely sounds like what we want to be using. Will report back.

**Comment by balopat** [comment]
@etanshaul can we close this?

**Comment by etanshaul** [comment]
Yes! Thanks. Using the suggested flag fixed this.
