### ISSUE TITLE
File sync nesting documentation ambiguity

### ISSUE THREAD

**Issue by MagicShoebox** [GoogleContainerTools/skaffold#2119]
The documentation at https://skaffold.dev/docs/how-tos/filesync/ is ambiguous.
(Source file: docs/content/en/docs/how-tos/filesync/_index.md)

The documentation states:
> By default, matched files are transplanted with their whole directory hierarchy below the artifact context directory onto the destination.

It then provides two relevant examples (# 2 and # 4) that seem to conflict:
```
# sync files directly below `static-html` into `static/`
          - src: 'static-html/*.html'
            dest: static
```
```
# sync all `md` files from `content/en` into `content`
          - src: 'content/en/**/*.md'
            dest: content
            strip: 'content/en/'
```

> - The second rule synchronizes all html files in the static-html folder into the <WORKDIR>/static folder in the container. [...]

> - The last rule synchronizes all md files below the content/en directory into the content folder on the container. The strip directive ensures that only the directory hierarchy below content/en is re-created at the destination. [...]

In the second example, why are the files not placed in <WORKDIR>/static/static-html/? If the hierachy is only transplanted when using `**`, the documentation could make that more clear. Perhaps in the last example, the `strip: 'content/en/'` could be changed to `strip: 'content/'` to make it more clear whether both `en/` and `**` matched directories are included or just `**` matched directories.

To be clear, I have not tested how it actually behaves, I am merely commenting on the documentation. I could test it and report back, if that would help.

Thanks for all your work, Skaffold is great!

**Comment by balopat** [comment]
This should be the way it behaves: `static/*.html` matches _files_ in a directory, `content/en/**/*.md` matches all paths, including folders, preserving the folder structure. 
We are open to have a clearer doc always :) If you have a good idea how to explain this better, please raise a PR!
Thank you :)
