### ISSUE TITLE
skaffold debug reference applications

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleContainerTools/skaffold#2124]
I feel it would be extremely valuable to have a reference project that demonstrates how to get up and running with `skaffold debug`.

Things I would hope to see:
 - A project per supported language/runtime
 - `git clone <repo> && skaffold debug` is all I should need to run it.
 - Supporting documentation that explains they key parts that make the feature tick
 - Include a screenshot/video of how you might attached your favourite IDE
   - vscode seems like a popular choice

Your documentation clearly states that this is an alpha feature but doing this now will:
 - Make it easier to demonstrate how the feature changes over time through executable documentation
  - Encourage more feedback by making it easier to use

**Comment by briandealwis** [comment]
I've started this as a set of integration tests in #2141.

**Comment by GavinOsborn** [comment]
As well as some of the above suggestions I think this project would benefit from a clear understanding of its relationship with Cloud Code.

**Comment by briandealwis** [comment]
Projects have been merged with #2141 into [`integration/testdata/debug/`](https://github.com/GoogleContainerTools/skaffold/tree/master/integration/testdata/debug).
