### ISSUE TITLE
Skaffold examples should incorporate container healthcheck eval 

### ISSUE THREAD

**Issue by tequilarista** [GoogleContainerTools/skaffold#2129]
Upon completion of [#176](https://github.com/GoogleContainerTools/skaffold/issues/176), we should also add use of the success state (and failure conditions) to the skaffold/examples for best practice examples.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
