### ISSUE TITLE
Deploying to GKE with Cloud Build + Kustomize

### ISSUE THREAD

**Issue by ItsLeeOwen** [GoogleContainerTools/skaffold#2137]
### Expected behavior
The following cloudbuild.yaml config, which works as expected using `dev` or `run` on a local machine, to also build & deploy to GKE from Cloud Build as seen on [Priya Wadhwa's demo](https://www.youtube.com/watch?v=TYx0BTyFtmc?t-17m)

```yaml
# cloudbuild.yaml
steps:
  - name: "gcr.io/k8s-skaffold/skaffold"
    args:
      [
        "gcloud",
        "container",
        "clusters",
        "get-credentials",
        "my-cluster",
        "--region",
        "us-east1",
        "--project",
        "${PROJECT_ID}",
      ]

  - name: "gcr.io/k8s-skaffold/skaffold"
    args: ["skaffold", "run", "-p", "test", "-v=debug"]
```

### Actual behavior
The build succeeds, however deployment fails with a kustomize manifest error.
```
ERROR: build step 1 "gcr.io/k8s-skaffold/skaffold" failed: exit status 1
ERROR
Finished Step #1
Step #1: time="2019-05-16T15:15:51Z" level=fatal msg="deploy failed: reading manifests: kustomize build: Running [kustomize build k8s/overlays/test]: stdout , stderr: Error: json: unknown field \"apiVersion\"\nUsage:\n  kustomize build [path] [flags]\n\nExamples:\nUse the file somedir/kustomization.yaml to generate a set of api resources:\nbuild somedir/\n\nFlags:\n  -h, --help   help for build\n\nGlobal Flags:\n      --alsologtostderr                  log to standard error as well as files\n      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)\n      --log_dir string                   If non-empty, write log files in this directory\n      --logtostderr                      log to standard error instead of files\n      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)\n  -v, --v Level                          log level for V logs\n      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging\n\n, err: exit status 1: exit status 1"
Step #1: time="2019-05-16T15:15:51Z" level=debug msg="Running command: [kustomize build k8s/overlays/test]"
```

### Information

- Skaffold version: 
  gcr.io/k8s-skaffold/skaffold
  gcr.io/k8s-skaffold/skaffold:edge

- Contents of skaffold.yaml:
```yaml
apiVersion: skaffold/v1beta10
kind: Config
profiles:
  - name: test
    build:
      artifacts:
        - image: gcr.io/my-project-id/test
          context: test
          docker:
            dockerfile: docker/Dockerfile
      googleCloudBuild:
        projectId: my-project-id
    deploy:
      kustomize:
        path: k8s/overlays/test
```

- Contents of k8s/overlays/test/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
```

### Steps to reproduce the behavior

1. Create a skaffold project w/ kustomize manifests
2. Verify that skaffold works as expected using `run` from your local machine
3. Create a `cloudbuild.yaml` file using gcr.io/k8s-skaffold/skaffold to run the profile
4. Create a build trigger on Cloud Build to run `cloudbuild.yaml`
5. Run trigger manually (or push to branch)
6. Observe history log

**Comment by priyawadhwa** [comment]
Hey @ItsLeeOwen, sorry for the delayed response. In my demo, I was running my cloud build trigger and Kubernetes cluster under the same GCP project. Is that the case for you as well? If so, does your cloud build service account have permissions to deploy to your Kubernetes cluster?

I gave my cloudbuild service account `Kubernetes Engine Admin` permissions so it could deploy to my cluster for the demo.

**Comment by steevee** [comment]
Hey @priyawadhwa, same issue here when submitting my `cloudbuild.yaml` that is applying `kustomize` to our `deployment.yaml` via a `skaffold` build step.

1. I can confirm `@cloudbuild.gserviceaccount.com` has the role `Kubernetes Engine Admin`
2. Interestingly, if I remove `kustomize` config from `skaffold.yaml` and default to using `kubectl` (on a manually created `k8s/deployment.yaml`), then it works!

Note: `gcr.io/k8s-skaffold/skaffold` uses `kustomize v1.0.1` - so I daresay the issue is with that right now (and in my case, likely the lack of support for strategic merges in `v1.0.1`). 

Is there a reason why we're not using a more recent version of `kustomize`?

I'll fork and try updating.

**Comment by priyawadhwa** [comment]
Hey @steevee that's interesting. I don't think there's any specific reason why we are on this version of `kustomize`, we probably just haven't gotten around to updating it. Does a more recent version work with your build step? If so, would you be interested in submitting a PR to [update](https://github.com/GoogleContainerTools/skaffold/blob/master/deploy/skaffold/Dockerfile#L42) to that version?

**Comment by steevee** [comment]
@priyawadhwa yep, fixed it for me. I just dropped #2265 in for review. Thanks!
