### ISSUE TITLE
Allow using environment variable for  force color option

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#2139]
Related to https://github.com/GoogleContainerTools/skaffold/issues/2021

This way we can avoid using incompatible CLI option (`--force-colors`) and checking for Skaffold version before using it. I believe now it's not possible to specify it with an environment variable (`SKAFFOLD_FORCE_COLORS` doesn't seem to work)

**Comment by priyawadhwa** [comment]
Thanks for opening this @ivanporty, I have a fix open in #2143 :)

**Comment by priyawadhwa** [comment]
This should be fixed now!

**Comment by etanshaul** [comment]
Thanks Priya!
