### ISSUE TITLE
Produce signed binaries

### ISSUE THREAD

**Issue by cmosguy** [GoogleContainerTools/skaffold#2154]
### Information

- Skaffold version: latest version
- Operating system: Windows 10

### Steps to reproduce the behavior

1. Clicked on the link for getting the binary for windows:  https://storage.googleapis.com/skaffold/releases/latest/skaffold-windows-amd64.exe

2.  Both the Windows Defender and Symantec Endpoint protection both are prompting me that this .exe can put my system at risk:

![image](https://user-images.githubusercontent.com/1676382/58025082-4673d900-7ad9-11e9-8e03-1d8755044e93.png)

**Comment by nkubala** [comment]
hmm. I wonder if this is happening because we're not signing the binary when we build it? @dgageot any ideas?

**Comment by balopat** [comment]
I'll have a look at this - we can probably get this sorted out with some internal workflows.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!

**Comment by balopat** [comment]
This is still an open issue. Nothing has been done about it, I haven't finished setting up a kokoro process for it.

**Comment by MarlonGamez** [comment]
Closing this issue as we publish signed binaries for windows as of skaffold >= v1.35.1. Please let me know if similar issues are run into
