### ISSUE TITLE
Documentation for use of named kaniko flags unclear

### ISSUE THREAD

**Issue by twuttk** [GoogleContainerTools/skaffold#2168]
The current documentation for the use of kaniko additional flags states 

> additional flags to be passed to Kaniko command line. See Kaniko Additional Flags. Deprecated - instead the named, unique fields should be used, e.g. buildArgs, cache, target.

https://skaffold.dev/docs/references/yaml/

In the documentation it's not clear how e.g. the --reproducible flag for kaniko can be used in a non deprecated way. An approach like "reproducible: true" does not work
>  field reproducible not found in type latest.KanikoArtifact

Skaffold version used: 0.29
apiVersion: skaffold/v1beta10

**Comment by priyawadhwa** [comment]
Hey @twuttk --the field `reproducible: true` would need to be added to the `KanikoArtifact` for this to work. Would you be interested in submitting a PR?

**Comment by tbarrella** [comment]
I'd be happy to start a PR for this if no one else has

**Comment by priyawadhwa** [comment]
@tbarrella that would be great, thanks!
