### ISSUE TITLE
Support GitHub Actions for building

### ISSUE THREAD

**Issue by crimeminister** [GoogleContainerTools/skaffold#2171]
### Expected behavior

Skaffold should allow building with the [local build tool](https://github.com/nektos/act) for GitHub Actions.

### Actual behavior

The GitHub Actions local build tool isn't supported.

**Comment by balopat** [comment]
Hi @crimeminister - thank you for the recommendation - have you tried hooking it up with our [Custom Artifact builder](https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally)? I don't think we will implement and maintain `act` as part of the Skaffold codebase unless there is a lot of demand for it.

**Comment by crimeminister** [comment]
Hi @balopat, I will go ahead and wire things up using Custom Artifact builder as you suggest. Would examples of this sort of extension be useful contributions, or are they better kept outside of the `skaffold` repo? I would also be keen to have an example of wiring up `cloud-build-local` in a similar fashion and would be happy to contribute either / both.

**Comment by balopat** [comment]
For now we haven't had a place for this in our repo - but could be interesting - maybe a community folder? @crimeminister did you have a chance to look at this?

**Comment by gmhflg** [comment]
Hey @crimeminister & @balopat, 
Just curious if any progress has been made on this before I try and build our own workaround?
Thanks,
G

**Comment by crimeminister** [comment]
@gmhflg At my office the decision was taken to transition to Cloud Build for the things I am working on. Would still like to see this happen, but I think `nektos/act` will need to be fully up-to-date w.r.t. the changes to GHA before it makes sense, perhaps?

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, no one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
