### ISSUE TITLE
Add 'metadata' field to skaffold schema

### ISSUE THREAD

**Issue by botwhytho** [GoogleContainerTools/skaffold#2200]
My team is using kustomize with skaffold, we've moved common config to centralized repos and are using kustomize's 'remote base' feature. We have taken this further and centralized a generic `skaffold.yaml` which we modify by repo to specify the artifact details. So during CI/CD the `skaffold.yaml` file is dynamically created from remote bases and local kustomizations.

I've added a
```
metadata:
  name: base-config
```
block to the central `skaffold.yaml` file as kustomize will error out without one, but this is not a legal field in the current skaffold schema so I have to pipe the generated skaffold config through sed, to remove those two lines; not ideal.

I propose a metadata field be added to the `skaffold.yaml` schema. This can hold, at the minimum, name inside it so that skaffold configs can be modified with kustomize, as well as other values that may be used for other things.

**Comment by botwhytho** [comment]
Realized I can make my local patch a json patch and add:
```
- op: remove
  path: /metadata
```
to the list of patches and thus not need `sed` or an additional outside tool.

I consider this _less_ hacky but still not close to ideal.

Considering the `skaffold.yaml` schema is kubernetes-like by having `apiVersion` and `kind`, still think a `metadata` section would be a great addition.

**Comment by nkubala** [comment]
hey @botwhytho thanks for the issue. I'm not sure I totally understand your use case here, can you explain what kustomize is actually doing with this metadata?

and you're proposing that this field live in the top level of the skaffold.yaml right? not in the kustomize stanza? I guess I'm not inherently opposed to this, just wondering exactly why we need it and if there might be a way to embed it in the kustomize builder spec instead.

**Comment by corneliusweig** [comment]
So I think the idea is to use kustomize to merge multiple `skaffold.yaml` files into one. For that, kustomize needs the `metadata.name` field to identify the resources.

I think it's a neat trick to use kustomize for this job. Adding an optional `metadata.name` field overall makes sense to me. However, I would argue against re-using the `apimachinery/ObjectMeta` object which contains a lot more fields than just the name that simply don't make sense in the context of Skaffold.

**Comment by botwhytho** [comment]
@corneliusweig Thanks for chiming in. Yes, this is how we're using kustomize with skaffold: to merge multiple `skaffold.yaml` files. Unless there are plans on the roadmap for `skaffold.yaml` files to live inside a kubernetes cluster as k8s objects, then agreed, re-using a full `apimachinery/ObjectMeta` object might be a bit of overkill.

For my use case a `metadata.name` field that takes a string should suffice.
