### ISSUE TITLE
`skaffold debug` may need to apply IDE-specific language runtime bindings

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2202]
Different IDEs may require different combinations of language runtime support packages.  For example, IDEA/PyCharm does not support the _Debug Adapter Protocol_, so `ptvsd` for Python will not work out of the box.  Instead it needs to use a separate package, [`pydevd-pycharm`](https://pypi.org/project/pydevd-pycharm/) to enable [remote debugging](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config).  And unfortunately it seems to require running some code on startup to enable.

We can maybe try to support this by a command-line specified "flavour" or "kind".

**Comment by corneliusweig** [comment]
Could that be handled together with #2203?

**Comment by briandealwis** [comment]
IDEs shouldn't need to modify the `skaffold.yaml`.

**Comment by tstromberg** [comment]
Marking as stale, since it's been a while and does not appear to be on the teams priority radar. Feel free to reopen if you disagree.

**Comment by briandealwis** [comment]
Re-opening but marking as p3 as we know it's an issue but other issues were higher priority.

**Comment by briandealwis** [comment]
With Delve's DAP finishing up, we'll need to support this soon.  Rather than trying to maintain IDE-compatibility tables, I think it's best if the IDEs specify a list of supported protocols.  For example, CC-VSC could run:
```
skaffold debug --protocols dap
```

whereas CC-IJ would run:
```
skaffold debug --protocols dlv,jdwp,pydevd,nodejs
```

cc: @quoctruong @etanshaul @petlin

**Comment by etanshaul** [comment]
how timely! I just wrote up: https://docs.google.com/document/d/1Dj52OayWFFa_3dBSzvt3-xWFIGLvm0oyGswRW4oV0KI, so I think we can converge on this.

**Comment by etanshaul** [comment]
one thing that is missing from my above design is multiple protocol support (good catch)

I also like how you differentiate between DAP and _everything else_. 

> could become unwieldy?

How do you figure this? Do you mean because JB has to manually specificy all of the individual protocols?

**Comment by nkubala** [comment]
> could become unwieldy?

seems like a small price to pay for the flexibility this grants, otherwise we're going to have to coordinate on both sides every time a new debug protocol is added.

my only question is, what happens when two separate protocols for the same language are provided? we can't use both at the same time, so would we select arbitrarily or fail out?

**Comment by etanshaul** [comment]
> my only question is, what happens when two separate protocols for the same language are provided? we can't use both at the same time, so would we select arbitrarily or fail out?

I think we should default to DAP unless specified. I updated the referenced design above with this proposal.
