### ISSUE TITLE
skaffold fails to retrieve digest when building in remote cluster using kaniko

### ISSUE THREAD

**Issue by gbates101** [GoogleContainerTools/skaffold#2217]
### Expected behavior
Skaffold should be able to build and deploy in a remote cluster using kaniko and an insecure registry. The insecure registry is hosted within the same cluster, and is not exposed to the internet (only available to pods within the cluster).

### Actual behavior
When building in and deploying to a remote cluster using kaniko with an insecure registry hosted in said remote cluster, the kaniko build finishes and pushes successfully, but skaffold fails to fetch the digest for the newly pushed image. I suspect this is because my default gateway can't resolve the kube DNS name of `registry.gbates.svc.cluster.local`. 

### Information
Log snippet showing that kaniko pushed the layers to my insecure registry just fine, but immediately fails afterwards when fetching the image.
```
2019/06/03 22:21:42 pushed blob sha256:c4d88c88e4d39a4407c100eb40888d6701b9eecede5a9e3c57660711c92c63a2
2019/06/03 22:21:42 pushed blob sha256:df8cc18a010481b7cbe7c04532d4969b4264c072d4aa17ca12c198d0bf222a33
2019/06/03 22:21:42 pushed blob sha256:6b2f8b80e4fbec34dccc72b58cb35e3dedd76e1ba57e367d129ae50599c0c7f4
2019/06/03 22:21:42 pushed blob sha256:5a621a3fc672e9d360a3d3728c612a70d758264558bc3fe5b82b627e5c763e46
2019/06/03 22:21:42 pushed blob sha256:68d394e8e0e454f611d71438e79240a9ade152324d2eb9b755d2d1e1d150acc0
2019/06/03 22:21:42 pushed blob sha256:f06abc82ff2f9f750bf1e9dd0ea030abfa70eb3acf66aad1b4e75f35a75b0aeb
2019/06/03 22:21:48 pushed blob sha256:00de8cb14b0fb84f4fe582116b11a9644faf0f97ac456ab06bb0fc7830d9d285
2019/06/03 22:21:53 pushed blob sha256:7b1a53a24ea4c3aeb130cb27691966ac2d0064552c7844035d890ee282ca1d70
2019/06/03 22:22:01 pushed blob sha256:08c91c84c62b82fb3abbf0650d587458f95a9238b555bfe7106d5e8dbe70a7db
2019/06/03 22:22:01 registry.gbates.svc.cluster.local/dev/git-service:a48409e-dirty: digest: sha256:d0e093e733bfbaa806cc8d75a4a5999e4b4aecf103e2cc1b9ee74ffdd92c3ba5 size: 2541
FATA[0073] build failed: building [registry.gbates.svc.cluster.local/dev/git-service]: kaniko build for [registry.gbates.svc.cluster.local/dev/git-service]: getting image: Get http://registry.gbates.svc.cluster.local/v2/: dial tcp: lookup registry.gbates.svc.cluster.local on 192.168.1.1:53: no such host 
```

I think the root issue is that this:
https://github.com/GoogleContainerTools/skaffold/blob/81a56b1be7d34a510f0008eaf50750ce8b2bc14f/pkg/skaffold/build/cluster/kaniko.go#L104

is being called to get the digest for retagging local cache, but won't be used in remote builds:
https://github.com/GoogleContainerTools/skaffold/blob/81a56b1be7d34a510f0008eaf50750ce8b2bc14f/pkg/skaffold/build/cache/save.go#L40-L43

Might make sense to move the digest fetch to `RetagLocalImages`? Need someone to confirm, I'm pretty new to skaffold code and golang in general.

- Skaffold version: v0.30.0
- Operating system:  Windows 10 (WSL)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: registry.gbates.svc.cluster.local/dev/git-service
    context: .
    sync:
      manual:
      - src: '***/*.py'
        dest: /git_service
    kaniko:
      image: gcr.io/kaniko-project/executor:v0.7.0
      buildContext:
        localDir: {}
      cache:
        repo: registry.gbates.svc.cluster.local/dev/cache
  insecureRegistries: [registry.gbates.svc.cluster.local]
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  cluster:
    # pullSecret:
    pullSecretName: docker-config
    namespace: gbates
    timeout: 20m
    dockerConfig:
      path:
      secretName: docker-config
    resources:
      requests:
        cpu: 1
        memory: 500Mi
      limits:
        cpu: 2
        memory: 1Gi
deploy:
  helm:
    releases:
    - name: git-service
      namespace: gbates
      chartPath: charts/git-service
      values:
        # This is how skaffold knows which pods to sync with.
        service.image: registry.gbates.svc.cluster.local/dev/git-service
      overrides:
        service:
          image: registry.gbates.svc.cluster.local/dev/git-service
          pullPolicy: IfNotPresent
          imagePullSecret: ""
        persistence:
          enabled: true
          existingClaim: "git-service-data"
          # storageClass: "standard"
          accessModes:
            - ReadWriteOnce
          size: 10Gi
        config:
          debug: true
```

### Steps to reproduce the behavior

1. Deploy this manifest to a remote k8s cluster:
```yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: registry
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:80
  volumeClaimTemplates:
  - metadata:
      name: registry-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: linode-block-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
  - name: registry
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: registry
  type: ClusterIP
```
2. Update `skaffold.yaml` above to use the FQDN of your registry svc and app deployment.
3. `skaffold run` whatever app you have.

**Comment by gbates101** [comment]
@balopat Gentle bump on this. If this is reproducible and should be fixed, could I take a crack at a PR for this one?

**Comment by nkubala** [comment]
hey @gbates101 thanks for the issue. you make a good point that we don't technically need the remote digest when we're running on cluster builds since we won't be retagging for the local cache anyway, but I'm wondering if there's a way we could fix that call instead of working around that logic for cluster builds. I don't know too much about kube DNS resolution but maybe you could proxy your cluster DNS to your local machine? it would be nice for users to be able to use their FQDNs in their skaffold.yaml and have them "just work".

otherwise, go for it on the PR and we'll see what it looks like!

**Comment by ikogan** [comment]
Should a cluster build require a local docker install at all? I'm forced to do my development in a Windows VM on a machine that doesn't have nested virtualization support. This makes running Docker pretty difficult which is why cluster building is so appealing.

**Comment by dgageot** [comment]
@gbates101 Is the issue still there?

**Comment by bernardelli** [comment]
> 
> 
> @gbates101 Is the issue still there?

I am having the exact same issue.

**Comment by SamyCoenen** [comment]
Same issue here 
`dial tcp: lookup registry.container-registry on 192.168.1.1:53: no such host`

**Comment by gbates101** [comment]
I haven't confirmed whether or not this is working now, but I'm gonna go ahead and close this issue. We've significantly changed our dev setup and have dropped skaffold in the process, so I won't be much of a resource on confirmation, and it does appear that the issue is documented elsewhere (and maybe even fixed).

If anyone is still experiencing this issue, feel free to reopen it.
