### ISSUE TITLE
[Feature Request] API to get the list of skaffold configuration files in a given directory

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#2229]
In order to support multiple skaffold.yaml files from IDEs, it would be good to have an api that returns the list of skaffold configuration files in a given directory.

**Comment by balopat** [comment]
This would be relatively easy to implement a `skaffold find-configs -d <dir>` which would find in a given directory all files that are parseable or upgradeable. It would give back a list of skaffold yamls but also indicating the version and whether they'll need upgrade or not.

**Comment by sujit-kamireddy** [comment]
It would be great. Thanks @balopat .

**Comment by balopat** [comment]
@sujit-kamireddy can you check #2244 and comment?

**Comment by sujit-kamireddy** [comment]
@balopat , I am reviewing it. Thanks.

**Comment by sujit-kamireddy** [comment]
Thanks @balopat for the quick resolution of this issue.
