### ISSUE TITLE
Skaffold not working anymore on Alpine Linux with v0.31.0 release

### ISSUE THREAD

**Issue by math-nao** [GoogleContainerTools/skaffold#2243]
### Expected behavior
Skaffold v0.31.0 commands should work on Alpine Linux as it is working with Skaffold v0.30.0 and below.
 
### Actual behavior
skaffold: not found

### Information

- Skaffold version: v0.31.0
- Operating system: Alpine Linux v3.9
- Contents of skaffold.yaml: N/A

### Steps to reproduce the behavior

1. `docker run --rm -it alpine:3.9`
2. This should return an error: `apk add --no-cache curl && curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.31.0/skaffold-linux-amd64 && chmod +x skaffold && mv skaffold /usr/local/bin && skaffold -h`
3. Previous command for v0.30.0 and below is working

**Comment by briandealwis** [comment]
Maybe from #2006?

**Comment by priyawadhwa** [comment]
@dgageot do you think this could be related to the CGO change that was merged in this release?

**Comment by dgageot** [comment]
@priyawadhwa yes, I'm pretty sure it's due to the CGO thing.

**Comment by dgageot** [comment]
```
ldd skaffold
	/lib64/ld-linux-x86-64.so.2 (0x7f4eb0471000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f4eb0471000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f4eb0471000)
Error relocating skaffold: __vfprintf_chk: symbol not found
Error relocating skaffold: __fprintf_chk: symbol not found
```

Maybe there are options to make sure it's statically compiled.

**Comment by dgageot** [comment]
It looks like we are missing `-ldflags '-extldflags "-static"'`. The Makefile has `GO_LDFLAGS += -extldflags \"${LDFLAGS}\"` but `LDFLAGS` is not configured...
