### ISSUE TITLE
Skaffold build logs while `--quiet`

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2249]
### Expected behavior

It would be great to be able to see the output of the build logs as well, not only the build result json. It would be useful both in a CI/CD and an interactive setting. I'm thinking about the ability to channel the build result to a json file when `--quiet` is not defined.

### Actual behavior

`skaffold build --quiet` just outputs the build results. 

### Information

- Skaffold version: 0.31.-
- Operating system: all

**Comment by twuttk** [comment]
Was about to open a similar issue. We are using skaffold in combination with kaniko in our CI/CD pipeline.

Basically we are doing 
```
skaffold build -- quiet > build.out
change k8s context
skaffold deploy --build-artifacts build.out
```
This results in us being completely blind in regard to the actual build process which makes debugging super annoying.

**Comment by marlon-gamez** [comment]
We now have the `--file-output` flag to achieve this!

@twuttk, your flow can now be changed to this:
```
skaffold build --file-output build.out
change k8s context
skaffold deploy --build-artifacts build.out
```

**Comment by twuttk** [comment]
Thanks for letting me now @marlon-gamez, I tried moving to `--file-output` immediately after I read the release notes. Sadly we encountered an issue (https://github.com/GoogleContainerTools/skaffold/issues/2522) with v0.34.0, hopefully it's just me missing some documentation :)
