### ISSUE TITLE
server.Initialize() returns a nil callback on second call

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2281]
See https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/server/server.go#L87

The second time we call `Initialize()`, for e.g. when a runner is recreated, instead of getting a shutdown callback, we get a `nil` callback. It'll cause a panic [here](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/dev.go#L93).

In fact, I think we should initialize/shutdown the gRPC server only once.

ping @nkubala

**Comment by nkubala** [comment]
I guess we're recreating the runner whenever the skaffold config changes? seems a little weird to me but I guess that's the way we have to handle it. could we memoize the `shutdown()` callback in the server package and return that once we've started up the first time?
