### ISSUE TITLE
sha256 tagger doesn't actually compute checksum

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#2290]
### Expected behavior

`sha256` tag policy computes checksum of workdir contents, and uses this to tag images

### Actual behavior

`sha256` tagger either uses a user provided tag, or uses `latest`.

### Information

this tagger just isn't doing what it's advertised as doing. https://github.com/GoogleContainerTools/skaffold/pull/1482 reworked the tag mechanism to tag BEFORE we build images (which is fine), but we changed the paradigm of the `sha256` tagger to use the checksum of the **directory contents**, not of the image tar itself...except this was never implemented.

one way to implement this would be to walk the working directory, taking the shasum of each encountered file and storing it in a map. then, sort the keys and append the hash strings in a predictable order, and take the final checksum of that string.

**Comment by balopat** [comment]
dupe of #1884?

**Comment by dgageot** [comment]
The `sha256` tagger was indeed changed to basically always use `latest` as a tag. It works because when images names are replaced in yaml files, they are in the form `name:tag@sha256`

**Comment by seblegall** [comment]
@nkubala What do you think of the following function to generate the checksum ? 

```golang
func generateCheckSum(workingDir string) (string, error) {

	var checksum []byte

	err := filepath.Walk(workingDir,
		func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}

			f, err := os.Open(path)
			if err != nil {
				return nil
			}
			defer f.Close()

			h := sha256.New()
			if _, err := io.Copy(h, f); err != nil {

			}
			checksum = h.Sum(checksum)
			return nil
		})

	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%x", md5.Sum(checksum)), nil
}
```
If you are ok with that I could make a PR (even if I don't know yet how I'm going to test that...)

**Comment by dgageot** [comment]
@nkubala @seblegall I don't really understand what this feature would bring. Can you share examples of how that would be used?

**Comment by seblegall** [comment]
@dgageot I've tested it and it seems to work find without that, indeed. My only concern is about the pushed image on a remote registry. I've tested it using docker-for-desktop so I couldn't see the effect on a remote registry. But it's possible that the image is pushed with a tag `latest` on the registry. I'm not sure if it could have an impact other than the impossibility to find an older build on the registry.

**Comment by nkubala** [comment]
@dgageot I guess it just feels weird to me because we're still overwriting the `latest` tag on every build, so even though it is replacing the image in the yaml on every build it's not really a "tag" in the conventional sense. if I cared about all of the images built during a skaffold dev run then I'm out of luck because I only have the very last one that was built.

and in the skaffold logs I see something like 
```
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/k8s-skaffold/skaffold-example:latest
Tags generated in 120.889µs
```

on every build, which feels strange.

**Comment by dgageot** [comment]
@seblegall @nkubala I understand your concerns. I like the simplicity of the current implementation of `sha256`:
 + It's as fast as it can get. It makes the dev loop super tight.
 + It's similar to Docker, used with `:latest` or without a tag. But it doesn't have the same issues since we use the digest in yaml manifests, not just the tag.

Maybe we should have both a `latest` and a `sha256` tagger. wdyt?

Another detail to sort out is that the `sha256` can be provided a tag (defaults to `latest`). Should we have a separate tagger that uses a fixed `tag`?

And finally, I think it would be safe to default to the `latest` tagger instead of the current `git` default. It would be faster and would not complain that the sources are not in a git repo.

wdyt?
cc @balopat

**Comment by nkubala** [comment]
I'm fine with having a `latest` tag, and actually I think I'm a fan of defaulting to `latest` instead of `git`. thinking about it, probably many (the majority?) of users don't care about the intermediate image tags and only care about iteration speed, so that should help there.

in general my primary issue here is that `sha256` as a name is confusing, the functionality makes sense but `latest` seems more reasonable. I'd be fine just getting rid of the `sha256` concept (i.e. @seblegall's new PR) as a tagger.

having a fixed `static` tagger is also an idea, though I really kind of hate the concept of using mutable tags as a way to do iterative development. to me this is bad practice so I'd vote not to encourage developers to do this, but if enough people want it/use this flow I could be convinced.

**Comment by nkubala** [comment]
after much discussion, I'm going to go ahead and close this issue because I'm convinced there isn't anything we *need* to address here. I think that changing the names of the tags to make a little bit more sense might be worth doing, but I don't think it's worth keeping an issue open over.
