### ISSUE TITLE
We need a logo!!

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#232]

**Comment by nilfanif** [comment]
Hi, i am a logo designer and I can make a logo for you, can you give me little brief of how do you want the logo look like?

**Comment by clanstyles** [comment]
What about a bunch of gophers on a bunch of scaffolds orchestrating a crane that is putting colored containers (docker containers) together? I've seen this before with a PaaS but it sorta makes sense here too.

**Comment by nilfanif** [comment]
Isn't that too complicated for a logo. There are too many elements.

Any logos on the internet that you like for inspirations?

**Comment by brotherhod** [comment]
As a suggestion:
[https://www.iconfinder.com/icons/882754/ladder_scaffold_stairs_steps_icon#size=256](https://www.iconfinder.com/icons/882754/ladder_scaffold_stairs_steps_icon#size=256)
with the kubernetes logo somewhere at the top being supported

**Comment by nilfanif** [comment]
Kubernet logo is a trademark of linux foundation, and I don't think we can alter and combine the logo with scaffold for this project. This is the guidelines for the their trademark https://www.linuxfoundation.org/trademark-usage/

**Comment by nilfanif** [comment]
so, I made two version based on the brief you gave.

![image](https://user-images.githubusercontent.com/16274923/38128380-8993f488-3424-11e8-9f6f-2073a675cc4c.png)

and bellow is a friendlier version

![image](https://user-images.githubusercontent.com/16274923/38128386-900525f8-3424-11e8-8379-94755c4e3a56.png)

**Comment by nilfanif** [comment]
those are as simple as it can get, i can add more elements to the logo but it will look terrible in small size

**Comment by nilfanif** [comment]
@dgageot what do you think?

**Comment by dgageot** [comment]
@nilfanif I like the second one better. @r2d4 @dlorenc @viglesiasce any feedback?

**Comment by nilfanif** [comment]
Cool, just let me know if you need any tweaks or refinements

**Comment by dankohn** [comment]
When this is finalized, could you please provide in SVG format. I'd like to include Skaffold in the CI/CD section of https://landscape.cncf.io/grouping=landscape&landscape=ci-cd

If you want to create the entry yourself, please see https://github.com/cncf/landscape#new-entries

**Comment by nilfanif** [comment]
both version in SVG format.

[Skaffold logo SVG.zip](https://github.com/GoogleCloudPlatform/skaffold/files/1904659/Skaffold.logo.SVG.zip)

**Comment by kimsterv** [comment]
I think this is still a bit too busy for a logo with all the lines especially when we shrink it down. Maybe a version with scaffolding designed into the letters?

**Comment by aaronkorver** [comment]
Can there be scaffolding around the letters of "Scaffold"?

**Comment by dlorenc** [comment]
@kimsterv can you link in the logo?

**Comment by dankohn** [comment]
I converted the eps to svg and updated here: https://landscape.cncf.io/grouping=landscape&landscape=application-definition-image-build&selected=skaffold

**Comment by r2d4** [comment]
Awesome thanks @dankohn!!

**Comment by alewis001** [comment]
My 2 pennies worth... I like the logo by @dankohn

**Comment by dankohn** [comment]
@r2d4 made the logo. I just converted to SVG and added to the Interactive Landscape.
