### ISSUE TITLE
Avoid scale down upon rebuild image

### ISSUE THREAD

**Issue by haf** [GoogleContainerTools/skaffold#2341]
I have a deployment registered in Skaffold and am running `skaffold dev`. When I change a file, it updates the docker image, but while it's updating the docker image, Skaffold scales down the number of replicas. I was hoping to avoid this behaviour, since I'm working with the site in between compiles. Otherwise I have to wait one minute every time I save a file, which is bad for productivity, to say the least.

Question on Stackoverflow, if this is an actual feature (couldn't find it in docs or while searching for it): https://stackoverflow.com/questions/56772148/avoid-scale-down-on-updated-files

For example, I update the UI/run UI tests:
![image](https://user-images.githubusercontent.com/193115/60177730-f0056300-9819-11e9-9cbc-9dc143fff7db.png)

**Comment by priyawadhwa** [comment]
Hey @haf, this is definitely weird behavior. We expected the number of replicas to be scaled down to 1 for `skaffold debug` but not for `skaffold dev`. Could you please provide some sample code so we can reproduce this bug?

**Comment by haf** [comment]
Hi, I've moved on from this problem now. Sorry.
