### ISSUE TITLE
Fix microservices example to deploy to healthy state

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2372]
### Expected behavior
Running `skaffold deploy` on example/micro-services should create valid deployments
### Actual behavior
On master run 
```
make install
cd example/microservices
skaffold deploy

```
The deploy command succeeds, but if you look the the deployment, it never stabilizes.
```
examples/microservices: (master)$ skaffold deploy
Starting deploy...
kubectl client version: 1.11+
kubectl version 1.12.0 or greater is recommended for use with Skaffold
service/leeroy-app configured
deployment.apps/leeroy-app configured
service/leeroy-web configured
deployment.apps/leeroy-web configured
Deploy complete in 4.348085116s

examples/microservices: (master)$ kubectl rollout status deployment/leeroy-app
error: deployment "leeroy-app" exceeded its progress deadline'

examples/microservices: (master)$ kubectl rollout status deployment/leeroy-web
error: deployment "leeroy-web" exceeded its progress deadline
```

**Comment by dgageot** [comment]
@tejal29 I assume you meant to run `skaffold run`, not `skaffold deploy`. For `skaffold deploy` to work without any additional argument, you have to make sure both the `gcr.io/k8s-skaffold/leeroy-web` and `gcr.io/k8s-skaffold/leeroy-app` docker images exist.

**Comment by dgageot** [comment]
I'm going to close this one because `skaffold run` does the job
