### ISSUE TITLE
No Linux build of v0.33.0 on release page

### ISSUE THREAD

**Issue by s3than** [GoogleContainerTools/skaffold#2395]
### Expected behavior
Download of linux v0.33.0 should not return 404
### Actual behavior
No linux build
### Information
https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.33.0

No linux assets present

- Skaffold version: v0.33.0

### Steps to reproduce the behavior

1. Go to releases https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.33.0
2. No linux version, however the sha is present
3. Try downloading from https://github.com/GoogleContainerTools/skaffold/releases/download/v0.33.0/skaffold-linux-amd64
4. get 404

**Comment by dgageot** [comment]
ping @balopat

**Comment by dgageot** [comment]
I've updated the GitHub release page
