### ISSUE TITLE
Add box as alternative builder

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/skaffold#241]
[box](https://box-builder.github.io/box/) is a nice alternative to `Dockerfile` with Ruby syntax, it maybe a good idea to consider adding it as an option.

cc @erikh

**Comment by erikh** [comment]
hi! thanks Ilya, please let me know if I can answer any questions.

**Comment by r2d4** [comment]
Is box just a different frontend for the docker daemon? 

We're interested in supporting alternative frontend configs other than dockerfiles. Theres a bit of work to decouple the current skaffold codebase from the dockerfile, but its something on our roadmap.

**Comment by erikh** [comment]
Yes it is now. OCI and runc support are planned, but I have been
preoccupied with work.

**Comment by dgageot** [comment]
I'm going to close this one. When builders become plugins, it will up to the community to provide more builders.
