### ISSUE TITLE
Add support for Kustomize Kustomization resources

### ISSUE THREAD

**Issue by jmcclell** [GoogleContainerTools/skaffold#2416]
As of version 2.1, Kustomize has deprecated the concept of "bases" in favor of combining the concept into the "resources" array by enforcing merge order. This means that as of 2.1, a resource can refer to a Kustomization (a directory containing a kustomization config at its root) rather than simply a file. This means that Skaffold's Kustomization support needs to be expanded to treat resources as if they are potentially bases in order to properly construct the dependency array for file monitoring.

This also tangentially relates to Issue #2082 (fixed in PR #2269), as the handling of resources needs to to take into account the possibility that they may now be remote just like bases were.

**Comment by jmcclell** [comment]
@dgageot This is probably actually a bug rather than a feature request, because today if you use version 2.1 and opt to use the new resource functionality rather than bases, Skaffold won't properly watch all the files as it won't follow the dependency tree. I'm putting a PR together now.

**Comment by dgageot** [comment]
great

**Comment by jmcclell** [comment]
Closed by the merge of #2420
