### ISSUE TITLE
support kustomize remote resources

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#2421]
issue #2082 was closed with https://github.com/GoogleContainerTools/skaffold/pull/2269, but while doing it bases were removed from kustomize. code in that pr needs to be somehow :tm: mangled to support the :latest of the :latests.

opening this issue on behalf of @dgageot  https://github.com/GoogleContainerTools/skaffold/pull/2269#issuecomment-508515009 who owns me a :beer: now

**Comment by jmcclell** [comment]
@matti Duplicate of #2416, which is addressed in #2420
