### ISSUE TITLE
feature request: support callback for custom actions

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#2425]
It would be awesome if skaffold would support callbacks for lifecycle hooks.
Skaffold will publish lifecycle events, and allow the user to hook into these events by running a custom command/script when they occur.

IMHO These callbacks can have major befits for the development / deployment process, and make skaffold a true "one stop shop" tool.

some examples - 

1. create a `beforeDev` callback, which will allow the user to copy some files from a specific location before running `skaffold dev`. This will allow the user to copy files which are required for building the artifact, but exists in another location and can't be copied into a docker image, since they're not in the docker daemon context. 

2. create a `afterDevDeployment` callback, which will allow the user to run a custom command after the deployment is done when running the `skaffold dev` command. This action can help in many different ways, such as to create mock data for dev environments, triggers UI automation tests, and many other things.

#### why not use a wrapper
One could argue that these actions can be achieved with a simple wrapper before / after running skaffold. However, some actions (such as `dev` or `debug`) run in continuous mode, and can't be easily moved to the background.

#### suggested lifecycle hooks callbacks   
(wrote for dev but can be relevant for any other command) - 
1. beforeDev - trigger before the dev command
1. afterDevError - trigger after an error has occured
1. afterEachDevDeployment - trigger after each deployment is done
1. afterDevDeployment - trigger after the initial dev deployment
1. afterDev - trigger after existing from dev command watch mode

**Comment by nthypes** [comment]
Maybe close in favor of #1441 ?

**Comment by giladsh1** [comment]
closing in favor of #1441
