### ISSUE TITLE
Ignore kustomization.yaml when using kubectl deployer

### ISSUE THREAD

**Issue by poikilotherm** [GoogleContainerTools/skaffold#2432]
### Expected behavior
When using a `kubectl` deployer with 
```yaml
deploy:
  kubectl:
    manifests: ["k8s/*.yaml"]
```
or similar, deploymens should succeed, as `kustomization.yaml` files are filtered from the glob match.

### Actual behavior
When a `kustomization.yaml` is present in the manifests, validation will fail due to kubernetes-sigs/kustomize#738. This will fail deployment, too, while `kubectl` is otherwise only printing warnings, but deploying everything else.

### Information

- Skaffold version: 0.33.0
- Operating system: Linux
- Contents of skaffold.yaml: see above

### Steps to reproduce the behavior

1. Create a Kubernetes object and add a `kustomization.yaml` file
2. Create a small Skaffold config using the kubectl deployer as described above 
3. Watch `skaffold run` fail, as validation fails for kustomization.yaml

**Comment by balopat** [comment]
Hi @poikilotherm, thanks for opening this! 

1.) I'm not sure that hard coding excluding kustomize yamls is the direction we'd like to go - however if we'd support an `exclude: kustom*.yaml` would solve your problem. 
2.) if you are using kustomize did you try using our kustomize deployer?

**Comment by poikilotherm** [comment]
Hi @balopat thanks for coming back to me.

Ad 1) an `exclude` option sound great, might be beneficial for others, too. Supporting arrays of globs would be a great enhancement.

Ad 2) I would like to keep things not depending on `kustomize` and I dislike the necessity to install it, as I wrote in #2431 which is a dup of #1781. So, no, I did not yet use the `kustomize` deployer... :wink:

**Comment by corneliusweig** [comment]
Another approach would be to follow the semantics of dockerignore files, where a `!` prefix inverts the match. So for example:
```yaml
manifests:
- k8s/*.yaml        # includes all yamls
- '!**/kustomize*'  # excludes kustomize
```
Or is that too magic?

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.

**Comment by Schachte** [comment]
I'm also interested in this feature. Any thoughts on reconsidering?

**Comment by nkubala** [comment]
@Schachte we recently added functionality to use kubectl's built-in kustomize when the standalone binary isn't present on the host, which might enable you to use our `kustomize` deployer without having a hard dependency on `kustomize` itself. have you given this a shot?
