### ISSUE TITLE
FATA[0268] listing files: listing files: file pattern [ ... ] must match at least one file

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2433]
### Expected behavior

Skaffold should just still respect the dependencies inferred from the Dockerfile and retry to watch again, even if the file/folder is temporarily deleted.  

### Actual behavior

Currently we are failing: 

````
FATA[0268] listing files: listing files: file pattern [<redacted>] must match at least one file
````

### Information

- Skaffold version: 0.33.0
- Operating system: Linux
- Contents of skaffold.yaml:

```yaml
...
simple artifact  
...
```

`Dockerfile` has a COPY of a whole directory

### Steps to reproduce the behavior

1. start `skaffold dev`
2. delete the original directory that is being copied

**Comment by balopat** [comment]
cc @saturnism

**Comment by dgageot** [comment]
I've tried to reproduce and I'm not sure I understand the issue:

 + If `skaffold dev` is not able to find the dependencies on the first build than it's going to fail fast. The docker build will fail anyways.
 + If the files are deleted after the first build, then skaffold will just complain that it can't build but will continue to watch files for changes.

Is that correct? Do you think we should not fail the first build?

**Comment by balopat** [comment]
@saturnism it must have been the first build. It is a 3 artifact (2 jib and 1 node + Dockerfile based) project running on kind and image loading was slow (~58 seconds to load the image to kind!)...I guess we didn't wait until it finished...? It definitely felt jarring as a UX :)

**Comment by balopat** [comment]
I reproduced it on 0.33 but it is fixed on master for some reason... :D

**Comment by dgageot** [comment]
@balopat can the issue be closed then?

**Comment by balopat** [comment]
We can close this as it is fixed on master, we confirmed with @saturnism.
