### ISSUE TITLE
Switch to using go modules

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#2451]
[Go modules](https://github.com/golang/go/wiki/Modules) are nicer than `dep` for handling dependency management. We should switch skaffold over to use them.

**Comment by dgageot** [comment]
@nkubala are you working on it or can I take the action?

**Comment by nkubala** [comment]
@dgageot I haven't started on it yet, if you wanna take it on go for it

**Comment by dgageot** [comment]
@nkubala I tried a bit and failed! I've unassigned myself.

**Comment by SantoshSah** [comment]
Any work around using Skaffold in Go Module project till you natively support it? How can we ignore some files to be watched by Skaffold?

**Comment by nkubala** [comment]
closed with https://github.com/GoogleContainerTools/skaffold/pull/2541
