### ISSUE TITLE
tag policy has no effect on cached artifacts

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2457]
When an artifact is found in the cache, the tag that's computed by the tag policy is not used to reference it in yaml manifests. The sha256 digest is not appended either.

See here: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/runner/build_deploy.go#L38

**Comment by dgageot** [comment]
@priyawadhwa I believe we should try to avoid tagging artifacts with their workspace hash. That would reduce the code complexity, avoid issues like this one and reduce the number of tags Skaffold produces.

Do see any important use case that would not be possible if we do that?

**Comment by priyawadhwa** [comment]
Nope, I think that should work.

**Comment by dgageot** [comment]
Fixed with https://github.com/GoogleContainerTools/skaffold/pull/2470
