### ISSUE TITLE
Improve documentation for `skaffold diagnose`

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2465]
When working with Skaffold profiles, it would be illustrative to see what the effective `skaffold.yaml` is that Skaffold works with. AFAIK Skaffold does currently not support this, but I think this is quite important for debugging.

For example, `skaffold fix` could have a `--flatten` mode and accept a list of profiles to show the effective yaml. WDYT?

**EDIT** It turns out, `skaffold diagnose` already does that. Therefore I relabeled the issue to improve the diagnose docs.

**Comment by dgageot** [comment]
@corneliusweig I think `skaffold diagnose` does that

**Comment by corneliusweig** [comment]
@dgageot woops! Didn't know that. Thanks for nudging me in the right direction.

What do you think about mentioning this in the short description of `skaffold diagnose`? At the moment it just says

> Run a diagnostic on Skaffold

Maybe something like

> Run diagnostics on Skaffold and print the effective config

Additionally, it could get a long description.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
