### ISSUE TITLE
Skaffold config's flag `--config` is useless

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2468]
The subcommand `skaffold config {set,list,unset}` each have a flag `--config` which overrides the default location of the global skaffold config (`$HOME/.skaffold/config`).

Although this works nicely with `skaffold config`, none of the other Skaffold subcommands support to specify the location of the global config. Therefore, the flag is useless in its current shape.

I see two options:
1. Remove the `--config` flag for `skaffold config`, and _always_ use the default location
2. Add the `--config` flag to all other Skaffold subcommands.

My preferred solution would be 1), because
- nobody seems to rely on it anyway
- it avoids further confusion with `skaffold.yaml`
- by nature, global configurations should have global scope, so there is no need to have different sets of global configs.

WDYT?

**Comment by balopat** [comment]
Ah, facepalm, this is an ugly inconsistency indeed. 
I think 2) is better, because it enables other tools like IDEs when integrate with Skaffold to store their own config file. Maven is an interesting example here, where you can have ~/.m2/settings.xml defined globally for interactive use cases but IDEs typically have their own settings.xml.

**Comment by nkubala** [comment]
`--config-file`?

**Comment by corneliusweig** [comment]
@nkubala I fear that `--config-file` may be too similar to `--config` and confuse people.

**Comment by corneliusweig** [comment]
@nkubala I went with `--config` in #2555, because it is most consistent with `skaffold config`

**Comment by LEQADA** [comment]
@balopat @corneliusweig is it possible now to set a custom maven settings.xml file?

**Comment by corneliusweig** [comment]
@LEQADA These flags only refer to Skaffold configuration.
