### ISSUE TITLE
Schema upgrade mechanism fails to upgrade profiles by default

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2469]
Currently, the schema upgrade mechanism works by implementing the `VersionedConfig` interface:
```go
type VersionedConfig interface {
	GetVersion() string
	Upgrade() (VersionedConfig, error)
}
```
The responsibility of `Upgrade` is to migrate the whole config from one version to the next. This opens the possibility for a class of bugs, where the main pipeline (`SkaffoldConfig.Pipeline`) is migrated to a new version, but none of the pipeline configs in the profiles `SkaffoldConfig.Profiles[*].Pipeline` (see for example #2415). If there are use-cases where profile-pipelines need to be upgraded differently than the main pipeline, the following suggestion is void.

Suggestion
----

Add a new interface
```go
type SkaffoldPipeline interface {
	Upgrade() (SkaffoldPipeline, error)
}
```
which upgrades a given pipeline to the next version. In addition, add an upgrade helper which migrates the main pipeline _and_ all profile pipelines to the next version.
This will be backwards compatible with skaffold schema versions before the `Pipeline` structure was introduced.

**Comment by dgageot** [comment]
I like that!
