### ISSUE TITLE
Watch for changes in libraries?

### ISSUE THREAD

**Issue by dimovnike** [GoogleContainerTools/skaffold#2471]
Hello,
I am new to kubernetes and skaffold. I have a question: what is the best way to organize a project that has 2 services using same library?

I have 2 services that use same library, and I need it to react to the changes in the library code (rebuild affected artifacts). Is this possible with skaffold?

I tried building the library as a separate docker image but i encountered following problems:
1. Could not find a way to specify a build order or dependency. So when i run skaffold dev the first artifact can not find the library image  because it is not build yet.(The order seems random, is there a rule for the build order?)
2. Can not pass default-repo var to the docker build command so I can use correct FROM in the Dockerfile.

Is this doable? Are there better way of doing this?
Thanks.

**Comment by dimovnike** [comment]
There is also a problem that library image is built with a certain tag but that tag can not be passed into dependent images (in the FROM).

**Comment by tejal29** [comment]
@dimovnike Thank you for your question. 
Currently, we don't have a way to specify artifact dependency. Its on our radar and we are looking to implement it as part of https://github.com/GoogleContainerTools/skaffold/issues/2717

right now you can achieve build order in locally.
- Use local builder.
```
build: 
  local: {}
  artifacts:
    - image: lib
 
   - image: service1

  - image: service2 
```

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!

**Comment by nkubala** [comment]
I'm gonna reopen this one cause I think it's related to modules.

**Comment by gsquared94** [comment]
Sorry for not getting to this earlier, but we released `build dependencies` support that allows defining dependencies between artifacts and ensuring build ordering. Take a look at this [tutorial](https://skaffold.dev/docs/tutorials/artifact-dependencies/). This should exactly solve your problem, let us know if you have problems setting it up.
