### ISSUE TITLE
Dev mode: should we redeploy unchanged manifests

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#249]
Every manifest is reapplied on each rebuild, so we continuously redeploy unchanged manifests. It should be no-op. Sometimes it isn’t. That's not Skaffold's fault but Skaffold's behaviour make the issue very visible.

For example, with Istio 0.4.0, RouteRules fail to be reapplied with the same settings.

Should we ignore that or try to not redeploy unchanged manifests? In my case, until this bug is fixed in Istio, I can’t easily use skaffold.

**Comment by r2d4** [comment]
This is a little tough. Most resources such be declarative in Kubernetes. In this case, should we have an istioctl deployer?  Maybe we could support multiple deploy stanzas if really needed

**Comment by dgageot** [comment]
OK, let's consider two behaviors:
 1. We always redeploy all the manifests:
     a. All of them are indeed idempotent -> Everything is ok
     b. Some of them are not idempotent because they are buggy -> The user can't use skaffold because of a bug that's not due to skaffold -> The user might stop using skaffold because of something we can't improve.
 2. We only display changed manifests (in a dev loop that is):
     a. All of them are indeed idempotent -> Everything is ok. We avoided a few no-ops.
     b. Some of them are not idempotent because they are buggy -> The dev loop works as expected by the user.

I'm currently stuck in state 2.b and it drives me nuts that a bug outside of skaffold scope blocks me from using skaffold.

With regards to deploying with istioctl. That's not something I'm doing outside of skaffold so I don't expect to do that with skaffold. That said it's a good idea.

**Comment by dgageot** [comment]
Let's close this one
