### ISSUE TITLE
Skaffold grpc event api endpoints not working in 0.33

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#2493]
Related to https://github.com/GoogleContainerTools/skaffold/issues/2435

As noted in the issue above, with skaffold version `0.31 - 0.33` (inclusive), the HTTP event API endpoint was changed from `event_log` to `event`. This required a workaround in VS Code which consumes the HTTP API.

IntelliJ uses the GRPC flavor of the API, and I'm noticing the following behavior (which does not match what I see with the HTTP API):

`event_log` works in all versions up `0.32`. It does not work in `0.33`.
neither `event_log` nor `event` works in version `0.33`

Tested using the latest [proto](https://github.com/GoogleContainerTools/skaffold/blob/eb9b9ec01aab85c07830aed559f65fb3cfe1556c/proto/skaffold.proto)

**Comment by etanshaul** [comment]
closing temporarily as I'm seeing inconsistent results. Will reopen once I can validate the information above.

**Comment by etanshaul** [comment]
Update: I was testing using `skaffold debug`. The reason I hesitated and closed the issue is because of an inconsistency in the API between `dev` and `debug`:

For the HTTP API:

**Setup**

Skaffold version 0.33
Command: `skaffold debug`

**Expected**
HTTP API is open on `localhost:{port}/events`

**Actual**
No HTTP API open on either `localhost:{port}/events` or `localhost:{port}/event_log`

By contrast, running `skaffold dev` with the same setup, the API is up on `localhost:{port}/events`

I'm still trying to untangle what this means in the context of the original issue described here. But reopening in case this helps.

**Comment by balopat** [comment]
Thank you for opening this, Etan, this is messy :/

**Comment by dgageot** [comment]
Do you pass the command line flags to activate the api? Or do you expect it to be on by default?

**Comment by balopat** [comment]
The renaming part is already in and will be released tomorrow with 0.34 - we closed https://github.com/GoogleContainerTools/skaffold/issues/2435.

**Comment by etanshaul** [comment]
I think the most immediate concern is if the grpc api works with skaffold debug (otherwise debugging won’t work); either out of the box as it was before, or with some workaround we can put in for the IDE.

I will check this as soon as I get into the office and report back.

**Comment by etanshaul** [comment]
I see the `--enable-rpc` flag now in the docs and that by default it the API is only enabled for `dev`. Looks like we weren't setting this previously.

Tentatively, it looks like adding this flag fixes the grpc api for all versions.

**Comment by etanshaul** [comment]
closing since I think everything is resolved via either setting the `--enable-rpc` flag or the fix in #2435 for the HTTP API. Also this issue is a bit messy, so will reopen a more focused one if needed.
