### ISSUE TITLE
Refactor GetAvailablePort to PortBroker

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2503]
Currently, we use [GetAvailablePort](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/util/port.go#L37) in two places:
1. To get local ports for port-forwarding
2. To get a port for the event API ([here](https://github.com/GoogleContainerTools/skaffold/blob/299c21389bb9cf413e494e334fb499cb7c543a74/pkg/skaffold/server/server.go#L57))

We pass in a generic map interface to work with both of these, but this is unnecessary since `server.go` passes in an empty map as a placeholder.

We should refactor this function and create a type `PortBroker` which will handle getting and storing local ports for all of skaffold, so that multiple parts of the code using local ports won't step on each others toes.

This should also fix the issue of copied unit tests from #2593 in `entry_manager_test.go` and `port_test.go`

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
