### ISSUE TITLE
getting started: macos: unknown api version: 'skaffold/v1beta13'

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#2507]
https://skaffold.dev/docs/getting-started/#installing-skaffold

Following the above instructions

I run `brew install skaffold` and then clone the project and go into the getting-started example, then do a `skaffold dev --default-repo [mycustomrepo]`

```
==> Summary
🍺  /usr/local/Cellar/skaffold/0.33.0: 8 files, 57.4MB
```

```
WARN[0005] Your Skaffold version might be too old. Download the latest version (0.34.0) at https://storage.googleapis.com/skaffold/releases/latest/skaffold-da
rwin-amd64
FATA[0005] creating runner: parsing skaffold config: unknown api version: 'skaffold/v1beta13'
```

If the `brew install skaffold` command apparently doesnt get the correct version for this example

**Comment by balopat** [comment]
Thanks for opening this - there is a bit of lag between the github release and the brew package update: https://github.com/Homebrew/homebrew-core/pull/42199 
When this happens, you can always download the latest release from the main GCS bucket: https://skaffold.dev/docs/getting-started/#installing-skaffold
Can you check now? It should be fine!
