### ISSUE TITLE
Activate caching by default

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2511]
At some point when we are confident that it's stable, we should activate artifact caching by default.

**Comment by dgageot** [comment]
@GoogleContainerTools/container-tools How do you think we should get into that state of confidence? (I'm pretty confident myself)

**Comment by priyawadhwa** [comment]
I was looking through the list of issues in #1740 and almost all of them are resolved, so I feel pretty good about turning on caching by default.

The ones I think we need to address at some point are:

1. store artifacts in cache as they are built (in case a user cancels in the middle of a long build, we don't want to start over)
1. tags provided with --images to skaffold deploy are kinda ignored. (we may not want to do anything about this, but I think it's worth thinking about)

I don't think either of these should block turning on artifact caching by default.
