### ISSUE TITLE
Exec into a pod

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#252]
Could we add a `skaffold exec` command to attach to a running pod?

**Comment by r2d4** [comment]
What functionality would we gain over kubectl? 

I'm for this idea, but we have to deliver a better/different experience than kubectl otherwise we should probably defer to that.

**Comment by dgageot** [comment]
We'd have to make it work without specifying the pod name. Not sure we can do that though...
Even if we gave a name to the artifacts, those would not map pods.

**Comment by r2d4** [comment]
Exec actually works at the container level with pods by picking the first container in the pod afaik.

We could parse the artifacts, and then either

1. exec into the container if there is only one artifact running in the cluster
2. give a user a list of containers they can exec to based off config artifacts

**Comment by dgageot** [comment]
That's true we could do that.
 + Best case scenario, only one pod runs for a given image and this pod has a single container.
 + The pod has multiple containers. We have to ask the user which one to connect to. Same UX as `kubectl exec`
 + Worst case, multiple pods use the same image. We'd have the user specify the pod name and the container name. Back to what `kubectl exec` forces you to do.

**Comment by dgageot** [comment]
Let's close this one since it's out of scaffold's scope to reimplement all the commands of kubectl

**Comment by brpaz** [comment]
I know this issue has been closed, but just my 2 cents.
I think abstract kubectl commands like exec, logs etc in skaffold makes perfect sense.  During development  I want the process to be simplest as possible for new devs. .I dont want them to have to kwown when to use  skaffold commands and kubectl commands. With docker-compose its  just one comamnd for everything. you dont have to know the lower level docker  commands.

Tools like skaffold, draft, telepresence are steps in the right direction, but for now nothing beats the simplicity of docker-compose for development.

**Comment by bhack** [comment]
@brpaz I was trying to collect some of the requirements with a similar scope at https://github.com/GoogleContainerTools/skaffold/issues/913. Please add your feebacks there if you want.
