### ISSUE TITLE
Can we see the logs of a deployment when not in dev mode

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#253]
Adding a `skaffold logs` command would do the trick

**Comment by r2d4** [comment]
Would need to take a slice of containers to stream from. SGTM

**Comment by mmarchetti** [comment]
It would be great to see the log output from `skaffold run` and not just `skaffold dev`. I don't run dev mode because I prefer to control when the build/deploy cycle happens, but I really like the unified log stream.

**Comment by balopat** [comment]
hey all, trying to clarify this a bit further - there seem to have two use cases: 

@mmarchetti are you thinking about a `skaffold run --tail` type of command? 
@dgageot  `skaffold logs` would be a separate command similar to `kubectl logs` right?

**Comment by dgageot** [comment]
I really like the `--tail` flag more than the `skaffold logs` command

**Comment by priyawadhwa** [comment]
Sounds good, I'll get started on this with the flag then!

**Comment by priyawadhwa** [comment]
Just to clarify -- do we want a continuous log stream (like with `skaffold dev`), or to print out whatever logs there are once after deployment?

**Comment by balopat** [comment]
`--tail` would be a continuous log stream until Ctrl+C.

**Comment by priyawadhwa** [comment]
Thanks @balopat !
