### ISSUE TITLE
Logs should stay muted when a build fails in the dev loop

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2530]
Run `skaffold dev`. Wait for the app to be deployed. Break a Dockerfile. The user should see the error and the logs should be muted until the build is repaired.

Logs are currently unmuted.

**Comment by balopat** [comment]
+1 and we should write tests for this.

**Comment by nkubala** [comment]
@dgageot I'm not seeing this issue on the examples in the repo. can you tell me what you did to reproduce this?

**Comment by dgageot** [comment]
@nkubala I failed to reproduce with our samples. However, it's easy to reproduce with https://github.com/GoogleCloudPlatform/microservices-demo. What happens is that the [doDev](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/runner/dev.go#L35) code is sometimes called when there's no change. This mutes and unmutes the logs. Which is an error because by muting for no reason, we might lose a few logs and by unmuting for no reason, we might unmute logs that were stopped because of a build error.

**Comment by nkubala** [comment]
this was fixed with #2592
