### ISSUE TITLE
Too many flags

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2531]
I think we have way too many flags in Skaffold. We should try hard to move some of them to the skaffold.yaml.

**Comment by cbrintnall** [comment]
I'm particularly interested in cleanup moving to the yaml file. Not everyone realizes cleanup is default behavior and could accidentally remove quite a bit. It'd be nice to have a `global` section with some of the flags living there.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
