### ISSUE TITLE
Applying tags on GCR with 'skaffold run' not working as expected

### ISSUE THREAD

**Issue by btardell** [GoogleContainerTools/skaffold#2534]
I want to apply multiple tags on GCR with:

>skaffold run --profile dev -t tag-1 -t tag-2

No error, but "tag-2" is the only tag applied.

>skaffold version
v0.31.0

**Comment by balopat** [comment]
Thank you for opening this! Skaffold behaves similarly to docker here - only a single tag and tagpolicy is available currently. If you're interested in multiple tags, there is an issue open for that: https://github.com/GoogleContainerTools/skaffold/issues/622 please comment on it too! 

Apart from multi-tagging, I could see how this is confusing and maybe we should throw an error when a non-array valued flag is defined more than once.

**Comment by balopat** [comment]
On second thought - this is not that different from for example how `git` or `docker` is handling multiple flags. Not sure we want to put extra validation on top of the CLI framework, cobra. 
Thus, I'm closing this in favor for #622, and I'll add an extra comment there to support array valued flag version too.
