### ISSUE TITLE
Deployers need better documentation for tag behaviour

### ISSUE THREAD

**Issue by poikilotherm** [GoogleContainerTools/skaffold#2547]
### Expected behavior
Replace image tags, also "full qualified image" is used, at least when using `kubectl`. Maybe have a configuration option per image.

### Actual behavior
Working as designed in #565.

The behaviour described in #565 was very counter-intuitive to me. It is not described in [the docs](https://skaffold.dev/docs/how-tos/deployers). You will only see the error message
```
WARN[0002] image [iqss/dataverse-k8s] is not used by the deployment
```
which will leave you quite puzzled.

I understand why #565 is implemented. On the other hand it is good and common practice, to use tagged deployments for your environments. You are using a tag for the development env, right?

IMHO this should be
1. documented
2. user choice "global" and per image. (Having #565 as default, but overridable)

I don't want to change my deployment objects I also use for production, just because of a fixed policy in a dev tool. This is a blocker.

### Information

- Skaffold version: 0.34.0
- Operating system: Linux
- (Partial) contents of skaffold.yaml:

```yaml
build:
  artifacts:
  - image: iqss/dataverse-k8s
    context: .
    docker:
      dockerfile: docker/dataverse-k8s/dev-glassfish/Dockerfile
  local: {}
```
- Relevant parts of deployment object:
```
spec:
  template:
    spec:
      containers:
        - name: dataverse
          image: iqss/dataverse-k8s:4.15.1
```

**Comment by corneliusweig** [comment]
If I understand correctly, you want to use your production manifests (with tagged images) as input to run your app with Skaffold. From a workflow perspective, this seems the wrong way to me. Here is why: when releasing new a new version, you need to apply new image tags in your prod manifests, so the input files get changed all the time.

It would be preferable to generate the production manifests (with updated image tags) from some static input manifests. This is what `skaffold run` or `skaffold build`+`skaffold deploy -a ..` does. These commands do not show the rendered manifests though. They used to do that for a while but it was removed.

You seem to prefer when you the a grip on the manifests that are going to be applied. Would it help, if there were a `skaffold deploy --dry-run`, which prints all the manifests?

**Comment by poikilotherm** [comment]
Hi @corneliusweig,

thanks for coming back to me.

I somewhat disagree with your PoV, IMHO being Skaffold-centric. There are multiple places where the "best practice" of using tagged images for Kubernetes deployments is referenced. Some (strong?) examples:
* https://kubernetes.io/docs/concepts/configuration/overview/#container-images
* https://www.weave.works/blog/kubernetes-best-practices

My humble, yet strong and opinionated opinion and cents on this:

1. For running in production, you don't want untagged which is `:latest` due to image pull policy, rollback etc. IMHO one should not offer production-ready deployment objects for a project, violate best practices and just say "well, use Skaffold". Tools IMHO should respect upstream best practices and if the differ, it should be well documented and ideally offer an option to stay aligned. 

2. Not everybody might be allowed to use such a tool or has their own toolchain. And looking back to the history of the K8s universe, a lot of tools came, some stayed, many died. Skaffold might cease one day, so one should add it as an *option*, not as a hard *requirement*.

3. It is always a good habit for a tool to be adaptable to user needs. I don't want to change the default, just have more option in a promising tool.

4. About the workflow: Skaffold is a bare *dev* tool for me. Deployment to production will not happen with Skaffold, there are other toolchains in place. I follow GitOps for this, so the repo is the source of truth. Needing an extra step to generate the real manifests from a (versioned) Skaffold manifest is bad practice IMHO, see 2. (To be precise: there is already kustomize in that chain, but this is now in upstream with `kubectl apply -k`. Before that I didn't use it... :wink: )

5. Changing the descriptors will happen anyway - the labels need to be adapted, too. And any changes, be it lables, image tags or other are easy to `kubectl apply`.

**Comment by corneliusweig** [comment]
Hey @poikilotherm, if I gave the impression that you should run prod with untagged images, I'm sorry for that. This is not what I meant. Instead, what I was trying to say is that it should be preferred to generate the ready-to-use production manifests (_with_ tags) from static input manifests (_without_ tags).

As you said, kustomize is a tool which does that, but it can also be achieved with Skaffold (even though you only use it for development so far).

Even when using kustomize, there is still the problem of applying the correct image tags in the kustomize overlays. If you don't want to use Skaffold as a deploy tool, there is currently no way to dump the patched manifests. However i think that may be useful for others and for debugging.

**Comment by frejonb** [comment]
I think the current behavior is based on the statement (from https://github.com/GoogleContainerTools/skaffold/issues/565#issuecomment-390097364):
> Images with fully qualified names (tag or digest) should be left untouched. The user clearly indicated that they want to use a very specific version of the image. That's what need to be fixed.

which is too opinionated on what the user is actually intending to do. I think the correct solution is to allow the user specify the actual path (in the manifest) that skaffold should replace with the just built images.

**Comment by corneliusweig** [comment]
@frejonb Can you give an example of how you would imagine this matching procedure? One thing that works very nicely for the great majority of users is the automatic matching of images in manifests with artifacts built by Skaffold. Whatever option we provide must not impact this seamless user experience for most of Skaffold users.

**Comment by frejonb** [comment]
@corneliusweig One idea would be similar to the pod syncing API. Say we have `manual` and `infer (default)` options, then we could do something like

```yaml
deploy:
  kubectl:
    replaceImages:
      manual:
        - path: /spec/template/spec/containers/0
          name: gcr.io/k8s-skaffold/example
```
where `name` refers to the `image` under `/build/artifacts/<n>`, i.e. not including tags that skaffold might add during build.

**Comment by corneliusweig** [comment]
@frejonb Would you care to write this up in a design proposal? The current issue is not the right place to have this discussion, I think.
Design proposal are the best place to discuss alternatives and decide whether this is needed at all. You find a template and some examples in `docs/design_proposals`.

**Comment by nkubala** [comment]
I'm not sure what else is actionable on this issue apart from documentation, and we have docs that hopefully provide some clarification on tagging at https://skaffold.dev/docs/how-tos/taggers/, so I'll close this issue now. if people are running into specific issues with the way skaffold creates and replaces tags, please open another issue.
