### ISSUE TITLE
`debug` should provide option to remove capping replicas to 1

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2553]
`skaffold debug` should offer some way to not cap replica counts to 1 instance.

**Comment by briandealwis** [comment]
Background: with Cloud Tools for Eclipse and IntelliJ, we forced the number of _module instances_ to 1.  A module (now known as a service) is somewhat like a deployment with an unlimited number of replicas: App Engine will automatically add new instances of a module/service as required.  In [(re-)enabling the cap](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/498), I noted:
> I restored [the limit] in [#657](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/657) as you get some confusing behaviour when hitting a breakpoint. If you're using a browser to invoke the endpoints, browsers will oftentimes test-fetch the URL; since the existing request hasn't completed, the dev_appserver launches a new JVM to handle the test-fetch. We need to provide some UI to allow the user to change the max-instances.

Another later justification was to [limit the number of JVMs appearing in the debugger](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cloud-tools-for-eclipse-external/rodaHBRnQJg/NjQ2HSk-CQAJ).

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and if it does still exist, it doesn't seem to be getting any traction at the moment. If this issue appears in the most recent release of Skaffold, please feel free to add a follow-up comment and we will see about getting it prioritized appropriately.

If someone sees a similar issue to this one, please create a new issue, but do include a link to this issue if possible. 

Thank you for sharing this issue with us!
