### ISSUE TITLE
init: Add default skaffold-config name?

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2556]
Since https://github.com/GoogleContainerTools/skaffold/pull/2437 the `skaffold.yaml` can have a `metadata.name` field. With upcoming changes for configurable kubecontext, this name-field needs to be set when creating a project-kubeContext relation (see https://github.com/GoogleContainerTools/skaffold/pull/2384#discussion_r303346094 for details).

So far, `skaffold init` is completely ignorant about this field, but I think we can make our users' lives easier if `init` takes care of the name field. There are two basic options:

1. Prompt the user for a name (with a suggestion). The downside here is that `skaffold init` will obviously require more user interaction.
2. Provide a sane default without prompting the user.

Both options need a sane default. A reasonable default value could be to use the directory basename of the current working dir.

So what do you think? Should `skaffold init` do that, and what should be the default?

**Comment by nkubala** [comment]
yeah I think we should try and have as little user input in `skaffold init` as possible. i'm fine with putting a default in, your suggestion of the current directory basename seems reasonable to me.
