### ISSUE TITLE
skaffold helm sync fails with warning

### ISSUE THREAD

**Issue by amurdock** [GoogleContainerTools/skaffold#2559]
### Expected behavior
files sync to container without a rebuild when updated

### Actual behavior
skaffold fails to sync files, prints warn log

### Information

- Skaffold version: v0.34.1
- Operating system: macOS 10.14.5 (18F132)
- Kubernetes: v1.10.11
- Docker: 18.09.2
- Minikube: v1.2.0
- Helm: v2.13.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: amurdock/node
    context: packages/node
    sync:
      manual:
      - src: 'index.js'
        dest: '.'
deploy:
  helm:
    releases:
    - name: skaffold-helm-example
      chartPath: k8s
```

- Output:
```
DEBU[0007] Found dependencies for dockerfile: [{index.js /root true}] 
INFO[0007] files modified: [packages/node/index.js]     
Syncing 1 files for amurdock/node:61b03bf18376cb8ce916213e632e505849b114d7e409c0a71dcabdceaaf73129
INFO[0007] Copying files: map[packages/node/index.js:[/root/index.js]] to amurdock/node:61b03bf18376cb8ce916213e632e505849b114d7e409c0a71dcabdceaaf73129 
WARN[0007] Skipping deploy due to sync error: copying files: didn't sync any files 
Watching for changes...
```

### Steps to reproduce the behavior

1. clone [this](https://github.com/amurdock/skaffold-helm-sync-example) repo
2. `skaffold dev -v debug`
3. make trivial change to `packages/node/index.js` file

**Comment by amurdock** [comment]
I appreciate there's several of these _helm sync failure_ issues floating about but I've looked through each one and there's no indication that my configuration is incorrect or that what I'm trying to do isn't supported. Any help would be gratefully received.

**Comment by amurdock** [comment]
I've tried both `infer` and `manual` syncing approaches and both have the same symptomes.

**Comment by yolkov** [comment]
https://github.com/GoogleContainerTools/skaffold/issues/1566#issuecomment-515412465

**Comment by corneliusweig** [comment]
This looks like a configuration error. When trying sync with the helm deployment example, it works for me.

Can you try applying the following patch on your example:
```patch
diff --git a/k8s/templates/deployment.yaml b/k8s/templates/deployment.yaml
index 6a98e25..40f3260 100644
--- a/k8s/templates/deployment.yaml
+++ b/k8s/templates/deployment.yaml
@@ -24,7 +24,7 @@ spec:
     spec:
       containers:
       - name: node
-        image: amurdock/node
+        image: {{ .Values.image }}
         imagePullPolicy: Never
         ports:
         - containerPort: 3000
diff --git a/packages/node/index.js b/packages/node/index.js
index a6cb82f..3b5f4f4 100644
--- a/packages/node/index.js
+++ b/packages/node/index.js
@@ -5,4 +5,4 @@ const server = http.createServer((req, res) => {
   res.end('ok')
 })
 
-server.listen(3000)
\ No newline at end of file
+server.listen(3000)
diff --git a/skaffold.yaml b/skaffold.yaml
index 65640c7..160dda6 100644
--- a/skaffold.yaml
+++ b/skaffold.yaml
@@ -15,3 +15,5 @@ deploy:
     releases:
     - name: skaffold-helm-example
       chartPath: k8s
+      values:
+        image: amurdock/node
```

With that, your example works for me.

**Comment by amurdock** [comment]
Brilliant, amazing ... thanks for you help 👍
