### ISSUE TITLE
parallel builds

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#2560]
Currently `skaffold build` (and `skaffold dev`) build images one by one.

Even when all layers have been cached, it's still slower than building images in parallel.

**Comment by balopat** [comment]
I would love to have this somehow. 

Thoughts: 

This is only for `local` builds. 
On `cluster` and `gcb` builds we have parallel builds. 

1. We experimented with this before for local builds but things were breaking back then . @dgageot maybe it's worth having another look now
2. There _are_ people who depend on sequenced builds - they use it as a poor man's dependency management solution.

**Comment by balopat** [comment]
I realized that this is a dupe: I will close this issue and track it here: https://github.com/GoogleContainerTools/skaffold/issues/1380
