### ISSUE TITLE
inherit profile

### ISSUE THREAD

**Issue by lduparc** [GoogleContainerTools/skaffold#2569]
Is there a way to run skaffold command with multiple profiles. Use case is to have inherit profiles like this : 

`skaffold deploy -p p1,p2`
or using yml with an `heritage property` on profile config
 
Where profile p1 is apply and then profile p2 override or add some configurations.
For now using multiple profiles skaffold do both, deploy with p1 config and deploy with p2 config.

**Comment by briandealwis** [comment]
You can use `-p` multiple times: `-p p1 -p p2`.

**Comment by priyawadhwa** [comment]
@lduparc does that solve your issue?

**Comment by nkubala** [comment]
@lduparc I'll close this issue for now, if you think there's an issue here feel free to reopen with more information.
