### ISSUE TITLE
init: Automatically add .dockerignore file?

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2587]
When running `skaffold init`, Skaffold generates a ready-to-use `skaffold.yaml`. However, for IDEs this is not quite enough:

Consider a Dockerfile with a wildcard copy:
```Dockerfile
COPY . ./
```
This will include all IDE-specific configuration files, such as the `.idea` folder. (This probably is a potential reason for #2583).

We could make our users' lives easier by also generating a `.dockerignore` file which ignores some well-known IDE folders. Or is that already trying to be too clever?

**Comment by balopat** [comment]
It's a cool idea, we can have a .dockerignore starter that has best practices.

**Comment by balopat** [comment]
on a second thought maybe `skaffold init` should only create skaffold specific stuff...this seems to belong to the bootstrapping phase of the module. WDYT?

**Comment by corneliusweig** [comment]
Yeah, the more I think about this, the less I like the idea myself. _If_ this gets implemented, it should probably be the responsibility of the IDE plugin, because the IDE knows more about the programming language being used, for example.
