### ISSUE TITLE
Run skaffold behind a corporate proxy

### ISSUE THREAD

**Issue by bruno-roussel** [GoogleContainerTools/skaffold#2612]
### Expected behavior
Skaffold should run

### Actual behavior
Using  "getting started guide" and skafflod behind a corporate proxy, i get the following error:

skaffold dev

time="2019-08-05T16:10:02+02:00" level=fatal msg="watching files for artifact gcr.io/k8s-skaffold/skaffold-example: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12.6-alpine3.9) for ONBUILD tri
ggers: getting remote config: getting image: Get https://index.docker.io/v2/: dial tcp 52.200.103.230:443: connectex: No connexion was established because it was rejected by target"

### Information

- Skaffold version: latest
- Operating system: windows
- Contents of skaffold.yaml: getting started guide examples/getting-started

### Steps to reproduce the behavior

1. clone https://github.com/GoogleContainerTools/skaffold
2. cd examples/getting-started
2. skaffold dev

**Comment by prary** [comment]
Hi @bruno-roussel change the base image in your Dockerfile to any other base image which is accessible in your corporate and similarly change the target image also in skaffold.yaml
```

build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
```

**Comment by bruno-roussel** [comment]
Thks, it helped !

Not sure to understand what happened exactly.
I changed the base image but than I had to manually call docker build before calling skaffold dev.

Works fine now.

**Comment by janusch** [comment]
Hi @prary and @bruno-roussel ,
I am having the exact same issue. 
When I `docker build` the image first it works as expected pulling from local registry, and skaffold build will succeed afterwards. However, skaffold will start failing when that image in not, i guess in local cache anymore.

Could you please elaborate and provide an example on how you fixed this. I don't think I fully get your answer @prary 

I am on skaffold v0.41.0 wondering if an upgrade to 1.x would resolve the issue.

Thank you in advance!
