### ISSUE TITLE
Support for Operator-sdk / Operators

### ISSUE THREAD

**Issue by alikor** [GoogleContainerTools/skaffold#2620]
I have recently been switching to the Operator-sdk with operator-lifecycle-manager to manage operator versions and i was wondering will you be supporting Operators as a Deployer?

https://github.com/operator-framework/operator-sdk
https://github.com/operator-framework/operator-lifecycle-manager

**Comment by balopat** [comment]
Hi @alikor,

thank you for putting this on our radar, we haven't really thought about supporting Operator-SDK just yet. If there is enough adoption and demand from the community, it could become interesting. 
However, just to manage expectations, unless something changes, based what I know today, this is not likely to be picked up anytime soon by our team. 

In the meantime if you're interested to dig in - it would be interesting to do a feasibility study / design prework - I would be interested to see how things like logging / port forwarding / filesync would work with the Operator SDK.

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.
