### ISSUE TITLE
Fix "GetAllCredentials()` from credential store which is slow.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2625]
In #2573, we reverted a part of @dgageot's #279 to send all credentials  to docker build `GetAllCredentials()` which is slow to fix #239 

As, @mattnworb also mentioned, "correctness wins over performance". 

This TODO is to address if we can fix this in docker.
See https://github.com/GoogleContainerTools/skaffold/issues/239#issuecomment-516471130
and 
https://github.com/GoogleContainerTools/skaffold/pull/2573#issuecomment-516478199
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
