### ISSUE TITLE
Limit number of invalid inputs allowed when running generate-pipeline

### ISSUE THREAD

**Issue by marlon-gamez** [GoogleContainerTools/skaffold#2627]
Reduce the number of times input can be invalid when running skaffold generate-pipeline. This is mostly to prevent the case where someone is automating their skaffold commands and mess up the input, causing it to be stuck indefinitely at the input loop.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
