### ISSUE TITLE
kubectl command should timeout if it take very long time to execute

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#2629]
Running skaffold on windows is smooth until kubectl command are executed, kubectl version used is 1.13. Its takes almost 15 -20 minutes sometime to execute the kubctl deploy command

### Expected behavior
Should execute fast
### Actual behavior
Kubectl command execution are slow sometime, we should have timeout if it takes too long along with the message "kubectl responding slow" or if not timeout some info stating kubectl being slow
### Information

- Skaffold version: latest
- Operating system: Windows

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`

**Comment by priyawadhwa** [comment]
Hey @prary looks like there's a `--timeout` flag on `kubectl apply` that you pass in to skaffold via additional kubectl flags:

```yaml
kubectl:
  flags:
    apply:
    - --timeout
    - 60s
```

Does that solve your issue?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of Skaffold, please feel free to add a comment and we'll re-open it.

If someone sees a similar issue, please create a new issue, but do include a link to this issue if possible.

Thank you for opening the issue!
