### ISSUE TITLE
Create integation test for generate-pipeline to run generated tekton pipeline in cluster

### ISSUE THREAD

**Issue by marlon-gamez** [GoogleContainerTools/skaffold#2635]
Current integration tests for generate-pipeline only check to see that the output into skaffold.yaml and pipeline.yaml is as expected.

There should be an integration test to check that the generated tekton pipeline runs properly and doesn't error when running on cluster.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists.
