### ISSUE TITLE
Build events should be sent even when artifacts are cached

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2636]
Or we should have a cache event? When working on #2621 I noticed that `TestDevAPITriggers` was failing because build events aren't sent if images exist in the cache.

**Comment by balopat** [comment]
I'd prefer sending a Build Succeeded event even when we have a cache hit.

**Comment by priyawadhwa** [comment]
Cool that's actually what I ended up doing in #2621 -- I'll close this issue.
