### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [GoogleContainerTools/skaffold#2670]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by balopat** [comment]
Hi Yevgeny, thank you for reaching out! This sounds interesting, would be cool to catch some bugs with it. First ideas where we could use: one obvious part would be the config parser. We also have a Control API that takes requests. There might be other places too, but this would be a good start to experiment with.

**Comment by yevgenypats** [comment]
hi @balopat the config parser sounds like a good candidate indeed. I think I'll start with that.

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by balopat** [comment]
Thank you, good to know - for me finding a bug would be a sufficient reward - it's my job to make skaffold better. I don't have time to jump in right now but it looks interesting.

However, someone from the community might be motivated more by the reward program. I'm open to contributions either from you or others. Feel free to post this issue on our slack channel.

**Comment by yevgenypats** [comment]
Sounds good, can you send me an invite to slack to yp [at] fuzzit.dev

**Comment by balopat** [comment]
I see you managed to find it and post! Let me know if you need any help!

**Comment by yevgenypats** [comment]
@balopat help is appreciated, looks like there were more projects [interested](https://github.com/fuzzitdev/fuzzit) then I assumed and I'm working now on unrelated fuzzit release. if you have some spare time then this is this will be quicker. 

we have a draft for two fuzzers https://github.com/dominikh/skaffold/commit/e88043cd576592fe8b8984e67daa1ed3225eecc6 

maybe @bookmoons can help integrate

**Comment by bookmoons** [comment]
Thanks a lot @yevgenypats. Will dig into this soon.

**Comment by bookmoons** [comment]
There's a functional fuzz target for the config file. No obvious crashes in a local run.

https://github.com/GoogleContainerTools/skaffold/compare/master...bookmoons:f05b7d989fa770907e1d574f21569f465103cab3

Going to look into that Control API.

**Comment by bookmoons** [comment]
There's some fuzzing around the HTTP server in `pkg/skaffold/server`. Is this the kind of thing you were imagining for hitting the control API?

https://github.com/bookmoons/skaffold/blob/214ba72f3f8703027b90f08ee5a3da5602f79151/pkg/skaffold/server/server_fuzz.go

It has a target that fuzzes binary requests and one that decodes the fuzz into valid HTTP requests. So it will try to catch failures at both of those semantic levels.

**Comment by bookmoons** [comment]
Made a submission to start this off in #2835. @balopat

**Comment by briandealwis** [comment]
Closing as per #2835.
