### ISSUE TITLE
Add support for `--set-file` in helm deployer

### ISSUE THREAD

**Issue by aeneasr** [GoogleContainerTools/skaffold#2678]
### Expected behavior

Right now there does not seem a way to use the `--set-file` feature of helm. This is useful where large files need to be ingested into a helm value config. This could be the case with e.g. binary files that need to be mounted using a configmap.

### Actual behavior

It does not seem to be possible to use `--set-file`.

### Information

- Skaffold version: v0.36.0
- Operating system: any

### Steps to reproduce the behavior

Does not apply

**Comment by marti1125** [comment]
Hi I am interesting in contribute with this. Could you tell me more, please?

**Comment by aeneasr** [comment]
Regarding the feature or the implementation?

**Comment by marti1125** [comment]
@aeneasr the implementation, please

**Comment by aeneasr** [comment]
I can not help with that unfortunately (not a Skaffold maintainer)

**Comment by cedrickring** [comment]
@aeneasr This would require changes at two locations:

1. Modify the config to accept `setFile` values in [`HelmRelease`](https://github.com/GoogleContainerTools/skaffold/blob/dd9b3b3f66555f65e21b1de41a87a8a8dc28e6e1/pkg/skaffold/schema/latest/config.go#L433)
2. Append the values to the `helm` command [like here](https://github.com/GoogleContainerTools/skaffold/blob/dd9b3b3f66555f65e21b1de41a87a8a8dc28e6e1/pkg/skaffold/deploy/helm.go#L303).

**Comment by marti1125** [comment]
@cedrickring  please review my [PR](https://github.com/GoogleContainerTools/skaffold/pull/2895) thanks!
