### ISSUE TITLE
Make skaffold-debug's duct-tape location configurable

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2679]
The location of the `duct-tape` images used by `skaffold debug` should be configurable, probably in the skaffold global config.  This may be required for pointing to internally-hosted variants.

**Comment by sbueringer** [comment]
Hi, 
I would start implementing this, if it's okay.

I have a few questions:
* where in the global config should this be configurable, options are:
  *  a separate field inside the kubectl & kubelet section (which are according to the doc the only ones supporting skaffold debbuging)
  * one field in the deploy section (possibly in a debug sub section)
  * top-level debug section

* field name/semantic. (the image is actually only a prefix appended with e.g. "install-%s-support")
  * field only to overwrite the "registry" (default would be `gcr.io/gcp-dev-tools/duct-type`)
  * field to set the image including repo name which is then directly used without appending a suffix. But I'm not sure if it's supported to use multiple duct-tape images in one skaffold.yaml, which then would be a problem. We could also allow setting an image per `RuntimeSupportImage` (e.g. go, node, ..)

* The transformation is currently done in `skaffold/debug/transform.go`. As this is only exposed via the interface `type ManifestTransform func(l kubectl.ManifestList, builds []build.Artifact, insecureRegistries map[string]bool) (kubectl.ManifestList, error)` to `kubectl.go` and `kustomize.go` I'm not sure how the field should be handed over. Maybe just add a config parameter to the interface?

**Comment by briandealwis** [comment]
Thanks for your interest @sbueringer and my apologies in the delay in following up!  Here are my thoughts.

I think this location should be the registry and should be configurable either by the global config or an environment variable.  I'm thinking this will be used primarily to mirror the duct-tape artifacts for those behind corporate proxies.  We may well support multiple transforms in the future.  And we'll definitely be supported other language runtimes.

I've been thinking of these duct-tape images as debug helpers.  So maybe a variation of `debugHelpersRegistry`?

For now, I'd make the duct-tape image location a var in `skaffold/debug/debug.go`, which loosely houses the Skaffold-specific binding.  We'd then retrieve the value from the global config and set that var in [`skaffold/cmd/skaffold/app/cmd/debug.go`](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/debug.go#L45).

It might be worth turning the `insecureRegistries` and `debugHelpersRegistry` into a `debugHelpers` structure that's passed into `ManifestTransform`.

Thanks again!

**Comment by sbueringer** [comment]
@briandealwis Thx for the feedback. I opened a PR for it

**Comment by dgageot** [comment]
https://github.com/GoogleContainerTools/skaffold/pull/4057

**Comment by tejal29** [comment]
work in progress.

**Comment by sbueringer** [comment]
@tejal29 
Isn't it already fixed here: https://github.com/GoogleContainerTools/skaffold/pull/3945
/cc @briandealwis

**Comment by tejal29** [comment]
closed due to this https://github.com/GoogleContainerTools/skaffold/pull/4057 and  #3945
