### ISSUE TITLE
Drop the dog, show me the product

### ISSUE THREAD

**Issue by steren** [GoogleContainerTools/skaffold#2693]
### Expected behavior
https://skaffold.dev shows me the Skaffold developer experience and what problem it solves with actual commands and or screenshots

### Actual behavior

https://skaffold.dev shows me a dog (a cute one, I agree)

**Comment by balopat** [comment]
Thank you @steren - we are working on this for our 1.0.0 release!

**Comment by dgageot** [comment]
@steren Cats ftw!
