### ISSUE TITLE
skaffold dev should recover by itself when user internet connection is intermittent

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2698]
### Expected behavior
If user's internet connection goes on an off, `skaffold dev` should be able to recover gracefully.
Inspired from #1890, we should make sure

- port-forwarding should start listening on the same ports
- deploy healthcheck should recover if internet is back and it can now fetch the deploy health check.
- clean exit.

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by tstromberg** [comment]
Thank you for the feedback!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
