### ISSUE TITLE
Tag Spec Validation

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#27]
We need to make sure that some parameters are valid docker tags before it gets to the downstream tools and fails. We should vendor in the validation from docker/moby

**Comment by balopat** [comment]
Is this an issue with the envTagger? Can you provide more details please?

**Comment by dgageot** [comment]
I'm going to close this one because we haven't seen issues about that. @r2d4 please reopen in case you think there's still an issue
