### ISSUE TITLE
idea: open github issue with attachments

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2705]
to help our contributors on issues we could have a functionality to submit an issue from skaffold, e.g. `skaffold bug --attach-file buggy-skaffold.logs --attach-file screenshot.png` - which would take the files and attach them, and fill out the details of OS, skaffold version, and a masked version of skaffold.yaml in a draft issue that the user could edit.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
