### ISSUE TITLE
How to set Helm setValues via env vars

### ISSUE THREAD

**Issue by emichaf** [GoogleContainerTools/skaffold#2714]
How to set Helm setValues via env vars ?

Tried many variants: 
ex:
```
          setValues:
            ingress.hosts[0]: {{.MYVAR}}   <--- not parsed
            image.pullPolicy: Never
```

**Comment by devronhansen** [comment]
Found this while searching for other things, hopefully it's still correct: https://github.com/GoogleContainerTools/skaffold/pull/347/commits/2da2629042c401fd901797db41506fd53e2c7aea
(not tested)

```
  setValues:
        some.other.key: ${PWD}/mypath
```

**Comment by emichaf** [comment]
Tried that one also, did not work!

export MYVAR=Never
```setValues:
            image.pullPolicy: ${MYVAR}   <---- did not parse env var
```
Error: release ms-backend-local-dev failed: Deployment.apps "ms-backend-dev" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "${MYVAR}": supported values: "Always", "IfNotPresent", "Never"

**Comment by dgageot** [comment]
@emichaf @devronhansen Have you tried `setValueTemplates` instead of `setValues`. This should support env variables interpolation.

**Comment by dgageot** [comment]
I'm going to close this issue. I've just checked that it works well with this syntax:

```
          setValueTemplates:
            ingress.hosts[0]: {{.MYVAR}}
            image.pullPolicy: Never
```
