### ISSUE TITLE
splitting manifests on apiVersion not resilient to antecedent fields in ascending lexicographical order

### ISSUE THREAD

**Issue by khrisrichardson** [GoogleContainerTools/skaffold#2715]
### Expected behavior

A `ClusterRole` containing `aggregationRule` or a `StorageClass` containing either `allowVolumeExpansion` or `allowedTopologies` as top-level fields are created just like any other resource.

### Actual behavior

A `ClusterRole` containing `aggregationRule` or a `StorageClass` containing either `allowVolumeExpansion` or `allowedTopologies` as top-level fields are subject to truncation when `---` is added before `apiVersion` in the [`Append` method of `github.com/GoogleContainerTools/skaffold/pkg/skaffold/kubectl`](https://github.com/GoogleContainerTools/skaffold/blob/96ac37e30ee94b3f015a5eda14c7e7b1d99b0a34/pkg/skaffold/deploy/kubectl/manifests.go#L44-L46).

If continuing with the forking of `kubectl create --dry-run` it may be worthwhile to output `json` instead of `yaml` and tokenize text segments by line starting with `^{`, which has cascading effects throughout the code.

Alternatively to forking `kubectl`, it may be advantageous to feed the stream of documents to [k8s.io/apimachinery/pkg/util/yaml](https://godoc.org/k8s.io/apimachinery/pkg/util/yaml).

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by dgageot** [comment]
I'm going to push a fix that uses the fact that `kubectl create --dry-run -oyaml` produces a lexicographically sorted output.
