### ISSUE TITLE
TestPollDeploymentRolloutStatus is unstable

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#2744]
See https://travis-ci.com/GoogleContainerTools/skaffold/jobs/228963982#L166-L171

```
--- FAIL: TestPollDeploymentRolloutStatus (0.19s)
    cmd_helper.go:134: unable to run RunCmdOut() with command "kubectl --context kubecontext --namespace test rollout status deployment dep --watch=false"
    --- FAIL: TestPollDeploymentRolloutStatus/rollout_returns_did_not_stabilize_within_the_given_timeout (0.10s)
        testing.go:820: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
```

**Comment by dgageot** [comment]
The test is unstable and the way fake commands are created with the parent `t` instead of the child `testing.T` creates this funky error message.

**Comment by balopat** [comment]
This is in progress, on her branch in #2750 this is going to be not a time based logic.

**Comment by tejal29** [comment]
This test does not check for number of calls any more. It also is not time dependent.
