### ISSUE TITLE
`skaffold init --artifact` should use builder IDs 

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#2747]
`skaffold init --artifacts '{...json...}`'s JSON input object should use an identifier rather than the [human-oriented builder names](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/initializer/init.go#L273-L284) being used currently.  For example: `docker` and `jib-maven` instead of `Docker` and `Jib Maven Plugin`.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
