### ISSUE TITLE
Mailing list is not accessible

### ISSUE THREAD

**Issue by edwin-zvs** [GoogleContainerTools/skaffold#2751]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/43801454/63906554-0b811b80-c9cd-11e9-9d00-67ae1221a526.png">

"Skaffold mailling list" and mail icon on the footer does not work.

### Expected behavior

Able to access, subscribe mailing list. Or no broken link on the website.

### Actual behavior
<img width="586" alt="image" src="https://user-images.githubusercontent.com/43801454/63906487-d70d5f80-c9cc-11e9-9415-7fa0a7a15fcf.png">

**Comment by balopat** [comment]
Thank you for reporting this!! I'm not sure what happened here but it is definitely broken if I look at it from my personal account. The group permissions seem messed up - and the one who created is not with us anymore. I'll fix this soon - I'll try to take over the ownership, if that doesn't work out, by creating a new user list.

**Comment by balopat** [comment]
This is fixed now, thank you again for the notice!
