### ISSUE TITLE
docs: Split concepts section into subpages

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#2779]
The concepts section has accumulated a lot of loosely related information, such as

- Architecture
- Configuration of the Skaffold pipeline (skaffold.yaml)
- Global configuration (~/.skaffold/config)
- Workflow
- Image repository handling
- Operating modes
- Local development

I think it's time to break this up into several sub-pages, similar to the Howto section. This will allow more structure in the individual sections and improve the navigation through this whole section.

Any concerns about that?

**Comment by nkubala** [comment]
agree for sure. I think our docs need an overhaul, there are a lot of nuanced concepts in Skaffold that deserve their own write-ups. we get lots of questions about things that **I** know are in the docs, but are very hard for users to find.

are you at all interested in taking a stab at restructuring/breaking out some of these concepts?

**Comment by corneliusweig** [comment]
Yes, I will have a go at this. I don't have as much time as I used to, but I'll make room for it :)
