### ISSUE TITLE
skip tests when not needed

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2814]
It would speed us up somewhat and save resources if our tests and checks would be smarter: 

| change | tests to run | skip/autoPass | 
|------- | -----| ---- |
| docs/ only change | checks | all unit and integration jobs + kokoro|
 | *.md only change outside of docs | none | all Travis jobs + kokoro |  
 | any makefile or *.go change | all tests | none |

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and if it does still exist, it doesn't seem to be getting any traction at the moment. If this issue appears in the most recent release of Skaffold, please feel free to add a follow-up comment and we will see about getting it prioritized appropriately.

If someone sees a similar issue to this one, please create a new issue, but do include a link to this issue if possible. 

Thank you for sharing this issue with us!
