### ISSUE TITLE
publish the n-1, n-2, n-3 versions of skaffold to homebrew

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2833]
Context: https://github.com/GoogleContainerTools/skaffold/issues/2816#issuecomment-528790124

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and if it does still exist, it doesn't seem to be getting any traction at the moment. If this issue appears in the most recent release of Skaffold, please feel free to add a follow-up comment and we will see about getting it prioritized appropriately.

If someone sees a similar issue to this one, please create a new issue, but do include a link to this issue if possible. 

Thank you for sharing this issue with us!
