### ISSUE TITLE
update skaffold google cloud build image in gcr.io

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#2837]
### Expected behavior
This [community image](https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/skaffold/Dockerfile) should contain the latest version of skaffold.

### Actual behavior
The actual skaffold version in this image is v0.34.1.

### Information
The latest skaffold version contains an important backoff implementation for cloud build, which is not included in the existing image :-(

I know there's a plan to implement an official cloud builder, but in the meanwhile it would be great to expect the latest version, without having to build locally when a new version is released.

**Comment by balopat** [comment]
Thank you for letting us know - not sure that "latest" is the right thing there anyway. 
I raised PR: https://github.com/GoogleCloudPlatform/cloud-builders-community/pull/295/files 
And for now we'll stick with this - I'll add it to our release process to update this image. 
Next release is coming on Thursday - v0.38.0!

**Comment by balopat** [comment]
Also, in the meantime, FWIW, as a workaround, you can build your own buildstep image and use that in your cloudbuild.yaml.

**Comment by giladsh1** [comment]
> Also, in the meantime, FWIW, as a workaround, you can build your own buildstep image and use that in your cloudbuild.yaml.

Yes, that's exactly what I did... thank you @balopat !

**Comment by balopat** [comment]
Actually I'm not sure I understand this - this was merged, however as per the main docs: 

https://cloud.google.com/cloud-build/docs/cloud-builders#community-contributed_builders

"Pre-built images are not available for these builders; to use these builders, download the source code from the cloud builders community GitHub repository and then build the image."

**Comment by balopat** [comment]
I am going to revert back to `latest` policy. This adds an extra manual step in our release process. 
We are planning to release the coming quarter or so an official Cloud Build Step image - in that case you don't have to rebuild it all the time - in the meantime it is a good idea to just build it and cache it based on the community `Dockerfile`.
