### ISSUE TITLE
Remove --XXenableJibInit requirement for "skaffold init" once IDEs are ready

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/skaffold#2842]
`skaffold init` fails without the flag `--XXenableJibInit` for a project configured with Jib.

```
FATA[0000] one or more valid builder configuration (Dockerfile or Jib configuration) must be present to build images with skaffold; please provide at least one build config and try again or run `skaffold init --skip-build`
```

At some point, we should enable it by default. This should probably need to be coordinated with IDE plugins.

@GoogleContainerTools/java-tools-build

**Comment by chanseokoh** [comment]
@GoogleContainerTools/java-tools-build

**Comment by dkirrane** [comment]
I get this on skaffold `1.0.0`
```
skaffold init --XXenableJibInit
time="2019-11-08T11:44:40Z" level=fatal msg="one or more valid Kubernetes manifests is required to run skaffold"
```

**Comment by chanseokoh** [comment]
@dkirrane I suspect that your error probably happens without `--XXenableJibInit` too. But even if it only happens with `--XXenableJibInit`, you should file a new issue. This issue is about remove the `-XXenableJibInit` flag to make it default. Could you file a new issue?

**Comment by tstromberg** [comment]
Anyone know if this is still an issue in more recent releases?

**Comment by nkubala** [comment]
this flag does still exist, but we probably want to remove it soon.

**Comment by dgageot** [comment]
Closing in favour of broader #4401
