### ISSUE TITLE
"skaffold init" generates incorrect config for Jib project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/skaffold#2844]
In #2843, the config for a Jib project has `module: demo`

```yaml
    jibMaven:
      module: demo
```

However, the project was a simple Spring Boot demo generated from the [Initializr](https://start.spring.io/) and not a multi-module project. I had to remove `module:` to make it work correctly. Seems like a bug.

@GoogleContainerTools/java-tools-build

**Comment by chanseokoh** [comment]
In #2843, the config for a Jib project has `module: demo`

```yaml
    jibMaven:
      module: demo
```

However, the project was a simple Spring Boot demo generated from the [Initializr](https://start.spring.io/) and not a multi-module project. I had to remove `module:` to make it work correctly. Seems like a bug.

@GoogleContainerTools/java-tools-build

**Comment by balopat** [comment]
cc @GoogleContainerTools/java-tools

**Comment by loosebazooka** [comment]
@TadCordle

**Comment by TadCordle** [comment]
Ah, I think I see the issue. In `SkaffoldInitMojo.java` in Jib, we do this check:
```
if (getProject().getParent() != null) {
  skaffoldInitOutput.setProject(getProject().getName());
}
```
i.e. if the goal is running on the root project, don't provide the module name to skaffold. The problem is that a spring initializr project is not actually the root project.

pom.xml:
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.8.RELEASE</version>
	<relativePath/> <!-- lookup parent from repository -->
</parent>
```

So, it seems we need to find a different way of determining whether or not a module is the root project.

**Comment by TadCordle** [comment]
Alternatively, we could fix this skaffold-side by just checking the number of modules that were output by Jib, and ignore the project if it's only one.

**Comment by TadCordle** [comment]
This should be fixed with the next release of Jib.
