### ISSUE TITLE
idea: run script to generate files listed under `deploy:kubectl:manifests`

### ISSUE THREAD

**Issue by AndiDog** [GoogleContainerTools/skaffold#2860]
What about supporting a workflow where
- CI calls a ~custom~ single-source-of-truth `generate-manifest.sh` to create a full manifest, commits it to another Git repo which is watched by a CD tool (Argo CD, Flux, ...) and deployed using kubectl+prune (typical usage of Argo CD) to production.
- Developers should be working closely to this production CI/CD pipeline, and use Skaffold for that (for obvious benefits, such a helpful tool 🎉).

Skaffold would have to allow running `generate-manifest.sh` before deployment, so the manifest files can be generated according to the currently active profile and any outside environment variables. So instead of `ENV=staging-a ./generate-manifest.sh && skaffold dev`, you would _only_ run `skaffold dev`.

That can be achieved like:

```yaml
deploy:
  kubectl:
    generateManifestsScripts: # <- new feature
      - generate-manifest.sh
    manifests:
      - generated.manifest.yml
```

The kubectl deployer would run the commands before deployment, and afterwards do the usual thing (fill in image tags, deploy). For the kustomize deployer, the same feature applies. For Helm, I could imagine a related helpful feature where the script produces values.yaml files upfront.

This is similar to #1441 (pre-build hook in this case), but has the advantage that profiles can overwrite the whole `deploy` section.

If you think this makes sense, ping me and I can implement it. I believe supporting CI/CD workflows is important – there are already issues asking to document how to combine CI/CD with Skaffold...

**Comment by nkubala** [comment]
hey @AndiDog thanks for the issue! CI/CD and GitOps are something that we're looking very closely at right now, definitely agree with you that supporting these types of workflows is important. the current plan right now is to start by implementing a feature in skaffold that outputs the rendered k8s manifests so they can be used in GitOps or similar workflows, and also optionally deploy them as normal. i'm not quite sure about having skaffold do the actually committing of the manifest to a git repo though.

**Comment by AndiDog** [comment]
That's a nice and much anticipated feature 👍

My idea here, however, would amend that feature. The example `generate-manifest.sh` script can use any template tool (helm/ytt/envsubst/${var}...) to generate any manifest, and Skaffold would use it as base for filling in the image tags, generating the final manifest and deploying.

**Comment by tejal29** [comment]
@AndiDog Skaffold build provides now spits out the artifacts it built in a [format](https://github.com/GoogleContainerTools/skaffold/blob/15868fb4b5818c576208c4e05f0a14e1f3d3ee56/cmd/skaffold/app/flags/build_output.go#L36)
It would be easy for folks to use `skaffold build --output <>` and then parse the built images values and replace it them `generate-manifest.sh` instead of skaffold providing hooks to run a pre-deploy hook.

**Comment by tejal29** [comment]
I am going to close this as supporting a `generate Manifest` is a subset of `pre-deploy` hook #1441
