### ISSUE TITLE
PullSecretName is never null

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#2888]
https://github.com/GoogleContainerTools/skaffold/blob/a892d7910f74fab9ead9930da3e3c26b74771757/pkg/skaffold/build/cluster/secret.go#L33

PullSecretName is set to DefaultKanikoSecretName in case it is empty.

https://github.com/GoogleContainerTools/skaffold/blob/a892d7910f74fab9ead9930da3e3c26b74771757/pkg/skaffold/schema/defaults/defaults.go#L213

**Comment by balopat** [comment]
This is resolved in #2910.
