### ISSUE TITLE
Problems while using buildah as builder via custom, issues with $PUSH_IMAGE and reference parsing

### ISSUE THREAD

**Issue by Edke** [GoogleContainerTools/skaffold#2921]
### Expected behavior

I'd like to use buildah for image building while keeping skaffold in it's current role, so handle image name for each environment, generate tags etc.

So far skaffold does not support buildah as another builder (would be good idea to create a feature request?) so custom script is only solution right now.

Skaffold no matter what sets PUSH_IMAGE to false, from docs I was not able to follow how  skaffold handles PUSH_IMAGE variable.

After this also another problem is handled, skaffold tries to fetch sha256 currently from local Docker daemon. We would like to drop docker in CI completely. Not sure how to handle passing sha256 back to skaffold at the end of our custom build script without Docker.

### Actual behavior

- Always PUSH_IMAGe=false is sent to buildCommand.
- `skaffold build` crashes when buildah finishes push to repo with:
   `FATA[0014] build failed: build failed: building [example.com/project-dev]: Error parsing reference: "" is not a valid repository/tag: invalid reference format`

### Information

- Skaffold version: v0.38.0
- Operating system: Arch Linux
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: example.com/project-dev
    custom:
      buildCommand: skaffold2buildah
```

Python script that handles passing args from skaffold build to buildah, `skaffold2buildah`:

```python
#!/usr/bin/python
import os 
import sys
import subprocess

# just to debug skaffold's calls
with open('/tmp/docker.log', 'a+') as fd:
    fd.write('args: {}\n'.format(sys.argv))
    fd.write('images: {}\n'.format(os.environ['IMAGES']))
    fd.write('push_image: {}\n'.format(os.environ['PUSH_IMAGE']))
    fd.write('context: {}\n'.format(os.environ['BUILD_CONTEXT']))

context = os.environ['BUILD_CONTEXT']
for image in os.environ['IMAGES'].split(' '):
    cmd = ['buildah', 'bud', '--layers', '-t', image, context]
    print(' '.join(cmd))
    subprocess.run(cmd, stdout=subprocess.PIPE).stdout.decode('utf-8')
    cmd =['buildah', 'push','--format', 'docker', image, 'docker://{}'.format(image)]     
    print(' '.join(cmd))
    subprocess.run(cmd, stdout=subprocess.PIPE).stdout.decode('utf-8')
```

### Steps to reproduce the behavior

1. skaffold.yaml from above
2. `skaffold2buildah` as executable in $PATH 
3. `skaffold build`

**Comment by tejal29** [comment]
@Edke in your script, you do a `buildah push` in the script which is assume does the push?
Can you push if only `PUSH_IMAGE` is set?
https://github.com/GoogleContainerTools/skaffold/blob/master/examples/buildpacks/build.sh#L8

Can you also give us some feedback on how we can improve the docs around it?
Not your fault, but looks like our [docs](https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally) do mention this in a very subtle manner. 
Would it help we link the above example there?

Thanks
Tejal

**Comment by Edke** [comment]
> @Edke in your script, you do a `buildah push` in the script which is assume does the push?
> Can you push if only `PUSH_IMAGE` is set?
> https://github.com/GoogleContainerTools/skaffold/blob/master/examples/buildpacks/build.sh#L8

That is what I understand, was not able to figure it out how to configure skaffold so it sends PUSH_IMAGE=true.
 
> Can you also give us some feedback on how we can improve the docs around it?
> Not your fault, but looks like our [docs](https://skaffold.dev/docs/how-tos/builders/#custom-build-script-run-locally) do mention this in a very subtle manner.
> Would it help we link the above example there?

In docs in table for custom builder it states:

>  Set to true if each image in $IMAGES is expected to exist in a remote registry. Set to false if each image in $IMAGES is expected to exist locally.

What I don't understand is how can I configure custom builder so it sends PUSH_IMAGE=true.

But more on my problem:

- I'm using custom builder so I can drop my dependancy on Docker, so I can use other way to build image, for example `podman` or `buildah`, without Docker engine at all
- when skaffold helps me to do that using custom build, at the end it expects that builded image will be pushed to local Docker daemon so skaffold can using expect fetch it's SHA256 and finalize image's tag
- I guess currently using gitCommit tagger it is not able to successfully run custom script without Docker as it fails after custom script finishes build (and/or push)

**Comment by tejal29** [comment]
@Edke ah, ok. 
For question 1: 
please use 
```
build: 
  local: 
    push: true
``` 
in your skaffold config to configure local push.

**Comment by tejal29** [comment]
@Edke Can you try again with this config and see if it fixes your issue?

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
