### ISSUE TITLE
Docs: Every feature page should mention the command(s) they belong to.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2925]
### Expected behavior
For every page in https://skaffold.dev/docs/how-tos/ guide we should mention what phases or command the feauture is available in
e.g. Its not clear from https://skaffold.dev/docs/how-tos/filesync/ page whether filesync works for `debug` and `dev`.
On the contrary, prot-forwarding page explicitly mentions tit.
```
This page discusses how to set up port forwarding with Skaffold for 
skaffold dev and skaffold debug.

Port forwarding is set to false by default; it is enabled with the --port-forward flag.
If this flag is not set, no port forwarding will occur. If the flag is set, Skaffold will:
```

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by tstromberg** [comment]
Seems fixed.
