### ISSUE TITLE
Add simple file sync and port forwarding to getting started

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2952]
Or, to the tutorial in our getting started docs, so that these useful features are more visible.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
