### ISSUE TITLE
Enhancement: Enable skaffold build to output  kustomize edit set image instructions

### ISSUE THREAD

**Issue by wstrange** [GoogleContainerTools/skaffold#2957]
This is related to #1187.

I'm not sure how the Kustomize deployer fixes up docker image names before deployment. 

The "kustomize" way of setting image names is documented here: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md 

If the `build` phase of skaffold could output a file that contains a series of `kustomize edit set image` transformations, this largely solves the problem of using skaffold in a CD pipeline where you want another tool (say argo) to manage the deployment. 

The workflow would be . `skaffold build`, to build, tag and push the final images, and then hand the generated kustomize edit file to the CD deployer to fix up the image names before sending to the cluster.

Hope that makes sense.

**Comment by priyawadhwa** [comment]
Hey @wstrange thanks for opening this issue!

cc @nkubala -- this seems related to `skaffold render`, do you know if we have any plans to add this feature?

**Comment by tejal29** [comment]
@wstrange We have a PR in progress. Please track #2943

**Comment by wstrange** [comment]
@tejal29 Thanks. That PR looks like it is for kubectl. Does it also work with Kustomize?

**Comment by nkubala** [comment]
@wstrange kustomize implementation in the works, it'll go out with the next release. will having rendered manifests solve this issue for you?

**Comment by wstrange** [comment]
Rendered kustomize manifests definitely solves our most pressing issue for CD integration.

It would be really neat if skaffold could output `kustomize edit` commands that set the image names and tags.  I think this is the canonical way of setting image/tags in kustomize deployments.  I'm wondering if that file could be output in the build phase? So the CD process becomes something like:

```shell
# build, tag and push
skaffold build 
# This also outputs a kustomize.edit.sh file... containing commands like 
# kustomize edit set image busybox=alpine:3.6
# CD process runs:
# ./kustomize.edit.sh 
# Then deploys:
# kustomize build ./path | kubectl apply -f -
```

If the image output file was a simple csv or json mapping, the edit commands could also be derived from that.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
