### ISSUE TITLE
Point users to helm/kustomize examples in skaffold init

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleContainerTools/skaffold#2969]
If we can somehow guess that users are using helm/kustomize during skaffold init, we can point them to helpful examples on the github page.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
