### ISSUE TITLE
Remove `gcr.io/k8s-skaffold` from examples

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#2973]
All of the images built in the examples we provide are using the `gcr.io/k8s-skaffold` registry. We originally did this because our examples stemmed from the integration testing examples we were running, and our justification for leaving this was that users can use the default repo functionality to run them as is.

While the default repo can (and probably should) still be used to run these examples, the fact that the `k8s-skaffold` registry is sitting on the image names is confusing for users. We should remove this to make it more clear that the images are not able to be pushed in their current form. We'll need to slightly modify the way we run integration tests.

Additionally, we should clarify how the default repo functionality should be used to run skaffold.

**Comment by dgageot** [comment]
This was fixed a while ago. Couldn't find the PR
