### ISSUE TITLE
Not able to keep idempotency when using the status check?

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2980]
I'm not sure about the best way to handle this, or if it should be supported (it might be strange if for example the label override affected the logic of the status check), but it would be nice to be able to do both.

### Expected behavior
Able to use `--status-check` with `-l skaffold.dev/run-id=` to use the status check while preserving idempotency to avoid unnecessary rollouts.

### Actual behavior
Using both causes the status check to immediately report success because no deployments are labeled with the generated runID and thus none are checked.

### Information
- Skaffold version: v0.39.0

### Steps to reproduce the behavior
1. Write `deploy` block that includes at least one Deployment
2. `skaffold deploy --status-check -l skaffold.dev/run-id=<runID>`

**Comment by balopat** [comment]
Thanks for opening! I'm surprised that this is not working, we should have a look at it.

**Comment by nkubala** [comment]
@tbarrella can you check and see if this is still an issue for you? I think we changed the way we allow the user to override the run-id and I hope this is fixed now 🙏

**Comment by dgageot** [comment]
This was fixed with https://github.com/GoogleContainerTools/skaffold/pull/3985
