### ISSUE TITLE
Status check uses progressDeadlineSeconds in an unexpected way

### ISSUE THREAD

**Issue by tbarrella** [GoogleContainerTools/skaffold#2983]
### Expected behavior
Potentially, either `--status-check` doesn't take a Deployment's progressDeadlineSeconds into account, or progressDeadlineSeconds is interpreted similar to the existing Deployment controller, allowing the status check to continue until the deployment is fully rolled out (or until statusCheckDeadlineSeconds). From [docs](https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/controller/deployment/util/deployment_util.go#L729) in the controller's code, it seems like DeploymentProgressing is interpreted as having new pods come up or old ones removed, and the deployment is only considered "timed out" if DeploymentProgressing hasn't been reported since progressDeadlineSeconds.

### Actual behavior
If progressDeadlineSeconds is set for a Deployment, and the Deployment isn't fully rolled out beforehand, the status check times out with an unexpected error, even if the rollout is making progress, like
```
 - n:deployment/one failed. [1/2 deployment(s) still pending] Error: context deadline exceeded.
 - n:deployment/two failed. Error: kubectl rollout status command killed.
```

### Information
- Skaffold version: v0.39.0

### Steps to reproduce the behavior
1. Write deploy block that includes at least one Deployment with a progressDeadlineSeconds but multiple replicas such that the entire rollout can take longer than progressDeadlineSeconds
2. `skaffold deploy --status-check`

**Comment by tejal29** [comment]
@tbarrella Thanks for opening the issue. The `statusCheckDeadlineSeconds` overrides the `deployment.Spec.ProgressDeadlineSeconds` if it's greater than `statusCheckDeadlineSeconds`.
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/status_check.go#L106

This is intentional, so deploy errors out  when user expect them to stabilize within what was specified in the `skaffold.yaml` and cases where deployments take  longer (which is what happens in your case get surfaced)

That actually also exposes a bug, skaffold should probably cleanup when `skaffold deploy --status-check` fails.

**Comment by tbarrella** [comment]
Hi @tejal29, thank you for you reply! Before you posted it I reread what I wrote and was just about to clarify some of my thoughts.

When I saw `statusCheckDeadlineSeconds` in the Skaffold API it sounded exactly like something I wanted and so was eager to try it. Without the code, the way I interpreted it was that it would poll for up to `statusCheckDeadlineSeconds` and error if the rollout wasn't complete yet. I realized later that this is what it does, except for the interaction with `progressDeadlineSeconds` that I didn't expect.

For the meaning of the two terms,
- `statusCheckDeadlineSeconds`: From my initial interpretation, how long should it take for the deployment to roll out completely?
- `progressDeadlineSeconds`: From my understanding of the Deployment API, how long should it take for each new pod to become ready or available, or for each old pod to scale down?

The confusion for me was that I realized that the status check uses `progressDeadlineSeconds` as a deadline for the entire rollout, rather than for an incremental step to be made. It feels like it would be less confusing if the status check considered only one or the other. For example, the check could poll Deployment status and throw an error if `DeploymentProgressing` is ever `False`. Or, it could it have the existing behavior without taking `progressDeadlineSeconds` into account. I only have my own experience so far, so I'm curious about the feedback of others who try out the feature.

In terms of clean up, it makes sense to me why someone would want to either clean up or roll back if the status check fails, although the way I was hoping to use it is the existing behavior, where Skaffold exits with an error but doesn't take any action. My main use for this was to be notified if the deployment isn't rolling out as quickly as I expected it to. Would it make sense for this to either default to the most conservative action (doing nothing) or be configurable?

**Comment by tejal29** [comment]
@tbarrella thank your reply and sorry for the delay.
so, i think the intention is not ignore `progressDeadlineSeconds`  if set for a deployment.
And a deployment spec does not have `progressDeadlineSeconds`, then  wait for deployments to stabilize for `statusCheckDeadlineSeconds`

**Comment by tbarrella** [comment]
I guess I understand the intention and how it works, but I think it would be good to reconsider the behavior.

`progressDeadlineSeconds` is often going to be a relatively small value; it only needs to be long enough for a new pod to roll out. This is how it's interpreted by the Deployment controller. If the status check uses this as a timeout for the status check, it will time out for deployments with enough replicas.

In particular, `progressDeadlineSeconds` is expected to be used in a way that it does not increase as the number of replicas increases. But we would expect the status check to have a longer timeout if there are more replicas

That's why I think the current behavior should be reconsidered; if people use the status check, they can no longer use `progressDeadlineSeconds` as it was intended to be used

**Comment by tbarrella** [comment]
Hey, just want to give a specific example

For pods that take 10 seconds each to roll out, it might make sense to set `progressDeadlineSeconds: 20`. If the Deployment has 20 replicas, it could take more than 20 seconds total for all the pods to roll out, depending on the update strategy, even if the Progressing condition is True throughout. But as is, the status check would fail after 20 seconds
