### ISSUE TITLE
[Reappeared] Build and push to an insecure registry completes unsuccessfully

### ISSUE THREAD

**Issue by NicklasWallgren** [GoogleContainerTools/skaffold#2986]
Expected behavior
A Skaffold driven build should complete successfully even if the image is pushed to an insecure registry.

Actual behavior
Skaffold errors on building/pushing the new image.
```
FATA[0000] failed to build: tagging image: Get https://<registry>:32000/v2/: http: server gave HTTP response to HTTPS client
```

Works as expected in v0.35.0.

See https://github.com/GoogleContainerTools/skaffold/issues/1732 for more information.

**Comment by balopat** [comment]
Hi @NicklasWallgren did you try using `insecureRegistry` in either the CLI / skaffold.yaml / global config? https://skaffold.dev/search/?q=insecure%20registry

**Comment by dgageot** [comment]
@NicklasWallgren you are using Jib, right?

**Comment by dgageot** [comment]
@NicklasWallgren Can you try without artifact caching? It was activated by default in 0.36.0, I think. Something like `skaffold build --cache-artifacts=false`

If that works, I think it's because you now have to configure skaffold to handle insecure registries too. See https://skaffold.dev/docs/concepts/image_repositories/#insecure-image-registries.

Before 0.36.0, Skaffold would let Jib tag the images. Now, because of caching, Skaffold can sometimes retag images and it then requires to know that the registry is insecure.

**Comment by dgageot** [comment]
Maybe Skaffold could read the list of insecure registries from `~/.docker/deamon.json`
See https://github.com/GoogleContainerTools/skaffold/issues/3051

**Comment by NicklasWallgren** [comment]
I'm not using `jib` for this particular project, and I have specified the insecure registries in `skaffold.yaml `as well as in `deamon.json`.

I'll provide additional information tomorrow.

**Comment by NicklasWallgren** [comment]
@dgageot Worked fine without artifact caching enabled `--cache-artifacts=false`

**Comment by dgageot** [comment]
@NicklasWallgren Thanks! So there must be an issue. Do you have a small project we could use to reproduce?

**Comment by NicklasWallgren** [comment]
Hmm, it works as expected if I remove `insecureRegistries` from the skaffold.yaml.

@dgageot https://asciinema.org/a/f9bbw5cH94a5AoTCkaLNb2wAt

**Comment by NicklasWallgren** [comment]
@dgageot @balopat 

It fails on https://github.com/google/go-containerregistry/blob/7683b4ee5f6150cb47a791309f781c522b95a58f/pkg/v1/remote/transport/transport.go#L43

Called from https://github.com/GoogleContainerTools/skaffold/blob/6236f7f2c6ba1b06abb37965e3afe9a996275c4a/pkg/skaffold/docker/remote.go#L48

**Comment by NicklasWallgren** [comment]
`reg.insecure` is false in transport.go.
```

`targetRef.Registry.insecure` in AddRemoteTag is always false.
