### ISSUE TITLE
Support for Ephermal Storage for Kaniko pod

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#2990]
This is a feature request for adding support for Ephermal Storage for Kaniko pod.
Presently we can specify CPU and memory for kaniko pods but not Ephermal storage.

**Comment by balopat** [comment]
Thanks for this @prary, it should be relatively easy to implement [local ephemeral storage](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage) requests. PRs are welcome!

**Comment by prary** [comment]
I raise a PR for it, can you assign it to me @balopat
