### ISSUE TITLE
Users get prompted by Skaffold with NPS, CSAT form links

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3010]
### Expected behavior
Skaffold users should see a prompt to fill in CSAT survey
 - Once every two weeks until they fill the survey
-  Once per 3 months.

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by briandealwis** [comment]
Is there further work required here?

**Comment by dgageot** [comment]
@tejal29 can we close this one?

**Comment by nkubala** [comment]
I think this can be closed. please reopen if there's more work to be done here.
