### ISSUE TITLE
Skaffold init with Jib init behaves differently in analyze mode

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#3060]
Skaffold v0.40

Project has Dockerfile and skaffold.yaml already present. We assume the generation of the Skaffold YAML is not necessary at this point. However:

`skaffold init --analyze`:
```
FATA[0000] pre-existing skaffold.yaml found
``` 
(expected)

`skaffold init --analyze --XXenableJibInit`:
```
{"builders":[{"name":"Docker","payload":{"path":"Dockerfile"}},{"name":"Jib Maven Plugin","payload":{"path":"pom.xml"}}],"images":[{"name":"java-hello-world","foundMatch":false}]}
```
(unexpected, we would notify user about skaffold YAML generation possibility although skaffold.yaml already present).

**Comment by TadCordle** [comment]
What does the project structure look like? Is the `skaffold.yaml` in the same directory as the `pom.xml`? I think what might be happening is that it searches for an existing `skaffold.yaml` and for build files in the same pass, and skaffold finds a Jib config first, so it returns `filepath.SkipDir` and stops searching the current directory before finding `skaffold.yaml`.

**Comment by ivanporty** [comment]
It's `cloud-code-samples/java/java-hello-world`, so
```
checkstyle.xml  
Dockerfile  
hello-world.iml  
img  
kubernetes-manifests  
pom.xml  
README.md  
skaffold.yaml  
src  
target
```

**Comment by TadCordle** [comment]
Hmm yeah, I suspect that's the case then. The correct behavior should probably be to continue walking at the current level without entering any nested directories after a Jib config is found, rather than just skipping the rest of the current directory.
