### ISSUE TITLE
Additional contexts for an artifact, shared directories that parent/siblings relative a Dockerfile

### ISSUE THREAD

**Issue by ghost** [GoogleContainerTools/skaffold#3061]
Not a bug. Skaffold is working as intended. My use case is probably not standard so really just seeing if there is a work around or existing functionality.

### Expected behavior
My project structure is the following:
```
/app
  /k8s
    client-deployment.yaml
    client-cluster-ip.service.yaml
  /shared
    /contexts
      package.json
      index.js
    /hooks
  /web
    /src
      App.js
    package.json
    Dockerfile.dev
  skaffold.yaml
```
`/shared` are some React contexts and hooks that will be shared between React and React Native using the directory as a local npm dependency. This is done by doing the following from `./web`:

`npm install --save ../shared/contexts` 

Which creates this entry in the `package.json`:

`"contexts": "file:../shared/contexts"`

This works great if just using `npm start`, but setting up Docker, Skaffold, and K8S has been a bit of a pain.

I do have it working with Docker with the following:
```
FROM node:alpine

WORKDIR '/app'
EXPOSE 3000
CMD ["npm", "run", "start"]

COPY ./web ./
COPY ./shared /shared
RUN npm install
```
And then from `/app` running:

`docker build -t testapp/client -f web/Dockerfile.dev .`

Some I'm trying to duplicate this in the `skaffold.yaml`:
```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: testapp/client
      # context: web
      docker:
        dockerfile: web/Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.css"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
portForward:
  - resourceType: client
    resourceName: client-cluster-ip-service
    port: 3000
    localPort: 3000
```
I'd hope this would let me keep the same project structure, install the local npm dependency, and also retain the ability for Skaffold to automatically update the image when changes are made to either `/web` or `/shared`.

### Actual behavior
This is not the case however...

Basically I have two choices:

1. Retain the ability for Skaffold to automatically update the image when the program changes, but `/shared` npm dependency no longer works since the paths become `./web/web` and `./web/shared` in the `Dockerfile.dev`:
```
context: web
docker:
  dockerfile: Dockerfile.dev
```
2. Lose the ability for Skaffold to update the images, but keep the project structure intact with:
```
# context: web
docker:
  dockerfile: web/Dockerfile.dev
```
Or
```
context: ./
docker:
  dockerfile: web/Dockerfile.dev
```
Neither one is desirable, but 2. is the least desirable. I'm likely just going to have settle for 1., develop the hooks and contexts for React, make them an npm module, and install into React Native as a dependency.
### Information

- Skaffold version: v.0.39.0
- Operating system: macOS Mojave 10.14.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta15
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: testapp/client
      context: web
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.css"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
portForward:
  - resourceType: client
    resourceName: client-cluster-ip-service
    port: 3000
    localPort: 3000
```

### Steps to reproduce the behavior

See this repo for cloning and instructions to reproduce:

https://github.com/cheslijones/skaffold-context-issue

**skaffold -v trace: Initial startup**

    $ skaffold -v trace dev --port-forward --tail
    INFO[0000] starting gRPC server on port 50051           
    INFO[0000] starting gRPC HTTP server on port 50052      
    INFO[0000] Skaffold &{Version:v0.39.0 ConfigVersion:skaffold/v1beta15 GitVersion: GitCommit:4145d76cbccd0ea46ee31541f5f550368e257fa3 GitTreeState:clean BuildDate:2019-09-30T05:59:50Z GoVersion:go1.13.1 Compiler:gc Platform:darwin/amd64} 
    DEBU[0000] validating yamltags of struct SkaffoldConfig 
    DEBU[0000] validating yamltags of struct Metadata       
    DEBU[0000] validating yamltags of struct Pipeline       
    DEBU[0000] validating yamltags of struct BuildConfig    
    DEBU[0000] validating yamltags of struct Artifact       
    DEBU[0000] validating yamltags of struct Sync           
    DEBU[0000] validating yamltags of struct SyncRule       
    DEBU[0000] validating yamltags of struct SyncRule       
    DEBU[0000] validating yamltags of struct SyncRule       
    DEBU[0000] validating yamltags of struct ArtifactType   
    DEBU[0000] validating yamltags of struct DockerArtifact 
    DEBU[0000] validating yamltags of struct TagPolicy      
    DEBU[0000] validating yamltags of struct GitTagger      
    DEBU[0000] validating yamltags of struct BuildType      
    DEBU[0000] validating yamltags of struct LocalBuild     
    DEBU[0000] validating yamltags of struct DeployConfig   
    DEBU[0000] validating yamltags of struct DeployType     
    DEBU[0000] validating yamltags of struct KubectlDeploy  
    DEBU[0000] validating yamltags of struct KubectlFlags   
    DEBU[0000] validating yamltags of struct PortForwardResource 
    INFO[0000] Using kubectl context: minikube              
    DEBU[0000] Using builder: local                         
    DEBU[0000] Running command: [minikube docker-env --shell none] 
    DEBU[0000] Command output: [DOCKER_TLS_VERIFY=1
    DOCKER_HOST=tcp://192.168.99.104:2376
    DOCKER_CERT_PATH=/Users/work/.minikube/certs
    ] 
    DEBU[0000] setting Docker user agent to skaffold-v0.39.0 
    Listing files to watch...
     - testapp/client
    TRAC[0000] Checking base image node:alpine for ONBUILD triggers. 
    DEBU[0000] Found dependencies for dockerfile: [{web /app true} {shared /shared false}] 
    List generated in 2.479513ms
    Generating tags...
     - testapp/client -> DEBU[0000] Running command: [git describe --tags --always] 
    DEBU[0000] Command output: [bebbfc5
    ]                   
    DEBU[0000] Running command: [git status . --porcelain]  
    DEBU[0000] Command output: []                           
    testapp/client:bebbfc5
    Tags generated in 31.653609ms
    Checking cache...
    TRAC[0000] Checking base image node:alpine for ONBUILD triggers. 
    DEBU[0000] Found dependencies for dockerfile: [{web /app true} {shared /shared false}] 
     - testapp/client: Found. Tagging
    Cache check complete in 16.090394ms
    Tags used in deployment:
     - Since images are not pushed, they can't be referenced by digest
       They are tagged and referenced by a unique ID instead
     - testapp/client -> testapp/client:e6dc788f1d8d57b0fce825ddbcfc40b510ea7f91c594c94be6e3c3f5779584c3
    Starting deploy...
    DEBU[0000] Running command: [kubectl version --client -ojson] 
    DEBU[0000] Command output: [{
      "clientVersion": {
        "major": "1",
        "minor": "14",
        "gitVersion": "v1.14.6",
        "gitCommit": "96fac5cd13a5dc064f7d9f4f23030a6aeface6cc",
        "gitTreeState": "clean",
        "buildDate": "2019-08-19T11:13:49Z",
        "goVersion": "go1.12.9",
        "compiler": "gc",
        "platform": "darwin/amd64"
      }
    }
    ] 
    DEBU[0000] Running command: [kubectl --context minikube create --dry-run -oyaml -f /Users/work/Projects/test/test-app/k8s/client-deployment.yaml -f /Users/work/Projects/test/test-app/k8s/client-cluster-ip-service.yaml] 
    DEBU[0001] Command output: [apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-deployment
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: web
      template:
        metadata:
          labels:
            component: web
        spec:
          containers:
          - image: testapp/client
            name: client
            ports:
            - containerPort: 3000
    apiVersion: v1
    kind: Service
    metadata:
      name: client-cluster-ip-service
      namespace: default
    spec:
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        component: web
      type: ClusterIP
    ] 
    DEBU[0001] manifests apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-deployment
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: web
      template:
        metadata:
          labels:
            component: web
        spec:
          containers:
          - image: testapp/client
            name: client
            ports:
            - containerPort: 3000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: client-cluster-ip-service
      namespace: default
    spec:
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        component: web
      type: ClusterIP 
    DEBU[0001] manifests apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-deployment
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: web
      template:
        metadata:
          labels:
            component: web
        spec:
          containers:
          - image: testapp/client
            name: client
            ports:
            - containerPort: 3000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: client-cluster-ip-service
      namespace: default
    spec:
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        component: web
      type: ClusterIP 
    DEBU[0001] manifests with tagged images: apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: client-deployment
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: web
      template:
        metadata:
          labels:
            component: web
        spec:
          containers:
          - image: testapp/client:e6dc788f1d8d57b0fce825ddbcfc40b510ea7f91c594c94be6e3c3f5779584c3
            name: client
            ports:
            - containerPort: 3000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: client-cluster-ip-service
      namespace: default
    spec:
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        component: web
      type: ClusterIP 
    DEBU[0001] manifests with labels apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/managed-by: skaffold-v0.39.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kubectl
        skaffold.dev/docker-api-version: "1.39"
        skaffold.dev/run-id: 6929adc6-da5e-4af7-8f79-076d967bafc5
        skaffold.dev/tag-policy: git-commit
        skaffold.dev/tail: "true"
      name: client-deployment
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: web
      template:
        metadata:
          labels:
            app.kubernetes.io/managed-by: skaffold-v0.39.0
            component: web
            skaffold.dev/builder: local
            skaffold.dev/cleanup: "true"
            skaffold.dev/deployer: kubectl
            skaffold.dev/docker-api-version: "1.39"
            skaffold.dev/run-id: 6929adc6-da5e-4af7-8f79-076d967bafc5
            skaffold.dev/tag-policy: git-commit
            skaffold.dev/tail: "true"
        spec:
          containers:
          - image: testapp/client:e6dc788f1d8d57b0fce825ddbcfc40b510ea7f91c594c94be6e3c3f5779584c3
            name: client
            ports:
            - containerPort: 3000
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/managed-by: skaffold-v0.39.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kubectl
        skaffold.dev/docker-api-version: "1.39"
        skaffold.dev/run-id: 6929adc6-da5e-4af7-8f79-076d967bafc5
        skaffold.dev/tag-policy: git-commit
        skaffold.dev/tail: "true"
      name: client-cluster-ip-service
      namespace: default
    spec:
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        component: web
      type: ClusterIP 
    DEBU[0001] 2 manifests to deploy. 2 are updated or new  
    DEBU[0001] Running command: [kubectl --context minikube apply -f - --force] 
     - deployment.apps/client-deployment created
     - service/client-cluster-ip-service created
    Deploy complete in 1.499851687s
    DEBU[0002] getting client config for kubeContext: ``    
    DEBU[0002] getting client config for kubeContext: ``    
    Port forwarding service/client-cluster-ip-service in namespace default, remote port 3000 -> local port 3000
    DEBU[0002] found open port: 3001                        
    DEBU[0002] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/client-cluster-ip-service 3000:3000 --namespace default] 
    DEBU[0002] Change detected <nil>                        
    TRAC[0002] Checking base image node:alpine for ONBUILD triggers. 
    DEBU[0002] Found dependencies for dockerfile: [{web /app true} {shared /shared false}] 
    Watching for changes...
    DEBU[0002] port forwarding service-client-cluster-ip-service-default-3000 got terminated: exit status 1, output: error: unable to forward port because pod is not running. Current status=Pending 
    DEBU[0002] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/client-cluster-ip-service 3000:3000 --namespace default] 
    DEBU[0002] port forwarding service-client-cluster-ip-service-default-3000 got terminated: exit status 1, output: error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0003] [port-forward] error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0003] killing port forwarding service-client-cluster-ip-service-default-3000 
    TRAC[0003] failed to kill port forwarding service-client-cluster-ip-service-default-3000, err: os: process already finished 
    TRAC[0003] Checking base image node:alpine for ONBUILD triggers. 
    DEBU[0003] Found dependencies for dockerfile: [{web /app true} {shared /shared false}] 
    DEBU[0003] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/client-cluster-ip-service 3000:3000 --namespace default] 
    DEBU[0003] port forwarding service-client-cluster-ip-service-default-3000 got terminated: exit status 1, output: error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0003] [port-forward] error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0003] killing port forwarding service-client-cluster-ip-service-default-3000 
    TRAC[0003] failed to kill port forwarding service-client-cluster-ip-service-default-3000, err: os: process already finished 
    DEBU[0003] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/client-cluster-ip-service 3000:3000 --namespace default] 
    DEBU[0003] port forwarding service-client-cluster-ip-service-default-3000 got terminated: exit status 1, output: error: unable to forward port because pod is not running. Current status=Pending 
    INFO[0004] Streaming logs from pod: client-deployment-58474dc658-rn9jn container: client 
    DEBU[0004] Running command: [kubectl --context minikube logs --since=4s -f client-deployment-58474dc658-rn9jn -c client --namespace default] 
    [client-deployment-58474dc658-rn9jn client] 
    [client-deployment-58474dc658-rn9jn client] > web@0.1.0 start /app
    [client-deployment-58474dc658-rn9jn client] > react-scripts start
    [client-deployment-58474dc658-rn9jn client] 
    TRAC[0004] [port-forward] error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0004] killing port forwarding service-client-cluster-ip-service-default-3000 
    TRAC[0004] failed to kill port forwarding service-client-cluster-ip-service-default-3000, err: os: process already finished 
    DEBU[0004] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/client-cluster-ip-service 3000:3000 --namespace default] 
    TRAC[0004] [port-forward] error: unable to forward port because pod is not running. Current status=Pending 
    TRAC[0004] killing port forwarding service-client-cluster-ip-service-default-3000 
    TRAC[0004] failed to kill port forwarding service-client-cluster-ip-service-default-3000, err: os: process already finished 
    [client-deployment-58474dc658-rn9jn client] Starting the development server...
    [client-deployment-58474dc658-rn9jn client] 
    TRAC[0005] [port-forward] Forwarding from 127.0.0.1:3000 -> 3000 
    TRAC[0006] [port-forward] Forwarding from [::1]:3000 -> 3000 
    [client-deployment-58474dc658-rn9jn client] Compiled successfully!
    [client-deployment-58474dc658-rn9jn client] 
    [client-deployment-58474dc658-rn9jn client] You can now view web in the browser.
    [client-deployment-58474dc658-rn9jn client] 
    [client-deployment-58474dc658-rn9jn client]   Local:            http://localhost:3000/
    [client-deployment-58474dc658-rn9jn client]   On Your Network:  http://172.17.0.7:3000/
    [client-deployment-58474dc658-rn9jn client] 
    [client-deployment-58474dc658-rn9jn client] Note that the development build is not optimized.
    [client-deployment-58474dc658-rn9jn client] To create a production build, use yarn build.
    [client-deployment-58474dc658-rn9jn client] 

**skaffold -v trace: After file update**

    DEBU[0858] Change detected notify.Write: "/Users/work/Projects/test/test-app/web/src/App.js" 
    TRAC[0859] Checking base image node:alpine for ONBUILD triggers. 
    DEBU[0859] Found dependencies for dockerfile: [{web /app true} {shared /shared false}] 
    INFO[0859] files modified: [web/src/App.js]             
    Syncing 1 files for testapp/client:e6dc788f1d8d57b0fce825ddbcfc40b510ea7f91c594c94be6e3c3f5779584c3
    INFO[0859] Copying files: map[web/src/App.js:[/app/web/src/App.js]] to testapp/client:e6dc788f1d8d57b0fce825ddbcfc40b510ea7f91c594c94be6e3c3f5779584c3 
    DEBU[0859] getting client config for kubeContext: ``    
    DEBU[0859] Running command: [kubectl --context minikube exec client-deployment-58474dc658-rn9jn --namespace default -c client -i -- tar xmf - -C / --no-same-owner] 
    DEBU[0859] Command output: [], stderr: tar: removing leading '/' from member names 
    Watching for changes...

This part looked odd: `{shared /shared false}]`, so I wanted to make sure it was in the image Skaffold was using. Did the following:

    `minikube ssh`
    
To get the correct tag:

    `docker image ls` 

Then:
  
    `docker run -it <tag> ssh`

Looked in the image and the `/shared` is there with the `/contexts`... so not really sure what is going on. Otherwise, the output from `skaffold -v trace` looks the same as a setup where the update is working properly.

**Comment by nkubala** [comment]
this was an interesting question, and one that was complicated enough that nobody from our team got around to it in a timely manner....we waited so long that the user removed themselves from github entirely 😮 there are some nuanced issues with the way we handle dockerfiles and docker contexts in skaffold, and hopefully if those are still present and someone runs across them we can file issues that adequately describe the problem and help us fix them!

**Comment by sauerm1** [comment]
I know this is closed, but id also like to be able to develop shared packages locally with hot-reload in the apps that use those packages. I.E. Developing a shared component library for a web app, and making changes in the local component library will instantly reflect in the web-app. Similar to the way yarn workspaces works. 
If there isn't a solution to this, is there a current workaround? I dont want to have to publish my shared package to npm and then have the app pull it down every time i change a line of code in the shared package and want to see it locally.
