### ISSUE TITLE
[Custom builder] $IMAGES is always a single image

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3081]
We currently pass the build script the `IMAGES` env variable. This variable contains the list of images to build. However, this variable always contains a single tag.

I think we should deprecate this value and use `IMAGE` instead.

**Comment by tejal29** [comment]
Can you please add these to current Deprecation notices  to the Deprecation policy as well ?
https://skaffold-latest.firebaseapp.com/docs/references/deprecation/#current-deprecation-notices

We shd make sure this is captured in Release notes. Added Deprecation to the title.
