### ISSUE TITLE
Implement timedate tagger

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#309]

**Comment by dlorenc** [comment]
Should this take a datetime format string?

**Comment by dlorenc** [comment]
Something like: https://golang.org/pkg/time/#Time.Format

**Comment by gtseres** [comment]
Could you please provide some more info on what has to be done for this one?

**Comment by r2d4** [comment]
@gtseres We'd like to have a new "tagger" implementation that generates a docker image tag with the date time

You would add a new struct in the v1alpha2 config

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v1alpha2/config.go

```
type TimeDateTagger struct {
  Format string `yaml:format,omitempty`
}
```

Add a new tagpolicy entry for it

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v1alpha2/config.go#L51-L56


Add it to this list (this step wont be needed after #388)

https://github.com/GoogleContainerTools/skaffold/blob/7a89445cc34ee6f243fdf9e039c7d9264fd7cd6a/pkg/skaffold/runner/runner.go#L117-L129


then add the implementation here https://github.com/GoogleContainerTools/skaffold/tree/master/pkg/skaffold/build/tag

It should probably just use the golang timedate format type (although the golang format string is a bit different than the general unix `date` formats) 

https://golang.org/pkg/time/#Time.Format

**Comment by r2d4** [comment]
There is also a little more context on the taggers in https://github.com/GoogleContainerTools/skaffold/issues/407
