### ISSUE TITLE
skaffold dev --tail=true doesn't tail logs when using remoteManifest

### ISSUE THREAD

**Issue by gbird3** [GoogleContainerTools/skaffold#3113]
### Expected behavior
When adding --tail=true to skaffold dev, it should tail the logs for the pod

### Actual behavior
It doesn't tail the logs. Doesn't seem like it even attempts to.
### Information

- Skaffold version: v0.40.0
- Operating system: MacOS Catalina
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: docker.joltup.com/backend/api
      context: .
      docker:
        dockerfile: Dockerfile-local
      sync:
        manual:
          - src: src/**/*
            dest: .
deploy:
  kubectl:
    remoteManifests:
      - default:deployment/api-server
```

### Steps to reproduce the behavior

1. In skaffold, instead of using a k8s file, use remoteManifest and point the the deployment
2. `skaffold dev --tail=true`
3.  Everything works great, but it doesn't tail the logs

```List generated in 52.698213ms
Generating tags...
 - docker.joltup.com/backend/api -> docker.joltup.com/backend/api:latest
Tags generated in 422.2µs
Checking cache...
 - docker.joltup.com/backend/api: Found Locally
Cache check complete in 250.487153ms
Tags used in deployment:
 - Since images are not pushed, they can't be referenced by digest
   They are tagged and referenced by a unique ID instead
 - docker.joltup.com/backend/api -> docker.joltup.com/backend/api:03a2471082dc3da792b72ed58a0d42d3a8c4edb150e1a5e39479e57e552a70a3
Starting deploy...
WARN[0000] k8s/*.yaml did not match any file            
WARN[0000] image [docker.joltup.com/backend/api] is not used by the deployment 
 - deployment.extensions/api-server configured
Deploy complete in 383.301593ms
WARN[0000] k8s/*.yaml did not match any file            
Watching for changes...
WARN[0001] k8s/*.yaml did not match any file  ```

**Comment by balopat** [comment]
Thank you for opening, @gbird3! 

For dev you shouldn't need `--tail=true` as that is the default. 
I tried to reproduce it but couldn't! 

Here's what I did: 

1. With the [microservices example ](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/microservices) first `skaffold run` 
2. edit the yaml file to replace the manifests to remoteManifests and added some extra logs to the web.go and app.go files (`log.Print("leeroy app server request!")` and the same for web server) 
```
apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    remoteManifests:
      - default:deployment/leeroy-app
#    manifests:
#      - ./leeroy-web/kubernetes/*
#      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
```
2. run `skaffold dev --port-forward=true` and ping the forwarded port (localhost:9000)
```
Tags used in deployment:
 - gcr.io/k8s-skaffold/leeroy-web -> gcr.io/k8s-skaffold/leeroy-web:v0.40.0-117-g20ada24e0-dirty@sha256:5d38861bab458c12e4a85d072f7504e0d047f2a3c588615393f93b8317e01771
 - gcr.io/k8s-skaffold/leeroy-app -> gcr.io/k8s-skaffold/leeroy-app:v0.40.0-117-g20ada24e0-dirty@sha256:a855f5dd372c7bf3c53737b23e35bb5d80dcc37745878357bdd27c0765a6e49b
Starting deploy...
WARN[0000] k8s/*.yaml did not match any file            
WARN[0000] image [gcr.io/k8s-skaffold/leeroy-web] is not used by the deployment 
WARN[0000] image [gcr.io/k8s-skaffold/leeroy-app] is not used by the deployment 
 - deployment.extensions/leeroy-app configured
Deploy complete in 808.719856ms
Port forwarding deployment/leeroy-web in namespace default, remote port 8080 -> local port 9000
WARN[0001] k8s/*.yaml did not match any file            
Watching for changes...
INFO[0001] Streaming logs from pod: leeroy-web-754bbfc6bc-f8g57 container: leeroy-web 
INFO[0001] Streaming logs from pod: leeroy-app-675db5569f-vw8m6 container: leeroy-app 
WARN[0002] k8s/*.yaml did not match any file            
INFO[0002] Streaming logs from pod: leeroy-app-64bf9f65f9-lhbgj container: leeroy-app 
[leeroy-app-64bf9f65f9-lhbgj leeroy-app] 2019/10/24 23:23:37 leeroy app server ready hello
[leeroy-web-754bbfc6bc-f8g57 leeroy-web] 2019/10/24 23:23:55 leeroy web server request!
[leeroy-app-64bf9f65f9-lhbgj leeroy-app] 2019/10/24 23:23:55 leeroy app server request!
[leeroy-app-64bf9f65f9-lhbgj leeroy-app] 2019/10/24 23:23:55 leeroy app server request!
[leeroy-web-754bbfc6bc-f8g57 leeroy-web] 2019/10/24 23:23:55 leeroy web server request!
[leeroy-app-64bf9f65f9-lhbgj leeroy-app] 2019/10/24 23:23:55 leeroy app server request!
[leeroy-web-754bbfc6bc-f8g57 leeroy-web] 2019/10/24 23:23:55 leeroy web server request!
```

Can you try this yourself as well? 
Also can you send logs for `-v info` level? we might get some more information about why the pods are not being monitored for logs.

**Comment by gbird3** [comment]
@balopat after doing more testing, this does not seem to be an issue with remoteManifest. I think my skaffold config is wrong. We have all of our k8s config in a central repo and so I am trying to add skaffold into that repo. It seems the issue may be that my skaffold.yml is not in the same directory as our dockerfile: 

`apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: docker.joltup.com/backend/api
      context: /Users/gregbird/jolt/code/api/
      docker:
        dockerfile: Dockerfile-local
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
deploy:
  kubectl:
    remoteManifests:
    - default:deployment/api-server
`

So I think I'm running into issues with adding the context path. We can close this issue and if I can't figure it out I'll open a different one.

**Comment by gbird3** [comment]
I figured out my issue. We are storing our yaml onfig as nodejs code and coverting to a yaml file as part of a build process. The yaml conversion wasn't properly formatting the yaml file. Thanks for the help
