### ISSUE TITLE
Skaffold Jib: Multi-module Maven project with Maven wrapper cannot find Maven

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#3121]
Project: https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-guestbook
Skaffold: 0.40
Jib: 1.7.0

Make sure you don't have Maven on PATH.

Add Maven Wrapper at the root project directory (`\some-location\mvn -N io.takari:maven:0.7.6:wrapper`)

Run `skaffold dev`: 
`
FATA[0000] watching files for artifact java-guestbook-backend: listing files: listing files: getting jib-maven dependencies: initial Jib dependency refresh failed: failed to get Jib dependencies: starting command &{mvn [mvn jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 --non-recursive jib:_skaffold-files-v2 --quiet] [] backend <nil> 0xc0000e19a0 0xc0000e19b0 [] <nil> <nil> <nil> 0xc0003c6100 0xc0006d6c40 false [] [0xc0000e19a0 0xc0000e19b0] [0xc0000e1998 0xc0000e19a8] [] <nil> <nil>}: exec: "mvn": executable file not found in $PATH 
`

Running the Maven wrapper from the directory manually works.
If you add Maven wrapper individually to all submodules, then Jib is able to detect it.

**Comment by briandealwis** [comment]
In a [Jib multimodule project](https://skaffold.dev/docs/how-tos/builders/), the `context` directory should point to the root and the `project` should be the subproject location.

**Comment by ivanporty** [comment]
Should I file an issue for `cloud-code-samples` repo instead then to fix this?

**Comment by ivanporty** [comment]
https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/152
