### ISSUE TITLE
disable skaffold watch on *.swp files

### ISSUE THREAD

**Issue by mbarlow** [GoogleContainerTools/skaffold#3124]
### Expected behavior
when using skaffold dev if I edit a file with vim (creates a swp file) it should not trigger the build

### Actual behavior
editing a file with vim triggers rebuild. I've tried looking through the docs to configure this, I don't see a way to exclude *.swp from the watch

**Comment by mbarlow** [comment]
to clarify, I mean if I open vim to edit a file it shouldn't trigger the build. If I save a file that has been modified I do expect the build to happen.

**Comment by balopat** [comment]
Hi @mbarlow thanks for opening the issue. 
What builder are you using? If you are using Dockerfile, adding *.swp rule to a `.dockerignore` file should help.

**Comment by chanseokoh** [comment]
Ever since this, I put the following in my `.vimrc` to create swap files in a central location. Very happy about it, as crashing vim doesn't leave dangling swap files in places I can't remember.

```
" The directory does not get auto-created. Must be created beforehand.
set directory=~/.vim/swapfiles//
```

But most people don't know about this trick.

And note it is usually `*.swp`, but if you open vim windows, the next file is `*.swo`.

**Comment by mbarlow** [comment]
@balopat yes, using Dockerfile. I adding the *.swp to .dockerignore. @chanseokoh that's a good tip. Thanks to both of you!

**Comment by wgj** [comment]
I'm experiencing this behavior (`.swp`, `.swo` files triggering `skaffold dev`) with Custom Build Script. Should I update this issue with more details or create a new issue?

**Comment by lautaro-eb** [comment]
Is it not a good idea to omit swap files by default?

**Comment by tstromberg** [comment]
@lautaro-eb - For many users, yes. From Skaffold's standpoint though, we cannot assert by file extension alone that something is a swap file or not. If it works for you, please add it to the .dockerignore.

**Comment by chanseokoh** [comment]
What's the recommendation for Jib uses who don't have .dockerignore?

**Comment by nkubala** [comment]
ref https://github.com/GoogleContainerTools/skaffold/issues/20

**Comment by davidxia** [comment]
For anyone wondering why `*.swp* in `.dockerignore` isn't working, if you need to ignore all `*.swp` files in all directories, use `**/*.swp` instead.
