### ISSUE TITLE
Skaffold init --analyze returns duplicate image name

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#3128]
### Expected behavior
"skaffold init --analyze" should dedup image names. Expected output below.

{"dockerfiles":["src\\backend\\Dockerfile","src\\frontend\\Dockerfile"],"images":["node-guestbook-backend","mongo","node-guestbook-frontend"]}

### Actual behavior
"skaffold init --analyze" returns the "mongo" name twice in the "images". Actual output below.

{"dockerfiles":["src\\backend\\Dockerfile","src\\frontend\\Dockerfile"],"images":["node-guestbook-backend","mongo","node-guestbook-frontend","mongo"]}

### Information

- Skaffold version: version... v0.39.0-215-g96e5cef6
- Operating system: ... Windows
- Contents of skaffold.yaml:
No skaffold.yaml

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior
1. Get the nodejs guestbook cloud code sample.
2. Delete the skaffold.yaml at the root
3. run "skaffold init --analyze"

**Comment by balopat** [comment]
Thanks for opening @sujit-kamireddy - we should fix this, I agree!
