### ISSUE TITLE
Add/Modify a sample with a more complicated build

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#314]
Most (all?) of our examples are a simple `go build` on a single file. We should demonstrate how to properly write a `Dockerfile` for a more complicated codebase without loosing too much on the incremental build side.

**Comment by r2d4** [comment]
Yes, I'd also like to have something for interpreted languages, like python.

**Comment by dgageot** [comment]
Let's close this one and add an interpreted language example when  https://github.com/GoogleContainerTools/skaffold/issues/477 is fixed
