### ISSUE TITLE
Control API rebuild doesn't work as expected

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3151]
### Expected behavior

* on the getting-started example: 
```
skaffold dev --auto-build=false
```
* change `main.go` 
* skaffold shouldn't do _anything_ as there is nothing to sync or deploy, and build is stopped!
* send `curl -X POST http://localhost:50052/v1/execute -d '{"build": true}'`
* skaffold should `build` & `deploy`

### Actual behavior

* on the getting-started example: 
```
skaffold dev --auto-build=false
```
* change `main.go` 
* skaffold deploys the non-changed manifests!!! 
* send `curl -X POST http://localhost:50052/v1/execute -d '{"build": true}'`
* skaffold  `build`s but it doesn't deploy!!! 

### Information

- Skaffold version: 0.41.0
- Operating system: Linux
- Contents of skaffold.yaml: getting-started example

**Comment by nkubala** [comment]
bumping this down a priority since I doubt we'll get to it anytime soon.

**Comment by tejal29** [comment]
We haven't seen this issue in a while. CC users use the control api and this has not surfaced. I am going to close this issue.
