### ISSUE TITLE
Add the --tag flag to skaffold build

### ISSUE THREAD

**Issue by Inkdpixels** [GoogleContainerTools/skaffold#3163]
### Expected behavior

Our usecase is as follows, we need to build and push the image with a calculated tag to a repository without deploying it immediately. The `skaffold build` command currently does not support the `--tag` flag same as the `skaffold run`, which makes our desired behavior quite impossible without generating a `skaffold.yml` for each build. 

### Actual behavior

While the `skaffold run` command supports the flag, `skaffold build` does not.

### Information

- Skaffold version: v0.41.0
- Operating system: OSX

**Comment by balopat** [comment]
Thanks for opening @Inkdpixels! I'm open to have this, but we don't have a lot of capacity anytime soon, PRs are welcome! 
It should be relatively easy to implement given the `--tag` feature in `skaffold run` - needs integration tests and unit tests to make sure everything is working nicely.

**Comment by ishankhare07** [comment]
@balopat I'll be happy to take this up if its open.
Just to be clear, I guess we just need to replicate the `--tag` options from `skaffold build` to `skaffold run`
