### ISSUE TITLE
skaffold init fails for Maven project using Jib

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/skaffold#3188]
### Expected behavior

Maven w/ Jib plugin configured, and Kubernetes manifest files created.

`skaffold init` should generate the `skaffold.yaml`

### Actual behavior
```
$ skaffold init -v=debug
INFO[0000] Skaffold &{Version:v0.40.0 ConfigVersion:skaffold/v1beta16 GitVersion: GitCommit:4058d66b191038f4c3ac27ea2433a2dfccd40c5e GitTreeState:clean BuildDate:2019-10-12T03:08:04Z GoVersion:go1.13.1 Compiler:gc Platform:darwin/amd64}
DEBU[0000] skip walking hidden dir .git
DEBU[0000] skip walking hidden dir .idea
DEBU[0000] skip walking hidden dir .mvn
INFO[0000] found valid k8s yaml: k8s/deployment.yaml
INFO[0000] found valid k8s yaml: k8s/service.yaml
FATA[0000] one or more valid builder configuration (Dockerfile or Jib configuration) must be present to build images with skaffold; please provide at least one build config and try again or run `skaffold init --skip-build`
```

### Information

- Skaffold version: v0.40.0
- Operating system: OSX
- Contents of skaffold.yaml: none

### Steps to reproduce the behavior

1. Maven w/ Jib plugin configured
2. Create Kubernetes manifiests
3. `skaffold init`

**Comment by chanseokoh** [comment]
Jib detection is not yet enabled by default, and you should use `--XXenableJibInit` (or `--enableJibInit`, not sure). The flag is there to coordinate with IDEs. And always try with the latest Skaffold and Jib, since we fixed some issues on both sides recently.

**Comment by dgageot** [comment]
Let's close this issue since it's the desired behaviour, for now. See https://github.com/GoogleContainerTools/skaffold/issues/2842
