### ISSUE TITLE
Skaffold init in force mode still opens interactive mode when choice is ambiguous

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#3221]
Setup:
* Use https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world project
* Remove `skaffold.yaml`
* Run 
```
skaffold init --analyze --XXenableJibInit
{"builders":[{"name":"Docker","payload":{"path":"Dockerfile"}},{"name":"Jib Maven Plugin","payload":{"path":"pom.xml"}}],"images":[{"name":"java-hello-world","foundMatch":false}]}
```
* Add `--force`, remove `--analyze` to try to force configuration:
```
skaffold init --force --XXenableJibInit
? Choose the builder to build image java-hello-world  [Use arrows to move, space to select, type to filter]
> Docker (Dockerfile)
  Jib Maven Plugin (pom.xml)
  None (image not built from these sources)
```

*Expected*: skaffold to fail with non-zero code indicating it cannot force the ambiguous configurations.

**Comment by TadCordle** [comment]
I think the purpose of `--force` was to force overwriting existing skaffold configurations, not to force skip the interactive menu, correct? Is this a feature request?

**Comment by etanshaul** [comment]
`--force` seems to imply that something will happen no matter what - either a config file is generated, or failure

**Comment by ivanporty** [comment]
I would think of it as force create configuration no matter what or fail

**Comment by ivanporty** [comment]
Thanks @TadCordle!
