### ISSUE TITLE
deprecate `useDockerCLI` and `useBuildkit`

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3248]
Thanks to the `custom` builder, we could remove `useDockerCLI` and `useBuildkit` from the `docker` builder. If people want to use bleeding edge flags of the Docker CLI, they will be able to do it with the`custom` builder.

**Comment by balopat** [comment]
I'm okay with this as long as we generate a custom build script that is equivalent during `skaffold fix`.

**Comment by dgageot** [comment]
I tried to do that but I hit one issue: The custom build script that we'd generate would be linux only. That made me think wether the custom builder should have two build commands. One windows only and one used in any other case.

@balopat @nkubala wdyt?

**Comment by nkubala** [comment]
mmm that feels a little strange to me. would it be possible to do platform-specific script generation in skaffold instead? though maybe that's weird as well.

**Comment by nkubala** [comment]
@dgageot you think this is something we'll realistically do? seems like maybe more trouble than it's worth, and I've seen at least one person using buildkit through env vars recently

**Comment by dgageot** [comment]
It's indeed a nice espace hatch in case of an issue in the docker builder.
I let you close it.

Le jeu. 30 juil. 2020 à 21:15, Nick Kubala <notifications@github.com> a
écrit :
