### ISSUE TITLE
Remove`gcsBucket` upload strategy for in-cluster builds

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3249]
Since we introduced the `localDir` build context, it seems that the we could deprecate the `gcsBucket` build context. I see multiple advantages:

 + It makes current code simpler
 + Supporting additional artifact types, in-cluster, would be simpler to implement
 + It would make it easier for users to understand if the kaniko secret is for pulling from GCS or pushing to GCR or both.

**Comment by balopat** [comment]
I think this makes sense.
I wonder if anyone is using it or not. 
@prary I know you are using Kaniko extensively with Skaffold - do you use `GCS` or `localdir`?

**Comment by prary** [comment]
Hi @balopat 
We use localdir.
