### ISSUE TITLE
Add gitTag to TagPolicy

### ISSUE THREAD

**Issue by quasiben** [GoogleContainerTools/skaffold#325]
I see that there is a `gitCommit` tag policy but I would like to use `git tags` as the tag for my docker during build.  Would it be possible to add this as a new policy ?

**Comment by dlorenc** [comment]
We've discussed allowing users to specify a Go template string that we would execute against a bunch of git variables, things like branch name, commit sha, tags, etc. I think that would suit this use case as well.

**Comment by dgageot** [comment]
@quasiben the git tagger now uses the current tag if there's one, over the commit sha1. Do you think it solves your issue?

**Comment by dlorenc** [comment]
Closing, I think this has been fixed like @dgageot mentioned.

**Comment by quasiben** [comment]
@dgageot yes, thank you!  apologies for not responding earlier
