### ISSUE TITLE
Setting specific profile with flag should override any activations (which are 'implicit')

### ISSUE THREAD

**Issue by botwhytho** [GoogleContainerTools/skaffold#3261]
### Expected behavior

We have some profiles with kubecontext activation in our skaffold configs but have other profiles ('testing' for example) that are unable to run even when running `skaffold run -p test` because the kubecontext activation seems to override that profile.

It is a common pattern for runtime flags to take precedence of more 'implicitly set' values like a config file or the default values. Skaffold seems to break this assumption/pattern

### Actual behavior

At least with kubeContext activations (haven't tested with others), the profile with that activation will be triggered as opposed to the profile explicitly set with `-p/--profile [PROFILE NAME]`. Also, documentation doesn't make it clear if two profiles would run at once if activation would trigger both of them (I am aware that one can explicitly run more than one profile, not sure if this works with activations as well).

Finally skaffold should probably print to stdout what profile is using as this would aid a lot in troubleshooting such issues.

### Information

- Skaffold version: v0.36.0
- Operating system: both observed in macOS 10.14.6 and Debian Stretch docker container

### Steps to reproduce the behavior

I cannot post specific kubeContext values here but a skaffold.yaml with two profiles should reproduce this easily:
* One profile ('profile-a') can deploy service a and have a `kubeContext` activation
* The other one ('profile-b') can deploy service b and have no activation
* Running `skaffold deploy -p profile-b` with the Kubernetes context of profile a as the current context will deploy service a and NOT service b

**Comment by balopat** [comment]
Thank you for opening @botwhytho - this should be relatively easy to fix and I agree that we are breaking here a conventional pattern. @dgageot you want to take a shot at this, I see you self-assigned?
