### ISSUE TITLE
microservices example is broken

### ISSUE THREAD

**Issue by riker09** [GoogleContainerTools/skaffold#3266]
I wanted to get familiar with Skaffold, as this seems to solve many of the issues we're facing with day-to-day development. However, I cannot get the microservices example to run.

### Expected behavior

`minikube service leeroy-web --url` to resolve to an URL 

### Actual behavior

```
💣  Error opening service: Service leeroy-web was not found in "default" namespace. You may select another namespace by using 'minikube service leeroy-web -n <namespace>: Temporary Error: Error getting service leeroy-web: services "leeroy-web" not found

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

### Information

- Skaffold version: v1.0.0
- Operating system: Ubuntu 19.10 @ 5.3.0-23-generic
- Minikube version: v1.5.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000

```

### Steps to reproduce the behavior

1. Clone this repository
2. `cd examples/microservices && skaffold dev`
3. In another terminal: `curl $(minikube service leeroy-web --url)`

**Comment by riker09** [comment]
It looks like I'm having the same issue as in #2381.

I can `kubectl port-forward pod/leeroy-web-d5bf49d8c-mfsvx 8888:8080` but `minikube service leeroy-web --url` still gives me an error.

**Comment by riker09** [comment]
Actually, nevermind, I missed the `--port-forward` flag as mentioned in the [documentation](https://skaffold.dev/docs/pipeline-stages/port-forwarding/).

The documentation in `examples/microservices/README.adoc` should at least mention this, imho.

**Comment by laurentvaills** [comment]
I met that same issue. I think this issue could reopened to have the documentation updated like: 
- Running skaffold like this: `skaffold dev --port-forward` 
- The curl commands updated to this: `curl http://localhost:9000/` 

The `Service` was removed in this commit https://github.com/GoogleContainerTools/skaffold/commit/3f93642deee42e3ad3dfab741fec88850f14a85b . 
@balopat : What was your motivation to remove the `Service` ?  

I'm keen to create a PR to either add it back or to update the documentation as I suggested. Any preference ?

**Comment by etix** [comment]
The documentation is obviously wrong and an update would be welcome indeed.

**Comment by nkubala** [comment]
hey y'all, sorry for the radio silence on this one. it does seem like we have some holes in our documentation here. @laurentvaills would you still be interested in sending a PR to update them?

**Comment by laurentvaills** [comment]
I would have been interested in providing a PR for this and being able to
contribute, but unfortunately I'm too much busy at the moment and won't
have time to set it up.


Le ven. 28 févr. 2020 à 19:42, Nick Kubala <notifications@github.com> a
écrit :
