### ISSUE TITLE
header part of CLI document does not list `debug` & `credits` subcommand

### ISSUE THREAD

**Issue by oke-py** [GoogleContainerTools/skaffold#3270]
### Expected behavior

header part of CLI document should list all subcommands.
`debug` and `credits` should be added.
https://skaffold.dev/docs/references/cli/

### Actual behavior

`debug` and `credits` are not listed.

**Comment by balopat** [comment]
Thanks @oke-py, yupp, that's missed. Easy fix: 

- fix in https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/docs/references/cli/index_header
- run `hack/generate-man.sh`

**Comment by dgageot** [comment]
@oke-py would you like to submit a PR?

**Comment by oke-py** [comment]
I submitted a PR.
