### ISSUE TITLE
improve error message when docker is not installed

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3275]
We should reproduce and improve the messaging here: 

![image](https://user-images.githubusercontent.com/635073/69282066-4941aa80-0b9e-11ea-9324-df6870ab6ff3.png)

**Comment by prary** [comment]
Hi @balopat
Plus this #3225 .

**Comment by tstromberg** [comment]
This seems to be improved now when Docker is not installed:

```
FATA[0006] exiting dev mode because first build failed: couldn't build "skaffold-example": docker build: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? 
```
