### ISSUE TITLE
Use fully-qualified jib plugin references for Maven

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#3280]
The Skaffold-Jib binding currently requires Jib to be explicitly referenced in a Maven project through a `<plugins>` or `<pluginManagement>` reference in the root `pom.xml`.  If we instead referenced the plugin with its group-artifact IDs (`mvn com.google.cloud.tools:jib-maven-plugin:build`) instead of the plugin-prefix (`jib`) then we should be able to do away with this `<plugins>`/`<pluginManagement>` requirement.  This change would reduce the number of steps required to get Skaffold working with a Maven project.

(When Maven is invoked with a version less fully-qualified name, it uses the latest version available unless the project has configured a version of jib already.)

The user would still need to do the following:
  - add `artifact: xxx / jib: {}` to their `skaffold.yaml`

What are the breaking situations?
  - Project packagings other than `jar` and `war` would not produce an image
  - Projects without `jib-maven-plugin` wouldn’t fail (but users had to configure the artifact)
  - Jib's `skaffold init` currently looks for modules referencing `jib-maven-plugin`

Is our default configuration good enough for the general (Skaffold-K8s) case?
  - Ports?  (But not actually necessary for k8s)
  - JVM Flags?  Our examples use `-Djava.security.egd=file:/dev/./urandom` to avoid slow-starts from insufficient entropy in the system. It that's recommended ([there seems to be some disagreement](https://www.2uo.de/myths-about-urandom/)), perhaps it should be Jib's default jvmFlags, or we could set them using the `jib.container.jvmFlags` property

**Comment by briandealwis** [comment]
Quick stab at https://github.com/briandealwis/skaffold/pull/new/jibmaven-group-artifact — doesn't address `skaffold init`.

**Comment by chanseokoh** [comment]
I think the idea makes sense. I wonder if we can have a feature parity with Gradle.

**Comment by briandealwis** [comment]
Maybe with an [init script](https://docs.gradle.org/current/userguide/init_scripts.html)?

**Comment by dgageot** [comment]
@briandealwis any news on this one?

**Comment by chanseokoh** [comment]
> Maybe with an [init script](https://docs.gradle.org/current/userguide/init_scripts.html)?

Oh, yeah. I actually used `init script` for [jib-gradle Tekton catalog sample](https://github.com/tektoncd/catalog/blob/b35554f9bfaf3a65ee97c4d29cad4e91d9977c7b/jib-gradle/jib-gradle.yaml#L30-L41). But I don't think it works well for a multi-module Gradle project.

**Comment by briandealwis** [comment]
I remember we had a discussion around this idea and had some reservations.  It doesn't look like we documented them anywhere however, except for this gradle feature-parity issue.  Given that certain setups will require additional configuration (e.g., `war` projects and the `appRoot` for non-Jetty configs), and other plugins are now incorporating Jib directly, I'm not sure if not requiring some configuration is a good idea.
