### ISSUE TITLE
Installing Skaffold page does not actually talk about how to install it

### ISSUE THREAD

**Issue by talonx** [GoogleContainerTools/skaffold#3286]
### Expected behavior
Instructions on how to install Skaffold should be there. E.g. a one liner like 
```
get https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64  -O /usr/local/bin/skaffold
```
is sufficient, for Linux.

### Actual behavior
No such information.

### Information

NA
### Steps to reproduce the behavior

Visit https://skaffold.dev/docs/install/

**Comment by balopat** [comment]
Thank you for opening @talonx! 

In my browser I see this: 

![image](https://user-images.githubusercontent.com/635073/69573524-238c1b00-0f7b-11ea-841c-30b2b518975a.png)

Maybe Javascript is disabled in your browser? I think that might be the issue.

**Comment by talonx** [comment]
Strangely enough I can see the content now. Perhaps my ad-blocker was the culprit and blocking one of the CDNs serving JS. Thanks!
