### ISSUE TITLE
Unable to run docker-compose file through skaffold in Openshift

### ISSUE THREAD

**Issue by reddybhavaniprasad** [GoogleContainerTools/skaffold#3288]
I am trying to run docker-compose file through skaffold in Openshift and found the following command in [https://github.com/GoogleContainerTools/skaffold/tree/master/examples/compose](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/compose)

	skaffold init --compose-file docker-compose.yaml

### Expected behavior
It should generate kubernetes manifests based on the docker-compose configuration, which generates skaffold configuration on issue of "**skaffold init**" command

### Actual behavior
It fails with the following error:

	+ skaffold init --compose-file docker-compose.yaml --verbosity=info
	time="2019-11-25T07:37:38Z" level=info msg="Skaffold &{Version:v0.37.0 ConfigVersion:skaffold/v1beta13 GitVersion: GitCommit:b3aa6b0a95ea1e87fd8420df195c3c2d35d8341a GitTreeState:clean BuildDate:2019-08-29T20:44:03Z GoVersion:go1.12.9 Compiler:gc Platform:linux/amd64}"
	time="2019-11-25T07:37:38Z" level=info msg="running 'kompose convert' for file docker-compose.yaml"
	time="2019-11-25T07:37:38Z" level=fatal msg="running kompose: exit status 1"

### Information

- Skaffold version: v0.37.0
- Operating system: RHEL

I am unable to understand what is the cause of the error since the error message is too short. Please help me to resolve the issue and correct me if I am doing anything wrong.

**Comment by balopat** [comment]
Hi @reddybhavaniprasad, thanks for opening this issue! 
Can you provide a minimal / non-sensitive version of your docker-compose file so that we can reproduce it? 
Thanks!

**Comment by dgageot** [comment]
I pushed that PR to make future failures easier to understand: https://github.com/GoogleContainerTools/skaffold/pull/3299

**Comment by reddybhavaniprasad** [comment]
@balopat, thanks for the reply. I got to understand that the issue is due to missing docker-compose.yaml file.

Actually I am using docker-compose.yml file instead of docker-compose.yaml. Since the file is unavailable it fails with "running kompose: exit status 1" error.

I think it would be better if the error msg is "docker-compose.yml: No such file or directory"

**Comment by dgageot** [comment]
@reddybhavaniprasad for sure! I'll push a PR that checks of the file exists

**Comment by reddybhavaniprasad** [comment]
"skaffold init" now fails with "Invalid k8s yaml" error. Please find below the error log.

	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/Chart.yaml: decoding kubernetes yaml: Object 'Kind' is missing in 'apiVersion: v1\nappVersion: 0.0.84\ndescription: A Helm chart for Kubernetes\nname: user-interface\nversion: 0.0.84\n'"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/config-map.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/deployment.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/ingress.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/ksvc.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/service.yaml: decoding kubernetes yaml: yaml: line 11: could not find expected ':'"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/volume.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/templates/volumeclaim.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string"
	time="2019-11-26T08:57:19Z" level=info msg="invalid k8s yaml charts/user-interface/values.yaml: decoding kubernetes yaml: Object 'Kind' is missing in '# Default values for helm.

I came across the similar issue which has been already resolved. https://github.com/GoogleContainerTools/skaffold/issues/1726

So, please share if there is any option to mention the deploy type (like helm) in the "skaffold init" command or any other way to resolve this issue.

**Comment by balopat** [comment]
Hi @reddybhavaniprasad - I closed this issue as the original issue is closed. Do you mind adding this comment to #1726? My answer is going to be: helm support for skaffold init is on our roadmap for Q1!

**Comment by reddybhavaniprasad** [comment]
Hi @balopat - When can we expect the Q1 release to support helm support.
