### ISSUE TITLE
Skaffold (helm-deployment) should work within namespace RBAC restrictions

### ISSUE THREAD

**Issue by kylewolfe** [GoogleContainerTools/skaffold#3311]
Related / follow up to #1521

 # Expected behavior

`skaffold dev` should work on `examples/helm-deployment` w/ a cluster that has RBAC restrictions (user has access to one namespace)

### Actual behavior

Excerpt:
```
Starting deploy...
Helm release skaffold-helm not installed. Installing...
No requirements found in skaffold-helm/charts.
NAME:   skaffold-helm
LAST DEPLOYED: Wed Nov 27 13:08:35 2019
NAMESPACE: my-namespace
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME           READY  UP-TO-DATE  AVAILABLE  AGE
skaffold-helm  0/1    0           0          0s

==> v1/Service
NAME                         TYPE      CLUSTER-IP     EXTERNAL-IP  PORT(S)       AGE
skaffold-helm-skaffold-helm  NodePort  xxxxxx  <none>       80:34590/TCP  0s

==> v1beta1/Ingress
NAME                         HOSTS  ADDRESS  PORTS  AGE
skaffold-helm-skaffold-helm  *      80       0s


Cleaning up...
release "skaffold-helm" deleted
time="2019-11-27T13:08:38-05:00" level=fatal msg="starting logger: initializing aggregate pod watcher: initializing pod watcher for : unknown (get pods)"
```

### Information

- Skaffold version: 1.0.1
- Have ability to watch resource within namespace (eg: `kubectl proxy` followed by `http://localhost:8001/api/v1/namespaces/my-namespace/pods?watch=1`)
- I successfully tested against my local docker desktop cluster which I have full access to

### Steps to reproduce the behavior

1. Create and connect to cluster / namespace as user who only has access to that one namespace
2. `git clone https://github.com/GoogleContainerTools/skaffold`
3. `cd skaffold/example/helm-deployment`
4. Update `skaffold.yaml` artifacts to something you have access to
5. `skaffold dev`

**Comment by balopat** [comment]
Thanks for opening, this seems like a regression indeed compared to #1521 - we need to investigate!

**Comment by nkubala** [comment]
hey @kylewolfe we recently had some changes that went into the helm deployer that may have addressed this issue. would you mind trying this out again from HEAD and letting us know if you're still seeing this issue? thanks!

**Comment by kylewolfe** [comment]
Sorry for the delay. Testing from master today:
```
exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "xxxxxxxxxxxxxx" cannot list resource "deployments" in API group "apps" at the cluster scope: access denied
```

**Comment by kylewolfe** [comment]
> Settings tail to false removes the problem

@Xan2063 Can you elaborate on this? I'm unfamiliar with a tail option anywhere.

**Comment by Xan2063** [comment]
From the cli docs for skaffold dev
--tail=false: Stream logs from deployed objects (true by default for `skaffold dev` and `skaffold debug`)

https://skaffold.dev/docs/references/cli/

**Comment by kylewolfe** [comment]
Thanks for that!

It just so happened that I tested with `sync` at first. After removing sync and running `skaffold dev --tail=false`, it's still attempting to read at the cluster scope.

**Comment by Xan2063** [comment]
You should also add your namespace with -n to the Skaffold call

**Comment by kylewolfe** [comment]
Thanks again.

Confirmed works with `skaffold --tail=false -n <namespace>`. Also confirmed that sync attempts to list pods at cluster scope.

**Comment by tejal29** [comment]
Thanks @kylewolfe for confirming. Closing this issue now.

**Comment by Xan2063** [comment]
I would not close this issue as the missing sync and tail feature is pretty annoying...

**Comment by kylewolfe** [comment]
Yes. I think those both need tracked. Without those, I'm still not going to adopt skaffold.

**Comment by sarmad-abualkaz** [comment]
I was seeing the same issue on skaffold version v1.12.1 - `starting logger: initializing pod watcher for "": unknown (get pods)` when my user RBAC is scoped to a single namespace as well. 

I've been able to work around it by adding the namespace field under the helm release section:
```
    deploy:
      helm:
        releases:
        - name: <release-name>
          namespace: <release-namespace>
```

With the above setup I'm able to watch logs and sync works as well. 

It seems like installing the release honors the `SKAFFOLD_NAMESPACE` or `-n`/`--namespace` (without the `namespace` field under `deploy.helm.release`) but the log watch isn't.

**Comment by Xan2063** [comment]
@sarmad-abualkaz Thanks for the hint, I will definitely try that in the next days!

**Comment by sarmad-abualkaz** [comment]
I think I have a fix for this problem actually - I'm opening a PR soon, @nkubala I'm adding you as a reviewer, let me know if that's okay?

**Comment by kylewolfe** [comment]
Should we reopen this issue for the sync issue described earlier, or should a new one be opened for that?

**Comment by sarmad-abualkaz** [comment]
Tbh @kylewolfe I'm not seeing any sync issues anymore - I'm using sync with 3 different images and appears to work fine for me without cluster-wide RBAC (my RBAC is scoped to a single ns). 

Just to confirm, by 'sync' you mean this setup?
```
build:
  ...
  artifacts:
     - image: <docker-image>
        # keep a sync of file changes locally to file content inside running pod/container:
        sync:
        ...
```
