### ISSUE TITLE
Fetch k8s events on kaniko pod failure

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#3345]
If kaniko pod fails due to platform reason let say ephemeral storage full then kaniko pod simply fails with ```Pod already in terminal phase error```. But if we have the ability to fetch the events related to kaniko pod or namespace then it would be extremely useful.
 
### Expected behavior
On kaniko pod failure, pod scheduler events should be fetched as well.
### Actual behavior
Present it doesn't pull the events.
### Information

- Skaffold version: latest
- Operating system: All

**Comment by tejal29** [comment]
@prary Thanks for your PR. 
We are working on a overall diagnose story to see how we can solve this question. 
I will take a look at your PR next week, to see if  its is aligned with our thinking. 

Thanks a lot!

**Comment by tejal29** [comment]
This is still in scope and a priority.

**Comment by prary** [comment]
Hi @tejal29
I have updated the PR ```make checks``` is failing meanwhile take look at the functionality of it.

**Comment by tstromberg** [comment]
@tejal29 - any news?

**Comment by tejal29** [comment]
@prary and @tstromberg This is being actively worked on in https://github.com/GoogleContainerTools/skaffold/issues/3915

We are looking into integrating pod events.

**Comment by tstromberg** [comment]
@tejal29 - good to hear. Thank you!

**Comment by tejal29** [comment]
We don't havepod events for kaniko still but we have got better at surfacing kaniko pod logs. 
Closing this now since its close to 2 years and we haven't had time to work on this.
