### ISSUE TITLE
It would be great to have supports for skaffold.yaml in intellij!

### ISSUE THREAD

**Issue by jiraguha** [GoogleContainerTools/skaffold#3347]
Hi,

Maybe it would be great to have inspections supports for skaffold.yaml in intellij or code as kubernetes does.

Stuff like:
- yaml validation
- auto completion

Is this could have an added value for skaffold?

Br,
JP

**Comment by bdudelsack** [comment]
It's already there: https://cloud.google.com/tools/intellij/docs/

**Comment by jiraguha** [comment]
Thanks man!  It provides skaffold auto doc! This should be enough for my usage :-).
