### ISSUE TITLE
Error parsing Dockerfile FROM "scratch" where scratch is quoted

### ISSUE THREAD

**Issue by nic-larkin** [GoogleContainerTools/skaffold#3364]
### Expected behavior
Skaffold should be able to process a valid Dockerfile. 

### Actual behavior
skaffold dev exits with following log:

FATA[0000] watching files for artifact xxx/xxx: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image ("scratch") for ONBUILD triggers: getting remote config: getting image: parsing reference ["scratch"]: could not parse reference: "scratch"

### Information
- Skaffold version: v1.0.1
- Operating system: CentOS Linux release 7.7.1908 (Core)
- Contents of skaffold.yaml: not provided (and shouldn't be needed)

### Steps to reproduce the behavior
-  Start with a working skaffold / Dockerfile setup where the Dockerfile has the line FROM scratch.
-  Add double quotes around the scratch making FROM "scratch"
-  Confirm dockerfile still builds via docker build.
-  Run skaffold and you should see the error above.

**Comment by nkubala** [comment]
hey @nic-larkin thanks for the issue. I was able to reproduce this, and after digging in a bit I think this might be a bug with the docker parser.

checking out the nodes from the AST constructed by the parser, I see this node for the `FROM "scratch"` line:

```golang
Value:from Next:0xc0002e53b0 Children:[] Attributes:map[] Original:FROM "scratch"" Flags:[] StartLine:1 EndLine:1
```

so it parses my image as `"scratch""`, which has a conspicuous double quote at the end, and sure enough that's what makes go-containerregistry eat it:

`...processing base image ("scratch"") for ONBUILD triggers: getting remote config: getting image: parsing reference ["scratch""]: could not parse reference: "scratch""
`

I don't see the double quote in your error string that you posted though? so I'm not quite sure what to make of that.

**Comment by nic-larkin** [comment]
Hello there, thanks for the swift reply.  I just double checked the error message and there is only a single quote so I guess we might be using different versions of something.

I can repro it minimally with :

skaffold.yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: example

Dockerfile
FROM “scratch”

In case it’s any use:
> docker version
Client: Docker Engine - Community
Version:           19.03.5
API version:       1.38 (downgraded from 1.40)
Go version:        go1.12.12
Git commit:        633a0ea
Built:             Wed Nov 13 07:25:41 2019
OS/Arch:           linux/amd64
Experimental:      false

Server:
Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
