### ISSUE TITLE
skaffold init using docker compose configuration fails with "Nil Pointer Dereference" error

### ISSUE THREAD

**Issue by reddybhavaniprasad** [GoogleContainerTools/skaffold#3370]
I am trying to generate skaffold configuration for docker-compose configuration using the following init command

	+ skaffold init --compose-file docker-compose.yml --verbosity=info

### Expected behavior

The command should generate k8s manifests based on the docker-compose configuration and should generate skaffold configuration on issue of "skaffold init" command

### Actual behavior

This fails with the following "nil pointer deference" error

	time="2019-12-11T15:44:08Z" level=info msg="generating skaffold config"
	panic: runtime error: invalid memory address or nil pointer dereference

### Information

- Skaffold version: v0.37.0
- Operating system: RHEL
- Contents of skaffold.yaml: No skaffold.yaml

### Steps to reproduce the behavior

1. Run "skaffold init --compose-file docker-compose.yml --verbosity=info" with a basic docker compose file.

**Comment by balopat** [comment]
Thanks for opening @reddybhavaniprasad! 
Can you share your docker-compose.yml for reference?

**Comment by dgageot** [comment]
@reddybhavaniprasad any update?

**Comment by briandealwis** [comment]
Closing; will re-open if a reproduction is provided.
