### ISSUE TITLE
skaffold init command to use the existing k8s files instead of creating new ones for docker-compose configuration

### ISSUE THREAD

**Issue by reddybhavaniprasad** [GoogleContainerTools/skaffold#3371]
skaffold init with docker compose configuration uses "komopse convert" to generate the k8s manifest files. I want skaffold to use the existing k8s config files instead of creating new ones.

Please suggest me how I can do that using skaffold.

### Expected behavior

skaffold should generate configuration file based on the existing k8s manifest files instead of creating new ones (without "kompose convert").

### Actual behavior

Following is the log for skaffold init command:

    + skaffold init --compose-file docker-compose.yml --verbosity=info
    time="2019-12-11T11:44:08Z" level=info msg="Skaffold &{Version:v0.37.0 ConfigVersion:skaffold/v1beta13 GitVersion: GitCommit:b3aa6b0a95ea1e87fd8420df195c3c2d35d8341a GitTreeState:clean BuildDate:2019-08-29T20:44:03Z GoVersion:go1.12.9 Compiler:gc Platform:linux/amd64}"
    time="2019-12-11T11:44:08Z" level=info msg="running '**kompose convert**' for file docker-compose.yml"

### Information

- Skaffold version: v0.37.0
- Operating system: RHEL
- Contents of skaffold.yaml: No skaffold.yaml

**Comment by nkubala** [comment]
hey @reddybhavaniprasad, thanks for the issue. can you give a little more info on your project structure? are you saying that you've already written the k8s manifests that correspond to the services you defined in your docker-compose.yml? if so, then you should just be able to run `skaffold init` without telling it anything about your compose file (assuming you have Dockerfiles for each of your images in the same directory).

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
