### ISSUE TITLE
How to use jib instead of jibDockerBuild using gradle ?

### ISSUE THREAD

**Issue by lduparc** [GoogleContainerTools/skaffold#3372]
How can we define jib command to use jib instead of jibDockerBuild ?

Currently using gradle is this can be define on build.gradle or can we do it on skaffold.yml config file ?

**Comment by tejal29** [comment]
@loosebazooka or @chanseokoh would you be able to answer this?

**Comment by chanseokoh** [comment]
@lduparc sorry, I'm not sure I understand your question. Jib does not make use of your local Docker client or engine. For example, if Skaffold is configured to use a remote Kubernetes cluster, Jib will push an image directly to a remote registry (basically doing `gradle jib`). If Skaffold is configure to use a local cluster like Minikube, Jib will load an image to the internal Docker engine running inside Minikube. In this case, it does `gradle jibDockerBuild`, but even in this case, it doesn't build to your local Docker daemon.

**Comment by briandealwis** [comment]
Closing as the question is answered and there was no follow-up.
