### ISSUE TITLE
The project doesn't open properly in IntelliJ/GoLand

### ISSUE THREAD

**Issue by iirekm** [GoogleContainerTools/skaffold#3384]
I'm trying to debug https://github.com/GoogleContainerTools/skaffold/issues/3383 in intellij or goland
and it's painful: please provide working .idea files, or instructions how to open this project.
Using just `File > New > Project > From existing sources` doesn't work (lots of compilation errors).

**Comment by balopat** [comment]
What is your operating system? 
I am using IntelliJ / GoLand to develop Skaffold on OSX. 
For me this works: 

```
cd ~ 
git clone git@github.com:GoogleContainerTools/skaffold.git
```

`File > Open...`, choose `~/skaffold`, and that's it, it takes a couple of minutes to get the modules sorted out. 

It's the first time I tried `From existing sources` and it does act weird: on my installation it picks up all the examples as modules, but not the main Go module!  

Let me know if this helped or not and I can add it to our DEVELOPMENT.md

**Comment by iirekm** [comment]
Still no improvement: GoLand detects libraries, downloads them to `vendor`
directory, imports from Go distribution are processed correctly in the
editor, imports from other skaffold .go files, and from libraries
downloaded to 'vendor' are displayed in red.
Ubuntu 18.04, GoLand 2019.3

wt., 17 gru 2019 o 17:57 Balint Pato <notifications@github.com> napisał(a):

**Comment by balopat** [comment]
OK, let me try with actual GoLand - I was using IntelliJ + Go plugin.

**Comment by balopat** [comment]
Still works for me, if I click on `Vendoring mode` in `Preferences > Go > Go modules`, then it's faster too, as the vendor directory is checked into git. 

![image](https://user-images.githubusercontent.com/635073/71021975-b003a680-20ff-11ea-8464-3a433fa666bd.png)

What version go do you use? I'm on go 1.13.1.

**Comment by iirekm** [comment]
Ah ok, `Vendoring mode` helps me. Without it there are problems in my
GoLand.
Thank you for help.

wt., 17 gru 2019 o 19:02 Balint Pato <notifications@github.com> napisał(a):
