### ISSUE TITLE
`skaffold run --tail` doesn't exit if all pods are complete

### ISSUE THREAD

**Issue by iirekm** [GoogleContainerTools/skaffold#3388]
Such infinite waiting doesn't make much sense in most cases, `skaffold run --tail` should exit after things complete, similarly to `kubectl logs --f` or `docker logs -f` which exit after completion.

**Comment by iirekm** [comment]
Workaround: `skaffold run && for i in $(seq 30); do kubectl logs -f -l app=test && break || sleep 1; done`

**Comment by balopat** [comment]
This feature sounds good to me. It will require a bit of wiring so I wouldn't say a "good first issue" level, but can be fun. We need to make sure that it does not interfere with "dev" and that `deploy --tail` works the same. We should write an integration test to cover the functionality.

**Comment by zhuhaow** [comment]
I think this should be part of `--status-check`. 

IMHO, `run` should by default enable `--status-check` and stream log until either succeed or timeout.

**Comment by tstromberg** [comment]
@tejal29 - does status check address this in any way?

**Comment by nkubala** [comment]
i'm not sure i understand the original issue here. `skaffold run --tail` is meant to do a `skaffold run`, with an attachment to the application logs to continue to monitor them after the resources are created. `kubectl logs -f` can be used to get a glimpse at pod logs after they're deployed, which is different than our log tailing. if `skaffold run --tail` exited after everything completed, then they wouldn't show anything.

i think what you might be asking for is "startup logs", or the logs that are outputted in the pods by the application before a readiness probe would say that the application has started and is ready - i.e. logs that are put out by spring when it's starting up. this isn't something that we support right now.

as for status check, this is now enabled by default for `run`, but again, the logs during the "deploy complete" on the client and the "application ready" from status check aren't being streamed.

if application startup logs are a feature that people would like to see, please open another issue to track it. i'm going to close this one for now though.
