### ISSUE TITLE
Testable dev infrastructure with Config Connector

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3398]
**Problem**: Currently a bunch of our test and release infra is maintained manually: 
- the integration-test cluster with the kaniko-secret in it (we should store encrypted secrets in git and integrate with a secret service somehow to decrypt them during deployment)
- the docs cluster with the docs-previewer (webhook) in it (which is deployed at release time, but I'm pretty sure the process is broken, as we have to manually deploy a new version of the docs previewer - it doesn't get deployed from a branch, only after it's merged to master) 
- the Cloud Build triggers for releases  

**Solution**: We should store infrastructure as code as much as possible - one idea could be using [Config Connector](https://cloud.google.com/config-connector). In case the infrastructure is changed, we should be able to deploy a new infra on a PR and run a tests on them (test release process, and an integration test suite, etc.) 

I'm just going to leave this here for now. I know that this is a lot of work and currently it doesn't cause too much of an issue. As time goes on and the friction is increasing, we might pull the trigger on it. 

Another benefit: we could maintain a registry also in the integration cluster for the  `KanikoInsecureRegistry` and maybe other tests. Currently we deploy a new registry on every PR, losing 5 minutes of deployment time (until the registry + loadbalancer gets deployed). 

Let me know what you all think.

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment.
