### ISSUE TITLE
`skaffold run --port-forward` behaves like it's freezing

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3415]
Starting with https://github.com/GoogleContainerTools/skaffold/pull/3263, it's possible to run `skaffold run --port-forward`.

I found the behaviour puzzling, it looked like if it was freezing when in fact it was waiting for me to ctrl-c.
A message making that clear to the user might be good.

Another issue I have with this new behaviour is that I used to have `export SKAFFOLD_PORT_FORWARD=true` in my `.bashrc`. This was useful to have port forwarding always on for `skaffold dev`. Now I have to remove this line because it also enables pf for `skaffold run` which is something I very rarely want.

Finally, the PR introduces a regression [here](https://github.com/GoogleContainerTools/skaffold/pull/3263/files#diff-6570d04478f61ff7f9c91cab1437f91cR100). The initial logs can be lost if the deployment takes more than a second.

**Comment by tstromberg** [comment]
@dgageot - are you still seeing this behavior?

**Comment by dgageot** [comment]
yes

**Comment by gsquared94** [comment]
The regression for lost logs has already been fixed. For the message added this PR which shows up like:![image](https://user-images.githubusercontent.com/39389231/81107151-8e973180-8ecb-11ea-8982-b3b86b807712.png)
