### ISSUE TITLE
HelmDeployer should detect helm version (2 or 3)

### ISSUE THREAD

**Issue by oke-py** [GoogleContainerTools/skaffold#3438]
### Expected behavior

New function to detect helm version should be added to `pkg/skaffold/deploy/helm.go`.

### Actual behavior

Helm version is assumed as v2.x.
Some helm command syntax changed in 3.x, and so, some skaffold function does not work as expected.

### Information

This is the prerequisite for #3386 and #3387.

area/deploy
deploy/helm3

### Steps to reproduce the behavior

N/A

**Comment by oke-py** [comment]
I'm trying this.

**Comment by KhaledSakr** [comment]
I think a better solution for https://github.com/GoogleContainerTools/skaffold/issues/3386 would be to always use `helm upgrade --install` since that seems to be the desired behaviour anyway. We shouldn't need to reimplement something in skaffold that is already supported by helm.

**Comment by ktarplee** [comment]
This is implemented [here](https://github.com/ktarplee/skaffold/blob/b8b09ee12110e36d41d61a3ac1397ee13fd5b1f9/pkg/skaffold/deploy/helm.go#L162)

**Comment by oke-py** [comment]
@ktarplee Thank you for information.
If I understand correctly, detecting helm version is not desired and helm3 deployer should be implemented.

**Comment by ktarplee** [comment]
I know that having a new deployed is preferred however I have not seen the argument so I have no opinion on the matter.  However it seems to me that one should not require a change to skaffold.yaml if they deploy to a cluster using a different version of helm as it is still just helm.  That’s my two cents, and I don’t much care which way you guys go so long as full helm 3 support comes soon.

**Comment by tejal29** [comment]
@ktarplee Thanks. Supporting Helm3 is our high on our priority list. Sorry this taking longer.

We do want to make sure, we give users plenty of time to upgrade their app helm2 to helm3. We will change the default to helm3 as per our SLA.

**Comment by ErwinSteffens** [comment]
Any update v3 support? We love the tool, but this is a serious hurdle in adopting it.

**Comment by nkubala** [comment]
@ErwinSteffens this was fixed with #3738! we'll ship it with the v1.5.0 release.

**Comment by ErwinSteffens** [comment]
> @ErwinSteffens this was fixed with #3738! we'll ship it with the v1.5.0 release.

Awesome, we will check it out!
