### ISSUE TITLE
Use a simpler script to extract licenses for `skaffold credits`

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3443]
I'd like to simplify the code that extracts the licenses used by `skaffold credits` for three reasons:
 + it's currently very opaque what the tool is doing
 + the tool fails to find credits for `github.com/BurntSushi/toml` which I need to vendor for buildpacks.
 + `github.com/google/trillian/scripts/licenses` is outdated and its replacement is very slow.

I'd like to replace `github.com/google/trillian/scripts/licenses` with a simple script that copies every `LICENSE*`, `COPYING*` and `NOTICE*` found in `vendor`

**Comment by dgageot** [comment]
@nkubala @balopat @tejal29 wdyt?

**Comment by nkubala** [comment]
in general yes I agree. I'd like to switch this to only run in CI and release jobs, the code has strange behavior across different environments and I don't feel that we need it for local builds.

**Comment by balopat** [comment]
I am hesitant to write our own tool for this. In particular the notes mentioned in the comments in [this file](https://github.com/google/go-licenses/blob/master/licenses/classifier.go) for different types of licenses and logic to enforce those rules seem pretty useful to me. 

I would rather go down the route of figuring out how to make the licensing tool faster and better, e.g. recognize non-standard license naming like COPYING in github.com/BurntSushi/toml.  

WDYT?

**Comment by dgageot** [comment]
@balopat I managed to use go-licenses in https://github.com/GoogleContainerTools/skaffold/pull/3493
Closing this one
