### ISSUE TITLE
Feature request: Run local tests before building and deploying

### ISSUE THREAD

**Issue by samos123** [GoogleContainerTools/skaffold#3475]
I would like the ability to specify a command to run before build starts such as run `make test` or running a local testing framework that is being used by the application. This test command should return exit 0 and anything thats not 0 should stop build and deployment.

I'm happy to implement this if there is consensus that it's something that's acceptable.

For example I would like to do this:
```
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: k8s-qos
test: make test
build:
  artifacts:
  - image: gcr.io/gsam-123/k8s-qos
    kaniko:
      buildContext:
        localDir: {}
      cache: {}
  cluster:
    pullSecret: kaniko-secret.json
    namespace: default
deploy:
  kubectl:
    manifests:
    - deployments/k8s-qos.yaml

**Comment by nkubala** [comment]
@samos123 thanks for the issue. this would be accomplished by supporting pre-build hooks in skaffold, which is something we're planning on prioritizing for this year. skaffold already has a `test` stage in the pipeline that runs [container structure tests](https://github.com/GoogleContainerTools/container-structure-test) between the `build` and `deploy` stages, maybe this is something you can make use of in the interim?

check out https://github.com/GoogleContainerTools/skaffold/issues/1441 for more context on the pre/post stage hooks.
