### ISSUE TITLE
Ide integration

### ISSUE THREAD

**Issue by bhack** [GoogleContainerTools/skaffold#348]
Do you have already any plan on how to integrate with ide?
I.e. https://github.com/atom/atom/issues/14860

**Comment by r2d4** [comment]
As a weekend project I started https://github.com/r2d4/vscode-k8s, which is available on the visual studio code marketplace at https://marketplace.visualstudio.com/items?itemName=kubernetes-tools.k8s

It exposes a "skaffold dev" and "skaffold run" right-click menu item on skaffold.yaml files, which runs in the integrated terminal.

I don't plan to devote much time to this right now, but I'd be happy to help others get started if theres enough interest.

**Comment by bhack** [comment]
@r2d4 I think that generally there is a specific issue about language servers and remote debbuger comunication cause dependencies are only available in the image.

**Comment by bhack** [comment]
I.e. For vscode see https://github.com/Microsoft/vscode-python/issues/79

**Comment by bhack** [comment]
Other than language server and interpreter or execution there is also the remote debugging.
An example for python but still not automated: https://github.com/DonJayamanne/vscode-python-samples/tree/master/remote-debugging-docker

**Comment by bhack** [comment]
Debugging on compiled languagehttps://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/PipeTransport.md#docker-example

**Comment by bhack** [comment]
Probably this cloud be interesting also if it is related to Draft https://github.com/Azure/vscode-kubernetes-tools/

**Comment by bhack** [comment]
I think that there could be something in common with Skaffold also for the debug requirements https://github.com/Azure/vscode-kubernetes-tools/pull/160

**Comment by bhack** [comment]
@r2d4 If you don't have enough bandwidth here I think that there could be a collaboration to reuse some common components of  https://github.com/Azure/vscode-kubernetes-tools if the Draft part will be pluggable and not embedded. Most of the features there are K8S related.  Do you think that there could be some contact between the Azure and Google Container teams about this or is it sci-fi? :wink:

**Comment by bhack** [comment]
Check also https://medium.com/solo-io/introducing-kubesquash-remotely-debug-your-kubernetes-pods-f3e3391eaf16

**Comment by itowlson** [comment]
@bhack At this stage the core team for VS Kubernetes Tools is focused more on Draft than on Skaffold (and, unfortunately, we have limited resource and can't do everything!), but we definitely want to enable folks to plug in additional tools.  I'm working surfacing an API from the VS Kubernetes Tools extension that would allow another extension to leverage and integrate with the existing commands an UI.  Very happy to work with the Skaffold community on that.

**Comment by bhack** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2018/06/08/preview-of-visual-studio-kubernetes-tools/

**Comment by bhack** [comment]
There are two vscode issues to follow about remote scenarios if you are interested:
https://github.com/Microsoft/vscode/issues/35671
https://github.com/Microsoft/vscode/issues/29194

**Comment by nkubala** [comment]
@bhack sorry there hasn't been a lot of clarification from the team here, and thanks for all the ideas and input! we're currently working on a number of features to make native IDE integration possible, including schema generation for syntax highlighting of skaffold resources and a full control API exposed over gRPC. you can track these individual features with the `ide` label on issues in the repo.

**Comment by bhack** [comment]
Cause you had an initial vscode plugin my feedbacks was almost oriented to vscode and all the features requested for remote interaction cause soon or later you need to interact with pod remote resources for debugging etc..

**Comment by nkubala** [comment]
with the release of [Cloud Code](https://cloud.google.com/code/), I think this issue can be closed! @bhack and others please go give it a try, it has awesome native skaffold integration which we're actively developing and improving on.

any cloud code specific issues can be opened on their issues repo, or improvements in skaffold that you think would benefit cloud code can of course be opened here.

**Comment by bhack** [comment]
@nkubala Do you know if it solve also https://github.com/GoogleContainerTools/skaffold/issues/1396?
Or is it still in the Skaffold perimeter?

**Comment by nkubala** [comment]
@bhack I don't think this issue addresses #1396 unfortunately. that will require a separate change to the way we trigger syncs and isn't really IDE specific. an API for controlling specific skaffold components is still on the table though, and we'll look into how we can leverage it to sync to non-skaffold targets.

**Comment by bhack** [comment]
Ok thanks. I will stay subscribed to #1396 for updates.
