### ISSUE TITLE
Tail log from remote kubernetes cluster

### ISSUE THREAD

**Issue by tuananh170489** [GoogleContainerTools/skaffold#3490]
Hi,
I have a remote k8s cluster as my deployment target. `Skaffold` is great tool for kubernetes development.
But now I can't tail log from pods in remote kubernetes cluster (this feature only work in local cluster).
So great when this feature is available

**Comment by corneliusweig** [comment]
@tuananh170489 Can you explain a little how you are using Skaffold? If you are running `skaffold run` or `skaffold deploy` it is expected that you don't see logs. However, with `skaffold dev` you should see the logs even from a remote cluster.

To inspect logs of an already deployed application, Skaffold is probably not the correct tool to use. But there several tools out there for exactly that purpose:
- https://gitlab.com/grzesuav/kubectl-mtail
- https://github.com/boz/kail
- https://github.com/wercker/stern
- ..and many more I guess.

**Comment by tuananh170489** [comment]
@corneliusweig thank for your response.
I saw this infomation in skaffold docs
`Skaffold has built-in support for tailing logs for containers deployed by Skaffold on your cluster to your local machine when running in either dev, debug or run mode`
And I has got the same issue that I can't tail logs pod at remote k8s cluster

**Comment by nkubala** [comment]
@tuananh you can use the `--tail=true` flag for `skaffold run` or `skaffold debug` to tail logs to your machine. this should work regardless of whether your cluster is local or remote.

**Comment by tuananh170489** [comment]
@nkubala I tried with `getting-started` example, but not streamed log to stdout, it's stopped at `Waiting for change` state.
I used `skaffold dev`

**Comment by tuananh170489** [comment]
Redirect to [#3648 issue](https://github.com/GoogleContainerTools/skaffold/issues/3648)
