### ISSUE TITLE
[Deploy] Add Tanka Deployer

### ISSUE THREAD

**Issue by GeertJohan** [GoogleContainerTools/skaffold#3498]
Related to #10 

Tanka has been 'officially announced' by grafana.
https://grafana.com/blog/2020/01/09/introducing-tanka-our-way-of-deploying-to-kubernetes/

It is an interesting alternative to helm and seems to fit as possible deploy option for Skaffold.

**Comment by tejal29** [comment]
@GeertJohan Thanks for raising the issue. We currently donot have the bandwidth to support a new deployer.

The team is looking into #2277 and maybe that could be a way to supporting new deployers. If the demands increases, we can think of supporting Tanka natively in skaffold.

**Comment by sh0rez** [comment]
Hey there! I'm a maintainer of Grafana Tanka and was pointed here by some interested users. 

Tanka includes the `tk show` command, which renders Kubernetes YAML resources, all other tasks (applying, deleting, etc.) is delegated to `kubectl`. So I guess it could be quite straightforward to integrate both projects, as a lot of the current `kubectl` deployer could be re-used.

I'd offer some help on this, if implementing Tanka as a deployer is desired for Skaffold. 

WDYT @tejal29?

**Comment by nkubala** [comment]
hey @sh0rez, thanks for following up! tanka is definitely an interesting player in the k8s field right now, but I don't think we're looking to introduce any more *native* deploy strategies in skaffold right now. that said, we're definitely interested in making progress on allowing custom scripts as a deployer to give users more flexibility, which would open a path for using tanka in skaffold.

i'll close this issue for now, but keep your eyes peeled for custom deployers in skaffold!
