### ISSUE TITLE
Subcommands for build and deploy implementations

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#35]
Exposing the build and deploy steps as single runnable commands
```
$ skaffold build local
$ skaffold deploy helm --chart-path
``` 

We could autogenerate most, if not all, of the command by iterating over `BuildType` and `DeployType` and then generating flags based on the parameters on the subtypes like `LocalBuild`.  Each command would output a go-template `BuildResult` or `DeployResult`.

**Comment by dlorenc** [comment]
Thanks, added this one to our team project to prioritize it. Feel free to take it if you want to give it a try, though :)

**Comment by jonjohnsonjr** [comment]
Build command was added in https://github.com/GoogleContainerTools/skaffold/pull/476
