### ISSUE TITLE
No support for openshift deployment

### ISSUE THREAD

**Issue by deepejai** [GoogleContainerTools/skaffold#353]
In the current version, I am not able to deploy to openshift environment using skaffold. Can you provide support for same?

**Comment by dgageot** [comment]
Hi @deepejai, thanks for the feedback! Can you provide us more details on things you're trying to achieve and error messages you might see?

**Comment by deepejai** [comment]
Hi @dgageot I am using Openshift environment to host my application, To deploy my application, I am using **oc create/apply -f <yaml file name>** so When I tried deploying my app using default configuration, It was failing at deployed step, As It was using kubectl in backend, so I modified my skaffold.yaml file to use oc at place of kubectl, so It is throwing error as unknown deployer as It supports HelmDeploy and KubectlDeploy

**Comment by r2d4** [comment]
I think we'd happily accept an openshift deployer for skaffold. It should be pretty straightforward to implement and can reuse a lot of the machinery used for the kubectl deployer. 

Additionally, we can most likely add a lot of the single node optimizations that we added for minikube and docker for desktop in skaffold for minishift. cc @gbraad @praveenkumar

**Comment by jstrachan** [comment]
@deepejai though you can use `kubectl apply` on OpenShift too you know ;) as of recent versions (I think 3.8?) OpenShift's custom resources like `DeploymentConfig` and `Route` use standard kubernetes API groups so can be applied via `kubectl` too

**Comment by dgageot** [comment]
I'm going to assume the `kubectl` deploy plugin does know how to talk to OpenShift. Please feel free to reopen if that's not the case
