### ISSUE TITLE
skaffold build fails with Redhat CodeReady container's internal registry

### ISSUE THREAD

**Issue by sloppycoder** [GoogleContainerTools/skaffold#3530]
I'm trying to use skaffold with Redhat's CodeReady container, essentially a single node version of Openshift 4.2 on my laptop, but the pipeline fails. Apparently JIB successfully pushed the image to the internal registry, but then skaffold can't query the registry due to some permission problem.

The project is a spring boot based microservice built with JIB, here's [code repo](https://github.com/sloppycoder/sample-api-svc/tree/crc-problem).  The developer branch contains the version that was tested with microk8s and minikube.

By default, after installation CRC's internal registry to expose at ```default-route-openshift-image-registry.apps-crc.testing``` but no anonymous access is allowed. In order to gain access, I follow these steps,

```
oc login -u kubeadmin -p <somepasswrod>  https://api.crc.testing:6443
oc whoami -t
# the command will print out a token, then I'll put the token into my ~/.m2/settings.xml file.
 <server>
      <id>default-route-openshift-image-registry.apps-crc.testing</id>
      <username>kubeadmin</username>
      <password><token from oc whoami -t</password>
    </server>
```
If I run build manually  ``` mvn -P jib -Dpush.image.base=default-route-openshift-image-registry.apps-crc.testing/default ```, maven will build and push the image to internal registry correctly. But if I use skaffold, it fails right after maven build,

```
skaffold debug

..snip...
[INFO] Container entrypoint set to [java, -mx512m, -XX:+ExitOnOutOfMemoryError, -Djava.security.egd=file:/dev/./urandom, -cp, /app/resources:/app/classes:/app/libs/*, net.vino9.sample.ResourceServerApplication]
[INFO] 
[INFO] Built and pushed image as default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:44faa66, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:dev, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:1.0.0-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.015 s
[INFO] Finished at: 2020-01-19T16:18:36+08:00
[INFO] ------------------------------------------------------------------------
FATA[0005] exiting dev mode because first build failed: build failed: building [default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc]: build artifact: getting image: unsupported status code 503; body: <html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
```
It appears that skaffold try to verify if the image exists after the maven build but it failed, so what credentials does skaffold use to query the registry? And how do I supply the credentials to skaffold?

I don't have docker installed locally. I use minikube for build that requires docker. JIB does the build by itself and doesn't require docker.

### Information

- Skaffold version: 1.2.0
- Operating system: Ubuntu 18.04 LTS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc
    jib:
      args:
        - -DskipTests
        - -Pjib
  insecureRegistries: ["default-route-openshift-image-registry.apps-crc.testing"]

deploy:
  kustomize:
    path: "./k8s/overlays/crc"

```

**Comment by sloppycoder** [comment]
The internal registry can only be accessed by HTTPS but it has a self-signed certificate. I realized the line 
```
  insecureRegistries: ["default-route-openshift-image-registry.apps-crc.testing"]
```
caused skaffold to access registry with HTTP not HTTPS, and it got a 503.

I removed the insecureRegistries entry in skaffold, now got a different error message, 

```
 skaffold debug

...snip...
[INFO] Built and pushed image as default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:44faa66-dirty, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:dev, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:1.0.0-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.928 s
[INFO] Finished at: 2020-01-19T16:58:56+08:00
[INFO] ------------------------------------------------------------------------
FATA[0006] exiting dev mode because first build failed: build failed: building [default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc]: build artifact: getting image: Get https://default-route-openshift-image-registry.apps-crc.testing/v2/: x509: certificate signed by unknown authority 

```

Is there any way I can tell skaffold to not do TLS verify?

**Comment by sloppycoder** [comment]
One more update, I extracted the cert on the ingress controller and added to my linux ca-certificates, I managed to got pass the X.509 error, then I got a new error.

```
[INFO] Built and pushed image as default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:25dc986, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:dev, default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc:1.0.0-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.916 s
[INFO] Finished at: 2020-01-20T18:23:44+08:00
[INFO] ------------------------------------------------------------------------
FATA[0005] exiting dev mode because first build failed: build failed: building [default-route-openshift-image-registry.apps-crc.testing/default/sample-api-svc]: build artifact: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:default/sample-api-svc Type:repository]] 
```

**Comment by sloppycoder** [comment]
apparently the problem is skaffold using the outdated credential to authentication openshift's internal registry. the fix is to do a docker login before running the build.

```
oc login -u kubeadmin -p <blah> https://api.crc.testing:6443 
oc whoami -toc whoami -t | docker login -u kubeadmin --password-stdin  https://default-route-openshift-image-registry.apps-crc.testing
```

**Comment by sloppycoder** [comment]
Just want to add that despite getting pass the problem above I then ran into another problem with Openshift unable to pull the image, see #3269

I'm giving up on Openshift for now...

**Comment by tomgeorge** [comment]
I have gotten to about the point where you are.  I think the problem is that from inside the cluster, the default (external) route is unknown, and generally the images are resolved via the service URL `image-registry.openshift-image-regsitry.svc:5000`.  So it needs to push to one URL, and set the image reference to another internal URL.  I'm not sure if there is a way to do that in skaffold.

**Comment by chanseokoh** [comment]
@tomgeorge for that matter, maybe you can try `hostAliases` in Kubernetes to?

**Comment by chanseokoh** [comment]
@tomgeorge for that matter, maybe you can try [`hostAliases`](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) in Kubernetes?

**Comment by marzelwidmer** [comment]
Hello I run in the same issues .. I don't get it.. what is wrong..

`oc whoami -t oc whoami -t | docker login -u kubeadmin --password-stdin  https://default-route-openshift-image-registry.apps-crc.testing
Login Succeeded`

`skaffold build -p os4`

`[INFO] Using credentials from Docker config (/Users/morpheus/.docker/config.json) for default-route-openshift-image-registry.apps-crc.testing/demo/demo-service
[WARNING] Cannot verify server at https://default-route-openshift-image-registry.apps-crc.testing/v2/. Attempting again with no TLS verification.
[WARNING] Cannot verify server at https://default-route-openshift-image-registry.apps-crc.testing/openshift/token?service=default-route-openshift-image-registry.apps-crc.testing&scope=repository:demo/demo-service:pull,push. Attempting again with no TLS verification.
[INFO] Using base image with digest: sha256:eb6c663924b01abed363d76fb8982fe0814817c9e90e0dfdff8d4119d328006b
[INFO]
[INFO] Container entrypoint set to [java, -cp, @/app/jib-classpath-file, ch.keepcalm.demo.DemoApplicationServiceKt]
[INFO]
[INFO] Built and pushed image as default-route-openshift-image-registry.apps-crc.testing/demo/demo-service
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.650 s
[INFO] Finished at: 2021-11-17T18:38:00+01:00
[INFO] ------------------------------------------------------------------------
GET http://default-route-openshift-image-registry.apps-crc.testing/v2/: unexpected status code 503 Service Unavailable: <html>
  <head>`
  
  
  Skaffold Profile
  `
- name: os4
  build:
    artifacts:
      - image: default-route-openshift-image-registry.apps-crc.testing/demo/demo-service
        jib:
          args:
            - -Pjib,integration,contracts,documentation
            - -Dimage=default-route-openshift-image-registry.apps-crc.testing/demo/demo-service
    insecureRegistries: [ "default-route-openshift-image-registry.apps-crc.testing" ]

  deploy:
    kustomize:
      paths:
        - k8s/installs/0s4`
