### ISSUE TITLE
skaffold dev is not starting

### ISSUE THREAD

**Issue by zerdos** [GoogleContainerTools/skaffold#3532]
my expectation would be to have working example files

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by balopat** [comment]
Hi @zerdos, thanks for opening the bug. 
Can you describe a bit more details about how to reproduce the issue? 
Are you using minikube, or a remote cluster, what is the error that you see? 
Thanks!

**Comment by dgageot** [comment]
I'm going to close this issue because it got no response. We need at least the name of the example that's failing. It's also better with of log of what has happended.
