### ISSUE TITLE
add parallel local image pushing

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#3544]
similar to #1380 now when builds are done in parallel

**Comment by dgageot** [comment]
Hi @matti can you elaborate a little what you'd like to have?

**Comment by matti** [comment]
Currently skaffold can be set to build parallel, but images are still pushed sequentially.

in bash pseudo:

for image in a b c d; do
  docker push $image &
done

wait $(jobs -p)

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.
