### ISSUE TITLE
Implement a function or add a flag for IDEs to get a finalized image name with prepended default image repository without actually building and pushing

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#3546]
A user only sees the finalized image name (default image repository + converted image name from manifests) once deployment or build starts. IDEs could show the expected image name in the run configurations to make it easier to decide if that's what a user needs and understand errors better if it doesn't work.

We can use some flag to get an expected image (given default image repo), or use dry run of build to get it.

**Comment by tstromberg** [comment]
@dgageot - what did you have in mind as far as fixing this?

It initially sounded like a good use of a `--dry-run` flag, but I wonder if you had something more targeted in mind.

**Comment by dgageot** [comment]
Yes, —dry-run seems to be a good fit.
