### ISSUE TITLE
Skaffold init --analyze returns duplicate image name

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#3551]
### Expected behavior
"skaffold init --analyze" should dedup image names. Expected output below.

{"dockerfiles":["src\backend\Dockerfile","src\frontend\Dockerfile"],"images":["node-guestbook-backend","mongo","node-guestbook-frontend"]}

### Actual behavior
"skaffold init --analyze" returns the "mongo" name twice in the "images". Actual output below.

{"dockerfiles":["src\backend\Dockerfile","src\frontend\Dockerfile"],"images":["node-guestbook-backend","mongo","node-guestbook-frontend","mongo"]}

### Information
Skaffold version: v0.40.0-62-g8a2658464
Operating system: Windows
Contents of skaffold.yaml: No skaffold.yaml

### Steps to reproduce the behavior
Get the nodejs guestbook cloud code sample.
Delete the skaffold.yaml at the root
run "skaffold init --analyze"

This bug was [filed before](https://github.com/GoogleContainerTools/skaffold/issues/3128) and was fixed.

**Comment by balopat** [comment]
Hi @sujit-kamireddy, can you try with v1.2.0?

**Comment by balopat** [comment]
or is that v0.40.0-62-g8a2658464 built from master?

**Comment by balopat** [comment]
on the latest master I see 
```
 skaffold init --analyze | jq                                                                                              Tue Jan 21 21:44:22 2020
{
  "dockerfiles": [
    "src/backend/Dockerfile",
    "src/frontend/Dockerfile"
  ],
  "images": [
    "mongo",
    "nodejs-guestbook-backend",
    "nodejs-guestbook-frontend"
  ]
}
```

or with jib + buildpacks: 

```
skaffold init --analyze --XXenableJibInit --XXenableBuildpackInit | jq                                                    Tue Jan 21 21:44:17 2020
{
  "builders": [
    {
      "name": "Buildpacks",
      "payload": {
        "path": "package.json"
      }
    },
    {
      "name": "Docker",
      "payload": {
        "path": "src/backend/Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "src/backend/package.json"
      }
    },
    {
      "name": "Docker",
      "payload": {
        "path": "src/frontend/Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "src/frontend/package.json"
      }
    }
  ],
  "images": [
    {
      "name": "mongo",
      "foundMatch": false
    },
    {
      "name": "nodejs-guestbook-backend",
      "foundMatch": false
    },
    {
      "name": "nodejs-guestbook-frontend",
      "foundMatch": false
    }
  ]
}
```

**Comment by balopat** [comment]
based on what I can tell, you are using a very old build from October: https://github.com/GoogleContainerTools/skaffold/commit/8a2658464

**Comment by balopat** [comment]
Closing, verbally confirmed that this was an old version of skaffold.
