### ISSUE TITLE
Notify trigger does not detect changes until file is closed

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3566]
### Expected behavior
Earlier I created issue #3429.

Issue was closed with comment:
> we're using 'fsnotify' to handle the watching of file changes, none of this is actually handled by skaffold directly. I don't know that there's anything we can do to address this in skaffold, so you'll probably want to take this up on their repo. I'll close this issue for now.

So I created issue in `fsnotify` repository, and unfortunately only after that I decided to test `fsnotify` to be sure that this is an issue on their side.

As it turns out, `fsnotify` does not have an issue with detecting changes for files being opened, so now I'm sure that this is an issue on Skaffold side - probably `fsnotify` is not used properly somewhere in Skaffold code. Below are details of how I tested `fsnotify` and `skaffold`.
Also please see original issue #3429 

### Actual behavior
As previous closed issue says, Skaffold does not detect file changes when file is open.

### Information

- Skaffold version: master
- Operating system: MacOs Catalina
- Contents of skaffold.yaml: not relevant here, just any manual sync rule

### Steps to reproduce the behavior

To be sure that this is an issue on Skaffold side, let me start with example of using `fsnotify` without issues with open files.

Below is code that proves that `fsnotify` detects changes in open files.

1. Create go program that monitors file for changes using `fsnotify`.

```go
package main

import (
	"github.com/fsnotify/fsnotify"
	"log"
)

func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		log.Fatal(err)
	}
	defer watcher.Close()

	done := make(chan bool)
	go func() {
		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}
				log.Println("event:", event)
				if event.Op&fsnotify.Write == fsnotify.Write {
					log.Println("modified file:", event.Name)
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()

	err = watcher.Add("/tmp/fstest")
	if err != nil {
		log.Fatal(err)
	}
	<-done
}
```

2. Compile and run this program.

3. Open file being monitored using any programming language (I'll use Python interactive console for this example)

```python
f = open('tmp/fstest', 'a')
f.write('anything')
```

4. Check output of program that monitors file - no output.
5. Flush file:

```
f.flush() # Ensure that changes were actually written to disk, not buffered
```

6. Check output of program that monitors file - here's the output:

```
2020/01/23 14:57:38 event: "/tmp/fstest": WRITE
2020/01/23 14:57:38 modified file: /tmp/fstest
```

At this point we can be sure that `fsnotify` itself does not have issues with open files.
We can stop out monitor program.

7. Specify manual sync rule for the same in `skaffold.yaml` and run `skaffold dev`.

8. Repeat steps being done previously, or those specified in #3429.

9. Check skaffold output - no file changes detected, file is not synced to container.

**Comment by petr-buchin** [comment]
Hmm, I found that despite @nkubala said in #3429 that Skaffold uses https://github.com/fsnotify/fsnotify lib, Skaffold actually uses https://github.com/rjeczalik/notify lib, which seemed to be not suuported anymore (last commit in 2018).

Do you plan to move to `fsnotify` ?

**Comment by balopat** [comment]
Thanks for the detailed report @petr-buchin - I'd love to understand where this causes an issue! 
Having said that, if fsnotify works well, I would be open to switch. 
I'm sure we looked into that too, not sure why we didn't go with it and used instead rjeczalik/notify - @dgageot might be able to shed some light on that.

**Comment by petr-buchin** [comment]
@balopat below is my explanation of where this causes an issue for our company.

We use Skaffold for development environment in k8s. 
Basically we have the same environment for dev, qa, staging and prod environments.
We also use the same Dockerfiles for all environments.

We also have one legacy repository, which uses gulp to rebuild static assets at runtime when code changes (this applies only for dev mode). Developers want changes to be propagated to a running container.

Unfirtunately, `gulp.watch()` keeps files open. 
I've created few issues for `gulp` repo, but seems like `gulp` is not supported much anymore, or they don't think this is an issue with a serious priority.

In one of my previous issues to Skaffold repo one of contributors gave an advice to consider running `gulp dev` process inside container, but this is not an option for us, since we have the same images for all environments. We also have some other reasons to not do that.

However, without being able to propagate static assets to container after them being rebuilt, we cannot fully migrate our dev environment from `docker-compose` to `k8s` and `Skaffold`.

Anyway, thanks for the answer, I'm looking forward to have this bugfix.
Also, with some help about where to start (little explanation of Skaffold architecture) I would be happy to implement migration to `fsnotify` by myself.

**Comment by dgageot** [comment]
Hi @petr-buchin we have no plan on migrating to `fsnotify` mainly because it doesn't support `FSEvents` on macos and also probably doesn't support recursive watch (not sure about that last one).
I'll take a look at what we can do with https://github.com/rjeczalik/notify.
In the meantime, have you tried running skaffold with `--trigger=polling`?

**Comment by nkubala** [comment]
closing this one due to inactivity.
