### ISSUE TITLE
Skaffold run '--render-only' support to write output to a file.

### ISSUE THREAD

**Issue by kissmikijr** [GoogleContainerTools/skaffold#3582]
### Expected behavior
Currently skaffold run has a flag '--render-only'. This prints the output manifests to the stdout. I'd like to be able to write the output to a file like with skaffold render --output.

### Actual behavior
Currently not supported.
### Information

- Skaffold version: version latest
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold run --render-only`
3. ...

**Comment by tstromberg** [comment]
This can already be done using: `skaffold run --render-only > outfile`

If someone would like to contribute this as a flag, PR's welcome.

**Comment by geritol** [comment]
The problem with that solution is that other stuff eg. `There is a new version (x.x.x) of Skaffold available.` will get written to the outfile.

**Comment by MarlonGamez** [comment]
Closing this since it was resolved with #3586 :)
