### ISSUE TITLE
Skaffold with kaniko: docs are not in sync

### ISSUE THREAD

**Issue by saschahofmann** [GoogleContainerTools/skaffold#3590]
The kaniko docs linked on the main readme are stating `Rename the key to kaniko-secret.json`. However, [your example](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/kaniko) explicitly states  `rename the file to kaniko-secret (do not append .json to the filename)`. I struggled with that for a while because following the kaniko docs does not actually work with skaffold.  

Happy to make a PR to the docs.

**Comment by dgageot** [comment]
@saschahofmann That would be awesome if you could fix the doc!
