### ISSUE TITLE
Can `skaffold fix` take a flag to specify which schema version to transform to?

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#3613]
We have a few `skaffold.yaml` files at version `skaffold/v1beta15`. We want to transform them to `skaffold/v1`, but there is currently no way to do this with `skaffold fix` since it will currently transform the files to `skaffold/v2alpha2` (latest).

Perhaps something along the lines of:
`skaffold fix --filename=skaffold.yaml --version=skaffold/v1`

**Comment by tejal29** [comment]
@matthewmichihara This is possbile by adding a flag [here](https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/fix.go#L39) and then adding a new function `upgradeToVersion` similar to `upgradeToLatest` like [here](https://github.com/GoogleContainerTools/skaffold/blob/dd9fbdbdb559db67c7dc66bf33b781d22b5bae46/pkg/skaffold/schema/versions.go#L110) 

````
func upgradeToVersion(vc util.VersionedConfig, apiVersion string)
   (util.VersionedConfig, error){
}
```

However before that, i am curious, you are on latest skaffold , but you want the samples to be updated to `skaffold/v1`.  Is this just for one time ?

If yes, you could do that by using skaffold version `v1.0.0`.

**Comment by matthewmichihara** [comment]
Good to know. Context here is that for Skaffold files in https://github.com/GoogleCloudPlatform/cloud-code-samples or in snippets provided by the IDE, we don't always want to upgrade to the latest alpha version for stability reasons, but also want to be able to use the latest Skaffold binary. I can see this being more than a one time thing.

I think there is some debate around whether we should always just upgrade to latest vs pinning to a particular version (`skaffold/v1`), but for the time being, the IDEs want to stay at `skaffold/v1`.
