### ISSUE TITLE
Release process broken. 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3617]
### Expected behavior
On a release PR, like #3616 Travis test should pass.

### Actual behavior
On release PR, `./hack/check-samples.sh` script failed

e.g:  https://travis-ci.com/GoogleContainerTools/skaffold/jobs/282115609

This is due to recent PR https://github.com/GoogleContainerTools/skaffold/pull/3539

### Workaround
Change release process to 
1. Create release branch say release-1.3
2. Create a PR and get it approved. Ignore the travis failure. 
3. Create release TAG and push to upstream on the release branch
    - wait for the triggered built to complete.
4. Rerun the Travis job.  
5. Finally merge the PR

**Comment by dgageot** [comment]
@tejal29 I believe `./hack/check-samples.sh` does its job of checking samples versus the latest released version. However, `go run ./hack/versions/cmd/latest_released/version.go` should take into account the version that is in the process of being pushed and released.

**Comment by tejal29** [comment]
@dgageot yes we discussed about changing the `version.go` to look for latest version in the `config.go` like your PR does.
