### ISSUE TITLE
skaffold init - loads all files to memory

### ISSUE THREAD

**Issue by bukowa** [GoogleContainerTools/skaffold#3619]
### Expected behavior
Big file is not loaded into memory.

### Actual behavior
Big file is loaded into memory.

### Information
Given a folder with 12GB file, `skaffold init` hangs loading that file into memory.

- Skaffold version: v1.2.0

### Steps to reproduce the behavior

1. Skaffold init.
2. Skaffold loads big file into memory.

**Comment by balopat** [comment]
Thanks for opening this! I think that's a great idea to prefilter parsing logic to a certain file limit.

**Comment by balopat** [comment]
This is now going to be fixed in #3717.
