### ISSUE TITLE
skaffold docker image doesn't have skaffold binary

### ISSUE THREAD

**Issue by kchygoe** [GoogleContainerTools/skaffold#3622]
### Expected behavior
```
docker run gcr.io/k8s-skaffold/skaffold  skaffold
```
should correctly run.

### Actual behavior

```
docker run -ti --rm gcr.io/k8s-skaffold/skaffold:v1.3.0 skaffold
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"skaffold\": executable file not found in $PATH": unknown.
```

### Information

- Skaffold version: v1.3.0
- Operating system: Linux(ubuntu16.04), circle-ci
- Contents of skaffold.yaml:

```yaml
N/A
```

### Steps to reproduce the behavior

1. `docker run -ti --rm gcr.io/k8s-skaffold/skaffold:v1.3.0 skaffold`

**Comment by michalkosmowski** [comment]
I was just about to submit this one 👍
Not sure if related but the image virtual size increased from 313.3 MB (v1.2.0) to 839.2 MB (v.1.3.0)

**Comment by tvvignesh** [comment]
CC @tejal29 @balopat 

Hi. Facing the same issue on my end as well. The CI pipeline fails with the error `skaffold: command not found` Even tried upgrading the yaml file with `skaffold fix` just to make sure things are consistent as per the new verison. 

![Screenshot from 2020-01-31 16-06-14](https://user-images.githubusercontent.com/1165845/73532892-a03be980-4443-11ea-9be6-a7d10d2530bf.png)

**Comment by balopat** [comment]
We are looking at this ASAP.

**Comment by balopat** [comment]
In the meantime please rollback to `v1.2.0`.

**Comment by tejal29** [comment]
@kchygoe @michaelbeaumont and @tvvignesh v1.3.1 release is coming! soon

**Comment by tejal29** [comment]
This now fixed. 
I verified the `latest` and `v1.3.1` skaffold image and both have the `skaffold` binary.

```
tejaldesai@@workspace$ docker run -ti --rm gcr.io/k8s-skaffold/skaffold skaffold version
v1.3.1
tejaldesai@@workspace$ docker run -ti --rm gcr.io/k8s-skaffold/skaffold:v1.3.1 skaffold version
Unable to find image 'gcr.io/k8s-skaffold/skaffold:v1.3.1' locally
v1.3.1: Pulling from k8s-skaffold/skaffold
Digest: sha256:04d76159c1d24bdb9f16dc8df2c066fe195b553ee4e1ed8f4d335e38453fc68b
Status: Downloaded newer image for gcr.io/k8s-skaffold/skaffold:v1.3.1
v1.3.1
tejaldesai@@workspace$ 

```

**Comment by tvvignesh** [comment]
@tejal29 @balopat That was fast! You guys are doing an awesome job with Skaffold. Have made my job with CI very easy. Thanks

**Comment by kchygoe** [comment]
Thank you for the quick work! It works fine.
