### ISSUE TITLE
Documentation is wrong for portForward

### ISSUE THREAD

**Issue by ktarplee** [GoogleContainerTools/skaffold#3623]
### Expected behavior
[online docs](https://skaffold.dev/docs/references/yaml/) should show that portForward contains an array (just like "profile").

### Actual behavior
Instead the docs show that portForward is a dict.  It is missing the prefix "-" to show it is an array.

### Information

- Skaffold version: 1.2.0

**Comment by tejal29** [comment]
Decreasing the priority, since the team is busy with other p1 issues.

**Comment by nkubala** [comment]
@ktarplee would you be interested in submitting some update docs? it should be a pretty small change :)

**Comment by heatwole** [comment]
I was taking a look at this and portForward seemed to be defined correctly as an array in the schema docs. I think there is a bug during rendering, but I couldn't tell where.
