### ISSUE TITLE
Make duct-tape repo configurable for cluster without gcr.io access

### ISSUE THREAD

**Issue by sbueringer** [GoogleContainerTools/skaffold#3630]
Hi,

we're running our clusters without direct internet access. Therefore we cannot just use `gcr.io/gcp-dev-tools/duct-tape/*` duct-tape images. It would be nice if the repository would be configurable via skaffold.yaml.

### Expected behavior

duct-tape image repository should be configurable

### Actual behavior

I couldn't find a configuration option for this. And looks like it's hard-coded here: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/debug/transform.go#L209

### Information

- Skaffold version: 1.3.1
- Operating system: Ubuntu 18.04

### This would enable the following use cases

1. upstream images can be synced to some on-premise registry and skaffold could use them
2. duct-tape images can be customized for special use cases (I don't have a need for this, but maybe somebody else)

**Comment by dgageot** [comment]
cc @briandealwis

**Comment by briandealwis** [comment]
Duplicate of #2679

I'll bump the priority of #2679
