### ISSUE TITLE
`skaffold init --analyze` is not returning full builder list

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#3654]
### Expected behavior
When running `skaffold init --analyze`, I expected to receive all of the possible builders (jib, docker) that could be used, ideally in some sorted order.

### Actual behavior
Only Jib builders were returned, even though this project has Dockerfiles in the `frontend` and `backend` directories.

It looks like when a builder is detected, the other possible builders are ignored: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/initializer/builders.go#L105

### Information
- Skaffold version: 1.3.1
- Operating system: macOS Catalina

### Steps to reproduce the behavior
1. Clone https://github.com/GoogleCloudPlatform/cloud-code-samples.
2. Navigate to `java/java-guestbook`.
3. Run:
```
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 SKAFFOLD_XXENABLEJIBINIT=1 skaffold init --analyze | jq
{
  "builders": [
    {
      "name": "Jib Maven Plugin",
      "payload": {
        "path": "pom.xml"
      }
    },
    {
      "name": "Jib Maven Plugin",
      "payload": {
        "path": "pom.xml"
      }
    }
  ],
  "images": [
    {
      "name": "java-guestbook-backend",
      "foundMatch": false
    },
    {
      "name": "java-guestbook-frontend",
      "foundMatch": false
    },
    {
      "name": "mongo",
      "foundMatch": false
    }
  ]
}
```

**Comment by TadCordle** [comment]
Things might have changed since I last worked on this, but this might be because of an optimization to avoid redundant calls out to Jib. I think when init sees a pom.xml with Jib configured, it assumes there won't be Dockerfiles within the subdirectories (because it expects the project to be built with Jib) and doesn't search any further. But, I'm not sure if that's a good idea.

**Comment by balopat** [comment]
I think so @TadCordle - we'll have to narrow the logic for that filtering to jib modules - i.e. if I noticed a jib module we shouldn't look for other jib builders deeper - however there could be other builders in subdirs of java projects.
