### ISSUE TITLE
FR: Can `skaffold init --force` automatically select a builder if there are multiple builders and a single image detected?

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#3661]
skaffold version: 1.3.1

**Update:**
For example, I would like the following scenario to succeed in https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/golang/go-hello-world:

```
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 skaffold init --analyze | jq
{
  "builders": [
    {
      "name": "Docker",
      "payload": {
        "path": "Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "go.mod",
        "builder": "heroku/buildpacks"
      }
    }
  ],
  "images": [
    {
      "name": "go-hello-world",
      "foundMatch": false
    }
  ]
}
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 skaffold init --force
FATA[0000] unable to automatically resolve builder/image pairs; run `skaffold init` without `--force` to manually resolve ambiguities
```

In the event that there are multiple candidate builders and a single image detected, is it feasible for Skaffold to choose them for me according to some heuristic when `--force` is used? 

We could pick the highest precedence builder according to this list from https://github.com/GoogleContainerTools/skaffold/issues/3661#issuecomment-592732189:
1. Jib
2. Bazel
3. Dockerfile
4. Buildpack

**Original issue, disregard:**
For example, I would like the following scenario to succeed in https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/golang/go-guestbook:

```
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 SKAFFOLD_XXENABLEJIBINIT=1 skaffold init --analyze | jq
{
  "builders": [
    {
      "name": "Docker",
      "payload": {
        "path": "src/backend/Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "src/backend/go.mod",
        "builder": "heroku/buildpacks"
      }
    },
    {
      "name": "Docker",
      "payload": {
        "path": "src/frontend/Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "src/frontend/go.mod",
        "builder": "heroku/buildpacks"
      }
    }
  ],
  "images": [
    {
      "name": "go-guestbook-backend",
      "foundMatch": false
    },
    {
      "name": "go-guestbook-frontend",
      "foundMatch": false
    },
    {
      "name": "mongo",
      "foundMatch": false
    }
  ]
}
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 SKAFFOLD_XXENABLEJIBINIT=1 skaffold init --force
FATA[0000] unable to automatically resolve builder/image pairs; run `skaffold init` without `--force` to manually resolve ambiguities
```

In the event that there are multiple candidate builders per image, is it feasible for Skaffold to choose them for me according to some heuristic when `--force` is used? In this example, `Docker` and `Buildpacks` builders were present. Skaffold could potentially choose `Docker` builders for me without prompting.

**Comment by nkubala** [comment]
the main issue here is that even if we weren't using buildpacks, there would still be two Docker builders and two images, and it's hard to be totally sure which one builds which. it's possible we could try and make a "best guess" using string matching or some other similar heuristic - to the human eye, it's obvious that `src/backend/Dockerfile` builds `go-guestbook-backend`, and `src/frontend/Dockerfile` builds `go-guestbook-frontend` - but in practice we wouldn't always get it right and could end up writing out incorrect skaffold.yamls. I'd be willing to see a design proposal for this though

**Comment by dgageot** [comment]
@matthewmichihara wdyt of @nkubala's comment. We should give priority to Dockerfiles over anything else but we can't match the image names to the artifact

**Comment by dgageot** [comment]
I've thought it some more and I think the only thing we can do and that we should do no matter wether --force is used or not is ignore all the builders in a given folder if there's a Dockerfile there. If someone wrote a Dockerfile, it's to build with docker build.

**Comment by ivanporty** [comment]
We've been mulling this for quite a while, and since Jib support appeared, had to deal with reduced functionality since IntelliJ doesn't ask user to select a builder - it tries to do this automatically. I completely agree with @dgageot, and always rooted for is selecting a `Dockerfile` by default - it has to be present for a reason in the project.

However, profiles exist in Skaffold for a good reason, and it seems just a perfect place to add additional builders as profiles - it seems feasible too?

**Comment by balopat** [comment]
Strawman proposal for the conflicts: 

**Conflict** occurs when two or more builders are found under the same directory using the default settings. 

E.g.: src/frontend/Dockerfile, src/frontend/pom.xml with Jib info in it and src/frontend.pom.xml with Buildpacks compatibility 

**Conflict resolution precedence**: 

1. Jib 
2. Dockerfile 
3. Buildpack 

The highest precedence builder will be picked. In case of our example, the Jib builder would be picked.

**Comment by matthewmichihara** [comment]
I agree that buildpacks should be last in precedence order, but between Jib/Bazel/Dockerfile, I don't have a strong preference for what the order should be. Is there a strong reason to choose one over the other? @balopat's strawman proposal sgtm.

**Comment by balopat** [comment]
One strong reason: 

I'd be more okay with choosing jib over Dockerfile - as it is more deterministic in terms of the settings to build a jib project. Dockerfile's can be found easily but the rest of the settings (context, target, etc.) are hard to determine automatically, while a well configured jib plugin can contain all that's needed.

Between Jib / Bazel it is hard to say what's best, but for now Bazel builders are not recognized.

**Comment by matthewmichihara** [comment]
I think this FR covers 2 scenarios:
1. If there are multiple builders and *multiple* images detected, can `skaffold init --force` automatically choose for me?
2. If there are multiple builders and a *single* image detected, can `skaffold init --force` automatically choose for me?

I think we've agreed that (2) is doable with @balopat's strawman proposal in https://github.com/GoogleContainerTools/skaffold/issues/3661#issuecomment-592732189, but not (1) understandably.

I'll update the issue summary with this.

**Comment by tejal29** [comment]
@matthewmichihara hey going through skaffold triage, can you please explain what work is remaining as part of this issue?

**Comment by matthewmichihara** [comment]
hey @tejal29, I don't think has been started on yet -- just verified that the same behavior I saw earlier exists:

```
$ skaffold version
v1.14.0
$ pwd
/Users/michihara/Code/cloud-code-samples/golang/go-hello-world
$ ls
Dockerfile           cmd                  go.sum               kubernetes-manifests
README.md            go.mod               img                  skaffold.yaml
$ rm skaffold.yaml
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 skaffold init --analyze | jq
{
  "builders": [
    {
      "name": "Docker",
      "payload": {
        "path": "Dockerfile"
      }
    },
    {
      "name": "Buildpacks",
      "payload": {
        "path": "go.mod",
        "builder": "gcr.io/buildpacks/builder:v1"
      }
    }
  ],
  "images": [
    {
      "name": "go-hello-world",
      "foundMatch": false
    }
  ]
}
$ SKAFFOLD_XXENABLEBUILDPACKSINIT=1 SKAFFOLD_XXENABLEBUILDPACKINIT=1 skaffold init --force
unable to automatically resolve builder/image pairs; run `skaffold init` without `--force` to manually resolve ambiguities
```

I wish Skaffold would just generate a configuration file with the Docker builder here.
