### ISSUE TITLE
skaffold push

### ISSUE THREAD

**Issue by emichaf** [GoogleContainerTools/skaffold#3664]
I would like to only build and push a Docker Image, and later deploy!

How can this be done, can see build, but not push option?

**Comment by balopat** [comment]
Hi @emichaf, `skaffold build` should build & push! 
Push behavior depends on your builder setup. If you don't build locally (googlecloudbuild, or on cluster), skaffold always pushes. If you build locally - `build.local.push=true` has to be set. This is automated when the kubecontext is not local (not minikube/docker-for-desktop/kind/etc.)

**Comment by emichaf** [comment]
Ok, In my CI pipeline I would like to build the image and then run some tests and when tests passed perform the push.

**Comment by nkubala** [comment]
@emichaf skaffold has a test phase that runs between building and deploying. pushing is tied to building in skaffold though, since several of our build strategies build directly to a registry.

**Comment by dgageot** [comment]
I’m going to close this issue because all the features are there.
