### ISSUE TITLE
enable skaffold to work on minikube profiles

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3668]
Currently, if `kube-context` is pointing to a minikube profile that is not `minikube`, bunch of things will fail: 
 - we don't detect that this is a minikube profile 
 - even if we would, we'd call `minikube docker-env` without profile 

My recommendation would be:
- decide if the api-server URL is local or not (192.168.0.0/16, 172.0.0.0/24)
- if not local, assume remote  
- if local - check if minikube exists as a binary in the path, if yes: `minikube profile list` and see if any of them match the IP address - if yes, use the profile name for that profile throughout the code

**Comment by nkubala** [comment]
surprised we didn't run into this one sooner. where did you get `172.0.0.0` from (just curious)? isn't is possible that someone could have proxied their apiserver locally, and we would fail by assuming it's local when it actually isn't?

in general though this is an improvement on what we're doing now.

**Comment by balopat** [comment]
> surprised we didn't run into this one sooner. 

I know...maybe I'm missing something?

**Comment by briandealwis** [comment]
Would it make sense to look at the corresponding machines interfaces?

**Comment by balopat** [comment]
> Would it make sense to look at the corresponding machines interfaces?

`minikube profile list` should be good enough to list the necessary details. What do you mean by machine interfaces?

**Comment by balopat** [comment]
https://github.com/kubernetes/minikube/issues/6715 is also going to be useful going forward.

**Comment by briandealwis** [comment]
I meant host's network interfaces, thinking that we could correlate the API server to the available network interfaces to identify whether it's local on the machine.

`minikube profile list` sounds much easier.

**Comment by balopat** [comment]
bumping down to p1 since `--minikube-profile` flag was released...

**Comment by tstromberg** [comment]
If it helps, `minikube profile list -o json` is there.

One additional hint I've seen used in the past is looking for `minikube` in the certificate authority path.
