### ISSUE TITLE
unable to execute kubectl apply kube-inject parameter

### ISSUE THREAD

**Issue by Gsantomaggio** [GoogleContainerTools/skaffold#3672]
I have a question about kube-inject:
let's suppose I have:
```
kubectl:
    manifests:
    - ../ms_books/k8s-deploy.yaml
```
Now I'd need to execute something like:
```
 kubectl apply -f <(istioctl kube-inject -f ../ms_books/k8s-deploy.yaml)
```

I tried to pass parameters to the `apply`  without success.

Is there a way to do that?

```
version v1.3.1
os: openSuse Leap 15.1
```

( Sorry for the issue, but I couldn't find a way to solve the problem)

**Comment by Gsantomaggio** [comment]
Per discussion on the [group](https://groups.google.com/forum/#!topic/skaffold-users/26K2llVkcn4)

**Comment by balopat** [comment]
Hi @Gsantomaggio, 

For `skaffold dev` it is not possible today - I believe #1441 or https://github.com/GoogleContainerTools/skaffold/issues/2277 would help you with this. 

If you are using skaffold in CI/CD pipeline - you could use `skaffold render` and kube-inject into the result of it!

**Comment by Gsantomaggio** [comment]
Thank you @balopat for the suggestions.

I decided to create a dedicated namespace and enable the `namespace auto-injection` in istio during the developing, so I can use `skaffold dev` 

It basically solves the issue, so I can close the issue
