### ISSUE TITLE
Is it possible to run a custom script before a kaniko image build?

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3681]
Is it possible to run a custom script before a kaniko image build?

I have need to generate a Dockerfile right before kaniko runs

**Comment by bitsofinfo** [comment]
https://kubernetes.slack.com/archives/CABQMSZA6/p1581538776128400

**Comment by dgageot** [comment]
Closing as a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/1441
