### ISSUE TITLE
Skaffold init --analyze output not ideal for parsing by clients

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#3686]
Tested with Skaffold version 1.2. I assume this behavior is still carried forward.

`skaffold init --analyze --XenableJibInit` returns the following output:

```
{"builders":[{"name":"Jib Maven Plugin","payload":{"path":"pom.xml"}}],"images":[{"name":"java-hello-world","foundMatch":false}]}There is a new version (1.3.1) of Skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
```

Notice the new version / upgrade message after the JSON. This makes it inconvenient for clients trying to parse the json output of this command. Is there a way to suppress this that I may have missed?

**Comment by etanshaul** [comment]
Update:

If I omit the `--XXenableJibInit` flag, then the version update string is no long printed.

**Comment by etanshaul** [comment]
we are working around this for now by setting the SKAFFOLD_UPDATE_CHECK env var:
https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/1303

**Comment by tejal29** [comment]
@balopat Are you going to work on this soon? or else, can you decrease the priority?

**Comment by balopat** [comment]
I will work on this today!
