### ISSUE TITLE
Development requirements, missing `jq` tool?

### ISSUE THREAD

**Issue by dahovey** [GoogleContainerTools/skaffold#3694]
### Expected behavior

`DEVELOPMENT.md` should install all dependencies required.

### Actual behavior

`make build` works, but `make test` ends unexpectedly with error:

![image](https://user-images.githubusercontent.com/22330242/74680223-2747cc00-517d-11ea-9c1e-e9d31ceaed93.png)

Required installation using `brew install jq` based on (https://stedolan.github.io/jq/download/)[https://stedolan.github.io/jq/download/]

### Information

- Skaffold version: 1.0.0
- Operating system: Mac OS Catalina

**Comment by tstromberg** [comment]
+1 I just ran into this myself. 

@nkubala - would you rather a PR that updates `gotest.sh` to not require `jq`, or one that adds the requirement to `DEVELOPMENT.md`?
