### ISSUE TITLE
skaffold.yaml reference page

### ISSUE THREAD

**Issue by odino** [GoogleContainerTools/skaffold#3701]
Hola folks,

sorry to bother with such a trivial issue, but I think we've removed the content of the `skaffold.yaml` reference from the docs:

https://skaffold.dev/docs/references/yaml/

![image](https://user-images.githubusercontent.com/328420/74813098-272b0600-530e-11ea-99ee-a91f6f3ff9f4.png)

Is this a mistake? There seems to be no page where we can have a look at the entire yaml file (with an exhaustive list of options) anymore.

**Comment by dgageot** [comment]
Hi @odino Sorry that you had an issue with the documentation. It works well for me. Can you give us more details about your browser and maybe look at what printed to the console?

**Comment by ynouri** [comment]
On our side we can see the full YAML reference but only for the latest version `apiVersion: skaffold/v2alpha3`

Is there a way to access the YAML reference for the stable v1?

Thanks!

**Comment by odino** [comment]
Hi folks -- my bad, I didn't realize the reference was getting loaded asynchronously. After a few hours it started appearing again, I assume there was something wrong on my end :)
