### ISSUE TITLE
Skaffold yaml file validation scheme is not correct

### ISSUE THREAD

**Issue by zd-dalibor** [GoogleContainerTools/skaffold#3705]
The part of skaffold yaml file validation scheme that defines JSONPatch object validation is not correct.

The "value" property of JSONPatch can be also "string" value but in your scheme It can be only "object". So I got this false validation message:

![image](https://user-images.githubusercontent.com/226822/74917739-4d14e100-53c8-11ea-8463-7257e403c75b.png)

**Comment by dgageot** [comment]
Duplicate of https://github.com/GoogleContainerTools/skaffold/issues/3932
