### ISSUE TITLE
Use container-runtime info from minikube node for image loading strategy

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3711]
`kubectl describe node` contains the Container Runtime Version: 
```
  Container Runtime Version:  docker://18.9.7
```

We should use this info to determine whether to build a docker image directly against the internal docker daemon determined by docker-env or by using `minikube cache add` (similar to `kind load`)

**Comment by dgageot** [comment]
@balopat @tstromberg could you tell us how `minikube cache add` would be required or better?

**Comment by tejal29** [comment]
dupe of #5773
