### ISSUE TITLE
Port-forwarding does not work when SKAFFOLD_LABEL is set

### ISSUE THREAD

**Issue by pehlert** [GoogleContainerTools/skaffold#3734]
### Expected behavior
Even with the SKAFFOLD_LABEL environment variable set, `skaffold dev --port-forward` should forward service pods to localhost.

### Actual behavior
As soon as the SKAFFOLD_LABEL environment variable is set, port forwards are not set up anymore

### Information

- Skaffold version: 1.4.0
- Operating system: OS X Catalina

I have SKAFFOLD_LABEL set globally to workaround this issue: https://github.com/GoogleContainerTools/skaffold/issues/3361

However as soon as it is set, port-forwards stop working with `skaffold dev`.
Of course I can set SKAFFOLD_LABEL for `skaffold run` commands only, however this does not look like expected behaviour.

**Comment by dgageot** [comment]
The deployment is also broken by such env var.

**Comment by pehlert** [comment]
Thanks everyone!
