### ISSUE TITLE
Add yaml list to output of skaffold init --analyze --XXenableJibInit

### ISSUE THREAD

**Issue by peterlin741** [GoogleContainerTools/skaffold#3736]
Currently, the Cloud Code IntelliJ plugin team is dependent on the results of **skaffold init --analyze --XXenableJibInit**.

We would like a list of valid skaffold.yaml files returned as a separate field. The intelliJ team would like recognize valid skaffold.yaml files in the main directory, and if additional files are found in subdirectories, it would be great but not necessary to include them.

The proposed format is an additional field called **yamls**, with a list of objects including the **filename** (skaffold.yaml is the default but may change with the project) and the subdirectory location **path** (empty if in the project’s root directory). The field names can be changed if needed.

Because the IntelliJ team is only calling **skaffold init --analyze** with the flag **--XXenableJibInit**, the Skaffold team would only need to change the output of the command with the flag for now, since the addition of the flag changed the entire structure of the output, as referenced in http://go/buildpacks-skaffold-init.

Example proposed output included below:

```
  “yamls”: [
    {
      “filename”: “skaffold.yaml”,
      “path”: “”
    },
    {
      “filename”: “skaffold.yaml”,
      “path”: “src.main.resources”
    }
  ]
```

Full suggested Output of : skaffold init --analyze --XXenableJibInit

```
{
  "builders": [
    {
      "name": "Docker",
      "payload": {
        "path": "Dockerfile"
      }
    },
    {
      "name": "Jib Maven Plugin",
      "payload": {
        "path": "pom.xml"
      }
    }
  ],
  "images": [
    {
      "name": "java-hello-world",
      "foundMatch": false
    }
  ],
  “yamls”: [
    {
      “filename”: “skaffold.yaml”,
      “path”: “”
    },
    {
      “filename”: “skaffold.yaml”,
      “path”: “src.main.resources”
    }
  ]
}
```

**Comment by balopat** [comment]
I think this sounds fine, I can put this together easily soon.  Three nits: 

1. I would rename `yamls` to `skaffold-configurations`. 
2. I would provide a list of paths and that's it, not sure why we need a filename / path separation.
3. The path separator would be standardized "/" even on Windows, relative to the path of execution

Does that sound okay?

**Comment by sujit-kamireddy** [comment]
Can't you use the find-configs api to get the list of valid skaffold.yaml files in the directory?

skaffold find-configs -d <dir>
https://github.com/GoogleContainerTools/skaffold/issues/2229

**Comment by peterlin741** [comment]
> I think this sounds fine, I can put this together easily soon. Three nits:
> 
> 1. I would rename `yamls` to `skaffold-configurations`.
> 2. I would provide a list of paths and that's it, not sure why we need a filename / path separation.
> 3. The path separator would be standardized "/" even on Windows, relative to the path of execution
> 
> Does that sound okay?

Thanks, all of that sounds great. 

Looking at the `skaffold find-configs -d {directory}` command that Sujit mentioned, it looks like the feature we want is already there. I'll leave it up to the Skaffold team to decide if they want to duplicate the feature (since it does make sense for `init` to generate that output). However, it's not necessary since the IntelliJ team can already use the `find-configs` command. Please let me know what you decide, Thanks!

**Comment by tstromberg** [comment]
I'm going to leave this up to the `skaffold find-configs` feature, as there hasn't been a clearly defined need otherwise.
