### ISSUE TITLE
Using pre-existing deployments

### ISSUE THREAD

**Issue by LeoDupont** [GoogleContainerTools/skaffold#3756]
Hello!

Let's say I already have a shared Dev remote cluster running some deployments (say App1, App2 and App3) that all communicate with each other.
Is it possible to temporary "replace" the cluster's App2 by a local App2 using Skaffold?

I may have misunderstood the documentation but I'm afraid I'll have to re-deploy an entire, personal new set of deployments each time I need to do some development to one component of my cluster.

It seems like `remoteManifests`, as mentioned in #2160, could help me. But I'd like some confirmation and guidance as of how to achieve this.

Thanks in advance.

**Comment by nkubala** [comment]
@LeoDupont thanks for the question. it sounds like you're trying to do something like [telepresence](https://www.telepresence.io/), which we don't really support in skaffold. if you have a few deployments configured for a few difference images, skaffold should track which images are rebuilt each time and only redeploy the changed resources - but there isn't really a way to "swap out" an existing remote deployment with a local one without deploying the entire system.

the `remoteManifests` is for k8s manifests that are hosted somewhere other than your local project files - this doesn't really have anything to do with the actual location of your cluster.

hope this helps!

**Comment by balopat** [comment]
I would like to reopen this to have a bit more discussion. 

To me this does not sound like a telepresence like feature, it is more of a "selectively building and deploying modules" from a multi-module project, where skaffold _could be_ helpful, if I understand @LeoDupont's use case correctly. 

Currently this is not easy, but you could do something like https://github.com/GoogleContainerTools/skaffold/issues/3118 with a bunch of extra scripts around your multi-module project. 

We are working on a proposal to introduce modules is skaffold that could help with this, then you could do something like `skaffold deploy --module my-module` - however, the dev loop would concentrate on only the module's logging / portforwarding, and skaffold wouldn't care about what else is deployed on the cluster - i.e. that is the user's responsibility to make sure the rest of the modules/microservices are in a consistent state. Is that what you are looking for @LeoDupont?

**Comment by LeoDupont** [comment]
@nkubala Thank you for your answer!

@balopat Yes, this is my use case: working only on some modules on an already existing and configured cluster, shared by other developpers.

I actually went for Garden.io since then, which provides such feature pretty well.
Although to me, one disadvantage of Garden is the abstraction layer with Kubernetes that is too thick and not always equivalent... But it provides a good development workflow for my use case.
Best of both worlds would be great ;)

**Comment by nkubala** [comment]
I'm going to change this to a feature request since I think this would be addressed by the addition of modules in skaffold, but I'd like to keep it open to track.

**Comment by balopat** [comment]
@LeoDupont would you mind giving feedback on the design for modules? The design doc is here: http://tinyurl.com/skaffold-modules. Thank you!

**Comment by blaggacao** [comment]
@balopat I think the gitops case which values _hermetic evaluation_ and _no side effects_ (at the minimum for production) is under represented in this design document.

**Comment by blaggacao** [comment]
I have a very similar use case:

- Provide cert-manager in the `dev` profile which for an application is a run-time dependency
- I don't want to put the cert-manager under life-cycle management of skaffold for my `dev` profile, since it takes a while to set up, reportedly up to a minute.
- I rather want to have skaffold pre-deploy the cert manager (if it exists, just reconciling it)

This would be a problem for @LeoDupont 's use case if there is made a change to the cert-manager and they can't ensure that all developers pull in those changes at the same time, though.

**Comment by nkubala** [comment]
closing this since we've shipping modules/multi-config support in skaffold!

https://skaffold.dev/docs/tutorials/config-dependencies/
