### ISSUE TITLE
Allow to stream build logs to files on per-image basis

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3778]
### Expected behavior
Before Skaffold supported parallel local builds, we used profiles for that matter, building profiles concurrently.
That allows us to stream build log for each profile (one profile per image) to file named like `{LOGS_DIR}/build/{PROFILE_NAME}.log`.
Now when Skaffold supports parallel local builds natively, we would like to use this functionality, but we want to stream build logs to files on per-image basis, because it's not very cool to look at one log for all images. Do you plan to add such functionality?

### Actual behavior
It's impossible to stream logs on per-image basis - all build logs are streamed to stdout sequentially.

### Information

- Skaffold version: v1.4.0
- Operating system: MacOs Catalina
- Contents of skaffold.yaml: not needed here

**Comment by balopat** [comment]
This is a great feature idea, we should do it!  I would also love to get some help on it from the community!

**Comment by tejal29** [comment]
Maybe closed by https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/logfile.go#L40
https://github.com/GoogleContainerTools/skaffold/pull/4594/

**Comment by nkubala** [comment]
indeed, we now support writing build logs for each image to a file using the `--mute-logs=build` flag. skaffold chooses a location to write these logs, usually somewhere in the `/var` directory. @petr-buchin is this good enough for you? we could consider making this location configurable as well

**Comment by petr-buchin** [comment]
@balopat @tejal29 @nkubala sure this is enough for me. Thank you very much for your work!
