### ISSUE TITLE
skaffold init should not traverse node_modules directory either

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3793]
we are ignoring `vendor` - we should do the same with `node_modules` too.

**Comment by dgageot** [comment]
We do already, don't we?

**Comment by briandealwis** [comment]
I took a quick look but I could not find any filtering of the "vendor" directory in init except for something specific to the buildpacks init builder?

**Comment by dgageot** [comment]
We do ignore files in `vendor` and `node_modules` when it comes to buildpacks: https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/buildpacks/init.go#L73

**Comment by gsquared94** [comment]
@balopat I also couldn't find the "vendor" directory filtering anywhere other than buildpack. Can you link the file?
