### ISSUE TITLE
Invoke Gradle with option --console=plain

### ISSUE THREAD

**Issue by ewirch** [GoogleContainerTools/skaffold#3795]
Otherwise `gradle _skaffoldFailIfJibOutOfDate` will (sometimes) print this:
```

BEGIN JIB JSON


[2A[1m<[0;32;1m======[0;39;1m-------> 50% EXECUTING [55ms][m[36D[1B[1m> :api:_jibSkaffoldFilesV2[m[26D[1B[2A{"build":["/home/me/src/my-project/backend/build.gradle","/home/me/src/my-project/backend/settings.gradle","/home/me/src/my-project/backend/gradle.properties","/home/me/src/my-project/backend/api/build.gradle"],"inputs":["/home/me/src/my-project/backend/api/src/main/resources","/home/me/src/my-project/backend/api/src/main/java"],"ignore":[]}[0K
[1B[0K
[2A[1m<[0;1m-------------> 0% WAITING[m[26D[1B[1m> :api:_jibSkaffoldFilesV2[m[26D[1B[2A[2K[1B[2K[1A
```
Regex `BEGIN JIB JSON\r?\n({.*})` in `jib.refreshDependencyList()` will not match.

Funny thing is, that it sometimes succeeds. Maybe Gradle decides to print progress based on timing.

**Comment by dgageot** [comment]
cc @TadCordle

**Comment by chanseokoh** [comment]
Aha, we should use `--console` (Gradle) and `--batch-mode` (Maven) but only for non-normal builds (those internal goals returning `BEGIN JIB JSON`).

**Comment by loosebazooka** [comment]
hrmm... we use `-Djib.console=plain` but not `--console=plain`

**Comment by chanseokoh** [comment]
I think
- for normal builds, use `-Djib.console=plain` but not `--console=plain`.
- for non-normal builds, `--console=plain` (which implies `-Djib.console=plain`).

Same goes for Maven.
