### ISSUE TITLE
Helm fqn imageStrategy declares an unused `property` child

### ISSUE THREAD

**Issue by TBBle** [GoogleContainerTools/skaffold#3799]
### Expected behavior

https://skaffold.dev/docs/references/yaml/ only shows config options that exist.

### Actual behavior

https://skaffold.dev/docs/references/yaml/ shows that `deploy.helm.releases.imageStrategy.fqn` has a field `property` described as ["defines the image config"](https://github.com/GoogleContainerTools/skaffold/blob/5ccea0511d8e7adb9b396569835d1b788bde0ee6/pkg/skaffold/schema/latest/config.go#L553).

However, the [code that handles `imageStrategy`](https://github.com/GoogleContainerTools/skaffold/blob/5ccea0511d8e7adb9b396569835d1b788bde0ee6/pkg/skaffold/deploy/helm.go#L414) never looks at `HelmFQNConfig`, let alone looks at `HelmFQNConfig.Property`. The code actually operates based on the absence of `HelmConventionConfig` meaning we want `HelmFQNConfig`, which is enforced by `oneOf` tags in [`HelmImageConfig`](https://github.com/GoogleContainerTools/skaffold/blob/5ccea0511d8e7adb9b396569835d1b788bde0ee6/pkg/skaffold/schema/latest/config.go#L543)

I haven't checked 'blame' but was this perhaps once used in the way that the keys of the `values` collection are used?

### Information

- Skaffold version: 5ccea0511d8e7adb9b396569835d1b788bde0ee6
- Operating system: N/A

### Steps to reproduce the behavior

1. Look at the YAML reference online
2. Wonder what that `property` actually does
3. Look at the code, and wonder no more.

**Comment by TBBle** [comment]
Looks like this came with the original support for Helm imageStrategies, #826, and was even the never used.

**Comment by balopat** [comment]
I agree that this looks weird, thank you for your time to dig through the code to find the issue! 
I think this part needs a bit of a redesign to make it less confusing, I agree that currently neither of HelmFQNStrategy or it's Property field are used. The last commit using HelmFQNStrategy was 73c59d01ad6ed5352e779e7b1a29ef725d868903.

**Comment by TBBle** [comment]
If there's any redesign on the image-strategy support, one thing that'd be handy is being able to specify it per-artifact (i.e. in the `values` section) since a large enough multi-chart complex might have different Docker image references with different formats.

And also https://github.com/GoogleContainerTools/skaffold/issues/3652#issuecomment-595743149 for dealing with other structures that the three currently supported.

**Comment by tejal29** [comment]
Unfortunately we won't be to get this soon. Downgrading this to P3.

**Comment by aaron-prindle** [comment]
The `artifactsOverrides` and `imageStrategy` fields were removed in Skaffold `v2.0.0` and onward and Skaffold now uses Helm + Skaffold as a `post-renderer`.  The old `artifactsOverrides` + `imageStrategy` fields are now mapped to `setValues` calls - see the docs here  https://skaffold.dev/docs/pipeline-stages/deployers/helm/ for more information.  Marking closed (as `imageStrategy`) no longer exists
