### ISSUE TITLE
[FR] Application Metadata CRD for application dashboards

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3800]
I'm opening this issue to collect feedback from the Skaffold Community how high to prioritize this feature. 

Please **comment** or **thumbs up** if this would be useful for you, especially if this is solving a certain use case, or saves time for you! Ideas on what other features would make it useful are also welcome. 

Skaffold currently stores some metadata using labels: 

```
....
Name:         teaparty-756bcd8666-fq8g5
Namespace:    default
Priority:     0
Node:         minikube/172.17.0.2
Start Time:   Fri, 06 Mar 2020 12:18:22 -0800
Labels:       app=teaparty
              app.kubernetes.io/managed-by=skaffold-v1.4.0-96-g9b9b572ee
              pod-template-hash=756bcd8666
              skaffold.dev/builder=local
              skaffold.dev/cleanup=true
              skaffold.dev/deployer=kubectl
              skaffold.dev/docker-api-version=1.40
              skaffold.dev/run-id=7ee6cb5f-8595-44e8-b856-6612c4857c96
              skaffold.dev/tag-policy=sha256
              skaffold.dev/tail=true
Annotations:  <none>
...
```

This is useful to but not _standard_. 
It turns out, there _is_ a standard way to generate this metadata: the [Application Metadata CRD](https://github.com/kubernetes-sigs/application).

Now, this specific metadata could be surfaced for example in dashboards that are Application CRD aware, for example inside Google Kubernetes Engine UI it would look like something this: 

* You could see in GKE the (not yet released) Application page the app listed and that it was deployed by Skaffold 
![image](https://user-images.githubusercontent.com/635073/76132282-f6fa8d00-5fc6-11ea-8268-0df7d9376cd4.png)

* You could see on your application's detail page the same metadata that we provide in labels (instead of ? imagine the above labels roughly) _and_ a list of all the components (i.e. deployments, pods, services, etc.) that belong to the same application 

![image](https://user-images.githubusercontent.com/635073/76132290-08dc3000-5fc7-11ea-82c9-6752aef02d8f.png)

**Comment by clhodapp** [comment]
Overall, this seems like a nice-to-have to me, but not critical.

Do note that making this data might be considered to be the job of Helm for things that do their deploys through it.

**Comment by wstrange** [comment]
I think anything that brings skaffold more in line with the standard would be goodness. But also interested in how this intersects with helm's app definition (I think Helm does its own thing here?) and if the user brings their own App definition - how would that work?

**Comment by briandealwis** [comment]
The Application CR hasn't really picked up traction, so I'm going to close this issue.  We can re-open if a successor or other standard becomes accepted.
