### ISSUE TITLE
How to represent boolean flags in buildArgs

### ISSUE THREAD

**Issue by wstrange** [GoogleContainerTools/skaffold#3811]
https://skaffold.dev/docs/pipeline-stages/builders/docker/#dockerfile-in-cluster-with-kaniko

Suggests `flags` is deprecated, but the replacement `buildArgs` is a map, and does not seem to accomodate no arg flags. For example, how does one pass  `--single-snapshot` to kaniko?

It seems like leaving in flags would be make it easier to keep up with Kaniko changes?

**Comment by tstromberg** [comment]
For no-arg flags, you should be able to specify: `flag: true`

Does that work for you?

**Comment by wstrange** [comment]
It's not clear to me where we would specify that. In flags (which is marked as deprecated), or perhaps buildArgs?
Can you give me an example of how I pass the single flag `--single-snapshot` to Kaniko?

**Comment by wstrange** [comment]
To clarify the issue, passing in `--single-snapshot` to `flags` works fine - it's just that we get a deprecation warning:
`WARN[0006] The additionalFlags field in kaniko is deprecated, please consult the current schema at skaffold.dev to update your skaffold.yaml. `

**Comment by wstrange** [comment]
ahhhh, 
```
buildArgs:
          single-snapshot: "true"
``` 

OK - yea, that works ;-) Sorry for being dense, the use of the word "flag" threw me off.  

I think a small sample in the doc would be helpful...

**Comment by wstrange** [comment]
Not sure if you want to keep this open as a doc issue?
