### ISSUE TITLE
Add support for more expressive git commit tags

### ISSUE THREAD

**Issue by emersonf** [GoogleContainerTools/skaffold#3816]
The current `gitCommit` tag policy, specifically the `AbbrevCommitSha` variant, creates tags like `0f29189`. These tags don't have a qualifier, making it harder for automation tools to distinguish them from other types of tags, e.g. version tags. Adding support for qualifiers, like a prefix to create a `commit-0f29189` tag, would make it easier for tooling to spot images that have accumulated during development, and automatically remove them from a registry, for example.

In order to support these customized tags, it may be cleaner to support `{{.ABBREV_COMMIT_SHA}}` in `envTemplate` strings than adding a new `gitCommit` setting.

**Comment by tstromberg** [comment]
This seems reasonable. As a temporary workaround, you may be able to get away with using regular expressions to differentiate between the two:

[a-f0-9]{7}

I agree that it would be preferable to be precise here. If you are interested in taking this on, I think this would be the place to change the output:

https://github.com/GoogleContainerTools/skaffold/blob/6010e510a9cb5f80de1d26e7245052c16c833209/pkg/skaffold/build/tag/git_commit.go#L118
