### ISSUE TITLE
FR: Event API should provide container logs

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#3824]
This will make it easy to rely on event API completely for logs.

**Comment by tstromberg** [comment]
This seems like a reasonable enhancement, although also one that may require a significant amount of work.  One disadvantage I see is that you'll only be able to get logs then while the skaffold process is running.

**Comment by sujit-kamireddy** [comment]
Thats a great point. I think, it should be fine, atleast for vscode, as we anyways kill the skaffold process whenever users stop the session (either running the app or debugging the app).

**Comment by nkubala** [comment]
we have some preliminary designs in the works for restructuring our output to be more consumable by different frontends. i'm gonna close this for now, but we'll open another issue for tracking when we have more concrete plans
