### ISSUE TITLE
Build Artifact Output as Standard

### ISSUE THREAD

**Issue by no1melman** [GoogleContainerTools/skaffold#3836]
### Expected behavior

Given something like, `--output-artifacts` it should dump the `build-artifacts.json`

### Actual behavior

You have to run 

```
# Quietly build artifacts and output the image names as json
  skaffold build -q > build_result.json
```

This is not useful, because in my CD, I can't see the output of the skaffold build in great detail, which is super useful, obviously

### Information

- Skaffold version: 1.5

**Comment by balopat** [comment]
We do have a flag (maybe badly named):`skaffold build --file-output bla.json ` should work. Can you confirm?

**Comment by no1melman** [comment]
Okay - yeah I missed that. I think it isn't so much badly named - just not well documented.

The examples in CLI reference for build show how you would output json, so it isn't necessarily intuative to know you can substitute `skaffold build -q > build_result.json` for `skaffold build --file-output bla.json`
