### ISSUE TITLE
Skaffold 1.6.0 does not run on Windows

### ISSUE THREAD

**Issue by erulabs** [GoogleContainerTools/skaffold#3850]
### Expected behavior
Skaffold should work! 💃 
```
λ curl -s https://storage.googleapis.com/skaffold/releases/v1.5.0/skaffold-windows-amd64.exe -o skaffold-15 && ./skaffold-15 version
v1.5.0
```

### Actual behavior
Skaffold doesn't work! 😢 
```
λ curl -s https://storage.googleapis.com/skaffold/releases/v1.6.0/skaffold-windows-amd64.exe -o skaffold-16 && ./skaffold-16 version
bash: ./skaffold-16: cannot execute binary file: Exec format error
```
Perhaps something went wrong with the windows build?

### Information

- Skaffold version: 1.6.0
- Operating system: Microsoft Windows 10 Pro 10.0.18363 Build 18363 x64-based PC
- Contents of skaffold.yaml: Does not seem to matter, happens with/without skaffold.yaml

### Steps to reproduce the behavior

1. Have a Windows 10 machine
2. run `skaffold`

**Comment by andresterba** [comment]
Same problem with the linux release.

```
~/tmp curl -s https://storage.googleapis.com/skaffold/releases/v1.6.0/skaffold-linux-amd64 -o skaffold-16 && ./skaffold-16 version
zsh: exec format error: ./skaffold-16
```

**Comment by weivall** [comment]
The same for linux. 
`-bash: /usr/local/bin/skaffold: cannot execute binary file: Exec format error`.

**Comment by thanhvd** [comment]
The same for linux.
-bash: /usr/local/bin/skaffold: cannot execute binary file: Exec format error

**Comment by tvvignesh** [comment]
Same occurring for me in linux (Ubuntu 19.10) - 
`Linux vignesh-predator 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I get this error:

![Screenshot from 2020-03-20 17-56-56](https://user-images.githubusercontent.com/1165845/77163492-33a0ab00-6ad4-11ea-838c-96e46e8619d5.png)

**Comment by iwagner-inmar** [comment]
It appears at least the linux release is a Darwin binary:

```
$ curl -s -LO https://github.com/GoogleContainerTools/skaffold/releases/download/v1.6.0/skaffold-linux-amd64

$ file skaffold-linux-amd64
skaffold-linux-amd64: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>
```

**Comment by diegomarangoni** [comment]
Looks like this release was made manually according to the issue https://github.com/GoogleContainerTools/skaffold/issues/3847

**Comment by balopat** [comment]
I am so sorry, I will fix this, yes I manually pushed the binaries, using the results of `make cross` from Mac. Probably something got messed up in our build process.

**Comment by diegomarangoni** [comment]
To build from source:

```
$ git clone https://github.com/GoogleContainerTools/skaffold.git
$ cd skaffold
$ git checkout v1.6.0
$ ./hack/install_golint.sh
$ make
$ sudo mv out/skaffold /usr/local/bin
```

**Comment by balopat** [comment]
This should be fixed now! Please confirm.

**Comment by diegomarangoni** [comment]
I've tested for MacOS version, and it's working... thanks

**Comment by andresterba** [comment]
Works on linux. :+1:

**Comment by balopat** [comment]
I tested on windows and works now too. Please ping here if you see something's wrong. The homebrew update is still outstanding, https://github.com/Homebrew/homebrew-core/pull/51915. Thanks!
