### ISSUE TITLE
Skaffold + jib + gardle + helm2 auto sync fails with permission error

### ISSUE THREAD

**Issue by Romeh** [GoogleContainerTools/skaffold#3861]
### Information

- Skaffold version: 1.6.0
- Operating system: mac OS
- Contents of skaffold.yaml:
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: catalog-app
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: false
  artifacts:
    - image: docker-registry.test.com/test/test-app
      jib:
        project: test-app
      context: .
      sync:
        auto: {}
deploy:
  kubeContext: docker-for-desktop
  helm:
    releases:
      - name: test-app
        namespace: default
        chartPath: test-app/src/main/helm
        valuesFiles:
          - test-app/src/main/helm/values.yaml
        setValueTemplates:
          "dig.image.repository": '{{.IMAGE_NAME}}'
          "dig.image.tag": '{{.DIGEST_HEX}}'
```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior
when I enable auto sync with Jib and skaffold , changing the code trigger sync that fail on skaffold DEV mode as the following : 
Syncing 2 files for docker-registry.test.com/test/test-app:3713ae531ef4e2357ff04f3d70526f822076ac8f1b4fb9938d50a69ec2670362
WARN[4828] Skipping deploy due to sync error: copying files: Running [kubectl --context docker-for-desktop exec dig-66d8b576dd-4tq98 --namespace default -c dgc -i -- tar xmf - -C / --no-same-owner]
 - stdout: 
 - stderr: tar: removing leading '/' from member names
tar: can't remove old file app/resources/META-INF/build-info.properties: Permission denied
command terminated with exit code 1
: exit status 1 
Watching for changes...

any clues or tips guys how to fix it ?

**Comment by chanseokoh** [comment]
Is your image `test-app` configured to run as a non-root user?

**Comment by Romeh** [comment]
@chanseokoh i am using jib default gardle build docker task without any user configuration , do i need to configure a user for such use case ?

**Comment by chanseokoh** [comment]
Can you locate `app/resources/META-INF/build-info.properties` and check the permissions and the ownership information of the file inside the image at runtime? Both locally with Docker and remotely on Kubernetes. Can you also check the user running your image on Kubernetes?

For remote access, something like `kubectl --context docker-for-desktop exec -it <your pod name> --namespace default -c dgc -- sh` (assuming your container name is `dgc`) should give you a shell prompt. See the [doc](https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/#opening-a-shell-when-a-pod-has-more-than-one-container) for help.

**Comment by Romeh** [comment]
it is root user as is from sh connection to the target container : 

<img width="581" alt="Screenshot 2020-03-23 at 22 11 24" src="https://user-images.githubusercontent.com/10168589/77363703-78864500-6d53-11ea-996b-e96eda8ea12f.png">


<img width="576" alt="Screenshot 2020-03-23 at 22 10 30" src="https://user-images.githubusercontent.com/10168589/77363707-79b77200-6d53-11ea-8fb8-148c1f97b54c.png">

**Comment by chanseokoh** [comment]
> Can you also check the user running your image on Kubernetes?

Can you check this too through `kubectl exec`? Run `id` or `whomai`, for example.

**Comment by Romeh** [comment]
it is root user as is i see : 
/app/resources/META-INF $ id
uid=1000 gid=0(root)

**Comment by chanseokoh** [comment]
No, it is not a root user. The UID is 1000. (OTOH, the UID of root is 0. And the GID is not a user but group.) This is why the `tar` command is failing.

I have no experience with Docker for Desktop, but I guess the platform is set up to run images as non-root?

**Comment by Romeh** [comment]
Thanks for the explanation man , so to understand , the sync auto only work if my image run with root user ? 

as i did not find any documentation about user privileges to make sync work ?

**Comment by chanseokoh** [comment]
> the sync auto only work if my image run with root user ?

Not necessarily. If `build-info.properties` is writable by UID 1000, the `kubectl exec ... tar` extraction command will work. Running as root will always work, of course.

> as i did not find any documentation about user privileges to make sync work ?

Check the [File Sync](https://skaffold.dev/docs/pipeline-stages/filesync/) doc:

> ### Limitations
> File sync has some limitations:
> - File sync can only update files that can be modified by the container’s configured User ID.

> meanwhile my deployment security context is configured to be non root :

Makes sense. This is actually what I suspected from the beginning. I think for development, you could have a separate profile to run the image as root. Or, make files writable by UID 1000 somehow (by changing either the ownership or the permissions), but perhaps changing the runtime user on the platform is better than modifying the image. Of course, you don't want to do these for a production image.

**Comment by Romeh** [comment]
Now it works with losen up security context for local DEV , Thx man for your support so closing this issue now
