### ISSUE TITLE
open Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by cmoad** [GoogleContainerTools/skaffold#387]
Upgraded to v0.4.0 and a working config for v0.3.0 now fails. It looks like my custom dockerfilePath isn't being picked up anymore.

### Expected behavior

skaffold v0.4.0 runs the same as skaffold v0.3.0 with the same config file.

### Actual behavior

Getting an error that I did not in v0.3.0.

```
% skaffold -v debug dev
INFO[0000] Skaffold &{Version:v0.4.0 GitVersion: GitCommit:8a99affded87a0f81e3ee90bd9f24f01aec5038d GitTreeState:clean BuildDate:2018-04-12T22:37:36Z GoVersion:go1.10.1 Compiler:gc Platform:darwin/amd64}
INFO[0000] Using kubectl context: minikube
DEBU[0000] Running command: [minikube docker-env --shell none]
DEBU[0000] Command output: stdout DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.64.101:2376
DOCKER_CERT_PATH=/Users/charlie/.minikube/certs
DOCKER_API_VERSION=1.23
, stderr: , err: %!s(<nil>)
Error: running skaffold steps: getting path to dependency map: generating path to artifact map: getting paths for artifact abbott: getting dockerfile dependencies: opening dockerfile: %!d(string=Dockerfile): open Dockerfile: no such file or directory
```

### Information

```
Skaffold version: v0.4.0
Operating system: Mac 10.13.4
Content of skaffold.yaml:

apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: abbott
    dockerfilePath: service/abbott/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
      - ops/k8s/dev/abbott/abbott-*.yaml
```

**Comment by cmoad** [comment]
Looking through the source reveals a new yaml path for dockerfilePath:

```
build:
  artifacts:
  - imageName: abbott
    docker:
      dockerfilePath: service/abbott/Dockerfile
```

Updating my config to this layout seems to fix the problem. I can't find any examples of this change in the repo.

**Comment by dgageot** [comment]
Thanks @cmoad it's indeed a breaking change and we should add at least a sample

**Comment by Anakin-Hao** [comment]
I m seeing the same issue.
My Env    : Win 10 Pro
Minikube : v0.25.0
Skaffold   :v0.4.0

`
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: proj-rest
    dockerfilePath: ./myproject/Dockerfile
`

it's complaining on "Error: running skaffold steps: getting path to dependency map: generating path to artifact map: getting paths for artifact abbott: getting dockerfile dependencies: opening dockerfile: %!d(string=Dockerfile): open Dockerfile: no such file or directory"

**Comment by dgageot** [comment]
@Anakin-Hao Can you change the configuration and retry?

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: proj-rest
    docker:
      dockerfilePath: ./myproject/Dockerfile
```

**Comment by Anakin-Hao** [comment]
@dgageot 
Using this config, i m getting error on "Cannot locate specified Dockerfile:"

skaffold.yaml
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: proj-rest
    workspace: .
    docker:
      dockerfilePath: ./proj-rest/Dockerfile
```

Output
```
> skaffold dev
Starting build...
Found [minikube] context, using local docker daemon.
Sending build context to Docker daemon  58.37kB
WARN[0001] run: build: build step: running build for artifact: running build: docker build: Error response from daemon: Cannot locate specified Dockerfile: ./proj-rest/Dockerfile
Watching for changes...
```

- My OS : Win 10 Pro
- Minikube : v0.25.0
- Skaffold : v0.4.0

**Comment by Anakin-Hao** [comment]
@dgageot any update?

**Comment by r2d4** [comment]
Yes, I suppose skaffold should take paths relative to the skaffold.yaml. Currently, all paths are relative to the skaffold process directory. Taking paths to the skaffold yaml makes things a bit trickier in the code, since all paths will need to be joined or executed in the context of that separate config path.

**Comment by r2d4** [comment]
Yep that would be great @derekperkins

**Comment by dlorenc** [comment]
https://github.com/GoogleContainerTools/skaffold/issues/503 seems like a good umbrella issue to track this in. I'll close this to track it there.
