### ISSUE TITLE
Squash images using Docker options

### ISSUE THREAD

**Issue by tvvignesh** [GoogleContainerTools/skaffold#3887]
Hi. Docker image build provides an experimental flag `--squash` to squash new layers of images as mentioned here: https://docs.docker.com/engine/reference/commandline/image_build/

May I know how to pass the option via skaffold during build. Not sure how custom docker flags are to be passed via Skaffold. Thanks.

**Comment by tejal29** [comment]
@tvvignesh you can use the `buildArgs` config in `build.docker` like mentioned in the docs here
https://skaffold.dev/docs/references/yaml/

Closing this for now. Please feel free to reopen
