### ISSUE TITLE
skaffold render --output takes GCS file path

### ISSUE THREAD

**Issue by ChrisGe4** [GoogleContainerTools/skaffold#3902]
I would like to make a proposal to add functionality to allow --output flag to take a GCS path for skaffold render

if the value I pass to --output starts with gs://, skaffold should treat it as a GCS path.

possible solution:

Call gsutil in https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/util.go#L86 if filepath starts with gs://

**Comment by nkubala** [comment]
hey @ChrisGe4, thanks for filing. functionally this would be equivalent to `skaffold render --output render.json && gsutil cp render.json <gcs_path>`, but I suppose I wouldn't be opposed to supporting it natively in skaffold. our team probably won't be able to prioritize this any time soon, but contributions are always welcome!

**Comment by dgageot** [comment]
This was fixed with https://github.com/GoogleContainerTools/skaffold/pull/3979
