### ISSUE TITLE
Skaffold debug for NodeJS should handle `docker-endpoint.sh`

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#3903]
See GoogleCloudPlatform/cloud-code-samples#261 for details.

**Comment by balopat** [comment]
yeah I remember that I wanted to comment on https://github.com/GoogleContainerTools/skaffold/pull/3827 that that is not sufficient. Let's fix it. This is not p0 though.

**Comment by briandealwis** [comment]
Fixed by #4026.
