### ISSUE TITLE
Support kpt as a deployer

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/skaffold#3904]
https://github.com/GoogleContainerTools/kpt
https://googlecontainertools.github.io/kpt/

Similar to the kustomize+kubectl support:
https://skaffold.dev/docs/pipeline-stages/deployers/#deploying-with-kustomize

**Comment by tstromberg** [comment]
+1 - we should do this.

**Comment by jlewi** [comment]
How will skaffold.yaml and kpt setters interact if at all? For example, when skaffold builds/deploys a kpt package will it update setters to reflect the most recent values?

I often use skaffold and kpt together. I often use skaffold to build my images and then update my kpt package to use the newly built image.

I usually do this by having skaffold output the image and then using kpt + yq to set it; e.g

```
skaffold build --kube-context=${CONTEXT} -v debug --file-output=image.json
kpt cfg set -R . image $(shell yq r image.json builds[0].tag )
```

Any thought about whether this is something skaffold should support out of box?

**Comment by yuwenma** [comment]
> How will skaffold.yaml and kpt setters interact if at all? For example, when skaffold builds/deploys a kpt package will it update setters to reflect the most recent values?
> 
> I often use skaffold and kpt together. I often use skaffold to build my images and then update my kpt package to use the newly built image.
> 
> I usually do this by having skaffold output the image and then using kpt + yq to set it; e.g
> 
> ```
> skaffold build --kube-context=${CONTEXT} -v debug --file-output=image.json
> kpt cfg set -R . image $(shell yq r image.json builds[0].tag )
> ```
> 
> Any thought about whether this is something skaffold should support out of box?

Hi Jeremy, skaffold and kpt setters are working independently right now, but we have plans to support what you need here. Basically, you would be able to define kpt setters as a config file and provide its path in skaffold.yaml kpt. For now, I think a bash script to automate the step would be most efficient.

**Comment by yuwenma** [comment]
The kpt deployer is added to skaffold (stable version) and I think we can mark this issue done. Future changes related to render v2 is orthogonal to this request.

**Comment by irvifa** [comment]
HI @yuwenma do we have documentation on how to use this through the Skaffold?

**Comment by yuwenma** [comment]
> HI Yuwen Ma do we have documentation on how to use this through the Skaffold?

@irvifa You can try out these interactive codelabs: 
- [01 kpt validation](https://github.com/GoogleContainerTools/skaffold/tree/master/codelab/01_kpt-validate)
- [02 kpt deploy](https://github.com/GoogleContainerTools/skaffold/tree/master/codelab/02_kpt-deploy)

And check [this reference](https://skaffold.dev/docs/references/yaml/#deploy-kpt) for full features
