### ISSUE TITLE
status check blocks rebuild/redeploy

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3908]
I'm seeing this on microservices example: when both status check are pending, rebuilds and redeploys don't work on file changes.

**Comment by balopat** [comment]
I realized that this was designed this way. However I strongly feel that we should improve it. 
The work is not trivial at all - wiring up watcher events to the deployment flow will require probably to fan out the original events - so that they are not consumed from the channels that are actually used by `doDev`. That fanout could be used for cancellable builds as well though! 

For the fanout of the triggers and intents we need to probably set a second watcher? Not sure, needs thought.

**Comment by tejal29** [comment]
This is closed by https://github.com/dgageot/skaffold/commit/80a73e3f91fb8d2eb96be67d7ff0d93ab8d6164f
