### ISSUE TITLE
Make upgrade notification actionable

### ISSUE THREAD

**Issue by russwolf** [GoogleContainerTools/skaffold#3920]
### Expected behavior
It would be nice if the instructions provided a more complete set of instructions to update. New users can see full instructions here (https://skaffold.dev/docs/install/) for setup. Since Skaffold updates so frequently it might be nice to do one of a few options: 
a) provide the full set of instructions to update e.g. for OSX

> curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64
> chmod +x skaffold
> sudo mv skaffold /usr/local/bin

b) offer a link to a website where the instructions can be viewed. 

I'm not sure how much of a problem this is, but it could also be nice for the purpose of helping users not install multiple different competing skaffold versions on their machine unintentionally and using the wrong one from their path. 

### Actual behavior
There is a new version (1.7.0) of Skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64

### Information
- Skaffold version: Not sure. Already updated to newest. 
- Operating system: 10.14.6
- Contents of skaffold.yaml: n/a

### Steps to reproduce the behavior
1. Run skaffold dev on an outdated version of Skaffold

**Comment by tstromberg** [comment]
Perhaps we should just direct the user to the releases page - which then has more detailed installation instructions?
