### ISSUE TITLE
unable to set an empty default repo

### ISSUE THREAD

**Issue by shantanugadgil** [GoogleContainerTools/skaffold#3923]
I have an issue during `skaffold build` that I cannot specify an empty value "" as the `default-repo`.
The parameter `--default-repo=""` doesn't seem to be taking effect.

In my skaffold yaml I have two profiles, one with the "base images" and the other with the application services.
The base images are derived from CentOS and then updated and needed packages are added to them.
All the application service use the base image created as part of the base images.

### Steps
1. skaffold build -p base_images -b mycentos
2. skaffold build -p application -b myservice1

### global skaffold config
`cat ~/.skaffold/config`
```
  default-repo: my-private-ip:5000/shantanu
```

I tried the following cmd, but that doesn't work either:
` env SKAFFOLD_DEFAULT_REPO="" skaffold build -p base_images -b mycentos --default-repo ""`

### Expected behavior
A Docker image with just the name `mycentos:latest` should be created.
My application service images are using the custom `mycentos:latest` in their `FROM` line

### Actual behavior
A docker image get created with the full tag gets created:
```
docker images

my-private-ip:5000/shantanu/mycentos   latest ...

```

### Information

- Skaffold version: v1.7.0
- Operating system: Ubuntu 16.04.x

**Comment by shantanugadgil** [comment]
Also, upon deeper experimentation, the flag `--default-repo` is not getting honored during a `skaffold build` for **non-default** kube-context parameters.

I am not sure at this point if `default-repo` is even supposed to work with non-default `kube-context`, but putting it out there for the skaffold devs! 😃

**Comment by dgageot** [comment]
@shantanugadgil In Go, empty string often has the same meaning as undefined. I'll check what we can do

**Comment by dgageot** [comment]
I'll add a special case for that one flag.
