### ISSUE TITLE
[feature request] provide a flag to disable update check

### ISSUE THREAD

**Issue by shantanugadgil** [GoogleContainerTools/skaffold#3927]
Request to provide a cmd-line and config flag to disable update checking while running the skaffold binary.

### Expected behavior
when I run skaffold, it should not check online for a newer version

### Actual behavior
currently it checks online for a newer version

### Information

- Skaffold version: v1.7.0
- Operating system: Ubuntu 16.04
- Contents of skaffold.yaml: n/a

**Comment by nkubala** [comment]
`skaffold config set update-check false`

**Comment by shantanugadgil** [comment]
it is hiding in the Privacy section ... of course! :)

ref:
https://skaffold.dev/docs/references/privacy/
