### ISSUE TITLE
137 error code during npm install

### ISSUE THREAD

**Issue by tvvignesh** [GoogleContainerTools/skaffold#3928]
Hi. I have been lately facing an issue during CI/CD (Gitlab) with `npm install` frequently with error code being returned as 137 (Screenshot below)

![Screenshot from 2020-04-09 00-03-54](https://user-images.githubusercontent.com/1165845/78820829-189bc980-79f6-11ea-9382-2c8e387e7e61.png)

To start with, I am not sure if this is a problem with Skaffold or Gitlab Runner or GCloud (GKE) but I am filing this here because it started after I upgraded to Skaffold 1.7 and the latest version of Gitlab runner. (Will be filing an issue in Gitlab repo as well)

The links I referred say that I have to increase the memory in my container but I checked all containers and they have enough memory (not sure if I missed any).

The thing is it happens only during `npm install` and not during any other step and is very random. If I keep retrying the same build again and again, it successfully completes 1 in 10 times

Links I referred:

https://gitlab.com/gitlab-org/gitlab-runner/issues/4490
https://gitlab.com/gitlab-org/gitlab-runner/issues/3402
https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/2289
https://gitlab.com/gitlab-org/charts/gitlab-runner/issues/114
https://gitlab.com/gitlab-org/gitlab-runner/issues/3816
https://gitlab.com/gitlab-org/gitlab-runner/issues/3784
https://gitlab.com/gitlab-org/gitlab-runner/issues/3402
https://gitlab.com/gitlab-org/gitlab-runner/issues/1078

I am using DIND (to cache images in CI) and verdaccio (private NPM registry) to reduce external http requests and everything used to work fine till the last few days. Not sure where to begin to look. Any help appreciated. Thanks.

**Comment by balopat** [comment]
This does seem like an OOM on your docker runtime during builds and independent of skaffold. 
You should see the same behavior with older skaffold versions.

**Comment by tvvignesh** [comment]
@balopat Yup. That's what the forums said as well. That clarifies it. Closing this issue. Any recommendations on where I can look out to fix the error? Will try it out and see. Thanks.
