### ISSUE TITLE
Print summary of skaffold execution

### ISSUE THREAD

**Issue by coolpalani** [GoogleContainerTools/skaffold#3937]
I'm wondering if you print summary of skaffold execution it would be great. Like for example if you run helm chart, at the end of deployment it will print `kubectl get deloyment,svc,pvc -n namespace` status.
It will helpful to quickly navigate application url when deploy service using NodePort type.

Note: This is not bug, please add feature request flag if you feel make sense.

**Comment by tstromberg** [comment]
Seems like a reasonable UX improvement, but also not that high of a priority for the team. We would welcome a PR though!

**Comment by tejal29** [comment]
adding help wanted label

**Comment by tejal29** [comment]
Thanks @coolpalani. We think the recent cloud code logging experience with k8s explorer is a better UI for deployed k8 resources. Closing this ticket
