### ISSUE TITLE
Skaffold should use buildpacks builder to determine validity of image cache

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#3980]
If I change `examples/buildpacks` to use a different builder after having built it, Skaffold does not detect the change change of builder and reuses the built image with the previous builder.

**Comment by dgageot** [comment]
It does detect the change when you change the builder's name. However it'll not use the digest of the image, just its name. What happened to you, I think, is that you had already built with both builders and both were in cache.

A workaround to this issue is to use the full digest of the builder.

**Comment by briandealwis** [comment]
Oh! That makes sense. 👍
