### ISSUE TITLE
Explicit deactivation of profile via CLI argument

### ISSUE THREAD

**Issue by masih** [GoogleContainerTools/skaffold#3988]
Is there a way to explicitly disable a profile that may have been automatically activated?

**Comment by dgageot** [comment]
Hi @masih I'm sorry there's no such feature. Shouldn't be too complicated to add, though

**Comment by dgageot** [comment]
All the work happens here: https://github.com/GoogleContainerTools/skaffold/blob/d402799901c8c7b92fa670a38590e89bf2fd6de0/pkg/skaffold/schema/profiles.go#L39

**Comment by masih** [comment]
Thanks for the quick response @dgageot 🍻 

it would be fantastic if that's added. This could even be a flag to disable "auto-activation" and make profile enablement explicit.  

I think this would be useful in CI build environment just to assert behaviour and avoid unwanted accidental ones. Outside of that, it could be useful for capturing say integration tests in a profile that are run explicitly against a profile _after_ that profile is say deployed remotely. After tests are run one would want to clean up the test resources. That option would assure that I won't accidentally delete application resources as part of cleaning up integration test resources.

**Comment by tstromberg** [comment]
Makes sense to me. I can definitely see where you would want to be very explicit about which profiles to use in a CI environment. @dgageot - any additional feedback?

**Comment by dgageot** [comment]
Profile auto-activation was fixed by https://github.com/GoogleContainerTools/skaffold/pull/4034
I'll add a way to disable a single profile

**Comment by masih** [comment]
Fantastic many thanks 🍻
