### ISSUE TITLE
cryptic build fail: docker build: error during connect: Post "https://127.0.0.1:32769/v1.24/build...": EOF

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#3994]
```
Listing files to watch...
 - gcr.io/elegant-beach-274806/ih-aas
Generating tags...
 - gcr.io/elegant-beach-274806/ih-aas -> gcr.io/elegant-beach-274806/ih-aas:f836c96
Checking cache...
 - gcr.io/elegant-beach-274806/ih-aas: Not found. Building
Building [gcr.io/elegant-beach-274806/ih-aas]...
FATA[0007] exiting dev mode because first build failed: build failed: building [gcr.io/elegant-beach-274806/ih-aas]: build artifact: docker build: error during connect: Post "https://127.0.0.1:32769/v1.24/build?buildargs=null&cachefrom=null&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=null&memory=0&memswap=0&networkmode=&rm=0&shmsize=0&t=gcr.io%2Felegant-beach-274806%2Fih-aas%3Af836c96&target=&ulimits=null&version=": EOF
ironbark ~/git/glasnt/ih-aas [master] $
```

It seems that this is a build failure, but I would expect to see the build logs, not a URL of something I do not understand

**Comment by tstromberg** [comment]
I read this error as: Skaffold tried to send a build request to the local Docker daemon, but failed because Docker unexpectedly closed the connection.

Skaffold *should* retry all idempotent HTTP requests, including this one. 

Even if it was retried, we should be able to to return a better error message.

**Comment by briandealwis** [comment]
Revising down as it's not breaking functionality.

I *think* this particular case is because Docker was not running.

**Comment by dgageot** [comment]
This should be fixed with https://github.com/GoogleContainerTools/skaffold/pull/3998
