### ISSUE TITLE
`skaffold deploy` exit status 0 when Helm deployer failed

### ISSUE THREAD

**Issue by kostyaplis** [GoogleContainerTools/skaffold#4005]
### Expected behavior
Skaffold should return non-zero exit code if deployer failed
### Actual behavior
Skaffold throws `WARN[0010] exit status 1 ` and exited with 0 status, that makes our CI/CD to believe  that deploy successfully finished, even if it not started...
### Information
Issue introduced in version `1.5.0` and still exists in `1.8.0`. 
I've tested several scenarios. With Helm `2.16.5` and `3.1.2`.
Some helm failures captured as `FATA` while others `WARN` and 0 exit code. 
Let me put one example that reproducible using both Helm2 and Helm3
Skaffold version: `1.8.0`

- Contents of skaffold.yaml:
Note on `--atomic` flag

```yaml
apiVersion: skaffold/v2alpha4
kind: Config
profiles:
- name: cronjob
  deploy:
    helm:
      flags:
        install: ['--atomic']
        upgrade: ['--atomic']
      releases:
        - name: cronjob
         namespace: default
         chartPath: repo/cronjob_chart
         remote: true
         wait: true
         valuesFiles:
           - "helm_values/{{.TARGET_ENV}}/cronjob.yaml"
         setValueTemplates:
            image.tag: "{{.DOCKER_TAG}}"
        overrides:
           image:
             repository: repo/cronjob_image
```

- Contents of cronjob.yaml:
```yaml
***
cronjobs:
- name: super-long-resource-name-that-exceeds-63-characters
***
```

Run Skaffold deploy:
```bash
$ DOCKER_TAG=docker_tag TARGET_ENV=dev skaffold deploy -p cronjob -f skaffold.yaml
Tags used in deployment:
Starting deploy...
Helm release cronjob not installed. Installing...
INSTALL FAILED
PURGING CHART
Error: release cronjob failed: CronJob.batch "cronjob-cronjob-super-long-resource-name-that-exceeds-63-characters" is invalid: [metadata.labels: Invalid value: "cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 63 characters, spec.jobTemplate.spec.template.spec.containers[0].name: Invalid value: "cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 63 characters, metadata.name: Invalid value: "cronjob-cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 52 characters]
Successfully purged a chart!
Error: release cronjob failed: CronJob.batch "cronjob-cronjob-super-long-resource-name-that-exceeds-63-characters" is invalid: [metadata.labels: Invalid value: "cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 63 characters, spec.jobTemplate.spec.template.spec.containers[0].name: Invalid value: "cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 63 characters, metadata.name: Invalid value: "cronjob-cronjob-super-long-resource-name-that-exceeds-63-characters": must be no more than 52 characters]
WARN[0010] exit status 1                                
Waiting for deployments to stabilize...
Deployments stabilized in 1.864473587s

$ echo $?
0
```

Remove `--atomic` flag from skaffold manifest and above command produces following output (last few lines):
```bash
WARN[0009] error retrieving helm deployment info: Error: release: "cronjob" not found 
FATA[0009] deploying cronjob: exit status 1

$ echo $?
1
```

Note that it is not just about `--atomic`.  There were few other cases I came over last week that been throwing `exit status 1` from Helm, but Skaffold exits with zero. Let me know if you required more information, I'll try to reproduce those again.
```bash
WARN[0010] exit status 1 

$ echo $?
0
```
Thanks in advance!

**Comment by nkubala** [comment]
@kostyaplis it would be great to have a small sample project in a repo that we could use to reproduce. I'm not seeing this with any of our other examples or any of my initial tests. my guess is that this has something to do with the status check not knowing about the errors returned by helm, but it's hard to say.

also, providing us with your full chart config as well as logs from running with `-v DEBUG` would be helpful!

**Comment by kostyaplis** [comment]
@nkubala 
Hi Nick!
I've created [test chart](https://github.com/kostyaplis/test-cronjob-helm) that you can use to reproduce two types of issues.
```bash
git clone git@github.com:kostyaplis/test-cronjob-helm.git
cd test-cronjob-helm
```

1. Let's assume that chart itself is broken. I.e. it expects a key path that doesn't exist

```bash
$ skaffold deploy -p test-cronjob -f skaffold.yaml
Tags used in deployment:
Starting deploy...
Helm release cronjob not installed. Installing...
Error: template: basic/templates/cronjob.yaml:39:54: executing "basic/templates/cronjob.yaml" at <.doesnt_exist.env>: nil pointer evaluating interface {}.env
WARN[0005] exit status 1
Waiting for deployments to stabilize...
Deployments stabilized in 831.367963ms
$ echo $?
0
```

2. Let's assume that provided value is broken. I.e. resource name is longer than 63 chars.
Do remove `.doesnt_exist` part from ` basic/templates/cronjob.yaml:39`

```bash
$ skaffold deploy -p test-cronjob -f skaffold.yaml
Tags used in deployment:
Starting deploy...
Helm release cronjob not installed. Installing...
Error: release cronjob failed, and has been uninstalled due to atomic being set: CronJob.batch "cronjob-basic-super-long-resource-name-that-exceeds-63-characters-and-should-fail" is invalid: [metadata.labels: Invalid value: "basic-super-long-resource-name-that-exceeds-63-characters-and-should-fail": must be no more than 63 characters, spec.jobTemplate.spec.template.spec.containers[0].name: Invalid value: "basic-super-long-resource-name-that-exceeds-63-characters-and-should-fail": must be no more than 63 characters, metadata.name: Invalid value: "cronjob-basic-super-long-resource-name-that-exceeds-63-characters-and-should-fail": must be no more than 52 characters]
WARN[0005] exit status 1
Waiting for deployments to stabilize...
Deployments stabilized in 755.410779ms
$ echo $?
0
```

I think no need to provide debug output here, as long as you can reproduce it easily on your end.

**Comment by yolkov** [comment]
This bug breaks our pipeline CI/CD
skaffold version v1.7.0
helm version v2.16.1

**Comment by balopat** [comment]
I am pretty puzzled why we swallow that error: 

we throw an error pretty much everywhere else, but for some reason here, we swallow it: 

https://github.com/GoogleContainerTools/skaffold/blob/4ee028bb817e496e8181a5e12e22e291ccc91fb4/pkg/skaffold/deploy/helm.go#L315-L319

@tstromberg do you recall why was this accepting errors here? It looks like your refactoring introduced this - my inclination would be to just return error there, but the comment is holding me back.
