### ISSUE TITLE
Doc inconsistency on deploy/kustomize

### ISSUE THREAD

**Issue by sw360cab** [GoogleContainerTools/skaffold#4007]
Apparently documentation about [yaml syntax](https://skaffold.dev/docs/references/yaml/) is inconsitente on the kustomize part.
*Path* to kustomization.yaml files is referred as `paths`.

However the schema for v1 reports `path` for the same configuration part.
See [source code](https://github.com/GoogleContainerTools/skaffold/blob/07993d12af6a55edcf1c72562af7f7832f1d26a8/pkg/skaffold/schema/v1/config.go#L443)

### Information

- Skaffold version: v1.8.0
- Operating system: Mac Os - Darwin Kernel Version 18.0.0

**Comment by briandealwis** [comment]
Hi @sw360cab.  `path` was renamed to `paths` in v2alpha3 in #3585.  The reference `skaffold.yaml` uses the latest release (currently v2beta2).
