### ISSUE TITLE
Do not use "Builder" as a message name for Skaffold proto

### ISSUE THREAD

**Issue by ivanporty** [GoogleContainerTools/skaffold#4056]
When we consume Skaffold proto file in Cloud Code IJ (and compile it into Java code), we now have a conflict with `Builder` name being already used in any protoc-compiled class. Java generated code heavily uses `Builder` pattern and each structure will have its own `Builder` associated to it. We suggest renaming to something like `ContainerBuilder`:

```
...
message BuildMetadata {
  message ContainerBuilder {
      BuilderType type = 1;
      int32 count = 2;
  }
...
```

**Comment by dgageot** [comment]
@ivanporty If we changed it right now, what would be the impact for the IDES, in terms of compatibility?

**Comment by balopat** [comment]
- I don't think this is used yet, this is fairly new, right? 
- nit: i'd prefer `ImageBuilder` 
- I'm surprised this happens - is this a java protoc thing or an IntelliJ thing - i.e. do we have control over it or not? If it's the former, then we could in theory run tests to make sure proto libs generate valid code .

**Comment by ivanporty** [comment]
* No impact to IDEs is expected, as we are not really using it yet. 
* `ImageBuilder` sounds good.
* It probably because of our version of protobuf coming bundled with IntelliJ. Currently we try to use the Gradle plugin to automatically compile the proto together with the project, so it has to use the same versions and protoc, resulting in this error. One option is to do that manually, separately from build process - is this what Skaffold does with protoc images?
