### ISSUE TITLE
Integration tests fail with kind 0.8.0

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#4095]
Tests fail with this error:

```
creating namespace: Post "https://kind-control-plane:6443/api/v1/namespaces": dial tcp: lookup kind-control-plane on 169.254.169.254:53: no such host
```

**Comment by nkubala** [comment]
@dgageot have you seen this recently? I've never seen this error, was it happening in CI or local?

**Comment by dgageot** [comment]
@nkubala our integration tests use the previous version.

**Comment by tejal29** [comment]
@dgageot @nkubala do we plan to work on this in near future? This issue is out of SLO and if we don't plan to work on this, i can reduce the priority to p2

**Comment by dgageot** [comment]
The problem is only with our integration tests. Skaffold works well with kind 0.8.0. So, yes, changin gto P2
