### ISSUE TITLE
Improve build and deploy output from docker daemon/registry

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#41]
We are not processing the messages from the docker daemon or registry properly, so output isn't as pretty as it should be.  We should compress status updates for the same layers, add progress bars, etc.

Example:
```
abe52c89597f: Verifying Checksum
abe52c89597f: Download complete
96e333289084: Verifying Checksum
96e333289084: Download complete
39cd5f38ffb8: Verifying Checksum
39cd5f38ffb8: Download complete
503166935590: Verifying Checksum
503166935590: Download complete
ce145c5cf4da: Verifying Checksum
ce145c5cf4da: Download complete
503166935590: Pull complete
abe52c89597f: Pull complete
ce145c5cf4da: Pull complete
96e333289084: Pull complete
39cd5f38ffb8: Pull complete
```

**Comment by smarterclayton** [comment]
We have a reasonably low dependency formatter for pull here that I would like to see split out and cleaned up https://github.com/openshift/imagebuilder/tree/master/imageprogress

**Comment by r2d4** [comment]
@dgageot you fixed this at some point I think?

**Comment by balopat** [comment]
ping @dgageot, is this fixed?
