### ISSUE TITLE
Environment variable validation

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#4124]
**Background**
Environment variables are used in multiple places in skaffold: the helm fields as well as the envTemplate tagger for example inside the skaffold.yaml.

**Problem**
Env vars are convenient but create a challenge: they form a schema-free API to parametrize the skaffold configuration. One can pass in incorrect env vars, or miss mandatory ones, and realize the impact much later in the skaffold process. 

**Proposal**
Users would be able to define a schema for their environment variables. When skaffold executes, it would validate for the existence of mandatory env vars and valid combinations of env var values. 

If you like this idea, please thumbs up, also if possible, please share validation logic that would be interesting for you!

**Comment by briandealwis** [comment]
There has been no feedback on this issue in more than a year.  Closing and can re-open if there is desire.
