### ISSUE TITLE
WithFlags() change should defer applying default values until the command is to be used

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4129]
#4089 seeks to add `dev`'s `--auto-{build,deploy,sync}` options to `skaffold debug` but [with different default values](https://github.com/GoogleContainerTools/skaffold/pull/4089/files#diff-e38cfd6902a46a3295cb4067d8158878R37-R49).  But the obvious (or naive? :grinning:) attempt fails as Skaffold's commands framework immediately applies the function passed to `WithFlags()`:

https://github.com/GoogleContainerTools/skaffold/blob/86b4fde68f9b1530f09fc304e52841ca3efdb522/cmd/skaffold/app/cmd/commands.go#L78-L80

Since `NewCmdDebug` is processed after `NewCmdDev`:

https://github.com/GoogleContainerTools/skaffold/blob/86b4fde68f9b1530f09fc304e52841ca3efdb522/cmd/skaffold/app/cmd/cmd.go#L124-L128

the `debug` defaults win and so the `dev` integration tests fail as auto-{build/deploy/sync} are disabled.

For now I'll change `CmdNewDebug` to instead record these values locally and then overwrite the `opts.Auto*` values in the `doDebug()`, but it seems awkward.

**Comment by briandealwis** [comment]
This seems inherent to `pflags`: [`BoolVarP()` uses `newBoolValue()`](https://github.com/GoogleContainerTools/skaffold/blob/86b4fde68f9b1530f09fc304e52841ca3efdb522/vendor/github.com/spf13/pflag/bool.go#L55) to allocate a container to map the provider pointer to the default value, and [`newBoolValue()` immediately assigns the value](https://github.com/GoogleContainerTools/skaffold/blob/86b4fde68f9b1530f09fc304e52841ca3efdb522/vendor/github.com/spf13/pflag/bool.go#L15-L18).

```go
// BoolVarP is like BoolVar, but accepts a shorthand letter that can be used after a single dash.
func (f *FlagSet) BoolVarP(p *bool, name, shorthand string, value bool, usage string) {
	flag := f.VarPF(newBoolValue(value, p), name, shorthand, usage)
	flag.NoOptDefVal = "true"
}
```

```go
func newBoolValue(val bool, p *bool) *boolValue {
	*p = val
	return (*boolValue)(p)
}
```

**Comment by dgageot** [comment]
@briandealwis yes, it's caused by `pflags` strange behaviour. Any idea how we could fix that on the Skaffold side?

**Comment by briandealwis** [comment]
See #4089. I’ve started on a fix for pflags, but it’s a laborious chore.

**Comment by dgageot** [comment]
@briandealwis can this be closed?
