### ISSUE TITLE
Document connection guarantees for portforwarding and debugging

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#4136]
We should document on https://skaffold.dev/docs/pipeline-stages/port-forwarding/ and/or https://skaffold.dev/docs/references/api what each event guarantees in terms of connection - for example do we expect clients to retry connections after a portforwarding event is received? Can IDEs rely on debug events or should they use portforwarding events? How does this change with and without status-check?

**Comment by tejal29** [comment]
This should be part of #6122 where we should ask users to specify port-forwarding as a recommendation.

This is no longer needed.
