### ISSUE TITLE
Rebuilding on key press using --trigger=manual is not stable

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [GoogleContainerTools/skaffold#4139]
### Expected behavior

When `skaffold` is executed and set to rebuild on key press
```
skaffold dev --trigger=manual
```
it rebuilds on key press.

### Actual behavior

At first, I thought that rebuilding isn't working when `--tail=true` is specified. It turned out to be false.

Next, I suspected `--port-forward` is messing up. As in some cases
> Press any key to rebuild/redeploy the changes

message showed up after `Port forwarding ...` messages, in others - before. But it anyway turned out not to be the case, too.

It seems to be just randomly working/stopping to work. I've ran into a case once when first rebuild worked (on key press), but the subsequent did not. I don't see a clear pattern here. For the last 20+ attempts I didn't manage to get rebuilding on key press working at all.

### Information

- Skaffold version: 1.9.1 (but behaves similarly using 1.8.0 too)
- Operating system: macOS Catalina
- Contents of skaffold.yaml: n/a

### Steps to reproduce the behavior

1. Run multiple attempts of
    ```
    skaffold dev --trigger=manual
    ```
   trying to rebuild a few times.

**Comment by stanislav-zaprudskiy** [comment]
Some additional environment information:
* iTerm Build 3.3.9 / Terminal Version 2.10 (433)
* Bash
    ```
    $ bash --version
    GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin19.0.0)
    ```

**Comment by dgageot** [comment]
@stanislav-zaprudskiy Hitting a key only triggers something if there's a file change. Did you change files?

**Comment by stanislav-zaprudskiy** [comment]
This is indeed true - there should be some changed files for manual trigger to work. Thank you for explanation!.
