### ISSUE TITLE
Skaffold is not terminating processes with RPC connections

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#4144]
Likely a regression due to:
https://github.com/GoogleContainerTools/skaffold/pull/4010

When clients make an grpc connection to Skaffold's event api, normal Skaffold termination (via `ctr+c` / SIGINT) is does not terminate the Skaffold process resulting in orphaned processes.

To reproduce:
- Start a Skaffold dev session in the IntelliJ
- Hit the `stop` button

Expected: Skaffold process is terminated
Actual: The IDE fails to terminate the skaffold process without a forced termination, and the Skaffold process remains orphaned:

![image](https://user-images.githubusercontent.com/1735744/81572359-1e782800-9371-11ea-9a81-fec81131b8dd.png)
(example shown with 2 skaffold dev sessions, each with orphaned processes after hitting the stop button)

**Comment by etanshaul** [comment]
@nkubala @balopat 

This is from our chat late last week. Filing the issue for tracking. This is a blocker for the IDEs upgrading to `1.9.1` assuming we conclude that it is indeed Skaffold's responsibility to terminate the process under these conditions (which I _think_ it is).

**Comment by dgageot** [comment]
This is fixed with https://github.com/GoogleContainerTools/skaffold/pull/4148. We reverted the graceful shutdown code.
