### ISSUE TITLE
skaffold dev --default-repo removes service colors from the output

### ISSUE THREAD

**Issue by matti** [GoogleContainerTools/skaffold#4164]
version 1.9.1 (also tested with 1.8.0)
```
$ skaffold dev -p myprofile
```
![image](https://user-images.githubusercontent.com/3893/81828383-6bf7bf00-9542-11ea-9e54-7ff877aa4c45.png)

```
$ skaffold dev --default-repo myrepo.mydomain.com
```
![bin_amp_and_Lens](https://user-images.githubusercontent.com/3893/81828292-508cb400-9542-11ea-9b8c-2b49b356b98a.png)

**Comment by dgageot** [comment]
I can reproduce. Let me take a look
