### ISSUE TITLE
How to combine kubectl and helm deployments during init?

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4231]
Hi
while playing with some deployment setup question came up:

How could be kubectl and helm deployment combined in on skaffold.yaml, especially during init phase?
any example is appreciated.
regards
Marco

**Comment by MarcoSchaar** [comment]
btw. while testing new release 1.10. at windows:
skaffold-windows-amd64.exe is not working

**Comment by tstromberg** [comment]
@MarcoSchaar - The latter is #4234

**Comment by nkubala** [comment]
hey @MarcoSchaar, skaffold supports multiple deployers specified in the skaffold.yaml so there's no reason in theory why you couldn't combine kubectl and helm deployments together. just specify each component along with its configuration in your skaffold.yaml as a separate deployer and things should just work:

```
deploy:
  helm:
    releases:
    - name: my_release
       chartPath: charts/
  kubectl:
    manifests:
      - deployments/*.yaml
```

as for `skaffold init`, we only support automatically bootstrapping single deployer projects, and only ones setup with kubectl or kustomize - helm configuration is too vague for us to be able to infer the relevant project details for you, as would be the case for multiple deployer scenarios. it's not impossible, but we're not prioritizing it at the moment.

hopefully this answers your question! i'll close this issue for now, feel free and follow up though if you have more questions.

**Comment by tejal29** [comment]
closed as https://github.com/GoogleContainerTools/skaffold/issues/7300
