### ISSUE TITLE
Using kustomize buildin in kubectl breaks compatibility with kustomize 3.X features

### ISSUE THREAD

**Issue by KptMarchewa** [GoogleContainerTools/skaffold#4232]
### Expected behavior

Skaffold will continue working with kustomize 3.X features if I have kustomize binary in PATH.

### Actual behavior

Skaffold forces using outdated kubectl version of kustomize

### Information

- Skaffold version: version 1.10
- Operating system: OS X 10.15.4

This problem with buildin kustomize is relevant to me
https://github.com/kubernetes-sigs/kustomize/issues/1373#issuecomment-618439078

**Comment by niklasbuechner** [comment]
I have unfortunately the same problem. We have been using kustomize `v3.5.4` which now fails. Is there a workaround available?

**Comment by KptMarchewa** [comment]
@niklasbuechner my workaround is to downgrade to 1.9.1.

**Comment by nkubala** [comment]
i broke this in https://github.com/GoogleContainerTools/skaffold/pull/4183. i'm going to revert this change for now and do a hotfix release until we can figure out how to properly address this. sorry for the inconvenience 😞
