### ISSUE TITLE
v1.10.0 binaries released for macOS & Windows are actually ELF 64-bit binaries (Linux)

### ISSUE THREAD

**Issue by pcracknell** [GoogleContainerTools/skaffold#4234]
I am trying to run v1.10.0 release on Mac

### Expected behavior
Execute skaffold and be presented with help information

### Actual behavior
`bash: ./skaffold-darwin-amd64: cannot execute binary file`

### Information

- Skaffold version: v1.10.0
- Operating system: Mac OSX 10.14.6

### Steps to reproduce the behavior

1. Follow release [instructions](https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.10.0) for Mac
2. `skaffold`

**Comment by ncthbrt** [comment]
I'm experiencing a similar issue on Windows as well (#4235 )

**Comment by tstromberg** [comment]
Thank you for the heads up. I'll attempt to reproduce.

**Comment by tstromberg** [comment]
This also affects Windows.
