### ISSUE TITLE
v1.10.0 on Windows: The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by ncthbrt** [GoogleContainerTools/skaffold#4235]
After downloading the v1.10.0 [win amd64 binary](https://storage.googleapis.com/skaffold/releases/v1.10.0/skaffold-windows-amd64.exe), I attempted to run it via the cli as per usual, and received the following error message:

```
Program 'skaffold.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ skaffold.exe
+ ~~~~~~~~~~~~.
At line:1 char:1
+ skaffold.exe
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
I downloaded a fresh binary again to ensure that it wasn't simply a network issue, and got the same problem

**Comment by tstromberg** [comment]
Thank you for the heads up. I'll attempt to reproduce.

**Comment by tstromberg** [comment]
This is the same issue as #4234
