### ISSUE TITLE
Typescript sample project

### ISSUE THREAD

**Issue by pierreyves-lebrun** [GoogleContainerTools/skaffold#4261]
Are there any guidelines for setting up a TypeScript project based on Skaffold?

I am especially interested in how to setup VSCode for debugging my TypeScript project.

**Comment by tejal29** [comment]
We dont have anything right now. Team will definitely look into it.

**Comment by aryanPatilhm2** [comment]
Hii @pierreyves-lebrun, did you find any way to debug the typescript app through Skaffold?? Currently, I am mounting the container's build folder to my local build folder. But it's not the correct way.

**Comment by pierreyves-lebrun** [comment]
> Hii @pierreyves-lebrun, did you find any way to debug the typescript app through Skaffold?? Currently, I am mounting the container's build folder to my local build folder. But it's not the correct way.

I had to give up as Skaffold team doesn’t understand the concept of development containers.

In comparison, alternative solutions such as Okteto or Devspace support it pretty much  out of the box:
https://okteto.com/blog/remote-kubernetes-development/
https://devspace.sh/cli/docs/introduction

**Comment by tejal29** [comment]
@pierreyves-lebrun Sorry we were unable to get your request earlier. 
We are a small team trying our best to make container development easy for developers for all.
There is a possibility we lack support for some languages however that does not demonstrate the overall ability of the team to understand the given space.

We welcome constructive feedback and appreciate if you have any.

Please refer to our [Code Of Conduct Policy](https://github.com/GoogleContainerTools/skaffold/blob/da0ce3ba4b2bd64843a4e767a79fb2f3c3ef6a1d/CODE_OF_CONDUCT.md)

**Comment by ErolPeel** [comment]
Is there just no example project for TypeScript, or is debugging with TypeScript in general currently not possible?
