### ISSUE TITLE
Links not loading ...

### ISSUE THREAD

**Issue by ankumar** [GoogleContainerTools/skaffold#4276]
<img width="669" alt="Screen Shot 2020-05-28 at 3 26 35 PM" src="https://user-images.githubusercontent.com/658791/83200293-dcccd880-a0f7-11ea-9731-67ad59eed8d3.png">

### Expected behavior

Visited this site the first time ...

### Actual behavior

Screenshot attached

### Steps to reproduce the behavior

Mac/Browsers: Chrome & Safari, **loads fine on mobile**
 
Links: 
1. https://skaffold.dev/
2. https://skaffold.dev/docs/install/

**Comment by balopat** [comment]
That is very odd, can you share the certificate details that you see? And - if you don't mind - your location where you're trying to access it? 

From California it looks like this: 

![image](https://user-images.githubusercontent.com/635073/83281708-58c53000-a18d-11ea-9f90-70ecf03eac76.png)

**Comment by balopat** [comment]
As I don't see a large number of replies here, I'm going to assume that this was a temporary error somewhere - maybe in Firebase?. Closing out. Please let us know if it comes up again!
