### ISSUE TITLE
Incorrect version of skaffold pushed to 1.11.0 release for windows-amd64

### ISSUE THREAD

**Issue by erulabs** [GoogleContainerTools/skaffold#4317]
### Expected behavior
> curl -sL https://github.com/GoogleContainerTools/skaffold/releases/download/v1.11.0/skaffold-windows-amd64.exe -o skaffold && ./skaffold version
v1.11.0

### Actual behavior
> curl -sL https://github.com/GoogleContainerTools/skaffold/releases/download/v1.11.0/skaffold-windows-amd64.exe -o skaffold && ./skaffold version
v1.10.1

### Information
It seems like the incorrect binary was pushed to the 1.11.0 tag for windows? I have not checked builds for other O/Ses but will probably be able to find out in a few hours.

Edit: It appears to be simply the wrong binary v1.11.0 in all cases. Presumably @nkubala might want to know about this. Might be a nice new github action - build and upload new binaries on release!

**Comment by mackenzie-orange** [comment]
It's hard to tell, but it seems like 1.11.0 for windows didn't release at all. It errors when I try to run it against examples using `apiVersion: skaffold/v2beta5`, which suggests that it does not know how to parse that schema.

**Comment by stanislav-zaprudskiy** [comment]
The same issue for darwin version:
```
$ curl -L https://github.com/GoogleContainerTools/skaffold/releases/download/v1.10.1/skaffold-darwin-amd64.sha256
90ba9fb0c322946e5f32f4d815f79de6147aea3e59cd992a9ba16e679428831e  out/skaffold-darwin-amd64
$ curl -L https://github.com/GoogleContainerTools/skaffold/releases/download/v1.11.0/skaffold-darwin-amd64.sha256
90ba9fb0c322946e5f32f4d815f79de6147aea3e59cd992a9ba16e679428831e  out/skaffold-darwin-amd64
```

**Comment by steinwelberg** [comment]
The same for the linux version

**Comment by nkubala** [comment]
@erulabs thanks for pointing this out and thanks everyone for verifying on other platforms. I accidentally uploaded the wrong binaries when doing the release last week, which of course had to happen after the last two botched releases as well....it should be fixed now, but I'm quite unhappy with the amount of manual steps in our release process and how much possibility for human error there is. we'll be working this cycle to introduce some automation in our release to ensure that this doesn't happen again, and I really apologize for the inconvenience this might have caused!

**Comment by erulabs** [comment]
Not a biggie @nkubala - we appreciate the hard work! Thank you!
