### ISSUE TITLE
Fully automate release process

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4324]
our release process has way too many manual steps, which introduces all kinds of possibilities for human error (e.g. https://github.com/GoogleContainerTools/skaffold/issues/4317). some improvements we could make:

* use labels on all PRs to categorize them as "New Features", "Fixes and Improvements", "Docs Updates", or "None". we could then have a bit of logic to filter on each of these in our release script, which would make the generation of the patch notes completely automatic
* use a Github action or something similar to retrieve the built binaries from our GCS bucket and upload them to the Github release
* use a Github action to generate the release itself on Github

I think the only step that we'll actually need to do ourselves is simply push the new tag upstream. everything else can be triggered automatically.

**Comment by gsquared94** [comment]
PR #4325 should fix point 2 and 3 above.

**Comment by gsquared94** [comment]
PR merge inadvertently closed the issue. Point 1 is still pending.

**Comment by nkubala** [comment]
i'll close this since we've come a long way and our release process seems mostly satisfactory.
