### ISSUE TITLE
[FR] Different skaffold exit codes

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#4348]
It looks like `skaffold init` can fail in a few ways.

1. Project has no Kubernetes resources. `skaffold init` fails with `one or more Kubernetes manifests are required to run skaffold` and exit code `1`.
2. Project has no build configuration (no Dockerfile). `skaffold init` fails with `one or more valid builder configuration (Dockerfile or Jib configuration) must be present to build images with skaffold; please provide at least one build config and try again or run skaffold init --skip-build` and exit code `1`.

Is there a way to differentiate between these two error conditions without parsing the error message? If different exit codes were returned for different error conditions, this would help the IDEs in displaying different UI for each error condition.

**Comment by dgageot** [comment]
@tejal29 Do you have an idea on how to implement this with what you've already done on errors? Otherwise, I'm happy to give it a shot

**Comment by tejal29** [comment]
@dgageot i have done no work in `skaffold init` error codes. Please feel free to take this.
