### ISSUE TITLE
FR: Ability to combine tagging policies

### ISSUE THREAD

**Issue by felixtran39** [GoogleContainerTools/skaffold#4371]
This is a feature request.

I would like to expand on Skaffold's tagging policies by adding a new one which is able to combine pre-existing tagging policies together. For example, I want to be able to combine dateTime and gitCommit as my tagging policy and have it follow this template "{dateTime}-{gitCommit}".

**Comment by tstromberg** [comment]
Thank you for the feature request. I'm flagging this for discussion next week.

**Comment by nkubala** [comment]
@felixtran39 seems reasonable to me.
