### ISSUE TITLE
skaffold init --analyze builder detection for Java heuristic needs improvement

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#4378]
### Expected behavior

The Cloud Code java Cloud Run sample does not work out of the box with skaffold buildpack builders, and it is unclear how a Java project needs to be architected to cause skaffold to detect buildpacks as a builder.

https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-cloud-run-hello-world
For example, if I leave everything as is, Docker and Jib are the detected builders, but if I move the pom.xml file to /src, Buildpacks and Docker are the detected builders. I would expect that all 3 are valid builders.

### Information

- Skaffold version: version e03e4d8
- Operating system: macOS 10.15.4

**Comment by dgageot** [comment]
This is indeed a bug
