### ISSUE TITLE
Bash for Windows: fatal error: runtime: netpoll failed

### ISSUE THREAD

**Issue by bjornmagnusson** [GoogleContainerTools/skaffold#439]
### Expected behavior
Executing skaffold without arguments should show help output
A tool that facilitates continuous development for Kubernetes applications.

Usage:
  skaffold [command]

Available Commands:
  completion  Generate shell completion scripts
  dev         Runs a pipeline file in development mode
  docker      A set of commands related to developing with docker
  fix         Converts old skaffold.yaml to newest schema version
  help        Help about any command
  run         Runs a pipeline file
  version     Print the version information

Flags:
  -h, --help               help for skaffold
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

Use "skaffold [command] --help" for more information about a command.

### Actual behavior
skaffold
runtime: epollwait on fd 5 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x1565e8c, 0x17)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x34342fba9ba00, 0xc400000000)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
        /usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
regexp/syntax.(*parser).appendGroup(0xc4200cd560, 0xc420227620, 0x0, 0x2, 0x1, 0x1f4e8c0, 0x8, 0x8, 0x14e2fc0, 0x1fd5f01, ...)
        /usr/local/go/src/regexp/syntax/parse.go:1414 +0x245
regexp/syntax.(*parser).parsePerlClassEscape(0xc4200cd560, 0x155d089, 0x10, 0xc420227620, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/regexp/syntax/parse.go:1390 +0x126
regexp/syntax.(*parser).parseClass(0xc4200cd560, 0x155d088, 0x11, 0xc42013fa28, 0x20, 0x30, 0xc420212630)
        /usr/local/go/src/regexp/syntax/parse.go:1584 +0x2fb
regexp/syntax.Parse(0x155d088, 0x11, 0xd4, 0xa0, 0xc420215400, 0x0)
        /usr/local/go/src/regexp/syntax/parse.go:774 +0xcc1
regexp.compile(0x155d088, 0x11, 0xc4200000d4, 0xc42029fba8, 0x50052d, 0xc420212600)
        /usr/local/go/src/regexp/regexp.go:170 +0x4f
regexp.Compile(0x155d088, 0x11, 0x0, 0x500321, 0x0)
        /usr/local/go/src/regexp/regexp.go:133 +0x41
regexp.MustCompile(0x155d088, 0x11, 0x0)
        /usr/local/go/src/regexp/regexp.go:238 +0x4d
github.com/GoogleCloudPlatform/skaffold/vendor/github.com/docker/distribution/reference.expression(0xc4200b8708, 0x1, 0x1, 0x7e)
        /go/src/github.com/GoogleCloudPlatform/skaffold/vendor/github.com/docker/distribution/reference/regexp.go:115 +0x94
github.com/GoogleCloudPlatform/skaffold/vendor/github.com/docker/distribution/reference.anchored(0xc4200b8708, 0x1, 0x1, 0xc4202152c0)
        /go/src/github.com/GoogleCloudPlatform/skaffold/vendor/github.com/docker/distribution/reference/regexp.go:142 +0x43
### Information

```
Skaffold version: 0.4.0
Operating system: Windows, using Bash for Windows
Kubernetes environment: Docker for Windows 18.04

### Steps to reproduce the behavior

  1. Install Linux binaries in Bash for Windows
  2. Execute skaffold without arguments (skaffold)

**Comment by r2d4** [comment]
Can you try this again @bjornmagnusson? I wasn't able to reproduce it.

**Comment by bjornmagnusson** [comment]
Sure thing, will give it another go and post results here.

**Comment by bjornmagnusson** [comment]
OK, seems to be working now with respect of this issue.
Tried with version 0.7.0
