### ISSUE TITLE
`debug` detect direct processes with `/bin/sh -c ...`

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#4397]
### Expected behavior

Similar to what was done in #4345, but the general case that works for docker builds as well.

### Actual behavior

Debug events are not sent when the Dockerfile CMD or ENTRYPOINT contains `/bin/sh -c ...`

Something like
```dockerfile
ENTRYPOINT [ "/bin/sh", "-c" ]
CMD [ "python -m ptvsd --port 3000 --host 0.0.0.0 manage.py runserver 0.0.0.0:8080 --noreload" ]
```

### Information

- Skaffold version: version 4c2ea7c
- Operating system: macOS 10.15.4

**Comment by briandealwis** [comment]
We'd see this with a normal dockerfile like:
```
CMD python -m ptvsd --port 3000 --host 0.0.0.0 manage.py runserver 0.0.0.0:8080 --noreload
```

which will be turned by Docker into
```
"cmd":  ["/bin/sh", "-c", "python -m ptvsd --port 3000 --host 0.0.0.0 manage.py runserver 0.0.0.0:8080 --noreload"]
```

Handling `/bin/sh -c` as an entrypoint launcher like in @j-windsor's example is really no different.

**Comment by briandealwis** [comment]
Bumping priority since it's holding back some of the cloud-code-samples
