### ISSUE TITLE
Change default values/Remove `-XX*` flags from `skaffold init`

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#4401]
I wonder if it would be safe to enable `--XXenableBuildpacksInit`,  `--XXenableJibInit`, `--XXenableJibGradleInit`,  `--XXenableNewInitFormat` by default for `skaffold init`?

What would be the impact of that?

Could some of those flags even be removed?

**Comment by dgageot** [comment]
@matthewmichihara wdyt?

**Comment by matthewmichihara** [comment]
Would need to confirm for sure with testing, but on the IntelliJ side, I think all of those should be safe to to enable by default and remove except for `--XXenableJibGradleInit`.

For `--XXenableJibGradleInit`, we assume it is false and only set it to true if the right conditions are met, so enabling it by default would require a change on the plugin side.

**Comment by nkubala** [comment]
@matthewmichihara @dgageot how can we coordinate that change? I'd love to pull the trigger on this if we can

**Comment by matthewmichihara** [comment]
I think last we chatted, @dgageot was gonna create a build with the flags enabled by default (except --XXenableJibGradleInit) to do some testing with in IJ/VSC.

**Comment by gsquared94** [comment]
any update on this?
