### ISSUE TITLE
Question about node selectors, affinity and tolerations

### ISSUE THREAD

**Issue by adjavaherian** [GoogleContainerTools/skaffold#4409]
I'm looking at a few different docs and examples and I can't seem to find a succinct example of applying a toleration or selector when defining a kaniko arg spec.  Basically, I want to schedule kaniko pods (via skaffold) with tolerations for taints which are in place on some nodes.  I'm wondering if this is even possible?

### Information

- Skaffold version:  > v1.4
- Operating system: k8s

**Comment by briandealwis** [comment]
Ho @adjavaherian.  We added the ability to add [tolerations](https://skaffold.dev/docs/references/yaml/#build-cluster-tolerations) to the `cluster` environment (for Kaniko) in Skaffold 1.12.
