### ISSUE TITLE
Functionality not covered by integration tests

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#441]
An umbrella issue with the functionality not covered by integration tests. These items should be verified manually.

Examples not covered by integration tests

- [x] ./skaffold.yaml
- [x] examples/kaniko
- [x] examples/bazel
- [x] examples/helm
- [x] examples/microservices
- [x] examples/jib
- [x] examples/nodejs
- [x] examples/structure-tests

Commands not covered by integration tests

- [x] skaffold dev
- [x] skaffold build
- [x] skaffold deploy
- [x] skaffold delete
- [ ] skaffold completion

**Comment by dgageot** [comment]
I'm going to close this one because all of them are covered (except skaffold completion that I'll cover with unit tests)
