### ISSUE TITLE
Docker Hub has enabled rate limit -> CI is failing a lot

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#4432]
Integration tests are failing a lot because of 429 errors coming from the Docker hub.

See https://docs.docker.com/docker-hub/download-rate-limit/

Here's an example: https://travis-ci.com/github/GoogleContainerTools/skaffold/jobs/356484962

**Comment by dgageot** [comment]
[log.txt](https://github.com/GoogleContainerTools/skaffold/files/4859490/log.txt)

**Comment by binman-docker** [comment]
Hey David, long time no see! I'm not sure how Travis handles their infrastructure; if they use a small handful of public IPs for all of their worker nodes, that may explain why you're hitting this. If the worker node has it's own public IP that would mean your builds are pulling a bunch of images, which is probably unlikely.

Either way, the fix should be pretty simple. The pull request just needs to be authenticated with a Docker Hub login (this is to prevent abuse from anonymous IPs). This Travis documentation deals with authenticating for pushes, but it should work the same for pulls I think: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

**Comment by dgageot** [comment]
Thanks @binman-docker.
I guess they do have a small handful of public IPs.
The one issue that we have is that all of our PRs to skaffold come from forks so none of them can have login/pwd injected

**Comment by dgageot** [comment]
https://docs.travis-ci.com/user/ip-addresses/

**Comment by binman-docker** [comment]
Ah yeah we're dealing with similar issues regarding forks in Github Actions.

Give us a couple hours to dig into it. We'll get you unblocked (at least temporarily) ASAP.

**Comment by binman-docker** [comment]
Hey @dgageot - we've temporarily added Travis IPs to an override list so you should be good now. 

Our product team will reach out to the folks at Travis to work on a more long-term solution.

**Comment by dgageot** [comment]
Awesome! Thanks @binman-docker and @jeanlaurent

**Comment by nkubala** [comment]
reopening this because we're hitting it very frequently in CI again.

**Comment by tejal29** [comment]
@nkubala shd we close this now or atleast reduce the priority to p1 if we are not actively working on it.

**Comment by nkubala** [comment]
we've mitigated this for now, so let's close this until we start seeing it again
