### ISSUE TITLE
Python Debugger Should Support debugpy and ptvsd 

### ISSUE THREAD

**Issue by cpvandehey** [GoogleContainerTools/skaffold#4437]
### Expected behavior
Currently `ptvsd` is the only DAP supported by `skaffold` for python apps. Microsoft is deprecating `ptvsd` for `debugpy` -- [debugpy link](https://github.com/microsoft/debugpy). `debugpy` has a lot of the bug fixes revolving around debugging multiprocess python applications that `ptvsd` does not have ([the press release is here](https://visualstudiomagazine.com/articles/2020/03/20/vs-code-python-debugger.aspx)). `skaffold` should consider making the debug package configurable or converting over to `debugpy` exclusively once it gets out of beta (_or even now for that matter_).

In the meantime, I will be inserting the command arguments manually in order to use `debugpy` locally and specifying a debug port in the portForwarding section (replacing `skaffold debug` for now with a manual process -- e.g. `"-m", "debugpy", "--listen", "0.0.0.0:5000",...`).

- Skaffold version: latest
- Operating system: mac
- Contents of skaffold.yaml: n/a

**Comment by briandealwis** [comment]
Needs to be coordinated with GoogleContainerTools/container-debug-support

**Comment by cpvandehey** [comment]
Let me know if I need to file this ticket somewhere else or notify anyone

**Comment by briandealwis** [comment]
GoogleContainerTools/container-debug-support#42

**Comment by briandealwis** [comment]
Will get to this in August.

**Comment by cpvandehey** [comment]
Any update @briandealwis ?

**Comment by tejal29** [comment]
@briandealwis looks like this should be closed now?

**Comment by briandealwis** [comment]
Not yet: I've added debugpy to the duct-tape images (still needs to be regenerated), but I need to fix `debug` to reference debugpy now.

**Comment by cpvandehey** [comment]
Thank you all. Let me know how I can follow the relevant release for this.

**Comment by briandealwis** [comment]
It looks like we can rewrite `gunicorn` command-lines as `python -m debugpy --listen :PORT -m gunicorn.app.wsgiapp`.
