### ISSUE TITLE
Fetching the gcr.io/buildpacks/builder:v1 image should not require being logged in to gcloud

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#4447]
macOS 10.15.5

In https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world with a modified `skaffold.yaml` that uses buildpacks as the builder (shown below), I tried to run `skaffold dev` and got an error fetching the `gcr.io/buildpacks/builder:v1` image due to not being logged in to `gcloud`. I expected this to not require being logged in.

From @dgageot: `Skaffold is trying to use gcloud auth automatically without the user having to configure it. But it’s maybe too aggressive`

```
$ skaffold version
v1.12.0
$ gcloud version
Google Cloud SDK 289.0.0
alpha 2020.02.25
app-engine-java 1.9.79
app-engine-python 1.9.90
beta 2020.02.25
bq 2.0.56
cloud-datastore-emulator 2.1.0
core 2020.04.10
gsutil 4.49
minikube
skaffold
$ gcloud auth list

No credentialed accounts.

To login, run:
  $ gcloud auth login `ACCOUNT`
apiVersion: skaffold/v2beta5

$ pwd
/Users/michihara/Code/cloud-code-samples/java/java-hello-world
$ cat skaffold.yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: java-hello-world
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
$ skaffold dev
Listing files to watch...
 - java-hello-world
Generating tags...
 - java-hello-world -> java-hello-world:latest
Checking cache...
 - java-hello-world: Not found. Building
Found [docker-desktop] context, using local docker daemon.
Building [java-hello-world]...
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
exiting dev mode because first build failed: couldn't build "java-hello-world": failed to fetch builder image 'gcr.io/buildpacks/builder:v1': error getting credentials - err: exit status 1, out: ``
```

**Comment by dgageot** [comment]
So, here's what happens:
+ `pack`'s code is trying to pull the image
+  I guess you have `gcloud` configured as a `credHelper` in `~/.docker/config.json`
+ But `gcloud` is not logged in

Since `gcloud` is configured as a credential helper, it's normal that docker tries to generate credentials and it's normal that it fails. 

You should see the exact same behaviour if you run `docker pull gcr.io/buildpacks/builder:v2`. Can you confirm?

**Comment by matthewmichihara** [comment]
yes i think you are right --

```
$ docker pull gcr.io/buildpacks/builder:v2
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Error response from daemon: manifest for gcr.io/buildpacks/builder:v2 not found: manifest unknown: Failed to fetch "v2" from request "/v2/buildpacks/builder/manifests/v2".

$ cat ~/.docker/config.json
{
  "experimental" : "disabled",
  "credHelpers" : {
    "marketplace.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "us.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "gcr.io" : "gcloud"
  },
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/19.03.8 (darwin)"
  },
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  }
}
```

**Comment by dgageot** [comment]
I'm afraid there's not much we can do

**Comment by matthewmichihara** [comment]
Any insight on if there's anything we can change on our end here? From what I understand, for many other cases, having `gcloud` as the credential helper is needed so that we can do things like push built images to `gcr.io` or deploy to GKE clusters.

**Comment by ivanporty** [comment]
What would happen if gcloud not installed at all on the machine? Will docker be able to pull the buildpacks image then?

**Comment by ivanporty** [comment]
@dgageot Would you say gcloud credential helper could improve itself here? For public images (which I assume buildpack image is publicly available to anyone pulling it), should they require authentication at all?

**Comment by dgageot** [comment]
The issue is on docker’s side. It eagerly fetches the authentication
information based on the image prefix and the helpers declared for that
prefix.
