### ISSUE TITLE
Gaps in Cloud Run locally output

### ISSUE THREAD

**Issue by jmah-cc** [GoogleContainerTools/skaffold#4449]
From cloud-code-vscode-internal created by [vincentjocodes](https://github.com/vincentjocodes): GoogleCloudPlatform/cloud-code-vscode-internal#2680  

Repro steps
1) New Application: Cloud Run
2) Select the Node.js example
3) Run `Run on Cloud Run Emulator`
4) See that there are gaps in the output:

![image](https://user-images.githubusercontent.com/13400593/86640419-24fcd780-bf8f-11ea-82d1-cb3f2fd30b41.png)

**Comment by dgageot** [comment]
I don't really understand why this issue in opened on Skaffold. Do you have clues that make you think this happens because of Skaffold? As far as I can tell, none of the output comes directly from Skaffold.

**Comment by nkubala** [comment]
i don't think this is coming from skaffold, all of these messages are coming from the event API which is being consumed by the client. i'm gonna close this, but reopen it if you still think it's something wrong on our end.
