### ISSUE TITLE
gLinux Skaffold outputs many deployment in progress events, which floods VSCode logs

### ISSUE THREAD

**Issue by jmah-cc** [GoogleContainerTools/skaffold#4450]
From cloud-code-vscode-internal created by [j-windsor](https://github.com/j-windsor): GoogleCloudPlatform/cloud-code-vscode-internal#2682  

![Screen Shot 2020-07-06 at 3 09 52 PM](https://user-images.githubusercontent.com/554839/86654559-e40ac000-bf9a-11ea-89a9-d76d52c84d34.png)
![Screen Shot 2020-07-06 at 3 10 08 PM](https://user-images.githubusercontent.com/554839/86654567-e53bed00-bf9a-11ea-89e7-e2a8a428471c.png)

**Comment by dgageot** [comment]
Bumping the priority since it's a waste of screen real estate

**Comment by vincentjocodes** [comment]
@marlon-gamez @tejal29 

Any updates on this? Thanks!

**Comment by MarlonGamez** [comment]
@vincentjocodes sorry, I'm actually not working on this now, but forgot to remove myself from assignees

**Comment by vincentjocodes** [comment]
@marlon-gamez No problem, do you know if Tejal still taking this on?

**Comment by tejal29** [comment]
Thanks @vincentjocodes for pinging me. I am going to re-evaluate all the output statuses and the frequency of when the events needs to shown. 
e.g. 
1. what statuses are important and worth notifying about
2. If we do identify nothing interesting happened, what is reasonable amount of time to wait until we show some output
3. do events also need to apply the same rule?

I am going to write some mock streams or output lines and then make changes accordingly.
