### ISSUE TITLE
Publish Skaffold API proto libraries

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4461]
We should publish easy-to-consume API libraries generated from our proto definition for downstream consumers:
  - could publish a Java library on Maven Central?
  - an npm package suitable for use from Typescript

**Comment by tejal29** [comment]
@briandealwis we decided to not do prioritize this for internal deploy debug success metrics effort as it would be hard a lot of work for very little gain.
Closing this. please feel free to re-open
