### ISSUE TITLE
Is there a way to pass a helm binary path for skaffold?

### ISSUE THREAD

**Issue by AmetPreply** [GoogleContainerTools/skaffold#4462]
Hi.
I've migrating HELM 2 to 3, and want to say to the skaffold to use `/usr/bin/helm3` for deploying new releases instead of `/usr/bin/helm`.

Is there a way to pass a helm binary path for skaffold (maybe it's undocumented feature)? Or the only way is to replace binary file with `sudo cp /usr/bin/helm3 /usr/bin/helm`?

Version:
v0.33.0

**Comment by gsquared94** [comment]
There is currently no way to pass this information in Skaffold. You could try adding an `alias helm` to `/usr/bin/helm3`.
Closing this issue as it is not actionable by Skaffold.
