### ISSUE TITLE
Add ability to suppress status check output when configured

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4516]
depends on #4512

wire up flag/config option to suppress status check output in favor of status.

**Comment by tejal29** [comment]
As part of this work, Identify

- what statuses are important and worth notifying about
- If we do identify nothing interesting happened, what is reasonable amount of time to wait until we show some output
- do events also need to apply the same rule?

Previously, when designing status checks, we decided to show all new status updates every half secons.

after adding pod status health checks, the number of new statuses increases. Not all statuses are interesting like "container creating" or "pod initializing"
we also had a regressions where for deployment waiting for rollout was reported repeatedly.

**Comment by nkubala** [comment]
@tejal29 what follow up work needs to be done here?
