### ISSUE TITLE
Relocate Skaffold debug images from gcr.io/gcp-dev-tools

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4520]
gcp-dev-tools is not obviously associated with Skaffold

See http://go/gcp-dev-tools-acl-pm

----

Short-term plan:
  - [x] Publish helper images to both gcr.io/k8s-skaffold/skaffold-debug-support and gcr.io/gcp-dev-tools/duct-tape
  - [ ] Switch Skaffold to retrieve from gcr.io/k8s-skaffold/skaffold-debug-support

**Comment by tstromberg** [comment]
Yesterday, a 5-hour outage for image access would have likely been prevented if this issue was solved. Escalating the priority.

**Comment by briandealwis** [comment]
Sorry for the delay on this.  Was trying to figure out what should happen with the container-debug-support repo.
