### ISSUE TITLE
Stale responses with services from deployments 

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4522]
When using `skaffold dev`, attempts to fetch from a service via the service port-forward often results in stale data for up to 3-5 seconds after an updated container image has been deployed to replace the old container.  We believe the Service favours directing incoming requests to the old container until it has been terminated.  This staleness is seen on the [cloud-code-samples](https://github.com/GoogleCloudPlatform/cloud-code-samples/) which use [`Service`s of type `LoadBalancer`](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/java/java-hello-world/kubernetes-manifests/hello.service.yaml).

Steps to repeat:
  1. Clone https://github.com/GoogleCloudPlatform/cloud-code-samples
  2. `cd java/java-hello-world && skaffold dev --port-forward`
  3. `while true; do date; curl localhost:4503; sleep 1; done` (or whatever port is mapped)
  4. Make a source change to trigger a redeploy.
  5. Note how long it takes before the new container takes effect.

To investigate: are there any settings to tweak this behaviour?

(Broken out from #4445)

----

~The documentation on [services affinity](https://kubernetes.io/docs/concepts/services-networking/service/) notes:~
> If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting service.spec.sessionAffinity to "ClientIP" (the default is "None"). You can also set the maximum session sticky time by setting service.spec.sessionAffinityConfig.clientIP.timeoutSeconds appropriately. (the default value is 10800, which works out to be 3 hours).

~To investigate whether setting this timeout to a lower value (possibly 0?) would have a favourable result.  It is not clear if this setting applies to Services of type LoadBalancer.~

**Comment by briandealwis** [comment]
FWIW, accessing the service directly shows a similar gap. You can see at 22:26:55 EDT that the endpoint doesn't return a value.
```console
$ kubectl get svc
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
java-hello-world-external   LoadBalancer   10.110.210.205   <pending>     80:32470/TCP   20m
kubernetes                  ClusterIP      10.96.0.1        <none>        443/TCP        5d23h

# recurring is a little utility that runs the command repeatedly and only outputs results when changed
#   -p 1  pauses for 1 second
#   -h    outputs header between runs
#   -i    applies sed to command output to remove Date header (always changing)
$ recurring -p 1 -h '----------' -i '/^Date:/d' -- curl -si http://$(minikube ip):32470
----------
Tue 21 Jul 2020 22:26:39 EDT
HTTP/1.1 200 OK
Content-Type: text/plain;charset=utf-8
Content-Length: 13

Hello World!!

----------
Tue 21 Jul 2020 22:26:55 EDT

----------
Tue 21 Jul 2020 22:26:59 EDT
HTTP/1.1 200 OK
Content-Type: text/plain;charset=utf-8
Content-Length: 12

Hello World.
```

**Comment by briandealwis** [comment]
Aha: https://github.com/kubernetes/kubectl/issues/881 _port-forward to Service always go to first pod_ points to some discussion on https://github.com/kubernetes/kubernetes/issues/15180:

> https://github.com/kubernetes/kubernetes/issues/15180#issuecomment-410798267 **phsiao**: port-forward was originally designed to attach to one pod for debugging and other purpose, the improvement in #59809 was really to help with service discovery so you don't need to lookup the pod name first if you don't care which one you attach to if you have multiple qualifying ones.

> https://github.com/kubernetes/kubernetes/issues/15180#issuecomment-411195533 **mxxk**: [...] it would be great if [the docs] explicitly states that one pod selected by the service is chosen and all traffic is forwarded there for the entire lifetime of the port forward command 🙂

**Comment by briandealwis** [comment]
And further confirmation:
> https://github.com/kubernetes-client/javascript/issues/435#issuecomment-616943448 **brendanburns**: The implementation of port forwarding for a service in `kubectl` simply chooses a pod from that Service's label selector and then port forwards to that pod.

**Comment by briandealwis** [comment]
`kubectl`s [algorithm for selecting a pod from a resource](https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/attachablepodforobject.go#L32) gets the first pod 

I see a couple of options here:
  1. tweak kubectl's service-to-pod selection algorithm;
  2. add support to `kubectl` to take configurable logic in selecting the corresponding pod;
  3. initiate port forwarding directly using the k8s client API within Skaffold (https://github.com/kubernetes/client-go/issues/51), which would allow us to control how wee map a service to a port.

Options 1 and 2 will take some time to roll-out and doesn't help users using older versions of kubectl; it might require that we include our own copy.

**Comment by briandealwis** [comment]
Added some logging to `kubectl`'s `GetFirstPod()` to list the pods that are available when the new `kubectl port-forward` is issues for the service.  At this point, we've built and redeployed the modified image, and the pod container is running.  As can be seen below, the old pod (suffix `4vgkv`) has not yet been terminated.  These [pods are sorted in `attachablePodForObject()`](https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/attachablepodforobject.go#L51-L52) 

	sortBy := func(pods []*corev1.Pod) sort.Interface { return sort.Reverse(podutils.ActivePods(pods)) }
	pod, _, err := GetFirstPod(clientset, namespace, selector.String(), timeout, sortBy)
	return pod, err

But notice the `Reverse()`!   The [ordering function](https://github.com/kubernetes/kubectl/blob/2b775f287352b3191b0e52cc4231941cd8e337bf/pkg/util/podutils/podutils.go#L129) normally sorts [newer pods before older pods (all else being equal)](https://github.com/kubernetes/kubectl/blob/2b775f287352b3191b0e52cc4231941cd8e337bf/pkg/util/podutils/podutils.go#L156-L159):

	// 6. Empty creation time pods < newer pods < older pods
	if !s[i].CreationTimestamp.Equal(&s[j].CreationTimestamp) {
		return afterOrZero(&s[i].CreationTimestamp, &s[j].CreationTimestamp)
	}
	return false

So because of the `Reverse()`, `GetFirstPod()` returns the oldest pod.
```
Deployments stabilized in 2.497553835s
DEBU[0034] getting client config for kubeContext: ``    
Watching for changes...
DEBU[0034] found open port: 4503                        
Port forwarding service/java-hello-world-external in namespace default, remote port 80 -> address 127.0.0.1 port 4503
DEBU[0034] Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s service/java-hello-world-external 4503:80 --namespace default] 
2 attachable pods:
  pod 0: "java-hello-world-57fdf576c5-4vgkv": phase="Running" reason= message=
      condition: {Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:05 -0400 EDT  }
      condition: {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:07 -0400 EDT  }
      condition: {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:07 -0400 EDT  }
      condition: {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:05 -0400 EDT  }
      container: server: {nil &ContainerStateRunning{StartedAt:2020-07-22 15:51:06 -0400 EDT,} nil}
  pod 1: "java-hello-world-5fdfb59786-qskcj": phase="Running" reason= message= 
      condition: {Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:34 -0400 EDT  }
      condition: {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:36 -0400 EDT  }
      condition: {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:36 -0400 EDT  }
      condition: {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-07-22 15:51:34 -0400 EDT  }
      container: server: {nil &ContainerStateRunning{StartedAt:2020-07-22 15:51:35 -0400 EDT,} nil}
```

<details>
<summary>patch to write pods under consideration to /dev/tty</summary>
```diff
diff --git staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
index 762d953f2c..fde1c1a6a8 100644
--- staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
+++ staging/src/k8s.io/kubectl/pkg/polymorphichelpers/helpers.go
@@ -19,7 +19,9 @@ package polymorphichelpers
 import (
 	"context"
 	"fmt"
+	"os"
 	"sort"
+	"syscall"
 	"time"
 
 	appsv1 "k8s.io/api/apps/v1"
@@ -36,6 +38,31 @@ import (
 	watchtools "k8s.io/client-go/tools/watch"
 )
 
+func listPodDeets(tty *os.File, i int, p *corev1.Pod) {
+	tty.WriteString(fmt.Sprintf("  pod %d: %q: phase=%q reason=%v message=%v\n", i, p.ObjectMeta.Name, p.Status.Phase, p.Status.Reason, p.Status.Message))
+	for _, c := range p.Status.Conditions {
+		tty.WriteString(fmt.Sprintf("      condition: %v\n", c))
+	}
+	for _, c := range p.Status.InitContainerStatuses {
+		tty.WriteString(fmt.Sprintf("      initContainer: %s: %v\n", c.Name, c.State))
+	}
+	for _, c := range p.Status.ContainerStatuses {
+		tty.WriteString(fmt.Sprintf("      container: %s: %v\n", c.Name, c.State))
+	}
+}
+
+func listPodsDeets(pods []*corev1.Pod) {
+	tty, err := os.OpenFile("/dev/tty", os.O_RDWR|syscall.O_NOCTTY, 0)
+	if err != nil {
+		return
+	}
+	defer tty.Close()
+	tty.WriteString(fmt.Sprintf("%d attachable pods:\n", len(pods)))
+	for i := 0; i < len(pods); i++ {
+		listPodDeets(tty, i, pods[i])
+	}
+}
+
 // GetFirstPod returns a pod matching the namespace and label selector
 // and the number of all pods that match the label selector.
 func GetFirstPod(client coreclient.PodsGetter, namespace string, selector string, timeout time.Duration, sortBy func([]*corev1.Pod) sort.Interface) (*corev1.Pod, int, error) {
@@ -52,6 +79,7 @@ func GetFirstPod(client coreclient.PodsGetter, namespace string, selector string
 	}
 	if len(pods) > 0 {
 		sort.Sort(sortBy(pods))
+		listPodsDeets(pods)
 		return pods[0], len(podList.Items), nil
 	}
 
@@ -77,6 +105,7 @@ func GetFirstPod(client coreclient.PodsGetter, namespace string, selector string
 	if !ok {
 		return nil, 0, fmt.Errorf("%#v is not a pod event", event)
 	}
+	listPodsDeets([]*corev1.Pod{pod})
 	return pod, 1, nil
 }
 
```
</details>

**Comment by briandealwis** [comment]
The `ActivePods` type, which defines the less-than operation, [notes](https://github.com/kubernetes/kubectl/blob/2b775f287352b3191b0e52cc4231941cd8e337bf/pkg/util/podutils/podutils.go#L123):
```
// ActivePods type allows custom sorting of pods so a controller can pick the best ones to delete.
```

So it's unlikely that kubectl would accept a change to their sort.

**Comment by kschaab** [comment]
Can't we simply change our port forwarding logic to select pods rather than selecting them through the service match?  We are doing so much here already, doesn't skaffold know which pods are coming up and which are older already?  Can match pods based on these specs for the port forward rather than the service?

**Comment by briandealwis** [comment]
Added a fourth option, which is essentially what @kschaab  is suggesting. Will try this today.

**Comment by tejal29** [comment]
> 4\. Make a source change to trigger a redeploy.

is there a reason we don't mark the previous pods for deletion?

**Comment by briandealwis** [comment]
If they come from deployments, it's up to the controller to handle.  In the [case above](https://github.com/GoogleContainerTools/skaffold/issues/4522#issuecomment-662690790), the old pod is still running and hasn't been deleted yet.

**Comment by tejal29** [comment]
> If they come from deployments, it's up to the controller to handle. In the [case above](https://github.com/GoogleContainerTools/skaffold/issues/4522#issuecomment-662690790), the old pod is still running and hasn't been deleted yet.

got it.
