### ISSUE TITLE
skaffold run/dev breaks when built with semver build metadata

### ISSUE THREAD

**Issue by blaggacao** [GoogleContainerTools/skaffold#4535]
- Since skaffold's metdata label is based on a passed-through `skaffold version` tag,
- this implementation causes an issue once the version tag has semver's build metdata appended `+metadata`. 
- This is because `+` does not match against `'(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')` (the label name validation).

```console
$ skaffold version
v1.12.1+k3dv3-patched

$ k3d --version
k3d version v3.0.0
k3s version v1.18.6-k3s1 (default)
```

```log
 - Error from server (Invalid): error when creating "STDIN": Service "ldap-service" is invalid: metadata.labels: Invalid value: "skaffold-v1.12.1+k3dv3-patched": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**[Spec v2.0.0](https://github.com/semver/semver/blob/master/semver.md#semantic-versioning-specification-semver):**
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-].

**Comment by dgageot** [comment]
This is being addressed by https://github.com/GoogleContainerTools/skaffold/pull/4499
