### ISSUE TITLE
Recent docker can provide the digest at the end of build

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#456]
We currently generate a random id to tag a newly built image. That produces some noise that makes tagging process complicated to understand.

Docker versions with api >= 1.30 support returning the images digest ta the end of the build process.
This was done in https://github.com/GoogleContainerTools/skaffold/pull/428 but failed to check the api version.

**Comment by jonjohnsonjr** [comment]
Coming from a registry background: by "digest" here, I thought you were referring to the manifest's digest.

The docker client refers to this as the "Image ID", e.g. running:
```
docker images --digests
```

you can see that `DIGEST` != `IMAGE ID`, and `docker build` is outputting the `IMAGE ID`.

Fun fact: for schema 2 images, the Image ID == the manifest's *config* digest.

I don't mean to bikeshed this too much, but having consistent terminology could avoid some confusion :)

**Comment by dgageot** [comment]
This was implemented in https://github.com/GoogleContainerTools/skaffold/pull/1428
