### ISSUE TITLE
Support k3d final 3.0.0 release

### ISSUE THREAD

**Issue by abatilo** [GoogleContainerTools/skaffold#4569]
Support for k3d was added while v3.0.0 was still being finalized:
https://github.com/GoogleContainerTools/skaffold/commit/20318e7da3cc4db222570a7dffae0bdb4ab52932#diff-f46605d3cb30bca934740c2ea7f5e3f7

It looks like k3d support was added for k3d `v3.0.0-beta.1`:
https://github.com/rancher/k3d/releases/tag/v3.0.0-beta.1

After this version, k3d removed the `k3d load` command for loading the docker images.

I'd like to be able to continue using k3d with skaffold but with the official v3.0.0 release.

**Comment by blaggacao** [comment]
https://github.com/GoogleContainerTools/skaffold/pull/4507

Missing a new release cut, I'd guess

**Comment by abatilo** [comment]
Ah, awesome. So this is right around the corner. Awesome.

**Comment by dgageot** [comment]
It should be out before the end of the month :-) Let's close this issue

**Comment by blaggacao** [comment]
End of month :tada: :smiley_cat:
