### ISSUE TITLE
Allow for setting the deployment name when no manifests are used

### ISSUE THREAD

**Issue by tariq-islam** [GoogleContainerTools/skaffold#457]
Issues without logs and details are more complicated to fix.
Please help us!

### Expected behavior
1. Project has no k8s manifests (pod yaml etc)
2. skaffold dev/run --deploymentname=myapp
3. Skaffold deploys
4. kubectl get deployments
5. Listing shows deployment "myapp"

### Actual behavior
Currently, kubectl dev/run results in all deployments taking on the name of "skaffold" as a non-configurable default.

### Information

```
Skaffold version: version... v0.4.0
Operating system: ... OSX
Content of skaffold.yaml: ...
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/gcp-demo-200100/statefulapp
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:

```

### Steps to reproduce the behavior

1. Project has no k8s manifests (pod yaml etc)
2. skaffold dev/run 
3. Skaffold deploys
4. kubectl get deployments
5. Listing shows deployment "skaffold"
  
Edit: updated steps to reproduce (copy/paste error)

**Comment by dgageot** [comment]
I'm going to close this one because we stopped supporting manifest-less deployments
