### ISSUE TITLE
Tail logs of StatefulSets not working

### ISSUE THREAD

**Issue by blaggacao** [GoogleContainerTools/skaffold#4570]
Coming from https://github.com/GoogleContainerTools/skaffold/issues/3946#issuecomment-663925423

Neither `initContainer` nor normal `container` logs are tailed if they error out.

Please triage.

**Comment by blaggacao** [comment]
I experienced this on a `StatefulSet`.

**Comment by briandealwis** [comment]
@blaggacao I believe this was fixed by #4472  in Skaffold 1.13.0.  Could you please test and verify if this issue is still present?

**Comment by blaggacao** [comment]
Sorry, I think my bad, looks like it's working now, if not, I'm going a better scoped issue.
