### ISSUE TITLE
skaffold.yaml should support configuring the default-repo

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4573]
Some users wish to be able to share deployment-related settings within their skaffold.yaml to be shared across team members.   The currently require new team members to run onboarding scripts to configure their ~/.skaffold/config files for cluster-conditional settings.  We already support specifying `insecureRegistries` and `local-context` (via `build.local.push`).  By including the `default-repo` in `deploy`, users could use profiles to configure where images should be deployed to.

**Comment by saturnism** [comment]
+1, also see #2317

**Comment by briandealwis** [comment]
Duplicate of #2317
