### ISSUE TITLE
status-checks should not disable logging

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4589]
The status checks are wonderful, but as they suppress the logs until the application jas stabilized, it's hard to diagnose problems.

![Screen Shot 2020-07-29 at 3 21 49 PM](https://user-images.githubusercontent.com/202851/88843506-3b253e80-d1af-11ea-9d47-e315e21fe035.png)

IMHO we should always log, and have the status check messages appearing inline.  We should continue to have port-forwarding remaining pending on the status-checks.

**Comment by tejal29** [comment]
@briandealwis we are pulling logs in status check for failed pods when containers are terminated.

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/diag/validator/pod.go#L119

Maybe we need to just do this for more container statuses.
Can you give me a reproducible test case?

**Comment by dgageot** [comment]
Also, the status check can't be interrupted by a code change. So if one breaks the code, it'll take a long time before a new deployment can be made.

**Comment by tejal29** [comment]
> Also, the status check can't be interrupted by a code change. So if one breaks the code, it'll take a long time before a new deployment can be made.

This is only true for 1st skaffold dev. This is something me and @balopat discussed. We felt, we should make 1st `skaffold dev` interruptible.

**Comment by tejal29** [comment]
I don't any errors :(
```
Waiting for deployments to stabilize...
 - deployment/test-app: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/test-app: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/test-app: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/test-app: waiting for rollout to finish: 0 out of 1 new replicas have been updated...
 - deployment/test-app: waiting for rollout to finish: 0 of 1 updated replicas are available...
    - pod/test-app-5f8c595dd7-9kkb8: creating container server
 - deployment/test-app: waiting for rollout to finish: 0 of 1 updated replicas are available...
    - pod/test-app-5f8c595dd7-9kkb8: creating container server
 - deployment/test-app is ready. [1/2 deployment(s) still pending]
 - deployment/test-app is ready.
Deployments stabilized in 25.78577359s
Press Ctrl+C to exit
Watching for changes...
[test-app-5f8c595dd7-9kkb8 server] 
[test-app-5f8c595dd7-9kkb8 server] > test-app@1.0.0 dev /src/app
[test-app-5f8c595dd7-9kkb8 server] > NODE_OPTIONS=--inspect=9229 next -p 8080
[test-app-5f8c595dd7-9kkb8 server] 
[test-app-5f8c595dd7-9kkb8 server] Debugger listening on ws://127.0.0.1:9229/45990af9-0671-43e5-8668-b26d9f9304b4
[test-app-5f8c595dd7-9kkb8 server] For help, see: https://nodejs.org/en/docs/inspector
[test-app-5f8c595dd7-9kkb8 server] ready - started server on http://localhost:8080
[test-app-5f8c595dd7-9kkb8 server] (node:16) ExperimentalWarning: The fs.promises API is experimental
[test-app-5f8c595dd7-9kkb8 server] event - compiled successfully
```

**Comment by briandealwis** [comment]
Change the ENTRYPOINT

    ENTRYPOINT ["node", "./node_modules/.bin/next", "dev", "-p", "8080", "--inspect=127.0.0.1:9229"]`

**Comment by briandealwis** [comment]
Oh and `skaffold debug`

**Comment by tejal29** [comment]
> Change the ENTRYPOINT
> 
> ```
> ENTRYPOINT ["node", "./node_modules/.bin/next", "dev", "-p", "8080", "--inspect=127.0.0.1:9229"]`
> ```

yeah, i realized it was commented out in the dockerfile.
