### ISSUE TITLE
output a message when the deployment rollout is complete

### ISSUE THREAD

**Issue by WilliamDenniss** [GoogleContainerTools/skaffold#459]
### Expected behavior
Indicate to the user when the deployment is fully rolled out and available.

### Actual behavior
Currently Skaffold indicates when the deployment is complete in the sense that the image was uploaded, and the image set on the deployment – but it doesn't watch the rollout status and indicate when the deployment is actually ready for use.

### Information

```
Skaffold version: v0.4.0
Operating system: 10.13.3
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/wdenniss-gke-test17/nodedemo
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: wdenniss-gke-test17
```

### Steps to reproduce the behavior

1. Update an image in a deployment with readiness checks and multiple replicas
2. Observe the CLI messages from Skaffold
3. 
The following is printed
```
Deploy complete in 1.137004015s
Watching for changes...
```
But no indication that the deployment is ready to use.

**Comment by r2d4** [comment]
We don't currently do introspection on the kubernetes resources themselves, so we don't know that we've just deployed a deployment or a pod or some CRD. 

One method would be to just parse known types (deployment, pods) and we'd be able to output "readiness" for types. However, this gets a little trickier with higher level deploy representations (e.g. when is a chart "ready"?). However, I think its a worthwhile feature to pursue.

**Comment by Place1** [comment]
@WilliamDenniss i've implemented a basic version of this for the kubectl deployer on my fork in case you're interested: https://github.com/Place1/skaffold/blob/master/pkg/skaffold/deploy/kubectl/rollout_status.go

It simply finds all the deployment, daemonset and statefulset manifests and executes a `kubectl rollout status <type> <name>` on each. It blocks the completion of skaffold until they're all complete.

**Comment by balopat** [comment]
We are working on relying on rollout status for determining the deployment success: https://github.com/GoogleContainerTools/skaffold/pull/2374

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and if it does still exist, it doesn't seem to be getting any traction at the moment. If this issue appears in the most recent release of Skaffold, please feel free to add a follow-up comment and we will see about getting it prioritized appropriately.

If someone sees a similar issue to this one, please create a new issue, but do include a link to this issue if possible. 

Thank you for sharing this issue with us!

**Comment by nkubala** [comment]
this issue should actually be fixed now that we support deployment status check by default.
