### ISSUE TITLE
how can build artifacts with multi progress

### ISSUE THREAD

**Issue by zoulux** [GoogleContainerTools/skaffold#4593]
### Expected behavior

the yaml have five artifacts ，build artifacts with multi progress

### Actual behavior

single progress sequential execution

### Information

- Skaffold version: skaffold/v2beta5 / v1.12.1
- Operating system: mac
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by briandealwis** [comment]
The [`skaffold.yaml`](https://skaffold.dev/docs/references/yaml/#build-local-concurrency) supports specify the desired concurrency of the build.  The builds will proceed in the background and the logs will be shown as each build completes.
