### ISSUE TITLE
Feature Request: Output the commands being run by skaffold

### ISSUE THREAD

**Issue by WilliamDenniss** [GoogleContainerTools/skaffold#461]
Can we output the commands being run by Skaffold at a certain log verbosity?

For example, let's say I'm having an authentication issue pushing an image, and I'm getting the errors output. Can we output the stand alone commands as well (e.g. `docker push …`) so that I can run / investigate just the command that is failing?

### Information

```
Skaffold version: v0.4.0
Operating system: 10.13.3
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/wdenniss-gke-test17/nodedemo
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: wdenniss-gke-test17
```

**Comment by r2d4** [comment]
They should be output with `--v debug`. We aren't always shelling out (i.e. we use the docker API directly), but could definitely add more verbosity around what we're doing there. 

The registry auth is specifically a tricky issue, since we don't get any decent errors from the API or registry itself. We might need to special case some of those with better user-oriented action items.

**Comment by WilliamDenniss** [comment]
Ah ok. I am seeing some other command logs now you mention it.

For the push, the output currently is:
```
The push refers to repository [gcr.io/wdenniss-gke-test17/nodedemo]
```
Even though we're using the API rather than shelling out, can we construct a reliable shell command anyway and log that? Could be formatted differently to the actual shell commands, to avoid confusion.

E.g. we could say:
```
Pushing to container repository `docker push gcr.io/wdenniss-gke-test17/nodedemo:eac650c9dd25f5a7c159ffe05cdbe7fd7a56480fa65033bc5ccffa39c2e32842`
```

This gives a little more information including: the exact container with tag being pushed (even though this is implied by the previous build step, I don't think it hurts to be explicit), and a command line that the user can run manually if something goes wrong.

**Comment by dgageot** [comment]
I'm going to close this one because, now, we print all the commands that Skaffold runs
