### ISSUE TITLE
'skaffold dev' can hang and ignore ctrl-c

### ISSUE THREAD

**Issue by drewp** [GoogleContainerTools/skaffold#4613]
This should be timing out and erroring, but instead it hangs and ignores at least the first ctrl-c.

```
% skaffold version
v1.12.1

% head -999 *
==> Dockerfile <==
FROM nonexist:1234/foo

==> deploy.yaml <==
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
        - name: shortener
          image: bang5:5000/shortener_image  

==> skaffold.yaml <==
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: df
build:
  artifacts:
  - image: bang5:5000/shortener_image
deploy:
  kubectl:
    manifests:
    - deploy.yaml
```

```
% skaffold dev    
Listing files to watch...
 - bang5:5000/shortener_image
```

`docker build` is trying to resolve the host 'nonexist' but it just looks like `skaffold dev` has hung. I don't know what can easily be done about this, but docker has output `Step 1/1 : FROM nonexist:1234/foo` and skaffold has suppressed it, so maybe after a time skaffold could start printing what it has received.

**Comment by nkubala** [comment]
hmm, skaffold should still be catching the various ctrl+c signals and interrupting. are you by chance running on windows? we just shipped a fix to an issue with os.Interrupt on windows that might help here.

**Comment by drewp** [comment]
linux and zsh. Might it be zsh? See my internal bug 156014480 where I had a related problem with gcloud.

**Comment by MarlonGamez** [comment]
@drewp Have you been able to determine if it's a zsh issue? It seems possible, especially if it's happening in other tools beyond skaffold as well

**Comment by nkubala** [comment]
FWIW i also use zsh and i've never seen this issue myself.

to clear our triage queue, i'm going to close this issue out for now since it's unclear we have anything to do here. @drewp if you happen to dig in more and think this is a skaffold issue, please feel free and reopen.
