### ISSUE TITLE
Doc: Skaffold.yaml page not rendering

### ISSUE THREAD

**Issue by vishal-biyani** [GoogleContainerTools/skaffold#4614]
### Expected behavior

Skaffold YAML reference page in docs site loads full YAML with reference of each section

### Actual behavior

It is only loading a line and not full YAML:

![image](https://user-images.githubusercontent.com/1167948/89116515-7b880380-d4b2-11ea-9366-2c4f8b0bf540.png)

### Information

The docs website 
https://skaffold.dev/docs/references/yaml/

**Comment by Namielusi** [comment]
I found a workaround in case someone doesn't want to wait for a fix, the table renders if you revert to the `v2beta5` version.

1. Head to https://skaffold.dev/docs/references/yaml/ and open chrome dev tools
2. In the Sources tab, find index.html file
3. Using chrome [local overrides](https://developers.google.com/web/updates/2018/01/devtools#overrides), change the `date-version` attribute of the `#table` element from `skaffold/v2beta6` to `skaffold/v2beta5`
4. Save and reload the page

![image](https://user-images.githubusercontent.com/12588081/89122070-7d16f300-d4d5-11ea-8b71-54b3d49d0efa.png)

It can be done in the other browsers too if there is a possibility to somehow update the element attribute before js loads.
