### ISSUE TITLE
.dockerignore isn't watched for changes

### ISSUE THREAD

**Issue by WilliamDenniss** [GoogleContainerTools/skaffold#462]
### Expected behavior
Changes to `.dockerignore` should be reflected immediately.

### Actual behavior
Need to restart Skaffold to pickup changes in `.dockerignore`.

### Information

```
Skaffold version: v0.4.0
Operating system: 10.13.3
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/wdenniss-gke-test17/nodedemo
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: wdenniss-gke-test17
```

### Steps to reproduce the behavior

  1. Add a file to `.dockerfile`
  2. Modify that file
  3. Observe that Skaffold still triggers despite the file being ignored

**Comment by r2d4** [comment]
This makes sense. We parse the dockerfile for dependencies and add those files to the "watch" list, but we have to manually add the Dockerfile itself to that list. We should do the same for .dockerignore.
