### ISSUE TITLE
Feature request: Trigger on changes to the kubernetes manifests, even when they are .dockerignore'd

### ISSUE THREAD

**Issue by WilliamDenniss** [GoogleContainerTools/skaffold#463]
### Expected behavior
I should be able to add my Kubernetes manifests to `.dockerignore`, as I don't wish for them to be included in my container.

However, I would still like changes to those manifest files (e.g. replica count, etc) to be applied to the cluster.

Even better would be for changes to the manifests to be applied to the cluster *without* the step of building an image (due to the fact they are `.dockerignore`'d).

### Actual behavior
If the Kubernetes manifests are in the `.dockerignore`, changes to them do not trigger a rollout.

### Information

```
Skaffold version: v0.4.0
Operating system: 10.13.3
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/wdenniss-gke-test17/nodedemo
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: wdenniss-gke-test17
```

### Steps to reproduce the behavior

  1. Add your k8s manifest to `.dockerignore`
  2. Stop, and start `skaffold dev` (#462)
  3. Edit, and save a change to one of the manifests you just added to `.dockerignore`

**Comment by r2d4** [comment]
We actually do a bit of introspection on the dockerfile to create the absolute minimum context. This means that if you do your COPYs and ADDs in the minimum way (i.e. not just `COPY . .`), we'll only add the necessary files to the docker context.

> Even better would be for changes to the manifests to be applied to the cluster without the step of building an image (due to the fact they are .dockerignore'd).

Skaffold _should_ do this today in v0.5.0 with this change https://github.com/GoogleContainerTools/skaffold/pull/432. If thats not working, its a bug

**Comment by WilliamDenniss** [comment]
Oh, nice. Just updated to 0.5.0, and it's working perfectly!
