### ISSUE TITLE
survey shows when SKAFFOLD_INTERACTIVE is false

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4632]
Based on chat with @medyagh - this may not already be the case.

I didn't see any mention of interactive checks within `ShouldDisplayPrompt()`

**Comment by nkubala** [comment]
is this still an issue? @tstromberg @kschaab @medyagh

**Comment by MarlonGamez** [comment]
This should be fixed with v1.14.0! I'm gonna close this for now but please reopen if this shows up again
