### ISSUE TITLE
Obtuse error message when docker isn't authenticated with GCR

### ISSUE THREAD

**Issue by WilliamDenniss** [GoogleContainerTools/skaffold#464]
### Expected behavior
When docker can't push to GCR due to a lack of gcloud credential helpers, the error message is a little confusing.  It might be simpler just to say "you need to run run `gcloud alpha auth configure-docker`" (or provider pointer to where this is [documented](https://github.com/GoogleContainerTools/skaffold#installation)) rather than sending them to the complex GCR authentication docs with a lot of extraneous information.

### Actual behavior
Received the following error message:
```
cd7100a72410: Preparing
WARN[0000] run: build: build step: running push: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication 
Watching for changes...
```

In addition to crafting a more succinct message for GCR, two additional comments about this error:
1. Probably should be ERROR, not WARN, and not progress to "Watching for changes…"
2. I didn't know exactly what command generated this warning (#459) which made it harder to investigate the solution (I figured it was to do with docker push, but knowing the exact command would help a lot to debug, i.e. knowing it was using `docker push`, not `gcloud docker -- push` would have been a good clue).

### Information

```
Skaffold version: v0.4.0
Operating system: 10.13.3
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/wdenniss-gke-test17/nodedemo
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: wdenniss-gke-test17
```

### Steps to reproduce the behavior

  1. Try to deploy your first Skaffold app, without configuring docker with gcloud credentials first.

**Comment by r2d4** [comment]
Yup, this is a common use case. Thats the error we get from the registry, so its as obtuse on our end. We can do something like docker does when push fails. I kind of hinted at this in the other issue. Its probably common enough and unclear enough to be special cased.

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by dgageot** [comment]
I'm going to close this one. It's now a fatal error
