### ISSUE TITLE
CI, locally

### ISSUE THREAD

**Issue by blaggacao** [GoogleContainerTools/skaffold#4642]
- I like the idea of running container structure tests locally.

- In the same spirit, I also like the idea of running [integration tests locally](https://github.com/rancher/k3d/blob/8dd1ec61db6359f89346e5f033549658d0a8c74c/Makefile#L163-L165) \*

- Is there a place in the roadmap to clarify where skaffold's testing toolset might be heading?

\* You know, [home office](https://www.sallyscottages.co.uk/blog/sallys-new-office-has-great-view). (sic!)

**Comment by MarlonGamez** [comment]
Hi @blaggacao, thanks for opening up this issue. Having the ability to run integration tests locally through skaffold isn't currently a goal for our upcoming milestones, but it is definitely a story that we want to explore and expand upon in the upcoming quarters

**Comment by briandealwis** [comment]
People have been chiming in with feedback on #2561.  Feel free to add any thoughts you might have there.
