### ISSUE TITLE
"DevInit Iteration N" log messages are confusing

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4662]
Skaffold's devLoopEvents have a message like 

    DevInit Iteration 5 in progress
    DevInit Iteration 2 successful
    DevInit Iteration 0 failed with error code BUILD_UNKNOWN

These messages are reported by some IDEs and the _DevInit Iteration X_ is causing confusion.

I instead propose that these messages be changed to 

    Update initiated due to file change
    Update successful
    Update failed with error code %v

<details>
<summary>logEntry</summary>

```json
{
  "result": {
    "timestamp": "2020-08-14T04:01:07.178263Z",
    "event": {
      "devLoopEvent": {
        "status": "Failed",
        "err": {
          "errCode": "BUILD_UNKNOWN",
          "message": "couldn't build \"skaffold-example\": unable to stream build output: The command '/bin/sh -c go build -o /app main.go' returned a non-zero code: 2"
        }
      }
    },
    "entry": "DevInit Iteration 0 failed with error code BUILD_UNKNOWN"
  }
}
```
</details>

(Mentioned in [friction log](https://docs.google.com/document/d/1DcJtAs8345td8WKu1P02PPZTiBqhREN60wBkZprb3no/edit?disco=AAAAJ203H6M))

**Comment by tejal29** [comment]
@briandealwis i think VSC plugin constructs this message from events api.  Created an issue here https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2971

**Comment by tejal29** [comment]
Keeping this open for book keeping.
