### ISSUE TITLE
Increase default deployment timeout from 2m0s

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4669]
This  timeout is too short for many cases, especially if remote images need to be pulled in.

Seen here:

```
Resource deployment/nodejs-guestbook-backend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-frontend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-mongodb status failed with could not stabilize within 2m0s: context deadline exceeded
Status check failed
```

Based on my experience, 8-10 minutes is more suitable default. My apologies if this is something set by Cloud Code.

**Comment by nkubala** [comment]
no, I think this is our default. my only concern is that we don't have much feedback while the status checker is waiting, so to the user it just seems like it's hanging - this was my experience trying some things out yesterday even with the default set at 2. we should provide periodic updates if nothing else so the user knows that at least something is happening

**Comment by nkubala** [comment]
haha, just saw https://github.com/GoogleContainerTools/skaffold/issues/4670 :)

**Comment by kodeninja** [comment]
@tstromberg @nkubala

Any workaround for this (with `v1.17.2`)? I leverage skaffold in a CI for deployments, and am facing the same issue. The deployment takes about 3-3.5 minutes to complete, but skaffold borks after 2 minutes, causing the CI deploy job to fail, even though the actual deployment is successful 😒.

```bash
 $ skaffold deploy --skip-render=false --force=true --profile $SKAFFOLD_PROFILE --images "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest"
 Tags used in deployment:
  - my/image -> my/image:latest
 Starting deploy...
  - service/app configured
  - service/prometheus-metrics configured
  - deployment.apps/app configured
  - ingress.extensions/app configured
 Waiting for deployments to stabilize...
  - app:deployment/app: waiting for rollout to finish: 1 out of 3 new replicas have been updated...
  - app:deployment/app: creating container server-node
     - app:pod/app-6b659f6bcc-bgv5q: creating container server-node
  - app:deployment/app: could not stabilize within 2m0s
  - app:deployment/app failed. Error: could not stabilize within 2m0s.
 1/1 deployment(s) failed
```

**Comment by kodeninja** [comment]
Hmm... adding `spec.progressDeadlineSeconds: 540` in the deployment yaml _seems_ to be working. Need to test more.

**Comment by gsquared94** [comment]
@kodeninja  you can also update this property directly in the `skaffold.yaml`:
```yaml
deploy:
  statusCheckDeadlineSeconds: 540
  kubectl:
    manifests:
    - k8s-*
```
we've also changed the default to 10 minutes in the latest release. 
Closing as the original issue is fixed.
