### ISSUE TITLE
Skaffold ignores SKAFFOLD_UDPATE_CHECK and SKAFFOLD_INTERACTIVE on error

### ISSUE THREAD

**Issue by kschaab** [GoogleContainerTools/skaffold#4673]
If you pass in SKAFFOLD_UPDATE_CHECK: 'false', SKAFFOLD_INTERACTIVE: 'false' and run skaffold dev it will output version upgrade details on failure.

### Expected behavior
SKAFFOLD_UPDATE_CHECK and SKAFFOLD_INTERACTIVE flags always suppress the skaffold update check.

### Actual behavior
SKAFFOLD_UPDATE_CHECK and SKAFFOLD_INTERACTIVE flags are ignored on failure.

### Information

- Skaffold version: 1.13.0
- Operating system: Darwin 10.15.6

### Steps to reproduce the behavior

1. Run `SKAFFOLD_UPDATE_CHECK=false skaffold dev` with an error (malformed skaffold.yaml, problematic deployment, etc).

**Comment by nkubala** [comment]
can you paste the exact error you're seeing? I'm unable to reproduce this locally. we do have a warning that your skaffold version might be too old if there's a parse error since some changes may not be backwards compatible, so maybe this is what you're seeing? we could probably remove this.

```
➜  guestbook-1 skaffold dev
WARN[0000] Your Skaffold version might be too old. Download the latest version (1.13.1) from:
  https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.13.1 
parsing skaffold config: unable to parse config: yaml: unmarshal errors:
  line 16: field foo not found in type v2beta4.SkaffoldConfig
```

**Comment by nkubala** [comment]
yeah i just tried again and this seems to be working as intended. @kschaab can you check to see how you're passing these values to skaffold?

**Comment by kschaab** [comment]
That's the behavior I'm seeing, so I believe you can reproduce it.  Should an update warning show up when `SKAFFOLD_UPDATE_CHECK` is `false`?  Maybe I don't understand the function of `SKAFFOLD_UPDATE_CHECK`.  Our intent here is not to show this to users when they are having their dependencies managed for them as 1.13.1 is not available through the IDE extensions.  @russwolf .  It happens when skaffold dev deploy fails as well, at the end of deployment.
