### ISSUE TITLE
Skaffold docker image gcr.io/k8s-skaffold/skaffold is using Java 8.

### ISSUE THREAD

**Issue by vdsharma** [GoogleContainerTools/skaffold#4674]
Skaffold docker image gcr.io/k8s-skaffold/skaffold:v1.13.1 is installing OpenJDK 8. It would be nice to upgrade it to a more recent versions of java. Is there any dependency on using only jdk 8 only?

**Comment by briandealwis** [comment]
I believe the JDK is there to support building with Jib.  Is there some reason why you need a newer version available?

**Comment by vdsharma** [comment]
When using this image JIB builds can not be compiled for any java version above 8.

I like the fact that all tools are in a single image and it allows us to use this image in my local environment as well as CICD flow, rather than installing all the tooling on various environments and managing different versions of tools.  

Upgrading Java will allow for compiling with higher versions of Java as well.

**Comment by briandealwis** [comment]
Oops, sorry @vdsharma: this has been fixed.

**Comment by vdsharma** [comment]
Thanks! @briandealwis
