### ISSUE TITLE
Too many UNKNOWN/ERROR type failures for Skaffold events

### ISSUE THREAD

**Issue by go-nelango** [GoogleContainerTools/skaffold#4692]
Large number of skaffold event errors are being reported as UKNOWN/ERROR. We need more descriptive error codes for Cloud Code metrics tracking and investigations.

Based on this dashboard https://dashboards.corp.google.com/edit/_dcb794d1_3a93_4405_8560_8230e2e5325d, we see:
![image](https://user-images.githubusercontent.com/68573204/90555858-da08df00-e14c-11ea-9d83-00b27dd0b851.png)

On vscode side, we log skaffold version for cloudcode.skaffold.session.end event. So filtering based on versions:

68% error codes from v1.13.1 are UKNOWN/ERROR
![image](https://user-images.githubusercontent.com/68573204/90555636-88605480-e14c-11ea-985a-4d6349583c4b.png)

43% error codes from v1.13.0 are UKNOWN/ERROR
![image](https://user-images.githubusercontent.com/68573204/90555726-ac239a80-e14c-11ea-8189-3c090b19881b.png)

**Comment by go-nelango** [comment]
@briandealwis @tejal29 @sivakku as FYI

**Comment by tejal29** [comment]
Thanks @go-nelango for opening this issue.

**Comment by tejal29** [comment]
We have an issue #4645 which @PriyaModali  is working on to reduce Deploy_UNKNOWN. 
@go-nelango, can you add some data on
1. BUILD_UNKNOWN by builders?
2. DEPLOY_UNKNOWN by deployers?

**Comment by tejal29** [comment]
Handled BUILD_UNKONWN -> docker connectivity issues here #4914

**Comment by go-nelango** [comment]
Please note charts below are based on IntelliJ metrics from 9/1/2020 to 9/30/2020 with skaffold version v1.13.2 and higher.
Vscode is currently not reporting Skaffold Metaevent and we are fixing it.

1. BUILD_UNKNOWN by builders
![image](https://user-images.githubusercontent.com/68573204/96059730-97f5d400-0e43-11eb-880d-664dc1efdc36.png)

2.DEPLOY_UNKNOWN by deployers
![image](https://user-images.githubusercontent.com/68573204/96059741-9debb500-0e43-11eb-997c-a08ff239818a.png)

**Comment by tejal29** [comment]
We have now reduced unknowns to 23% of all failure that happen or 3% of total sessions

**Comment by tejal29** [comment]
Closing this in favor of https://github.com/GoogleContainerTools/skaffold/issues/5246
