### ISSUE TITLE
Prune old images at beginning of dev loop

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4693]
I've seen an increasing number of friction logs where Skaffold users have filled up their local Docker for Desktop image storage. 

I understand that we prune images on exit, but I suggest we also consider pruning at start-up. This may be either always, or if we detect that disk space is constrained (`docker system df`).

**Comment by tstromberg** [comment]
NOTE: We should consider doing so as a background task as this may take a while to execute.

**Comment by tejal29** [comment]
This is already in progress.
