### ISSUE TITLE
DevInit Iteration should be indexed starting at 1

### ISSUE THREAD

**Issue by kschaab** [GoogleContainerTools/skaffold#4700]
On running skaffold dev the event `DevInit Iteration 0 in progress` is reported to users.  It should start at 1.  From [friction log ](https://docs.google.com/document/d/1gX62_0G3OaVRwl8Do0WJs_co45ks0k9KYQuNpaNlJSU/edit?ts=5f3d59d6).
### Information

- Skaffold version: 1.13.0
- Operating system: MacOS 10.15.6
- Contents of skaffold.yaml: (N/A)

### Steps to reproduce the behavior

1. `skaffold dev...`

**Comment by briandealwis** [comment]
We're dropping the iteration and changing the message: see #4662 / #4684.
