### ISSUE TITLE
Chocolately install/upgrade of Skaffold v1.13.2 fails

### ISSUE THREAD

**Issue by avgojzack** [GoogleContainerTools/skaffold#4717]
The choco install/upgrade tries to download a file that does not exist. I happened to catch it on video, which you can see here:
https://www.youtube.com/watch?v=1NhVtWAhH2o

This is the file that it wants to download:
https://github.com/GoogleContainerTools/skaffold/releases/download/v1.13.2/skaffold-windows-amd64.exe

### Expected behavior
v1.13.2 should be installed up

### Information

- Skaffold version: version: 1.13.1 going to 1.13.2
- Operating system: Windows

### Steps to reproduce the behavior

1. choco install skaffold --version 1.13.2
2. choco upgrade skaffold --force

**Comment by avgojzack** [comment]
Just ran it again and I can see it working now :shrug: I'll close

**Comment by nkubala** [comment]
weird, maybe it took some time to propagate 🤷
