### ISSUE TITLE
Format port forward URL/port to make a visitable address

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4718]
currently the port forward logs provide something like:

```
Port forwarding deployment/leeroy-web in namespace default, remote port 8080 -> address 127.0.0.1 port 9000
Port forwarding service/leeroy-app in namespace default, remote port 50051 -> address 127.0.0.1 port 50053
```

when this is surfaced in a terminal/IDE, the user still needs to either copy+paste two separate items, or manually type the address+port into their browser. we can format these properly to make them a clickable link.

**Comment by briandealwis** [comment]
We could consider examining the service and containerPort definitions and apply some heuristics to see if it looks like an HTTP or HTTPS port and automatically synthesize a relevant URL:
  - service
    - if `service.spec.ports[].appProtocol` is `http` or `www` or `www-http` ([assigned protocol types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http)) then it's `http://local:port`
    - if `service.spec.ports[].appProtocol` is `https` ([assigned protocol types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=https)) then it's `https://local:port`
    - if `service.spec.ports[].name` is `http` or `www` or `www-http` ([assigned protocol types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http)) then it's `http://local:port`
    - if `service.spec.ports[].name` is `https` ([assigned protocol types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=https)) then it's `https://local:port`
    - if `service.spec.ports[].port` is 80, 8000, 8080 then it's `http://local:port`
    - if `service.spec.ports[].port` is 443 then it's `https://local:port`
    - if `service.spec.ports[].targetPort` is 80, 8000, 8080 then it's `http://local:port`
    - if `service.spec.ports[].targetPort` is 443 then it's `https://local:port`

  - containerPort
    - if `containerPort.name` is `http` or `www` or `www-http` ([assigned protocol types](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http)) then it's `http://local:port`
    - if `containerPort.name` is `https` then it's `https://local:port`
    - if `containerPort.port`  is 80, 8000, 8080 then it's `http://local:port`
    - if `containerPort.port`  is 443 then it's `https://local:port`
