### ISSUE TITLE
How to enable caching when using cloud build option 

### ISSUE THREAD

**Issue by amitm02** [GoogleContainerTools/skaffold#4722]
Is there a way to enable image layers cacheing when using the google cloud build option (https://skaffold.dev/docs/pipeline-stages/builders/docker/#dockerfile-remotely-with-google-cloud-build)?

**Comment by tejal29** [comment]
yes @amitm02. you could use kaniko GCB build step. 
Kaniko allows caching intermediate layers to speed up builds for dockerfile builds.
https://cloud.google.com/cloud-build/docs/speeding-up-builds

**Comment by tejal29** [comment]
Here is an example on how to configure skaffold to use GCB kaniko https://github.com/GoogleContainerTools/skaffold/tree/master/examples/gcb-kaniko

**Comment by amitm02** [comment]
Thanks @tejal29 , with the example you provided I was able to make it work.
I must admit, to my surprise and disappointment, even with caching, the builds were much slower than building locally on my laptop.

**Comment by briandealwis** [comment]
Closing as original question has been answered.
