### ISSUE TITLE
Render not displaying error message

### ISSUE THREAD

**Issue by p3tecracknell** [GoogleContainerTools/skaffold#4726]
### Expected behavior
skaffold render
``
Error: UPGRADE FAILED: template: fail/templates/deployment.yaml:9:33: executing "fail/templates/deployment.yaml" at <include "fail.name" .>: error calling include: template: no template "fail.name" associated with template "gotpl"
deploying "fail": install: exit status 1
```
### Actual behavior
```
skaffold render
rendering manifests: exit status 1
```

### Information

- Skaffold version: v1.13.2
- Operating system: MacOS / Ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta6
kind: Config

deploy:
  helm:
    releases:
      - name: fail
        chartPath: fail
```

### Steps to reproduce the behavior

1. https://github.com/p3tecracknell/skaffold-render-issue
2. `skaffold render`
3. Shows no error message
4. `skaffold run`
5. Shows error message with gotpl

**Comment by tejal29** [comment]
Hey @p3tecracknell, sorry for the confusing behaviour. skaffold render definitely needs to be patched and how better behavior.
