### ISSUE TITLE
`make integration-in-kind` leaves kind cluster running after creating it

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4729]
i prefer to run integration tests in kind because they're generally faster than running in plain docker, but the kind cluster gets left behind if i left skaffold create it, and eats up a ton of resources. we should teardown the cluster if we create it for integration tests.

**Comment by tejal29** [comment]
Is this from a user request or you are referring to skaffold integration tests. 
I am wondering because  you recently did a user study.

**Comment by nkubala** [comment]
haha no this is just something i run into all the time with integration tests that annoys me :)
