### ISSUE TITLE
Local build shouldn't need to collect licenses

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4730]
i prefer to run `make install` when developing skaffold locally since it builds the binary with the necessary compiler flags and puts it on my path. however, this also generates the licenses files for every dependency, which takes 20-30 seconds. we should only be generating these licenses for our releases, not for local builds.

**Comment by nkubala** [comment]
I'm going to reopen this one. `LOCAL=true` does provide a way around this, but I feel that we should invert this - instead let's add a `RELEASE` env var that when set causes licenses to be generated, otherwise don't do it by default. I find it annoying that if I have a shell that doesn't have this variable set, the licenses get generated, and they also get generated by default in integration tests which is not necessary.

**Comment by ericzzzzzzz** [comment]
licenses are stored in skaffold source repo now. closing this issue.
