### ISSUE TITLE
Enable BuildKit in Travis

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4746]
currently, we can't test buildkit builds in travis because the daemon doesn't support it. we should figure out how to enable it for all of our travis builds.

https://vladimir.varank.in/notes/2020/01/buildkit-multi-platform-travis-ci/

**Comment by aaron-prindle** [comment]
Closing this as travis is no longer used and we have migrated to Github Actions. Github Actions does support buildkit as per:
https://github.com/docker/github-actions/issues/12#issuecomment-600540752

Re-open if this issue still makes sense to keep just w/ renaming Travis -> Github Actions
