### ISSUE TITLE
Enable minikube profile detection by default

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4747]
https://github.com/GoogleContainerTools/skaffold/pull/4745 hides the minikube profile detection behind a flag to ensure we don't break existing minikube users with non-standard profile names. once we're confident in this feature we can remove the flag and enable it by default.

**Comment by tstromberg** [comment]
is this still a thing?

**Comment by nkubala** [comment]
yeah we still don't do this by default, but we could consider switching the default value if we're confident in this feature.

**Comment by gsquared94** [comment]
minikube's `profile list` command latency was a concern to not do this immediately. I've opened a PR to keep the flag but enable it by default. Will do away with the flag if there are no issues reported.
