### ISSUE TITLE
Outputting ANSI/VT100 escape sequences erroneously on Windows

### ISSUE THREAD

**Issue by Jimbly** [GoogleContainerTools/skaffold#4783]
![image](https://user-images.githubusercontent.com/774383/93142569-276c6380-f69b-11ea-938f-381374cc86d5.png)

It looks like Skaffold.exe is outputting escape sequences before enabling or checking for the feature.

Simplest fix is to add these lines (or similar) to your Windows build (will enable support on newer Windows versions and do nothing on older (XP/2K) Windows versions):
```C
HANDLE hConsole = GetStdHandle( STD_OUTPUT_HANDLE );
DWORD mode;
if (GetConsoleMode(hConsole, &mode)) {
	#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004 // needed if not building against a newer Windows SDK
	SetConsoleMode(hConsole, mode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
}
```
[MSDN reference](https://docs.microsoft.com/en-us/windows/console/setconsolemode)

**Comment by briandealwis** [comment]
Skaffold's written in Go, so that code snippet won't work :-)

But the libraries we use under the hood are supposed to check for support.  Could you please tell us what version of Windows and Skaffold that you're using?

**Comment by Jimbly** [comment]
Sure!  Just downloaded Skaffold yesterday, but from a screen share with a coworker a couple months ago, I know this was a problem then as well.

Windows 10 Pro v1909
```
C:\>skaffold version
v1.14.0

C:\>ver

Microsoft Windows [Version 10.0.18363.720]

C:\>echo %COMSPEC%
C:\WINDOWS\system32\cmd.exe
```
Also reproduces in Powershell.

I get colors showing up if I manual execute that code above, or I run `docker` first (e.g. `docker | skaffold run`).

**Comment by briandealwis** [comment]
I can reproduce this.
