### ISSUE TITLE
Debug needs to work with CNB Platform v0.4 and the new launcher style

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4796]
Debugging a buildpacks image with pack v0.13 now uses lifecycle 0.9.1, which introduced a [new launcher-style (RFC 45)](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md).

Previously images were built with the `ENTRYPOINT=/cnb/lifecycle/launcher` and used `CNB_PROCESS_TYPE` to determine the process to launch.  But it meant running these images with arguments like `docker run <bpimage> arg ...` didn't have the expected effect as the args were interpreted by the _launcher_ rather than the actual command that would be run.  To pass arguments to the process required providing `--` to indicate end of args to the launcher:  `docker run <bpimage> -- arg ...`.

CNB Platform 0.4 (implemented by pack v0.13.1) now links the `/cnb/lifecycle/launcher` to `/cnb/process/<process-type>` for each process-type.  The launcher now uses its invoked name to determine the process type, and `CNB_PROCESS_TYPE` is now ignored.  The process-type name `launcher` is also forbidden.

Marking as a bug as this issue prevents updating to pack v0.13.1 (#4757).

**Comment by tejal29** [comment]
It part of upcoming milestone. keeping the priority as is.
