### ISSUE TITLE
Skaffold.yaml files are not portable

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#480]
Something  that didn’t felt right when I configured the application to deploy it on GKE is that some parameters are stored in the skaffold.yaml and some are not. It makes it complicated to know what I have to change if I get a project from someone else and try to run it on my project.

  | skaffold.yaml | Manifests
-- | -- | --
Kubernetes context | CAN’T | -
Kubernetes namespace | CAN’T | CAN
GCB projectID | MUST | -
Kaniko GCS bucket | MUST | -
Image registries | MUST (with Tagger) | MUST

**Comment by balopat** [comment]
With the default repo functionality at least the last row is done - Image registries.

**Comment by balopat** [comment]
GCB projectId can be left empty as it is guessed from the image name, so that should be portable as well.

**Comment by dgageot** [comment]
I'm going to close this issue as it's been inactive for a while and the default repo features solves the most important issue.
