### ISSUE TITLE
Add watch for skaffold.yaml

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#483]
Skaffold.yaml changes should retrigger the full pipeline on `skaffold dev`. We can use a pattern like we used for the deploy dependencies.

**Comment by dlorenc** [comment]
Dup of https://github.com/GoogleContainerTools/skaffold/issues/483

**Comment by dlorenc** [comment]
Whoops, https://github.com/GoogleContainerTools/skaffold/issues/161
