### ISSUE TITLE
Lack of templating

### ISSUE THREAD

**Issue by noobG** [GoogleContainerTools/skaffold#4835]
### Expected behavior
Templating works universally in skaffold.yaml

### Actual behavior
It only works for certain fields

### Information
I'm worried that I've been working under some wrong assumptions seeing how often I run into the problem being unable to pass in variables from the environment

Here are some recent frustrations:
1) I want to use a separate Dockerfile in production for one of my images (e.g. Dockerfile.production); so I try to template the file suffix:
```
docker:
     dockerfile: ./Composer/Dockerfile{{.ENV}}
```
It just interprets it as is and fails

But then, to my great confusion, I have one field that **does** support it, which is part of my workaround to modify my Helm values file in production (had to do this to circumvent a separate issue with the inability to override Helm values files through skaffold; generating a separate Helm values file on my CI server and referring to that with variable substitution is my "hack" for this):

```
deploy:
    helm:
        releases:
            - name: load-balancer
              chartPath: ./k8s/load-balancer/helm
              valuesFiles:
                  - ./k8s/load-balancer/helm/values/{{.ENV}}.yaml
```
I just kinda haphazardly attempt to substitute when I need to and hope it's one of the supported fields - a little bit frustrating and confusing

2) I want build.artifacts.docker.cacheFrom to refer to a specific image tag (i.e. not ":latest"). So I try again for the field in the hopes that it supports templating, but again, the substitution doesn't work:
```
cacheFrom:
  - eu.gcr.io/redacted/myimage:{{.CACHED_IMAGE_TAG}}
```
Perhaps problem 1 could be solved by using profiles, but because I already use profiles to "enable services" in skaffold (e.g. skaffold dev -p service1,service2). I would need a profile to override another profile, which I'm not sure is possible, and would be a lot less maintainable than just simple templating

I see no easy way to accomplish 2, so I have to find workarounds for something that should (imo) be straight forward

It feels like my flexibility to arrange my workflow the way I want is hamstrung by skaffold.yaml not having variable substitution everywhere; am I going about this the wrong way? Am I supposed to use profiles for all cases where I know the possible values in advance? This is super verbose and hard to reason about, and doesn't even solve the problem of the case where my variables come from the environment (such as the case with the image tag, or CI environment secrets to pass to helm)

- Skaffold version: v1.14.0

**Comment by briandealwis** [comment]
We've been reluctant to support templating for a number of reasons.  As we've seen from Helm, templated files can be very hard to reason about as what you see is not necessarily what you get.  Our skaffold.yaml is a KRM-compliant resource that can be used with other KRM-related tools like kustomize (KRM = Kubernetes Resource Model), which would be lost.

You might consider looking at kustomize to preprocess and generate a skaffold.yam for your different environments.

**Comment by noobG** [comment]
In my case it would definitely be easier to reason about variable substitution, but I can see how maybe that would depend on the context and that you try to guide people toward certain practices - I'll just assume my perspective is missing some context :-)

kustomize does seem like it'd do the job - I'll run with that
