### ISSUE TITLE
Some FAILED skaffold events do not return error code

### ISSUE THREAD

**Issue by go-nelango** [GoogleContainerTools/skaffold#4847]
Skaffold devloop events with status == 'Failed' are expected to have a non-null error code. If failed events are missing the error code, failure_reason defaults to UKNOWN_ERROR in IDE metrics (and this is parsed as failure_phase = UKNOWN and failure_reason = ERROR in cloudcode.skaffold.session.end). Could you please investigate why failed events might be missing error code?

The above case makes up >9% of total errors in cloudcode.skaffold.session.end based on data from 8/01/2020 to 9/30/2020 and skaffold version >= v1.13.2
![image](https://user-images.githubusercontent.com/68573204/94874781-b7ced600-0407-11eb-9880-242492fa9fe0.png)

This case makes up 15% of unknown errors in cloudcode.skaffold.session.end based on data from 8/01/2020 to 9/30/2020 and skaffold version >= v1.13.2
![image](https://user-images.githubusercontent.com/68573204/94873772-f7e08980-0404-11eb-9e10-064c4522cf45.png)

**Comment by go-nelango** [comment]
@tejal29 FYI

**Comment by MarlonGamez** [comment]
Commenting just to let whoever sees this know that we're hoping to prioritize this this quarter! :)

**Comment by tejal29** [comment]
We have few PRs already implemented. This is still a P1 for us.

**Comment by tejal29** [comment]
This should be addressed by #4926

**Comment by tejal29** [comment]
Closing for now but lets re-open if we see more such cases in v1.16.0

**Comment by briandealwis** [comment]
Closing, but @tejal29 will reopen if required.
