### ISSUE TITLE
Improve `skaffold render` output

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/skaffold#4854]
### Expected behavior

`skaffold render` should indicate that the process has started. It would be great to see a loading indicator.

### Actual behavior

No output until the render process is done.

### Information

- Skaffold version: v1.15.0
- Operating system: Windows

### Steps to reproduce the behavior

1. skaffold render -p app

**Comment by StarpTech** [comment]
I just checked the PR

> By default, the logs and output for the builds are suppressed, but can be displayed using a --loud flag.

`skaffold render --lout` solve it! I'd enable it by default.

**Comment by tejal29** [comment]
Thanks @StarpTech for posting the solution.
