### ISSUE TITLE
Track multiple pod statuses and only report the meaningful pod error status

### ISSUE THREAD

**Issue by nelango** [GoogleContainerTools/skaffold#4857]
POD_INITIALIZING is a failure reason reported in status check sub-phase. Instead of capturing the pod status at time limit, Skaffold could track multiple pod statuses and only report the meaningful pod error status

**Comment by go-nelango** [comment]
Note: this failure reason is <2% of error breakdown, so may not be a high priority

![image](https://user-images.githubusercontent.com/68573204/95123791-5b213300-0707-11eb-8f5f-6a94d8ac017e.png)

**Comment by go-nelango** [comment]
@tejal29 FYI

**Comment by MarlonGamez** [comment]
Perhaps we should create some sort of Epic like tracker for this issue along with #4847 and #4692? Since they are all related to failures when using skaffold?

**Comment by tejal29** [comment]
@MarlonGamez makes sense. #4692 is kind of an epic. I added a epic label to it.

**Comment by tejal29** [comment]
This is kind of related to #5366 
Like "Container Creating", "Container Restarting", "pod initializing" should also be not shown as errors.
