### ISSUE TITLE
vm-driver-none fallback detection

### ISSUE THREAD

**Issue by chris-hammond** [GoogleContainerTools/skaffold#4868]
It looks like minkube changed the error code returned when trying to run `minikube docker-env` using `--vm-driver='none'` from 64 to 51. (Why??!!) For obvious reasons, this breaks skaffold when used with minikube in this configuration.

### Expected behavior
When using `skaffold deploy` with older versions of minikube (e.g. v1.12.3) running `--vm-driver='none'`, the following message is displayed:
```
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: ""
 - stderr: "* 'none' driver does not support 'minikube docker-env' command\n"
 - cause: exit status 64
Fallback should function the same with the latest version of minikube.
```

### Actual behavior
The following error occurs when running `skaffold deploy`:
 ```
creating runner: creating builder: getting docker client: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube]
 - stdout: "\n\n"
 - stderr: "X Exiting due to ENV_DRIVER_CONFLICT: 'none' driver does not support 'minikube docker-env' command\n"
 - cause: exit status 51
```

### Information

- Skaffold version: 1.14.0 and 1.15.0
- Minikube version: 1.13.1 

### Steps to reproduce the behavior

Using _any_ skaffold project with minikube v1.13.1 running as `--vm-driver='none'`, run `skaffold deploy`.

**Comment by briandealwis** [comment]
This was changed with https://github.com/kubernetes/minikube/pull/9126
