### ISSUE TITLE
Image pruner operations fail if the context was cancelled or timed out during build or deploy.

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#4888]
The type `pruner` in `prune.go` uses the same `context.Context` that are used by build or deploy. As such if the user hits `Ctrl+C` to cancel the build or deploy sometimes they get the error message:
```
failed to list images: error during connect: Get "https://127.0.0.1:32774/v1.40/images/json?filters=%7B%22reference%22%3A%7B%22image3%22%3Atrue%7D%7D": context canceled 
    from googlecloudsdk.core import config
```
which is returned from the docker api client that `pruner` calls with a cancelled context.

**Comment by gsquared94** [comment]
@ilya-zuyev I think it's from https://github.com/GoogleContainerTools/skaffold/pull/4792
Specifically in `pkg/skaffold/build/local/local.go`:
```
	rt, err := build.InParallel(ctx, out, tags, artifacts, builder, *b.local.Concurrency)

	if b.prune {
		if b.mode == config.RunModes.Build {
			b.localPruner.synchronousCleanupOldImages(ctx, artifacts)
		} else {
			b.localPruner.asynchronousCleanupOldImages(ctx, artifacts)
		}
	}
```

**Comment by ilya-zuyev** [comment]
Yep, that's me.
/assign

**Comment by ilya-zuyev** [comment]
Yep, that's me. Thanks!
