### ISSUE TITLE
Document yaml through godoc or generated documentation

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#490]
Our YAML specification isn't well documented right now. Worse, our yaml parser won't warn on unknown keys, leaving user quite confused with typos or targeting old config specs.

A few things we should do

- [ ] Provide comments for all v1alpha2 structs
- [ ] Either expose those comments with a link to the godoc
- [ ] OR generate documentation that gets regenerated on every new configuration change

**Comment by nkubala** [comment]
We've updated the error handling and yaml parsing for our config, and we have schema generation in the works right now. The only piece of this left to do would be to auto-generate the annotated-skaffold.yaml from the config structs.

**Comment by balopat** [comment]
We have annotated yaml reference on https://skaffold.dev/docs/references/yaml/ now. Closing.
