### ISSUE TITLE
Documentation: Font Awesome search icon placeholder broken

### ISSUE THREAD

**Issue by thomas-riccardi** [GoogleContainerTools/skaffold#4903]
![image](https://user-images.githubusercontent.com/1730297/95846468-bd071b80-0d4b-11eb-9705-fef4be1223c7.png)

The `font awesome 5 free` web font is somehow not used in the search dom element, so the placeholder isn't substituted.

(changing the font-weight to 900 does make it work, but it's not necessary on upstream docsy demo site https://example.docsy.dev/ ; I stopped the investigation there).

**Comment by gsquared94** [comment]
I couldn't figure much out other than if you delete [this](https://github.com/GoogleContainerTools/skaffold/blob/846b759142aa1b778113ffb42af4483d5cd604dc/docs/layouts/partials/hooks/head-end.html#L13) line:
```html
<script src="https://kit.fontawesome.com/077204b73e.js" crossorigin="anonymous"></script>
```
then it shows up correctly:
![image](https://user-images.githubusercontent.com/39389231/96149561-18413580-0f27-11eb-9307-953c940a0bc5.png)
 but `far fa-gem` goes missing:
![image](https://user-images.githubusercontent.com/39389231/96149434-f3e55900-0f26-11eb-95d7-ab8b8b58a66e.png)

**Comment by IsaacPD** [comment]
I managed to make the magnifying glass appear within my browser by changing the font used for that element from "font awesome 5 free" to "FontAwesome"

https://github.com/GoogleContainerTools/skaffold/blob/29d522ff1895036793245cb439246b56e4e64f05/docs/layouts/partials/navbar.html#L36

The code that is responsible for the search bar is that above but I cannot find this "search-input.html" partial file that describes it, I have a feeling that's the key but i'm not sure.

<img width="1792" alt="Screen Shot 2020-11-10 at 6 31 19 PM" src="https://user-images.githubusercontent.com/12650821/98746243-14b49900-2383-11eb-986b-9099721225dc.png">
