### ISSUE TITLE
Incorrect Dockerfile search

### ISSUE THREAD

**Issue by uipo78** [GoogleContainerTools/skaffold#492]
### Expected behavior

I have a directory called "project" that looks like this 
```
project
├── code
│   ├── Dockerfile
│   └── main.py
├── k8s
│   ├── x1.yaml
│   └── x2.yaml
└── skaffold.yaml
```

My skaffold file looks like this
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
    - imageName: x1
      workspace: ./code/
      dockerfilePath: ./code/
    - imageName: x2
      workspace: ./code/
      dockerfilePath: ./code/
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/x1.yaml
      - k8s/x2.yaml
```

I call `skaffold run -f skaffold.yaml` from `project`.

My expectation is that this should build, push, and deploy without issue.

### Actual behavior

It seems to build fine but I do receive an error:
```
Starting build...
Sending build context to Docker daemon  10.75kB
Step 1/6 : FROM python:3.6.5-alpine3.7
 ---> 27e79c0fa4d2
Step 2/6 : RUN apk add --no-cache     gfortran     build-base
 ---> Using cache
 ---> cee05648e88b
Step 3/6 : RUN pip install     boto3     grequests     numpy
 ---> Using cache
 ---> b812a13b4d2a
Step 4/6 : RUN mkdir code
 ---> Using cache
 ---> 5a5478369ebb
Step 5/6 : WORKDIR code/
 ---> Using cache
 ---> 33ace0a60b2a
Step 6/6 : COPY main.py ./
 ---> Using cache
 ---> 53f03548d415
Successfully built 53f03548d415
Successfully tagged 4927001afeca09a8e26107706956b2c5:latest
Error: running skaffold steps: build: build step: generating tag: reading diff: open /home/uipo/project/Dockerfile: no such file or directory
```

Why would skaffold be looking for the Dockerfile in project?

### Information

```
Skaffold version: v0.5.0
Operating system: Arch Linux
```

**Comment by goutamtadi1** [comment]
@uipo78 Thanks for raising this issue. I faced the same issue. skaffold could not recognize Dockerfile from a separate directory. We would want to have Dockerfile in a separate directory because, we have certain COPY commands to copy some files into the image when the image build is done. This keeps our project modular and easy to navigate.

**Comment by balopat** [comment]
Hi @uipo78 and @goutamtadi1, with `skaffold/v1alpha2` the `dockerFilePath` needs to refer to the actual path Dockerfile, not its directory and it needs to be under the `docker` tag like in [here](https://github.com/GoogleContainerTools/skaffold/blob/master/skaffold.yaml#L7-L8) for example: 

````
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold
    workspace: .
    docker:
      dockerfilePath: deploy/skaffold/Dockerfile
````

**Comment by goutamtadi1** [comment]
@balopat Thanks for the hint. Let me try that.

**Comment by goutamtadi1** [comment]
@balopat That's working but with small changes to above example:

**Comment by dgageot** [comment]
@uipo78 @goutamtadi1 Can this ticket be closed or do you still see the issue?

**Comment by dgageot** [comment]
I'm going to close the issue because I assume it's been fixed. Please free to reopen if that's not the case
