### ISSUE TITLE
Private dependency authentication problems without docker

### ISSUE THREAD

**Issue by whereswaldon** [GoogleContainerTools/skaffold#4928]
I'm doing containers and kubernetes from Fedora Linux. Instead of `docker`, I use `podman` because docker doesn't support cgroupsv2.

I am unable to use `skaffold` due to a strange authentication error. It is trying to pull a docker image from a private Artifactory registry, if that helps.

### Expected behavior

`skaffold dev` correctly runs on my system given that I am authenticated to my container registry in `podman`.

### Actual behavior

```
$ skaffold dev
Listing files to watch...
 - my-register.com/my-namespace/myimage:mytag
watching files for artifact "my-register.com/my-namespace/myimage:mytag": listing files: parsing ONBUILD instructions: retrieving image "my-register.com/my-namespace/myimage:mytag": GET https://my-register.com/my-namespace/myimage:mytag: : Authentication is required
```

`skaffold` seems to be relying upon something to provide registry credentials, but it doesn't seem to be `~/.docker/config.json`. I manually created that file with my registry credentials and it still fails.

### Information

- Skaffold version: v1.15.0
- Operating system: Fedora Linux 32
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: myregister.com/my-namespace/myimage
      context: ./localdir/myimage
```

### Steps to reproduce the behavior

I can't provide a repo because this behavior is only triggered when pulling private dependencies.

1. On Fedora 32 (in a vm, say), try to run `skaffold dev` on a project that has a private dependency.

**Comment by tejal29** [comment]
i see a relevant bug https://github.com/containers/podman/issues/4357 which looks fixed. Maybe we need to update container deps or @whereswaldon you need to update podman on you end.

**Comment by briandealwis** [comment]
@whereswaldon did updating podman help?

**Comment by whereswaldon** [comment]
Embarrassingly, I believe this came down to a trailing comma in my docker config. I'm pretty sure that this is resolved now. Will reopen if the problem recurs and I can't see a syntax error.
