### ISSUE TITLE
Make dev's fail on first build and deploy be configurable

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#4953]
From Tais P. Hansen on skaffold-users@:
> I have a simple setup with a deployment of the service being developed and a deployment with a backend store. The service won't start as long as it can't connect to the backend store service which takes a few seconds to start. Kubernetes normally just restarts the pod until it connects and runs but skaffold tears everything down on the first exit, making it impossible to use "skaffold dev" without having to add connection retry logic to the service itself.
...
> Using an init container may be a viable workaround but I was trying to avoid having to create such workarounds just because of the behaviour of a development tool in the first place. I was hoping for some setting or parameter I had overlooked somewhere.

We've discussed this previously, and it does seem like this should be configurable behaviour.

**Comment by tejal29** [comment]
@balopat  and me had briefly discussed this #4158 during cloud run skaffold integration. We also tried it out in our long working prototype branch. 

I was also thinking this could be useful for increasing the skaffold session success rate especially for BUILD compilation errors.

**Comment by tejal29** [comment]
@briandealwis I am moving the discussion to #4158 and close this bug
