### ISSUE TITLE
Run kpt as a pipeline

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4956]
#### Description
Current kpt implementation is not using kpt as a pipeline: It heavily relies on directory read/write operations and stores configs in tmp file. To further support kpt fn pipeline and make it less brittle when things go wrong in the middle of the conceptional pipeline, kpt shall rely less on the tmp directory to store config intermediate statuses and obey the following structure:

Step 1. `kp fn source` (read in the manifest as stdin),
Step 2. `kustomize build` (hydrate the manifest),
Step 3. `kpt fn run` (validate, transform or generate the manifests via kpt functions),
Step 4. `kpt fn sink` (store the stdout in a given dir).

#### Blockers
To fully support kpt pipeline, kustomize shall be called as a kpt fn. What's more, it shall not be necessary to configure kustomize config via skaffold.yaml. 
https://github.com/kubernetes-sigs/kustomize/issues/2837

**Comment by tejal29** [comment]
This can be closed now as its part of render v2 work #5673
