### ISSUE TITLE
Skaffold syncing problem: unable to upgrade connection: container not found

### ISSUE THREAD

**Issue by orbb92** [GoogleContainerTools/skaffold#4966]
Hello

I am new to microservice and I've  built my first application using docker, Kubernetes, and skaffold.
I'm using typescript to build the services.

I'm using skaffold dev for the development of the application, and I created all YAML files and it seems that all good.

the problem is that when I run skaffold dev, the syncing isn't good. it stops after a few updates and I cant see the updates. only after I run skaffold dev again it shows the changes 

here is the Docker file:

```
FROM node: alpine

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "start"]```
```
deployment and service file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: orbb92/auth
---
apiVersion: v
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
```

skaffold file:

```
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: orbb92/auth1
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
```

here is the output from the skaffold CLI , as you can see it watches the changes but doesn't update

```
[auth] Connected to MongoDb
[auth] Listening on port 3000!!!!!!!!
Syncing 1 files for orbb92/auth1:f9ce26974fa20cc8ef9ce23c06b3d8436c59c3b5b09ef829e3d12a4fe547d135
Watching for changes...
[auth] Connected to MongoDb
[auth] Listening on port 3000!!!!!!!
Syncing 1 files for orbb92/auth1:f9ce26974fa20cc8ef9ce23c06b3d8436c59c3b5b09ef829e3d12a4fe547d135
Watching for changes...
[auth] Connected to MongoDb
[auth] Listening on port 3000!!!!!!
Syncing 1 files for orbb92/auth1:f9ce26974fa20cc8ef9ce23c06b3d8436c59c3b5b09ef829e3d12a4fe547d135
Watching for changes...
Syncing 1 files for orbb92/auth1:f9ce26974fa20cc8ef9ce23c06b3d8436c59c3b5b09ef829e3d12a4fe547d135
Watching for changes...
```
edit: here is the log:
```
time="2020-10-30T11:59:41+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-10-30T11:59:41+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:57+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T11:59:58+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-10-30T11:59:58+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-10-30T11:59:58+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388
time="2020-10-30T11:59:58+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388"
time="2020-10-30T11:59:58+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-10-30T11:59:58+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T11:59:58+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-77bc586b59-7mb4h --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T11:59:59+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
time="2020-10-30T11:59:59+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
Watching for changes...
[auth] Connected to MongoDb
[auth] Listening on port 5000.
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:02+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:03+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-10-30T12:00:03+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-10-30T12:00:03+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388
time="2020-10-30T12:00:03+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388"
time="2020-10-30T12:00:03+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-10-30T12:00:03+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:03+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-77bc586b59-7mb4h --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:03+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
time="2020-10-30T12:00:03+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
Watching for changes...
[auth] Connected to MongoDb
[auth] Listening on port 5000..
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:06+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:07+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-10-30T12:00:07+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-10-30T12:00:07+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388
time="2020-10-30T12:00:07+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388"
time="2020-10-30T12:00:07+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-10-30T12:00:07+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:07+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-77bc586b59-7mb4h --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:07+02:00" level=warning msg="Skipping deploy due to sync error: copying files: running [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]\n - stdout: \"\"\n - stderr: \"error: Internal error occurred: error executing command in container: container not running (e5d6ccff1b6afa6ab16bf04c1a8023abb142a9f75d195822c9a1ef6a103fac5c)\\n\"\n - cause: exit status 1"
Watching for changes...
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:11+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-10-30T12:00:12+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-10-30T12:00:12+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-10-30T12:00:12+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388
time="2020-10-30T12:00:12+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:2e15e538cb905368441451a6a5084217a7c019b1e1de246f3767fbcf61720388"
time="2020-10-30T12:00:12+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-10-30T12:00:12+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:12+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-77bc586b59-7mb4h --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-10-30T12:00:13+02:00" level=warning msg="Skipping deploy due to sync error: copying files: running [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]\n - stdout: \"\"\n - stderr: \"error: unable to upgrade connection: container not found (\\\"auth\\\")\\n\"\n - cause: exit status 1"
Watching for changes...
```

here is a sync error log:
```
time="2020-10-30T12:00:13+02:00" level=warning msg="Skipping deploy due to sync error: copying files: running [kubectl --context docker-desktop exec auth-depl-6695948f77-nm26d --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]\n - stdout: \"\"\n - stderr: \"error: unable to upgrade connection: container not found (\\\"auth\\\")\\n\"\n - cause: exit status 1"

```
how can i fix it? its real devastating to developed and every thrid change to run skaffold dev
thanks!

**Comment by tejal29** [comment]
@orbb92 Sorry to hear `sync` is working as expected. 
We will try to reproduce the error on our samples. 

If you happen to have your debug logs handy, please feel free to add those. 
`-v=trace`

**Comment by tejal29** [comment]
Thanks for the detailed logs. 

I have a couple of questions. 
1. your deployment.Spec.Replicas for `auth-deploy` is set to 1, however i see 2 pods `auth-depl-6695948f77-nm26d ` and `auth-depl-77bc586b59-7mb4h`.
Do you have a deployment from previous `skaffold run` or `skaffold dev` running?

Looks like the container `auth` wasn't not found for deployment `auth-depl-6695948f77-nm26d `. 
Maybe it is restarting or something and hence skaffold skips the deploy.
```
unable to upgrade connection: container not found (\\\"auth\\\")\\n\"\n - cause: exit status 1"
```

One things skaffold can do is,
1. Continue with re-deploy if any one of many sync succeed and not quit on first sync failure.

**Comment by tejal29** [comment]
@orbb92 Can you please specify the platform i.e. windows or linux.

**Comment by pre** [comment]
Might be related: https://github.com/GoogleContainerTools/skaffold/issues/4246

@orbb92 did you happen to change the namespace of your current context in $KUBECONFIG while Skaffold was running?

**Comment by orbb92** [comment]
> @orbb92 Can you please specify the platform i.e. windows or linux.

windows

**Comment by orbb92** [comment]
> Might be related: #4246
> 
> @orbb92 did you happen to change the namespace of your current context in $KUBECONFIG while Skaffold was running?

no, I even tried to delete all containers, that didn't help.
one thing I noticed is that with js files it works as it should work, I made another project using js and it was perfect

**Comment by orbb92** [comment]
I made another restart to the pods,
here is the logs
`NAME                               READY   STATUS    RESTARTS   AGE
auth-depl-6f87f667cc-q7njm         1/1     Running   0          34s
auth-mongo-depl-86774b995d-ccfbf   1/1     Running   0          34s`


here is another log for the dev

`[auth] Connected to MongoDb
[auth] Listening on port 5000...
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:30+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:31+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-11-03T12:42:31+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-11-03T12:42:31+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0
time="2020-11-03T12:42:31+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0"
time="2020-11-03T12:42:31+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-11-03T12:42:31+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-5777465b6-9wqp9 --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-11-03T12:42:31+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
Watching for changes...
[auth] Connected to MongoDb
[auth] Listening on port 5000....
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:34+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:42:35+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-11-03T12:42:35+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-11-03T12:42:35+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0
time="2020-11-03T12:42:35+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0"
time="2020-11-03T12:42:35+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-11-03T12:42:35+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-5777465b6-9wqp9 --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-11-03T12:42:35+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
Watching for changes...
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:04+02:00" level=debug msg="Change detected notify.Write: \"C:\\Users\\orseg\\Desktop\\Udemy\\sample\\auth\\src\\index.ts\""
time="2020-11-03T12:43:05+02:00" level=debug msg="Found dependencies for dockerfile: [{package.json /app true} {. /app true}]"
time="2020-11-03T12:43:05+02:00" level=debug msg="Skipping excluded path: node_modules"
time="2020-11-03T12:43:05+02:00" level=info msg="files modified: [auth\\src\\index.ts]"
Syncing 1 files for orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0
time="2020-11-03T12:43:05+02:00" level=info msg="Copying files: map[auth\\src\\index.ts:[/app/src/index.ts]] to orbb92/auth1:4ecee56abed4f23b647aca2ee1910a2bc11ce0909334c520dde88e4e6b78a7b0"
time="2020-11-03T12:43:05+02:00" level=debug msg="getting client config for kubeContext: ``"
time="2020-11-03T12:43:05+02:00" level=debug msg="Running command: [kubectl --context docker-desktop exec auth-depl-5777465b6-9wqp9 --namespace default -c auth -i -- tar xmf - -C / --no-same-owner]"
time="2020-11-03T12:43:06+02:00" level=debug msg="Command output: [], stderr: tar: removing leading '/' from member names\n"
Watching for changes...`

when i run kubectl get pods it doesn't show me replicas..

**Comment by briandealwis** [comment]
@orbb92 could you please share your `package.json`?

**Comment by orbb92** [comment]
yeah here it is
`{
  "name": "auth",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "ts-node-dev src/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/cookie-session": "^2.0.39",
    "@types/express": "^4.17.3",
    "@types/jsonwebtoken": "^8.3.8",
    "@types/mongoose": "^5.7.8",
    "cookie-session": "^1.4.0",
    "express": "^4.17.1",
    "express-async-errors": "^3.1.1",
    "express-validator": "^6.4.0",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^5.9.7",
    "ts-node-dev": "^1.0.0-pre.44",
    "typescript": "^3.8.3"
  }
}
`

**Comment by briandealwis** [comment]
From your logs, it looks like the files are being copied across.  But something happens that caused your container to terminate, and hence the sync-errors.

Please try modifying your start script to `ts-node-dev --debug src/index.ts` and see if you get any further information.  But I really expect that you would see an error message from your application if there was some kind of crash.

So my suspicion is that your cluster (minikube?) is hitting a resource problem and the underlying OS is killing your container, or something like that.  If you could try running `kubectl describe deployment/auth-depl` both before and after you do a file save, that might help pin down the issue.

**Comment by BThvedt** [comment]
I'm having the exact same issue on windows .. with a very similar setup - might even be doing the exact same course! Searching for a solution, If I see or figure it out something useful I'll defiantly post it

**Comment by BThvedt** [comment]
In my case, turns out my problem was using docker toolbox for windows. It worked fine up until I tried to use skaffold to watch a typescript file. 
After I switched to docker desktop for windows I no longer had the problem. Of course the switch was a bit of a pain I had to update my windows subsystem for linux from my old version 1 to 2, re download ubuntu for windows, reconfigure my shell console, and update a couple other things ... but, in the end it ultimately worked. I guess the moral is to use docker desktop instead of docker toolbox! 
And when I used ts-node-dev in Ubuntu I had to add the `--poll` flag like this: 
`ts-node-dev --poll filename.ts`

**Comment by briandealwis** [comment]
@orbb92 were you able to try running with `--debug`?

**Comment by briandealwis** [comment]
(Will re-open if we hear more.)

**Comment by Venryx** [comment]
In case Kubernetes newcomers hit the same issue I did, the cause of this error for me was that my "test script" for the server was "completing", which Kubernetes was interpreting as a "failure", causing skaffold-sync to subsequently be unable to function. More info here: https://stackoverflow.com/a/68702549/2441655

(Sorry if it's off-topic to the OP, but I mention it here, because this thread is the top google search result for `skaffold "unable to upgrade connection: container not found"`.)
