### ISSUE TITLE
Skaffold Binary for darwin

### ISSUE THREAD

**Issue by prary** [GoogleContainerTools/skaffold#4977]
Make cross failing for darwin os fails with error.

### Expected behavior
Should build the darwin binary

### Actual behavior
Fails
### Information
docker version 1.13.1
golang 1.15.0
centos vm
Error Logs 
```
Step 11/11 : RUN if [ "$GOOS" = "darwin" ]; then export CC=o64-clang CXX=o64-clang++; fi;     GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=1     go build -tags "${TAGS}" -ldflags "${LDFLAGS}" -o /build/skaffold ./cmd/skaffold
 ---> Running in 43db3c2d762b

# crypto/x509
osxcross: error: targeted OS X version must be <= 10.10.0 (SDK)
osxcross: error: while detecting target
The command '/bin/sh -c if [ "$GOOS" = "darwin" ]; then export CC=o64-clang CXX=o64-clang++; fi;     GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=1     go build -tags "${TAGS}" -ldflags "${LDFLAGS}" -o /build/skaffold ./cmd/skaffold' returned a non-zero code: 2
make: *** [out/skaffold-darwin-amd64] Error 2

```

- Skaffold version: v1.16.0
- Operating system: linux
- Contents of skaffold.yaml:

```yaml
N/A
```

### Steps to reproduce the behavior

1. run make cross It will pass for linux but fails for darwin.

**Comment by tejal29** [comment]
@prary Are you using the  `deploy/cross/Dockerfile`

**Comment by prary** [comment]
yes @tejal29 using make cross which is building this file

**Comment by briandealwis** [comment]
I can't reproduce this @prary — I tried on several machines and the builds ran to completion.

**Comment by tejal29** [comment]
I am going to close this issue since, i also wasn't able to reproduce this. 
Please comment if this issue still exists.
