### ISSUE TITLE
`skaffold render` exits normally when no inputs are found

### ISSUE THREAD

**Issue by ekupershlak** [GoogleContainerTools/skaffold#4979]
### Expected behavior

Running `skaffold render --digest-source=none` using a skaffold.yaml that has no inputs exits with a non-zero 0.

### Actual behavior

skaffold exits with a code of 0.

```
$ skaffold render --digest-source=none
--digest-source set to 'none', tags listed in Kubernetes manifests will be used for render
WARN[0000] k8s-* did not match any file                 
$ echo $?
0
```

### Information

- Skaffold version: v1.16.0
- Operating system: Ubunutu
- Contents of skaffold.yaml: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/skaffold.yaml

### Steps to reproduce the behavior

1. Clone the skaffold project
2. `cd examples/getting-started; rm k8s-pod.yaml`
3. `skaffold render --digest-source=none`

**Comment by tejal29** [comment]
@ekupershlak It does make sense to error out in this case. 
However, by design we always set kubectl deployer as default deployer. 

We had a bunch of discussion here https://github.com/GoogleContainerTools/skaffold/pull/4172 to change that default. 
However, the team felt we shd keep this as is. 

We could error out when kubectl deployer does not end up finding any manifests in the default location.

**Comment by ekupershlak** [comment]
I think the error when no deployer is specified is a bit different - something like:
```
WARN[0000] k8s/*.yaml did not match any file 
```
I agree that this should probably be an error (`k8s/*.yaml` isn't actually in any of my config, so it's an unexpected error message).

I think that I'm describing a slightly different case - I'm proposing treating any case where no manifests are found as an error. Consider the following `skaffold.yaml`.

```
apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - no-such-files-*
```
It specifies a deployer, but the manifests pattern doesn't match anything.

**Comment by nkubala** [comment]
yeah this seems like something we could just validate at runtime. feels like if files are specified in the skaffold.yaml that don't exist we should give an error saying so.

**Comment by aaron-prindle** [comment]
@ekupershlak do you have an small sample repo that this can be reproduced in available?  Thanks.

**Comment by aaron-prindle** [comment]
Can somewhere here verify that the suggested solution - adding a runtime validation on listed files, is acceptable?  Will this break any expected behavior?  Additionally if someone does glob matching on a directly, does there have to be files in that dir (a single blob match)?  Thanks

**Comment by aaron-prindle** [comment]
Talked w/ @nkubala offline, adding notes here:

we do some pre-run config validation, mostly related to modules e.g. making sure all configs have unique names, etc. most of this lives in https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/parser/config.go

[...] probably start here to find the entrypoints where you could add more validation around inputs, etc.

and for globs i think it would be reasonable to make sure at least one file matches the glob pattern passed. e.g. if a user passes k8s/*.yaml and there's either no k8s directory or it's empty, then error out
