### ISSUE TITLE
Deploy - KPT - kustomizeVersionRegexP does not support non-Zulu BuildDate

### ISSUE THREAD

**Issue by DennisVis** [GoogleContainerTools/skaffold#4981]
### Expected behavior
Kustomize versions with a non-Zulu BuildDate and a supported version number should be accepted by the KPT deployer.

### Actual behavior
All `kustomize version` outputs that do not contain a Zulu time for the BuildDate field are treated as invalid by the KPT deployer:
```
unknown kustomize version {Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T07:05:45+01:00 GoOs:darwin GoArch:amd64}
```

### Information
- Skaffold version: v1.16.0
- Operating system: MacOS
- Kustomize version: v3.8.5

### Steps to reproduce the behavior
1. Install a version of Kustomize that has a non-Zulu BuildDate (kustomize/v3.8.5)
2. Run Skaffold with a kpt deploy

**Comment by yuwenma** [comment]
Thanks for catching the issue and the quick fix, Dennis! 

(Do you mind letting me know how you get the kustomize version? I'm wondering why the kustomize version info is different 🤣.  

Your catch really reminds me that in case the users may want to build the kustomize themselves, we actually can further loosen the kustomize version regex. I'll upload a new PR soon.

**Comment by DennisVis** [comment]
I think a warning would be a solid approach here. 

I discovered another discrepancy between the version expected by the KPT deployer and the output of my Kustomize instance; the `kustomize/` prefix. I hadn't even considered the case of users building their own version. So there's already quite a few edge cases to consider.

Doing a sanity check resulting in a warning, stating the minimum version required, would give users the needed info when the deploy breaks due to an unsupported Kustomize version.
