### ISSUE TITLE
Pull all images only using Skaffold

### ISSUE THREAD

**Issue by aryanPatilhm2** [GoogleContainerTools/skaffold#4991]
Hii... It's not an issue. But just wanted to know is there any way in Skaffold to pull all images only which defined in helm configuration. Just like docker-compose pull? I checked the documentation but I didn't find any. I know Skaffold pulls images while starting the app. But I wanted to pull the images only so that my app can start instantly after all images pulled. Is there any way? 

Thanks...

**Comment by tejal29** [comment]
@aryanPatilhm2 Skaffold does not have a command to only pull images. 
have you looked at crane which is a command line tool to interact with remote images. 
https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane.md

Installation https://github.com/google/go-containerregistry/blob/master/cmd/crane/README.md

Skaffold uses the go-containerregistry api

**Comment by nkubala** [comment]
this could also potentially be accomplished with a pre-build hook once we support that. you could use a script to get the images from your helm config and pull them before running the build.

i'll close this for now, but please reopen if you feel the need!
