### ISSUE TITLE
An experimental command to auto convert kubectl deployer to kpt

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4996]
Users can run `skaffold config kpt [--filename]` to convert their skaffold.yaml from using kubectl deployer to kpt deployer.  

--filename refers to the skaffold.yaml, by default, it should be ./skaffold.yaml

Difficulties:
1. kubectl supports `kubectl apply [--flags]`, `kubectl [--global flags]` and `kubectl create [flags]`. These may be incompatible with kpt or may have potential issues. we should clearly deliver the usage message about what the issue is and what change kpt makes.

**Comment by briandealwis** [comment]
`skaffold config` is already used for defining configuration values in the `~/.skaffold/config` file.  But maybe it could be added to `skaffold fix`, or we could have a `skaffold update`?

We could put the unknown kubectl args in comments:
```
   # fix: unable to translate kubectl argument to kpt: --my-whacky-kubectl-arg
```

**Comment by yuwenma** [comment]
obsolete
