### ISSUE TITLE
Enable kaniko with Google Cloud Build?

### ISSUE THREAD

**Issue by LukeeeeBennett** [GoogleContainerTools/skaffold#5004]
I am unsure of how to enable kaniko with Google Cloud Build.

I have read the documentation at https://skaffold.dev/docs/pipeline-stages/builders/

I see reference to kaniko nodes for in-cluster configs. I also see a reference to `kanikoImage` for Google Cloud Build configs, but looking at the extractor used in cloud build logs, it is not using kaniko.

Happy to update documentation when more information is provided.

**Comment by nkubala** [comment]
take a look at https://github.com/GoogleContainerTools/skaffold/tree/master/examples/gcb-kaniko, you should be able to adapt that skaffold config to your project.

going to close this issue for now, but feel free and submit an update to the docs if you think we should make this more visible!
