### ISSUE TITLE
humanize time in "stabilized in 5.23494327s"

### ISSUE THREAD

**Issue by drewpca** [GoogleContainerTools/skaffold#5005]
https://github.com/GoogleContainerTools/skaffold/blob/331da68e249ff6db83038f64513da33fd944ecd5/pkg/skaffold/runner/deploy.go#L160

My preference would be for it to say "5.2 seconds" since 0.1 sec is enough precision for this step. I don't care if it switches to stuff like "821 milliseconds" for short times.

**Comment by tejal29** [comment]
From the chat root, 

```
I've used https://github.com/dustin/go-humanize for this kind of thing in the past, not sure if Skaffold has some standardized library they work with for making time easier for humans to consume
```

**Comment by gunadhya** [comment]
Hi, I'd like to work on this issue.

**Comment by drewpca** [comment]
Thanks, gunadhya!
