### ISSUE TITLE
"workspace" field isn't relative to yaml; but PWD

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#503]
In skaffold v0.5.0 , it appears like "workspace" field is relative to the directory where the command is run (a.k.a. $PWD) rather than the yaml file.

Is this by design and/or the desired behavior?

For example, if I have a `voting-app` in my current dir ($PWD) and this yaml at `./skaffold/skaffold.yaml`:

```
  - imageName: vote
    workspace: ../voting-app/vote/
```

I expect that the workspace will be computed relative to `./skaffold` not $PWD(=`.`).

**Comment by thomas-riccardi** [comment]
Other relative paths should probably be changed to be relative to the `skaffold.yaml` file:
- #387 
- #501
- probably more

cf https://github.com/GoogleContainerTools/skaffold/issues/387#issuecomment-384860695

**Comment by balopat** [comment]
I agree that this is counter-intutitive but we'll have to be careful not to break people who are already using path resolution the current way. It would be great to have more feedback/support from the community around this.

**Comment by mistereechapman** [comment]
Its becoming a bit of a mess, a bit more control over the docker file build would be great. <- feed back and support in a line 👍 

Skaffold v1.0.0 issue
Even adding the workspace prop on the docker build definition would help us

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
