### ISSUE TITLE
Regression causing --mount option to break skaffold build

### ISSUE THREAD

**Issue by shaxbee** [GoogleContainerTools/skaffold#5049]
### Expected behavior

Dockerfile with `# syntax = docker/dockerfile:1-experimental` and `RUN --mount=<value> <cmd>` no longer works on master.

### Actual behavior

Dockerfile with `dockerfile:1-experimental` syntax should work.

### Information

- Skaffold version: master
- Operating system: macOS

### Steps to reproduce the behavior

Added test case to [pkg/skaffold/docker/dependencies_test.go](https://github.com/GoogleContainerTools/skaffold/compare/master...shaxbee:bug-buildkit-dependency-resolve#diff-60da1d62ea286ae7cdadb04f16157c056600acd3293e174664ee5f6b2dee72ff).

This is ultimately failing in [pkg/skaffold/docker/parse.go#L81](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/docker/parse.go#L81).

**Comment by shaxbee** [comment]
After commenting out the code in pkg/skaffold/docker/parse.go it passes the dependency check but fails at build.
Running latest stable release that does not happen though, wonder if it could be related to [pkg/skaffold/build/docker/docker.go#L49](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/build/docker/docker.go#L49), there used to be check for buildkit there.

**Comment by MarlonGamez** [comment]
@shaxbee thanks for opening this! I'll take a look at your PR
