### ISSUE TITLE
Skaffold build failing on AWS Linux 2 machine using custom buildCommand

### ISSUE THREAD

**Issue by afickley5** [GoogleContainerTools/skaffold#5062]
### Expected behavior

Running skaffold build results in a successfully-built container that can be deployed in the deploy section.

### Actual behavior

While `docker build .` results in a successfully-built image, `skaffold run`, `skaffold dev`, and `skaffold build` all fail on step 1/4 "FROM nginx:1.13.9-alpine"

`docker build .` (this runs successfully):

```
$ docker build .
Sending build context to Docker daemon  18.48MB
Step 1/4 : FROM nginx:1.13.9-alpine
1.13.9-alpine: Pulling from library/nginx
ff3a5c916c92: Pull complete 
b4f3ef22ce5b: Pull complete 
8a6541d11dc3: Pull complete 
7e869e2dcf68: Pull complete 
Digest: sha256:48947591194ac5a9dce1e110f9198a547debb21630f121081640b87d99ca8b11
Status: Downloaded newer image for nginx:1.13.9-alpine
 ---> 537527661905
Step 2/4 : COPY ./build/ /usr/share/nginx/html
 ---> 45b6d1c305f9
Step 3/4 : EXPOSE 80
 ---> Running in cd028fcf6c16
Removing intermediate container cd028fcf6c16
 ---> e6d96830d924
Step 4/4 : CMD ["nginx", "-g", "daemon off;"]
 ---> Running in 013a116127ca
Removing intermediate container 013a116127ca
 ---> 186dc2af88c7
Successfully built 186dc2af88c7
```

skaffold run (this fails): 
```
 Step 1/4 : FROM nginx:1.13.9-alpine
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
couldn't build "admin-app": building custom artifact: exit status 1
```

skaffold dev (this fails): 
```
 => ERROR [internal] load metadata for docker.io/library/node:10-buster   20.0s
 => ERROR [1/7] FROM docker.io/library/node:10-buster                     20.0s
 => => resolve docker.io/library/node:10-buster                           20.0s
 => [internal] load build context                                          0.0s
------
 > [internal] load metadata for docker.io/library/node:10-buster:
------
------
 > [1/7] FROM docker.io/library/node:10-buster:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head https://registry-1.docker.io/v2/library/node/manifests/10-buster: dial tcp: lookup registry-1.docker.io on 192.168.49.1:53: read udp 192.168.49.2:35434->192.168.49.1:53: i/o timeout
exiting dev mode because first build failed: couldn't build "admin-app": building custom artifact: exit status 1
```

### Information

- Skaffold version: 1.9.1
- Docker version: Docker 19.03.13-ce
- Minikube version 1.15.1
- Operating system: AWS Linux 2 WorkSpace (~CentOS?)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: { variant: AbbrevCommitSha }
  artifacts:
    - image: admin-app
      custom:
        buildCommand: "yarn install && yarn run build && docker build -t $IMAGE ."
deploy:
  helm:
    releases:
      - name: admin-app
        chartPath: <redacted>
        remote: true
        values:
          image: admin-app
        valuesFiles:
          - values/values.yaml
        version: 0.4.0
    flags:
      install: [--create-namespace]
      upgrade: [--create-namespace]
```

### Steps to reproduce the behavior

1. Create a skaffold.yaml file with a custom: buildCommand section, like the one above, on an AWS Linux 2 machine with Skaffold 1.9.1, Docker 19.03.13-ce, and yarn 1.22.10 installed
2. `skaffold build`

Notes: 

- This skaffold file and set of commands works fine while on MacOS Catalina using the same skaffold and Docker versions
- This skaffold file and set of commands works fine while on Ubuntu 20.04 using the same skaffold and Docker versions
- Skaffold builds fine for other projects of ours in the AWS Linux 2 machine when using the jib build command (rather than custom/docker)

**Comment by gsquared94** [comment]
@nkubala do we have an account to test on AWS?

**Comment by afickley5** [comment]
Thanks for looking into this - providing an update here so folks don't spin their wheels. 

After further investigating, it turns out that this is really an issue with Minikube on AWS Linux 2 WorkSpaces not being able to properly resolve some domain names (which was preventing Minikube's Docker daemon from reaching out and grabbing images). We worked around the issue by creating a squid proxy and were able to progress our efforts. 

We can close this issue, as it is not a Skaffold bug. We will be opening a bug with Minikube to investigate.
