### ISSUE TITLE
Linux and Windows v1.17.0 asset is actually v1.15.0

### ISSUE THREAD

**Issue by maximerassi** [GoogleContainerTools/skaffold#5073]
# Regarding the latest v.1.7.0 github release:
https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.17.0

# Issue
The binary for windows attached in the **assets** section of the release is still showing v1.15.0.
```
❯ skaffold version
v1.15.0
```
However the direct googleapis.com downlink listed in the notes looks fine.
```
❯ skaffold version
v1.17.0
```

**Comment by othercorey** [comment]
I can confirm this. `1.16.0` shows the right version but `1.17.0` release shows `1.15.0`.

The sha for `1.17.0` and `1.15.0` are the same.

**Comment by foosinn** [comment]
seems to be also true for the latest linux version:

```
$ cd $(mktemp -d)
$ wget https://github.com/GoogleContainerTools/skaffold/releases/download/v1.17.0/skaffold-linux-amd64
$ chmod +x skaffold-linux-amd64
$ ./skaffold-linux-amd64 version
v1.15.0
```

**Comment by oradwell** [comment]
@maximerassi can you modify the title to show that version for linux is also broken? perhaps something like "v1.17.0 release tagged as v1.15.0"

**Comment by nkubala** [comment]
hey all, we had an issue with our release automation that required a manual release for v1.17.0, which opened a window to introduce human error which I of course took advantage of :) 

I believe I've fixed the uploaded binaries on the release page. @maximerassi @othercorey @foosinn if any of you can verify then I'll close this issue.

**Comment by othercorey** [comment]
I can confirm v1.17.0 shows correctly now on windows.

**Comment by gsquared94** [comment]
I've checked and the linux binary is now 1.17.0 as well. Closing this issue.
