### ISSUE TITLE
Stop supporting helm v3 beta version

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#5081]
In one of the code review comments #5069, @briandealwis suggested, we could stop checking for helm 3 beta versions. 

Investigate and address the issues with updating tests.

**Comment by tejal29** [comment]
relates to #5442
Please check if this is already implemented

**Comment by aaron-prindle** [comment]
Our helm deployer no longer supports helm versions less than `Helm v3.1+` as we use the `--post-renderer` support which has this pre-requisite -  https://helm.sh/docs/topics/advanced/#prerequisites
