### ISSUE TITLE
WSL detection logic for minikube binary is flawed

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#5085]
Related #5054 

If Skaffold detects execution to be within WSL [it always sets ](https://github.com/GoogleContainerTools/skaffold/blob/1ae3284a93ceab53d52723af861dfd6db708983e/pkg/skaffold/cluster/minikube.go#L99)the minikube binary name to `minikube.exe`. This isn't always the case since with WSL2 Docker integration we can launch `minikube start --driver=docker` directly from within the WSL.
The fix would be to fallback on using the windows minikube executable only if it's not found on the WSL directly.

```go
func minikubeBinary() (string, error) {
	filename, err := exec.LookPath("minikube")
	if err != nil {
		if found, _ := util.DetectWSL(); found {
			filename, err = exec.LookPath( "minikube.exe")
		}
		if err != nil {
			return "", errors.New("unable to find minikube executable. Please add it to PATH environment variable")
		}
	}
	if _, err := os.Stat(filename); os.IsNotExist(err) {
		return "", fmt.Errorf("unable to find minikube executable. File not found %s", filename)
	}
	return filename, nil
}
```

**Comment by IsaacPD** [comment]
I'm not too sure it even makes sense to fall back to "minikube.exe" ever if you're in WSL. The kube context locally would not be "minikube" if you were to run "minikube.exe" from within WSL and would simply not work. It may be best just removing this detection behavior entirely.

**Comment by go-nelango** [comment]
@gsquared94 will this fix be in the next skaffold release?

**Comment by gsquared94** [comment]
@go-nelango yes, it should be part of the next release.

**Comment by go-nelango** [comment]
Thanks @gsquared94 ! When is the new version expected to be available in gcloud?

**Comment by nkubala** [comment]
I think their release cadence is weekly on Thursdays? I should have their code updated to the new binary tomorrow so whenever their next release goes out.
