### ISSUE TITLE
update render doc to include kpt

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#5094]
https://skaffold.dev/docs/pipeline-stages/deployers/

**Comment by tejal29** [comment]
@yuwenma Can you please also add kind e.g. kind/docs and priority for the bugs created. 
Unkinded and unprioritized bugs are caught by our triage filter.

Thanks
Tejal

**Comment by yuwenma** [comment]
> @yuwenma Can you please also add kind e.g. kind/docs and priority for the bugs created.
> Unkinded and unprioritized bugs are caught by our triage filter here [skaffold-triage-party-eyodkz2nea-uc.a.run.app/s/daily](https://skaffold-triage-party-eyodkz2nea-uc.a.run.app/s/daily)
> Thanks
> Tejal

Gotcha! Is there any doc i can read that describe how each label should be used? I was thinking of priorities but not sure what P0 P1 mean to OSS repo. And I guess I misused `area/doc` label in lieu of `kind/doc` 😅
