### ISSUE TITLE
Custom tagging based on contributing files - eg digest-tagger

### ISSUE THREAD

**Issue by robertgates55** [GoogleContainerTools/skaffold#5103]
Not an issue, but wanted to check the latest guidance on tagging.

We have a mono-repo setup containing multiple projects (`project1/`, `project2/`); producing multiple artifacts. We have one top-level skaffold.yaml referencing all of the artifacts.

## Desired outcome
If I change a file in `project1/` that is required by `project1/Dockerfile`, the resulting artifact gets a new tag. Otherwise, it gets the same tag.

## Actual outcome
- if using `gitCommit:` tagger, I obviously get a commit corresponding to the whole workspace, not the specific context
- if using `sha256:` tagger, I can build the images and output the resulting digest tags. I can then use these later on instead of `latest`. However, if I delete an image and rebuild it (or use a different machine), I get a different digest (because of how docker works) despite the inputs being (to all intents and purposes) the same

## Things I've Tried
- using `custom:` builder, implemented a small script that generates checksums based on the input Dockerfiles, and retags appropriately. I suspect this is what skaffold caching is doing under the covers too.
- various other cache-sharing approaches, trying to ensure identical docker digests for 'identical' inputs

Is there anything more I can try here? Or anything in the works that'll make this possible? The tickets below are the relateds I've seen.

https://github.com/GoogleContainerTools/skaffold/issues/2162
https://github.com/GoogleContainerTools/skaffold/pull/2301
https://github.com/GoogleContainerTools/skaffold/pull/2804

**Comment by briandealwis** [comment]
@robertgates55 you can use the [`gitCommit` tagger's](https://skaffold.dev/docs/references/yaml/#build-tagPolicy-gitCommit) `TreeSha` or `AbbrevTreeSha` variants to get the _sub-tree hash_ of the artifact directory.  This sub-tree hash is not the same as the commit that changed it, but it does uniquely identify the contents.

**Comment by robertgates55** [comment]
Yep - thanks - that's clearly closer, and I realised it soon after creating this ticket!

Interestingly though, as we've also started using skaffold artifact dependencies, this approach starts to fall down:

```
common/
svc1/
svc2/
```

If we use artifactDependencies to build `common` and then consume the result within `svc1` and `svc2`; then a change in `common` won't cause the `TreeSha` tags of `svc1` or `svc2` to change at all. Which is clearly an issue.

Likewise, there are sometimes changes within `svc1/` that may have no bearing on the image that we produce...

Am interested in if there's been any progress on https://github.com/GoogleContainerTools/skaffold/blob/master/docs/design_proposals/digest-tagger.md or whether there's another approach to project structure we should be considering to better fit within the existing taggers?

**Comment by nkubala** [comment]
@robertgates55 we've since implemented an [`InputDigestTagger`](https://github.com/GoogleContainerTools/skaffold/pull/5192) that I believe accomplishes exactly what you're looking for here (though we're still lacking documentation on this feature and are planning on adding it soon).  I'm going to close this issue because I think it addresses your use case (including the artifact dependencies issue), but please reopen if you think it doesn't!
