### ISSUE TITLE
Consider extending default status check timeout

### ISSUE THREAD

**Issue by fsladkey** [GoogleContainerTools/skaffold#5106]
## Consider extending default status check timeout

After discussing some deployments that (due to automatic cluster scaling) often took longer than the two minute status-check timeout, @tejal29 mentioned that because status checks now fail deployments immediately if they encounter an irrecoverable error, it may be desirable to extend the default status check timeout. Creating this issue for further discussion.

**Comment by tejal29** [comment]
Thanks @fsladkey for opening the issue. I have added this in next milestone.

**Comment by tejal29** [comment]
Sorry this spilled my attention. 
I will try to see if we can make this happen this release. 
/cc @gsquared94 , @nkubala , @marlon-gamez @IsaacPD any takers?

**Comment by MarlonGamez** [comment]
@tejal29 I can work on this 👍 do we have an idea of what the default timeout should be set to?

**Comment by tejal29** [comment]
The default time should be 10 mins which is the default for deployments to stabilize.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment
