### ISSUE TITLE
Skaffold with kustomize invokes multiple versions of the resources

### ISSUE THREAD

**Issue by dindurthy** [GoogleContainerTools/skaffold#5109]
### Expected behavior
`skaffold dev` deploys kustomized version of the app

### Actual behavior
`skaffold dev` runs a `kubectl apply -f -` of the un-kustomized manifests, `kustomize build`, and then another `kustomize apply -f -`

I don't think this is `dev` specific, I think it's a `deploy` thing.

### Information

- Skaffold version: 1.16.0
- Operating system: MacOs
- Contents of skaffold.yaml:

```yaml
{
    "apiVersion":"skaffold/v2alpha3",
    "kind":"Config",
    "build":{
        "artifacts":[
            {
                "image":<unkustomized image>
                "context":<path to module>
            }
        ],
        "local":{
            "useBuildkit":True
        },
        "tagPolicy":{
            "envTemplate":{
                "template":<tag>
            }
        }
    },
    "deploy":{
        "kubectl":{
            "manifests":[
                <path-to-manifest>
            ]
        },
        "statusCheckDeadlineSeconds":600,
        "kustomize":{
            "paths":[
                <path-to-kustomize>
            ]
        }
    }
}
```

```kustomization.yaml
images:
- name: <unkustomized image>
  newName: <kustomized image>
resources:
- <path-to-manifest>
```

### Steps to reproduce the behavior

1. `skaffold dev` a module with the above specs. You should see the old and new pods/jobs.

I can see the sequence of kubectl commands in the debug log:

```
kubectl --context <cluster> create --dry-run -oyaml <manifest>
kubectl --context <cluster> get -f - --ignore-not-found -ojson
kubectl --context <cluster> apply -f - --force --grace-period=0
<this creates unkustomized resources>
kubectl --context <cluster> get -f - --ignore-not-found -ojson
kustomize build <path-to-kustomize>
kubectl --context <cluster> -f - --force --grace-period=0
<now we have kustomized resources>
```

Forgive me if this has been documented somewhere. I didn't find the issue or documentation -- definitely could have missed it.

I believe this worked differently in older versions, i.e. an unkustomized version of the service was never applied. The create/update approach causes a number of issues beyond confusion. For example, `skaffold dev` for a job that runs tests against a database is vulnerable to the unkustomized job polluting the state. `skaffold run` won't work for jobs without a `--force` even if it's run from scratch. We've run into an analogous issue with testing a postgres upgrade with skaffold and a pvc. The unkustomized postgres version mounts and initializes the new pvc before the kustomized version, and the upgraded postgres errors when detecting a filesystem initialized by the lower version. It would be so great if we didn't have the unkustomized deployment or could turn it off somehow.

**Comment by gsquared94** [comment]
I think that the explicit `kubectl` deploy stanza in your `skaffold.yaml` causes the _unkustomized_ deployment of your resources. Can you try removing them. Only defining the `kustomize` stanza should be sufficient to subsequently trigger a `kubectl` deployment of the _kustomized_ manifests.
Also take a look at the [getting started](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started-kustomize/skaffold.yaml) example. 

```diff
{
    "apiVersion":"skaffold/v2alpha3",
    "kind":"Config",
    "build":{
        "artifacts":[
            {
                "image":<unkustomized image>
                "context":<path to module>
            }
        ],
        "local":{
            "useBuildkit":True
        },
        "tagPolicy":{
            "envTemplate":{
                "template":<tag>
            }
        }
    },
    "deploy":{
-       "kubectl":{
-           "manifests":[
-               <path-to-manifest>
-           ]
-        },
        "statusCheckDeadlineSeconds":600,
        "kustomize":{
            "paths":[
                <path-to-kustomize>
            ]
        }
    }
}
```

Let us know if that worked out, otherwise please add the logs of running with `-v DEBUG` flag.

**Comment by dindurthy** [comment]
That's it. Oof, I should have tried that given that kubectl and kustomize are sibling keys. Makes perfect sense. Thanks so much.
