### ISSUE TITLE
Make a util to hold the common cmd functionality

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5116]
Make a util to hold the common cmd functionality:
1. Create a util to hold the common cmd functionality
2. Move vars to flags and add them the to common flags registry

**Comment by tejal29** [comment]
@PriyaModali  
Can you please also add kind e.g. kind/docs and priority for the bugs created.
Unkinded and unprioritized bugs are caught by our triage filter here https://skaffold-triage-party-eyodkz2nea-uc.a.run.app/s/daily

Thanks
Tejal
