### ISSUE TITLE
helm doesn't appear to update resources when changed

### ISSUE THREAD

**Issue by shimmerjs** [GoogleContainerTools/skaffold#514]
### Expected behavior
The helm chart installed via `skaffold dev` should reflect changes made between iterations to the local chart.

### Actual behavior
If you've already started `skaffold dev`, then update your chart, then trigger an iteration by changing your source code (because changing the helm chart files themselves wont trigger it #235), your old chart definitions will still be applied until you kill `skaffold dev` and restart it.  I suspect this issue is actually the same or closely tied to #235, but I wanted to make sure this was captured in case it wasn't, because the issue isn't specifically that the chart resources are not being watched, but aren't being updated at all even when other resource changes trigger a `skaffold dev` build/deploy iteration.

### Information

```
Skaffold version: 0.4.0
Operating system: OSX 10.13.4
Content of skaffold.yaml:
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
    gitCommit: {}
  artifacts:
  - imageName: registry.ng.bluemix.net/dev-infra/grady
    workspace: .
    docker: {}
  local: {}
deploy:
  helm:
    releases:
    - name: grady-alex-weidner
      chartPath: .
      namespace: alex-weidner-dev
      values:
        image: registry.ng.bluemix.net/dev-infra/grady
```

### Steps to reproduce the behavior

  1. Run `skaffold dev` against helm example.
  2. Comment out any chart template resource, add a line to any file in the workspace, press save.  Chart will successfully install even though it should be invalid.

**Comment by r2d4** [comment]
Fixed in #765
