### ISSUE TITLE
Cleanup the term 'artifact' in skaffold docs

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5148]
We should try not to use the term artifact in our docs if we can avoid it. It's not really a concept that has meaning outside of skaffold, so it's fine to use in code (e.g. for function names) but we shouldn't use it when talking about real concepts in docs.

**Comment by briandealwis** [comment]
Artifact are containers that were built via Skaffold.  So they do represent something distinct.

**Comment by nkubala** [comment]
we can address this soon when we put some time into overhauling our docs.

**Comment by techchickk** [comment]
Gaurav is suggesting that we mark this as resolved due to the fact that the word Artifact is well-defined in terms of Skaffold.

**Comment by aaron-prindle** [comment]
@techchickk good idea, marking resolved
