### ISSUE TITLE
Support compose files

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#517]
Here's a silly idea: Why don't we support running Skaffold with just a compose file. No skaffold.yaml.

 + The list of artifacts can be guessed from the compose file. They are all of `docker build` type.
 + We would deploy using `kubectl` deployer. Transformation from the compose file to Kubernetes manifests could be done using [Kompose](https://github.com/kubernetes/kompose)
 + Everything else works the same. `skaffold dev` would still watch artifact dependencies and show the aggregated logs.

**Comment by dgageot** [comment]
Duplicate of #727

**Comment by dlorenc** [comment]
This isn't a duplicate?

**Comment by balopat** [comment]
closing in favor of #1195 and #1273.
