### ISSUE TITLE
Dockefiles using BuildKit feature Build Cache Mounts cannot be parsed

### ISSUE THREAD

**Issue by uvegla** [GoogleContainerTools/skaffold#5178]
### Expected behavior
Dockerfiles using BuildKit feature [Build Cache Mounts](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache) can be parsed by Skaffold.

### Actual behavior
If the Dockerfile contains a layer with for example `RUN --mount=type=cache,id=my-cache,target=/mnt/cache ...` then Skaffold fails in the Build stage with an error message similar to:

```
watching files for artifact "skaffold-helm": listing files: parsing dockerfile "<PATH_TO_DOCKERFILE>": Dockerfile parse error line <N>: Unknown flag: mount
```

### Information

- Skaffold version: v1.17.2
- Operating system: macOS Catalina 10.15.6
- Docker version: Docker Desktop 3.0.3 (Engine: 20.10.0)

The last Skaffold version that I have tried with and was working is `v1.14.0`. Not tested with any version between that and `v1.17.2`.

### Steps to reproduce the behavior

I reproduced it by making some slight modifications to the [helm-deployment example](https://github.com/GoogleContainerTools/skaffold/tree/531adb67bdf27f2b598cd260e625b827cf43caa1/examples/helm-deployment).

To skaffold.yaml I added `build.local. useBuildkit` as `true`. Contents after modification:

```yaml
apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      artifactOverrides:
        image: skaffold-helm
```

To Dockerfile I added a dummy layer that utilizes the build cache feature.

```Dockerfile
FROM golang:1.12.9-alpine3.10 as builder
COPY main.go .
# `skaffold debug` sets SKAFFOLD_GO_GCFLAGS to disable compiler optimizations
ARG SKAFFOLD_GO_GCFLAGS
RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app main.go
RUN --mount=type=cache,id=my-cache,target=/mnt/cache touch /mnt/cache/test.txt

FROM alpine:3.10
# Define GOTRACEBACK to mark this container as using the Go language runtime
# for `skaffold debug` (https://skaffold.dev/docs/workflows/debug/).
ENV GOTRACEBACK=single
CMD ["./app"]
COPY --from=builder /app .
```

If I run `skaffold dev -f skaffold.yaml` on this modified file I get the following error.

```
Listing files to watch...
 - skaffold-helm
watching files for artifact "skaffold-helm": listing files: parsing dockerfile "<PATH_TO_SKAFFOLD_REPO>/examples/helm-deployment/Dockerfile": Dockerfile parse error line 6: Unknown flag: mount
```

The Dockerfile simply builds without Skaffold using `DOCKER_BUILDKIT=1 docker build -f Dockerfile .`.

**Comment by IsaacPD** [comment]
This should have just been fixed with #5052, so by v1.18.0 or the next release this should be out, or you can use the bleeding edge version described here https://skaffold.dev/docs/install/
