### ISSUE TITLE
Limit skaffold run by artifact scope

### ISSUE THREAD

**Issue by l2silver** [GoogleContainerTools/skaffold#521]
### Expected Behaviour
skaffold run --artifact=leeroy-web

### Actual behavior
No ability to limit scope, so every time you need to redeploy, you need to run skaffold for everything

### Information
Basically, if you're not able to run skaffold dev for what ever reason, then executing skaffold run can be unnecessarily time consuming. It would be great if there was a way to limit skaffold run to a specific artifact workspace (or some other means, maybe regex workspace name).

Thanks

**Comment by dgageot** [comment]
We could even simplify to `skaffold run [artifact1] [artifact2]`

**Comment by dgageot** [comment]
However, the mapping between artifacts and k9s manifests is not always 1:1

**Comment by l2silver** [comment]
Agreed. The solution might have to be a little more verbose, but I'd rather that than nothing.

**Comment by balopat** [comment]
This looks like a useful feature but not super high on our priority list. If somebody is interested in picking it up, please let us know, we welcome PRs!!!
