### ISSUE TITLE
Is there a skaffold "debug" image that includes a shell?

### ISSUE THREAD

**Issue by cmamigonian** [GoogleContainerTools/skaffold#5218]
Basically this is just a question to see if `skaffold` has a "debug" image that comes with a shell so that someone can attach to a container and subsequently run `skaffold <cmd>`.  I thought I had seen somewhere that there was, but I can't find that statement again.  This is particularly useful for using `skaffold` in Jenkins CI in Kubernetes where a stage's steps has to be run in a shell.

**Comment by cmamigonian** [comment]
Man I'm pretty dumb.  I thought I had checked if the basic `k8s-skaffold/skaffold` image had a shell and found it didn't, but double checking it clearly does.

**Comment by nkubala** [comment]
😄
