### ISSUE TITLE
Excessive line breaks in output logs

### ISSUE THREAD

**Issue by redborian** [GoogleContainerTools/skaffold#5228]
![image](https://user-images.githubusercontent.com/6260897/104495220-55e84580-558c-11eb-83aa-456b7706bd41.png)

### Expected behavior
The output logs do not contain excessive line breaks

### Actual behavior
The output logs contain excessive line breaks

### Information

- Skaffold version: v1.17

### Steps to reproduce the behavior

1. Perform a deployment in Cloud Code and observe the logs emitted by Skaffold

**Comment by gsquared94** [comment]
These messages are outputted to the event API. I don't think we add the excessive line breaks in Skaffold. Does  https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/pull/3915 fix this?

**Comment by IsaacPD** [comment]
@gsquared94 That issue you linked is in a private repo so we can't see it 😓

**Comment by briandealwis** [comment]
This text is generated from events raised by Skaffold, and those event messages do not include newlines.  The newlines are being added within CC-VSC.

https://github.com/GoogleContainerTools/skaffold/blob/e6b27a55bd2b092e412ca68fee1de15257575705/pkg/skaffold/event/event.go#L546-L555
