### ISSUE TITLE
Maven builds sometimes fail with connection resets

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5248]
Seen on Travis surprisingly often:
```
        [builder] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project hello-spring-boot: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test failed: Plugin org.apache.maven.plugins:maven-surefire-plugin:2.21.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.surefire:surefire-api:jar:2.21.0, org.apache.maven.surefire:surefire-logger-api:jar:2.21.0: Could not transfer artifact org.apache.maven.surefire:surefire-api:jar:2.21.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-api/2.21.0/surefire-api-2.21.0.jar: Connection reset -> [Help 1]
```

Similar complaints abound on the internet.  Suspicion is that Maven Central's CDN times out connections resulting in a connection reset.

Some relevant reading:
- [WAGON-545](https://issues.apache.org/jira/browse/WAGON-545) and [WAGON-603](https://issues.apache.org/jira/browse/WAGON-603)
- actions/virtual-environments/issues/1499

**Comment by briandealwis** [comment]
Still [being seen](https://api.travis-ci.com/v3/job/473945864/log.txt):
```        [builder] [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:repackage (default) on project hello-spring-boot: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE:repackage failed: Plugin org.springframework.boot:spring-boot-maven-plugin:2.0.5.RELEASE or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-archiver:jar:2.6 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/2.6/maven-archiver-2.6.jar: Connection reset -> [Help 1]

```

**Comment by briandealwis** [comment]
[Maven Wagon HTTP defaults](https://github.com/apache/maven-wagon/blob/master/wagon-providers/wagon-http-shared/src/main/java/org/apache/maven/wagon/shared/http/AbstractHttpClientWagon.java):
- `maven.wagon.http.retryHandler.class` = `standard`
- `maven.wagon.http.retryHandler.requestSentEnabled` = `false`
- `maven.wagon.http.retryHandler.count` = 3

The default retry handler (`DefaultHttpRequestRetryHandler`) defaults to [not retrying the following classes](https://hc.apache.org/httpcomponents-client-4.5.x/httpclient/apidocs/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.html#DefaultHttpRequestRetryHandler(int,%20boolean)): `InterruptedIOException`, `UnknownHostException`, `ConnectException`, `SSLException`

**Comment by briandealwis** [comment]
Placing the following into `<top-level>/.mvn/jvm.config` seems to do the trick:
```
-Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true
```

From [stack-traces](https://stackoverflow.com/q/42024619/600339) the connection reset is raised in a `java.net.SocketException `, so if using the `default` retry-Handler (which isn't actually the default) will require explicitly specifying the `maven.wagon.http.retryHandler.nonRetryableClasses` property.

**Comment by briandealwis** [comment]
Still happening in the buildpacks tests ([log](https://api.travis-ci.com/v3/job/474501268/log.txt) from #5279)

**Comment by hligit** [comment]
@briandealwis  I think the [standard](https://github.com/apache/httpcomponents-client/blob/6a741b4f8f23e6c5c7cc42c36c2acabfac19c3d6/httpclient/src/main/java/org/apache/http/impl/client/StandardHttpRequestRetryHandler.java#L58) retryHandler simply uses the `DefaultHttpRequestRetryHandler` and [won't retry](https://github.com/apache/httpcomponents-client/blob/6a741b4f8f23e6c5c7cc42c36c2acabfac19c3d6/httpclient/src/main/java/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.java#L139-L141) on the same [list](https://github.com/apache/httpcomponents-client/blob/6a741b4f8f23e6c5c7cc42c36c2acabfac19c3d6/httpclient/src/main/java/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.java#L104-L108) of nonRetriableClasses. Probably need to configure `maven.wagon.http.retryHandler.nonRetryableClasses` to something like below?
```
java.io.InterruptedIOException,java.net.UnknownHostException,java.net.NoRouteToHostException,javax.net.ssl.SSLException
```
