### ISSUE TITLE
Registry synonym

### ISSUE THREAD

**Issue by LeDominik** [GoogleContainerTools/skaffold#5257]
I have the situation that on OpenShift (and this seems to be normal here) that there's two URL's for an image. These "image streams" show two urls: Image Repository (what I need in my K8S yaml's) and Public Image Repository (what I use in Skaffold / jib /...). Different hostname/port but same path. Now of course skaffold tells me that it doesn't know the image that is in the YAML because it's not _exactly_ the same.

My wish: some simple way to define a synonym for the image repo so that skaffold can correctly link it up and set the tag...

I googled a lot but couldn't find a decent solution 😞

**Comment by briandealwis** [comment]
Duplicate of #3461
