### ISSUE TITLE
v1.18.0 Release "our design document" broken link

### ISSUE THREAD

**Issue by dsutphin** [GoogleContainerTools/skaffold#5278]
The "our design document" link goes to https://github.com/GoogleContainerTools/skaffold/blob/v1.18.0/tinyurl.com/skaffold-multi-configs which is invalid.

**Comment by IsaacPD** [comment]
Thanks, Good catch! I just edited it, as i'm sure you are aware the proper link should be https://tinyurl.com/skaffold-multi-configs
