### ISSUE TITLE
Errors passing JSON --artifact to skaffold init in version 1.18.0

### ISSUE THREAD

**Issue by fsladkey** [GoogleContainerTools/skaffold#5296]
## Errors passing JSON --artifact to skaffold init in version 1.18.0

Hey Skaffold folks, just ran into this after upgrading and wondering if it's a mistake on my part, a bug or perhaps the expected format has changed.

### Expected behavior
When running `skaffold init` with `--artifact` flag with JSON, the command should create a `skaffold.yaml` file.

Command:
`skaffold init --force --artifact='{"builder":"Docker","payload":{"path":"Dockerfile"},"image":",java-hello-world"}' `

### Actual behavior

Command fails with error `invalid argument "{\"builder\":\"Docker\",\"payload\":{\"path\":\"Dockerfile\"},\"image\":\"java-hello-world\"}" for "-a, --artifact" flag: parse error on line 1, column 1: bare " in non-quoted-field`.

The command succeeds when using skaffold `1.17.2`.

### Information

- Skaffold version: 1.18.0
- Operating system: Mac OS
- Contents of skaffold.yaml: N/A (generating config with command)

### Steps to reproduce the behavior

1. Clone `https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world`
2. Delete existing `skaffold.yaml` file.
2. Run `skaffold init --force --artifact='{"builder":"Docker","payload":{"path":"Dockerfile"},"image":"java-hello-world"}' `
3. Encounter parse error.

**Comment by nkubala** [comment]
this does seem like a regression, though I'm not entirely sure which change caused it. cc @MarlonGamez any ideas?

**Comment by briandealwis** [comment]
`git bisect` reports that it was caused by #5120.

**Comment by IsaacPD** [comment]
Ah that looks like it's me then, I'll take a look at what it could be.

**Comment by MarlonGamez** [comment]
@IsaacPD Looks like the issue is just that the flag add method needs to be defined as StringArrayVar. With #5120 it's getting auto set to StringSliceVar which is causing the issue

**Comment by fsladkey** [comment]
Thanks everyone!
