### ISSUE TITLE
skaffold dependency resolving (for file sync) is not recursive

### ISSUE THREAD

**Issue by kervel** [GoogleContainerTools/skaffold#5301]
### Expected behavior

I use skaffold with multiple artifacts that are dependent one on another. In the "parent" artifact, the dockerfile contains an ADD statement. The parent artifact is not actually used, its just some common stuff that gets pushed to all child artifacts that then are used in a helm chart.

I'd like to sync my files directly to the "children".

### Actual behavior

Skaffold detects the ADD statement correctly and creates sync file watchers for it. however, i won't sync to the parent artifact since there is no container running with that artifact. I want to sync directly to the "children". This won't work (even with a manual sync setting) since the children only depend on their parent and their Dockerfile. So skaffold doesn't monitor the right files for the children.

### Information

- Skaffold version: git master
- Operating system: linux
- Contents of skaffold.yaml:

### Suggested fix

As a workaround i patched the dev.go in skaffold/runner to find dependencies recursively. I added this function to SkaffoldRunner:

```go
func (r *SkaffoldRunner) DependenciesForArtifactRecursive(ctx context.Context, out io.Writer, artifacts []*latest.Artifact, artifact *latest.Artifact) ([]string, error) {
	paths, err := build.DependenciesForArtifact(ctx, artifact, r.runCtx, r.artifactStore)
	for _, img := range artifact.Dependencies {
		n := img.ImageName
		for _, a := range artifacts {
			if a.ImageName == n {
				d_paths, d_err := r.DependenciesForArtifactRecursive(ctx, out, artifacts, a)
				paths = append(paths, d_paths...)
				err = d_err
			}
		}
	}
	return paths, err
}

```

Then i could use it like this:

```go
...
		default:
			if err := r.monitor.Register(
				func() ([]string, error) {
					paths, err := r.DependenciesForArtifactRecursive(ctx, out, artifacts, artifact)
...
```

I tested this change and now my skaffold sync works as expected. I am not used to writing go code otherwise i would have submitted a PR.

**Comment by briandealwis** [comment]
@gsquared94 this seems an interesting idea

**Comment by kervel** [comment]
https://github.com/Kapernikov/skaffold/tree/test-fix-5301 works for me (but no unit tests, or relevant go experience)

**Comment by MarlonGamez** [comment]
Hey @kervel, thanks for opening this and doing some investigation yourself :) If you don't mind, I think opening a PR with what you've written would be awesome! We can take a look at it and help write tests or anything if needed

**Comment by kervel** [comment]
Hello @MarlonGamez , i cleaned it up a bit and the PR is above. I guess a simple unit test would be enough for this, but i have no idea where to create it. the non-recursive DependenciesForArtifact doesn't seem to have one otherwise i could use that as a starting point.

**Comment by gsquared94** [comment]
Thanks @kervel for opening this issue. I wanted to summarize what we discussed about this in our triage meeting:
- The artifact dependency feature doesn't allow the child artifact to inherit sync rules from the parent artifact (by design).
- When a file change occurs for a parent artifact it triggers a rebuild for that artifact and all other children artifacts derived from it. In your description you said that  `'skaffold doesn't monitor the right files for the children.'` Can you confirm that you're not seeing even a _rebuild_ happen for the children artifacts when the parent artifact file changes? If so, can you share your `skaffold.yaml` file and the logs after running with `-v DEBUG` flag and triggering a file change?
- In your PR, you've added a dev loop trigger to the children artifact for parent artifact dependencies. But the response that the children artifact needs to take isn't clear for all builder types. In this case for the Docker builder it's probably simple to write sync rules that encompass files from the parent artifact, but we need a generic framework of how to do this (say if the parent artifact built with `buildpacks` was used as the run image for the child artifact built with `jib`). If you feel up for it then you can write a [design proposal](https://github.com/GoogleContainerTools/skaffold/tree/master/docs/design_proposals) for this (refer to the [`artifact dependencies`](https://github.com/GoogleContainerTools/skaffold/blob/master/docs/design_proposals/artifact-dependencies.md#sync) design where we noted this issue).

**Comment by kervel** [comment]
Hello @gsquared94 

* First remark: agree with this. this is also not what i want to do with the patch/PR. Actually, the sync rules only act within the discovered dependencies of a file (or: a sync rule has no effect if it acts on files that were not detected as a dependency)

* Second remark: sorry, i wasn't clear. My bug report and PR only affect file sync nothing else, the builds work fine. If it is still unclear i can try to provide a minimal example where my PR makes a difference.

* About the other builder types: i think my PR is not docker-specific as i just use the (already existing) GetDependencies which is - i think - not docker specific. The only thing i add is calling it recursively on parent artifacts. Just for reference, i put the built-in GetDependencies method below (that's the one i now call recursively)

```go
func DependenciesForArtifact(ctx context.Context, a *latest.Artifact, cfg docker.Config, r docker.ArtifactResolver) ([]string, error) {
        var (
                paths []string
                err   error
        )

        switch {
        case a.DockerArtifact != nil:
                // Required artifacts cannot be resolved when `ResolveDependencyImages` runs prior to a completed build sequence (like `skaffold build` or the first iteration of `skaffold dev`).
                // However it only affects the behavior for Dockerfiles with ONBUILD instructions, and there's no functional change even for those scenarios.
                // For single build scenarios like `build` and `run`, it is called for the cache hash calculations which are already handled in `artifactHasher`.
                // For `dev` it will succeed on the first dev loop and list any additional dependencies found from the base artifact's ONBUILD instructions as a file added instead of modified (see `filemon.Events`)
                deps := docker.ResolveDependencyImages(a.Dependencies, r, false)
                args, evalErr := docker.EvalBuildArgs(cfg.Mode(), a.Workspace, a.DockerArtifact.DockerfilePath, a.DockerArtifact.BuildArgs, deps)
                if evalErr != nil {
                        return nil, fmt.Errorf("unable to evaluate build args: %w", evalErr)
                }
                paths, err = docker.GetDependencies(ctx, docker.NewBuildConfig(a.Workspace, a.ImageName, a.DockerArtifact.DockerfilePath, args), cfg)

        case a.KanikoArtifact != nil:
                deps := docker.ResolveDependencyImages(a.Dependencies, r, false)
                args, evalErr := docker.EvalBuildArgs(cfg.Mode(), a.Workspace, a.KanikoArtifact.DockerfilePath, a.KanikoArtifact.BuildArgs, deps)
                if evalErr != nil {
                        return nil, fmt.Errorf("unable to evaluate build args: %w", evalErr)
                }
                paths, err = docker.GetDependencies(ctx, docker.NewBuildConfig(a.Workspace, a.ImageName, a.KanikoArtifact.DockerfilePath, args), cfg)

        case a.BazelArtifact != nil:
                paths, err = bazel.GetDependencies(ctx, a.Workspace, a.BazelArtifact)

        case a.JibArtifact != nil:
                paths, err = jib.GetDependencies(ctx, a.Workspace, a.JibArtifact)

        case a.CustomArtifact != nil:
                paths, err = custom.GetDependencies(ctx, a.Workspace, a.ImageName, a.CustomArtifact, cfg)

        case a.BuildpackArtifact != nil:
                paths, err = buildpacks.GetDependencies(ctx, a.Workspace, a.BuildpackArtifact)

        default:
                return nil, fmt.Errorf("unexpected artifact type %q:\n%s", misc.ArtifactType(a), misc.FormatArtifact(a))
        }

        if err != nil {
                return nil, err
        }

        return util.AbsolutePaths(a.Workspace, paths), nil
}

```

**Comment by gsquared94** [comment]
@kervel would be great if you could provide that minimal example.

**Comment by kervel** [comment]
ok here is the (tiny) example, see attached zip file: 

it contains a common base image "base" , and two derived images "d1", "d2". the base image has an index.html that links to a world.html but the world.html is defined by d1/d2. this simulates something generic + something specific.

now i do (using microk8s with registry enabled)
```shell
skaffold dev -d localhost:32000 --auto-deploy=false --auto-build=false
```
this should enable syncing.

with the standard skaffold:
* try to change world.html in d1 --> sync works
* try to change world.html in d2 --> sync works
* try to change hello.html in base --> **nothing happens**

with the patched skaffold:
* try to change world.html in d1 --> sync works
* try to change world.html in d2 --> sync works
* try to change hello.html in base --> the hello.html correctly gets synced to the two running containers as they both are derived from the base image.

[min_example.zip](https://github.com/GoogleContainerTools/skaffold/files/5961636/min_example.zip)

**Comment by gsquared94** [comment]
Thanks for the example project. This does improve on the existing logic. Added some comments to the PR.
