### ISSUE TITLE
Instrument skaffold for getting some performance metrics.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#5335]
Instrument skaffold for getting some performance metrics.

**Comment by MarlonGamez** [comment]
Commenting to keep tp happy 👍🏼

**Comment by tejal29** [comment]
hmm should definitely look into skaffold rules and code here https://github.com/google/triage-party

**Comment by tejal29** [comment]
Started working on adding traces to skaffold and collecting data.

**Comment by tejal29** [comment]
dupe of #5788
