### ISSUE TITLE
`debug` failing to recognize GCP Buildpacks .NET core images

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5336]
### Expected behavior

`skaffold debug` is able to debug .NET Core images produced by GCP Buildpacks.

### Actual behavior

```
time="2021-02-02T23:04:26Z" level=warning msg="Image \"dotnet-web\" not configured for debugging: unable to determine runtime for \"dotnet-web\""
```

### Steps to reproduce the behavior

Happens with `TestDebug/buildpacks`.

**Comment by briandealwis** [comment]
GCP Buildpacks' dotnet buildpack was recently changed to [perform `cd xxx` prior to launching the app](https://github.com/GoogleCloudPlatform/buildpacks/blob/cdf192c8aeb5de4fa6587ec485f010d5cc832deb/cmd/dotnet/publish/main.go#L167).  `debug` doesn't parse shell statements to this level.

**Comment by briandealwis** [comment]
[CNB RFC 81](https://github.com/buildpacks/rfcs/blob/main/text/0081-process-specific-working-directory.md) would allow removing this `cd`.  We'd need to add support for extracting this working directory.

**Comment by tejal29** [comment]
dupe of #5733
