### ISSUE TITLE
Skaffold Customized script

### ISSUE THREAD

**Issue by sunil31925** [GoogleContainerTools/skaffold#5377]
![skaffold_customized script](https://user-images.githubusercontent.com/12955434/107419726-1b6bbd00-6ae6-11eb-8c9d-2ec51dbc8fc8.JPG)

**Comment by sunil31925** [comment]
![skaffold_customized script](https://user-images.githubusercontent.com/12955434/107420191-9fbe4000-6ae6-11eb-9413-8518c22e3d61.JPG)

**Comment by sunil31925** [comment]
How to Make configurable base on instance i wan to spin 12 instance of my app with different param mention above. Please help me where do i need to customization to mage this kind of change

**Comment by nkubala** [comment]
hey @sunil31925, I don't think this is something that skaffold handles. you might consider looking into a tool like https://kustomize.io/, which handles environment parameterization among other things. good luck!
