### ISSUE TITLE
Force build docker container each time?

### ISSUE THREAD

**Issue by HarshadK15** [GoogleContainerTools/skaffold#5381]
Hello,

Is there a way we can force Skaffold to build the docker container each time, instead of skipping the build process if there are no changes to the container?

**Comment by nkubala** [comment]
@HarshadK15 thanks for the question, i think you're looking for `--cache-artifacts=false`. this will override skaffold's local build cache on every detected change.

hope this is what you were looking for! feel free to reopen if this doesn't solve your problem.
