### ISSUE TITLE
Add distinct error codes for test failures

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5382]
Skaffold should return distinct error codes for test failures.

The fix will be implemented in two phases
1. Adding error codes for existing structure test failures (tracker - #5384, pr - #5385)
2. Adding error codes for newly added custom test failures (tracker - #5431, pr - ##5501)

**Comment by nkubala** [comment]
commenting to make triage party happy

**Comment by PriyaModali** [comment]
Implemented.
