### ISSUE TITLE
should be able to run build steps without auth config

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/skaffold#539]
Today I happen to try Skaffold on a colleague's Linux machine that I used for the first time and learned that I have to login to Docker registry, which I'd rather not do at this point (I actually don't my password and it seems unnecessary anyway).

So, I don't have `~/.docker/config.json` and I see this:
```
$ skaffold dev
WARN[0000] Could not get minikube docker env, falling back to local docker daemon 
2018/05/11 15:04:45 Unable to read "/home/ilya/.docker/config.json", falling back on anonymous: open /home/ilya/.docker/config.json: no such file or directory
2018/05/11 15:04:48 manifest digest: "sha256:9cd6c8c389cd9fd26925f3e74f594a8a42d1a1156d96d18f0bec074a3ec27eb6" does not match Docker-Content-Digest: "sha256:88ea18c800aca19696c5cfcca1f390862a6bd6a724a1da3c5a76538ffe24a2be" for "index.docker.io/library/golang:1.9"
2018/05/11 15:04:48 Unable to read "/home/ilya/.docker/config.json", falling back on anonymous: open /home/ilya/.docker/config.json: no such file or directory
2018/05/11 15:04:50 manifest digest: "sha256:8c03bb07a531c53ad7d0f6e7041b64d81f99c6e493cb39abba56d956b40eacbc" does not match Docker-Content-Digest: "sha256:7df6db5aa61ae9480f52f0b3a06a140ab98d427f86d8d5de0bedab9b8df6b1c0" for "index.docker.io/library/alpine:3.7"
Starting build...
Found [minikube] context, using local docker daemon.
WARN[0005] run: build: build step: running build for artifact: running build: read auth configs: docker config: opening docker config: open /home/ilya/.docker/config.json: no such file or directory 
Watching for changes...
```

This is not very helpful at all, I'm just trying to run a local build and I don't care about pushing anything to the registry. I got a warning, and seems like I'm good, but actually build didn't take place...

**Comment by errordeveloper** [comment]
@dgageot I just tried to fix it, but seems like it's been fixed in master - what commit carries the fix for this? After having a brief look at the code which returns this error, I'm a little confused to be honest, some pointers would help a lot.

I was looking here:
https://github.com/GoogleContainerTools/skaffold/blob/d0479f91e109317f09cdb4b3e34b0f65be460fb5/pkg/skaffold/docker/image.go#L49-L82

**Comment by dgageot** [comment]
I think this PR is what you are looking for: #454

**Comment by dgageot** [comment]
The reading of the config.json is not for pushing (since local mode doesn't push) but for pulling base images during the build.

**Comment by errordeveloper** [comment]
Thanks, David! That makes sense.
