### ISSUE TITLE
Helm: uninstall: Release not loaded

### ISSUE THREAD

**Issue by satazor** [GoogleContainerTools/skaffold#5414]
### Expected behavior

Calling `skaffold delete` a second time, after a previous failed `skaffold delete` should not fail with `uninstall: Release not loaded` when using Helm.

### Actual behavior

If a previous run of `skaffold delete` fails (e.g.: network error) and some Helm releases were uninstalled and some were kept, the second run of `skaffold delete` fails with  `uninstall: Release not loaded`. It seems that this specific error should be ignored by skaffold, or perhaps emit a warning.

### Information

- Skaffold version: 1.20.0
- Operating system: MacOS
- Contents of skaffold.yaml:

> Any simple skaffold.yml with two or more helm releases

### Steps to reproduce the behavior

1. `skaffold run`
2. Run `helm uninstall <release>` manually or simulate the network error in between
3. `skaffold delete` again

**Comment by tejal29** [comment]
@satazor sounds like a great idea. Helm deployer code is here needs some attention to exclude the error message you just listed.
Would you be up for adding this?

**Comment by satazor** [comment]
@tejal29 I think you forgot to link "here". I can look into this yes. However, I have not wrote any Go code but I will give it a try :D

**Comment by satazor** [comment]
@tejal29 this seems to be the place where I can detect the error and ignore it: https://github.com/GoogleContainerTools/skaffold/blob/ef6ec476d0f6160af0a634271ecc44203ccf3c93/pkg/skaffold/deploy/helm/deploy.go#L245

Is it correct?

**Comment by gsquared94** [comment]
@satazor sorry for the late reply. You are correct in finding the offending code. I'd suggesting building the slice of errors for each release cleanup and return it at the end.
