### ISSUE TITLE
support for helm oci

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#5418]
Hi 
is there something planned to implement support for

https://helm.sh/docs/topics/registries/#enabling-oci-support 

that a given helm chart is pulled from e.g. registry before deployment?
cheers
Marco

**Comment by tejal29** [comment]
We are thinking of revamping helm support for skaffold.  We could definitely explore this.

We are tracking all helm support requests here #5442
/cc @nkubala

**Comment by havenotfear** [comment]
This would be great. 👍

**Comment by eshepelyuk** [comment]
It would be also great to allow pushing charts to OCI registries during the build, as for container images.

**Comment by CrystalMethod** [comment]
With Helm 3.8 OCI support has become generally available.

https://github.com/helm/helm/releases/tag/v3.8.0

**Comment by tejal29** [comment]
duplicate of #7127
