### ISSUE TITLE
Skaffold schema objects are not marked as type=object

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5421]
Our JSON schema type definitions are not marked as `"type": "object"` and so array references etc can be filled in with numbers or other values.  For example, the following is deemed to be valid:

```
portForward:
 - "foo"
```

Our [schema generator](http://github.com/GoogleContainerTools/skaffold/blob/master/hack/schemas/main.go) needs to add a `type` field to the generated objects.

**Comment by tejal29** [comment]
@tstromberg this bug is showing as p2 violation. It was created 4 days ago.
![image](https://user-images.githubusercontent.com/1534539/108921020-92c34580-75ea-11eb-934c-b1cc5a9cdded.png)

**Comment by briandealwis** [comment]
Specifically: a definition without a type can hold any type.  Our [PortForwardResource](https://github.com/GoogleContainerTools/skaffold/blob/4eb8930752cc27d8016b61f7595440f7d8aaa8cc/docs/content/en/schemas/v2beta14.json#L2446-L2497) can be anything.
