### ISSUE TITLE
Have skaffold emit various SubtaskEvent protos

### ISSUE THREAD

**Issue by MarlonGamez** [GoogleContainerTools/skaffold#5423]
Skaffold should emit the new SubtaskEvent protos for API v2

- [x] [build](https://github.com/GoogleContainerTools/skaffold/issues/5726) 
- [x] [test](https://github.com/GoogleContainerTools/skaffold/issues/5784)
- [x] [deploy](https://github.com/GoogleContainerTools/skaffold/issues/5782)
- [x] [statuscheck](https://github.com/GoogleContainerTools/skaffold/issues/5785)

**Comment by aaron-prindle** [comment]
Friendly ping

**Comment by tejal29** [comment]
Fixed by #5785
