### ISSUE TITLE
[Meta] Reopen issue wrongly marked as duplicate

### ISSUE THREAD

**Issue by Seb-C** [GoogleContainerTools/skaffold#5444]
### Expected behavior

The issue is considered and opened to discussion.

### Actual behavior

The issue was marked as duplicate and closed.

### Information

My issue #5210 was wrongly marked as a duplicate with #4953 and closed.

#4953 is about the development loop not starting if the code fails
#5210 is about the conditions that determines that the deployment is failed.

Currently, Skaffold is considering the development as failed when the container fails, while my pod is still healthily starting as per kubernetes (which is possible with probes).
As I also wrote [here](https://github.com/GoogleContainerTools/skaffold/issues/5210#issuecomment-784663857), I think Skaffold should not be aware of the containers layer, otherwise it is short-circuiting Kubernetes. Skaffold should rely exclusively on kubernetes to determine if a pod is healthy or not.
Because of this, I am forced to have a container/image/code that behaves differently in Skaffold and kubernetes.

### Steps to reproduce the behavior

Non-relevant

**Comment by tejal29** [comment]
Reopening the previous issue and closing this. 
Skaffold team uses https://github.com/google/triage-party open source tool which notifies the team if original author commented on a closed issue.  
Hence i went ahead a closed your issue #4953. :)
