### ISSUE TITLE
Installing Skaffold Docs macOS ARM64 binary url is incorrect

### ISSUE THREAD

**Issue by blitzd** [GoogleContainerTools/skaffold#5450]
has:

`curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64 && \`

and should probably be:

`curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-arm64 && \`

Same issue for the bleeding edge build...

**Comment by tejal29** [comment]
Its fixed on our latest master docs https://skaffold-latest.firebaseapp.com/docs/install/

I ended up running the trigger to publish docs on skaffold.dev
its not fixed on https://skaffold.dev/docs/install/
