### ISSUE TITLE
File-sync in infer mode does not detect changes with context including parent directory

### ISSUE THREAD

**Issue by jimmywan** [GoogleContainerTools/skaffold#5460]
### Expected behavior
Ideally: file sync works
Optionally: halt and output warning that file sync will not work, as configured.

### Actual behavior
skaffold runs, but silently doesn't detect the file changes.

### Information
- skaffold version v1.20.0
- Docker version 20.10.3, build 48d30b5
- minikube v1.13.1 on Ubuntu 18.04

```yaml
...
context: ../my_project_dir/Readme.md
...
```

### Steps to reproduce the behavior

 - Run `skaffold dev`
 - see original file
 - touch file
 - still see original file
 - change config to use absolute paths
 - restart via CTRL-C & `skaffold dev`
 - see output
 - touch file
 - see new file

**Comment by briandealwis** [comment]
@jimmywan could. you please include your `skaffold.yaml` (at least the artifact definition), your project's file layout, and the output that you're seeing from Skaffold?

An artifact's `context` is a directory that contains the artifact files, but your example is pointing to a file (presuming from the name).  When I try to reproduce, Skaffold raises an error:
```
$ skaffold build
image "skaffold-example" context "Readme.md" is not a directory
```

I would hazard that in your case, you'd want:
```yaml
build:
  artifacts:
  - image: xxx
    context: ../my_project_dir
    sync:
      infer: ['Readme.md']   # or maybe "**/*"
```

**Comment by jimmywan** [comment]
> An artifact's `context` is a directory that contains the artifact files, but your example is pointing to a file (presuming from the name). When I try to reproduce, Skaffold raises an error:

Apologies, that was 100% a cut/paste error on my part. It did look something a lot more like your example. I'll try to get a better example put together and edit the original.

**Comment by tejal29** [comment]
Closing this as the issue user has not provided a reproducible example for team to take a look at. 
@jimmywan If this is still an issue and please comment.
