### ISSUE TITLE
`skaffold dev` does not detect changes to source code for a nodejs app

### ISSUE THREAD

**Issue by jstrachan** [GoogleContainerTools/skaffold#547]
I was hoping to demo `skaffold dev` on a simple nodejs app: https://github.com/jenkins-x-quickstarts/node-http using this `Dockerfile` https://github.com/jenkins-x/draft-packs/blob/master/packs/javascript/Dockerfile

I was hoping `skaffold dev` would detect changes to the html/js files but after lots of attempts I couldn't get `skaffold dev` to detect any changes and trigger a rebuild. So I ended up having to cheat with a shell script ;) 
https://github.com/jenkins-x-quickstarts/node-http/blob/master/watch.sh

I wonder like this issue https://github.com/GoogleContainerTools/skaffold/issues/546 if we need some kind of watch or compile directive that lets us watch some file patterns/globs and optionally run a command CLI (make / npm / mvn / whatever) then run `skaffold run` with some profile?

Then pretty much any `Dockerfile` or project could be iteratively rebuilt on the fly via `skaffold dev`

**Comment by dlorenc** [comment]
I understand the issue in #546, but afaict skaffold *should* be watching all the html/js files in this case.  This specific case sounds like a bug. Can you share the app you tried using?

**Comment by jstrachan** [comment]
here's the nodejs demo I used last week: https://github.com/jstrachan/devoxxnode

**Comment by jstrachan** [comment]
@tejal29 awesome thanks!! I didn't see any output at all so assumed it wasn't doing anything ;) Adding a warning message will really help the next person who hits this issue.
