### ISSUE TITLE
how to tag the image with "latest" and gitversion?

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [GoogleContainerTools/skaffold#5477]
Hi,

how can I tag my images with two tags:
- latest
- gitversion

??
Best regards
Stefan

**Comment by briandealwis** [comment]
See the docs on [_Taggers_](https://skaffold.dev/docs/pipeline-stages/taggers/).  The oddly-named `sha256` tagger will use `latest`, and the `gitCommit` tagger offers several variants.
