### ISSUE TITLE
Helm chart containing NOTES.txt leads to the "error parsing object from string: collecting namespaces: reading Kubernetes YAML:..."

### ISSUE THREAD

**Issue by prokher** [GoogleContainerTools/skaffold#5484]
### Expected behavior

Helm charts with NOTES.txt file should work well and does not produce any extra errors in the log. 

### Actual behavior

Using Skaffold with Helm chart with NOTES.txt (containing just "Hello world!") leads to the error:
```
error parsing object from string: collecting namespaces: reading Kubernetes YAML: yaml: line 24: could not find expected ':' 
```

Removing NOTES.txt from the char fixes the issue.

### Information

- Helm's NOTES.txt file: https://helm.sh/docs/chart_template_guide/notes_files/
- Skaffold version: v1.20.0
- Operating system: Ubuntu 20.04
- Installed via: skaffold.dev

### Steps to reproduce the behavior

1. Create a Helm chart with NOTES.txt.
2. Configure Skaffold to use this Helm chart.
3. `skaffold dev`

### Extra

As far as I see, the problem is in the function `pkg/skaffold/deploy/helm/parse.go:parseReleaseInfo()` which expects an output of `helm get all <release name>` to be valid YAML file which is not the case when there is NOTES.txt in the Helm chart.

**Comment by briandealwis** [comment]
@prokher would you be able to submit a patch?

**Comment by prokher** [comment]
@briandealwis, unfortunately, no. I just made assumption about the place where error happens. Fixing this is a different story, for that I need to better understand decomposition, at least the local one.

**Comment by briandealwis** [comment]
I think we can just call `helm get all <xxx> --template '{{.Release.Manifest}}'` to return just the Kubernetes YAML.
