### ISSUE TITLE
Custom build example is currently broken

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5492]
Custom build example is currently failing. See the attached error .

![image](https://user-images.githubusercontent.com/2431844/110021317-6b9dff80-7cdf-11eb-86d8-06852de96322.png)

**Comment by MarlonGamez** [comment]
As far as I'm aware, it looks like the custom builder example should work, however, it seems like this piece of code from https://github.com/GoogleContainerTools/skaffold/pull/4952 isn't being applied?

https://github.com/GoogleContainerTools/skaffold/blob/2e55bec5dbf2afad231ea15620d5857dcc310279/pkg/skaffold/docker/reference.go#L83-L97

**Comment by briandealwis** [comment]
Closing again: #5505 is to investigate why `SanitizeImageName()` isn't called.
