### ISSUE TITLE
`skaffold init --analyze --XXenableJibInit` never exits if JDK not installed

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#5493]
### Expected behavior
command exits not showing jib build as an option

### Actual behavior
command never exits

### Information

- Skaffold version: v1.20.0
- Operating system: macOS 11.2 (M1 mac)
- Installed via: Cloud Code

### Steps to reproduce the behavior

1. ensure JDK is not installed
2. open [Cloud Code java hello world sample](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/java/java-hello-world).
3. run `skaffold init --analyze --XXenableJibInit`
4. wait a long time...

**Comment by briandealwis** [comment]
Noticed in #5380 too.  This isn't easily detectable as `/usr/bin/java` exists.  I suppose we could see if `JAVA_HOME` is set, and otherwise run `java -version` and see if it fails.

**Comment by j-windsor** [comment]
Yeah I ran into this issue while testing on M1 Mac and could repro on Intel Mac. The stalling `skaffold init` causes the Cloud Code skaffold setup UI to stall out and it is unusable. It also stalls out on `skaffold debug` or `skaffold dev` when Jib is selected as the builder but JDK is not installed.
