### ISSUE TITLE
Automatic docker login for CI

### ISSUE THREAD

**Issue by errordeveloper** [GoogleContainerTools/skaffold#550]
I think it'd be very nice to avoid having to run `docker login` when you want to let `skaffold run` build and push your images. Perhaps some kind of convention would be reasonable, e.g. detect commonly used environment variables.

Most CI user would end-up following the instructions vendors provide.

For example, [Travis CI](https://docs.travis-ci.com/user/build-stages/share-docker-image/) suggests to use this:
```
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
```
So detecting `DOCKER_PASSWORD` and `DOCKER_USERNAME` would work.

[CircleCI 1.0](https://circleci.com/docs/1.0/docker/) suggests this:
```
docker login -u $DOCKER_USER -p $DOCKER_PASS
```
While [CircleCI 2.0](https://circleci.com/docs/2.0/building-docker-images/) is much more Docker-native, and they have per-image auth, they still offer same `docker login` example as an option.

It'd be very convenient to the user if they could keep same secrets in CI config and drop `docker login` + `docker push`, and start using `skaffold run` instead.

**Comment by dlorenc** [comment]
I like this idea. We could implement an "environment variable" keychain in go-containerregistry.

**Comment by derekperkins** [comment]
I would want to use this with other container registries as well, specifically Azure.

`az acr login --name myregistry`

**Comment by jonjohnsonjr** [comment]
@derekperkins for normal authentication (where you control the environment), I'd recommend using a docker credential helper:
https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol
https://github.com/Azure/acr-docker-credential-helper

The go-containerregistry keychain will try to authenticate via whatever cred helpers you have configured in your docker config file.

**Comment by derekperkins** [comment]
Thanks for the suggestion @jonjohnsonjr! It caused a panic first run, but that may have been user error. I'll wait until my login expires and try again to see if it works.

**Comment by balopat** [comment]
Hi All, do we still think this is useful? I would like to collect more data / community support before we raise the priority on this feature. Thanks!

**Comment by errordeveloper** [comment]
I think this would still be very useful indeed.

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.

**Comment by CarlQLange** [comment]
This would be very helpful, particularly for the `az acr login` case mentioned above. In general I think a "hooks" setup would be very helpful, kinda like git's pre- and post- commit hooks and so on. If we could have a 'pre-build hook', 'post-deploy hook' and so on that could be defined in skaffold.yaml, I think that would make for some really valuable workflows.
