### ISSUE TITLE
Investigate why SanitizeImageName isn't being called

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5505]
`SanitizeImageName` isn't being called which is causing the custom test to fail with `ko:` images.

We need to investigate why SanitizeImageName isn't being called.

**Comment by MarlonGamez** [comment]
I believe this issue may be resolved with @halvards's proposed implementation of ko as a builder in skaffold. I'm going to hold off on serious investigation into this for now 

linking for context:
https://github.com/GoogleContainerTools/skaffold/pull/5611

**Comment by briandealwis** [comment]
Ah!  @PriyaModali and I had noticed that the image wasn't being rebuilt (#5500) — that it was being cached.  It looks like SanitizeImageName() is called from the imageReplacer:
https://github.com/GoogleContainerTools/skaffold/blob/7aaa1c70e29ba95caa07adc2aedf2e9e213ca4d5/pkg/skaffold/kubernetes/manifest/images.go#L80-L85
which is called to replace image references.  I wonder if cached images are not included in the built images passed in here:
https://github.com/GoogleContainerTools/skaffold/blob/7aaa1c70e29ba95caa07adc2aedf2e9e213ca4d5/pkg/skaffold/kubernetes/manifest/images.go#L60-L64

**Comment by halvards** [comment]
I can look into this as part of the work for #5611
