### ISSUE TITLE
Add remote helm chart example

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#5517]
Currently all `helm` examples use local charts. It'd be good to have at least one example using a remote helm chart.

**Comment by zestrells** [comment]
Hi @gsquared94 , it would be great if we can see an example of this working. I am attempting to use `remotePath` right now for my helm releases and it does not work for Windows or Linux

**Comment by gsquared94** [comment]
#5640 has an example. Can you check that you're using the right version of the config `skaffold/v2beta13` or greater?
https://skaffold.dev/docs/references/yaml/?version=v2beta13#apiVersion

**Comment by zestrells** [comment]
I confirmed I’m using v2beta13+ but it does not work as intended like the documentation says (on my end). I had to do

```
remote: true
chartPath: http://URL 
```

**Comment by gsquared94** [comment]
Can you create an issue for this with your (redacted) `skaffold.yaml` file and the output of `skaffold version` and `skaffold diagnose --yaml-only` ?
