### ISSUE TITLE
`helm.setFiles` base-path not resolved correctly when imported as a config dependency

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#5536]
`helm.setFiles` base-path not resolved correctly when imported as a config dependency.
This is because the tag `skaffold="filepath"` is missing on this field in [config.go](https://github.com/GoogleContainerTools/skaffold/blob/b5b916d1c5eb32d3b4758e20c76094f9b85b7bf5/pkg/skaffold/schema/latest/config.go#L704)

_Originally posted by @ngraf in https://github.com/GoogleContainerTools/skaffold/issues/5396#issuecomment-796535815_

**Comment by ngraf** [comment]
I downloaded HEAD and `setFiles` works for me now 💚 

Thanks a lot for that quick fix. That makes the multi-configuration feature complete now for me. This was a blocking bug for me.

**Comment by ReneWerner87** [comment]
@gsquared94 on linux and macos everything runs great, only on windows machines, it removes the slashes in the file path

```shell
Error: failed parsing --set-file data: open C:UsersdeveloperDesktopreposgco.clusterrepositoriesgco-serviceconfigproduct.env: The system cannot find the file specified.
exiting dev mode because first deploy failed: install: exit status 1
```

can you check and fix if necessary

**Comment by gsquared94** [comment]
I did add a `windows` test [here](https://github.com/GoogleContainerTools/skaffold/blob/e74d752176c4905e8a415d5d00ceff5d42c1a676/pkg/skaffold/tags/paths_windows_test.go#L47).

Can you give me an example of what path you're trying to set?

**Comment by ReneWerner87** [comment]
@gsquared94

created a small example today, hope you can find the error with it

https://github.com/ReneWerner87/skaffoldHelmMultiRepo

```shell
skaffold run -p dev
```
Mac: 
https://raw.githubusercontent.com/ReneWerner87/skaffoldHelmMultiRepo/master/macosWorking.png

Windows:
https://raw.githubusercontent.com/ReneWerner87/skaffoldHelmMultiRepo/master/windowsIssue.png

**Comment by ReneWerner87** [comment]
@gsquared94 do you nees something more or os it enough to reproduce the bug?

**Comment by ReneWerner87** [comment]
to better keep focus and since the issue is already on closed, i created a new fresh issue
https://github.com/GoogleContainerTools/skaffold/issues/5595
