### ISSUE TITLE
[BUG] Relative paths inside of deploy.helm.releases.valuesFiles are unusable for multiplatform Win/Lin usage

### ISSUE THREAD

**Issue by netaskd** [GoogleContainerTools/skaffold#5574]
Looks like a bug in relative path inside of `deploy.helm.releases.valuesFiles` on different OS (Linux/Windows)
### Actual behavior
Root inside of `app` directory. 
```bash
app
├── skaffold.yaml
├── resources
│   ├── helm
│   │   └── values.yaml
│   └── skaffold
│       ├── build
│       │   └── skaffold.yaml
```

Values `profiles.deploy.helm.releases.valuesFiles` inside of `app/resources/skaffold/build/skaffold.yaml`

Behavior:

```bash
# windows
profiles.deploy.helm.releases.valuesFiles:
  - resources/helm/values.yaml # <---- Error: open C:\test\app\resources\skaffold\deploy\resources\helm\values.yaml: The system cannot find the path specified. exiting dev mode because first deploy failed: install: exit status 1
  - ../../helm/values.yaml # <---- takes from root of the project, works well
```

```bash
# linux
profiles.deploy.helm.releases.valuesFiles:
  - resources/helm/values.yaml # <---- takes from root of the project, works well
  - ../../helm/values.yaml # <---- Error: open ./../../helm/values.yaml: no such file or directory
```

JFYI: `profiles.deploy.helm.releases.chartPath: ../../helm` works well for both systems

### Information

- Skaffold version: 1.20
- Operating system: Windows10 / Centos 7
- Installed via: binary

**Comment by netaskd1** [comment]
fixed in https://github.com/GoogleContainerTools/skaffold/pull/5538

**Comment by netaskd** [comment]
fixed in https://github.com/GoogleContainerTools/skaffold/pull/5538
