### ISSUE TITLE
Skaffold should first check for existence of test stanza before logging any testing phase statements

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5596]
Skaffold should first check for existence of test stanza in the config before logging any testing phase statements

This is applicable to all Skaffold commands:
skaffold test
skaffold run
skaffold dev

**Comment by briandealwis** [comment]
@PriyaModali do you have some more context here?  I don't see any testing phase statements without a `test:` clause.

**Comment by tejal29** [comment]
closing this now. Please feel free to re-open with more context
