### ISSUE TITLE
Skaffold should first check for existence of build stanza before logging any build phase statements

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5597]
Skaffold should first check for existence of build stanza in the config before logging any build phase statements

This is applicable to all Skaffold commands:
skaffold build
skaffold run
skaffold dev

**Comment by briandealwis** [comment]
Skaffold [spoofs up a local build stanza if one isn't found](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/defaults/defaults.go#L120-L127).
