### ISSUE TITLE
Skaffold should first check for existence of deploy stanza before logging any deploy phase statements

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5598]
Skaffold should first check for existence of deploy stanza in the config before logging any deploy phase statements

This is applicable to all Skaffold commands:
skaffold deploy
skaffold run
skaffold dev

**Comment by briandealwis** [comment]
Skaffold [spoofs up a default kubectl deploy stanza when no deploy is found](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/defaults/defaults.go#L114-L118).
