### ISSUE TITLE
skaffold test cmd should accept a list of prebuilt images as input for testing

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5599]
Update skaffold test cmd to 
1. accept skaffold build output  as input
2. accept a list of prebuilt images as input

**Comment by tejal29** [comment]
Thanks for creating this issue. I am curious on the motivation is behind this. Do you have a usecase in mind?

**Comment by briandealwis** [comment]
`test` accepts (and indeed, requires) such a list with `--build-artifacts`.
