### ISSUE TITLE
Debug and Fix gcb profile integration test on Kokoro.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#561]
### Expected behavior
The following test should pass on kokoro
```
cd examples/getting_started
skaffold run -p gcb 
```
### Actual behavior
It fails with no helpful information

Running locally is not helpful, since the command fails as we do not have GOOGLE_APPLICATION_CREDENTIALS variable set.

We need to grab the std our and debug this on kokoro

**Comment by dgageot** [comment]
Done with #580
