### ISSUE TITLE
Skaffold fails when a container's status code is 1 

### ISSUE THREAD

**Issue by casret** [GoogleContainerTools/skaffold#5617]
This is an exact dupe of #5210.  I want to reopen it because it's a big change of behavior from previous version and is blocking up from upgrading (from 1.7.0).  If you could either revert the change in behavior or allow a flag to allow the old behavior that would be great.  Just turning off the status-check does not work because in CI/CD we do want to check if the deployment fully progressed, which it would if skaffold didn't abort it prematurely.

**Comment by nkubala** [comment]
closing and reopening #5210 to continue conversation there
