### ISSUE TITLE
Expire intents at end of dev loop

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5621]
We currently queue up _intents_ the control API if they can't be applied at the moment.  We should expire intents when they cannot be applied.

From https://github.com/GoogleContainerTools/skaffold/pull/5553#issuecomment-800640367: 

>> I think @nkubala intended to have them queue up (like a single deploy request followed some time later by a single build request would run build and deploy both once)
>
> this is what i intended at the time, but now i'm not so sure it's what we want. it might be a more predictable UX to just reject the intents sent by a user if skaffold isn't ready to take the corresponding action yet (e.g. receives `build` intent from user, but `r.changeSet.needsRebuild == false`
>
>> Maybe a better flow would be if buildIntent == true but r.changeSet.needsRebuild == false we expire it immediately and show output Checking build status: already up-to-date and similarly for sync and deploy.
>
> if we decide to keep the current behavior, this is definitely something we should do. whatever route we take let's try and eliminate confusion.

**Comment by nkubala** [comment]
fixed by https://github.com/GoogleContainerTools/skaffold/pull/5636
