### ISSUE TITLE
`skaffold dev` with no build stanza gives misleading output

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#5624]
When running `skaffold dev` without a build stanza, no image is built, so the created pod will crash with `ErrImagePull`. However, Skaffold seems to think everything is fine, so it looks like our `PodSelector` is getting some bad info in the dev loop.

Additionally, the console output from Skaffold has a bunch of info about tag generation, file watching, cache checking, etc. We shouldn't be showing this if none of these actions are actually being performed.

### Expected behavior
`skaffold dev` should fail, and show warnings about tags not being substituted into the k8s manifests, as well as the pod itself failing status check since it's crashing

### Actual behavior
`skaffold dev` seems to succeed normally, "Watching for changes".

### Information

- Skaffold version: v1.21.0 (though this has probably always been an issue?)
- Operating system: OS X (all)
- Installed via: source
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
# build:
#   artifacts:
#   - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. using our `getting-started` example - comment out/remove the build section
2. `skaffold dev`

```
➜  skaffold dev
Listing files to watch...
Generating tags...
Checking cache...
Starting test...
Tags used in deployment:
Starting deploy...
 - pod/getting-started created
Waiting for deployments to stabilize...
Deployments stabilized in 68.801084ms
Press Ctrl+C to exit
Watching for changes...
```

**Comment by gsquared94** [comment]
Without an artifact list I wonder if we should fail outright; since there's no way to retrigger a dev loop, there's no reason to do a deployment even. The suggestion text could say about `skaffold deploy` and `skaffold apply` instead.
