### ISSUE TITLE
Spelling mistake Skaffold documentation

### ISSUE THREAD

**Issue by yrashish** [GoogleContainerTools/skaffold#5628]
There is a typo in the Skaffold pipeline stage Test [page](https://skaffold.dev/docs/pipeline-stages/testers/).
The document says the following.
Skafforl supports the below types of tests.
It should be.
Skaffold supports the below types of tests.
It needs to fixed.

**Comment by yrashish** [comment]
When I am trying to edit the page, it seems to show the correct spelling. I am guessing it's already fixed.

**Comment by gsquared94** [comment]
This has been fixed in the master branch. 
https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/docs/pipeline-stages/testers/_index.md
