### ISSUE TITLE
skaffold not recognize to remove manual changes

### ISSUE THREAD

**Issue by coolpalani** [GoogleContainerTools/skaffold#5634]
when running `skaffold run` the deployment went smooth. Assume I'm doing manual changes using `kubectl edit deploy deploymentname` like adding configmap on the fly. while I rereun `skaffold` it's not recognize to remove my manual changes. 

### Expected behavior
Eventually It should keep only changes applied through `skaffold`, manually applied configuration should be remove. So that consistency will be keep.

### Actual behavior
Configmap configuration still there in the deployment which was manually applied via `kubectl edit deploy deploymentname`

### Information

- Skaffold version: `v1.20.0`
- Operating system: Red Hat Enterprise Linux Server release 7.9
- Installed via: Binary downloaded from Github skaffold releases
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold run`
3. Do some manual changes via `kubectl edit deploy deploymentname`
4. Again execute `skaffold run` . Skaffold will run successfully without removing manually added objects.

**Comment by tejal29** [comment]
@coolpalani IIUC, you made a change to deployment on the fly when running `skaffold run`
You ran `skaffold run` again? 
What you expected was
- `skaffold run` should deploy from the deployment.yaml
Is that right?

skaffold relies on `kubectl apply` when reapplying changes.
Can you verify what `kubectl apply` behavior is?
1) kubectl apply -f deployment.yaml
2) kubectl edit deploy deployment
3) kubectl apply -f deployment.yaml


If you run `skaffold delete` before running `skaffold run` again or specify `force=true` in https://skaffold.dev/docs/references/yaml/#deploy-kubectl-flags-apply which will delete existing resources.

Does that answer your question?

**Comment by coolpalani** [comment]
@tejal29 

I request you that follow below process to reproduce that issue.

**Phase-1 Deployment**
`git clone https://github.com/GoogleContainerTools/skaffold`
`cd skaffold/examples/kustomize`
`kubectl create ns dev-cm-test`
`sed -i 's/busybox/busybox:1.32/g' patch.yaml`
`skaffold deploy -f skaffold.yaml -n dev-cm-test`

Deployment output
`$ skaffold deploy -f skaffold.yaml -n dev-cm-test`
`Tags used in deployment:`
`Starting deploy...`
` - deployment.apps/kustomize-test created`
`Waiting for deployments to stabilize...`
` - dev-cm-test:deployment/kustomize-test: creating container kustomize-test`
 `   - dev-cm-test:pod/kustomize-test-69c594cb5c-4twhj: creating container kustomize-test`
` - dev-cm-test:deployment/kustomize-test: DNSConfigForming: Search Line limits were exceeded, some search paths have been omitted, the applied search line is: dev-cm-test.svc.cluster.local svc.cluster.local cluster.local `
`    - dev-cm-test:pod/kustomize-test-69c594cb5c-4twhj: DNSConfigForming: Search Line limits were exceeded, some search paths have been omitted, the applied search line is: dev-cm-test.svc.cluster.local svc.cluster.local cluster.local `
` - dev-cm-test:deployment/kustomize-test is ready.`
`Deployments stabilized in 10.94 seconds`

**Manual Change on top of existing deployment**

I will create a configmap and mount in that container.

`wget https://kubernetes.io/examples/configmap/game.properties -O game.properties`
`kubectl create configmap game-config --from-file=./game.properties -n dev-cm-test`
`configmap/game-config created`

I'm making this change via kubectl by editing deployment config file.

`kubectl edit deploy/kustomize-test -n dev-cm-test`
`      volumeMounts:`
      `- name: config`
       ` mountPath: "/config"`
        `readOnly: true`

`volumes:`
   ` - name: config`
      `configMap:`
          `name: game-config`
          `items:`
          `- key: "game.properties"`
           ` path: "game.properties"`
kubernetes recreated the pod and it's running.

kubectl exec -it kustomize-test-85c7f6b64d-g9qz4 -n dev-cm-test -- sh
`/ # df -hT /config`
`Filesystem           Type            Size      Used Available Use% Mounted on`
`/dev/mapper/vgroot-lvroot`
`                     ext4           28.9G     18.0G      9.6G  65% /config`

`/ #  ls -la /config/`
`drwxr-xr-x    2 root     root          4096 Apr 12 14:44 ..2021_04_12_14_44_52.813728379`
`lrwxrwxrwx    1 root     root            31 Apr 12 14:44 ..data -> ..2021_04_12_14_44_52.813728379`
`lrwxrwxrwx    1 root     root            22 Apr 12 14:44 game.properties -> ..data/game.properties`

**Phase-2 Deployment**

I'm up the container version and perform deployment via skaffold.

`sed -i 's/busybox:1.32/busybox:1.33/g' patch.yaml`
`skaffold deploy -f skaffold.yaml -n dev-cm-test`
`Tags used in deployment:`
`Starting deploy...`
` - deployment.apps/kustomize-test configured`
`Waiting for deployments to stabilize...`
` - dev-cm-test:deployment/kustomize-test: creating container kustomize-test`
 `   - dev-cm-test:pod/kustomize-test-5dd79f5d54-6975f: creating container kustomize-test`
` - dev-cm-test:deployment/kustomize-test: DNSConfigForming: Search Line limits were exceeded, some search paths have been omitted, the applied search line is: dev-cm-test.svc.cluster.local svc.cluster.local cluster.local`
`    - dev-cm-test:pod/kustomize-test-5dd79f5d54-6975f: DNSConfigForming: Search Line limits were exceeded, some search paths have been omitted, the applied search line is: dev-cm-test.svc.cluster.local svc.cluster.local cluster.local`
` - dev-cm-test:deployment/kustomize-test is ready.`
`Deployments stabilized in 11.263 seconds`

The new docker image rolled out and able to see existing manually updated configmap files also.
The expectation is a manual change(configmap configurations) should be removed in phase2 stage deployment but it wasn't happening.
This expected behavior will ensure skaffold always push right configuration through this tool and will remove all intermediate manual changes.

I tried force flag as well, but it's not removing configmap changes.

`skaffold deploy -f skaffold.yaml --force=true -n dev-cm-test`

**Comment by tejal29** [comment]
@coolpalani I missed the fact you use `kubectl edit` to edit the deployment. 
Skaffold does not re-concile changes made to resources on the cluster to deployment.yaml You will have to make these changes in the declared manifests.

Can you not add the following to the deployment spec?
```
kubectl edit deploy/kustomize-test -n dev-cm-test
volumeMounts:
- name: config
mountPath: "/config"
readOnly: true

volumes:
- name: config
configMap:
name: game-config
items:
- key: "game.properties"
```

**Comment by tejal29** [comment]
Closing this since, skaffold can't do anything here. Please re-open if required.
