### ISSUE TITLE
Colorize Skaffold actionable error messages

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#5643]
it would be cool if we could add some color to the actionable errors we surface for known error scenarios. this would make it a little easier to distinguish between the error we encountered under the hood, vs. the one we're creating for the user to act on. 

the main obstacle for doing this right now is plumbing through the output stream to ensure that we only colorize errors when supported (some terminals don't support color ANSI codes, which makes the output we surface ugly).

**Comment by gsquared94** [comment]
@IsaacPD already did the heavy-lifting for this in [`formatter.go`](https://github.com/GoogleContainerTools/skaffold/blob/cc262b48867959858e592f76674f8ea0f37e0d8e/pkg/skaffold/color/formatter.go#L126-L128) so there shouldn't be any deterrent to implementing this.

**Comment by briandealwis** [comment]
> some terminals don't support color ANSI codes

It would be good to identify these cases.
