### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by rana** [GoogleContainerTools/skaffold#5655]
Any thoughts, plans, or perspectives on supporting [rust](https://www.rust-lang.org/)?

**Comment by tejal29** [comment]
@rana you can use skaffold's custom builder plugin to use your own builder.
https://skaffold.dev/docs/pipeline-stages/builders/custom/

We have some examples checked in in the skaffold examples https://github.com/GoogleContainerTools/skaffold/tree/master/examples/custom which you can follow along. 

Let us know if you had other than build support in your mind

**Comment by tejal29** [comment]
Tagging next oncall release person @briandealwis to close this next week if no further requests.

**Comment by tejal29** [comment]
closing as @rana is looking into Custom Build!

**Comment by rana** [comment]
@tejal29 Hi, thank you for the response.

The main question is if anyone has put thought into providing full Rust support similar to Go, Python, Node, and Java? That is my hope. From the response, I gather that Rust is not on your radar, not popular enough, and it's not a priority. Perhaps that will change in time. Feel free to post any thoughts as they develop. Rust + custom builder may be sufficient for now. Thank you.

**Comment by briandealwis** [comment]
Hi @rana. We would accept community contributions to add Rust debug support, but none of the core committers have the knowledge to support Rust.  Adding debug support for a language has two parts:

1. Installing language runtime debug supports in the [debug helper images](https://GitHub.com/GoogleContainerTools/container-debug-support) (if necessary); strong integration tests are essential here as none of the team develop in Rust.
2. Identifying and configuring language debug support in Skaffold (see pkg/skaffold/debug/transform_*.go).

**Comment by rana** [comment]
@briandealwis Appreciate the guidance- that will help get it done 👍
