### ISSUE TITLE
InputDigest is not supported by CustomTemplateTagger

### ISSUE THREAD

**Issue by mikekamornikov** [GoogleContainerTools/skaffold#5660]
### Expected behavior

I expect image tag with both some custom text and input digest created with `customTemplate` `tagPolicy`

### Actual behavior

```sh
$ skaffold build -p test-custom-template
creating runner: creating tagger: creating tagger: creating components: unknown component for custom template: DIGEST {GitTagger:<nil> ShaTagger:<nil> EnvTemplateTagger:<nil> DateTimeTagger:<nil> CustomTemplateTagger:<nil> InputDigest:0x7a479b8}
. If above error is unexpected, please open an issue https://github.com/GoogleContainerTools/skaffold/issues/new to report this error.
```

### Information

- Skaffold version: `v1.21.0-29-g89b83154e-dirty`
- Operating system: `macOS 10.15.7`
- Installed via: `built from master`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta14
kind: Config
profiles:
- name: test-custom-template
  build:
    tagPolicy:
      customTemplate:
        template: "release-aaa-{{.DIGEST}}"
        components:
        - name: DIGEST
          inputDigest: {}
    artifacts:
    - image: quay.io/my/project
      context: ../../..
      bazel:
        target: //project:docker.tar
```

### Steps to reproduce the behavior

1. clone this repo and build `skaffold` with `LOCAL=true make install`
2. `skaffold build -p test-custom-template`
3. ...

**Comment by mikekamornikov** [comment]
@piotr-szybicki This one is related to #5192 .

**Comment by tejal29** [comment]
will be fixed by https://github.com/GoogleContainerTools/skaffold/pull/5661
