### ISSUE TITLE
Custom test path dependency broken with multi-config

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5665]
In https://github.com/GoogleContainerTools/container-debug-support/pull/65 I'm trying to reorganize the `skaffold debug` helper images to use a Skaffold multi-config setup.  I have a custom test definition that specifies dependencies using a pattern:
```
test:
  - image: skaffold-debug-nodejs
    structureTests: [structure-tests-nodejs.yaml]
    custom:
      - command: "cd helper-image; go test ."
        dependencies:
          paths: ["helper-image/*.go", "helper-image/go.*"]
```

But my build is failing ([logs](https://api.travis-ci.org/v3/job/766487297/log.txt)):

```
Generating tags...
 - skaffold-debug-go -> skaffold-debug-go:be78dcf
 - skaffold-debug-netcore -> skaffold-debug-netcore:be78dcf
 - skaffold-debug-nodejs -> skaffold-debug-nodejs:be78dcf
 - skaffold-debug-python -> skaffold-debug-python:be78dcf
Checking cache...
 - skaffold-debug-go: Error checking cache.
getting hash for artifact "skaffold-debug-go": getting dependencies for "skaffold-debug-go": pattern "/home/travis/build/GoogleContainerTools/container-debug-support/nodejs/helper-image/*.go" did not match any file
```

The `paths` field is [marked as a `skaffold:filepath`](https://github.com/GoogleContainerTools/skaffold/blob/60458eb87ad1cf7be97c02ea0a9c7e15dcb18adf/pkg/skaffold/schema/latest/config.go#L1051) but the underlying implementation uses `list.Files()` which causes problems as `paths` has been made absolute in the multi-config situation:
  https://github.com/GoogleContainerTools/skaffold/blob/60458eb87ad1cf7be97c02ea0a9c7e15dcb18adf/pkg/skaffold/test/custom/custom.go#L149
   but `list.Files()` assumes that it *must* prefix the file patterns with the working directory:
   https://github.com/GoogleContainerTools/skaffold/blob/60458eb87ad1cf7be97c02ea0a9c7e15dcb18adf/pkg/skaffold/build/list/list.go#L34

I'm wondering if we should apply to the `skaffold:filepath` adjustments to all configs rather than just child configs so that we discover these situations earlier.

### Steps to reproduce the behavior

1. Clone https://github.com/briandealwis/container-debug-support/tree/modules at commit https://github.com/briandealwis/container-debug-support/commit/91c712b77b6a44b0ff9bc5d4c4a2b664f78da423
2. `skaffold build`

**Comment by gsquared94** [comment]
This is what had prompted https://github.com/GoogleContainerTools/skaffold/pull/5472. I don't think your [alternative](https://github.com/GoogleContainerTools/skaffold/pull/5472#discussion_r586645230) suggestion can catch these kinds of issues.

**Comment by gsquared94** [comment]
this should be fixed in https://github.com/GoogleContainerTools/skaffold/pull/5677
