### ISSUE TITLE
Use an incremental upload/manifest based approach for GCB

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/skaffold#568]
The manifest downloader is now an official build step: https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher

We should consider using this combined with an incremental upload approach to make GCB builds faster.

**Comment by ImJasonH** [comment]
There's a library encapsulating manifest upload too, which Skaffold can use: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/gcs-fetcher/pkg/uploader/uploader.go

**Comment by ImJasonH** [comment]
It looks like incremental upload (and maybe download?) could be used in kaniko-based builds as well, which specify `gcsBucket`.
