### ISSUE TITLE
Fix minikube version parsing error

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#5684]
/cc @gsquared94 

Strip `v` from minikube version parsing, and then parse the version.
```
DEBU[0000] Command output: [minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
] 
TRAC[0000] Minikube cluster not detected: parsing semver: Invalid character(s) found in major number "minikube version: v1" 
```

**Comment by tejal29** [comment]
Looks like, skaffold v1.22.0 does not build against minikube docker daemon.
Lets verify this,  fix if needed and follow up with a patch release.

**Comment by gsquared94** [comment]
I tested the latest release v1.22.0 against minikube version v1.18.1 and it was building correctly against the minikube docker daemon.

If you're referring to this issue https://github.com/GoogleContainerTools/skaffold/pull/5649#issuecomment-820033279, I reverted that change prior to the release, after @briandealwis reported it.

**Comment by tejal29** [comment]
Great!! Thanks @gsquared94. I am glad you caught it before release!!
