### ISSUE TITLE
Support for Packer builds of containers

### ISSUE THREAD

**Issue by Eronarn** [GoogleContainerTools/skaffold#572]
We currently use Ansible for our non-containerized deployments. Our long term goal is to move everything into Dockerfiles, but in the interim, we're using Packer to create containers using our Ansible provisioning scripts. I have heard of other folks being in this situation with other configuration management tools, since Packer allows you to use any tool to build the image.

I spent a day diving into the codebase and actually did get something mostly-working. However, the nature of Packer means that it is not nearly as polished as the Dockerfile or Bazel implementations: for example, you need to add a manifest step to Packer, and explicitly declare file dependencies (since it can't figure them out for you). It also won't work non-locally, of course.

Would there be interest in adding this support to Skaffold? Would be happy to submit a PR and document/provide code samples too.

**Comment by r2d4** [comment]
I'm actually curious about this. I think that explicitly declaring file dependencies is something we'll need to accept for a lot of builders. Not having dynamic dependency calculations breaks the `skaffold dev` file watching, but I'm curious to see what it would look like.

Do you mind sketching out what the build spec entry would look like?

**Comment by Eronarn** [comment]
Here's the Skaffold config file that I am using, based on my branch:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  local:
    skipPush: false

  artifacts:
    # This is just a Dockerfile in ./packer
    - imageName: example/basecontainer
      workspace: ./packer

    - imageName: example/container1
      workspace: ./packer
      packer:
        # What Packer template to use, relative to the workspace.
        template: container1.json
        # If provided, will watch for a previous build that has produced
        # an image matching this. Should match a prior Skaffold build.
        # Will be passed in as an "image" Packer variable if found. Therefore
        # the Packer config should provide a default image, but accept a var
        # to override it.
        image: example/basecontainer
        # Your Packer template needs to produce a manifest file at this path,
        # via the "manifest" post-build step. This stores the created artifacts,
        # since Packer doesn't
        manifest: container1-manifest.json
        # Specify a directory to watch, relative to the workspace. In our case,
        # the entire repo (not just /packer), because we mount the repo into
        # the Docker container.
        files: [".."]
```

This config is a little awkward, because Packer has neither good ability to override build arguments, nor good programmatic output. You can't just run any Packer template, it needs a few lines of modification to work properly. (It'll also be more sensitive to local config than existing builders, since the use case is typically that you're running local tools against a Docker container.)

I suppose that in our case `files` isn't being actually tested, since we are using `build` rather than `watch`. This is because I've implemented passing build results into subsequent builds, so that you can chain builds together, and therefore don't want to rebuild except in sequence. That's what the `image:` tag is for, and technically it's not required for Packer support. It was necessary in our case because we're planning to gradually move build steps into a Dockerfile to speed up the build and eventually transition away from Packer entirely.

**Comment by dlorenc** [comment]
I don't think this is going to be high up on our priority list, if this is something people are interested in please +1 the initial post.

**Comment by dgageot** [comment]
I'm going to close this one. When builders become plugins, it will up to the community to provide more buiders.
