### ISSUE TITLE
SeurityContext (sic)

### ISSUE THREAD

**Issue by joebowbeer** [GoogleContainerTools/skaffold#5754]
### Expected behavior

SecurityContext (spelling correct)

### Actual behavior

SeurityContext (spelling incorrect)

### Information

I noticed this typo in the `runAsUser` docs:

https://skaffold.dev/docs/pipeline-stages/builders/

which I suspect is generated from:

https://github.com/GoogleContainerTools/skaffold/blob/master/docs/content/en/schemas/v2beta15.json#L743

But also occurs in code:

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/latest/v1/config.go#L418

All occurrences:

https://github.com/GoogleContainerTools/skaffold/search?p=3&q=SeurityContext

**Comment by MarlonGamez** [comment]
welp, thanks for catching that @joebowbeer 😅
