### ISSUE TITLE
Increase timeout for pending resource deletions

### ISSUE THREAD

**Issue by go-nelango** [GoogleContainerTools/skaffold#5767]
Change https://github.com/GoogleContainerTools/skaffold/pull/4531 waits for pending resource deletions before attempting to redeploy. This sometimes leads to DEPLOY_ERR_WAITING_FOR_DELETION when the wait for deletion times out. The current default timeout seems to be 2 secs. Could you please increase this default or make it configurable?

As an extension, skaffold could look into not waiting for all resources marked for deletion and only query for specific resources found in the current skaffold config to be applied.

**Comment by MarlonGamez** [comment]
This can currently be configured using flags `--wait-for-deletions-max` and `--wait-for-deletions-delay`. Would you like these to be configurable through global config or skaffold.yaml as well?

**Comment by go-nelango** [comment]
> This can currently be configured using flags `--wait-for-deletions-max` and `--wait-for-deletions-delay`. Would you like these to be configurable through global config or skaffold.yaml as well?

That should work. Closing this and will reopen if we need these to be configurable through skaffold.yaml as well. Thanks!
