### ISSUE TITLE
typescript example fails in production ENV

### ISSUE THREAD

**Issue by joebowbeer** [GoogleContainerTools/skaffold#5771]
The typescript sample project does not compile the .ts files when ENV is production.

When ENV=development, `tsc-watch` compiles the code in place before starting node. However, there is no corresponding compile step when ENV=production.

Not a huge deal, as only the `dev` profile is defined, but I think the README should mention that the compile step is missing when ENV=production.

**Comment by aaron-prindle** [comment]
Thanks for catching this! I've attempted to update the docs as per your suggestion in: #5777.  Feel free to comment there if you think there is better wording or if you want to attempt the fix PR yourself that would be awesome as well and I can drop mine.
