### ISSUE TITLE
kubectl error messages are suppressed

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#578]
skaffold v0.6.0

when `kubectl apply` fails, its stderr is omitted from `skaffold dev` output and it gives this:

```
Starting deploy...
service "clusterregistry" created
configmap "gcp-project" created
configmap "corefile" created
service "dns-server" created
WARN[0280] run: deploy: deploy step: deploying manifests: exit status 1
Watching for changes...
```

and it actually doesn't start the watch.

This is very hard to debug as I have to apply every single manifest file to see which one is failing and why.

**Comment by dgageot** [comment]
@ahmetb it's fixed in master.

**Comment by dlorenc** [comment]
https://github.com/GoogleContainerTools/skaffold/pull/560
