### ISSUE TITLE
File Sync does not Restart Python Container process when JSON is copied in

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#5787]
### Expected behavior
Any files that are updated via FileSync should trigger main process to restart.

### Actual behavior

In our case, JSON config file was updated, the file was synced, but Python process did not restart.

### Information

- Skaffold version: 1.23.0
- Operating system: MacOS Big Sur
- Installed via: nightly
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

1. https://github.com/dhodun/skaffold/tree/filesync_issue/examples/hot-reload
2. skaffold dev
3. change config.json
4. File is updated but Python Flask not restarted

**Comment by briandealwis** [comment]
You need to configure the file-watching capabilities of your framework supports it, or use a separate file-watcher tool. Shahid doesn’t have any control over what’s happening inside your container.

**Comment by dhodun** [comment]
A understood! Tornado is reloading when new python files are detected.

**Comment by dhodun** [comment]
https://www.tornadoweb.org/en/stable/autoreload.html#tornado.autoreload.watch
