### ISSUE TITLE
Resolve skaffold metrics authentication issues - Compare alternatives and implement fix

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#5812]
Currenty skaffold is having metrics issues associated with the expiration on it's service account keys - #5760.  This bug tracks work to investigate alternatives and possibly move skaffold to use API keys instead.
- [x] investigate API keys (don't support authorization/IAM-roles)
- [x] enumerate possible options
- [x] identify best option (right now this seems to be extending key expiration)
- [ ] implement best option

**Comment by aaron-prindle** [comment]
@tejal29 was able to extend key expiry date as a solution here.  Closing.

**Comment by aaron-prindle** [comment]
There is still some current work being done regarding extending the key expiration date.  @tejal29 is also changing the release pipeline to re-create keys, see #5910

**Comment by tejal29** [comment]
Unfortunately, we will have to create a new teams project to get a longer expiry field. 
Trying to this in sustainability Sprint.

**Comment by tejal29** [comment]
New project created.  Waiting for internal team to respond

**Comment by tejal29** [comment]
New metrics project set up done!
