### ISSUE TITLE
Deployer Extensibility Interface

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#5813]
We should expose a cleaner interface for new `Deployer` implementations. This will make it more clear how to add new `Deployer` implementations and what is required of a `Deployer` to fit within Skaffold's resource model.

**Comment by tejal29** [comment]
Converting this to EPIC. If you could break this task down in individual tasks and pull those in individual sprints, that would be great.

**Comment by tejal29** [comment]
Can we close this now?
/cc @nkubala
