### ISSUE TITLE
Official Support for Sbt Jib as Part of Approved Builder

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/skaffold#5830]
### Kind

Feature request.

### Expected behavior

Support `sbt` as one of the option for accepted builder in jib `artifact`.

### Actual behavior

As of now, it's mentioned that `jib` [documentation](https://skaffold.dev/docs/pipeline-stages/builders/jib/):

```
Skaffold’s jib support chooses the underlying builder (Maven or Gradle) based on the presence of standard build files in the artifact's context directory:

    Maven: pom.xml, or .mvn directory.
    Gradle: build.gradle, gradle.properties, settings.gradle, or the Gradle wrapper script (gradlew, gradlew.bat, or gradlew.cmd).
```

### Information

There's `jib` core library in this [repository](https://github.com/GoogleContainerTools/jib/tree/master/jib-core). Is it possible for a plugin to be able to be supported in jib artifact within skaffold if one extend this core library.

**Comment by aaron-prindle** [comment]
@briandealwis are you familiar w/ how the jib sbt plugin might be added to skaffold's jib builder?  I see the user contributed sbt plugin referenced in the docs there:
https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/jib-core/examples/README.md

**Comment by briandealwis** [comment]
@irvifa The Jib builders come with special support for Skaffold, which sbt doesn't have.  We generally are not including support for new builders unless we have an internal partner team willing to contribute to the ongoing maintenance.  The [`custom` builder](https://skaffold.dev/docs/pipeline-stages/builders/custom/) is very flexible, and some Jib users choose to use it instead of the Jib builder due to some corner cases that are hard to support.

**Comment by irvifa** [comment]
Hi, as we already know that there's an sbt-jib repository is it possible to use that in the jib template argument on skaffold or if the recommended way of building an sbt project is actually to use a custom builder?

**Comment by briandealwis** [comment]
@irvifa the recommended way is to use the custom builder.  Does `sbt-jib` support overriding the resulting image name?

**Comment by irvifa** [comment]
Hi @briandealwis what do you mean by overriding the resulting image?

**Comment by briandealwis** [comment]
Skaffold supports a `--default-repo` flag that will cause the image to be built in a different registry or repository than what is specified in the `skaffold.yaml`.  So the builder needs to allow Skaffold to instruct it to build and push the image to a specific image location.

**Comment by irvifa** [comment]
Yes I think they provide the option as an optional parameter on this [part](https://github.com/schmitch/sbt-jib/blob/0380f32c280f9ffd5bc4d7e369fa7eb776826afe/src/main/scala/de/gccc/jib/JibPlugin.scala#L51).

**Comment by briandealwis** [comment]
What I mean is that there needs to be a command-line option for overriding the destination image.  For example, Jib allows [using `-Dimage=xxx` on the command-line](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#quickstart):
```
mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:build -Dimage=<MY IMAGE>
```

And we use this as part of the Skaffold support:
https://github.com/GoogleContainerTools/skaffold/blob/f95999ffad973fce7f3a9fbd2d96354fc2eb0749/pkg/skaffold/build/jib/maven.go#L111

**Comment by irvifa** [comment]
I don't think it support a command like option for overriding image at this moment. I tried to confirm this through the issue though. I also notice that the credentials helper for gcr also not implemented yet on the sbt-jib, which I'll probably need for my use case.
