### ISSUE TITLE
Block `skaffold` CLI execution until event consumer is ready

### ISSUE THREAD

**Issue by ekupershlak** [GoogleContainerTools/skaffold#5835]
The `skaffold` CLI does not wait for a connection to its API server when running. This means the CLI can complete and terminate before a connection is established. This makes programmatic integration tricky, since any events or metadata are no longer available. 

Could `skaffold` be modified to ensure the events have been received?  

One option would be to have `skaffold` connect to a host:port and not exit until all events have been transmitted. Another would be to wait until a connection is established before starting, or perhaps wait for the connection to be closed before terminating.

**Comment by tejal29** [comment]
For Long term solution, 
look into `skaffold server` 

For short term, 
 - Waiting until we see one client connected i.e. `--rpc-wait=true`
 - Waiting for 2-3 seconds `--rpc-wait=2s`
 - skaffold connects to a server and blocks until its connected.


We decided, we will implement this in H2. This will give the team the time to implement this feature correctly,

**Comment by tejal29** [comment]
Reducing priority for q3 as this feature wont be consumed in Q3 (mostly in q4)

**Comment by tejal29** [comment]
@marlon-gamez to give more updates on this ticket.

**Comment by MarlonGamez** [comment]
@ekupershlak, we have a flag now `--wait-for-connection` that will pause execution of skaffold until the `/v2/events` endpoint is hit, either through gRPC or HTTP endpoints. Is this sufficient?

**Comment by ekupershlak** [comment]
That sounds perfect - thank you!

**Comment by MarlonGamez** [comment]
Going to close this issue for now, please feel free to reopen if you think more changes should be made for this @ekupershlak
