### ISSUE TITLE
CLI command to fetch configuration properties

### ISSUE THREAD

**Issue by ekupershlak** [GoogleContainerTools/skaffold#5836]
It would be useful to have a command that can output structured details about a Skaffold configuration, so that tools that invoke the Skaffold CLI can make intelligent decisions about what can be done. For example, enable an option to run `skaffold test` if the configuration has tests.

Tools could directly inspect the Skaffold yaml, but a stable API, similar to the existing Metadata API object, would allow usage that doesn't depend on the configuration format.

**Comment by tejal29** [comment]
/cc @ekupershlak /cc @aaron-prindle Can we extend the existing `skaffold inspect ` command to do this?
Decreasing the priority to p2 for q3-21

**Comment by aaron-prindle** [comment]
Skaffold test inspection is supported now with `skaffold inspect tests list` command - https://github.com/GoogleContainerTools/skaffold/pull/6446.  Closing this for now, please re-open if there are some additional Metadata API objects that are required here outside of `tests`
