### ISSUE TITLE
Docs - Add CICD example with Google Cloud Build

### ISSUE THREAD

**Issue by agmsb** [GoogleContainerTools/skaffold#5866]
Looking to add a CICD tutorial with Skaffold and Google Cloud Build, similar to the GitLab example: https://skaffold.dev/docs/tutorials/ci_cd/.

I would directly just open a PR but wanted to discuss how to best organize this. Current breadcrumbs seem to be set up as `Documentation > Tutorials > Skaffold in CI/CD` and the path is just under `/ci_cd`. 

Should I merge this into the same page, and add a separate section on Cloud Build? Or should this be a separate page.

**Comment by tejal29** [comment]
Thanks @agmsb for adding to our docs. 
Please create a new page ttps://skaffold.dev/docs/tutorials/ci-cd-gcb and it will show up as another tutorial in the tutorial menu.

**Comment by agmsb** [comment]
Thanks. Makes sense!

**Comment by aaron-prindle** [comment]
@agmsb friendly ping.  Is there anything that skaffold team can do to help here?  Additionally if it is helpful feel free to submit a "Draft" type PR which might be easier to iterate on w/ the skaffold team while the docs are in more of a WIP state.

**Comment by nkubala** [comment]
@agmsb I'm gonna close this since I don't think there's anything left for our team to do, but please feel free and submit your example if and when it's ready! also if you're still unsure on where to add it, you can always open a PR and we can give you more concrete feedback.
