### ISSUE TITLE
Skaffold dev/debug should exit with error code 128 when incorrect flags are passed

### ISSUE THREAD

**Issue by sujit-kamireddy** [GoogleContainerTools/skaffold#5867]

**Comment by tejal29** [comment]
@sujit-kamireddy do you have a timeline in mind so we can plan for this accordingly.

**Comment by sujit-kamireddy** [comment]
We will be taking up our feature in H2. It will be great if we can get it by July/August time frame.

**Comment by tejal29** [comment]
Sounds good @sujit-kamireddy. Scheduled it for mid Aug release.

**Comment by ahmetb** [comment]
I will take a stab at this, I am trying to understand why `dev` and `debug` only? would we want to make this a cli-wide behavior or just these two commands because presumably Cloud Code is integrating with those?

**Comment by ahmetb** [comment]
Also is there any specific reason to stick to 128? I suspect it's best practice to document this behavior eventually, and in that case, we should probably pick the right value. Is there established convention around 128 being _invalid arguments_ (I am not finding much on it, e.g. [here](https://tldp.org/LDP/abs/html/exitcodes.html)).

**Comment by tejal29** [comment]
Thanks @ahmetb.
Some context around this from my prev discussion with @sujit-kamireddy.
We should make is cli-wide behavior.  Currently, we exit with `1` exit code. 
The 
```
~/workspace/skaffold/out/skaffold dev -d gcr.io/tejal-gke1 -v=trace --help1
unknown flag: --help1
See 'skaffold dev --help' for usage.
```


Skaffold uses cobra library and we use `NoArgs` and `ExactArgs` function. 
See cmd/command.go.
Skaffold does some error message handling [here](https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/skaffold.go#L73) and return 0 or 1 error code. 
It would be great if we parse the error message and set error code to 127 (std error code when invalid args are set) if `invalid args` or `unknown flag` error is present
