### ISSUE TITLE
run skaffold with non root user

### ISSUE THREAD

**Issue by dsaydon90** [GoogleContainerTools/skaffold#5897]
I'm currently running my `minikube` with non root user on my ubuntu 20.04 with: `minikube start --driver=none`
But when I'm trying to run `skaffold` with non root user it's asking for sudo password

### Expected behavior

Ability to run `skaffold` without sudo permissions 

- Skaffold version:  `v1.24.1`
- Operating system:  `Ubuntu 20.04.2 LTS`
- Installed via:  `skaffold.dev`

### Steps to reproduce the behavior

1. start minikube with driver none: `minikube start --driver=none`
2. run any skaffold command like: skaffold build
3. you will be asked for sudo password

minikube should support running with non root user on driver none: https://github.com/kubernetes/minikube/issues/3760

**Comment by briandealwis** [comment]
Could you run with `-v debug` and attach the log here?  That will include the external commands being invoked.  Skaffold doesn't invoke `sudo` or `su`, but clearly something is invoking it and the logs should help track that down.

**Comment by dsaydon90** [comment]
it seems that it was an issue on my pc that minikube from some reason requested for `sudo` probably due to left overs from old `minikube` installations.
The related command was: `/usr/local/bin/minikube docker-env --shell none -p minikube --user=skaffold`
After re-install the `mikube` it didn't ask sudo for the command above

The only thing that might help on this scenario from the `skaffold` level can be only to verify that the current user can run `minikube` commands, and if not just to present the error. But it's not so critical.
