### ISSUE TITLE
`skaffold inspect build-env add googleCloudBuild add` does not include options to set `logging` and `logStreamingOption` fields and others

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#5947]
### Expected behavior
The logging field is set under googleCloudBuild in the skaffold.yaml

### Actual behavior
Command errors saying the logging option in unrecognized.

### Information

- Skaffold version: 1.25.0
- Operating system: macOS 11.4
- Installed via: skaffold.dev

### Steps to reproduce the behavior

1. Run `skaffold inspect build-env add googleCloudBuild add --logging GCS_ONLY`

**Comment by aaron-prindle** [comment]
@tejal29 are you familiar w/ what the correct fix here is?  Currently GoogleCloudBuild has a number of fields here:
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v2beta16/config.go#L290-L361

That are not in the set of flags for `skaffold inspect build_env add googleCloudBuild`:
https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/inspect_build_env.go#L120-L126

I can implement the fix, just not quite sure what the behavior should be or if there is a more generic way to update the flags here.

**Comment by aaron-prindle** [comment]
@gsquared94 are you familiar w/ what the correct fix here might be, is it updating the flags in `inspect_build_env.go`?  I can implement the fix, just not quite sure what the behavior should be or if there is a more generic way to update the flags here.

**Comment by aaron-prindle** [comment]
Talked offline, the issue that is that some flags were not added (see above comment).  I have self-assigned and am working on fix
