### ISSUE TITLE
kaniko push-retry

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#5967]
dear supporting team,
kaniko provides e.g. a flag like `--push-retry`

how to pass this flag into kaniko build section in yaml as per
https://skaffold.dev/docs/references/yaml/#build-artifacts-kaniko ?

- Skaffold version: 1.25
- Operating system: any

**Comment by tejal29** [comment]
@MarcoSchaar, you could submit a [PR](https://github.com/GoogleContainerTools/skaffold/pull/4900) like this to support a new kaniko flag.

Please follow https://github.com/GoogleContainerTools/skaffold/blob/master/DEVELOPMENT.md#making-a-config-change to add a config for `--push-retry` e.g. `pushRetry`.
