### ISSUE TITLE
Skaffold should guard against invalid tags

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5979]
A user on the `#skaffold` channel was encountering a puzzling error:

```
Hello,

I am new to skaffold, I am facing issue while execeuting skaffold build application via skaffold in BB pipelines.
I have tried to echo variables mentioned like  $TARGET , $DOCKER_REGISTRY
before execution all are properly set but still it end up in error .

Kindly provide pointers to fix it.

+ skaffold build -p $TARGET --default-repo $DOCKER_REGISTRY --file-output ./dist/artifacts.json
Generating tags...
applying default repo to "test-api:test-api:0.1.0-d69db0d": invalid reference format
```

The use is using the git-tagger and must have a version tag with a colon. We should verify that the generated tag is a valid tag.

**Comment by JacekDuszenko** [comment]
Hey @briandealwis, I wanted to take a stab at this task here, but am not sure where in the codebase this tag verification should happen. Could you please elaborate more on this? Pointing the place in code would be really helpful as well. Thanks!

**Comment by briandealwis** [comment]
I'm sorry @JacekDuszenko, I missed your request.  I think this tag issue could happen for any of the tag policies, so I think the right place is in [`tag.GenerateFullyQualifiedImageName()`](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/tag/tag.go#L37).
