### ISSUE TITLE
Can't change build environment to `local` using `skaffold inspect build-env add`

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#5998]
### Expected behavior
`skaffold inspect build-env add local` is a command, as all other build environments are supported here.

### Actual behavior
`skaffold inspect build-env add local` is *not* a command

### Information

- Skaffold version: 1.25.0
- Operating system: macOS 11.4
- Installed via: skaffold.dev

### Steps to reproduce the behavior

1. `skaffold inspect build-env add local`

**Comment by gsquared94** [comment]
fixed in https://github.com/GoogleContainerTools/skaffold/pull/5944
