### ISSUE TITLE
Copyright statements

### ISSUE THREAD

**Issue by afrittoli** [GoogleContainerTools/skaffold#600]
Question more than an issue really. 
When adding new files in a PR I was trying to add something like this:

'''
/*
Copyright 2018 IBM Corporation
Copyright 2018 Google LLC
'''

But that won't work because of the enforced boilerplate:
https://github.com/GoogleContainerTools/skaffold/blob/f91c91514fe6d2403df65784434a22f95712bda2/hack/boilerplate/boilerplate.go.txt#L2

Is this by design? Must every contribution get Google copyright (with Apache 2.0 license)?

**Comment by afrittoli** [comment]
Reading thought the corporate CLA https://cla.developers.google.com/about/google-corporate I understand that contributor in fact grant the Copyright License. This answers my question.

**Comment by afrittoli** [comment]
I compared Google CCLA with OpenStack CCLA, and the both include a "Grant of Copyright License".
OpenStack does not however enforce an "OpenStack Foundation Copyright" header; copyright headers are added on new files or substantial contributions to existing ones: https://wiki.openstack.org/wiki/Documentation/Copyright.

Kubernetes uses "The Kubernetes Authors" as copyright holders: https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.go.txt which I think is a nice and clean solution.

**Comment by dgageot** [comment]
ping @dlorenc @kimsterv

**Comment by dlorenc** [comment]
Just confirmed we can change the copyright headers to "The Skaffold Authors". I'll send a pr to update this shortly.

**Comment by afrittoli** [comment]
Thanks!

**Comment by dgageot** [comment]
@afrittoli Can we close this issue?

**Comment by afrittoli** [comment]
Thanks for the fix!
