### ISSUE TITLE
Docker images with Java 8 JDK

### ISSUE THREAD

**Issue by bruno-lopes** [GoogleContainerTools/skaffold#6012]
### Expected behavior

I would like to be able to select a Docker image of Skaffold, example: v1.26.0 with Java 8 JDK (I have to use it with legacy systems)

### Actual behavior

The image has JDK 11 installed. Is it possible to have it with Java 8 JDK ?

### Information

- Skaffold version: v1.24.0
- Operating system: Linux

**Comment by gsquared94** [comment]
I've added this to our triage discussion. Will update.

**Comment by briandealwis** [comment]
Hi @bruno-lopes.  Many newer Maven plugins no longer work with JDK 8.  Our `gcr.io/k8s-skaffold/skaffold` image is already too hefty.

I can think of a few alternatives:
- You could create your own image using `gcr.io/k8s-skaffold/skaffold` as a base image and install a Java 8 JDK and configure toolchains.
- You could create your own image using your JDK of choice and install Skaffold there.  The latest release can be obtained from https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64

**Comment by bruno-lopes** [comment]
@briandealwis, thanks! I have opted to create my own image using a specific JDK as you suggested.
