### ISSUE TITLE
gcr.io/k8s-skaffold/pack 0.19.0 support

### ISSUE THREAD

**Issue by cage1016** [GoogleContainerTools/skaffold#6028]
### Expected behavior

[GoogleCloudPlatform/buildpacks: Builders and buildpacks designed to run on Google Cloud's container platforms](https://github.com/GoogleCloudPlatform/buildpacks#using-with-google-cloud-build) mention that instance by using the pack builder image provided by the Skaffold project. buildpacks/pack release [v0.19.0 ](https://github.com/buildpacks/pack/releases/tag/v0.19.0) 19 days ago

https://console.cloud.google.com/gcr/images/k8s-skaffold/GLOBAL/pack?gcrImageListsize=30 should add v0.19.0 release tag

### Actual behavior

gcr.io/k8s-skaffold/pack latest version is v0.17.0

**Comment by tejal29** [comment]
@briandealwis do you have any idea?

**Comment by cage1016** [comment]
[Images – Container Registry – Google Cloud Platform](https://console.cloud.google.com/gcr/images/k8s-skaffold/GLOBAL/pack?gcrImageListsize=30) gcr.io/k8s-skaffold/pack has been updated to latest version (v0.21.1) at 7 hours ago.

Thanks and i close this issue.
