### ISSUE TITLE
Skaffold should provide a mechanism to include remote modules in-tree

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6030]
For some deployment scenarios, it is useful to be able to run tests post-delivery, such as by using `skaffold test`.  As these tests likely reference resources (e.g., scripts) within the application, the user (or a tool) might zip up the workspace as a snapshot fo the application to be able to run these tests separately.

This can breaks when an application uses remote modules as our current modules implementation downloads the remote modules into a local cache location that exists outside of the workspace. This means that the zip is incomplete.  Although Skaffold may download the remote modules on the next `skaffold test`, there's no guarantee that the newly-cloned repositories correspond to the state at the time of the deployment.

One possibility:
  1. Skaffold should look for modules in a specific place in the local directory.  `.skaffold/modules`?
  2. Offer a `skaffold prepare` or `skaffold stage` that pull in the referenced modules into this `.skaffold/modules` location

**Comment by gsquared94** [comment]
you can override the remote module download location using the flag `--remote-cache-dir` so you can have it downloaded to zip target. I think that addresses this issue, WDYT?

**Comment by briandealwis** [comment]
SGTM.  FYI @ekupershlak
