### ISSUE TITLE
Enable hidden schema changes

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/skaffold#6040]
It'd be great to establish a mechanism for making backwards compatible schema changes as part of a series of small PRs that implement a feature.

This will allow the PRs to be merged continuously, rather than all at the end.

Currently, if there's a Skaffold release part-way through a series of PRs for a feature, schema changes will be visible in user documentation even if the feature isn't ready for use yet.

**Comment by gsquared94** [comment]
I think if there's no path from config root to the newly introduced struct then it doesn't show up in the user documentation.
For instance, I've added `BuildHooks` struct excluded from the `yaml` parser:
https://github.com/GoogleContainerTools/skaffold/blob/eee8a212420bf87cc9cbcc4ab77b68e28c8c8956/pkg/skaffold/schema/latest/v1/config.go#L860-L861

It doesn't show up on the docsite https://skaffold-latest.firebaseapp.com/docs/references/yaml/:
![image](https://user-images.githubusercontent.com/39389231/125593463-ed6a6935-7578-4b3c-9b11-f203783a331b.png)

When this feature is ready I'll expose this field in which ever config version is the latest at that time.

WDYT @halvards ?

**Comment by halvards** [comment]
Perfect, thanks @gsquared94! This matches the implementation plan for the ko builder.
