### ISSUE TITLE
Add ko builder

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/skaffold#6041]
Tracking issue for the effort to add the `ko` builder.

See the [design proposal](../blob/master/docs/design_proposals/ko-builder.md) for further details.

Related: #5611, #1958

**Comment by halvards** [comment]
Related PRs in [google/ko](https://github.com/google/ko):

- [Enable embedding of ko publish #348](https://github.com/google/ko/pull/348)
- [Add flag and PublishOption for destination repo #351](https://github.com/google/ko/pull/351)
- [Enable setting the working dir for the go tool #365](https://github.com/google/ko/pull/365)
- [Add support for Go build flags #340](https://github.com/google/ko/pull/340)

**Comment by tejal29** [comment]
Thanks for creating the issue!

**Comment by aaron-prindle** [comment]
ko builder is added now 🎊! Marking closed(fixed)
