### ISSUE TITLE
Perform cleanup during development or on exit

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#61]
This is an umbrella issue for some ideas on how we might clean up the development artifacts we create in a `skaffold dev` pipeline.

- [ ] Auto prune images/tags to save disk splace

**Comment by dgageot** [comment]
Not yet finished!

**Comment by nkubala** [comment]
@dgageot what else needs to be done here?

**Comment by dgageot** [comment]
@nkubala image pruning is not done but we could create a new issue for that

**Comment by dgageot** [comment]
Let's close this one since #733 is here to implement pruning
