### ISSUE TITLE
[FR] Implement fixes for misconfigurations in user Dockerfile

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6103]
Implement top 2 recommendations for misconfigurations in users dockerfile

**Comment by tejal29** [comment]
Nice! thanks for creating this issue.  The first one we want to recommend is:
1) If Dockerfile exists at root of the project with  `Copy . .` exists, flag it.  Reason being
   - It watches all `.git`, `.vscode`, `.idea` and 
   - If user still wants to add `Copy . .` prompt user to add these files in `.Dockerfileignore`
 
2) TODO - suggest another. 

Can you also add an issue to track a DD for recommendation system?
 - is it going to be a command?
 - will skaffold automatically do this at the end of dev command?

**Comment by aaron-prindle** [comment]
Added tracking issue for DD for recommendation system here - #6122
