### ISSUE TITLE
Add a `skaffold stop/destroy` command 

### ISSUE THREAD

**Issue by tossmilestone** [GoogleContainerTools/skaffold#611]
Hi, guys. Is there a plan to add `skaffold stop/destroy` command if someone want to stop the running services? Because sometimes the running services are high cpu/mem utilization.

Thanks

**Comment by dgageot** [comment]
@tossmilestone master container a`skaffold delete` command that sneaked in in this [PR](https://github.com/GoogleContainerTools/skaffold/pull/589)

**Comment by tossmilestone** [comment]
@dgageot thanks，I will have a try
