### ISSUE TITLE
Enabling Cross-platform builds with Skaffold

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6120]
# Enabling Cross-platform builds with Skaffold

## Local build environment
The local build environment delegates to the individual artifact builder to decide the list of supported platforms.
- [x] Docker builder supports cross-platform
- [x] Custom builder supports cross-platform and multi-platform
- [x] Jib supports cross-platform and multi-platform
- [x] ~~Buildpacks builder only supports `linux/amd64`~~ (pending https://github.com/buildpacks/lifecycle/issues/435)
- [x] ~~Bazel supports cross-platform~~ (out of scope)
- [x] Kaniko supports cross-platform depending on the platform configuration for the nodes of the target kubernetes cluster.

## Google Cloud Build build environment

- [x] Docker builder supports cross-platform
- [x] Jib supports cross-platform and multi-platform

## Cluster build environment

- [x] The Cluster build environment supports cross-platform depending on the platform configuration for the nodes of the target kubernetes cluster.

**Comment by tejal29** [comment]
This is now being de-prioritized. Please move to Dec timeline.

**Comment by snickell** [comment]
Any sense what's required on this still after the merger of #7021?

**Comment by gsquared94** [comment]
> Any sense what's required on this still after the merger of #7021?

updated issue description.
