### ISSUE TITLE
[DD] Design recommendation system (command, log-output, etc.) for recommending config fixes to skaffold users

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6122]
Tracking issue for designing a recommendation system to output config recommendations to skaffold users, for example:
- Configuration improvements/fixes for a user's Dockerfiles w/ skaffold - #6103 
- Configuration improvements/fixes for user's skaffold.yaml - #6102 
- Configuration improvements/fixes for k8s #6098

Questions design doc should answer:
- is it going to be a command?
- will skaffold automatically do this at the end of dev command?

**Comment by tejal29** [comment]
Thanks!!

**Comment by aaron-prindle** [comment]
Document is finished with review feedback.  Implementation has begun, marking fixed
