### ISSUE TITLE
Skaffold process takes a long time to terminate after ctrl-c

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#6123]
Skaffold 1.27.0 (also noticed in earlier versions)
Deployment to GKE
Skaffold yaml: https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/java/java-hello-world/skaffold.yaml
Command run: `skaffold dev --default-repo=my-repo`

**Expected:**
After skaffold prints the log lines that the resources were deleted:

```
^CCleaning up...
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
```

The process should end.

**Actual**
Skaffold prints those lines above, and then takes a long time to exit (~30 seconds). I'm not sure if the bug is that it is taking so long to exit, or that the logging isn't clear enough (there should be some indication that something is still happening - what is printed makes it looks like its done, and skaffold is stuck).

![Kapture 2021-07-01 at 16 49 22](https://user-images.githubusercontent.com/1735744/124187819-5ddd6880-da8c-11eb-8208-e6619b3db5ef.gif)
Notice the process running on the right terminal.

**Comment by tejal29** [comment]
I think the time spent is in pruning/cleaning images.
Can you try running with `--no-prune=true` which will skip pruning of images to make sure that us the culprit

**Comment by etanshaul** [comment]
even with `--no-prune=true` it still takes a long time to terminate after Skaffold prints:

```
Cleaning up...
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
```

**Comment by etanshaul** [comment]
According to the [docs](https://skaffold.dev/docs/pipeline-stages/cleanup/#image-pruning), I should have seen prune related log lines right?

```
Pruning images...
untagged image gcr.io/k8s-skaffold/skaffold-example:v0.41.0-148-gd2f3e0539
untagged image gcr.io/k8s-skaffold/skaffold-example:v0.41.0-58-g8c428b975
untagged image gcr.io/k8s-skaffold/skaffold-example@sha256:00d7fa06c313f7d06ad3d4701026e0ee65f8f437c703172f160df37c0059b3b1
deleted image sha256:f7a2f5c3a2f6721989598d09a09ad70134936db398d93303ebb3545de2d32e22
deleted image sha256:c069434a51c8d96f68a95c13bbccd3512849f9ccfe5defbb80af7e342a48bbba
```

But in reality, I have never seen those (despite never having issued `--no-prune=true`.

**Comment by tejal29** [comment]
Thanks for confirming. I will investigate this.

**Comment by tejal29** [comment]
Attaching debug logs.  Looks like the cleanup took 6.25 seconds.
```
DEBU[0028] Running command: [kubectl --context gke_tejal-gke1_us-central1-c_dump-apis delete --ignore-not-found=true -f -] 
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
INFO[0034] Cleanup completed in 6.252 seconds           

DEBU[0034] exporting metrics   
````

Need to investigate more and add more debug logs for clean up phase.

**Comment by etanshaul** [comment]
I should turn on debug logs too to test. It took closer to 30 seconds for cleanup for me (this was on GKE)

**Comment by tejal29** [comment]
Digging in some more, 
1) clean up for kubectl deployer on minikube context,  took 6 seconds
```
DEBU[0008] Running command: [kubectl --context minikube --namespace test delete --ignore-not-found=true -f -] 
 - pod "getting-started" deleted
INFO[0015] Cleanup completed in 6.952 seconds           

DEBU[0015] exporting metrics                            
DEBU[0016] metrics uploading complete in 967.748847ms   
➜  getting-started git:(deploy-namespaces) ✗ 
```

2) clean up for app deployed via helm took 2 seconds
```
DEBU[0010] Running command: [helm --kube-context minikube delete skaffold-helm --namespace test] 
release "skaffold-helm" uninstalled
INFO[0012] Cleanup completed in 1.96 second 
```

**Comment by aaron-prindle** [comment]
In attempting this, I have seen the following times on repeated runs on GKE:

Skaffold v1.27.0 `Cleanup completed in *`
- 6.25 seconds
- 2.54 seconds
- 740.321245ms
- 848.830373ms

```
skaffold dev --default-repo=gcr.io/aprindle-billing-test -v debug
...
...
DEBU[0050] Running command: [kubectl --context gke_aprindle-billing-test_us-central1-c_aprindle-test-cluster delete --ignore-not-found=true -f -] 
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
INFO[0051] Cleanup completed in 848.830373ms            

DEBU[0051] exporting metrics                            
DEBU[0052] metrics uploading complete in 1.052936914s  
```

In trying an older Skaffold version:

Skaffold v1.19.0 `Cleanup completed in *`:
- 3.756 seconds 
- 786.376282ms 
- 8.567 seconds 
- 8.645 seconds

```
DEBU[0037] Running command: [kubectl --context gke_aprindle-billing-test_us-central1-c_aprindle-test-cluster delete --ignore-not-found=true -f -] 
 - deployment.apps "java-hello-world" deleted
 - service "java-hello-world-external" deleted
INFO[0040] Cleanup completed in 3.756 seconds           
DEBU[0040] exporting metrics                
```

**Comment by aaron-prindle** [comment]
I believe this variability is due to kubectl having a variable time for this output.  All below trace information comes from skaffold v1.28.0 using https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/java/java-hello-world/skaffold.yaml app code.  With this same app I see variable cleanup times on different runs:
- 834.261ms
- 1539.967ms (1.5 seconds)
- 14001ms (14 seconds)

Trace for Cleanup phase on 1.5 second run:
![image](https://user-images.githubusercontent.com/1951658/125687783-27d8011f-f81a-4568-bfe2-4f0519956bfe.png)


Trace for the Cleanup phase on a 14 second run:
![image](https://user-images.githubusercontent.com/1951658/125687387-07e45d24-50e5-40d7-b3c2-1f2199ccbf2f.png)

This is the trace for Cleanup on an 800ms run

**Comment by aaron-prindle** [comment]
Will investigate more why kubectl.Delete:
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl/kubectl.go#L461

varies so much for the same project & skaffold config

**Comment by aaron-prindle** [comment]
Using kubectl `--wait=false` flag:
eg: `kubectl delete --wait=false -f foo.yaml`

I am consistently seeing the Cleanup_kubectl.Delete phase taking ~400-600ms.  From 3 consecutive runs:
- 609ms
- 638ms
- 408ms

![image](https://user-images.githubusercontent.com/1951658/125689619-8895efe3-504d-41c2-b32f-769551f9bd9d.png)

**Comment by aaron-prindle** [comment]
I will submit a PR w/ this change, post on the PR or issue here if there are any objections/issues-with-skaffold in changing cleanup to do this.  Currently I do not believe there are any downsides with not having skaffold wait for the deletes and the UX is better (users not hanging for what can be ~10s for delete to finish)

**Comment by etanshaul** [comment]
> Currently I do not believe there are any downsides with not having skaffold wait for the deletes and the UX is better (users not hanging for what can be ~10s for delete to finish)

The alternative (not making a judgment on which is better, but just pointing it out) might be just to have skaffold print something to at least let the user know that it is waiting for the cleanup to actually finish. As it stands today, it looks like it's done and skaffold is hanging.
