### ISSUE TITLE
pseudo-empty string "<no value>" returned by setValueTemplate when undefined environment variable 

### ISSUE THREAD

**Issue by AleksandarFaraj** [GoogleContainerTools/skaffold#6128]
For undefined environment variables setValueTemplates returns pseudo-empty string "" with 10 length and no whitespace, where value is: \<no value\> but not visible in output when rendering the template

In helm outputs empty string "q{{ .Values.envName }}p" visually "qp". actually "q\<no value\>p".
It is not considered empty. {{empty .Values.envName}} === false
It is not falsy for {{ default 'def' .Values.envName }} === visually empty.
Causing yaml errors if not quoted since it's outputted as Nothing. Not "" 
It has no whitespace.
Trim has no effect.
It equals "\<no value\>"

### Expected behavior
For undefined environment variables I expect .Values.image.pullSecretsName to be _ANY_ sane result. Either null, nil, undefined, false, len 0 string "", the actually visible value "\<no value\>", "\u003cno value\u003e" 

skaffold.yaml
```yaml
deploy:
  helm:
    releases:
      - name: app
        chartPath: app/helm
        setValueTemplates:
          image.pullSecretsName: "{{.SECRET_NAME}}"

```

deployment.yaml
```yaml
imagePullSecrets:
  - name: {{ default "repository_secret" .Values.image.pullSecretsName }}
```

1. command:
```bash
echo "$SECRET_NAME key does not exist, has no value"  
skaffold run
```

output:
```yaml
imagePullSecrets:
  - name: repository_secret
```

2. with env
```bash
SECRET_NAME=secret000001 skaffold run
```

output:
```yaml
imagePullSecrets:
  - name: secret000001
```

### Actual behavior
1. command:
```bash
echo "$SECRET_NAME key does not exist, has no value"  
skaffold run

```

deployed output:
```yaml
imagePullSecrets:
  - {}
```

actual value:
```
.Values.image.pullSecretsName = ""
len .Values.image.pullSecretsName = 10
empty .Values.image.pullSecretsName // false
toJson .Values.image.pullSecretsName // "\u003cno value\u003e" 

eq .Values.image.pullSecretsName "<no value>" // true
```

### Hack

```
 imagePullSecrets:
   - name: '{{ (eq .Values.image.pullSecretsName "<no value>") | ternary "secret-repository" ( default "secret-repository" .Values.image.pullSecretsName) }}'

```

**Comment by briandealwis** [comment]
This `<no value>` is the default behaviour of Go templates.  But I agree it's odd.  It can be changed with the [`missing=zero` option](https://golang.org/pkg/text/template/#Template.Option).

**Comment by briandealwis** [comment]
@nkubala @viglesiasce any thoughts on changing our templates to replace missing values with an empty string instead of Go's default of `<no value>`?

**Comment by nkubala** [comment]
I'm assuming Go chose to use `<no value>` intentionally, probably to ensure that parsed templates referencing unset values don't fail silently on an empty string. that said, there are plenty of valid cases where users actually *want* that behavior, especially when falling back on default values - case in point here. I'm fine changing the way we handle this in skaffold.
