### ISSUE TITLE
Provide flag to turn off syncing remote modules

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6145]
The remote modules schema supports the field `sync` to turn off auto-syncing the downloaded remote modules at the start of every skaffold process. There should also be an overriding flag to this effect.

https://skaffold.dev/docs/references/yaml/#requires-git-sync

**Comment by ekupershlak** [comment]
Would it also be possible to fail if (somehow) the cache does not contain the file? e.g. with a `--cached-only` flag 

/cc @maggieneterval
