### ISSUE TITLE
Flake TestGracefulBuildCancel is flaky

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6154]
### Expected behavior
Run `go test github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/misc` can always give consistent results. 

### Actual behavior
Run `make quicktest` multiple times, `github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/misc` sometimes pass and sometimes fail.

### Information
```
=== Failed Tests ===
/pkg/skaffold/build/misc/TestGracefulBuildCancel
--- FAIL: TestGracefulBuildCancel (0.61s)
/pkg/skaffold/build/misc/TestGracefulBuildCancel/terminate_before_timeout
    graceful_test.go:64: unexpected error: signal: interrupt
    --- FAIL: TestGracefulBuildCancel/terminate_before_timeout (0.20s)
```

- Skaffold version: running against [master](https://github.com/GoogleContainerTools/skaffold/commit/823896bdd7464d79886664b32f56948957ea5f65)

**Comment by tejal29** [comment]
Saw  this again on https://github.com/GoogleContainerTools/skaffold/pull/7148

**Comment by aaron-prindle** [comment]
Haven't seen this for a while, marking closed (fixed)
