### ISSUE TITLE
Feature request - add dry run option to skaffold delete

### ISSUE THREAD

**Issue by yuhuishi-convect** [GoogleContainerTools/skaffold#6156]
### Expected behavior

Can we add a "dry run" option to `skaffold delete`, to give an overview on what are the resources that are going to be deleted?
Or alternatively, can we add a user prompt before the actual deletion happens?

Got this idea after accidentally deleting a namespace that contains workloads belonging to other services in one `skaffold delete` run.

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by briandealwis** [comment]
Patches welcome!
