### ISSUE TITLE
Watch does not recompute dependencies

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#617]
Current flow:
1. Artifact dependencies are computed (expanded)
2. Those computed dependencies are sent to the watcher
3. Watcher watches that file list and directory list

This doesn't handle new files or directories, and sometimes fails on deleted files. Not sure what should happen here - maybe each file change should be matched against the glob pattern given by the artifact. Either way, it would require the watcher to be given more information.

This is particularly painful when using skaffold on a new project that has a dockerfile that copies the entire repository as the build context

**Comment by dgageot** [comment]
@r2d4 I think switching out of the notify watcher will make all those things not too complicated

**Comment by jonjohnsonjr** [comment]
From https://github.com/GoogleContainerTools/skaffold/issues/272#issuecomment-389668873
> What's the interest level for making a PR?

Sounds like high level of interest?

**Comment by r2d4** [comment]
fsevents is macOS only and has an unreasonably low limit for the amount of watches that you can do (its hardcoded to ~400). On the other hand, a recursive directory watch only counts as 1 watch. We used fsevents in the very first watch impl for skaffold

**Comment by jonjohnsonjr** [comment]
I think watchman uses the right watcher depending on the platform:
https://github.com/facebook/watchman
