### ISSUE TITLE
How to use existing workflow tool like Draft?

### ISSUE THREAD

**Issue by fkpwolf** [GoogleContainerTools/skaffold#618]
It is said "Skaffold has a pluggable architecture that allows you to choose the tools in the developer workflow that work best for you.". 
It is a nice feature. But I can't find related info. What's the default workflow tool and how to change it to tool like Draft?

**Comment by dlorenc** [comment]
Skaffold supports plugins for the build/deploy/tag steps.

Can you explain how you would like to use Skaffold and Draft together?

**Comment by fkpwolf** [comment]
I just want to try the "pluggable" feature. You can replace Draft with any other workflow tools.

**Comment by dlorenc** [comment]
Can you explain what it would do? Skaffold and draft are both workflow tools, so I'm not sure I understand the goal. Draft and Skaffold do some of the same things, so you would use Draft instead of Skaffold.

**Comment by dlorenc** [comment]
I'm going to close this for now. Please re-open with more information.
