### ISSUE TITLE
`skaffold init --generate-manifests` failing to generate manifests for Jib project

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6203]
### Actual behavior

```
$ cd examples/jib
$ rm -rf k8s skaffold.yaml
$ skaffold init --generate-manifests
? Which builders would you like to create kubernetes resources for?  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [ ]  Buildpacks (pom.xml)
  [ ]  Jib Maven Plugin (org.skaffold:hello-spring-boot, pom.xml)
<select Jib Maven Plugin>
one or more valid Kubernetes manifests are required to run skaffold
```

### Expected behavior

Expected to have Kubernetes manifests generated.

Workaround: `skaffold init --generate-manifests --XXenableBuildpacksInit=false` is successful.

It looks like this logic in `defaultBuildInitializer.resolveBuilderImages()` to call `generateArtifactInfos()` needs to happen regardless of the number of builders.
https://github.com/GoogleContainerTools/skaffold/blob/7b18b11ba98ea0e48c0dc500d0b8f48e94867978/pkg/skaffold/initializer/build/resolve.go#L38-L44

### Information

- Skaffold version: HEAD; reported on Slack with 1.27.0
- Operating system: darwin

**Comment by MarlonGamez** [comment]
@briandealwis I think the issue here is that hitting enter without selecting any options will cause this to happen. Space needs to be used to select, then enter to move forward, which is a bit of confusing UX.

**Comment by sivakku** [comment]
i used up & down arrow to choose the builder option and see that one of the builder is picked but it didn't seem to register and as a result it failed.

``` $ '/Users/sivakk/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/skaffold' init --generate-manifests
? Which builders would you like to create kubernetes resources for?                                                                  one or more valid Kubernetes manifests are required to run skaffold
sivakk@sivakk-macbookpro ~/dev/cloudcode-projects/java-server-demos/jboss/wildfly/helloworld (main) $ '/Users/sivakk/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/skaffold' init --generate-manifests
? Which builders would you like to create kubernetes resources for?                                                                  one or more valid Kubernetes manifests are required to run skaffold ```

**Comment by MarlonGamez** [comment]
@sivakku did you use `space` to select the option that you wanted to generate for?
When unselected, it looks like so:
<img width="617" alt="Screen Shot 2021-09-15 at 11 57 12 AM" src="https://user-images.githubusercontent.com/12601690/133493151-07b379a7-9bc5-42bb-a594-751edf26e401.png">

and when selected, looks like this:
<img width="620" alt="Screen Shot 2021-09-15 at 11 57 23 AM" src="https://user-images.githubusercontent.com/12601690/133493197-defcc516-09ff-4f1c-b311-0af604db03c9.png">

If you've properly selected and are still seeing this issue, can you please link to a repo which I can use to reproduce this?

**Comment by briandealwis** [comment]
He mentioned to me that he used this repo: https://github.com/subfuzion/java-server-demos/tree/main/jboss/wildfly/helloworld

**Comment by sivakku** [comment]
That was the repo, thanks i realized the mistake i made that after the down arrow and then i have to use left arrow to highlight, but interesting it picks up.
![image](https://user-images.githubusercontent.com/16199637/133518747-b5d6ed04-cca5-44cf-8551-b3741f30d5eb.png)

**Comment by briandealwis** [comment]
@MarlonGamez why do we use `MultiSelect` to choose one or more builders?  Do we really support selecting multiple builders here?

**Comment by briandealwis** [comment]
If I do a multi-select, then I get different images for the same context.  For example:
```
$ cd examples/jib
$ rm -rf skaffold.yaml k8s
$ skaffold init --generate-manifests
? Which builders would you like to create kubernetes resources for? 
[x] Buildpacks (pom.xml)
[x] Jib Maven Plugin (org.skaffold:hello-spring-boot, pom.xml)
? Which builders would you like to create kubernetes resources for? Buildpacks (pom.xml), Jib Maven Plugin (org.skaffold:hello-spring-boot, pom.xml)
? Select port to forward for pom-xml-image (leave blank for none): 8080
? Select port to forward for pom-xml-image (leave blank for none): 8080

apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: jib
build:
  artifacts:
  - image: pom-xml-image
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: pom-xml-image
    jib:
      project: org.skaffold:hello-spring-boot
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: pom-xml-image
  port: 8080
- resourceType: service
  resourceName: pom-xml-image
  port: 8080
```

I honestly don't think multi-select makes sense here.

**Comment by MarlonGamez** [comment]
Discussed offline with @briandealwis but leaving a similar response here. 
The reason that we use multi select is that in the case of there being multiple possible images that are being built. In this case, we want the user to be able to generate manifests for multiple. The confusion here comes from the possibility of there being multiple builders that can build a single image. In this case, the user could possible select two options that have the same end result.
