### ISSUE TITLE
Allow configuring iterative-status-checks in the skaffold.yaml

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6209]
Related: #6115, #5774 

We should allow users to configure `--iterative-status-checks` in the `skaffold.yaml`.

Alternatively, we should change the default to always be enabled, such that users have to disable it.

**Comment by chronicc** [comment]
I'm for configuring the iterative status-check in the skaffold.yaml.

As a proposal if the iterative status-check field is set inside a module, only this module should wait for the status check. This way we can use the iterative status check only in modules where we know, we need to wait for. All other modules should be deployed as fast as possible.

Ideally modules, that depend on modules which have the iterative status-check enabled, should wait for those modules (as well as all modules above depending on this module). E.g. when **D** is a module using the iterative status-check field and **F** is the module called by `skaffold run`, the dependency graph would look like:

```mermaid
graph TD;
A--wait for D-->C;
B--wait for D-->C;
C--wait for D-->D;
E--wait for D-->D;
D--deploy instantly-->F;
G--deploy instantly-->F;
```
