### ISSUE TITLE
Skaffold Should Be Able To Distinguish When Running in CI vs. Dev

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6212]
Currently skaffold is unable to distinguish when it is being run by a user for dev purposes vs run in a CI system.  It would be helpful for skaffold to distinguish how it is being used for metrics, functionality (disable prompts), etc.

**Comment by aaron-prindle** [comment]
Research from @viglesiasce done offline:

CI env variables that are commonly set in CI systems:
GitLab: CI https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
GitHub Actions: CI https://docs.github.com/en/enterprise-server@2.22/actions/reference/environment-variables
Jenkins: JENKINS_URL https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables
 Cloud Build: BUILD_ID https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

**Comment by aaron-prindle** [comment]
@gsquared94 - we had an old issue that is tracking something similar to your current work.  Adding it to this milestone and assigning you as I believe it will be fixed by the PR you are working on

**Comment by ericzzzzzzz** [comment]
closing as the implementation is done already. will re-open it if any verification related to this change fails when firelog one platform metrics is available.
