### ISSUE TITLE
--tail=false no longer works on dev

### ISSUE THREAD

**Issue by aariacarterweir** [GoogleContainerTools/skaffold#6216]
### Expected behavior
`--tail=false` running on dev should disable logs

### Actual behavior
`--tail=false` running on dev outputs logs

### Information

- Skaffold version: 1.28.0
- Operating system: OS X Big Sur 11.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
# NA
```

**Comment by etrikp** [comment]
Interesting, I'm seeing the exact opposite with 1.28.0. In skaffold 1.27.0 logs were working fine in dev mode by default, and in 1.28.0 I am unable to see any logs at all with either --tail=false or --tail=true
