### ISSUE TITLE
portForward not work

### ISSUE THREAD

**Issue by Spartaques** [GoogleContainerTools/skaffold#6240]
### Expected behavior

Port Forwarding should work by default with command:

skaffold dev -p local --port-forward

### Actual behavior

Port forwarding not work. And i ca'nt find a way i can do this.

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

skaffold version:

v1.28.0

helm version:

version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}

OS: macos Catalina version 10.15.7

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: riup
profiles:
  - name: local
    build:
      artifacts:
        - image: riup-core
          context: ./services/riup_core
          docker:
            dockerfile: Dockerfile.dev

    deploy:
      helm:
        releases:
          - name: riup-core
            chartPath: riup
            artifactOverrides:
              image: riup-core

**Comment by Spartaques** [comment]
I also tries to use portForward manually, but it not works

`apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: riup
profiles:
  - name: local
    build:
      artifacts:
        - image: riup-core
          context: ./services/riup_core
          docker:
            dockerfile: Dockerfile.dev

    deploy:
      helm:
        releases:
          - name: riup-core
            chartPath: riup
            artifactOverrides:
              image: riup-core
    portForward:
      - resourceType: Deployment
        resourceName: riup
        port: 8000
        localPort: 8083 # *Optional*
      - resourceType: Deployment
        resourceName: db
        port: 3306
        localPort: 63309 # *Optional*
      - resourceType: Deployment
        resourceName: mongo
        port: 27017
        localPort: 27018 # *Optional*
      - resourceType: Deployment
        resourceName: kafka-manager
        port: 9000
        localPort: 9000 # *Optional*
`

**Comment by nkubala** [comment]
@Spartaques thanks for the issue! We're aware of this problem having widespread effects in version `1.28.0` - we're working on a hotfix for this now, but in the meantime, we're recommending downgrading to a previous version while we work to fix the issue.

I'll close this issue so we can track in https://github.com/GoogleContainerTools/skaffold/issues/6242. Stay tuned there, and sorry for the inconvenience!
