### ISSUE TITLE
Skaffold doesn't track default namespace when not explicitly provided

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#6242]
### Expected behavior
Skaffold does normal logging, port forwarding, syncing, etc. when deploying to a default namespace (aka no namespace provided)

### Actual behavior
If no namespace is provided, Skaffold does not track the default namespace. As a result, any component that relies on a `PodSelector` to retrieve its resources to operate on does not function. This seems to only apply to `kustomize` and `helm` projects, not `kubectl`.

### Information

- Skaffold version: `v1.28.0`

### Steps to reproduce the behavior

Run `skaffold dev` in our `examples/getting-started-kustomize`.

### More Info

#6170 moved the tracking of the deployed namespaces into the Deployer object. However, it inadvertently removed some pre-processing logic to retrieve the initial namespaces when creating the Deployer. Since the empty string ("") is interpreted as the "default" namespace when deploying to Kubernetes, this meant that all projects deploying to this namespace were not being considered for logging, port forwarding, or any other component that uses a podSelector to retrieve its resources.

**Comment by briandealwis** [comment]
Re-opening: will close once v1.28.1 is released.

**Comment by nkubala** [comment]
[v1.28.1](https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.28.1) has now been published. Closing this issue now
