### ISSUE TITLE
`skaffold init --generate-manifests --force` does not have a way to non-interactively specify exposed ports

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#6248]
### Expected behavior
The command allows for a flag (perhaps `--port-forward=[]` where a non-interactive user (aka a Cloud Code user) can specify ports for each of the images that will be built.

### Actual behavior
The command outputs port 8080 in each of the manifest files and skaffold.yaml port forwards section regardless of what the actual exposed port is. The user should have an opportunity to specify this.

### Information

- Skaffold version: v1.27.0
- Operating system: MacOS Big Sur 11.4
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml: n/a

### Steps to reproduce the behavior

1. Clone https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/nodejs/nodejs-hello-world
2. Delete skaffold.yaml and k8s manifests
2. Change port from 8080
2. `skaffold init --generate-manifests --force`
3. `skaffold dev`
4. *App fails to load*

**Comment by j-windsor** [comment]
@briandealwis mentioned that buildpacks assumes that the app is running on port 8080, so since there is a precedent set for this, we might be able to do the same. In this case, Cloud Code would just have a text blurb saying that it will assume the app is running on 8080.

**Comment by MarlonGamez** [comment]
Seems we need to design and expose some sort of API to allow non interactive use of `--generate-manifests` I'll look into this and be in contact @j-windsor

**Comment by MarlonGamez** [comment]
closing this as we now have a non-interactive way to expose ports in #6599
