### ISSUE TITLE
Clean up build struct

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#625]
Currently the build struct looks like 

```golang
// Build is the result corresponding to each Artifact built.
type Build struct {
	ImageName string
	Tag       string
	Artifact  *v1alpha2.Artifact // The artifact used in the build.
}
```

It should really only need

```golang
type Build struct {
   Tag name.Tag // from go-containerregistry
}
```

We might need a function to match it back up to the corresponding artifact, but I don't think that has to live on the struct itself.

**Comment by dgageot** [comment]
The `Artifact` is currently needed by the `kubectl` deployer because it needs the artifact workspace and Dockerfile to generate the k8s manifest.

This makes me think that this feature fails with an artifact that's not of Docker type.
I wonder how useful is the feature.

**Comment by r2d4** [comment]
I'm fine getting rid of it. I'm not sure skaffold is the right place for a generation feature like that anyways
