### ISSUE TITLE
[FR] generate helm values.yaml file with `build`

### ISSUE THREAD

**Issue by rimusz** [GoogleContainerTools/skaffold#627]
`skaffold build` command should generate the new `override-values.yaml` file which only has the docker `repository` and `tag:...` and then it is up to user to merge it with the app’s code after successful deploy, and when the release is done use `helm upgrade ... -f override-values.yaml`?

the whole process just needs to be well documented on skaffold repo and we get `GitOps`.

user probably have another system that can orchestrate the git webhooks and triggers, and then the commits/merge

**Comment by balopat** [comment]
This is something similar to what we are tracking as part of #2161.
I wonder if rendering the actual manifests would be satisfactory?

**Comment by nkubala** [comment]
since we have `skaffold render` and are close to having support for helm, I'm going to close this issue. if there are other use cases that aren't supported by rendering templated manifests, please give some detail about them here!

**Comment by aantn** [comment]
@nkubala I would like to re-open this.

I maintain an application which is deployed using Helm. As part of my CI/CD pipeline I'd like to test installing that application with Helm and enabling various features in the values.yaml. To do so, the output of Skaffold render (k8s manifests) is insufficient. I need to render the values.yaml file.
