### ISSUE TITLE
kubectl should use `--dry-run=server` 

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6273]
This issue proposes to:
1. switch the `kubectl` deployer to use `--dry-run=server` rather than the current default of `--dry-run=client`
2. expose this dry-run setting as a flag in the `skaffold.yaml`.  

`--dry-run=server` is very useful for clusters like GKE Autopilot that perform additional validation, including erroring on settings that violate its constraints.

In case this causes deployments to fail that worked fine with `--dry-run=client`, we should provide an environment variable to restore the old behaviour like `SKAFFOLD_KUBECTL_DRY_RUN` that can be set to `client`, `server`, or `none`.

Relevant: #4094

**Comment by briandealwis** [comment]
A few thoughts:
  - `--dry-run=server` may fail if the user has insufficient permissions — but an `apply` would fail then too
  - should have an option, probably in the global config, to default dry-run to client-only.

**Comment by MarlonGamez** [comment]
@briandealwis so do you think we should change the default for this? Or should we first just introduce a change to have it be configurable before possibly changing the default?

**Comment by briandealwis** [comment]
I think we should change the default so that users can benefit from the warnings returned by the Kubernetes API — @ahmetb [shows a nice example](https://twitter.com/ahmetb/status/1437816662212763657).

**Comment by briandealwis** [comment]
Closing: we already get validation reports from the `kubectl apply`.
