### ISSUE TITLE
support --wait on helm operations

### ISSUE THREAD

**Issue by booninite** [GoogleContainerTools/skaffold#631]
This is a feature request

### Expected behavior

After deploying via `skaffold run`, I should be able to issue `helm test` immediately without implementing my own watching utility.

### Actual behavior

Because I can't pass `--wait` along to the Helm operations that Skaffold provides, my readiness probes have no way to inform me when its safe to run `helm test`.

### Information

This could be implemented as a config field (`wait: true`?) or a CLI flag (`skaffold run --wait`? -- would also need to wait for non-helm deployments in that case)

**Comment by r2d4** [comment]
ref #176

**Comment by booninite** [comment]
closed via #633
