### ISSUE TITLE
`dev --port-forward` with user-defined ports may result in services being allocated random ports

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6312]
Seen in Skaffold HEAD, but present back to v1.24.0.

@dhodun has a multi-module app with two services configured by user-defined port-forwards (UDPFs) with specific local ports.  The UDPFs look like:
```
portForward:
- resourceType: service
  resourceName: rules-engine
  port: 80
  localPort: 8887
```

He reported an odd situation where `skaffold dev --port-forward` with would frequently set one of the services that should be bound to port 8887 was sometimes being bound to port 4503.  As I write this, I realized there have been some other user reports of this nature.

In digging into the issue, the problem is that `skaffold dev --port-forward` creates multiple forwarders to handle the various types of forwarders (services, user ports, pods, etc): https://github.com/GoogleContainerTools/skaffold/blob/55f5860137ef74c8e7d935835a2dd59b98a6f63d/pkg/skaffold/kubernetes/portforward/forwarder_manager.go#L63-L91
and the [UDPF and services forwarders are different instances of  `ResourceForwarder`](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/kubernetes/portforward/resource_forwarder.go#L50-L65).  The services forwarders retrieves the list of services and spoofs up a port-forwarding resource but with localPort=0 so that a random'ish port is allocated.

The entries-manager attempts to coalesce port-forward requests by mapping requests for the same resource+port to the same entry.  So a UDPF and a services forward for the same service will map to the same service.

Each of these forwarders is started in turn, but the `ResourceForwarder`s actually establish the individual port-forwards in a goroutine:
https://github.com/GoogleContainerTools/skaffold/blob/55f5860137ef74c8e7d935835a2dd59b98a6f63d/pkg/skaffold/kubernetes/portforward/resource_forwarder.go#L128-L134

The underlying forwarding mechanism, the `KubectlForwarder`, uses a goroutine to launch `kubectl port-forward` and then blocks on a channel to retrieve the launch result:
https://github.com/GoogleContainerTools/skaffold/blob/55f5860137ef74c8e7d935835a2dd59b98a6f63d/pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go#L81-L85

So it's possible that the UDPF-forwards (with a specific local port) become blocked while the services-forwards (with local-port = 0) go forward.    And if the services-forwards happens first, then the real entry will have a random'ish port allocated.

(This is rather complicated and my explanation is rather poor.)

**Comment by briandealwis** [comment]
I think a solution is to remove the use of the goroutine in the ResourceForwarder:
https://github.com/GoogleContainerTools/skaffold/blob/55f5860137ef74c8e7d935835a2dd59b98a6f63d/pkg/skaffold/kubernetes/portforward/resource_forwarder.go#L128-L134

**Comment by dhodun** [comment]
Ya, I was seeing it happen every time. When i just ran the service in question with `-m service-name` the port was allocated as expected, so it wasn't a port contention issue.

when i drop `--port-forward` from the command, it works just fine.
