### ISSUE TITLE
Implement `skaffold delete` for Docker deployer

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#6314]
If the skaffold process is forced to quit without time to cleanup, it will leave behind containers and sometimes a network in the local docker daemon. In this case `skaffold delete` should be able to sift through the local daemon and find containers and networks it created, and remove them.

**Comment by MarlonGamez** [comment]
@tejal29 do we currently have plans for docker deployer? This seems like a pretty important feature, but I'm not sure if we'd get the chance to prioritize it
