### ISSUE TITLE
[Doc site] Schema reference for latest config version not loading

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6347]
https://skaffold.dev/docs/references/yaml/?version=v2beta20 not loading the schema for the latest config version

![image](https://user-images.githubusercontent.com/39389231/127999567-5b3fa6c6-94a2-4ae7-9f99-38aea040537a.png)

**Comment by davecardwell** [comment]
There is a JavaScript error when processing the v2beta20 schema fetched from https://skaffold.dev/schemas/v2beta20.json:
> Uncaught (in promise) TypeError: Cannot read property 'properties' of undefined

The problem occurs at line 99 below when `refName` evaluates to `"ContainerHook"` in this code:
https://github.com/GoogleContainerTools/skaffold/blob/1e3da21af7add15c2a36e707a27b84a2cf3787b3/docs/content/en/docs/references/yaml/main.js#L95-L99

The corresponding definition for `ContainerHook` does not exist in the schema for `SyncHookItem`:
https://github.com/GoogleContainerTools/skaffold/blob/1e3da21af7add15c2a36e707a27b84a2cf3787b3/docs/content/en/schemas/v2beta20.json#L3134

Should it be `NamedContainerHook` as it is for `DeployHookItem`?

**Comment by gsquared94** [comment]
fixed in #6372
