### ISSUE TITLE
Upgrade CI to Go 1.16

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6348]
### Expected behavior
`os.WriteFile` should be supported.

### Actual behavior
Travis CI reports  `undefined: os.WriteFile`

### Information
Travis CI runs on Go1.15 and cannot support some Go1.16  features like `os.WriteFile`.
This disallow us to develop on Go1.16 and misses some cool features https://golang.org/doc/go1.16

**Comment by aaron-prindle** [comment]
We have officially migrated off of Travis to GH Actions.  It might make sense to close/rename this issue

**Comment by yuwenma** [comment]
THanks Aaron.

**Comment by MarlonGamez** [comment]
closing this since we've moved our release process and are using go `1.17+`
