### ISSUE TITLE
Support --target for Docker artifacts

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#635]
This makes it possible to define multiple artifacts from the same Dockerfile

**Comment by bryanlarsen** [comment]
There's a workaround for --target in #890.

**Comment by thomas-riccardi** [comment]
@dlorenc As it is only a workaround, shouldn't this issue be kept open?

**Comment by leahneukirchen** [comment]
It would be very nice if this was documented.
