### ISSUE TITLE
Sync pre-hooks and post hooks with Event API v2

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6351]
Please investigate pre-hooks and post-sync hooks with V2 skaffold logging api. 
Run it in intellij or VSC latest build.

**Comment by gsquared94** [comment]
Ran `VSCode Cloud Code v1.14.0-insiders.10` against `examples/lifecycle-hooks` project. The pre-build and post-build hook loglines show up in the corresponding artifact build node, similarly for deploy. The container hook loglines show up in the corresponding container node. 🎉

However, one issue I found is that `sync` doesn't have any node in the log view. When a sync-only devloop occurs the view only has the container node:
![image](https://user-images.githubusercontent.com/39389231/132652510-86417f96-c3c1-4c03-991f-21f92289e912.png)
So `pre-sync` and `post-sync` hooks loglines are missing (https://github.com/GoogleContainerTools/skaffold/issues/6579)
