### ISSUE TITLE
Add command/functionality to skaffold to verify whether tests will run for a given skaffold.yaml

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6355]
For projects that use skaffold as a dependency it can be helpful to understand what tests a skaffold.yaml have defined and are applicable for a given profile,etc.  This bug tracks extending `skaffold inspect` command to inspect the complete skaffold config (aggregated from all relevant `skaffold.yaml` files) to verify if a test will occur.

**Comment by aaron-prindle** [comment]
Adding @maggieneterval @ekupershlak @plumpy for partnership tracking

**Comment by gsquared94** [comment]
IMO could be added to [go/mutate-skaffold-configs](http://go/mutate-skaffold-configs)
