### ISSUE TITLE
incorrect json schema generation

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6371]
### Expected behavior
Any new structs added to `config.go` will create corresponding correct json schema definition on running `make generate-schemas`.

### Actual behavior
If struct `Foo` is used in two structs, as:

```go
type Bar1 struct {
    Foo `yaml:",inline"`
}

type Bar2 struct {
    Foo *Foo `yaml:"foo,omitempty"`
}
```
then the generated json doesn't include the definition for `Foo`.

This caused #6363, #6347

**Comment by verbanicm** [comment]
@gsquared94 You can specify skipTrim to prevent the parser from removing the Foo ref in the output

```golang
type Bar1 struct {
    Foo `yaml:",inline" yamltags:"skipTrim"`
}
```

**Comment by gsquared94** [comment]
> @gsquared94 You can specify skipTrim to prevent the parser from removing the Foo ref in the output
> 
> ```go
> type Bar1 struct {
>     Foo `yaml:",inline" yamltags:"skipTrim"`
> }
> ```

awesome, thanks for the find.
