### ISSUE TITLE
Modify the skaffold v2 render prompt behavior 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6373]
Per offline discussion with @briandealwis , this is what we believe the appropriate behavior when prompting a message in render.
- if the hydration dir exists and is empty => no prompt
- if the hydration dir exists and there is content but no Kptfile => exit: this doesn't look right
- if the hydration dir exists and there is content and Kptfile => prompt to remove ?

**Comment by yuwenma** [comment]
cc @briandealwis

**Comment by tejal29** [comment]
Render prompt will not feasible in cloud deploy scenario as well as cloud code.  Closing this for now.

**Comment by tejal29** [comment]
closing this as dupe of #7608
