### ISSUE TITLE
Skaffold /v2/events API returning empty log lines

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#6377]
Skaffold built from: 5ceca632294e4218062642eb81c242d1ec24b3ad
Cloud Code built from: https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/commit/82760372e99229d6558b9cc82fe5f8a5cb7e4c19

Using the v2 logging UI in Cloud Code I run the `go-guestbook` sample app. When I hit stop, I see some strange application log output:

![image](https://user-images.githubusercontent.com/79073/128538178-8313f3d9-ffdc-44ef-933b-54a41a4406eb.png)

^ notice the `[init-db-ready] [init-db-ready] [backend] [frontend] [backend]` line

![image](https://user-images.githubusercontent.com/79073/128538288-cecf3e95-ccf8-4b26-be5e-dd546cb6d51f.png)

^ notice the `[init-db-ready] [backend]` line

I looked through the log of events Cloud Code is receiving from Skaffold: https://paste.googleplex.com/5443215772614656

In here I'm seeing `ApplicationLogEvent`s like:

```
timestamp {
  seconds: 1628264879
  nanos: 178155000
}
applicationLogEvent {
  containerName: "frontend"
  podName: "go-guestbook-frontend-68755fcf54-2l9kl"
  prefix: "\033[92m[frontend]\033[0m "
  richFormattedMessage: "\033[92m[frontend]\033[0m "
  ```

or 

```
timestamp {
  seconds: 1628264879
  nanos: 178612000
}
applicationLogEvent {
  containerName: "backend"
  podName: "go-guestbook-backend-64c54f4c68-fg7sj"
  prefix: "\033[91m[backend]\033[0m "
  richFormattedMessage: "\033[91m[backend]\033[0m "
}
```

I think these are the cause of these empty log prefix messages. Cloud Code IJ prints the `richFormattedMessage` values from here. Can we stop emitting these kinds of empty messages?

**Comment by gsquared94** [comment]
this should be fixed in https://github.com/GoogleContainerTools/skaffold/pull/6376/files#diff-6cb06d2260392a314577c4433e16bc4b77b3b9f70af7831de7b1c5874524a337R42-R44 already.

**Comment by etanshaul** [comment]
> this should be fixed in https://github.com/GoogleContainerTools/skaffold/pull/6376/files#diff-6cb06d2260392a314577c4433e16bc4b77b3b9f70af7831de7b1c5874524a337R42-R44 already. 

Will confirm this today.

**Comment by etanshaul** [comment]
@gsquared94 this does look fixed now! thank you. Closing the issue for now.
