### ISSUE TITLE
Previous iteration application logs being emitted

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleContainerTools/skaffold#6378]
Skaffold built from: 5ceca63
Cloud Code built from: GoogleCloudPlatform/cloud-code-intellij-internal@8276037

(This might be working as intended, and not a bug)

![image](https://user-images.githubusercontent.com/79073/128540092-6b58db6f-2e97-42c9-8c55-80ead7ead0c3.png)

The above screenshot shows the second iteration of developing the go-guestbook sample app. Notice that in the `Stream application logs` tree node, there are two `go-guestbook-backend-*` nodes. This app only has 1 backend pod and 1 frontend pod, so we'd expect there to only be 1 backend application log node here.

What I think is happening is that the previous iteration's backend logs are still being received in addition to the current iteration's.

**Comment by etanshaul** [comment]
this looks very similar, or the same underlying issue, as this comment: https://github.com/GoogleContainerTools/skaffold/pull/6370#issuecomment-894335725

**Comment by tejal29** [comment]
This can be closed now.
