### ISSUE TITLE
[v2] Add flags to pass in `Inventory` in `skaffold apply`. 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6389]
### Information

In v2, add the following flags in `skaffold render`:

--default_kpt_inventory_namespace: namespace value for the Kpt inventory
--default_kpt_inventory_name: name value for the Kpt inventory 
--default_kpt_inventory_id: inventoryId value for the Kpt inventory

These flags are needed by cloud deploy and shall be hidden from --help

**Comment by tejal29** [comment]
Talk to @yuwenma about this.
