### ISSUE TITLE
Deployment hooks when Helm is used

### ISSUE THREAD

**Issue by Ambrase** [GoogleContainerTools/skaffold#6420]
Hi

We would like you use pre-deploy and after-deploy hooks with [the deployment option Helm](https://skaffold.dev/docs/references/yaml/?version=v2beta21#deploy), but you added them only to kubectl.
Do you plan to add them to the Helm deploy section as well?

@gsquared94 

Thanks

**Comment by gsquared94** [comment]
yes we do.
