### ISSUE TITLE
Skaffold should provide a way to list artifacts across modules and profiles

### ISSUE THREAD

**Issue by peterlin741** [GoogleContainerTools/skaffold#6457]
As part of the effort to support Artifact Registry, in addition to GCR:

- We want to handle the auto-creation of a GCR/AR repo when deploying to GKE, only if the artifacts do not already have a repository
- Add a `skaffold inspect artifacts list` to list out the artifacts images, which can be read by Cloud Code to see if there are any without a repository portion (e.g., java-guestbook-frontend vs `gcr.io/xxx/my-image`) 
- Used to decide whether an AR/GCR repository should be automatically created
- If the artifacts already have a repository, we want to return the url, so that we can use that instead

**Comment by briandealwis** [comment]
cc: @ivanporty for the artifacts table

**Comment by gsquared94** [comment]
@peterlin741 can you please help us understand how urgent this workitem is for Cloud Code?

**Comment by peterlin741** [comment]
closing for now, since the design for AR support has changed since the creation of this issue, Will reopen if necessary

**Comment by briandealwis** [comment]
`skaffold build --dry-run -q` outputs the list of artifacts to be built and the resulting tagged images.
