### ISSUE TITLE
[Docs fixit] Rename `Skaffold API` to `Skaffold gRPC and HTTP service`

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6479]
The side-bar and pages titled `Skaffold API` can get confused with the `skaffold.yaml API`. We should consider explicitly renaming all occurrences of `Skaffold API` to `Skaffold gRPC and HTTP service` or something similar.
Also change the links from `<link>/../api` to `<link>/../server` or `<link>/../service` 

https://skaffold.dev/docs/design/api/
https://skaffold.dev/docs/references/api/

**Comment by gsquared94** [comment]
> The "Skaffold API" term IMO more clearly explains the feature than "Skaffold [...] service". 

for tilt.dev, "Tiltfile API" is used for the config file schema link. They don't seem to have any Skaffold API equivalent atm.
![image](https://user-images.githubusercontent.com/39389231/131323606-f66997af-2232-45e7-8ca8-9d3201cf174c.png)

---
In Skaffold the link for the config file schema is called "Skaffold Pipeline":
https://skaffold.dev/docs/design/
![image](https://user-images.githubusercontent.com/39389231/131323545-a206b201-5b20-4e1e-bbef-03b0f76669c1.png)

No data to support this, but I'd click `Skaffold API` first before the other links hoping to get the config file schema details which is obviously much more important (and should be more easily discoverable, #6484) than the API server.

wdyt @kourtneyshort ?

**Comment by kourtneyshort** [comment]
If the Skaffold Meta API would be clearer to customers, that sounds good to me. In https://skaffold.dev/docs/references/api/, you link to the other page but I don't think the sentence makes clear that the link is taking them to a different thing. "For a detailed description of the Skaffold API.

So on https://skaffold.dev/docs/references/api/, I'd suggest:

Naming the page something more informative than API
Rephrasing the description to make clear when they've come to the right place and when they should leave e.g.

This section describes the <page name> that lets you retreive information about the state of the process and exert fine-grained control over its execution. If you're looking for the config file schema, see the Skaffold API (or whatever the new page title is.

You could also consider adding something here https://skaffold.dev/docs/design/api/ in case someone ends up there in error and should go to the other API

**Comment by ahmetb** [comment]
> Rephrasing the description to make clear when they've come to the right place and when they should leave e.g.

Agreed, I added a similar warning #6503.  Happy to take on to fix it that way. 

I don't think we need to follow Tilt's way necessarily here. In their case, they have the main interaction method (config file) in the navbar (which you suggest at #6484). For us, the API should be something less discoverable, hence doesn't need that disambiguation IMO.
