### ISSUE TITLE
[Docs fixit] [technical writers review] Multiple links to the same content

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6481]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/39389231/130270402-a8cb5adc-648b-4d57-8acb-f2356c400406.png">

https://skaffold.dev/docs/tutorials/

This behavior is found on several pages.

**Comment by briandealwis** [comment]
The `docsy` theme started auto-generating these subpage links.  They're always added at the bottom of the page though, but maybe that's configurable?  They can be turned off, but maybe we should just take advantage of them and remove our hand-rolled lists.
