### ISSUE TITLE
[Docs fixit] [technical writers review] [HaTS feedback] Pages should link to relevant github repo `examples`

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6488]
The [`examples`](https://github.com/GoogleContainerTools/skaffold/tree/main/examples) directory is a treasure trove of many direct usage examples for various concepts explained in the docs. We should be able to link the relevant examples directly from a documentation page.
The right side pane for every page could have an `examples` section similar to the `Applicable/Not applicable` section.
![image](https://user-images.githubusercontent.com/39389231/130473876-fdf5ed1e-8a94-47e1-b696-9b88c8f3d926.png)

**Comment by maggieneterval** [comment]
I am working on this.
