### ISSUE TITLE
[feat] Ability to load secrets from environment variables

### ISSUE THREAD

**Issue by abhishiekgowtham** [GoogleContainerTools/skaffold#6489]
Hey! Since docker v20.10.x there's a way to load docker secret using env vars when buildkit is enabled. Can it supported by skaffold? I can't find any reference in the docs, but i found [this](https://skaffold.dev/docs/references/yaml/#build-artifacts-docker-secret) allowing to read secrets from a file.

**Comment by ahmetb** [comment]
@abhishiekgowtham this seems doable if we can add `env:` field and make it mutually exclusive with `src:` in the linked schema section.

@alex-dixon I doubt this help with variable expansion in `src:` field but you could do `export MY_ENV="$(cat $HOME/file)"` while running skaffold (with a tool like direnv)?

**Comment by abhishiekgowtham** [comment]
Thanks for working/adding the feature @ahmetb! 👍

**Comment by ahmetb** [comment]
@abhishiekgowtham no problem! have you had a chance to build from the repo and try it out?
