### ISSUE TITLE
skaffold  logtail not support unique color  when concurrency != 1 for more than one microservice

### ISSUE THREAD

**Issue by beastpu** [GoogleContainerTools/skaffold#6521]
skaffold  logtail not support unique color  when concurrency set to != 1 for more than one microservice

**Comment by gsquared94** [comment]
I ran the `microservices` example with concurrency 1 and got unique color pod name prefixes
![image](https://user-images.githubusercontent.com/39389231/131358828-72b7746a-31bd-4b6e-bfdf-d0f6e3899ead.png)

Can you share a small example that reproduces the issue that you're seeing?

**Comment by beastpu** [comment]
sorry~   the color problem will appear when  concurrency set to 0 not 1

**Comment by gsquared94** [comment]
tested with `examples/microservices`. We lose all colors even for deployers, loggers and port-forward messages if the artifacts are built with concurrency != 1. 
@MarlonGamez I think this could be a regression from the recent `skaffoldWriter` and `colorableWriter` changes.

**Comment by akostic-kostile** [comment]
+1, it's very difficult to follow logs on several services with everything being same color. As a small addition to this bug report I'd like to say that, even tho I `skaffold dev` with concurrency=0, in my case this is an intermittent bug, sometimes I get colored output, sometimes not. But in fairness colored outputs seems much more rare than colorless.

**Comment by GeraldXv** [comment]
+1
