### ISSUE TITLE
kubectl apply prune support

### ISSUE THREAD

**Issue by mxey** [GoogleContainerTools/skaffold#654]
David Gageot on Slack asked me to file this is as a feature request.

I'd like Skaffold to support the prune feature of kubectl, in both the kubectl and kustomize deployer.

**Comment by r2d4** [comment]
Always on won't let multiple users use skaffold on the same cluster (unless we prune on a user-specific label)

**Comment by mxey** [comment]
@dlorenc I think it should be a flag, because not everybody might want it, and having it on by default could be a bad surprise.

@r2d4 it definitely would have to be a user-specified label selector, so people could use it with multiple Skaffold-ed applications. It should be a label selector, not just a single label. For example, I might have a combination of `app=myapp,environment=featurebranchXYZ`. 

Maybe just allow for arbitrary options to kubectl? Would also be useful for `--force`.

**Comment by nkubala** [comment]
This should be fixed through https://github.com/GoogleContainerTools/skaffold/pull/807
