### ISSUE TITLE
Label schema

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#656]
ref #644

What labels do we want to tag our deployed objects with?

- "skaffold options" (cleanup, notification, profiles, custom tag, namespace)
-  builder name
-  deployer name
-  tagger name
-  VCS metadata (git commit, git tree state)
-  build time
-  deploy time
-  skaffold mode (dev/run)
-  docker build args

Additionally, should we prefix the labels or not? (something like `skaffold.dev/builder.name`)

Some label guidance for docker images
http://label-schema.org/rc1/

And for kubernetes applications
https://github.com/kubernetes/website/pull/8703

**Comment by dlorenc** [comment]
+1 on prefixing. The labels themselves should be pretty short, if we want to add more info like (timing, arguments, etc. we should use annotations).

**Comment by jonjohnsonjr** [comment]
It would be nice if we can do this in a way that is compatible with:
https://github.com/opencontainers/image-spec/blob/master/annotations.md

**Comment by nkubala** [comment]
closing this since we have labeling infrastructure set up.
