### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by abitrolly** [GoogleContainerTools/skaffold#6568]
Right now `skaffold` requires to be integrated into the project rather than scaffolding it. This requires contributors to learn yet another file format.

It would be quite soothing for the start if `skaffold` could inherit some kind of herokuish behavior, where the project files are left intact, and it's the buildpacks tools that mature, rather than project DevOps (who are not always available if you're FOSS).

### Expected behavior

Run `skaffold --auto dev` or `skaffold --auto build` to autodetect available runtime environment (Docker, k8s, ..), relevant build files (Dockerfile, ...), and run the logical set of operations that people expect.

### Actual behavior

Go read  the docs, use `skaffold init`, setup cluster (not sure - still reading the docs).

### Information

- Operating system: Fedora 34
- Installed via: Homebrew

**Comment by gsquared94** [comment]
Skaffold can attempt the `init` flow with heuristics and best-effort guesses instead of prompting the user. You could run:
```
skaffold dev -f /tmp/skaffold-transient.yaml --auto-create-config=true --assume-yes=true
```

This however does create the ` /tmp/skaffold-transient.yaml` file, and you would have to clean it up manually every run.
