### ISSUE TITLE
Sync log lines missing from new log view for Cloud Code

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6579]
### Expected behavior
New log view has a `Sync` node when `sync` devloop occurs so that it shows `pre-sync` and `post-sync` log messages.
### Actual behavior
New log view only shows the container node when a sync-only devloop occurs. Thus log messages from the sync hooks go missing.
![image](https://user-images.githubusercontent.com/39389231/132652510-86417f96-c3c1-4c03-991f-21f92289e912.png)

### Information

- Skaffold version: built from main
- Operating system: Darwin

### Steps to reproduce the behavior

1. Use `VSCode Cloud Code v1.14.0-insiders.10` against the `examples/lifecycle-hooks` project.
2. Run `Run on Kubernetes`
3. Make a change to `hello.txt` file
4. Observe the new log view, it does not have any loglines specific to `pre-sync` and `post-sync` hooks. It does have the container log messages that show the effect of the hooks having run.

**Comment by gsquared94** [comment]
cc @etanshaul @vincentjocodes

**Comment by gsquared94** [comment]
cc @etanshaul @vincentjocodes

**Comment by tejal29** [comment]
Is this an issue on skaffold side or needs investigation?

**Comment by gsquared94** [comment]
> Is this an issue on skaffold side or needs investigation?

It's an issue on Skaffold side.
