### ISSUE TITLE
Reset dependency Git repos instead of erroring.

### ISSUE THREAD

**Issue by glennpratt** [GoogleContainerTools/skaffold#6598]
### Expected behavior

Local cached repositories are reset automatically even with uncommitted changes. Failed builds often leave untracked files that aren't relevant and should just be removed or reset.

This option could be called `sync: "force". 

If we're paranoid, we could add a stash option.

### Actual behavior

```
`parsing skaffold config: error parsing skaffold configuration file: caching remote dependency git@github.com:org/repo.git: failed to clone repo git@github.com:org/repo.git: there are uncommitted changes in the target directory /Users/foobar/.skaffold/repos/Aec4Xk44O0h606qlC2brihRnueRXDVtD; either set the repository `sync` property to false in the skaffold config, or manually commit and sync changes to remote, or revert the local changes
```

### Information

- Skaffold version: v1.31.0
- Operating system: macOS 11.5.2 (20G95)
- Installed via:  Homebrew
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

1. Install a skaffold config with dependencies.
2. Find the cached repo and add untracked changes.
3. Try to install.

**Comment by nkubala** [comment]
thanks for filing @glennpratt, agreed this is an annoying UX when something goes wrong in the build. as long as we don't change the defaults I don't see any harm in adding an option to force a reset of the cache. would you be interested in taking a stab at adding this?

**Comment by tomas-mota** [comment]
I can give this a shot. Any examples of an application/framework that generates such files on build error @glennpratt ?

**Comment by tomas-mota** [comment]
Can I get some feedback on this? Adding a new field will change the field to be a string instead of boolean as it is, so I am a bit confused as to whether this solution is viable.

**Comment by glennpratt** [comment]
From my perspective, I'd absolutely be OK with forcing a reset just on true. You could use `git stash` to do it and document that, so users have a path to recover if they made some valuable changes to the repo, however unlikely that might be.

I'm not a maintainer though, just a user.

**Comment by tomas-mota** [comment]
Yeah, that also seems to me to be the intended behaviour of the flag. If it is safe for us to assume that the user is not going to make deliberate modifications to the cached repo directly, then we can skip the caching (good idea though!)
