### ISSUE TITLE
Kokoro builds are failing as tests are taking too long

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6601]
We're seeing frequent test failures on Kokoro as the tests are exceeding 45m:

```
panic: test timed out after 45m0s
```

For the short-term: increase the test timeout to 50m.  But we should investigate whether we can set up parallelize the tests as we do with Github Actions, and also determine which tests seem to be taking longer.  It might be worth investigating using [gopogh](https://github.com/medyagh/gopogh) to help visualize the test runs.

**Comment by briandealwis** [comment]
Bumped to 50m in #6590.

**Comment by aaron-prindle** [comment]
Tests are regularly running under 30 mins now with @ericzzzzzzz PR here https://github.com/GoogleContainerTools/skaffold/pull/8106

Closing (fixed)
