### ISSUE TITLE
Support declarative mechanism for deploying to Cloud Run

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6629]
Relates to #6686
Ensure that Skaffold supports deploying Cloud Run services.

- [x] Add image replacement for identified KCC group 
- [ ] Add status check for cloud run KCC

**Comment by briandealwis** [comment]
cc @ekupershlak

**Comment by tejal29** [comment]
Reopening as @briandealwis mentioned we might need to follow up.

**Comment by tejal29** [comment]
We opened #6709 for health check for KCC resource. closing this one.
