### ISSUE TITLE
skaffold dev logs will not print in color when a local build is executed

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#6638]
I'm using the skaffold dev command to run a local pipeline of build and deploy to docker-desktop.
I use a local build with no push method.
When I have cached images and the build is skipped ("Found Locally") skaffold will print all container logs in colors.
However, if I have changed any local development files and a build has to be executed ("Not found. Building"), skaffold will stop printing output with colors. 

### Expected behavior
skaffold will print with colors
### Actual behavior
skaffold doesn't print with colors when a local build is done
### Information

- Skaffold version: v1.32.0
- Operating system: macOS
- Installed via: Homebrew

**Comment by briandealwis** [comment]
Hmm, I'm unable to reproduce.  Could you please

1. Try reproducing using one of the Skaffold examples, like the [`getting-started`](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started) example?
2. Try running Skaffold with `-vdebug` and include the output here?

**Comment by tejal29** [comment]
@giladsh1 Please provide more details. 
Thank you.

**Comment by MarlonGamez** [comment]
hey @giladsh1 , I'm going to close this for now since we haven't been able to reproduce the issue and haven't heard from you in a while, but feel free to reopen with more information if you get the chance to!
