### ISSUE TITLE
'skaffold dev' gives an error 'container is waiting to start...cant be pulled'

### ISSUE THREAD

**Issue by pinakinc** [GoogleContainerTools/skaffold#6668]
### The output from the small Typescript code should get displayed

Skaffold

- Skaffold version: V1.32.0
- Operating system: Windows 10
- Installed via: **Google Cloud SDK** 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: pinakinc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/.ts'
            dest: .
  
index.TS
---------

const express=require('express');
import {json} from 'body-parser';
const app=express();

const port = process.env.PORT || 3100;
app.use(json());
app.listen(port, ()=>{
    console.log('Listening on port 3100',port);
});
-------------------------------------------------------------------------

Docker File

FROM node:alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
CMD ["npm","start"]

auth-depl.yaml

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth
  template: 
    metadata:
      labels:
        app: auth 
    spec:
      containers:
        - name: auth
          image: pinakinc/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports: 
    - name: auth
      protocol: TCP
      port: 3100
      targetPort: 3100

**Comment by gsquared94** [comment]
if you want to iterate on this locally you'll have to setup a cluster like `minikube` or `kind`. Otherwise if it is a remote kubernetes cluster then you'll need to push the built image to a container registry, and as such `build.local.push` property needs to be true.

**Comment by briandealwis** [comment]
I wonder if we should make it an error to have `build.local.push=false` with a non-local cluster.

**Comment by tejal29** [comment]
The team discussed, adding a suggestion for errors when we see deployments errors due to "image can't be pulled" and `build.local.push=false` is set to try removing the config.

**Comment by nkubala** [comment]
one of the issues here is also that skaffold isn't actually very good at knowing whether a cluster is remote or local, so we make assumptions based on primitive heuristics that may or may not be accurate. it might be useful for us to expose an optional flag for users to explicitly declare whether their cluster is remote or not - we could recommend the use of this flag as an alternative to removing the `build.local.push` flag

**Comment by aaron-prindle** [comment]
Sorry for the delay here.  @ngfgrant can you post the log output of the erroring skaffold command with the `-v debug` flag? (eg: `skaffold dev -v debug`).  It might be the case that your built images are in the wrong docker env (minikube has it's own docker daemon), looking at the logs will help us identify the issue.  Thanks

**Comment by bestofman** [comment]
I have similar issue posted here: https://github.com/GoogleContainerTools/skaffold/issues/8235
But couldn't find a solution for that untill now!

**Comment by bestofman** [comment]
> if you want to iterate on this locally you'll have to setup a cluster like `minikube` or `kind`. Otherwise if it is a remote kubernetes cluster then you'll need to push the built image to a container registry, and as such `build.local.push` property needs to be true.

What about using `kubeadm`? I am on Ubuntu 22.04 and have similar issue posted here https://github.com/GoogleContainerTools/skaffold/issues/8235

**Comment by gsquared94** [comment]
Closing this issue due to no recent updates, replied to issue #8235 directly.
