### ISSUE TITLE
Update `skaffold init --artifact` API to allow manifest generation non-interactively

### ISSUE THREAD

**Issue by MarlonGamez** [GoogleContainerTools/skaffold#6681]
### Information

- [x] make necessary changes to allow for manifest generation
- [ ] document the changes for reference

**Comment by briandealwis** [comment]
Can I suggest something other `--artifact` since this will be for non-artifacts (i.e., containers that *aren't* listed in the `skaffold.yaml`)

**Comment by tejal29** [comment]
This issue is cancelled for now.
