### ISSUE TITLE
Add integration test - `skaffold apply` with health checks 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6724]
Add integration tests for cloud deploy `skaffold apply` with health checks in the main branch.

**Comment by MarlonGamez** [comment]
@tejal29 we have tests for `skaffold apply` at https://github.com/GoogleContainerTools/skaffold/blob/main/integration/apply_test.go

**Comment by MarlonGamez** [comment]
Going to close this unless there is other specific functionality that we want to add integration tests for
