### ISSUE TITLE
docs: /v2/events does not appear in API docs

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#6740]
I am looking at these pages to find more info on `/v2/events`:

- https://skaffold.dev/docs/references/api/swagger/
- https://skaffold.dev/docs/references/api/grpc/#v1skaffoldproto

but there doesn't seem to be any relevant endpoints listed.

**Comment by MarlonGamez** [comment]
Thanks for pointing this out, I think it's about time that we include this page, as we're currently generating and not including it as we wanted to have all things finalized and implemented. I think we're at that stage now and can go ahead with this

**Comment by aaron-prindle** [comment]
Closing, fixed via - https://github.com/GoogleContainerTools/skaffold/pull/7539
