### ISSUE TITLE
Update docs to indicate that healthcheck is performed for `skaffold apply`

### ISSUE THREAD

**Issue by dorbin** [GoogleContainerTools/skaffold#6741]
### Expected behavior
Documentation should indicate that `healthcheck` is performed for `skaffold apply`.

### Actual behavior
[Doc](https://skaffold.dev/docs/workflows/ci-cd/#waiting-for-skaffold-deployments) references `healthcheck` as if only included in processing of `skaffold deploy`.

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by nkubala** [comment]
thanks for pointing this out @dorbin, our documentation is in constant need of love 🙂
