### ISSUE TITLE
Do not use KRM setters in rendering 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6784]
### Information

- Skaffold version: v2.0.0 

Do no use setters KRM functions. this is not compatible with our general non-templating hydration design. 

https://github.com/GoogleContainerTools/skaffold/blob/v2/pkg/skaffold/render/transform/transform.go#L40

https://github.com/GoogleContainerTools/skaffold/blob/v2/pkg/skaffold/render/transform/transform.go#L44

**Comment by yuwenma** [comment]
The rationale is explained here https://github.com/GoogleContainerTools/kpt/issues/3131

**Comment by ericzzzzzzz** [comment]
After discussion, we decided to keep the setters in skaffold to support parameterization.  So closing this out.
