### ISSUE TITLE
Skaffold - Openshift

### ISSUE THREAD

**Issue by jvaidyan** [GoogleContainerTools/skaffold#6789]
Does Skaffold work with Openshift dpeloyment?
In my use case Deployment yaml and Service yaml stays the same. But, not sure how will I get a route created in case of Openshift.

**Comment by briandealwis** [comment]
At its essence, Skaffold is shim around a container-build script and `kubectl apply` (or `kustomize` or `helm`).  As long as you're deploying Kubernetes resources using `kubectl`, then things should Just Work™.

(There is one caveat: Skaffold only rewrites image references in the standard workload objects like deployments, and a preconfigured list of common Kubernetes custom resources #4081.)
