### ISSUE TITLE
Update skaffold CI to use go1.16

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#6790]
Currently skaffold uses go1.15 in CI and for its release builds.  go1.16 has new features/functionality that current PRs require and are blocked on including:
- https://github.com/GoogleContainerTools/skaffold/pull/6056 - `need to update doublestar to get its new ValidatePattern which requires updating to Go 1.16`
- https://github.com/GoogleContainerTools/skaffold/pull/6367 - `kpt requires "embed" package which was added in go1.6`

**Comment by MarlonGamez** [comment]
I think this may be a dupe of https://github.com/GoogleContainerTools/skaffold/issues/6348, do we want to keep both around or should we close one?

**Comment by aaron-prindle** [comment]
Ah sorry, didn't that at the time.  This is a dupe
