### ISSUE TITLE
skaffold inspect build-env list exits 0 on error

### ISSUE THREAD

**Issue by j-windsor** [GoogleContainerTools/skaffold#6801]
### Steps to reproduce the behavior

1. open up Cloud Code [NodeJS Guestbook Samples](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/nodejs/nodejs-guestbook) (this one uses skaffold modules)
2. run `skaffold inspect build-env list --profile kjhkjhkjh` (a profile that doesn't exist)
### Expected behavior
Exit code is nonzero on error
```
➜  guestbook-13 skaffold inspect build-env list --filename /Users/jameswindsor/guestbook-13/skaffold.yaml --profile cloudbuild {"errorCode":"CONFIG_PROFILES_NOT_FOUND_ERR","errorMessage":"profile selection [\"cloudbuild\"] did not match those defined in any configurations. Check that values specified in the \"--profile\" or \"-p\" flags are valid profile names."}
➜  guestbook-13 echo $?                                                                                                       
1
```
### Actual behavior
Exit code is zero on error
```
➜  guestbook-13 skaffold inspect build-env list --filename /Users/jameswindsor/guestbook-13/skaffold.yaml --profile cloudbuild {"errorCode":"CONFIG_PROFILES_NOT_FOUND_ERR","errorMessage":"profile selection [\"cloudbuild\"] did not match those defined in any configurations. Check that values specified in the \"--profile\" or \"-p\" flags are valid profile names."}
➜  guestbook-13 echo $?                                                                                                       
1
```

### Information

- Skaffold version: v1.34.0
- Operating system: MacOS 11.2.3 (M1)
- Installed via: Google Cloud SDK
- Contents of skaffold.yaml:
[heres](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/nodejs/nodejs-guestbook) (this one uses skaffold modules)

```
➜  guestbook-13 skaffold inspect build-env list --profile cloudbuild -v debug
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v1.34.0 ConfigVersion:skaffold/v2beta25 GitVersion: GitCommit:22cfab75ffb305e7af220910af2f48d0a5c0e6af BuildDate:2021-10-27T00:34:25Z GoVersion:go1.16beta1 Compiler:gc Platform:darwin/arm64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Disable housekeeping messages for command explicitly  subtask=-1 task=DevLoop
DEBU[0000] config version out of date: upgrading to latest "skaffold/v2beta25"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/jameswindsor/guestbook-13/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] config version out of date: upgrading to latest "skaffold/v2beta25"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/jameswindsor/guestbook-13/src/frontend/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
DEBU[0000] config version out of date: upgrading to latest "skaffold/v2beta25"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/jameswindsor/guestbook-13/src/backend/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
{"errorCode":"CONFIG_PROFILES_NOT_FOUND_ERR","errorMessage":"profile selection [\"cloudbuild\"] did not match those defined in any configurations. Check that values specified in the \"--profile\" or \"-p\" flags are valid profile names."}
```

**Comment by sujit-kamireddy** [comment]
This issue is not limited to skaffold inspect build-env list.
It also applies to skaffold inspect modules list and I suspect it may be a generic issue affecting more commands.

**Comment by ivanporty** [comment]
I don't see this issue with 1.34 and `inspect modules list --profile doesn-exist`:
```
$ skaffold inspect modules list --profile xyz
unknown flag: --profile
See 'skaffold inspect modules list --help' for usage.
$ echo $?
127
```

Confirmed with build env call.

**Comment by briandealwis** [comment]
So the problem is that the `list` command receives an error when trying to resolve the final profile and calls `WriteErr()` to write out the error:
https://github.com/GoogleContainerTools/skaffold/blob/05d51bc7e47e291e4b14c92e0537577b2ab98832/pkg/skaffold/inspect/profiles/list.go#L38-L42

`WriteErr()` ends up calling `JSONFormat.Output()` which writes out the error but returns a *different* error object, the result of writing out the error.  
https://github.com/GoogleContainerTools/skaffold/blob/05d51bc7e47e291e4b14c92e0537577b2ab98832/pkg/skaffold/output/format/format.go#L46-L55

Since the write succeeds, the formatter returns `nil`, which percolates back up to `main()`, and so Skaffold exits with 0:
https://github.com/GoogleContainerTools/skaffold/blob/05d51bc7e47e291e4b14c92e0537577b2ab98832/cmd/skaffold/skaffold.go#L49-L50

**Comment by briandealwis** [comment]
I was thinking that we could change and document that Formatter.WriteErr() should return the original error, but that's rather grotty and unexpected:
https://github.com/GoogleContainerTools/skaffold/blob/05d51bc7e47e291e4b14c92e0537577b2ab98832/pkg/skaffold/output/format/format.go#L28-L31

So I think the write thing to do (haha) is to change the error-writing code to be something like:
```
 cfgs, err := inspect.GetConfigSet(ctx, config.SkaffoldOptions{ConfigurationFile: opts.Filename, ConfigurationFilter: opts.Modules, RepoCacheDir: opts.RepoCacheDir}) 
 if err != nil {
 	formatter.WriteErr(err) // ignore formatter errors
 	return err
 }
```

That would cause the original error to percolate upwards where `app.ExitCode(err)` will assign a non-zero error code:
https://github.com/GoogleContainerTools/skaffold/blob/05d51bc7e47e291e4b14c92e0537577b2ab98832/cmd/skaffold/app/exitcode.go#L27-L34

**Comment by briandealwis** [comment]
But if we do this, then we get an error written out by Skaffold to stderr:
```
$ out/skaffold inspect build-env list --profile skdjfhskdjhf > /dev/null
profile selection ["skdjfhskdjhf"] did not match those defined in any configurations. Check that values specified in the "--profile" or "-p" flags are valid profile names.
```

I think we could move the error-reporting up into `app.Run()`, and annotate these commands to suppress error output.
