### ISSUE TITLE
skaffold dev  unable to connect to Kubernetes: getting client config for Kubernetes client

### ISSUE THREAD

**Issue by uchenxy** [GoogleContainerTools/skaffold#6806]
![image](https://user-images.githubusercontent.com/40748300/140476230-f325b6b2-5d00-4fac-88ff-eac418e73fd3.png)

![image](https://user-images.githubusercontent.com/40748300/140476488-0c3499b1-101a-42a3-9224-57cddb4598e2.png)

**### unable to connect to Kubernetes: getting client config for Kubernetes client: error creating REST client config in-cluster: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined**

why? thank you!

**Comment by briandealwis** [comment]
@uchenxy can you please confirm that the use of `KUBECONFIG_PATH` is a redacted version of the path to your kubeconfig file?

Could you try running `skaffold dev -v debug` and include the full output?

**Comment by uchenxy** [comment]
@briandealwis
this is the full output

> @uchenxy can you please confirm that the use of `KUBECONFIG_PATH` is a redacted version of the path to your kubeconfig file?
> 
> Could you try running `skaffold dev -v debug` and include the full output?

![image](https://user-images.githubusercontent.com/40748300/141246711-7ae0d2b2-4790-40c7-9dd1-84716bb50deb.png)
this is the full output，Thank you for your answer

**Comment by briandealwis** [comment]
The key here is the line after your highlight:

     no kube-context set and no kubeConfig found, attempting in-cluster config

you need to provide your KUBECONFIG to skaffold too, like

    skaffold dev —kubeconfig path

Skaffold will pass that down to Helm.

Skaffold also talks to your cluster and when it cannot determine which cluster to use, it tries to see if it’s running within a cluster.

We should make that error more clear.

**Comment by uchenxy** [comment]
Although this does not achieve my goal, thank you for your answer

**Comment by Derry-ukere** [comment]
any soluton to this yet?

**Comment by Derry-ukere** [comment]
`Starting deploy...
Cleaning up...
WARN[0001] deployer cleanup:kubectl create: running [kubectl --context  create --dry-run=client -oyaml -f /home/avenger/Desktop/devops/hello-world/infra/k8s/ConfigMap.yaml -f /home/avenger/Desktop/devops/hello-world/infra/k8s/cronjob.yaml -f /home/avenger/Desktop/devops/hello-world/infra/k8s/ingress-config.yaml -f /home/avenger/Desktop/devops/hello-world/infra/k8s/star-wars-depl-two.yaml -f /home/avenger/Desktop/devops/hello-world/infra/k8s/star-wars-depl.yaml]
 - stdout: ""
 - stderr: "Error from server (NotFound): the server could not find the requested resource\n"
 - cause: exit status 1  subtask=-1 task=DevLoop
unable to connect to Kubernetes: getting client config for Kubernetes client: error creating REST client config in-cluster: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
`

**Comment by MarlonGamez** [comment]
hey there @Derry-ukere , are you running into this issue using a similar setup? It seems you're using kubectl deployer and running into the same issue. Any more info on your config here would be great, thanks!

**Comment by AfhaamANJ** [comment]
**Any solutions for this issue ?**

**Comment by Adeku5080** [comment]
currently experiencing this issue when I run skaffold dev command.
