### ISSUE TITLE
skaffold  helm flags : unable to connect to Kubernetes: getting client config for Kubernetes client:..

### ISSUE THREAD

**Issue by uchenxy** [GoogleContainerTools/skaffold#6808]
![image](https://user-images.githubusercontent.com/40748300/140597391-6582560d-9907-437f-964e-817a9b3342c5.png)

![image](https://user-images.githubusercontent.com/40748300/140597405-3921073c-712c-4942-9136-3e3ac0b70096.png)

**Comment by briandealwis** [comment]
Duplicate of #6806
