### ISSUE TITLE
ko builder sideload displays both correct and incorrect tag when using default tag policy

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/skaffold#6835]
### Expected behavior

Using the ko builder with the default tag policy results in the output displaying the correct tag name.

### Actual behavior

The image builds correctly, and the correct tag is applied.

However, using the default tag policy results in the output displaying both the correct tag name and an image name with the wrong tag.

Using the `sha256` tag policy results in the correct tag being displayed.

### Information

Build from `main` at commit a9d715237873e19a22295159128ab9d85d7eb87b

Output:

```
$ skaffold build --cache-artifacts=false --push=false

Generating tags...
 - skaffold-ko -> australia-southeast1-docker.pkg.dev/test/default/skaffold-ko:v1.34.0-42-ga9d715237-dirty
Starting build...
Found [minikube] context, using local docker daemon.
Building [skaffold-ko]...
2021/11/11 22:49:46 Using base gcr.io/distroless/static:nonroot for github.com/GoogleContainerTools/skaffold/examples/ko
2021/11/11 22:49:50 Building github.com/GoogleContainerTools/skaffold/examples/ko for linux/amd64
2021/11/11 22:49:51 Loading australia-southeast1-docker.pkg.dev/test/default/skaffold-ko:83b8d5fec80f5c121ff0f4365f19a679ca1bb674c8533dd7189995c882da9d13
2021/11/11 22:49:51 Loaded australia-southeast1-docker.pkg.dev/test/default/skaffold-ko:83b8d5fec80f5c121ff0f4365f19a679ca1bb674c8533dd7189995c882da9d13
2021/11/11 22:49:51 Adding tag v1.34.0-42-ga9d715237-dirty
2021/11/11 22:49:51 Added tag v1.34.0-42-ga9d715237-dirty
australia-southeast1-docker.pkg.dev//default/skaffold-ko:83b8d5fec80f5c121ff0f4365f19a679ca1bb674c8533dd7189995c882da9d13
```

The image `australia-southeast1-docker.pkg.dev//default/skaffold-ko:v1.34.0-42-ga9d715237-dirty` is correctly built and exists in the local Docker daemon after the build is done.

**Comment by briandealwis** [comment]
The final image ref also seems to be missing the `test` repository component:
`....dev//default/skaffold-ko...` vs
`...dev/test/default/skaffold-ko...`

**Comment by halvards** [comment]
That may have been me editing out the project ID... :-)
