### ISSUE TITLE
Dev with dirty submodules

### ISSUE THREAD

**Issue by bhack** [GoogleContainerTools/skaffold#685]
### Expected behavior
skaffold dev could work with dirty submodules
### Actual behavior
skaffold dev fail with dirty submodules cause:
`mq FATA[0267] first build: exiting dev mode because the first build failed: generating tag: reading diff: read <mysubmodulepath>: is a directory`
### Information

- Skaffold version: 0.7

**Comment by Lawouach** [comment]
I am also seeing that issue. However I didn't have it with 0.7 but it appeared with 0.8.

**Comment by bhack** [comment]
@Lawouach  Can you test if is it solved with https://github.com/GoogleContainerTools/skaffold/pull/711?

**Comment by Lawouach** [comment]
@bhack I can confirm that with that fix, I don't get the issue I had with 0.8.0 that was released last week.
