### ISSUE TITLE
Skaffold should reformat (Cloud Logging-oriented) JSON structured logs

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6856]
GCP's Cloud Logging supports [receiving _structured log lines_](https://cloud.google.com/logging/docs/structured-logging) from applications, which are JSON objects with a specific set of fields.  It is awkward to use during development as humans aren't that great at parsing JSON.  Although GKE passes application logs through the [Cloud Logging Agent](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields) which parses the stream, developers using Skaffold will still see the JSON-formatted output.

We can make GCP developers' lives better by recognizing and reformatting such structured log lines:
- these structured logs should be valid JSON and be encoded as a single line, and thus should match the following regex `^{".*"}$`
- key fields are `severity`, and `message`; we could consider trying to interpret [the timestamp in one of its three possible forms](https://cloud.google.com/logging/docs/agent/logging/configuration#timestamp-processing)

cc: @Alos

**Comment by etanshaul** [comment]
@briandealwis @tejal29 should we try and prioritize this for Dec / Jan ? This has been a point of friction for some time. If you look at the Cloud Run Java Cloud Code samples they currently emit Stackdriver formatted log output, so this happens even out of the box with our samples.

Additional thoughts:
- Cloud Code also streams container logs directly (from the k8s explorer, outside of a `skaffold dev` session). We currently run `kubectl logs...` but this is susceptible to the same formatting problem. The IDEs could fix it themselves, but for the sake of sharing code it might make sense for Skaffold to support this as well: perhaps by exposing a `skaffold logs` command.

**Comment by tejal29** [comment]
/cc @marlon-gamez 

Got it. Basically the ask is to try parse the application logs retrieved from `kubectl logs` into [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) and emit only the text.

**Comment by etanshaul** [comment]
That’s right. That would be a great first step. A potential (to be discussed) follow up is outlined above in my comment under “additional thoughts”.

**Comment by MarlonGamez** [comment]
@briandealwis @etanshaul I'm assuming this is something that we'd want to be toggleable ?

**Comment by briandealwis** [comment]
Yeah, making it togglable as a deploy property in the skaffold.yaml?

**Comment by gennadiycivil** [comment]
@tejal29 Gentle ping, any updates on this thank you!

**Comment by MarlonGamez** [comment]
@gennadiycivil I'll be working on this this week

**Comment by MarlonGamez** [comment]
I've opened a PR for this now. I made it so that the fields that get parsed out are user configurable, so that this can be used in any use case with json logs

**Comment by etanshaul** [comment]
That’s great! Thanks @MarlonGamez. That sounds reasonable to me.

cc @Alos as well for feedback on the approach.
