### ISSUE TITLE
Difference between the run command and the dev command

### ISSUE THREAD

**Issue by riita10069** [GoogleContainerTools/skaffold#6885]
### Expected behavior

If we use the skaffold run command, shouldn't the process start in the background?
If you thinks that starting in the background is undesirable, shouldn't it return an error?
It is understandable to me that doing PortForward in a background process leads to Port conflicts and is undesirable.

### Actual behavior

If we use the skaffold run command, it will still start as dev mode by using certain options.
The options are, for example, --tail, --port-forward.

### Information

- Skaffold version:  1.26.1
- Operating system:  MacOS Bug Sur
- Installed via:  skaffold.dev
- Contents of skaffold.yaml:

```yaml

```

### Steps to reproduce the behavior

1. exec `skaffold run -f filename --tail` or `skaffold run -f filename --port-forward`

**Comment by aaron-prindle** [comment]
Currently `skaffold run` under the hood is essentially `skaffold dev` but only for a single iteration of the build and deploy loop (no file watching hooks, etc.).  `skaffold run` is not meant to run in the background, it should return an error and does for certain error types (example of `skaffold run` returning an error below):
```
$ cd validation-samples # has skaffold.yaml file with validation error, in this case `invalid` resourceType for PortForward
$ ~/validation-samples $ skaffold run
invalid skaffold config: source: /usr/local/google/home/aprindle/validation-samples/skaffold.yaml, in unnamed config at index 0: invalid is not a valid resource type for port forwarding
$ ~/validation-samples $ echo $?
1
```

Can you specify which errors you believe should result in an error code for `skaffold run` that currently do not?  Thanks.

**Comment by MarlonGamez** [comment]
hi @riita10069 , i'm going to close this issue for now, but please feel free to get back and continue this discussion if you need further clarification on anything
