### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#69]

**Comment by srivathsah** [comment]
Is there an installation for windows available to test this ?

**Comment by dlorenc** [comment]
We should add an e2e test run on Windows and publish binaries.

**Comment by dlorenc** [comment]
Going to close this in favor of the specific bugs: https://github.com/GoogleContainerTools/skaffold/issues/234

**Comment by sunnygoel8** [comment]
> Is there an installation for windows available to test this ?

yes, install using chocolatey package manager for windows platform.

`choco install skaffold`
