### ISSUE TITLE
build in cluster support for BuildKit

### ISSUE THREAD

**Issue by JCzz** [GoogleContainerTools/skaffold#6917]
Will cloud build support BuildKit?

Would be nice to be able to use [BuildKit with driver for kubernetes](https://github.com/moby/buildkit#kubernetes). 

Also maybe for tools like [kubectl-build-cli](https://github.com/vmware-tanzu/buildkit-cli-for-kubectl).

**Comment by aaron-prindle** [comment]
> Will cloud build support BuildKit?
Can you clarify, do you mean adding native support to skaffold for on cluster builds (kubernetes cluster + [BuildKit with driver for kubernetes](https://github.com/moby/buildkit#kubernetes)) or are you referring to using [Google Cloud Build](https://cloud.google.com/build) integration with skaffold BuildKit?  If it is the former I will update the issue text here and make label this a `feature request`

> Would be nice to be able to use [BuildKit with driver for kubernetes](https://github.com/moby/buildkit#kubernetes).
+1 I agree, this would be a good to support for skaffold to do on cluster builds with docker's BuildKit.  Currently it is possible to do on cluster builds with skaffold+kaniko integration.  See [kankio](https://github.com/GoogleContainerTools/kaniko) and https://skaffold.dev/docs/pipeline-stages/builders/docker/#dockerfile-in-cluster-with-kaniko

> Also maybe for tools like [kubectl-build-cli](https://github.com/vmware-tanzu/buildkit-cli-for-kubectl).
Agreed.

**Comment by JCzz** [comment]
Yes I was thinking of:

BuildKit (kubernetes cluster + skaffold support for BuildKit with driver for kubernetes).

Thanks

Do you have any opinion on [BuildKit CLI for kubectl](https://github.com/vmware-tanzu/buildkit-cli-for-kubectl) ?
