### ISSUE TITLE
v1.35.1 tag was force pushed

### ISSUE THREAD

**Issue by leoluk** [GoogleContainerTools/skaffold#6950]
Running `git fetch --tags` on my local checkout results in the following error:

```
skaffold $ git fetch --tags 
From https://github.com/GoogleContainerTools/skaffold
 ! [rejected]            v1.35.1    -> v1.35.1  (would clobber existing tag)
```

My local checkout points to 4ec4a23aeac4eab0ec6eaefc5aff459cd59166ba, while the upstream repo points to bfc618edd22b577fff49a467588f0b87f3cac3e5.

Just leaving this here in case this is unexpected or indicating an account compromise.

**Comment by leoluk** [comment]
... and again, this time from `23c144ea1` to `351898de4`. What's going on? :eyes:

**Comment by tejal29** [comment]
@leoluk Sorry, There was an error when manually testing new github trigger pipeline. 
Things are now restored. Let us know if you still have issues.
