### ISSUE TITLE
Support user-provided post-renderer for filtering

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6951]
Tracking bug: #6706

#6949 changes our Helm deployer to use Skaffold as a post-renderer.  This change will break any users that had configured Helm to use their own post-renderer hooks via [`deploy.helm.flags`](https://skaffold.dev/docs/references/yaml/#deploy-helm-flags). We can have `skaffold filter` support a `--post-renderer` flag that then invokes the user-configured post-renderer.

**Comment by jearangoo** [comment]
is there any progress on this?
i am inserting a post renderer in the flags array `[ "--post-renderer=./charts/app/kustomizations/dev/render.sh" ]` in deploy.helm.flags.install and deploy.helm.flags.upgrade to add patches, secrets and resources like managed google cloud https certificates, to my chart as they vary between environments, when running `skaffold run`, `skaffold dev` and `skaffold deploy`,  but its not working with version 2, maybe this should be linked as well #5387, thanks.

**Comment by Agalin** [comment]
This is a blocker for us, we won't be able to migrate to v2 until a way to run post renderers is added.

We're using them to inject secrets, template stuff outside of Skaffold's and Helm's reach and even pipeline results through kustomize at times.
