### ISSUE TITLE
Skaffold 1.35.1 source file checksum changed

### ISSUE THREAD

**Issue by iMichka** [GoogleContainerTools/skaffold#6962]
### Expected behavior

Checksum of the 1.35.1 version was 4ec4a23aeac4eab0ec6eaefc5aff459cd59166ba, 24 days ago.
But it changed to 6945c5b1cfcffc4a168f26673c0f6695f2088dd2 a few days ago.

We would like no checksum changes, and a confirmation everything is fine on your side.

### Actual behavior

There are two options here:
- Did you retag? This is "the insane thing to do" (from the official git documentation): https://git-scm.com/docs/git-tag#_discussion
- Was your account compromised and someone took the opportunity to ship a malicious version? This might be a serious security issue.

Related issue on our side: https://github.com/Homebrew/homebrew-core/pull/91182

**Comment by iMichka** [comment]
Looks like I was not the only one bitten by this: #6950

**Comment by leoluk** [comment]
It actually looks like there are _three_ different versions now :eyes:

- 4ec4a23
- 6945c5b
- bfc618e

**Comment by tejal29** [comment]
@leoluk Sorry. there was an manual error when running a github trigger due to which accidentally we published a v1.35.1 version.

This should be the right v1.35.1 release https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.35.1

**Comment by tejal29** [comment]
Feel free to comment if this does not answer your issue

**Comment by iMichka** [comment]
Thanks for the clarification. Just from a package manager point of view, best would have been to delete the 1.35.1 tags, and finally tag a correct 1.35.2 or even 1.35.2. This would have skipped 1.35.1 / 1.35.2 but it is perfectly fine to have a hole in the git tags, if it brings clarity that these releases have been withdrawn / were wrong.
