### ISSUE TITLE
GCP service account impersonation massively slows down Skaffold build

### ISSUE THREAD

**Issue by dominikbraun** [GoogleContainerTools/skaffold#6980]
When running `skaffold dev`, the build step is dramatically slowed down by a command related to GCP service account impersonation:

```
Building [my-service]...
WARNING: This command is using service account impersonation. All API calls will be executed as [...].
```

This output takes some minutes, and the command eventually fails:

```
ERROR: (gcloud.auth.docker-helper) Failed to impersonate [...]. Make sure the account that's trying to impersonate it has access to the service account itself and the "roles/iam.serviceAccountTokenCreator" role.
```

**I don't have a GCP-related command in my `skaffold.yaml` file and don't know which particular command causes this error message.** Any ideas?

I'm running Skaffold 1.35.1 on macOS 11.

**Comment by gsquared94** [comment]
can you provide your `skaffold.yaml` file and/or the output of running `skaffold dev -v DEBUG` after removing any sensitive info?

**Comment by gsquared94** [comment]
`gcloud` is registered as the credential helper for Google-supported Docker registries in your Docker config file, which triggers this GCP command. I have no idea about the exact nature of this problem, however have you tried [this](https://stackoverflow.com/a/64949872/4540147) stackoverflow answer?

**Comment by dominikbraun** [comment]
@gsquared94 Yes, I came across this answer in the meantime as well and it works. Thanks!

## Solution

Just deactivate service account impersonation for GCP:

```
gcloud config unset auth/impersonate_service_account
```
