### ISSUE TITLE
Consider pinning https://github.com/golangci/golangci-lint/

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/skaffold#699]
We just had an issue where golangci-lint started failing in CI because of some new validation rules they added. This is a bad experience for contributors who start to see failures in CI unrelated to their changes.

We should consider pinning to a release available at https://github.com/golangci/golangci-lint/releases

**Comment by dlorenc** [comment]
Ref #697

**Comment by dgageot** [comment]
@dlorenc I'd love to do that. How can we pin a given version though?

**Comment by dlorenc** [comment]
For travis we can grab one of the releases from https://github.com/golangci/golangci-lint/releases with curl/tar and then validate the sha. Or we could go get then cd/git checkout.

**Comment by r2d4** [comment]
I did this for dep

https://github.com/GoogleContainerTools/skaffold/blob/master/hack/dep.sh#L19-L30

Although this method fails when you have an old version of dep already on your path. Theres probably some extra work to be done to verify the installed version is correct

**Comment by jirfag** [comment]
Hi!
Here https://github.com/golangci/golangci-lint/blob/master/README.md#install are commands for pinning a release, it has installation script. Also it much faster than go get
