### ISSUE TITLE
missing concurrency field for custom build

### ISSUE THREAD

**Issue by amitm02** [GoogleContainerTools/skaffold#6990]
there are "concurrency" field for builds of type local, googleCloudBuild and cluster.
but there is not way to indicate how many parallel builds to perform for custom build: https://skaffold.dev/docs/pipeline-stages/builders/custom/

**Comment by gsquared94** [comment]
the `concurrency` field is specified at the _build environment_ level i.e. `local`, `googleCloudBuild` or `cluster` which sets how many `artifacts` can be built in parallel. If you're running multiple builds within a single `custom` artifact definition then you can't control their concurrency, but if they are defined as individual skaffold _artifacts_ then you can set `local.concurrency` to control that. Is it possible to share your `skaffold.yaml` file?

**Comment by amitm02** [comment]
I do not think the custom build falls under either local, googleCloudBuild, or cluster.
that is the problem, the custom build is a different type of build and maybe just like we can have:

```
build: 
  local:
      concurrency: 1
```

we should be able to have:

```
build: 
  custom:
      concurrency: 1
```

**Comment by gsquared94** [comment]
oh, the `custom` builder should work with `build.local.concurrency`.

**Comment by amitm02** [comment]
I see, in that case, I think there is a bug involved that caused me the be confused about it.
I've just tested with a custom build that all it does is run a bash script of `sleep 30`  and use build.local.concurrency=10.
It builds just the first artifact first, wait for 30 seconds. only after the first artifact is done, it run the rest of the artifacts in concurrency.

**Comment by gsquared94** [comment]
> It builds just the first artifact first, wait for 30 seconds. only after the first artifact is done, it run the rest of the artifacts in concurrency.

So we are limited by not being able to show concurrent build outputs on the terminal which is why we write to a buffer and print them out altogether at the end. The actual builds are happening concurrently. You can get a better visualization of the concurrent builds if you're using [Cloud Code](https://cloud.google.com/code/docs/vscode/viewing-k8-logs) along with skaffold

**Comment by amitm02** [comment]
can confirm. it's just a log buffer issue.

**Comment by gsquared94** [comment]
closing this issue since we previously discussed this and aren't going to change the terminal output anytime soon and recommend the UX provided by Cloud Code for a better visualization of skaffold logs.
