### ISSUE TITLE
SHA256 checksums of release 1.35.1 don't check out for the Mac releases

### ISSUE THREAD

**Issue by delanni** [GoogleContainerTools/skaffold#6991]
### Expected behavior
The advertised sha256 checksums for the released binaries should be what we get for the binaries.

### Actual behavior
The advertised .sha256 files differ from what we get locally with `shasum -a 256` for the Mac releases

### Information

- Skaffold version: v1.35.1
- Operating system: Mac OSX Big Sur
- Installed via: curl
- Contents of skaffold.yaml: Not relevant

### Steps to reproduce the behavior
```bash
➜  curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.35.1/skaffold-linux-amd64
➜  curl -Lo skaffoldAmd64 https://storage.googleapis.com/skaffold/releases/v1.35.1/skaffold-darwin-amd64 && shasum -a 256 skaffoldAmd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66.0M  100 66.0M    0     0  17.4M      0  0:00:03  0:00:03 --:--:-- 17.4M
178084bf0405f4be2dfde3a97d59273206f08110dba30592951165260e7c4b84  skaffoldAmd64

# at the same time
➜ curl -Lo skaffoldAmd64.sha256 https://github.com/GoogleContainerTools/skaffold/releases/download/v1.35.1/skaffold-darwin-amd64.sha256 && cat skaffoldAmd64.sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   667  100   667    0     0    943      0 --:--:-- --:--:-- --:--:--   942
100    88  100    88    0     0     88      0  0:00:01 --:--:--  0:00:01    88
7e85c3319162658495ed560d8f983492ff2663ce30a2233b3f4a871b74d7bd21  skaffold-darwin-amd64
```

`178084bf0405f4be2dfde3a97d59273206f08110dba30592951165260e7c4b84 != 7e85c3319162658495ed560d8f983492ff2663ce30a2233b3f4a871b74d7bd21`

**Comment by solsson** [comment]
Actual checksum for the darwin-arm64 binary is `ee26c4334bc787633aec6d4cbd8386d95a8cc6e34e2ef7cd37805ba98b28310d`

**Comment by MarlonGamez** [comment]
@delanni thanks for pointing this out. We've recently changed our release process before doing this release and I believe we are now calculating checksums at the wrong time. This should be fixed for next release, and I'll work on getting the correct checksums into the release page for 1.35.1
