### ISSUE TITLE
Reference for skaffold.yaml is missing in website

### ISSUE THREAD

**Issue by arikkfir** [GoogleContainerTools/skaffold#7017]
### Expected behavior

Reference of the `skaffold.yaml` to be shown in the URL: https://skaffold.dev/docs/references/yaml

### Actual behavior

No YAML reference shown. Small paragraph about YAML anchors and "Organizing multiple configurations" are shown, but that's it.

### Steps to reproduce the behavior

1. Navigate to https://skaffold.dev/docs/references/yaml/

**Comment by halvards** [comment]
I can see the content. Do you still experience this issue?

![Screenshot 2022-01-18 09 01 37](https://user-images.githubusercontent.com/52342/149841606-4c286f25-620e-44fc-94a1-168bd64f1da7.png)

**Comment by arikkfir** [comment]
Yes I can see it too now - perhaps it was a momentary issue.
Closing.

Thanks!
