### ISSUE TITLE
Build step: generating tag fails

### ISSUE THREAD

**Issue by sbulman** [GoogleContainerTools/skaffold#703]
Running skaffold build (or dev) fails when running in a directory that has a Visual Studio solution open. 

### Expected behavior
skaffold build is successful

### Actual behavior
skaffold build fails with the following error:

FATA[0001] build step: generating tag: reading status: open /mnt/c/Development/temp/Lofts/.vs/Lofts/v15/Server/sqlite3/db.lock: permission denied

### Information
This looks similar to [this issue](https://stackoverflow.com/questions/47460039/vs-2017-git-local-commit-db-lock-error-on-every-commit) which might indicate that skaffold is not processing the ,gitignore file correctly (if it is at all?)

My setup is a little complex, I am running skaffold v0.7.0 in WSL (due to issue #695).

**Comment by dgageot** [comment]
Should be fixed with https://github.com/GoogleContainerTools/skaffold/pull/714

**Comment by dgageot** [comment]
Fixed with #714
