### ISSUE TITLE
[V2] TestDockerDebug integration test fail

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7030]
As per test logs for PR https://github.com/GoogleContainerTools/skaffold/pull/6949

Log: https://gist.github.com/tejal29/d147b48ead35f859b382110cd590e291#file-gistfile1-txt-L235

Steps to reproduce. 
1) Check out GoogleContainerTools:v2-v1.35.0 : https://github.com/GoogleContainerTools/skaffold/tree/v2-v1.35.0
2) Run integration test mentioned

**Comment by dhodun** [comment]
I've taken a look. The test is essentially a `skaffold build` followed by a `skaffold debug` and inspecting that the entrypoint is rewritten and a support container is attached.

Fixing missing Deployer schema entries for Docker deployer unblocks `skaffold build`. The `skaffold debug` command still seems to be blocked by: https://github.com/GoogleContainerTools/skaffold/issues/7104

**Comment by dhodun** [comment]
Partial Fix created: https://github.com/GoogleContainerTools/skaffold/pull/7189
