### ISSUE TITLE
[V2] TestFixStdout failing on v2 branch

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7033]
As per test logs for PR https://github.com/GoogleContainerTools/skaffold/pull/6949

Log: https://gist.github.com/tejal29/d147b48ead35f859b382110cd590e291#file-gistfile1-txt-L358

Tests failing:

1) TestFixOutputFile
2) TestFixStdout

Steps to reproduce. 
1) Check out GoogleContainerTools:v2-v1.35.0 : https://github.com/GoogleContainerTools/skaffold/tree/v2-v1.35.0
2) Run integration test.

**Comment by tejal29** [comment]
This test is still failing.

Lets add a test.Skip for now and keep this issue open.

Assigning it to @MarlonGamez  to  add a TODO. 
Please un-assign after

**Comment by tejal29** [comment]
Actually this is part of `Making skaffold fix work on v2` which is already assigned to @MarlonGamez

**Comment by MarlonGamez** [comment]
Closing this in favor of https://github.com/GoogleContainerTools/skaffold/issues/6721
