### ISSUE TITLE
[v2] fix Skaffold v3 config duplication

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7055]
While going through the skaffold v3alpha1 config, I found a bit of redundancy

1) `manifests`, `helmReleases` and `kustomizePaths` is duplicated in  render config as well respective deploy config i.e. `KubectlDeploy`, `HelmDeploy` and `KustomizeDeploy`.

2) Remote manifests config should be moved from `KubectlDeploy` to `manifests` config section.

**Comment by MarlonGamez** [comment]
@tejal29 I think some of this duplication may need to still exist. Since we are going to support a LegacyHelmDeployer as well as a Helm Renderer, I think we'll need the config in both places right?

**Comment by aaron-prindle** [comment]
@MarlonGamez is it possible to have the LegacyHelmDeployer read the manifests information from the `manifests` section vs the `deploy.helm.*` section of the skaffold.yaml config?  This way we could properly remove these fields and not confused users who might bump the apiVersion manually but then have lots of render & deploy errors but no validation errors

**Comment by aaron-prindle** [comment]
Done, closing
