### ISSUE TITLE
Files not included in Dockerfile `COPY` instructions trigger artifact rebuilds

### ISSUE THREAD

**Issue by rahil-p** [GoogleContainerTools/skaffold#7075]
### Expected behavior

```dockerfile
FROM node AS dev

WORKDIR /home/node
COPY packages/db/package.json ./packages/db/
COPY packages/db/build ./packages/db/build/
```

```yaml
sync:
  manual:
  - src: 'packages/db/build/**/*'
    dest: /home/node/
```

The following are working as expected:
- changes inside `packages/db/build` are synchronized
- changes to `packages/db/package.json` trigger a rebuild

Additionally expected:
- changes to files that are not included in any `COPY` instructions (e.g. `packages/db/tsconfig.json`) do not trigger a rebuild

### Actual behavior

Despite modifying a file that never ends up the container, the change still triggers a rebuild of the artifact.

While this can be fixed with a `.dockerignore`, this isn't really feasible when multiple Docker build targets share the same context (e.g. a monorepo in which all builds don't share the same ignore rules).

### Information

- Skaffold version: v1.3.5
- Operating system: MacOS Big Sur (11.3)
- Installed via: Homebrew

**Comment by kadern0** [comment]
Cannot reproduce this behavior on Linux with the latest main code.

**Comment by rahil-p** [comment]
After checking Skaffold's debug logs, it seems like I missed an important point in the original issue.  The Dockerfile is multi-stage, but dependencies are being found from stages that Buildkit otherwise skips.

Sorry for any time lost trying to reproduce this issue.  I'll close this for now and post a new issue once I've investigated it some more.
