### ISSUE TITLE
Use kubernetes dynamic client for labeling

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#708]
https://github.com/kubernetes/client-go/blob/master/dynamic/interface.go

Might be used to make this code more robust and remove almost all the boilerplate

https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/runner/label/label.go#L64-L115

**Comment by nkubala** [comment]
I'll look into this

**Comment by dlorenc** [comment]
What did we decide here? It's not worth doing right now?

**Comment by nkubala** [comment]
Yeah I deprioritized this based on the amount of work it ended up being. If someone else wants to take a stab at it feel free but I don't think it's worth the effort right now
