### ISSUE TITLE
Disabling profiles does not work

### ISSUE THREAD

**Issue by vladimir-avinkin** [GoogleContainerTools/skaffold#7084]
### Expected behavior
According to documentation (in `skaffold --help`) prepending a minus sign before a profile name should disable it, instead, we get an error.
### Actual behavior
When trying to disable a profile we get an error that says that a profile with a prepended minus is not declared.

### Information

- Skaffold version: v1.35.2
- Operating system: Darwin MacBook-Pro-Vladimir.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- Installed via: homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta13
kind: Config
profiles:
  - name: default
  - name: test
```

Below are my speculations:
The initial feature was introduced here https://github.com/GoogleContainerTools/skaffold/pull/4054 and then probably the logic got duplicated somewhere along the way, probably two places that conflict with each other are here:
https://github.com/GoogleContainerTools/skaffold/blob/20ae7f64ccdb9fcf40fb18e41f3cd9a86eb312ed/pkg/skaffold/parser/config.go#L96
https://github.com/GoogleContainerTools/skaffold/blob/20ae7f64ccdb9fcf40fb18e41f3cd9a86eb312ed/pkg/skaffold/schema/profiles.go#L130

### Steps to reproduce the behavior

1. bare skaffold.yaml contents of which are stated above is enough to reproduce
2. `skaffold dev -p -test`
3. According to documentation prepending a minus sign before a profile name should disable it, instead we got an error
```
skaffold dev -p -test
parsing skaffold config: profile selection ["-test"] did not match those defined in any configurations. Check that values specified in the "--profile" or "-p" flags are valid profile names.
```

**Comment by tomas-mota** [comment]
I'll take a look at this :)

**Comment by tomas-mota** [comment]
@vladimir-avinkin the error message should definitely be more clear, but it seems like you are trying to disable the 'test' profile, even though no profile was activated. As you can read [here](https://skaffold.dev/docs/environment/profiles/), no profile is enabled by default, you have to activate it either through the command or setting triggers in the yaml.

Perhaps what would make sense is that if you exclude a profile that was not activated anyways, it simply continues without erroring (perhaps this was what you actually meant and I misunderstood)
