### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#71]

**Comment by r2d4** [comment]
https://aur.archlinux.org/packages/skaffold/

**Comment by wi-ski** [comment]
I'm absolutely elated at the fact you did this six hours before I wanted it. Thank you for all your efforts you handsome, handsome man. <3

**Comment by r2d4** [comment]
I wish I could take credit, but this work was not my doing. Thank you @frealgagu!
