### ISSUE TITLE
Skaffold Render is Non-obvious in Minikube workflow

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#7103]
Affects v1, v2.

Most of the skaffold commands are supported in minikube when the minikube kubectl context is set, `skaffold render` is an exception and requires the non-obvious `--digest-source=local` to be added.

Use case:
- New user who is primarily learning all the steps using minikube (and thus no remote repo).
- A user who is trying to make their skaffold setup repo agnostic, setting the repo in the future with --default-repo and leaving the repo off of all image names. They test all the commands locally to replicate the workflow before pointing to GCR, GKE, etc.

Repro:

1. Checkout release/v1.35.1
2. Start minikube and set as kubectl context
3. in `examples/getting-started` the following commands work easily:
- build
- dev
- debug
- run
- delete
4. `skaffold render` throws the following:
```
failed to resolve the digest of skaffold-example:v1.35.2: does the image exist remotely?
```
5. `skaffold render --digest-source=local` succeeds

There is plenty of helper logic making `minikube` "just work" until the render command. Since the default for `--digest-source` is `remote`, this breaks that simple workflow.
https://skaffold.dev/docs/references/cli/#skaffold-render

Proposed fixes:
- Reconsider `remote` as default
- Add helper magic so that if in minikube context `remote` is interpreted to mean minikube docker daemon

**Comment by dhodun** [comment]
Also effects more workflows in v2 since render is more prevalent: https://github.com/GoogleContainerTools/skaffold/issues/7104

**Comment by gsquared94** [comment]
IMO if we detect a _local_ cluster then we should also default to `digest-source=tag`.  
We can remove the default value for the flag here:
https://github.com/GoogleContainerTools/skaffold/blob/20ae7f64ccdb9fcf40fb18e41f3cd9a86eb312ed/cmd/skaffold/app/cmd/flags.go#L593
and instead set it here:
https://github.com/GoogleContainerTools/skaffold/blob/16b931d138b6f10c18dfc04a4f8ca5057d612fe6/pkg/skaffold/runner/runcontext/context.go#L198
```go
func (rc *RunContext) DigestSource() string {
	if rc.Opts.DigestSource != "" {
		return rc.Opts.DigestSource
	}
	if rc.Cluster.Local {
		return TagDigestSource
	}
	return RemoteDigestSource
}
```


This should make the behavior of being able to run `skaffold build && skaffold render` consistent across:
- a minikube cluster that builds the image to the minikube docker daemon and does not push to a remote registry. 
- a remote cluster that builds the image and pushes it to a remote registry.

**Comment by dhodun** [comment]
As discussed on chat, I think this will work, particularly in v2 where Render should really be its own phase.

--digest-source=local seems to perform a silent auto-build for local contexts (silent meaning there is not stdout output for cache hits, etc)
--digest-source=tag assumes in all contexts that `skaffold build` will already have been run. And it should work for the contexts mentioned in the bug, including minikube.

Also discussed: a few better examples in the docs of assembling or piping the more focused skaffold commands to compose a pipeline.

**Comment by MarlonGamez** [comment]
+1 to defaulting to `tag` for local clusters
