### ISSUE TITLE
[V2] Some minikube workflows break if they the command now involves render phase

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#7104]
Related to: https://github.com/GoogleContainerTools/skaffold/issues/7103

Some skaffold commands break in minikube context using v2. From what I've debugged it's when they are hitting the render phase and render phase is defaults to 'remote' digest-source.

Repro (kubectl manifest):

1. Checkout v2-v1.35.2
2. Start minikube and set context
3. `cd integration/examples/getting-started`
4. `skaffold build` then `skaffold debug` hits the remote repo error mentioned in https://github.com/GoogleContainerTools/skaffold/issues/7103
```
failed to resolve the digest of skaffold-example:50edfd8b57a0f7185cce01a71acc93306f9bcbcc66a2f014d81f816c84af7bae: does the image exist remotely?
```
5. `skaffold run` succeeds, however, presumably because they are skipping the render phase?
6. `skaffold dev` does not succeed, same error

This example has simple kubectl manifest - I believe there is a hack for this type of deployer:
```
deploy:
  kubectl:
    manifests:
      - k8s-*
```

Repro (helm):
Trying a different type of deployer (maybe helm is bad choice):

1. Same setup as before
2. `cd integration/examples/helm-deployment`
3. build works
4. run seems to succeed, but nothing is deployed on the cluster
5. render fails with usual error
6. debug fails with usual error

I know there is some magic related to either no deployer or kubectl deployer where we skip render but haven't found an example where we see none of these errors.

Also, the `--digest-source=local` fix doesn't work for these other commands aside from skaffold render because it's not a valid flag for them.

**Comment by gsquared94** [comment]
https://github.com/GoogleContainerTools/skaffold/issues/7103#issuecomment-1041146353 should work for this issue also.
