### ISSUE TITLE
Don't see installers for any of the releases done on 3/2/22 (e.g. 1.36.1)

### ISSUE THREAD

**Issue by todd-andrew-procore** [GoogleContainerTools/skaffold#7158]
### Expected behavior

Should see installers here: https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.36.1

### Actual behavior

- No installers exist.
- Also, the windows release example reads `https://storage.googleapis.com/skaffold/releases/v1.36.1skaffold-windows-amd64.exe` (missing a slash after 1.36.1)

### Information

N/A

### Steps to reproduce the behavior

N/A

**Comment by tejal29** [comment]
Dupe of #7165
