### ISSUE TITLE
Installing Skaffold

### ISSUE THREAD

**Issue by jmcudd** [GoogleContainerTools/skaffold#7198]
### Expected behavior
When downloading the `/latest/` binary, skaffold version should be 1.36.1
```
$ curl https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 -o skaffold
$ chmod +x skaffold
$ ./skaffold version
v1.36.1
```
### Actual behavior
The Skaffold version is stale
```
$ curl https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 -o skaffold
$ chmod +x skaffold
$ ./skaffold version
v1.35.2
```
### Information

- Skaffold version: N/A
- Operating system: Arch Linux
- Installed via: Standalone Binary https://skaffold.dev/docs/install/#standalone-binary
- Contents of skaffold.yaml: N/A

### Steps to reproduce the behavior

```
curl https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 -o skaffold
chmod +x skaffold
./skaffold version

```

**Comment by tejal29** [comment]
Aah. This will be fixed by #7199 soon. 
We had an error in our release process where we updated the latest bucket when patching old skaffold versions. 
We should be fixing it.

**Comment by kevin-hanselman** [comment]
@tejal29 FWIW this is not fixed with the release of 1.37, at least not yet.

```
$ curl -sLo skaffold 'https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-arm64'

$ chmod +x skaffold

$ ./skaffold version
v1.35.2

$ date
Fri Mar 18 10:21:00 EDT 2022
```

**Comment by tejal29** [comment]
hmm interesting, its fixed for `darwin-amd64`
```

curl -sLo skaffold 'https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64'
➜  microservices git:(main) ✗ chmod +x skaffold
➜  microservices git:(main) ✗ ./skaffold version
v1.37.0
➜  microservices git:(main) ✗ 
```

**Comment by tejal29** [comment]
Can you try again? Sorry we delayed the v.1.37.0 release due to corporate holiday.

**Comment by kevin-hanselman** [comment]
@tejal29 All good now. Thanks for looking into this.

**Comment by jmcudd** [comment]
Thanks for the fix!

**Comment by aaron-prindle** [comment]
This should be fixed now (our release CI/CD properly updates skaffold/releases/latest now).  Marking closed (fixed)
