### ISSUE TITLE
Some changed are not deployed because git tag is computed too late

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#720]
Currently, tags are computed after the image is built.

When in a dev loop, some changes to files can occur during the build, so before the image tag is computed. Next time the image is rebuilt, it will be rebuilt with the same tag so it won't be deployed.

**Comment by jonjohnsonjr** [comment]
This could be solved by deploying by manifest digest instead of deploying by tag.

I think this would be a pretty large change, since I believe skaffold assumes you have a tag (basically everywhere).
