### ISSUE TITLE
Cannot file sync using helm to deploy

### ISSUE THREAD

**Issue by Fdslk** [GoogleContainerTools/skaffold#7211]
### Syncing 1 files for skaffold-webflux-example:d9d9fb5066bd7a50e3b1e2290ed437e7fdd6d12f46b57fbc07873a6683fae4e8
Watching for changes... but get the former response context as well

### Information

- Skaffold version: v1.37.0
- Operating system:macOS 12.0.1
- Installed via: homebrew
- Contents of skaffold.yaml:

```yaml
https://github.com/Fdslk/ops/blob/main/skaffoldDemo/rxjavademo/skaffold.yaml
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project (https://github.com/Fdslk/ops.git)
2. `skaffold dev`
3. modify hellocontroller content
4.there is not changing when using 'curl --get http://localhost:8080/hello'

**Comment by tejal29** [comment]
@Fdslk Can you please provide more information and debug logs `skaffold dev -v=trace` for the issue.

**Comment by Fdslk** [comment]
Hey,@tejal29. The detail as follows: could you please check it thx. 
`DEBU[0091] Change detectednotify.Write: "/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/src/main/java/com/example/javademo/HelleController.java"  subtask=-1 task=DevLoop
DEBU[0092] Change detectednotify.Write: "/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class"  subtask=-1 task=DevLoop
DEBU[0093] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0093] could not stat dependency: stat /Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/src/main/jib: no such file or directory  subtask=-1 task=DevLoop
DEBU[0093] Found dependencies for jib maven artifact: [pom.xml src/main/java/com/example/javademo/DemoApplication.java src/main/java/com/example/javademo/HelleController.java src/main/resources/application.properties src/main/resources/application.properties]  subtask=-1 task=DevLoop
INFO[0093] files modified: [src/main/java/com/example/javademo/HelleController.java]  subtask=-1 task=DevLoop
DEBU[0093] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0093] Running command: [/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/mvnw --batch-mode jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=2.0.0 -Psync --non-recursive -DskipTests=true prepare-package jib:_skaffold-sync-map]  subtask=-1 task=DevLoop
DEBU[0096] Change detectednotify.Write: "/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst"  subtask=-1 task=DevLoop
DEBU[0096] Change detectednotify.Write: "/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst"  subtask=-1 task=DevLoop
DEBU[0097] Command output: [[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.javademo:javademo:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.projectlombok:lombok:jar -> duplicate declaration of version (?) @ line 47, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -----------------------< com.javademo:javademo >------------------------
[INFO] Building skaffold-webflux-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jib-maven-plugin:3.2.0:_skaffold-fail-if-jib-out-of-date (default-cli) @ javademo ---
[INFO]
[INFO] -----------------------< com.javademo:javademo >------------------------
[INFO] Building skaffold-webflux-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ javademo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ javademo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ javademo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ javademo ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ javademo ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- jib-maven-plugin:3.2.0:_skaffold-sync-map (default-cli) @ javademo ---

BEGIN JIB JSON: SYNCMAP/1
{"generated":[{"src":"/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/classes/application.properties","dest":"/app/resources/application.properties"},{"src":"/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/DemoApplication.class","dest":"/app/classes/com/example/javademo/DemoApplication.class"},{"src":"/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class","dest":"/app/classes/com/example/javademo/HelleController.class"}],"direct":[]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.195 s
[INFO] Finished at: 2022-03-29T09:10:28+08:00
[INFO] ------------------------------------------------------------------------
]  subtask=-1 task=DevLoop
TRAC[0097] dev intents: build true, sync true, deploy true  subtask=-1 task=DevLoop
DEBU[0097]  devloop: build false, sync true, deploy false  subtask=-1 task=DevLoop
Syncing 1 files for skaffold-webflux-example:d9d9fb5066bd7a50e3b1e2290ed437e7fdd6d12f46b57fbc07873a6683fae4e8
INFO[0097] Copying files:map[/Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class:[/app/classes/com/example/javademo/HelleController.class]]toskaffold-webflux-example:d9d9fb5066bd7a50e3b1e2290ed437e7fdd6d12f46b57fbc07873a6683fae4e8  subtask=-1 task=DevLoop
DEBU[0097] getting client config for kubeContext: `minikube`  subtask=-1 task=DevLoop
Watching for changes...
DEBU[0097] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0097] could not stat dependency: stat /Users/zengqiangfang/Documents/code/ops/skaffoldDemo/rxjavademo/src/main/jib: no such file or directory  subtask=-1 task=DevLoop
DEBU[0097] Found dependencies for jib maven artifact: [pom.xml src/main/java/com/example/javademo/DemoApplication.java src/main/java/com/example/javademo/HelleController.java src/main/resources/application.properties src/main/resources/application.properties]  subtask=-1 task=DevLoop
TRAC[0097] dev intents: build true, sync true, deploy true  subtask=-1 task=DevLoop
TRAC[0110] [port-forward] Forwarding from 127.0.0.1:8080 -> 8080  subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0111] [port-forward] Forwarding from [::1]:8080 -> 8080  subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0112] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0113] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0114] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0115] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward`

**Comment by Fdslk** [comment]
If I use kubectl as my deploying section, file sync can work well.

**Comment by tejal29** [comment]
Thanks @Fdslk for providing the debug logs and the fact that kubectl sync well. 
Trying this now. Will report back.

**Comment by tejal29** [comment]
@Fdslk I was able to see the files synced

```

BEGIN JIB JSON: SYNCMAP/1
{"generated":[{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/application.properties","dest":"/app/resources/application.properties"},{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/DemoApplication.class","dest":"/app/classes/com/example/javademo/DemoApplication.class"},{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class","dest":"/app/classes/com/example/javademo/**HelleController.class**"}],"direct":[]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.032 s
[INFO] Finished at: 2022-05-23T12:45:44-07:00
[INFO] ------------------------------------------------------------------------
]  subtask=-1 task=DevLoop
TRAC[0037] dev intents: build true, sync true, deploy true  subtask=-1 task=DevLoop
DEBU[0037]  devloop: build false, sync true, deploy false  subtask=-1 task=DevLoop
Syncing 2 files for gcr.io/tejal-gke1/skaffold-webflux-example:latest@sha256:36996a47d65f3e6b6818bbbeb88e6964298fa3a2a22b4c039b8ef13a150c5e1b
INFO[0037] Copying files:map[/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/DemoApplication.class:[/app/classes/com/example/javademo/DemoApplication.class] /Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class:[/app/classes/com/example/javademo/HelleController.class]]togcr.io/tejal-gke1/skaffold-webflux-example:latest@sha256:36996a47d65f3e6b6818bbbeb88e6964298fa3a2a22b4c039b8ef13a150c5e1b  subtask=-1 task=DevLoop
DEBU[0037] getting client config for kubeContext: `gke_tejal-gke1_us-central1-c_dump-apis`  subtask=-1 task=DevLoop
DEBU[0037] Running command: [kubectl --context gke_tejal-gke1_us-central1-c_dump-apis exec skaffold-webflux-example-web-6b75c7d6d6-m4kkk --namespace default -c skaffold-webflux-example-web -i -- tar xmf - -C / --no-same-owner]  subtask=-1 task=DevLoop
DEBU[0038] Command output: [], stderr: tar: Removing leading `/' from member names  subtask=-1 task=DevLoop
Watching for changes...
DEBU[0038] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0038] could not stat dependency: stat /Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/src/main/jib: no such file or directory  subtask=-1 task=DevLoop
DEBU[0038] Found dependencies for jib maven artifact: [pom.xml src/main/java/com/example/javademo/.HelleController.java.swp src/main/java/com/example/javademo/DemoApplication.java src/main/java/com/example/javademo/HelleController.java src/main/resources/application.properties src/main/resources/application.properties]  subtask=-1 task=DevLoop
INFO[0038] files modified: [src/main/java/com/example/javademo/.HelleController.java.swp]  subtask=-1 task=DevLoop
DEBU[0038] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0038] Running command: [/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/mvnw --batch-mode jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=2.0.0 -Psync --non-recursive -DskipTests=true prepare-package jib:_skaffold-sync-map]  subtask=-1 task=DevLoop
DEBU[0040] Change detectednotify.Write: "/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst"  subtask=-1 task=DevLoop
DEBU[0040] Change detectednotify.Write: "/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst"  subtask=-1 task=DevLoop
DEBU[0040] Command output: [[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.javademo:javademo:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.projectlombok:lombok:jar -> duplicate declaration of version (?) @ line 47, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -----------------------< com.javademo:javademo >------------------------
[INFO] Building skaffold-webflux-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jib-maven-plugin:3.2.0:_skaffold-fail-if-jib-out-of-date (default-cli) @ javademo ---
[INFO] 
[INFO] -----------------------< com.javademo:javademo >------------------------
[INFO] Building skaffold-webflux-example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ javademo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ javademo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ javademo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ javademo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ javademo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jib-maven-plugin:3.2.0:_skaffold-sync-map (default-cli) @ javademo ---




BEGIN JIB JSON: SYNCMAP/1
{"generated":[{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/application.properties","dest":"/app/resources/application.properties"},{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/DemoApplication.class","dest":"/app/classes/com/example/javademo/DemoApplication.class"},{"src":"/Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/target/classes/com/example/javademo/HelleController.class","dest":"/app/classes/com/example/javademo/HelleController.class"}],"direct":[]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.160 s
[INFO] Finished at: 2022-05-23T12:45:47-07:00
[INFO] ------------------------------------------------------------------------
]  subtask=-1 task=DevLoop
TRAC[0040] dev intents: build true, sync true, deploy true  subtask=-1 task=DevLoop
DEBU[0040]  devloop: build false, sync true, deploy false  subtask=-1 task=DevLoop
Syncing 0 files for gcr.io/tejal-gke1/skaffold-webflux-example:latest@sha256:36996a47d65f3e6b6818bbbeb88e6964298fa3a2a22b4c039b8ef13a150c5e1b
Watching for changes...
DEBU[0041] Using wrapper for mvnw: mvn                   subtask=-1 task=DevLoop
DEBU[0041] could not stat dependency: stat /Users/tejaldesai/workspace/ops/skaffoldDemo/rxjavademo/src/main/jib: no such file or directory  subtask=-1 task=DevLoop
DEBU[0041] Found dependencies for jib maven artifact: [pom.xml src/main/java/com/example/javademo/.HelleController.java.swp src/main/java/com/example/javademo/DemoApplication.java src/main/java/com/example/javademo/HelleController.java src/main/resources/application.properties src/main/resources/application.properties]  subtask=-1 task=DevLoop
TRAC[0041] dev intents: build true, sync true, deploy true  subtask=-1 task=DevLoop
[skaffold-webflux-example-web] 
[skaffold-webflux-example-web]   .   ____          _            __ _ _
[skaffold-webflux-example-web]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[skaffold-webflux-example-web] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[skaffold-webflux-example-web]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[skaffold-webflux-example-web]   '  |____| .__|_| |_|_| |_\__, | / / / /
[skaffold-webflux-example-web]  =========|_|==============|___/=/_/_/_/
[skaffold-webflux-example-web]  :: Spring Boot ::                (v2.6.4)
[skaffold-webflux-example-web] 
[skaffold-webflux-example-web] 2022-05-23 19:45:49.407  INFO 1 --- [  restartedMain] com.example.javademo.DemoApplication     : Starting DemoApplication using Java 1.8.0_302 on skaffold-webflux-example-web-6b75c7d6d6-m4kkk with PID 1 (/app/classes started by root in /)
[skaffold-webflux-example-web] 2022-05-23 19:45:49.408  INFO 1 --- [  restartedMain] com.example.javademo.DemoApplication     : No active profile set, falling back to 1 default profile: "default"
[skaffold-webflux-example-web] 2022-05-23 19:45:49.872  INFO 1 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
[skaffold-webflux-example-web] 2022-05-23 19:45:49.897  INFO 1 --- [  restartedMain] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
[skaffold-webflux-example-web] 2022-05-23 19:45:49.908  INFO 1 --- [  restartedMain] com.example.javademo.DemoApplication     : Started DemoApplication in 0.567 seconds (JVM running for 28.838)
[skaffold-webflux-example-web] 2022-05-23 19:45:49.921  INFO 1 --- [  restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged
TRAC[0092] [port-forward] Forwarding from 127.0.0.1:8080 -> 8080  subtask=deployment/skaffold-webflux-example-web task=PortForward
[skaffold-webflux-example-web] 2022-05-23 19:46:39.860  INFO 1 --- [or-http-epoll-3] reactor.Mono.Just.1                      : | onSubscribe([Synchronous Fuseable] Operators.ScalarSubscription)
[skaffold-webflux-example-web] 2022-05-23 19:46:39.866  INFO 1 --- [or-http-epoll-3] reactor.Mono.Just.1                      : | request(unbounded)
[skaffold-webflux-example-web] 2022-05-23 19:46:39.869  INFO 1 --- [or-http-epoll-3] reactor.Mono.Just.1                      : | onNext(hello mono sync file test -)
[skaffold-webflux-example-web] 2022-05-23 19:46:39.876  INFO 1 --- [or-http-epoll-3] reactor.Mono.Just.1                      : | onComplete()
TRAC[0093] [port-forward] Forwarding from [::1]:8080 -> 8080  subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0094] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward
TRAC[0095] [port-forward] Handling connection for 8080   subtask=deployment/skaffold-webflux-example-web task=PortForward
```

A few observations, 
1) I saw another dev session got triggered even tough i changed only one file once. 
2) The first `skaffold dev` session i tried, the port-forwarding failed and hence the change was not reflected on locahost:8080. 
3) I gave it a 10 seconds more and I was able to see my change. 
4) I re-ran `skaffold dev` session with `--verbose=trace` flag to get more logs. This time, i changed the same file. I didnt see any failures.

**Comment by gsquared94** [comment]
Closing this due to no update from the reporter, and us not being able to repro.
