### ISSUE TITLE
Incompatible output directory with io_bazel_rules_docker v0.23

### ISSUE THREAD

**Issue by sashamor** [GoogleContainerTools/skaffold#7228]
### Expected behavior

`skaffold.yaml`

```yaml
build:
  artifacts:
  - image: reports
    bazel:
      target: //go/services/reports/cmd/server:server_img.tar
```

Expect that it builds & runs with `skaffold`.

### Actual behavior

`skaffold dev` gives:

```
Target //go/services/reports/cmd/server:server_img.tar up-to-date:
  bazel-out/k8-fastbuild-ST-4a519fd6d3e4/bin/go/services/reports/cmd/server/server_img.tar
INFO: Elapsed time: 84.321s, Critical Path: 54.36s
INFO: 572 processes: 210 remote cache hit, 30 internal, 332 linux-sandbox.
INFO: Build completed successfully, 572 total actions
INFO: Build completed successfully, 572 total actions
Building [reports]...
Build [reports] was canceled
build [reports] failed: reading image "/home/sasha/.cache/bazel/_bazel_sasha/ab67a788adc4b5b8d1470f6531fe3b59/execroot/__main__/bazel-out/k8-fastbuild/bin/go/services/reports/cmd/server/server_img.tar": open /home/sasha/.cache/bazel/_bazel_sasha/ab67a788adc4b5b8d1470f6531fe3b59/execroot/__main__/bazel-out/k8-fastbuild/bin/go/services/reports/cmd/server/server_img.tar: no such file or directory
```

It looks like it's expdecting `server_img` to be at `./bazel-out/k8-fastbuild/...`, but it's now at `./bazel-out/k8-fastbuild-ST-4a519fd6d3e4/...` since the latest `io_bazel_rules_docker` update.

### Information

- Skaffold version: v1.37.0
- Operating system: Linux workspace-678db7c888-t7jbq 5.4.0-1067-azure #70~18.04.1-Ubuntu SMP Thu Jan 13 19:46:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: paypaplane-dev-env
build:
  artifacts:
  - image: reports
    bazel:
      target: //go/services/reports/cmd/server:server_img.tar
```

### Steps to reproduce the behavior

1. Create skaffold project
2. `skaffold dev`
3. Above error.

**Comment by tejal29** [comment]
Thanks @sashamor. Dont think we have tested the bazel builder with the latest `io_bazel_rules_docker`.

Would love to get some community support to fix this.
