### ISSUE TITLE
Add a `skaffold show/status` to output runner information

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#726]
Skaffold currently takes the skaffold.yaml and converts it to a skaffold runner internally. The skaffold runner has information about which builder, deployer, and tagger were resolved from the config. It might be useful to output this information without actually running a dev/run. This could be useful for debugging the skaffold.yaml as it grows.

**Comment by balopat** [comment]
It was not implemented - #816 got closed as we didn't agree on an implementation yet.

**Comment by nkubala** [comment]
we have `skaffold diagnose`, and https://github.com/GoogleContainerTools/skaffold/pull/4048 is open for outputting the effective skaffold.yaml with activated profiles, so I'm going to close this issue.
