### ISSUE TITLE
[V2] Runtime error when running skaffold v2 binary. 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7262]
I see a runtime error when running v2 binary. 

error https://gist.github.com/tejal29/9fdca6d8a2d3159ab01861ffa88bb820

Steps to reproduce: 

1) checkout v2-v1.37.0 branch
2) LOCAL=true make
3) Go to getting-started examples. Run
```
skaffold dev -d <>
```

**Comment by gsquared94** [comment]
I'm not able to repro this issue. I tried:
- `amd64` host on `amd64` cluster
- `amd64` host on `arm64` cluster

However, the error trace you linked has this function call:
```
/Users/tejaldesai/go/pkg/mod/k8s.io/client-go@v0.21.3/plugin/pkg/client/auth/gcp/gcp.go:225
```
I wonder if it's something to do with connecting to the GCP cluster. Are you able to run this command directly?
```
kubectl --context <your cluster> describe nodes
```

**Comment by tejal29** [comment]
Will look into this today. 
/cc @aaron-prindle and @marlon-gamez Did you see this issue when you were running commands yesterday?

**Comment by aaron-prindle** [comment]
I did not see this issue when running commands yesterday, I will update this thread if I see this

**Comment by aaron-prindle** [comment]
I did not see this issue when running commands yesterday, I will update this thread if I see this

**Comment by tejal29** [comment]
This no longer exists. Something wrong with my cluster connection.
