### ISSUE TITLE
Update Golang-based examples to use go.mod

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#7265]
All of Skaffold's Go -based examples should use go.mod and probably be updated to the latest release of Go.

GOPATH builds create problems for Go debugging as the build-time filepaths are embedded into the binary and almost certainly don't map to the user's local file system.  For example, our [`examples/getting-started`](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started) uses a multistage build.  The build part uses the `golang:1.15` image:
https://github.com/GoogleContainerTools/skaffold/blob/ba6ba4f0415b331c9af9c135b010626bc3106dff/examples/getting-started/Dockerfile#L1-L5
The COPY command copies the source (`main.go`) from the user's workspace into the container's current directory (spolier: it's `/go`, which I determined by inspecting the image config, but neither the user nor us have any indication of this), and builds the app into a binary in the root as `/app`.

The second stage builds the deploy-time image, which uses a different base image (alpine:3):
https://github.com/GoogleContainerTools/skaffold/blob/ba6ba4f0415b331c9af9c135b010626bc3106dff/examples/getting-started/Dockerfile#L7-L12
The COPY command copies the built binary /app from the first stage into this otherwise-disconnected deploy image.

Connecting with dlv to the running result shows that the source files are believed to be in `/go`, even though the actual deploy-time image does not have a `/go`:
 ```
$ dlv connect localhost:56268
(dlv) sources
/go/main.go
/usr/local/go/src/errors/errors.go
/usr/local/go/src/errors/wrap.go
/usr/local/go/src/fmt/doc.go
```

Using Go modules, on the other hand, changes the file prefix to be relative to the module name.  This simplifies the debugger's life.

Cloud Code for IntelliJ requires use of Go modules.

----

Implementation notes:
- must be done to `integration/examples/` and `examples/`
- all go.mod should have unique module names: just append the example directory name.
    - `gopls`, the Go LSP, underpinning a lot of IDE tooling, has conniptions if it finds multiple go.mod files with the same module name

**Comment by johnmanjiro13** [comment]
I try to use go.mod in the Dockerfile, but prefix doesn't change.
Do you have any idea?

I create a go.mod and changed Dockerfile of the [`examples/getting-started`](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started) like below.

go.mod
```
module github.com/GoogleContainerTools/skaffold/examples/getting-started

go 1.18
```

Dockerfile
```Dockerfile
FROM golang:1.18 as builder
WORKDIR /getting-started
COPY main.go .
COPY go.mod .
```

And I ran these commands, the source files were believed to be in `/getting-started`.
```shell
$ skaffold debug

$ dlv connect localhost:56268
(dlv) sources
/getting-started/main.go
/usr/local/go/src/errors/errors.go
/usr/local/go/src/errors/wrap.go
/usr/local/go/src/fmt/errors.go
```

**Comment by briandealwis** [comment]
@johnmanjiro13 IIRC you need to have a `go.sum` too.  Run `go mod tidy` and then it should work!

**Comment by johnmanjiro13** [comment]
Thank you for your advice!

I set WORKDIR because `$GOPATH` is `/go` by default in the base image.
If I don't set it, go build fails with below message.
```
 > [builder 5/5] RUN go build -gcflags="all=-N -l" -o /app main.go:
#11 0.232 $GOPATH/go.mod exists but should not
```

> IIRC you need to have a go.sum too. Run go mod tidy and then it should work!

`go mod tidy` didn't generated a `go.sum` because main.go hadn't have any external dependency.
I added an empty `go.sum` by myself and retried, but prefix didn't change.
I did `go get` for adding some external package to the go.sum but it was same result 🤔

**Comment by briandealwis** [comment]
Oh! We need to build with `-trimpath`.  I didn't think this was required, but pretty clear from the doc:
```
        -trimpath
                remove all file system paths from the resulting executable.
                Instead of absolute file system paths, the recorded file names
                will begin either a module path@version (when using modules),
                or a plain import path (when using the standard library, or GOPATH).
```

**Comment by johnmanjiro13** [comment]
That makes sense. I was able to replicate your result! Thank you so much.
I will work on this issue.
