### ISSUE TITLE
Docker Compose support 

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#727]
Skaffold can understand docker-compose.yaml files by converting the build information to skaffold's docker builder and using `kompose` to convert docker-compose.yaml files to kubernetes resources.  How do we want to expose this functionality?

The current PR https://github.com/GoogleContainerTools/skaffold/pull/674 runs a docker-compose file directly.

Another way to do it is to just add this functionality to a different command that would output a `skaffold.yaml` files and the kubernetes resources.

**Comment by dlorenc** [comment]
I like the idea of a "skaffold init" command that would create a skaffald.yaml, possibly a user-level configuration and handle converting things like compose to k8s manifests.

**Comment by balopat** [comment]
closing in favor of #1195 and #1273.
