### ISSUE TITLE
Opening image tarball: open bazel-out/darwin../image.tar: no such file or directory

### ISSUE THREAD

**Issue by weivall** [GoogleContainerTools/skaffold#7281]
Skaffold build throws an error after upgrading to v1.38.0.
 
### Information
Dir structure:
```
└── skaffold.yaml
    └── backend/
        |── WORKSPACE
       └── cmd/
           └── api/    
               └── BUILD

```

- Skaffold version: v1.38.0
- Operating system: Darwin MacBook-Pro-5.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
    build:
      artifacts:
        - image: api
          context: backend
          bazel:
            target: //cmd/api:image.tar

```

```

DEBU[0001] Running command: [bazel build //cmd/api:image.tar --color=yes]  subtask=api task=Build
Loading:
Loading: 0 packages loaded
Analyzing: target //cmd/api:image.tar (0 packages loaded, 0 targets configured)
INFO: Analyzed target //cmd/api:image.tar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //cmd/api:image.tar up-to-date:
  bazel-out/darwin-fastbuild-ST-4a519fd6d3e4/bin/cmd/api/image.tar
INFO: Elapsed time: 0.376s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
DEBU[0001] Running command: [bazel cquery //cmd/api:image.tar --output starlark --starlark:expr target.files.to_list()[0].path]  subtask=api task=Build
DEBU[0001] Command output: [bazel-out/darwin-fastbuild-ST-4a519fd6d3e4/bin/cmd/api/image.tar
], stderr: Loading:
Loading: 0 packages loaded
Analyzing: target //cmd/api:image.tar (0 packages loaded, 0 targets configured)
INFO: Analyzed target //cmd/api:image.tar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.262s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions  subtask=api task=Build
DEBU[0001] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0002] Command output: [256
]                        subtask=-1 task=DevLoop
opening image tarball: open bazel-out/darwin-fastbuild-ST-4a519fd6d3e4/bin/cmd/api/image.tar: no such file or directory

```

**Comment by weivall** [comment]
I guess it could be related to https://github.com/GoogleContainerTools/skaffold/pull/7251 @sashamor

**Comment by weivall** [comment]
I found out that the issue happens with combination `bazel rules_docker-0.23.0 and skaffold v1.38.0`

**Comment by sashamor** [comment]
Hmm... I wonder if this is because `bazel-out` is a relative path, so it needs to be running from the same directory as the `bazel-out` folder.

What is the actual path to the `tar` file? Does `bazel-out/darwin-fastbuild-ST-4a519fd6d3e4/bin/cmd/api/image.tar` exist as Bazel is suggesting?

If the answer is the relative path issue, we'll need a way to figure out where the `bazel-out` directory is, then prepend that to the calculated directory.

**Comment by weivall** [comment]
> bazel-out/darwin-fastbuild-ST-4a519fd6d3e4/bin/cmd/api/image.tar exist as Bazel is suggesting?
yes, it is exists

**Comment by a9b3** [comment]
Just wanted to chime in, having the same issue when my skaffold.yaml was in a subdirectory but after I moved the skaffold.yaml to project root (next to bazel-out) it works.

**Comment by savage-engineer** [comment]
Notably the above seems to work, but setting the `context` of the build to the project root doesn't. This is a bit sticky when using Skaffold config files in subdirs with other steps that use relative paths for artifacts etc.

> Just wanted to chime in, having the same issue when my skaffold.yaml was in a subdirectory but after I moved the skaffold.yaml to project root (next to bazel-out) it works.

**Comment by tejal29** [comment]
Thanks @a9b3 for providing the input. Will tag this as an enhancement. 
We would love help around this.

**Comment by weivall** [comment]
with https://github.com/bazelbuild/rules_docker/releases/tag/v0.24.0 the was fixed for me

**Comment by arjantop-cai** [comment]
This is still an issue if bazel is configured to not create `bazel-*` symlinks. We have this disabled because of issues with `GoLand` (even if you exclude `bazel-*` directories it is still very slow to sync).

If the absolute path to the `.tar` is used it would resolve the issue.
