### ISSUE TITLE
Currently `skaffold run` does not run the `render` pipeline in V2 which is not expected

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7295]
Currently `skaffold run` does not invoke `skaffold render` which causes test breakages and is unexpected for users. In the past running `skaffold run` was a single iteration of `skaffold dev` but currently they differ in that `skaffold dev` invokes render and `skaffold run` doesn't.  This should likely be resolved s.t. `skaffold run` invokes the render phase

**Comment by tejal29** [comment]
This should be fixed by #7329

**Comment by MarlonGamez** [comment]
closing as this has been fixed on main
