### ISSUE TITLE
JSON Schemas using "wrong" schema key

### ISSUE THREAD

**Issue by Uzlopak** [GoogleContainerTools/skaffold#7298]
I use the json schemata to validate generated skaffold configurations. For this I use ajv. 

The json schemas use 
`http://json-schema-org/draft-07/schema#`
while ajv expects the $schema-Key to be 
`http://json-schema.org/draft-07/schema#`.

To get ajv to process the json schemas properly, I patch on the fly the JSON-Schema to use the correct $schema-key.

But still, it seems to be odd, that skaffold is providing the wrong $schema.

Is there a reason why skaffold does not use the correct url?
Should I create a PR?

**Comment by tejal29** [comment]
I am not sure why. We do have other team depend on this schema. At this time, we would not want to change this. 

However, I am going to publicize this internally and see if this has implication on partner integrations.

**Comment by tejal29** [comment]
Thanks @Uzlopak. Please feel free to create PR :)

**Comment by Uzlopak** [comment]
@tejal29 
done
