### ISSUE TITLE
Feature Request: Cache Skaffold GCB successful builds even when not all succeeded

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#7320]
### Expected behavior

I am running a complicated build with skaffold and Google Cloud Build - if even the very last build fails but the rest complete, I want all of those to be skaffold cache hits when i re-run the pipeline.

### Actual behavior

Currently, even if the last build fails, none of them get cached and I end up re-building 9 containers when I shouldn't have to.

I've also seen this with long-running builds (i.e. long tail builds), if my wifi flaps, the last build fails and I have to rebuild everything from scratch.

I have somewhat gotten around this by heavily leveraging Docker caching in GCB, but this still involves deploying a GCB worker, pulling down the previous container to get all the docker build cache hits. Would rather avoid this

### Information

- Skaffold version: v1.36.1
- Operating system:MacOS
- Installed via: homebrew
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

1. Start multiple GCB builds from the same `skaffold.yaml`
2. turn off laptop wifi or somehow trigger a fatal build failure so that skaffold exits

**Comment by tejal29** [comment]
duplicate on #5892

**Comment by tejal29** [comment]
filed by  @briandealwis on behalf of @dhodun

**Comment by dhodun** [comment]
Thanks! forgot about that one
