### ISSUE TITLE
Update skaffold documentation to have some relevant V2 related information - spefically a landing pager for Renderers

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7327]
Skaffold needs to update docs related to v2, specifically s/Deployer/Renderer

This is a requirement for the Cloud Deploy related documentation work

**Comment by tejal29** [comment]
This was also something that was brought by an internal partner. They would want to know more about rendering and types of renderer.

**Comment by aaron-prindle** [comment]
Done - https://skaffold-v2-latest.firebaseapp.com/
