### ISSUE TITLE
Running out of disk space very quickly

### ISSUE THREAD

**Issue by d11wtq** [GoogleContainerTools/skaffold#733]
I guess this is more of a question than an issue, since it's probably (?) out of scope for skaffold itself. I'm using minikube locally and I have a few nodejs services that are reasonably large due to the node_modules directory size. I'm finding that as I make changes I'm quickly running out of disk space due to an excess of docker images and stopped containers. Manually cleaning these up is cumbersome and tricky.

I do have the appropriate cache-maximizing logic in my Dockerfiles to avoid regenerating the docker image layers containing the node_modules (i.e. I add package.json and yarn.lock in isolation first, then I add the remainder of the source tree after running `yarn install`).

Any suggestions on how to deal with the garbage that quickly accumulates using `skaffold dev`?

I've allocated 40gb of disk space to minikube so I don't think allocating more space is a reasonable solution.

### Expected behavior

I can continue hacking on my project for days/weeks without problems.

### Actual behavior

After a few hours of hacking on my project, I run out of disk space in minikube.

### Information

- Skaffold version: git HEAD (0.7.0)
- Operating system: MacOS 10.12.16

**Comment by d11wtq** [comment]
Will work around this by running `docker system prune --force` regularly.

**Comment by dgageot** [comment]
Let's reopen the issue to provide a proper fix

**Comment by balopat** [comment]
cc https://github.com/GoogleContainerTools/skaffold/issues/61

**Comment by wstrange** [comment]
A `skaffold prune` , or equivalent would be really sweet...

**Comment by thebigredgeek** [comment]
This seems to still be an issue?

**Comment by nkubala** [comment]
@thebigredgeek that issue was fixed in https://github.com/GoogleContainerTools/skaffold/pull/4792, which will go out with our v1.16.0 release hopefully later this week
