### ISSUE TITLE
Skaffold cannot find private workerPool when using GoogleCloudBuild

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7340]
As per the [Changelog](https://github.com/GoogleContainerTools/skaffold/blob/main/CHANGELOG.md#v1330-release---10072021), a fix for private workerPool when using GCB was released in Oct in v1.33.0. 
The fix was this PR https://github.com/GoogleContainerTools/skaffold/pull/6666

This commit exists on the v1.38.0 tag. See [here](https://github.com/GoogleContainerTools/skaffold/commit/bc3824bc77e2a15521129603e47f0e34ff304621)

However, @ekupershlak mentioned this does not exist on v1.37.1.
https://github.com/GoogleContainerTools/skaffold/blob/v1.37.1/pkg/skaffold/build/gcb/cloud_build.go#L163

For this issue
1) Backporting the fix on v1.37.1
2) Verifying internal bug assigned to erik.

**Comment by ekupershlak** [comment]
I just wanted to clarify one minor point. PR #6666 looks like the correct change, but is a different change from the referenced ([commit](https://github.com/GoogleContainerTools/skaffold/commit/bc3824bc77e2a15521129603e47f0e34ff304621)). 

The changes in that commit are present in older branches, but I think the relevant change is to [cloud_build.go](https://github.com/GoogleContainerTools/skaffold/pull/6666/files#diff-dd1a90fc55f5fb8a4e3f1ec8cfaf8e009093d229d653b6e5d4452aa565b350e6), which is not present in the main branch.

**Comment by tejal29** [comment]
@ericzzzzzzz  Can you verify if the change is present on tag v1.37.1?

**Comment by ericzzzzzzz** [comment]
just checked the change in not available in v1.37.1

**Comment by tejal29** [comment]
Can you please backport this on main?
1) try cherry-pick the commit on the main branch
Once that is done, 
Please work with @aaron-prindle to cherry-pick the commit on v1.37.2 tag for releasing v1.37.2.
See go/skaffold-release#heading=h.pz6k23irwcio is you are curious about how to create hot fixes.

**Comment by ericzzzzzzz** [comment]
Will do.
