### ISSUE TITLE
Allow users to force deployment platform

### ISSUE THREAD

**Issue by edude03** [GoogleContainerTools/skaffold#7355]
Or detect M1 Macs and deploy amd64 images. 

When I try to run `skaffold run|dev` on an M1 mac running docker (I use buildpacks with google cloud build but I think this is relevant to all build tools anyway) it won't allow me to deploy as the images (built for amd64) aren't compatible with arm64. 

Typically, this is the case (you can't run amd64 images on arm64) but for mac m1 users with docker for desktop w/ qemu, it does of course work. 

Since it does work in practice, can a flag or setting be added to allow the deployment to continue anyway? Otherwise, skaffold is currently usable since we currently don't build arm64 images anyway. 

### Expected behavior

It shouldn't prevent me from deploying

It prevents me from deploying.

### Information

Funny side note, if you exit docker desktop, start the build then start docker again, it will work as its unable to check what platform it will be deployed to, which leaves me to believe it's an "artificial" limitation.

**Comment by aaron-prindle** [comment]
@gsquared94 can you add some context here on the feasability of adding this, how this might be done if so, and if it currently in the roadmap?  Thanks!

**Comment by gsquared94** [comment]
This definitely seems doable. We can probably convert this to a warning message instead of an error here:
https://github.com/GoogleContainerTools/skaffold/blob/f6bf562743f50b6ff9fa1371258ba9494294dcb8/pkg/skaffold/platform/resolver.go#L84-L88

**Comment by briandealwis** [comment]
Can we bump the priority on this?  Buildpacks builds used to work on M1, and this is affecting internal products (b/224003339).  Making this a warning seems like a good idea.

The difficulty here is that Docker Desktop now includes qemu-based [binfmt_misc extensions](https://docs.docker.com/desktop/multi-arch/) such that it can silently run binaries from other platforms.  But these capabilities are not surfaced into the Kubernetes cluster — a node can only claim it supports a single os/architecture.
