### ISSUE TITLE
feat(verify): add user configurable timeout to skaffold verify

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7366]
Currently the timeout for `skaffold verify` is hardcoded to 10minutes for each test.  This should be user configurable via the verify schema or a CLI flag to enable longer/shorter running tests if desired by the user

**Comment by renzodavid9** [comment]
The behaviour should be:
- Per default, no timeout
- If the user configures it, have a time out for docker and k8s verify test cases

We'll need to do an schema upgrade for this.
