### ISSUE TITLE
Add support for skaffold v1 and skaffold v2 docs on skaffold.dev page

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7367]
Currently skaffold is preparing it's first skaffold v2 release - `skaffold-v2-alpha-1`.  During this period where the skaffold team is improving skaffold v2 and there is a v1 and v2 split, the skaffold.dev page need to have appropriate documentation for both skaffold v1 and v2.  This issue tracks the effort to support this.

**Comment by techchickk** [comment]
For clarification, does this mean that you would like a copy of each page on both the Skaffold v1.0 and v2.0 sites? Everything on v1.0 on v2.0 and vice versa?

**Comment by aaron-prindle** [comment]
Sorry, this is actually already done but was not updated.  Closing this now
