### ISSUE TITLE
Re-enable publishing binaries from main branch

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7427]
As part of v2 feature work, we had disabled jobs to publish latest binaries on merge to master. 

As part of this, 

1) Re-enable the jobs that run and publish binaries as part of merge to master
2) Think about where do we wan to publish these
3) Any other thots. 
    a) Shd we create an alpha1 release? and mark it as pre-release?
         If we do that, what will go in the description.
         i.e which flows are working. What is not working etc.

**Comment by tejal29** [comment]
Team Meeting Discussion: 
> a) Shd we create an alpha1 release? and mark it as pre-release?
No.

**Comment by MarlonGamez** [comment]
This issue is finished now!

New binaries are being published to `gs://skaffold/builds/latest/v2`
