### ISSUE TITLE
Skaffold run/dev unable to detect local NPM repository but skaffold build works as expected

### ISSUE THREAD

**Issue by gitn00b1337** [GoogleContainerTools/skaffold#7441]
I have been unable to find logs so please copy the following git repo:
[https://github.com/gitn00b1337/skaffold-verdaccio](https://github.com/gitn00b1337/skaffold-verdaccio)

CD into the project, then run (requires helm + minikube + yarn):

```
$ sudo chmod -R a+rw ./verdaccio/storage 
$ yarn install 
$ minikube start
$ docker-compose up (seperate terminal)
$ skaffold config set --kube-context minikube local-cluster true
$ eval $(minikube -p minikube docker-env)
$ skaffold build
```

This works as expected. Now run:

`$ skaffold run`

Never connects to verdaccio locally

`$ skaffold dev`

Same issue as run.

### Expected behavior

I expect the same behavior when building whether standalone or part of run/dev.  I also expect to be able to connect to my host machine during the build step.

In the min repro i've left out quite a bit of stuff to get it "running". Correct/expected behaviour is for the build step to complete and the deploy to fail once it tries running the command.

### Actual behavior

Unable to connect to the host machine during build for run/dev. This is a blocking issue for me.

### Information

> - Skaffold version: v1.38.0
> - Operating system: 
>       Distributor ID: Ubuntu
>       Description:    Ubuntu 20.04.4 LTS
>       Release:        20.04
>       Codename:       focal
> - Installed via: curl
> - Contents of skaffold.yaml: in repro

**Comment by gsquared94** [comment]
can you provide the logs for `dev` and `run from running with `-v DEBUG` flag, after redacting anything sensitive?

**Comment by aaron-prindle** [comment]
I am attempting to go through the repro steps above, got:
```
aprindle@aprindle-ssd ~/skaffold-verdaccio  [master]$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.my-net value Additional properties are not allowed ('name' was unexpected)
```

Do you happen to know the fix here?  I didn't have a chance to read through `verdaccio` docs yet, hoping you might now the fix here off the top so I can repro this.  Thanks

**Comment by gsquared94** [comment]
Closing this issue due to lack of response. @gitn00b1337 if you find time to update on this issue we can reopen it.
