### ISSUE TITLE
Possible metrics breakage for new releases - Skaffold service account key generated from setup-secret.sh currently in the wrong directly - s/ secrets/key.json /assets/key.json

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7443]
With the change made in https://github.com/GoogleContainerTools/skaffold/pull/7339 Skaffold switched to using the `embed` package which embeds files at "assets/*".  Currently though our Makefile/CI-CD creates a secret file at secrets/keys.json so it's possible the key won't be added properly.  I believe the work to be done is changing to `secret/key.json` (and any other references) to `assets/key.json`
https://github.com/GoogleContainerTools/skaffold/blob/main/deploy/setup-secret.sh#L21

Without this change IIUC, this key will not be in our skaffold binary releases and we will not get any telemetry.

**Comment by aaron-prindle** [comment]
cc - @marlon-gamez @ericzzzzzzz

**Comment by ericzzzzzzz** [comment]
hey @aaron-prindle , if my understanding is correct, this script generates secrets then stores it to secrets/keys.json file? 

https://github.com/GoogleContainerTools/skaffold/blob/main/hack/generate-embedded-files.sh#L51 copies everything in secrets directory to fs/assets/secrets_generated folder, then keys.json should be embedded in the binary.

**Comment by aaron-prindle** [comment]
@ericzzzzzzz I see now thanks! In discussing w/ @marlon-gamez we thought this might be a possible error but it seems like there is likely no issues.

@marlon-gamez if you think that this will work as intended (seems it will as secrets/ is copied to assets/) we can close this.  I will wait ~1-2 days for any feedback and then close

**Comment by ericzzzzzzz** [comment]
run ``deploy/setup-secret.sh && make ``   then check fs/assets/secrets_generated should be able to verify the change

**Comment by aaron-prindle** [comment]
I think @marlon-gamez wanted to weigh in on this as they brought the potential issue to my attention but in my own attempts I believe this is ok from your comments above and checking via `deploy/setup-secret.sh && make`.  Closing this for now and we can have @marlon-gamez open it back up if there are additional concerns.  Thanks @ericzzzzzzz!
