### ISSUE TITLE
Request for local_arch & target_arch in BuildEvent

### ISSUE THREAD

**Issue by emmanuelbaah** [GoogleContainerTools/skaffold#7475]
### Request
With Skaffold now performing cross-architecture builds, the CC IDEs need to know the local and target architectures of their builds. It would be great if Skaffold could provide this information in the form of an event. The most obvious place to add such information would be to the BuildEvent. This way a new event doesn't need to be created and the IDEs, who already parse the BuildEvent, can consume the new information.

The following is a current example output of a build event:
```
buildEvent {
  artifact: "java-hello-world"
  status: "In Progress"
}
```
With the requested change, it would look more like the following:
```
buildEvent {
  artifact: "java-hello-world"
  status: "In Progress"
  local_arch:darwin/amd64
  target_arch:linux/amd64
}
```
This change will help facilitate CC supporting M1 users. Note that this change is required before CCIJ's M1 changes can go into the Insider's Build. (CCIJ blocked until done)

**Comment by gsquared94** [comment]
Completed in https://github.com/GoogleContainerTools/skaffold/pull/7550
