### ISSUE TITLE
Integrate v1 kpt into v2 Skaffold via migration path, any additional functionality necessary, etc

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7564]
V1 -> v2 kpt render and deploy - “what is the plan/requirements here for users upgrading”.  Might make sense to look at stats to see how many v1 users use kpt to see if this is high priority

**Comment by tejal29** [comment]
There are no kpt v1 users from the skaffold operation metrics. 
Closing this now.
