### ISSUE TITLE
 --hydration dir doesn’t work as expected in V2

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7568]
--hydration dir doesn’t work as expected IIUC: --hydration-dir=manifests doesn’t output manifests/manifests.yaml, still .kpt-pipeline/manifests.yaml

**Comment by renzodavid9** [comment]
With the latests changes in the [renderers logic](https://github.com/GoogleContainerTools/skaffold/pull/8365/files), we are not creating the `.kpt-pipeline` folder any more, and we removed the `--hydration-dir` flag. I'm closing this issue.
