### ISSUE TITLE
Provide actionable error message when cross-platform emulators are not setup

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#7576]
For doing cross-platform docker builds we need QEMU emulation support to be configured in the kernel using the `binfmt_misc` extensions. These extensions are installed by default with `Docker Desktop` while other installations, such as installing docker via `apt-get` on a normal Linux system, requires installing `binfmt_misc` support explicitly. 

When cross-platform builds fail due to platform mismatch errors like:
```
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ```
we should show the user steps to install QEMU emulation support manually.

**Comment by etanshaul** [comment]
one thing to consider is where exactly this message is injected in the event api stream (which is what the IDEs consume). We can coordinate to make sure we consume them properly.

**Comment by gsquared94** [comment]
this has been implemented and the actionable error message shows up in the IDE
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/39389231/194231473-573eae15-9a26-40b4-80bd-a9e13b9d419b.png">
