### ISSUE TITLE
Remove Kustomize deployer

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7597]
### Discussion
 - Kustomize deployer is not used in v2, and we've moved Kustomize manifests logic into generate.go should we remove Kustomize deployer?

**Comment by tejal29** [comment]
@ericzzzzzzz Can you verify if this is done already?

**Comment by ericzzzzzzz** [comment]
@tejal29  just verified.. kustomize deployer has already been removed, we can close this out.
