### ISSUE TITLE
Investigate multiple renders and possible issues w/ V2 related to that

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7606]
Currently multiple renderers are likely not supported by Skaffold V2.  More work needs to be done to investigate this but the likely solutions are:
- add multiple renderer functionality to Skaffold as a FR
- document any incompatibilites/lack-of-functionality using multiple renders at skaffold.dev and additionally create schema validations to make users aware of this

**Comment by aaron-prindle** [comment]
@tejal29 I believe you had some input here regarding the expectation of multiple renderers for V2 (perhaps this is working as intended atm?)

**Comment by MarlonGamez** [comment]
imo we should primarily support having one renderer per config, supporting multi config as the way to have multiple renderers. This would make it more clear on how to tie renderers to deployers and create a clear separation of what is handling what resources for the user

**Comment by aaron-prindle** [comment]
Talked offline w/ Marlon, as a short term item we can add likely a validation rule to prevent multiple renders from being used (even across multiple configs) as a way of minimizing work requried in the short term (addressing possible conflicting tmp dirs, flagging objects that are in scope for multiple renderers, etc.)

**Comment by aaron-prindle** [comment]
Marking as dupe of #7675 7675
