### ISSUE TITLE
V2 kpt renderer & deployer.  What is the status of these compared to Yuwen’s vision, what is the roadmap for these?

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7609]
Issue tracks investigating the current status of the v2 kpt renderer and deployer and validating it meets the functionality that @yuwenma initially set out to create.  Likely involves talking w/ Yuwen Ma and going through v2 kpt code to see if there are any gaps/missing-functionality

**Comment by MarlonGamez** [comment]
closing this issue as we have a better idea of where kpt stands in v2.
