### ISSUE TITLE
gRPC API

### ISSUE THREAD

**Issue by dallasvaughan** [GoogleContainerTools/skaffold#7616]
Documentation typo on https://skaffold.dev/docs/references/api/grpc/#v1skaffoldproto:

### Expected behavior
The link to the `skaffold.proto` file is https://github.com/GoogleContainerTools/skaffold/blob/main/proto/v1/skaffold.proto
### Actual behavior
The link to the `skaffold.proto` file is https://github.com/GoogleContainerTools/skaffold/blob/main/proto/v1/v1/skaffold.proto (extra `/v1` in the path)

**Comment by aaron-prindle** [comment]
Thanks for catching this @dallasvaughan!  I've submitted a fix here:
#7626
