### ISSUE TITLE
useHelmSecrets not decrypting on render

### ISSUE THREAD

**Issue by panbanda** [GoogleContainerTools/skaffold#7651]
### Expected behavior

`skaffold render` should produce the same output as `skaffold up` for secrets that are used with `useHelmSecrets: true`

### Actual behavior

`skaffold render` does not decrypt the secret, `skaffold up` does decrypt the secret

### Information

Demo repo here:

https://github.com/panbanda/skaffold-helm-secrets-issue

### Steps to reproduce the behavior

```
# Install SOPS sample gpg key
gpg --import pgp/sops_test_key.asc

# Encrypted with 
sops -e -i secrets.yaml

# Decrypted with 
sops -d -i secrets.yaml

# Skaffold dev puts the secret in container decrypted
# ie: test
skaffold dev

# Skaffold render creates a kube secret manifest with encrypted string
# ie: ENC[AES256_GCM,data:SyyH6w==,iv:CbNC...
skaffold render
```

**Comment by tejal29** [comment]
Thanks @panbanda. I am not aware or `skaffold up` do yo mean `skaffold dev`?

**Comment by anthonyalayo** [comment]
I have the same issue. Skaffold render should all the secrets as encrypted. Can this be fixed? Ideally `useHelmSecrets` would have had them decrypted.

**Comment by anthonyalayo** [comment]
Can anyone from the skaffold team chime in?

**Comment by anthonyalayo** [comment]
@aaron-prindle @tejal29 If someone could point me to where the change needs to happen, I could also give it a shot. Is there anyone around that would know?

**Comment by anthonyalayo** [comment]
Thanks @ericzzzzzzz !
