### ISSUE TITLE
[Multi-platform Support] Implement integration tests 

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#7661]
- [x] #7808
- [x] #7809
- [x] #7863
- [x] #7868

**Comment by aaron-prindle** [comment]
Currently there is a multi-platform integration test failure:
https://source.cloud.google.com/results/invocations/def964af-8d6e-4b51-b846-e2b298221b8f/targets/skaffold%2Fintegration%2Farm%2Fisplit_3/log

Awaiting a fix here then we can mark this issue complete.
