### ISSUE TITLE
Move Deploy Error codes to Render Error codes

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7662]
I was looking through some error proto codes. The convention of an error code is
`<Phase>_<Descriptive_Error>`

Now, that manifest manipulation happens in Render, we need to rename or add new error codes for some conditions e.g. 

    `DEPLOY_SET_LABEL_ERR = 1019;`

**Comment by tejal29** [comment]
Before, we take upon this work, Please contact CC engineer. The CC team relies on the "Phase" string. This change could break them.

**Comment by aaron-prindle** [comment]
@ericzzzzzzz this is related to the Cloud Code v1 -> v2 migration effort.  Assigning you for now as it is related to your prior investigation
