### ISSUE TITLE
Discussion what is the expected behavior for multi-renderers in single config projects

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7675]
### Description

multi-rendererer in one config not working, only one renderer config takes effect, looks like that the support for multi-renderer in one config never implemented from the conversation here. https://github.com/GoogleContainerTools/skaffold/issues/7606 ,  do we want to error out if multiple renders in one config. 

### Expected behavior
 - not sure what is the expected behavior.
   - should error out -- or add warning which renderer will be used ? 
   - should support multiple-renderers in one yaml config?
   - should document which renderers will take effect if multiple renderers configured 

### Actual behavior
 - only one renderer config takes effect if a skaffold.yaml contains multiple renderer configs

### Steps to reproduce the behavior

1. run  `skaffold render` in this  [multi-renderers-one-config-project](https://github.com/ericzzzzzzz/skaffold/tree/bug-bash-testing/examples/multi-renderer-one-config)
2. there are two renderers configured but the output is only for one renderer.

**Comment by ericzzzzzzz** [comment]
We want to support multiple-renderers except kpt

**Comment by aaron-prindle** [comment]
In the short term likely adding a validation rule that denies kpt + any other renderer will suffice and in the long term adding support is ideal

**Comment by tejal29** [comment]
Starting looking into this. Will update if I find any solution
