### ISSUE TITLE
skaffold render does not support overrides?

### ISSUE THREAD

**Issue by mcg1969** [GoogleContainerTools/skaffold#7687]
### Expected behavior

`skaffold render` should take into account not just the `setValues` entries but the `overrides` as well, just as `skaffold run` does.

### Actual behavior

The `overrides` section is not included in the generated `helm template` command.

### Information

- Skaffold version: v1.39.1
- Operating system: macOS Monterey / Minikube
- Installed via: skaffold.dev

I'm afraid I cannot share the contents of my skaffold.yaml. What I can share however is that the generated helm command looks as follows:

```
helm --kube-context minikube template <CHART_DIR> \
    <--set-string image.[NAME]=[TAG] commands for each image>
    <lots of --set commands for my setValues section>
    --namespace default
```

In contrast, the `skaffold run` command generates a temporarily file called `skaffold-overrides.yaml` and generates a helm command structured as follows:

```
helm --kube-context minikube install <RELEASE_NAME> <CHART_DIR> \
    --namespace default \
    <--set-string image.[NAME]=[TAG] commands for each image> \
    <lots of --set commands for my setValues section> \
     -f skaffold-overrides.yaml
```

**Comment by gsquared94** [comment]
Can you provide the `skaffold render` and `skaffold run` commands  along with the flags that you're executing?

**Comment by mcg1969** [comment]
Yep, just `skaffold run --namespace default` and `skaffold render --namespace default`.

**Comment by mcg1969** [comment]
I have found that `skaffold run --namespace default --render-only`, which is of course deprecated, does not supply the overrides either.

**Comment by jkleckner** [comment]
I was scripting some render operations and was frustrated that the `--kube-context` argument doesn't work with render.

I don't really want to modify my kube context globally just to perform a render.

**Comment by skrech** [comment]
I've encountered the same issue with Skaffold 2.1.0 as well. When using `skaffold render` `overrides` section in `deploy/helm/releases/<release-item>` doesn't seem to be applied, while using skaffold dev/run works as expected.
