### ISSUE TITLE
Provide a "skaffold upgrade" command

### ISSUE THREAD

**Issue by gtseres** [GoogleContainerTools/skaffold#775]
This is a feature request. It would be nice if skaffold provided a `skaffold upgrade` command that would upgrade skaffold itself to the latest release.

**Comment by r2d4** [comment]
Maybe ref #148

**Comment by gtseres** [comment]
Yes, thanks @r2d4 . I searched for "upgrade", so it didn't show up. I guess we can close this.

**Comment by r2d4** [comment]
I think they can be distinct - we can check for updates but also have a command to automatically upgrade you

**Comment by dlorenc** [comment]
I think we're going to skip doing the auto-upgrade of skaffold (that's the responsibility of the package manager). The update check command makes sense though. We could always help out by detecting what package manager installed skaffold and telling the user what commands to run.
