### ISSUE TITLE
`skaffold apply` does not support `--rpc-port` (and similar flags atm)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7756]
Currently `--enable-rpc` is deprecated atm and `skaffold apply` does not support `--rpc-port` meaning there is no acceptable way atm to setup the skaffold-server/watch-events with `skaffold apply`.  We should add `apply` to the list of commands which take the `--rpc-port` flag and similar flags (`--rpc-http-port`, etc.) and plumb them through so that when we eventually fully deprecate `--enable-rpc` there will not be any breaking workflows

**Comment by tejal29** [comment]
@OladapoAjala would you be interested in working on this?

**Comment by aaron-prindle** [comment]
Awesome!  I've assigned you this issue for now @OladapoAjala.  Feel free to ask any questions you might have in the issue thread here, thanks!

**Comment by OladapoAjala** [comment]
@aaron-prindle you can assign this now that I have commented on it.

**Comment by aaron-prindle** [comment]
Great, I've assigned the issue to you.  For more context here, currently skaffold apply  supports the --enable-rpc  flag which is deprecated but not the newer --rpc-port flag:
https://github.com/GoogleContainerTools/skaffold/blob/main/cmd/skaffold/app/cmd/flags.go#L210-L217
		Name:          "rpc-port",
...
		DefinedOn:     []string{"dev", "build", "run", "debug", "deploy", "test", "verify"}, // <--- no "apply" currently, needs to be added

I believe you will need to add `apply` to the `DefinedOn` values and possibly do additional plumbing but I think that might actually be it IIUC
