### ISSUE TITLE
Git tags for releases should be annotated

### ISSUE THREAD

**Issue by mattkelly** [GoogleContainerTools/skaffold#776]
Since git tags such as `v0.9.0` are actual releases, they should be annotated tags. Currently, all of them except for `v0.6.0` are lightweight tags, which are really just aliases for a commit:

```
skaffold ❯ git for-each-ref refs/tags
e265bb780f63894f649b8fb1ac53f8aaf89573b2 commit refs/tags/v0.1.0
eb0fd0223bb9ec640f1031bb8c9858ef22338e01 commit refs/tags/v0.2.0
0e9951cbab558661dcd189a0ccd8ed1d13a402f2 commit refs/tags/v0.3.0
8a99affded87a0f81e3ee90bd9f24f01aec5038d commit refs/tags/v0.4.0
a9b7884039ae50fbada04e5bdcaf9e43ddf0a3e4 commit refs/tags/v0.5.0
aa0ec1cf4e74a3a3e19bc3381f60ef8c9ec191ae tag    refs/tags/v0.6.0
71acd5d27b1f16f89047a02549818b887008ded3 commit refs/tags/v0.6.1
71021311d4f4db76044e5fcf8d862bd644744e79 commit refs/tags/v0.7.0
2d0ee1ef0e40bf9b032ce62e400f26373fa36e3b commit refs/tags/v0.8.0
7302a37b6e2d02c0a71d4079c944262381245277 commit refs/tags/v0.9.0
```

For example, it can be confusing when things like `git describe` don't behave as expected:

```
skaffold ❯ git checkout v0.9.0
Note: checking out 'v0.9.0'.
...
```

```
skaffold ❯ git describe
fatal: No annotated tags can describe '7302a37b6e2d02c0a71d4079c944262381245277'.
However, there were unannotated tags: try --tags.
```

You can read more about annotated vs. lightweight tags [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

I think if you tag something using GitHub then it's a lightweight tag. That might be what's going on here.

**Comment by r2d4** [comment]
Yeah I think this was just me being lazy. @dgageot did the v0.6.0 release :)

Is there a clean way to convert? Or should we just use annotated tags going forward?

**Comment by mattkelly** [comment]
Hmm, it seems that you can convert, but it might be a bit sketchy to [get the timestamps correct](https://stackoverflow.com/a/21032471/846956) and not confuse GitHub (I'm not sure if you can adjust release dates on GitHub, or how that would even work in general).

I would love if the existing tags could be fixed, but just making sure we use annotated tags moving forward is also great!

**Comment by dgageot** [comment]
:-)

**Comment by nkubala** [comment]
We're doing this for our release tags now.
