### ISSUE TITLE
Duplicate portforwards

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#7775]
### Expected behavior
Each service is port forwarded only once.
### Actual behavior
Some services are port forwarded multiple times.

### Information

There is the additional log line `could not map pods to service /go-guestbook-frontend/80: getting service /go-guestbook-frontend: an empty namespace may not be set when a resource name is provided` which seems to suggest a bug in: https://github.com/GoogleContainerTools/skaffold/blob/0029055060c6e588d8a29499e7367772fa8311ab/pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go#L188

### Steps to reproduce the behavior

1. Use the `cloud-code-samples/golang/go-guestbook` sample Github project
2. `skaffold dev -v info --port-forward --rpc-http-port 57208 --wait-for-deletions-max 2m0s --wait-for-connection --default-repo gcr.io/k8s-skaffold`
3. Build and deploy succeeds, but the portforward has duplicates for the `go-guestbook-frontend ` service.
```
Port forwarding service/go-guestbook-frontend in namespace , remote port 80 -> http://127.0.0.1:4503
Port forwarding service/go-guestbook-backend in namespace default, remote port 8080 -> http://127.0.0.1:8080
Port forwarding service/go-guestbook-mongodb in namespace default, remote port 27017 -> http://127.0.0.1:27017
Port forwarding service/go-guestbook-frontend in namespace default, remote port 80 -> http://127.0.0.1:4504
```

**Comment by aaron-prindle** [comment]
In attempting to repro this, I only see the correct # of portforwards:
```
Port forwarding service/go-guestbook-frontend in namespace default, remote port 80 -> http://127.0.0.1:4503
Port forwarding service/go-guestbook-backend in namespace default, remote port 8080 -> http://127.0.0.1:8080
Port forwarding service/go-guestbook-mongodb in namespace default, remote port 27017 -> http://127.0.0.1:27017

```

**Comment by aaron-prindle** [comment]
I am not able to reproduce this using Cloud Code + skaffold bin @ HEAD either:
https://paste.googleplex.com/5657545136930816

**Comment by aaron-prindle** [comment]
Talked w/ @gsquared94 offline and both of us were unable to repro this issue @ HEAD.  Marking closed, will re-open if we are able to reproduce this again
