### ISSUE TITLE
Add unit test coverage for util.RunCommand

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#78]
We should add info and debug level logging to this function also.  As we add more build and deploy implementations, we'll be using this a lot so it should have good test coverage.

To test exec.Command, we can shell out to the test binary like the std library does https://github.com/golang/go/blob/master/src/os/exec/exec_test.go#L33

We can also use the fake readclosers in our testutil package.

**Comment by yakovzaytsev** [comment]
All util.RunCommand does is call out to [Commander.RunCommand](https://github.com/GoogleCloudPlatform/skaffold/blob/master/pkg/skaffold/util/cmd.go#L54) Should I add tests to that one?

**Comment by r2d4** [comment]
Yep, thats the one I was referring to. That would be amazing!
