### ISSUE TITLE
skaffold should have warnings when using jib builder with --platform flag

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7820]
- run the following command against a mixed nodes cluster in this sample project https://github.com/ericzzzzzzz/skaffold/tree/main/examples/jib-gradle
 ```bash
skaffold build --platform linux/arm64,linux/amd64 --default-repo=xxxx --namespace xxx
```
 - the build will succeed but the build artifact is an amd64 image, before the base image configured here ``jib.from.image = 'gcr.io/google-appengine/openjdk:8'`` in build.gradle file is an amd64 image
 - Most likely skaffold will not inspect build.gradle future, so we probably want to show a warning like jib builder is used, --platform flag is ignored

**Comment by renzodavid9** [comment]
[This PR](https://github.com/GoogleContainerTools/jib/pull/3707) was created to change the behavior from Jib itself. The PR is already merged, we'll need to wait for the next release.

**Comment by gsquared94** [comment]
fixed in https://github.com/GoogleContainerTools/skaffold/pull/7831
