### ISSUE TITLE
Reuse tagpolicy in yaml

### ISSUE THREAD

**Issue by bhack** [GoogleContainerTools/skaffold#783]
Is there a way to consume tag assigned by the tagpolicy in other section of the artifact's yaml?

**Comment by dkirrane** [comment]
Yes I need same in order to pass it as a value into my helm chart

**Comment by bhack** [comment]
I think it is generally useful for gitops goals. Cause if you want to have something dynamic in the manifest and not strictly related to profiles you need to let it to be trackable. So tagpolicy gives a trackable anchor.

**Comment by lenlen** [comment]
I need the same feature too, more in detail I need to use the value of the tag in deployment with kustomize

**Comment by fovecifer** [comment]
I also need this feature
another option is skaffold could publish the tag name to some place

**Comment by balopat** [comment]
Currently we publish `IMAGE_NAME` that you can use in `deploy.helm.releases.setValueTemplates`: https://skaffold.dev/docs/how-tos/templating/

I am going to assume that this is fixed. If somebody doesn't agree, please reopen the issue!

**Comment by tejal29** [comment]
Related to https://github.com/GoogleContainerTools/skaffold/pull/2804/files#diff-81b7c8fde9b80eacae6769099d68df32R49
And closing this for real.
