### ISSUE TITLE
Cannot use helm deployer for mixed nodes cluster

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7839]
### Expected behavior
 not sure if it's something on helm or skaffold. Not sure if there is anything we can do about it. 

### Actual behavior
Running into error when deploy helm project 

### Information

- Skaffold version:  main
- Operating system:  macOS Monterey

### log
```bash
=== RUN   TestHelmDeploy
time="2022-09-02T13:00:39-04:00" level=info msg="Namespace: skaffoldgknmm" subtask=-1 task=DevLoop
    helper.go:259: Running [skaffold deploy --namespace skaffoldgknmm --default-repo gcr.io/k8s-skaffold --images gcr.io/k8s-skaffold/skaffold-helm] in testdata/helm
    helper.go:259: skaffold deploy: exit status 1, Tags used in deployment:
         - gcr.io/k8s-skaffold/skaffold-helm -> gcr.io/k8s-skaffold/skaffold-helm
        Starting deploy...
        Helm release skaffold-helm-skaffoldgknmm not installed. Installing...
        Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1beta1"
    panic.go:642: deploying "skaffold-helm-skaffoldgknmm": install: exit status 1
```

### Steps to reproduce the behavior

1.  connect to a mixed node cluster
2. change this https://github.com/GoogleContainerTools/skaffold/blob/main/integration/helm_test.go#L28 to arkIntegrationTest(t, CanRunWithoutGcp)
3. run the test.

**Comment by tejal29** [comment]
@ericzzzzzzz helm is a priority for us this cycle. Can we get to the root cause of this?

**Comment by ericzzzzzzz** [comment]
I'll look into this @tejal29

**Comment by ericzzzzzzz** [comment]
@tejal29 This is related to our hybrid cluster version which is on 1.24.2 and helmTest was using an older api (/apis/extensions/v1beta1/ingresses) for Ingress rules,  this version api was removed on v1.22, our old cluster for integration test is on v1.21, that's why it works on that cluster not for mixed nodes cluster, 
If we want a helm test against mixed nodes cluster, we need to ``apiVersion: networking.k8s.io/v1`` for ingress.yaml update related config fields, this is more like a user error.

**Comment by ericzzzzzzz** [comment]
This is an user error caused by ingress rule version not supported by k8s cluster, not an issue in skaffold, closing the issue.
