### ISSUE TITLE
Support TLS communication with Tiller

### ISSUE THREAD

**Issue by gtseres** [GoogleContainerTools/skaffold#785]
Currently skaffold does not support the communication with a Tiller pod where TLS is enabled. Just tried to run `skaffold dev` for the `helm-deployment` example and got the following:

```
WARN[0018] error retrieving helm deployment info: Error: transport is closing
```

This error takes place when one tries to communicate without TLS enabled with a Tiller that requires TLS, e.g.:
```
$ helm ls
Error: transport is closing
```

where when trying with TLS:
```$ helm ls --tls
NAME         REVISION    UPDATED                     STATUS      CHART             NAMESPACE
bold-hare    3          Wed Jun 13 13:38:46 2018    DEPLOYED    test-0.1.0    default
```

It would be great if support for communicating with Tiller over TLS could be added. #

**Comment by dlorenc** [comment]
From the helm docs:
https://github.com/helm/helm/blob/master/docs/tiller_ssl.md

It looks like we'd need to add support for the TLS parameters to the helm configuration object in Skaffold, then pass those on the command line.

**Comment by yeahphil** [comment]
Looked like #1284 would fix this, but after trying it, it doesn't. Unfortunately, Helm doesn't understand the --tls flag in commands like `helm dep build`, so we can't just set that flag globally and be done with it.

Proper helm TLS support looks like it will mean adding the argument in helm.go to every command that supports it as needed.

There's an easier way: helm supports configuring all aspects of it's TLS stuff via env vars. So if you can add --tls and it works, you can just `export HELM_TLS_ENABLE=1` and that should do the trick.

**Comment by tejal29** [comment]
The team is moving towards adding support for `helm3`, a `Tillerless`
As @yeahphil mentioned, there is way to support this via env variables. I am going to rank this at lowest priority.

**Comment by sryabkov** [comment]
Try `export HELM_TLS_ENABLE=true`

**Comment by tstromberg** [comment]
Sounds like there was a workaround.
