### ISSUE TITLE
skaffold ignores kustomizePath setting during cleanup

### ISSUE THREAD

**Issue by tomster** [GoogleContainerTools/skaffold#788]
### Expected behavior

when running `skaffold delete` using the kustomize deploy option with a `kustomizePath` setting like so:

```
deploy:
  kustomize:
    kustomizePath: base/
```

the resources defined there are deleted.

### Actual behavior

i got this error when running `skaffold dev`:

```
ERRO[0007] dev: dev step: first run: exiting dev mode because the first deploy failed: running kubectl: exit status 1 
Cleaning up...
WARN[0007] cleanup: kustomize: running kustomize build: Running [kustomize build .]: stdout , stderr: Error: open /home/tomster/Development/community-modbot/k8s/kustomization.yaml: no such file or directory
```
it seems to me it is ignoring the kustomizePath setting during cleanup but that's just a guess.

### Information

- Skaffold version: 0.9.0
- Operating system: ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  local: {}
  artifacts:
  - imageName: <redacted>
    workspace: ../
    docker: {}
deploy:
  kustomize:
    kustomizePath: base/
```

### Steps to reproduce the behavior

run `skaffold dev` and/or `skaffold delete`

**Comment by dgageot** [comment]
I believe this is fixed with #781
