### ISSUE TITLE
Update skaffold-v2.web.app, skaffold-v1.web.app and skaffold.dev to have banner explaining new V2 version and how to get to each docsite

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7910]
Issue tracks updating the skaffold-v2.web.app, skaffold-v1.web.app and skaffold.dev to have banner explaining new v2 Skaffold version and how to get to each docsite.  

The `docsy` theme that we use has docs here:
https://www.docsy.dev/

and docs versioning docs here:
https://www.docsy.dev/docs/adding-content/versioning/

Currently this `release version` support is enabled but it has poor affordance/visibility.  Would be great to dig into the theme to see how to customize this.  

I think the minimum work here would be to see how to add a banner at either the top of the main page(s) or all pages stating something related to:
"Skaffold v2 has been released (Oct ....)!  The Skaffold v2.0.0 docs are hosted at http://... and for older Skaffold v1 docs see http://...."

**Comment by maggieneterval** [comment]
@maggieneterval
