### ISSUE TITLE
Update skaffold.dev main page text and all mission statement related pages to be in line with new broader DevX mission (vs 2019 mission)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7911]
This bug tracks updating the skaffold.dev main page text and all mission statement related pages to be in line with new broader DevX mission (vs 2019 mission).  For example currently the skaffold.dev home page states - 
`Fast. Repeatable. Simple. Local Kubernetes Development.`

when the mission is broader now (container dev, cloudrun deploy, etc.).  Some broad ideas for things to add:
Skaffold V2 Updated Mission Statement & Core Identity

Kubernetes dev tool -> Container or Cloud Native developer tool

Integrations w/ Cloud Run, Cloud Deploy and Cloud Code

CI/CD use cases ++

Multi-platform support as a mission (build and deploy on all CPU architectures)

**Comment by maggieneterval** [comment]
@maggieneterval
