### ISSUE TITLE
Skaffold verify overrides container's env with host's env

### ISSUE THREAD

**Issue by quozd** [GoogleContainerTools/skaffold#7945]
Skaffold verify overrides container's env with host's env and fails to run container's commands due to invalid PATH, GOPATH and other environment variables.

Details:

Dockerfile
```
FROM golang:1.18
WORKDIR /src
COPY . .
CMD ["go", "test", "./..."]
```

Error
```
1 error(s) occurred:
* creating container in local docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "go": executable file not found in $PATH: unknown
```

`docker inspect <container>` if run via `skaffold verify -a build_artifacts.json`
```javascript
[
    {
        // ...
        "Config": {
            // ...
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/homebrew/bin:/Users/<redacted>/.go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
                "SHELL=/bin/fish",
                "GOPATH=/Users/<redacted>/.go"
                ...
            ]
            // ...
        }
        // ...
    }
]
```
It clearly contains PATH and other environment variables from my host machine.

`docker inspect <container>` if run via `docker run`:
```javascript
[
    {
        // ...
        "Config": {
            // ...
            "StdinOnce": false,
            "Env": [
                "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOPATH=/go"
                ...
            ]
            // ...
        }
        // ...
    }
]
```

I've fixed the issue simply by removing the [environment override](https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/verify/docker/verify.go#L220) in sources and it works fine now, but I'm not sure if there are any reasons behind this behaviour, so I didn't open a PR.

### Expected behavior

Verify container has container's default environment variables

### Actual behavior

Verify container has host's environment variables

### Information

- Skaffold version: v2.0.0-beta3-28-gb5ce32043
- Operating system: MacOS 12.4
- Installed via: skaffold.dev or local build
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3alpha1
kind: Config
build:
  artifacts:
    - image: test
      docker:
        dockerfile: Dockerfile
verify:
  - name: test
    container:
      name: test
      image: test
```

### Steps to reproduce the behavior

1. [a clonable repository with the sample skaffold project](https://github.com/quozd/skaffold-env-bug-demo)
2. `skaffold build -q > build_artifacts.json`
3. `skaffold verify -a build_artifacts.json`

Logs:
```
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v2.0.0-beta3-28-gb5ce32043 ConfigVersion:skaffold/v3alpha1 GitVersion: GitCommit:b5ce32043047b91205b398d9a1b4b539d4c673c4 BuildDate:2022-10-13T21:31:58Z GoVersion:go1.17 Compiler:gc Platform:darwin/arm64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Skipping update check for pre-release version  subtask=-1 task=DevLoop
INFO[0000] Loaded Skaffold defaults from "/Users/<redacted>/.skaffold/config"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /Users/<redacted>/skaffold-env-bug-demo/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
DEBU[0000] Defaulting deploy type to kubectl             subtask=-1 task=DevLoop
INFO[0000] map entry found when executing locate for &{test . <nil> {0x14000bb0840 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} []} of type *latest.Artifact and pointer: 1374391879360  subtask=-1 task=DevLoop
INFO[0000] Using kubectl context: docker-desktop         subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0000] Running command: [minikube version --output=json]  subtask=-1 task=DevLoop
DEBU[0000] setting Docker user agent to skaffold-v2.0.0-beta3-28-gb5ce32043  subtask=-1 task=DevLoop
INFO[0000] manifests hydration will take place in /Users/<redacted>/skaffold-env-bug-demo/.kpt-pipeline  subtask=-1 task=DevLoop
DEBU[0000] CLI platforms provided: ""                    subtask=-1 task=DevLoop
DEBU[0000] platform detection from active kubernetes cluster is not enabled  subtask=-1 task=DevLoop
DEBU[0000] platforms selected for artifact "test": ""    subtask=-1 task=DevLoop
DEBU[0000] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0000] push value not present in NewBuilder, defaulting to false because cluster.PushImages is false  subtask=-1 task=DevLoop
INFO[0000] build concurrency first set to 1 parsed from *local.Builder[0]  subtask=-1 task=DevLoop
INFO[0000] final build concurrency value is 1            subtask=-1 task=DevLoop
Tags used in verification:
 - test -> test:137d99c0f568bc460f8bc8b4ef662a268df0df1b69e561b4ba12f27dd25de577
DEBU[0000] push value not present in isImageLocal(), defaulting to false because cluster.PushImages is false  subtask=-1 task=DevLoop
DEBU[0000] Local images can't be referenced by digest.
They are tagged and referenced by a unique, local only, tag instead.
See https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works  subtask=-1 task=Verify
DEBU[0000] container test already present in local daemon: using test-2528b030 instead  subtask=test task=Verify
DEBU[0000] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0000] Command output: [256
]                        subtask=-1 task=DevLoop
1 error(s) occurred:
* creating container in local docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "go": executable file not found in $PATH: unknown
```

**Comment by aaron-prindle** [comment]
reopening, solution needs to support passthrough as well as keeping container ENVs.  Will investigate a more thorough solution here

**Comment by aaron-prindle** [comment]
@quozd thanks for flagging this.  This change was made and then undone as an early user relied on this functionality so more careful changes need to be made here to support them (vs the naive attempt I made prior - #7949 which was reverted).  I have added this item to the current milestone as I agree this is bad/difficult-to-work-around UX currently

**Comment by betaboon** [comment]
heya, I'm looking forward to using `verify` but this is completely preventing me from being able to do so.

any update on this?

**Comment by aaron-prindle** [comment]
Hi @betaboon I am in discussions with the the early adopter of `skaffold verify` which requested this feature and relies on it.  My plan in to allowlist the N env vars they pass through from the host OS -> verificiation container and them give them an allowlisted prefix to continue future dev.  Once this we can agree on the allowlist values, I can make the code change and this should be ok.  I am hoping for this to be done in the 1-2 weeks timeline.

**Comment by betaboon** [comment]
@aaron-prindle wouldnt it be more flexible to do the following:
- dont pass in any env-vars from the host by default
- add a setting (eg `hostEnvForward: true`) to forward all the env-vars (allowing to opt-in to current behavior for the early adopters)
- add a setting (eg `hostEnvVars: ["PATH", "GOPATH"]`) to forward individual env-vars (which might actually be useful eg for tokens and stuff)

**Comment by aaron-prindle** [comment]
Yes, sorry I should have enumerated the options better - currently I need to see if this internal early-adopter has the ability to change how they use/invoke Skaffold (I threw out the ones that would require them to change nothing).  I am definitely pushing towards options like the ones you have suggested as they are strictly better UX-wise (users configure the envs to pass themselves, the default is the more sane option, etc.) just need to make sure this internal user is able to set this up appropriately.  Appreciate the solutions above, thanks!

**Comment by ritsuki1227** [comment]
I have the same problem on skaffold v2.6.2.
