### ISSUE TITLE
Add link to https://github.com/GoogleCloudPlatform/solutions-template in Skaffold Docs

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7959]
Recently a GCP project templating tool has been created at https://github.com/GoogleCloudPlatform/solutions-template.  We should link this from the appropriate docs page in Skaffold (eg: tutorials, getting started,etc)

**Comment by techchickk** [comment]
Can we go ahead and resolve this one?

**Comment by aaron-prindle** [comment]
Marking as resolved, thanks @techchickk!
