### ISSUE TITLE
Please add a skaffold@1.39.3 brew formula

### ISSUE THREAD

**Issue by damien-swarm** [GoogleContainerTools/skaffold#7976]
Recently, skaffold 2.0.0 and the corresponding brew formula were released. Unfortunately, it will take us a little bit of time to update all our files to work with 2.0.0, so we'd like to stick with 1.39.3 for now.

However, one of our developers accidentally auto-updated skaffold via brew to 2.0.0, and brew [famously wants to make installing old versions as hard as possible](https://github.com/Homebrew/brew/issues/8791).

Since 1.39.3 is the latest v1 release, it would be helpful to separately `brew extract` that version as `skaffold@1.39.3` so it's automatically an installation candidate if a user needs it.

Edit: I also noticed there's a tag for 1.39.3 but no release, which is also confusing.

**Comment by aaron-prindle** [comment]
There is now a v1.39.3 release, there was in issue with our CI/CD which makes this released automatically but this is fixed now - https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.39.3.
