### ISSUE TITLE
update architecture diagram in v2 doc site

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#7983]
Skaffold v2 doc site is still using v1 architecture diagram, the diagram doesn't reflect current skaffold v2 implementations, this diagram should be updated. 
<img width="889" alt="Screen Shot 2022-10-25 at 5 25 57 PM" src="https://user-images.githubusercontent.com/102683393/197885294-f29a0176-a678-4996-b213-d9cf99e49f23.png">

**Comment by ericzzzzzzz** [comment]
- Render phase is missing,
 - Kustomize is no longer a deployer in v2

**Comment by paulbrai** [comment]
How do you use Kustomize if it is no longer a deployer?  That is not anywhere in the docs either.

**Comment by ericzzzzzzz** [comment]
Hi @paulbrai , you can put your kustomize configuration under manifests.. doc reference : https://skaffold-v2-latest.firebaseapp.com/docs/references/yaml/#manifests-kustomize 
here is an example project: https://github.com/GoogleContainerTools/skaffold/tree/main/examples/getting-started-kustomize

**Comment by aaron-prindle** [comment]
@paulbrai `Kustomize` is no longer a `Deployer` but is now a `Renderer` and the same functionality that existed prior still exists.  The docs @ericzzzzzzz explains the new schema and the new categories
