### ISSUE TITLE
Cannot connect to the Docker Damon via /var/run/docker. sock

### ISSUE THREAD

**Issue by lucidlips** [GoogleContainerTools/skaffold#7985]
### Expected behavior
Skaffold is able to connect to the docker daemon

### Actual behavior
Skaffold cant connect.

### Information
This is an issue with Docker but its affecting scaffold so I thought I would post here. A recent update to docker desktop for mac v4.13.0 does not add the required sym link to access to docker daemon at `/var/run/docker.sock`. I tested this with a clean install of v4.12.0 and verified this.

Creating the sym manually or rolling back to docker desktop v4.12.0 does resolve the issue. 

Docker issue is here: [Cannot connect to the Docker Damon via /var/run/docker. sock](https://github.com/docker/for-mac/issues/6536)

**Comment by aariacarterweir** [comment]
Just pasting the super quick workaround for affected users:

```
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

**Comment by aaron-prindle** [comment]
Closing as dupe of #7981
