### ISSUE TITLE
Example app giving warnings and there's no log output on MacOS High Sierra with Minikube and local Docker build

### ISSUE THREAD

**Issue by inadarei** [GoogleContainerTools/skaffold#799]
Getting an unexpected error when running `skaffold dev`

```BASH
→ gcloud alpha auth configure-docker
gcloud credential helpers already registered correctly.
user@localhost - /.../work/skaffold(master *=)
→ skaffold dev
Starting build...
Found [minikube] context, using local docker daemon.
Building [gcr.io/k8s-skaffold/skaffold]...
WARN[0001] Error processing base image for onbuild triggers: getting remote config: UNAUTHORIZED: "authentication required". Dependencies may be incomplete.
WARN[0001] Error processing base image for onbuild triggers: getting remote config: UNAUTHORIZED: "authentication required". Dependencies may be incomplete.
WARN[0001] Error processing base image for onbuild triggers: getting remote config: UNAUTHORIZED: "authentication required". Dependencies may be incomplete.
Sending build context to Docker daemon  78.92MB
Step 1/27 : FROM gcr.io/gcp-runtimes/ubuntu_16_0_4 as runtime_deps
 ---> 2b0ed236a672
Step 2/27 : RUN apt-get update &&     apt-get install --no-install-recommends --no-install-suggests -y         python-dev
 ---> Using cache
 ---> 1cfc6db128b8
Step 3/27 : ENV KUBECTL_VERSION v1.10.0
 ---> Using cache
 ---> 6b655ff08c6e
Step 4/27 : RUN curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl  &&     chmod +x /usr/local/bin/kubectl
 ---> Using cache
 ---> b940db2e76e9
Step 5/27 : ENV HELM_VERSION v2.8.1
 ---> Using cache
 ---> debcd79e286f
```
and there is no log shown when the example app eventually runs:

```BASH
Successfully built 271054dbf3bc
Successfully tagged 072126f7810d8f0585650c4a34eb7515:latest
Successfully tagged gcr.io/k8s-skaffold/skaffold:a6b0b93-dirty-271054d
Build complete in 4.863658572s
Starting deploy...
pod "skaffold" created
Deploy complete in 307.255341ms
Watching for changes...
```

The app is running and editing it does hot-reload, but again no logs and can't see logs via kubectl either:

```BASH
→ kubectl get pods
NAME       READY     STATUS    RESTARTS   AGE
skaffold   1/1       Running   0          4m
user@localhost - ~/
→ kubectl logs skaffold
user@localhost - ~/
```

### Expected behavior

1. No warnings after running `skaffold dev` for the example app
2. Logs would show repeating 'Hello world'
3. kubectl logs skaffold would also show logs

### Actual behavior

1. Warnings (see the beginning)
2. No logs in interactive mode
3. No logs via kubectl

### Information

- Skaffold version: v0.9.0
- Operating system: MacOS High Sierra 10.13.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold
    workspace: .
    docker:
      dockerfilePath: deploy/skaffold/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - deploy/skaffold/*
```

### Steps to reproduce the behavior

1. Docker for Mac (latest stable)
1. Vanilla installation of minikube on MacOS High Sierra with hyperkit (http://www.freshblurbs.com/blog/2017/05/21/Kubernetes-on-Mac.html)
2. Latest kubectl installed via Google Cloud Tools (with `gcloud components install kubectl`) instead of what is in the blog post
3. Checked-out skaffold and followed installation steps, tried to run the example go app with "skaffold dev"

**Comment by dgageot** [comment]
@inadarei Have you tried with the latest version of Skaffold?

**Comment by inadarei** [comment]
@dgageot tried with lates Skaffold + Kube from Docker4Mac and it worked like a charm.

Will try with the original minikube + latest Skaffold and report back. Thank you!

**Comment by balopat** [comment]
Hi @inadarei, please reopen this if you still see the issue, thank you!

**Comment by balopat** [comment]
hey @marcusnielsen yes, this seems like a different issue. Can you check on v0.15.0 that we released yesterday? If it's still there, do you mind opening another issue, also it would be great to have a reproducible example :)
