### ISSUE TITLE
skaffold v2.0.0 docs site has incorrect binaries (v1 binaries) at the `edge` releases

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7994]
Currently the skaffold documentation has links here:
https://skaffold.dev/docs/install/

![image](https://user-images.githubusercontent.com/1951658/198187559-547a5f54-b9ea-45a5-af1f-50ec4d2f3b37.png)

which state that skaffold edge builds can be downloaded at:
Linux x86_64 (amd64): https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-amd64
Linux ARMv8 (arm64): https://storage.googleapis.com/skaffold/builds/latest/skaffold-linux-arm64

These links are currently not correct (point to v1 bins from April 8th), we need to update our CI/CD pipeline and/or change the links so that the links there correctly point to skaffold `main` branch edge builds

**Comment by aaron-prindle** [comment]
Updated the binaries to be newer v2 binaries but it seems our CI/CD pipeline that handled this is no longer run on each release (last binary at the temp location of `skaffold/builds/latest/v2/*` is from 10/19/2022 when merges have taken place each day since (currently 10/26/2022(

**Comment by ericzzzzzzz** [comment]
the ci job has been failing since oct 19th due to ci go version is outdated, just upgraded ci go version, the issue should be fixed if everything goes well, we can double check that on next a few commits.

**Comment by ericzzzzzzz** [comment]
The fix is verified... closing this out.
