### ISSUE TITLE
Incorrectly (I assume, unless intentional) tagged commit may be misleading

### ISSUE THREAD

**Issue by tsilenzio** [GoogleContainerTools/skaffold#8055]
### Expected behavior

N/A

### Actual behavior

N/A

### Information

I noticed there is a tagged commit labeled [v2.2.3](https://github.com/GoogleContainerTools/skaffold/tree/v2.2.3) which appears to not be related to Skaffold v2. It could be misleading for people or software.

![Screen Shot 2022-11-08 at 1 44 23 PM](https://user-images.githubusercontent.com/1105413/200650196-cb02f14e-f1ee-41f6-8ed1-59206bbbc36d.png)

Homebrew for example has some code to specifically counter the tag:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/skaffold.rb#L17

### Steps to reproduce the behavior
N/A

**Comment by aaron-prindle** [comment]
Thank you for flagging this, this tag was a leftover from some prior testing and is not tied to a v2.2.3 release.  For the resaons  you mentioend above, the `v2.2.3` tag is now deleted.
