### ISSUE TITLE
Make Skaffold work without any local Docker registry credentials

### ISSUE THREAD

**Issue by laurivosandi** [GoogleContainerTools/skaffold#8099]
### Expected behavior

With remote build and deploy I would expect Skaffold to work without any locally configured Docker registry credentials.

### Actual behavior

With remote build and deploy the secrets to talk to Docker registry are stored in `kaniko-secrets`, yet Skaffold stlil touches local Docker registry credentials.

```
INFO[0054] Pushing image to harbor.codemowers.eu/laurivosandi-bimxb/hello-nodejs:e16db9f 
INFO[0066] Pushed harbor.codemowers.eu/laurivosandi-bimxb/hello-nodejs@sha256:ec919dbcf05664226ee722a125de4afcd931d4eb5f462051aa1481a9792f1e43 
Cleaning up...
 - No resources found
build [hello-nodejs] failed: getting image: GET https://harbor.codemowers.eu/v2/laurivosandi-bimxb/hello-nodejs/manifests/e16db9f: UNAUTHORIZED: unauthorized to access repository: laurivosandi-bimxb/hello-nodejs, action: pull: unauthorized to access repository: laurivosandi-bimxb/hello-nodejs, action: pull
```

I need to issue `docker login` on my workstation to make build pass correctly

### Information

- Skaffold version: v2.0.1-24-g8dc3b9bbd
- Operating system:Ubuntu 22.04.1 LTS
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-nodejs

manifests:
  rawYaml:
     - deployment.yaml

deploy:
  kubectl: {}

build:
  artifacts:
  - image: hello-nodejs
  cluster:
    dockerConfig:
      secretName: kaniko-secret
```

### Steps to reproduce the behavior

Remove local Docker credentials at `~/.docker/config` and try build+deploy on remote cluster with secured Docker registry.

**Comment by gsquared94** [comment]
right now, skaffold gets the built image digest this way
https://github.com/GoogleContainerTools/skaffold/blob/1a09eeee687beeb383b3b972139f32205d8feba4/pkg/skaffold/build/cluster/kaniko.go#L104
We could probably extract this from the build logs instead.

**Comment by nevill** [comment]
we also have this issue, even worse, we cannot access registry directly from local machine even with secret.

I dig into kaniko a bit, found `--digest-file=/dev/termination-log` can be useful @gsquared94 

quote from [kaniko](https://github.com/GoogleContainerTools/kaniko#flag---digest-file)

> Flag --digest-file
> 
> Set this flag to specify a file in the container. This file will receive the digest of a built image. This can be used to automatically track the exact image built by kaniko.
> 
> For example, setting the flag to --digest-file=/dev/termination-log will write the digest to that file, which is picked up by Kubernetes automatically as the {{.state.terminated.message}} of the container.

**Comment by nevill** [comment]
`pkg/skaffold/build/cache.cache#lookupRemote` also calls `docker.RemoteDigest`, have to find a way to do a in-cluster alternative.
