### ISSUE TITLE
Install error expected: 5ab3107c54242b39ea6f8d0c36f653f90e9dc0b5c37717e777e7b2475340a1f4

### ISSUE THREAD

**Issue by BrechtCorbeel** [GoogleContainerTools/skaffold#8122]
### Expected behavior

Install skaffold

### Actual behavior

// nothing

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

unsure

###################

I tried downloading and installing with the .exe and the package through scoop but it simply errors with scoop or gives a 1 sec black terminal with the .exe and then nothing

here is the scoop error:

skaffold-windows-amd64.exe ... ERROR Hash check failed!
App:         extras/skaffold
URL:         https://github.com/GoogleCloudPlatform/skaffold/releases/download/v2.0.2/skaffold-windows-amd64.exe#/skaffold.exe
First bytes: 4D 5A 90 00 03 00 04 00
Expected:    5ab3107c54242b39ea6f8d0c36f653f90e9dc0b5c37717e777e7b2475340a1f4
Actual:      7a1202a0674c7600d16b9f05c96185aaec01b6a1108b56891d0344dbf2dbd3a0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=skaffold%402.0.2%3a+hash+check+failed

**Comment by aaron-prindle** [comment]
Thanks for flagging this @BrechtCorbeel, we recently updated our CI/CD pipeline with some changes around how we sign our release binaries. I think these changes may have caused some issues here:

@ericzzzzzzz do you have any ideas what might be happening here?

**Comment by aaron-prindle** [comment]
I have confirmed that currnently our signed windows release binary has the correct sha value uploaded:
https://github.com/GoogleContainerTools/skaffold/releases/download/v2.0.2/skaffold-windows-amd64.exe
https://github.com/GoogleContainerTools/skaffold/releases/download/v2.0.2/skaffold-windows-amd64.exe.sha256

```
aprindle@aprindle-ssd ~/Downloads $ sha256sum skaffold-windows-amd64.exe
7a1202a0674c7600d16b9f05c96185aaec01b6a1108b56891d0344dbf2dbd3a0  skaffold-windows-amd64.exe
aprindle@aprindle-ssd ~/Downloads $ cat skaffold-windows-amd64.exe.sha256 
7a1202a0674c7600d16b9f05c96185aaec01b6a1108b56891d0344dbf2dbd3a0  skaffold-windows-amd64.exe
```

I believe our CI/CD process also released the unsigned binary accidentally prior to the signed binary.  I need to verify what the sha of that release (assuming it will be:
5ab3107c54242b39ea6f8d0c36f653f90e9dc0b5c37717e777e7b2475340a1f4)

**Comment by aaron-prindle** [comment]
Seems scoop has our hash as:

**Comment by aaron-prindle** [comment]
Submitted https://github.com/ScoopInstaller/Extras/pull/9792
hopefully this will resolve this

**Comment by aaron-prindle** [comment]
https://github.com/ScoopInstaller/Extras/pull/9792 was merged which should fix this, closing
