### ISSUE TITLE
About release 2.0.2

### ISSUE THREAD

**Issue by chenrui333** [GoogleContainerTools/skaffold#8159]
👋 Just curious if the 2.0.2 release got re-tagged? [Found the checksum mismatch](https://github.com/Homebrew/homebrew-core/actions/runs/3483459524/jobs/5826974652) when regression build, raising this issue to double confirm. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/116769

**Comment by aaron-prindle** [comment]
2.0.2 release was re-tagged (re-released). Initially a binary was uploaded that was not signed properly so the binary was re-uploaded after being signed correctly.  Sorry for the inconvenience, the binary + sha that is currently available in our Github release and at our cloud storage link :
https://storage.googleapis.com/skaffold/releases/v2.0.2/[skaffold-linux-amd64, ..., etc.]

 I have posted a similar comment to this on the issue you posted above, thanks for flagging this

**Comment by chenrui333** [comment]
Thanks for confirming it, appreciate it!
