### ISSUE TITLE
Need a means to exec externally and template the results

### ISSUE THREAD

**Issue by briantopping** [GoogleContainerTools/skaffold#8170]
It's quite common for builds to take information from the build environment. For instance, an instantiation of Skaffold from a Makefile may add environment variables very easily, and these environment variables can be templated for use within the `skaffold.yaml`.

This gets more complex in reuse situations, such as when a user wishes to run such a build directly from the command line. One process that works is to scrutinize the output of `make` and either export the variables or create a long command line that can be reused from shell history. It is annoying if the environment changes (such as with providing the Git hash for `HEAD`), but it's still doable.

Unfortunately, this becomes unworkable when used in IDE environments such as Cloud Code. At this writing, the current version of Cloud Code for VSC does not allow environment variables to be set unless they are passed in to the execution of the IDE itself. This is problematic in the previous case because `HEAD` will change but the environment variables set at the launch of the IDE mean the IDE needs to be relaunched to pick them up. If the build artifact tags in Skaffold come from this environment (such as with build `ldflags`), we are stuck.

### Expected behavior

Some discussion of the current and desired behavior is [here](https://kubernetes.slack.com/archives/CABQMSZA6/p1669654211969569). @aaron-prindle and I couldn't figure a generic way around the problem that would work with all tools and suggested I create a feature request.

Separation of concerns would ideally allow a `skaffold.yaml` to call out to external executables and capture the output. If the `git` executable could be called from within a Skaffold config, the output from it could be used as template input. It would not be up to the user to figure out a way that satisfies all tools in use and create a configuration that's not harmful to the next peer tool (IDE etc) that comes along with different constraints. 

In this use case, `${-git rev-parse --verify HEAD}` (note the dash, but any symbol would be fine) would allow the output of `git` to be dropped into a config via template/interpolation.

### Actual behavior

It's not that these issues are impossible in *most* cases, rather the constraints are tight enough that it (as described above) is impossible in *some* situations. 

### Information

- Skaffold version: v1.39.3
- Operating system: MacOS 13.0.1
- Installed via: Homebrew

### Steps to reproduce the behavior

See https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3115 for steps

**Comment by ericzzzzzzz** [comment]
I'm thinking about two options for supporting the request:
  - Defined a new stanza(vars) in skaffold.yaml file at the root level where users can directly define their skaffold session variables or run some command to assign values to those variables.  example config stanza looks like 
 ```yaml
  vars: 
     exec:
        - var1 : ["command",  "argument1", "argument2".. ]
```
  skaffold can run user-defined command during config parsing and then store it to somewhere like a map, and those values can be used for go templates in other stanzas in skaffold config, like {{.var1}} or {{vars.var1}}
 - alternatively, we could define a template function(cmd) https://pkg.go.dev/text/template#hdr-Functions -- similar to what we do here https://github.com/GoogleContainerTools/skaffold/pull/6136 , and users use the function in this template to define external command and skaffold will execute those commands while executing the parsed templates,   example template '{{cmd "bash", "-c", "xxx xx xxx"}}'

Although the first option would provide the power to store values and reuse them to different stanzas, this approach requires more design work and discussion, the second approach is intuitive and doesn't require much effort to implement and it's easier to learn(people are familiar with go template should be able to use this feature with very small documentation). I think The second approach is sufficient for the request ask, if we want to enable customized variables for skaffold session, we can  revisit this in the future.  What do you guys think ?

**Comment by briantopping** [comment]
Hi @ericzzzzzzz, hope your holidays were relaxed and enjoyable :-) Apologies I missed your inquiry above! 

Pretty sure this will resolve what we were looking for. I'll do the needful to get converted over to v2. I presume this will more than cover requirements we have. Timing is perfect, thank you for your quick response here!

**Comment by ericzzzzzzz** [comment]
@briantopping  thank you!

**Comment by renzodavid9** [comment]
[Ignore] Making triage bot happy

**Comment by briantopping** [comment]
Hi @ericzzzzzzz, sorry to necro this. We got converted to v2 and I am getting back to this.

The template that I am using calls a shell script, the output is a newline-separated list of `ldflags`. The assignment for the flags is [here](https://github.com/GoogleContainerTools/skaffold/blob/d2732961a8dbdf251c5bc21bfdd4cdd9ce806e27/pkg/skaffold/build/ko/builder.go#L98) but it's defined as a `StringArray` [here](https://github.com/GoogleContainerTools/skaffold/blob/3a3c3a34e2c58a81dee4c0815be80fc13b987d92/vendor/github.com/google/ko/pkg/build/config.go#L79).

I have been playing around with a local fork that has Sprig linked in, that gives me the ability to write something such as this:
```yaml
      ldflags:
      - '{{ cmd "bash" "-c" "hack/get-build-ld-flags.sh" | splitList "\n" | toJson }}'
```

The problem is go templates are designed to render a string. If the string doesn't have parsable structure, then it's pretty tricky to turn it back into a list for something like ldflags. 

You can see the WIP I created for this [here](https://github.com/GoogleContainerTools/skaffold/compare/main...briantopping:skaffold:ldflags). Basically it tries to parse the results of the template with `json.Unmarshall()` and just takes the string as is if it fails. I'm not that happy with it, it has a lot of dependencies on the template serializing as JSON and the result has to be a list of strings, which isn't very versatile.

Thoughts?
