### ISSUE TITLE
Actionable error message for docker running in a non-default socket

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#8190]
If docker is setup on a different socket than `unix:///var/run/docker.sock`, then Skaffold will error like this:
```
getting imageID for <image id-dirty>: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
```

The error message should also suggest the user to set DOCKER_HOST environment variable to the correct socket path.

**Comment by ericzzzzzzz** [comment]
We will support deducing docker host from docker context, this issue is no longer needed.
