### ISSUE TITLE
Skaffold Sync only triggers after a while

### ISSUE THREAD

**Issue by rstoermer** [GoogleContainerTools/skaffold#8203]
### Expected behavior
Before v2 Skaffold did the sync instantly after a change in code was made

### Actual behavior
Since 2.0 the sync takes a variable time, usually > 10 Seconds. I don't know if this is intentional. I didn't read about this change and couldnt find an option in the API to configure this.

### Information

- Skaffold version: 2.0.3
- Operating system: OS X latest
- Installed via: Homebrew
- Contents of skaffold.yaml:

More than 12 Skaffold'ed services produce this behaviour. I can provide an example if this is not intentional :)

**Comment by renzodavid9** [comment]
Hi @rstoermer. Thanks for reporting this. It looks like we have another similar issue #8166. And yes, if you have an example repro project you can share it will be great. Thanks!

**Comment by rstoermer** [comment]
The issue you linked is the exact same problem that I experienced, so we can close this one here.
