### ISSUE TITLE
[err msg] Skaffold doesn't point to Kustomize file giving error

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8218]
(text below is copied from analysis by @briandealwis )

Skaffold user @palladius has an interesting problem where they made a mistake in a kustomize.yaml file (didn't comment out the earlier KRM headers), but Skaffold's error messages made it very difficult to diagnose the problem. The problematic file is:

https://github.com/palladius/vanilla-app/blob/085bdc88368bf20067f45475c715b6351248897c/deploy/k8s/overlays/dev/kustomization.yaml

You can reproduce with (replace minikube with your context):

$ git clone https://github.com/palladius/vanilla-app/
$ git reset --hard 085bdc88368bf20067f45475c715b6351248897c
$ skaffold dev -p dev --kube-context minikube
Listing files to watch...
 - sku-vanilla-app-image
Cleaning up...
 - No resources found
listing files: yaml: unmarshal errors:
  line 18: mapping key "apiVersion" already defined at line 1
  line 19: mapping key "kind" already defined at line 2
  line 20: mapping key "resources" already defined at line 4
  
It looks like pkg/skaffold/render/generate/util.go's DependenciesForKustomization could report a bit more detail in the unmarshal error?

**Comment by palladius** [comment]
I can't assign to myself but I'll nonetheless start working on this. `[b-261818134]`

**Comment by palladius** [comment]
https://github.com/GoogleContainerTools/skaffold/pull/8220 should hopefully fix this.

Thanks Brian for guidance.

**Comment by palladius** [comment]
Note: I've also added error 1201 according to the contribution guide on actionable feedback. (Unless we want to create a brand new Kustomize error message, which would make sense. Saw plenty of Helm messages, but zero specific Kustomize ones).

As per [my interpretation of the docs] in: https://github.com/GoogleContainerTools/skaffold/blob/main/DEVELOPMENT.md#adding-actionable-error-messages-to-code

**Comment by aaron-prindle** [comment]
Assigned this to @palladius

**Comment by palladius** [comment]
Aaron, anything missing in my error message ?

**Comment by palladius** [comment]
Aaron, LGTM.

**Comment by aaron-prindle** [comment]
Fixed with #8220, closing
