### ISSUE TITLE
kubectl manifests option has not documented

### ISSUE THREAD

**Issue by johnmanjiro13** [GoogleContainerTools/skaffold#8224]
### Expected behavior

kubectl manifests option in a skaffold.yaml is documented.

### Actual behavior

kubectl manifests option in a skaffold.yaml has not documented.

### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

The `kubectl` deploy type of skaffold.yaml has a `manifests` option.
https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/schema/v2beta29/config.go#L581-L583

However, the option has not documented in the [kubectl document page](https://skaffold.dev/docs/pipeline-stages/deployers/kubectl/).

I don't know how to add the option to the document.

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by ericzzzzzzz** [comment]
Hi @johnmanjiro13, schemas before v3 including v2beta29 were created based on skaffold v1 architecture, so the documentation you're looking for in in v1 doc website .. https://skaffold-v1.web.app/docs/pipeline-stages/deployers/kubectl/ , you can choose documentation version from our main docs site as well at the ``version`` drop down menu.

**Comment by johnmanjiro13** [comment]
That makes sense.
I could see the `manifests` option in v1 doc website, thank you!

By the way, will we configure manifest files with `flags` like `-f deployment.yaml` after v3 schema?
