### ISSUE TITLE
Add Skaffold Neos tutorial to skaffold.dev page

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8228]
Recently @maggieneterval created a Skaffold Neos tutorial to allow new users to easily use skaffold via GCP + Cloud Shell and learn Skaffold commands, principles, and functionality.  This issue tracks adding a link/explanation regarding this Skaffold Neos tutorial to the skaffold.dev site

**Comment by maggieneterval** [comment]
Thanks @aaron-prindle! I was thinking we could either:

1. Add a new page under [Tutorials](https://skaffold.dev/docs/tutorials/) that includes an "Open in Cloud Shell" link to the new tutorial.
2. Replace the existing [Quickstart](https://skaffold.dev/docs/quickstart/) with the new tutorial, copying the tutorial text into the Standalone section and replacing the link in the Cloud Shell section.

Any preference?

**Comment by aaron-prindle** [comment]
Are these exclusive?  I think adding the information in both places seems like it would be the best for users currently (more visibility to our most up-to-date & easily-acceptable way of getting onboarded & understanding Skaffold)

**Comment by maggieneterval** [comment]
SGTM!
