### ISSUE TITLE
Make it possible to disable enforced namespace when rendering with `kubectl`

### ISSUE THREAD

**Issue by bsideup** [GoogleContainerTools/skaffold#8233]
### Expected behavior

A flag that would allow skipping setting the namespace while rendering the manifest.

### Actual behavior

The namespace is always set, either to the current namespace from `kubectl` or the default value.

### Information

- Skaffold version: Latest (2.0.3)
- Operating system: Any
- Installed via: skaffold.dev

### Context

We want to use Skaffold to render a manifest that will later be installed into multiple namespaces (GitOps style).

Right now, Skaffold will force the namespace to be set **at the render stage**, making it impossible to use the rendered manifest without some post-processing that would remove the enforced namespace.

**Comment by bsideup** [comment]
Submitted a draft PR to demonstrate one of possible solutions:
https://github.com/GoogleContainerTools/skaffold/pull/8234

**Comment by aaron-prindle** [comment]
Related - https://github.com/GoogleContainerTools/skaffold/issues/8186

**Comment by bsideup** [comment]
@aaron-prindle ohhh, thanks for sharing! I did not expect it to be a regression, but a feature. If previously it wasn't the behavior, I will be more than happy if, by default, Skaffold will not force any namespace unless specified 👍

**Comment by bsideup** [comment]
Update: after reading the linked issue more carefully, I realized that `--offline` flag does exactly what I needed and skips adding the namespace (in the latest release).

I consider my use case solved, assuming that #8186 will be addressed before the next release, but I will leave the issue open in case the new behavior is desired and the flag will still be needed. Thank you!

**Comment by aaron-prindle** [comment]
Going to close this, tracking changing the default behaviour to be the same as `--offline=true` in this issue: 
https://github.com/GoogleContainerTools/skaffold/issues/8318
