### ISSUE TITLE
Add `skaffold debug` support for Python 3.11

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8242]
Issue tracks adding `skaffold debug` support for Python 3.11.  
Related: https://github.com/GoogleContainerTools/container-debug-support/issues/121

**Comment by ericzzzzzzz** [comment]
example https://github.com/GoogleContainerTools/container-debug-support/pull/101

**Comment by cheburakshu** [comment]
I filed a bug report here. Thanks for adding support 👍 

https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/735

**Comment by aaron-prindle** [comment]
This same PR MUST also update the `skaffold debug` docs to explain that Python 3.11 is now supported

**Comment by ericzzzzzzz** [comment]
closing due to this is complete.

**Comment by astellingwerf** [comment]
I'm confused now: [Documentation](https://skaffold.dev/docs/workflows/debug/) still indicates that support for the 1.5 year old version of Python 3.11 is planned and coming soon but not present. Is it or not?
