### ISSUE TITLE
Skaffold should publish major/minor branches and cut releases from that vs only tag branches

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8275]
context:
https://kubernetes.slack.com/archives/CABQMSZA6/p1671648964467299

Users find it difficult when following versions with multiple patch releases what is changing between them as well as how the commits map to `main`/PRs with our current release tagging policy (only a tag is created).  It likely makes sense to have a branch for each major/minor release that we can cut patches from - this is essentially what we try to do with our current flow but there is no single branch currently

**Comment by betaboon** [comment]
now with the `2.1.0`- and the `1.39.5`-releases you seem to have switch to this behavior. thank you very much.

thus i believe this can be closed?
