### ISSUE TITLE
Skaffold 2.0 Documentation

### ISSUE THREAD

**Issue by JulyMoon87** [GoogleContainerTools/skaffold#8282]
### Information

- Skaffold version: 
- Operating system: 
- Installed via: 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

https://github.com/GoogleContainerTools/skaffold

**Comment by aaron-prindle** [comment]
Closing this for now - feel free to re-open with additional context related to the issue you were having with the Skaffold 2.0 Documentation, thanks!
