### ISSUE TITLE
Add contributors for each release to changelog

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#829]
Let's thank all the contributors in the changelog for each release.

`git log "${LAST_RELEASE_TAG}".. --format="%aN" --reverse | sort | uniq | awk '{printf "- %s\n", $0 }'`

And first I'd like to thank docker/machine and @dgageot for giving us this idea :)

https://github.com/docker/machine/blob/66183198cd3ade76dbf47ed4ab1ebfb8908008a9/script/release.sh#L136-L138

**Comment by dgageot** [comment]
ping @balopat. I updated v0.11.0 release page with the names of the contributors. How can we not forget next time we do a release?

**Comment by balopat** [comment]
Thanks @dgageot, this was not on my radar. I think we should add it to the release note generator script.  I'll add this to this week's todo so that we don't forget about it!

**Comment by dlorenc** [comment]
Does release documentation exist anywhere?
