### ISSUE TITLE
Document skaffold's go template functions (namely  #8269 cmd execution)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8301]
Skaffold should add an additional docs page (or section under template values) that shows all of skaffold's template functions - esp.  the `cmd` template from
https://github.com/GoogleContainerTools/skaffold/pull/8296

Might make sense to callout:
- command is not re-run on recompilation (only first pass)
- how this might affect idempotency
- what security risk there might be from using this template fxn

**Comment by ericzzzzzzz** [comment]
related https://github.com/GoogleContainerTools/skaffold/issues/7345
