### ISSUE TITLE
Ignore tag in skaffold.yaml and kubernetes yaml

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#834]
I think this worked once upon a time, but it doesn't anymore.

We should allow users to specify a tag in the skaffold.yaml or their kubernetes.yaml and

1. If we built the image, ignore it and replace it with our intermediate tag
2. If we didn't build the image, don't do anything.

**Comment by dgageot** [comment]
@r2d4 I don't know. There are cases where I need to have two version of the same artifact deployed (think blue/green) one is the dev version that skaffold is handling. The other one is a previous version that Skaffold shouldn't handle.
