### ISSUE TITLE
Architecture and Design

### ISSUE THREAD

**Issue by rana-ian-intel** [GoogleContainerTools/skaffold#8371]
### Expected behavior

Expect to see an image named `workflow_local`,

### Actual behavior

Image url is incorrect.

![image](https://user-images.githubusercontent.com/97198581/214960005-6607aaa5-a62c-45e5-822e-c76a22a4e46a.png)

### Information

Missing documentation image on public website.

### Steps to reproduce the behavior

Visit https://skaffold.dev/docs/design/

**Comment by aaron-prindle** [comment]
Thanks for flagging this, not sure what happened here when you encountered this but it seems this is correct now as of 2/13/203 (at least when I view the docs, image below)

![image](https://user-images.githubusercontent.com/1951658/218560729-4ef2dcad-65b6-41f5-b49b-c7f725627e37.png)

Going to close this for now, please re-open if this is still happening for you.  Thanks
