### ISSUE TITLE
Raw kubernetes deployment not deployed when under profile

### ISSUE THREAD

**Issue by mkdirJava** [GoogleContainerTools/skaffold#8378]
### Expected behavior
Given the skaffold.yaml
```
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: test
profiles:
  - name: dev
    manifests:
      rawYaml:
        - dev/smtp.yaml
requires:
  - path: base


```

When I execute the command
``` skaffold dev -p dev```

Then I expect the smtp.yaml to be deployed to the kubernetes cluster 
This is strange as the command

``` skaffold render -p dev ``

Shows the smtp deployment

### Actual behavior

The smtp.yaml is not deployed

### Information

- Skaffold version:  v2.1.0

- Operating system:  Ubuntu 20.04
- Installed via:  Standalone binary from : https://skaffold.dev/docs/install/#standalone-binary
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: test
profiles:
  - name: dev
    manifests:
      rawYaml:
        - dev/smtp.yaml
requires:
  - path: base

```

### Steps to reproduce the behavior

Git Repo:  https://github.com/mkdirJava/skaffold-issue

1. skaffold render -p dev
2. skaffold dev -p dev  -vdebug
3. kubectl get po -w

DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v2.1.0 ConfigVersion:skaffold/v4beta2 GitVersion: GitCommit:c037d6f51276e178a2c05c1c59665956ff34aa4c BuildDate:2023-01-23T09:57:08Z GoVersion:go1.19.1 Compiler:gc Platform:linux/amd64 User:}  subtask=-1 task=DevLoop
INFO[0000] Loaded Skaffold defaults from "/home/origin/.skaffold/config"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /home/origin/mkdirdev/skaffold-issue/skaffold.yaml  subtask=-1 task=DevLoop
INFO[0000] applying profile: dev                         subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Build  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field artifacts  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field insecureRegistries  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field tagPolicy  subtask=-1 task=DevLoop
INFO[0000] no values found in profile for field TagPolicy, using original config values  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field platforms  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field BuildType  subtask=-1 task=DevLoop
INFO[0000] no values found in profile for field BuildType, using original config values  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Test   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Render  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Generate  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field rawYaml  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field remoteManifests  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kustomize  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field helm   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kpt    subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field hooks  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field before  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field after  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field transform  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field validate  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field output  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Deploy  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field DeployType  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field docker  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field helm   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kpt    subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kubectl  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field cloudrun  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field statusCheck  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field tolerateFailuresUntilDeadline  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field kubeContext  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field logs   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field prefix  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field jsonParse  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field fields  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field -      subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field PortForward  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field ResourceSelector  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field allow  subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field deny   subtask=-1 task=DevLoop
DEBU[0000] overlaying profile on config for field Verify  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
DEBU[0000] config version out of date: upgrading to latest "skaffold/v4beta2"  subtask=-1 task=DevLoop
DEBU[0000] parsed 1 configs from configuration file /home/origin/mkdirdev/skaffold-issue/base/skaffold.yaml  subtask=-1 task=DevLoop
DEBU[0000] Defaulting build type to local build          subtask=-1 task=DevLoop
INFO[0000] Using kubectl context: docker-desktop         subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0000] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0000] Running command: [minikube version --output=json]  subtask=-1 task=DevLoop
DEBU[0000] setting Docker user agent to skaffold-v2.1.0  subtask=-1 task=DevLoop
INFO[0000] no kpt renderer or deployer found, skipping hydrated-dir creation  subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0000] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0000] Running command: [kubectl config view --minify -o jsonpath='{..namespace}']  subtask=-1 task=DevLoop
DEBU[0001] Command output: ['']                          subtask=-1 task=DevLoop
DEBU[0001] CLI platforms provided: ""                    subtask=-1 task=DevLoop
DEBU[0001] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0001] platforms detected from active kubernetes cluster nodes: "linux/amd64"  subtask=-1 task=DevLoop
DEBU[0001] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0001] push value not present in NewBuilder, defaulting to false because cluster.PushImages is false  subtask=-1 task=DevLoop
DEBU[0001] Using builder: local                          subtask=-1 task=DevLoop
DEBU[0001] push value not present in NewBuilder, defaulting to false because cluster.PushImages is false  subtask=-1 task=DevLoop
INFO[0001] build concurrency set to default value of -1  subtask=-1 task=DevLoop
No tags generated
INFO[0001] Tags generated in 55.418µs                    subtask=-1 task=Build
INFO[0001] Cache check completed in 15.385µs             subtask=-1 task=Build
INFO[0001] Starting render...                            subtask=-1 task=DevLoop
INFO[0001] starting render process                       subtask=0 task=Render
DEBU[0001] Executing template &{envTemplate 0xc000cc0000 0xc00112c140  } with environment map[CHROME_DESKTOP:code-url-handler.desktop COLORTERM:truecolor CONDA_DEFAULT_ENV:base CONDA_EXE:/home/origin/anaconda3/bin/conda CONDA_PREFIX:/home/origin/anaconda3 CONDA_PROMPT_MODIFIER:(base)  CONDA_PYTHON_EXE:/home/origin/anaconda3/bin/python CONDA_SHLVL:1 DBUS_SESSION_BUS_ADDRESS:unix:path=/run/user/1000/bus DEFAULTS_PATH:/usr/share/gconf/ubuntu.default.path DESKTOP_SESSION:ubuntu DISPLAY::0 DOCKER_HOST:unix:///home/origin/.docker/desktop/docker.sock GDK_BACKEND:x11 GDMSESSION:ubuntu GIO_LAUNCHED_DESKTOP_FILE:/usr/share/applications/code.desktop GIO_LAUNCHED_DESKTOP_FILE_PID:2276 GIT_ASKPASS:/usr/share/code/resources/app/extensions/git/dist/askpass.sh GJS_DEBUG_OUTPUT:stderr GJS_DEBUG_TOPICS:JS ERROR;JS LOG GNOME_DESKTOP_SESSION_ID:this-is-deprecated GNOME_SHELL_SESSION_MODE:ubuntu GPG_AGENT_INFO:/run/user/1000/gnupg/S.gpg-agent:0:1 GTK_MODULES:gail:atk-bridge HOME:/home/origin IM_CONFIG_PHASE:1 INVOCATION_ID:25ade16af311466090638753119a5908 JAVA_HOME:/opt/graalvm JOURNAL_STREAM:8:42909 LANG:en_GB.UTF-8 LANGUAGE:en_GB:en LESSCLOSE:/usr/bin/lesspipe %s %s LESSOPEN:| /usr/bin/lesspipe %s LOGNAME:origin LS_COLORS:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: MANAGERPID:1254 MANDATORY_PATH:/usr/share/gconf/ubuntu.mandatory.path NVM_BIN:/home/origin/.nvm/versions/node/v16.16.0/bin NVM_CD_FLAGS: NVM_DIR:/home/origin/.nvm NVM_INC:/home/origin/.nvm/versions/node/v16.16.0/include/node ORIGINAL_XDG_CURRENT_DESKTOP:ubuntu:GNOME PATH:/home/origin/.jbang/bin:/home/origin/.local/bin:/home/origin/anaconda3/bin:/home/origin/anaconda3/condabin:/home/origin/.jbang/bin:/home/origin/.nvm/versions/node/v16.16.0/bin:/home/origin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/origin/.local/share/JetBrains/Toolbox/scripts:/usr/local/go/bin:/opt/maven/apache-maven-3.8.6/bin:/opt/graalvm/bin:/home/origin/.local/bin:/home/origin/.local/share/JetBrains/Toolbox/scripts:/usr/local/go/bin:/opt/maven/apache-maven-3.8.6/bin:/opt/graalvm/bin:/home/origin/.local/bin PWD:/home/origin/mkdirdev/skaffold-issue QT_ACCESSIBILITY:1 QT_IM_MODULE:ibus SESSION_MANAGER:local/origin:@/tmp/.ICE-unix/1474,unix/origin:/tmp/.ICE-unix/1474 SHELL:/bin/bash SHLVL:1 SSH_AGENT_PID:1434 SSH_AUTH_SOCK:/run/user/1000/keyring/ssh TERM:xterm-256color TERM_PROGRAM:vscode TERM_PROGRAM_VERSION:1.74.3 USER:origin USERNAME:origin VSCODE_GIT_ASKPASS_EXTRA_ARGS:--ms-enable-electron-run-as-node VSCODE_GIT_ASKPASS_MAIN:/usr/share/code/resources/app/extensions/git/dist/askpass-main.js VSCODE_GIT_ASKPASS_NODE:/usr/share/code/code VSCODE_GIT_IPC_HANDLE:/run/user/1000/vscode-git-9e0a41b926.sock WINDOWPATH:2 XAUTHORITY:/run/user/1000/gdm/Xauthority XDG_CONFIG_DIRS:/etc/xdg/xdg-ubuntu:/etc/xdg XDG_CURRENT_DESKTOP:Unity XDG_DATA_DIRS:/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop XDG_MENU_PREFIX:gnome- XDG_RUNTIME_DIR:/run/user/1000 XDG_SESSION_CLASS:user XDG_SESSION_DESKTOP:ubuntu XDG_SESSION_TYPE:x11 XMODIFIERS:@im=ibus _:/usr/local/bin/skaffold _CE_CONDA: _CE_M:]  subtask=-1 task=DevLoop
DEBU[0001] manifests with tagged images:apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: smtp4dev
        resources: {}
status: {}  subtask=0 task=Render
DEBU[0001] manifests with labels apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
    spec:
      containers:
      - image: nginx
        name: smtp4dev
        resources: {}
status: {}  subtask=-1 task=DevLoop
DEBU[0001] manifests set with namespace apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
    spec:
      containers:
      - image: nginx
        name: smtp4dev
        resources: {}
status: {}  subtask=-1 task=DevLoop
INFO[0001] starting render process                       subtask=1 task=Render
DEBU[0001] Executing template &{envTemplate 0xc000242900 0xc00112c410  } with environment map[CHROME_DESKTOP:code-url-handler.desktop COLORTERM:truecolor CONDA_DEFAULT_ENV:base CONDA_EXE:/home/origin/anaconda3/bin/conda CONDA_PREFIX:/home/origin/anaconda3 CONDA_PROMPT_MODIFIER:(base)  CONDA_PYTHON_EXE:/home/origin/anaconda3/bin/python CONDA_SHLVL:1 DBUS_SESSION_BUS_ADDRESS:unix:path=/run/user/1000/bus DEFAULTS_PATH:/usr/share/gconf/ubuntu.default.path DESKTOP_SESSION:ubuntu DISPLAY::0 DOCKER_HOST:unix:///home/origin/.docker/desktop/docker.sock GDK_BACKEND:x11 GDMSESSION:ubuntu GIO_LAUNCHED_DESKTOP_FILE:/usr/share/applications/code.desktop GIO_LAUNCHED_DESKTOP_FILE_PID:2276 GIT_ASKPASS:/usr/share/code/resources/app/extensions/git/dist/askpass.sh GJS_DEBUG_OUTPUT:stderr GJS_DEBUG_TOPICS:JS ERROR;JS LOG GNOME_DESKTOP_SESSION_ID:this-is-deprecated GNOME_SHELL_SESSION_MODE:ubuntu GPG_AGENT_INFO:/run/user/1000/gnupg/S.gpg-agent:0:1 GTK_MODULES:gail:atk-bridge HOME:/home/origin IM_CONFIG_PHASE:1 INVOCATION_ID:25ade16af311466090638753119a5908 JAVA_HOME:/opt/graalvm JOURNAL_STREAM:8:42909 LANG:en_GB.UTF-8 LANGUAGE:en_GB:en LESSCLOSE:/usr/bin/lesspipe %s %s LESSOPEN:| /usr/bin/lesspipe %s LOGNAME:origin LS_COLORS:rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: MANAGERPID:1254 MANDATORY_PATH:/usr/share/gconf/ubuntu.mandatory.path NVM_BIN:/home/origin/.nvm/versions/node/v16.16.0/bin NVM_CD_FLAGS: NVM_DIR:/home/origin/.nvm NVM_INC:/home/origin/.nvm/versions/node/v16.16.0/include/node ORIGINAL_XDG_CURRENT_DESKTOP:ubuntu:GNOME PATH:/home/origin/.jbang/bin:/home/origin/.local/bin:/home/origin/anaconda3/bin:/home/origin/anaconda3/condabin:/home/origin/.jbang/bin:/home/origin/.nvm/versions/node/v16.16.0/bin:/home/origin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/origin/.local/share/JetBrains/Toolbox/scripts:/usr/local/go/bin:/opt/maven/apache-maven-3.8.6/bin:/opt/graalvm/bin:/home/origin/.local/bin:/home/origin/.local/share/JetBrains/Toolbox/scripts:/usr/local/go/bin:/opt/maven/apache-maven-3.8.6/bin:/opt/graalvm/bin:/home/origin/.local/bin PWD:/home/origin/mkdirdev/skaffold-issue QT_ACCESSIBILITY:1 QT_IM_MODULE:ibus SESSION_MANAGER:local/origin:@/tmp/.ICE-unix/1474,unix/origin:/tmp/.ICE-unix/1474 SHELL:/bin/bash SHLVL:1 SSH_AGENT_PID:1434 SSH_AUTH_SOCK:/run/user/1000/keyring/ssh TERM:xterm-256color TERM_PROGRAM:vscode TERM_PROGRAM_VERSION:1.74.3 USER:origin USERNAME:origin VSCODE_GIT_ASKPASS_EXTRA_ARGS:--ms-enable-electron-run-as-node VSCODE_GIT_ASKPASS_MAIN:/usr/share/code/resources/app/extensions/git/dist/askpass-main.js VSCODE_GIT_ASKPASS_NODE:/usr/share/code/code VSCODE_GIT_IPC_HANDLE:/run/user/1000/vscode-git-9e0a41b926.sock WINDOWPATH:2 XAUTHORITY:/run/user/1000/gdm/Xauthority XDG_CONFIG_DIRS:/etc/xdg/xdg-ubuntu:/etc/xdg XDG_CURRENT_DESKTOP:Unity XDG_DATA_DIRS:/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop XDG_MENU_PREFIX:gnome- XDG_RUNTIME_DIR:/run/user/1000 XDG_SESSION_CLASS:user XDG_SESSION_DESKTOP:ubuntu XDG_SESSION_TYPE:x11 XMODIFIERS:@im=ibus _:/usr/local/bin/skaffold _CE_CONDA: _CE_M:]  subtask=-1 task=DevLoop
DEBU[0001] manifests with tagged images:apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smtp
  name: smtp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smtp
    spec:
      containers:
      - image: rnwood/smtp4dev:v3
        name: smtp4dev
        resources: {}
status: {}  subtask=1 task=Render
DEBU[0001] manifests with labels apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smtp
    skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
  name: smtp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smtp
        skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
    spec:
      containers:
      - image: rnwood/smtp4dev:v3
        name: smtp4dev
        resources: {}
status: {}  subtask=-1 task=DevLoop
DEBU[0001] manifests set with namespace apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smtp
    skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
  name: smtp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smtp
        skaffold.dev/run-id: 4654b8bd-3355-4313-97a6-3d83b6c62c3d
    spec:
      containers:
      - image: rnwood/smtp4dev:v3
        name: smtp4dev
        resources: {}
status: {}  subtask=-1 task=DevLoop
INFO[0001] Render completed in 3.842592ms                subtask=-1 task=DevLoop
Starting deploy...
DEBU[0001] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0001] Running command: [kubectl --context docker-desktop get -f - --ignore-not-found -ojson]  subtask=0 task=Deploy
DEBU[0001] Command output: []                            subtask=0 task=Deploy
DEBU[0001] 1 manifests to deploy. 1 are updated or new   subtask=0 task=Deploy
DEBU[0001] Running command: [kubectl --context docker-desktop apply -f -]  subtask=0 task=Deploy
 - deployment.apps/nginx created
Waiting for deployments to stabilize...
DEBU[0001] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0001] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
DEBU[0001] checking status deployment/nginx              subtask=0 task=Deploy
DEBU[0002] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0002] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0002] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
DEBU[0003] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0003] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0003] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
DEBU[0004] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0004] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0004] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
DEBU[0005] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0005] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0005] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
 - deployment/nginx: creating container smtp4dev
    - pod/nginx-55fd57778f-z45v2: creating container smtp4dev
DEBU[0006] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0006] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0006] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
DEBU[0007] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0007] Command output: [Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
]  subtask=0 task=Deploy
DEBU[0007] Pod "nginx-55fd57778f-z45v2" scheduled but not ready: checking container statuses  subtask=-1 task=DevLoop
DEBU[0008] Running command: [kubectl --context docker-desktop rollout status deployment nginx --namespace default --watch=false]  subtask=0 task=Deploy
DEBU[0008] Command output: [deployment "nginx" successfully rolled out
]  subtask=0 task=Deploy
 - deployment/nginx is ready.
Deployments stabilized in 7.167 seconds
INFO[0008] Deploy completed in 7.523 seconds             subtask=-1 task=Deploy
DEBU[0008] getting client config for kubeContext: `docker-desktop`  subtask=-1 task=DevLoop
No artifacts found to watch
INFO[0008] List generated in 103.58µs                    subtask=-1 task=DevLoop
Press Ctrl+C to exit
Watching for changes...
DEBU[0008] Change detected<nil>                          subtask=-1 task=DevLoop

**Comment by renzodavid9** [comment]
Hi @mkdirJava, could you try adding a `deploy` stanza for the `dev` profile? That will look something this, assuming you'll use a `kubectl` deployer:

```
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: test
profiles:
  - name: dev
    manifests:
      rawYaml:
        - dev/smtp.yaml
    deploy:
      kubectl: {}
requires:
  - path: base
```
Thanks!

**Comment by aaron-prindle** [comment]
@mkdirJava were you able to try the suggestion @renzodavid9 posted?  I believe the issue here is that no `deploy:` stanza exists.  Perhaps we can create another issue or track better error messaging or better defaults as what the team could improve here

**Comment by aaron-prindle** [comment]
I was not able to reproduce this locally, the deployment was created when using the profile from the repro repository given - likely this has been fixed since this was posted.  Marking closed
