### ISSUE TITLE
Add GCB Trigger docs to getting started

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#84]

**Comment by ahmetb** [comment]
Nope, I just put out https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/skaffold which might even be broken right now. I also have a demo app using GCB+Skaffold to deploy here: https://github.com/ahmetb/coffeelog/blob/d6a7b6fb78cbd983d90410bc28fae8b497fdeb4c/cloudbuild.yaml I'm also working on a 10-tier microservices app, deploying with skaffold, and I'm planning to integrate GCB+Skaffold there, as well.

**Comment by balopat** [comment]
Closing in favor for #1937
