### ISSUE TITLE
[Documentation] Update skaffold documentation to indicate `skaffold debug` is not supported for python 3.11 and above

### ISSUE THREAD

**Issue by cheburakshu** [GoogleContainerTools/skaffold#8422]
`skaffold debug` doesn't work yet for python 3.11. The bug reports, tasks and PRs are as follows:
- Task:: https://github.com/GoogleContainerTools/skaffold/issues/8242
- PR:: https://github.com/GoogleContainerTools/container-debug-support/pull/122 in failed status for nearly 2 months.
- Bug report:: https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/735

Kindly update the documentation to say `skaffold debug` is not supported for python 3.11 and above until support is added.
Or better, state the python versions where the debug support is available, as it seems, every new python version will require a PR to enable support.

URL: https://skaffold.dev/docs/workflows/debug/
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/27330002/217690806-b4678673-1159-457a-83cc-f6a9266dec09.png">

**Comment by aaron-prindle** [comment]
@cheburakshu thanks for flagging this.  The work here unfortunately was halted  (you noted above the WIP PR) but we are now re-prioritizing to get the Python 3.11 support in Skaffold.  I will update the docs to state this in the next 1-2 days and the plan is to add Python 3.11 shortly as well

**Comment by cheburakshu** [comment]
Thanks @aaron-prindle!!

**Comment by cheburakshu** [comment]
Any idea when the actual support would be added? Given py 3.12 is going to be released shortly, will 3.12 also be in scope?
