### ISSUE TITLE
Upgrade logic for v1 kustomize deployer, is not adding a deployer stanza

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#8423]
In Skaffold v1, kustomize is configured as a deployer, in Skaffold v2 it is a renderer. When the upgrade logic tries to transform a v1 config that uses `deploy.kustomize` into a v2 config, it adds the `manifests.kustomize` stanza, but doesn't add a deployer. In multi config/module projects this behaviour causes that the manifests renderer with kustomize are not deployed.

### Expected behavior
The upgrade logic (`skaffold fix`) to output configs that can deploy v1 manifests that uses the kustomize deployer, with  Skaffold v2 (for the case of multi config/module projects).

### Actual behavior
The resulting config can not be use to deploy manifests generated with kustomize (for the case of multi config/module projects)

### Information

- Skaffold version: version from @ HEAD
- Operating system: any
- Installed via: Built from @ HEAD
- Contents of skaffold.yaml (this is a Skaffold v1 config):

```yaml
apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kustomize: {}

```

### Steps to reproduce the behavior

1. Using the [examples/kustomize](https://github.com/GoogleContainerTools/skaffold/tree/v1/examples/kustomize) project from `v1` branch
2. Run `skaffold fix` using Skaffold v2
3. The resulting config does not have a deploy stanza, making it to not work in multi config/module projects

**Comment by aaron-prindle** [comment]
Making triage bot happy
