### ISSUE TITLE
Add support for user supplied CRDs to be added to our `validations.go` logic (similar to bespoke ConfigController support currently but make it dynamic)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#8462]
Issue tracks adding support for user supplied CRDs to be added to our `validations.go` logic (similar to bespoke ConfigController support currently but make it dynamic).  With this, users could  supply an allowlist of CRDs that skaffold would watch dynamically as long as they support the `kstatus` standard:
https://github.com/kubernetes-sigs/cli-utils/blob/master/pkg/kstatus/README.md

**Comment by ericzzzzzzz** [comment]
Hi @aaron-prindle  could you help me understand the ask here? Is this asking to provide a way for CRDs statuscheck like ConfigConnector here https://github.com/GoogleContainerTools/skaffold/blob/88e1c1734ea0f1bd79a0f24783f9565057a0e46a/pkg/diag/validator/config_connector.go#L1-L87 in `validator` package but make it dynamic like providing CRDs through command line or in a skaffold config stanza?   Thank you :)
