### ISSUE TITLE
[IntegrationTest] Add test to validate the proper helm.releases[].namespace is used on render after a schema upgrade

### ISSUE THREAD

**Issue by renzodavid9** [GoogleContainerTools/skaffold#8483]
Related to https://github.com/GoogleContainerTools/skaffold/issues/8185, Skaffold team should add some integration tests related to namespaces (esp. helm release namespace setting) and v1 -> v2 schema upgrade that would expressly have caught #8185 and possible go a bit deeper as well (more namespace options and regression possibilities tested)

**Comment by linjingsde** [comment]
I am working on this.
