### ISSUE TITLE
`skaffold fix --overwrite` does not overwrite, instead it renames.

### ISSUE THREAD

**Issue by merikan** [GoogleContainerTools/skaffold#8489]
My `skaffold.yaml` file is symlinked to another location 
```
$ ls -o skaffold.yaml
lrwxr-xr-x  1 peter  26  3 Mar 09:54 skaffold.yaml@ -> etc/skaffold/skaffold.yaml
```
### Expected behavior
content of current `skaffold.yaml` should be overwritten 

### Actual behavior
current `skaffold.yaml` file is renamed and a new file is created. 
```
$ skaffold fix --overwrite
Backed up previous skaffold.yaml at  skaffold.yaml.v2
New config at version skaffold/v4beta2 generated and written to skaffold.yaml
$ ls -o skaffold.yaml*
-rw-r--r--  1 peter  613  3 Mar 10:08 skaffold.yaml
lrwxr-xr-x  1 peter   26  3 Mar 09:54 skaffold.yaml.v2@ -> etc/skaffold/skaffold.yaml
```
**workaround**
Using `--output skaffold.yaml` fixes my problem.

### Information

- Skaffold version: 2.1.0 
- Operating system: MacOs 12.6.2 
- Installed via: homebrew 
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by alphanota** [comment]
Would like to work on this. Thanks!

**Comment by alphanota** [comment]
was able to reproduce with skaffold version 453b101d7 - working on a fix.

**Comment by alphanota** [comment]
IIUC - the expected behavior should be to:
>  backup the origjnal skaffold file the symlink points to, by renaming it.
> Write the new config into the path that belonged to the old file (real path, not symlink)

The symlink still points to old path, but the file with that path will have new config.
After this, the symlink still points to the original skaffold path, but that path will be
