### ISSUE TITLE
Enable namespace flag for non-helm deploys

### ISSUE THREAD

**Issue by slamdev** [GoogleContainerTools/skaffold#849]
### Expected behavior
Replace `namespace` value in deploying manifests when it is provided via command-line for kubectl deploys
### Actual behavior
Works only for helm deploys
### Information
It would be nice to extend existing `namespace` flag to work with both helm and kubectl deploys.

**Comment by dgageot** [comment]
Hey @slamdev thanks for asking. I pushed support for this feature before I saw your issue! https://github.com/GoogleContainerTools/skaffold/pull/852

**Comment by slamdev** [comment]
@dgageot cool! thanks :)
