### ISSUE TITLE
Getting lots of parsing errors when running `skaffold init` on for example 'buildpacks-node-tutorial` using release 2.2.0

### ISSUE THREAD

**Issue by mpas** [GoogleContainerTools/skaffold#8547]
### Expected behavior
Running `skaffold init` on the `buildpacks-node-tutorial` in the repo should not return parsing errors.

**The latest version 2.2.0 has this behaviour, also tested with an older release and then the error messages do not appear. 2.0.6 does not mention the errors when doing an init.**

### Actual behavior
Cloning the example repo and trying the `buildpacks-node-tutorial` example

1. `git clone https://github.com/GoogleContainerTools/skaffold`
2. `cd skaffold/examples/buildpacks-node-tutorial`
3.  Running `skaffold init`

Returns a bunch of YAML parsing errors.

```
ERRO[0000] reading Kubernetes YAML: yaml: line 5: mapping values are not allowed in this context  subtask=-1 task=DevLoop
ERRO[0000] no valid Kubernetes objects decoded           subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into kubernetes.yamlObject  subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `<!docty...` into kubernetes.yamlObject  subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `use strict` into kubernetes.yamlObject  subtask=-1 task=DevLoop
```

Note: Also tried a homemade Docker project and this also gives errors on `skaffold init` as it seems that it wants to parse the Dockerfile as a YAML file.

### Information

- Skaffold version: v2.2.0
- Operating system: macOS Monterey
- Installed via: skaffold.dev

### Steps to reproduce the behavior

1. `git clone https://github.com/GoogleContainerTools/skaffold`
2. `cd skaffold/examples/buildpacks-node-tutorial`
3.  Running `skaffold init`

❯ skaffold init -vdebug
DEBU[0000] skaffold API not starting as it's not requested  subtask=-1 task=DevLoop
INFO[0000] Skaffold &{Version:v2.2.0 ConfigVersion:skaffold/v4beta3 GitVersion: GitCommit:bfc52e41ca7fbeac8a9f1da681118d14e197d6d4 BuildDate:2023-03-06T21:13:22Z GoVersion:go1.20.1 Compiler:gc Platform:darwin/amd64 User:}  subtask=-1 task=DevLoop
DEBU[0000] Disable housekeeping messages for command explicitly  subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: line 5: mapping values are not allowed in this context  subtask=-1 task=DevLoop
DEBU[0000] Running command: [java -version]              subtask=-1 task=DevLoop
DEBU[0000] apiVersion not present in yaml, continuing    subtask=-1 task=DevLoop
ERRO[0000] no valid Kubernetes objects decoded           subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into kubernetes.yamlObject  subtask=-1 task=DevLoop
DEBU[0000] not detecting a yaml file k8s/web.yaml as value file. Not part of any chart  subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `<!docty...` into kubernetes.yamlObject  subtask=-1 task=DevLoop
ERRO[0000] reading Kubernetes YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `use strict` into kubernetes.yamlObject  subtask=-1 task=DevLoop
? Choose the builder to build image skaffold-buildpacks-node  [Use arrows to move, type to filter]
> Buildpacks (package.json)
  Buildpacks (project.toml)
  None (image not built from these sources)

**Comment by renzodavid9** [comment]
Hi @mpas, thanks for opening the issue. I was able to reproduce the behaviour you mentioned, I just want to confirm, were you able to get the `skaffold.yaml` file after running `skaffold init` in the `buildpacks-node-tutorial` example? In my case, even with the parsing errors, the resulting `skaffold.yaml` file works as expected. 

I'll take a look to the parsing errors, looks like is not only with the `buildpacks-node-tutorial` project. Thanks!

**Comment by mpas** [comment]
@renzodavid9 the skaffold.yaml works as expected indeed! I tried using a custom app and it also complains on kube manifests file for example. The error message mentions that it tries to parse it as a yaml file.
