### ISSUE TITLE
[Question] Enabling Java debugger

### ISSUE THREAD

**Issue by cheburakshu** [GoogleContainerTools/skaffold#8586]
I am having a situation where I am running a java microservice using `CMD ["gradle", "bootRun"]`. Will `skaffold debug` automatically attach a debugger for these types of images?

Should I have to specify the `runtimeType: java` to enable debugger for this situation? In the docs, the debugger only seems to get attached when `java` is used in the `CMD` invocation. https://skaffold.dev/docs/workflows/debug/#supported-language-runtimes

Thanks in advance for your help.

**Comment by ericzzzzzzz** [comment]
Hi @cheburakshu , the value for ``runtimeType`` to enable javaDebugger is ``jvm`` instead of ``java``

**Comment by cheburakshu** [comment]
ah, got it, thanks @ericzzzzzzz!
