### ISSUE TITLE
upgrade docker in skaffold image

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#8648]
- related https://github.com/GoogleContainerTools/skaffold/issues/8578
 - The fix for this issue is not in v2.3.0, we probably want to include this fix in v2.3.1 as well.

**Comment by aaron-prindle** [comment]
This should be fixed now, cherry-picked https://github.com/GoogleContainerTools/skaffold/pull/8596 in to `v2.3.1`
