### ISSUE TITLE
skaffold dev doesn't detect a new file added to a directory

### ISSUE THREAD

**Issue by marccampbell** [GoogleContainerTools/skaffold#867]
### Expected behavior
When running `skaffold dev`, adding a new file to a watched directory does not trigger a rebuild.

### Actual behavior
Adding a new file should trigger a rebuild, the same as modifying an existing file.

### Information

- Skaffold version: 0.10.0
- Operating system: MacOS 10.13.6 
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

1. Run skaffold dev to watch a directory of files.
2. Create a new file in the directory.
3. Note that skaffold dev doesn't rebuild.

**Comment by marccampbell** [comment]
I just tried this again using 0.11.0 and it appears to work.  This no longer appears to be an issue.

**Comment by balopat** [comment]
thanks for letting us know @marccampbell
