### ISSUE TITLE
`skaffold deploy` cannot perform status check when there are no builds

### ISSUE THREAD

**Issue by anhpngt** [GoogleContainerTools/skaffold#8742]
When there are no build artifacts, `skaffold deploy` does not perform status check properly.

See `Steps to reproduce the behavior` below.

Digging through [the code](https://github.com/GoogleContainerTools/skaffold/blob/v2.4.0/pkg/skaffold/deploy/helm/helm.go#L441), the `--post-renderer /path/to/skaffold` flag only applies when there are `len(builds) > 0`. Maybe it is causing the `skaffold.dev/run-id` to be missing in the resource labels and making `skaffold` fail to detect them.

### Expected behavior

Running `skaffold deploy` with or without artifacts should check for all deployments/statefulsets/pods/...
before continuing.

```sh
Starting deploy...
...
Waiting for deployments to stabilize...
 - deployment/skaffold-helm is ready.
Deployments stabilized in 2.047 seconds
```

### Actual behavior

`skaffold deploy` does not recognize any deployment objects, thus succeeds immediately.

```sh
Starting deploy...
...
Waiting for deployments to stabilize...
Deployments stabilized in 10.845515ms
```

### Steps to reproduce the behavior

1. Use `examples/helm-deployment` with a customized `skaffold.yaml`.
Note that the `build` section must be removed to compare with and without artifact cases.

```yaml
# skaffold.yaml
apiVersion: skaffold/v4beta5
kind: Config
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValues:
        image: 'skaffold-helm:custom-tag'
```

Convenience script:

```sh
$ git clone https://github.com/GoogleContainerTools/skaffold/
$ cd skaffold/examples/helm-deployment
$ echo 'apiVersion: skaffold/v4beta5
kind: Config
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      setValues:
        image: skaffold-helm:invalid-tag
' > skaffold.yaml
```

3. Running `skaffold deploy` with artifacts

```sh
$ skaffold deploy -i 'skaffold-helm:invalid-tag'
Tags used in deployment:
 - skaffold-helm -> localhost:5001/skaffold-helm:invalid-tag
Starting deploy...
Helm release skaffold-helm not installed. Installing...
NAME: skaffold-helm
LAST DEPLOYED: Thu May  4 16:35:48 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for deployments to stabilize...
 - deployment/skaffold-helm: container skaffold-helm is waiting to start: localhost:5001/skaffold-helm:invalid-tag can't be pulled
    - pod/skaffold-helm-74f54b67bd-xczxn: container skaffold-helm is waiting to start: localhost:5001/skaffold-helm:invalid-tag can't be pulled
    - pod/skaffold-helm-74f54b67bd-v4wcz: container skaffold-helm is waiting to start: localhost:5001/skaffold-helm:invalid-tag can't be pulled
 - deployment/skaffold-helm failed. Error: container skaffold-helm is waiting to start: localhost:5001/skaffold-helm:invalid-tag can't be pulled.
1/1 deployment(s) failed
```

In this case, the status check correctly detects that the deployment fails due to invalid image.

`skaffold.dev/run-id` exists in the deployment's labels.

```
$ kubectl get deployments.apps/skaffold-helm --output=jsonpath='{.metadata.labels}'
{"app":"skaffold-helm","app.kubernetes.io/managed-by":"Helm","skaffold.dev/run-id":"95128d06-ae2e-4c3b-b376-f03cea013918"}
```

4. Running `skaffold deploy` without artifacts

```sh
$ helm uninstall skaffold-helm  # not important but you can uninstall the chart first
release "skaffold-helm" uninstalled
$ skaffold deploy
Starting deploy...
Helm release skaffold-helm not installed. Installing...
NAME: skaffold-helm
LAST DEPLOYED: Thu May  4 16:38:38 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
Waiting for deployments to stabilize...
Deployments stabilized in 3.603017ms
```

In this case, the status check fails to find any deployments that skaffold is managing. It exits immediately as a result.

`skaffold.dev/run-id` does not exist in the deployment's labels.

```
$ kubectl get deployments.apps/skaffold-helm --output=jsonpath='{.metadata.labels}'
{"app":"skaffold-helm","app.kubernetes.io/managed-by":"Helm"}
```

### Information

- Skaffold version: `v2.4.0`
- Operating system: `Linux anhpngt-manabie 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- Installed via: `skaffold.dev`

**Comment by Rajesh-Ayaldasani** [comment]
I am also facing the similar issue and would like to work on the fix.
