### ISSUE TITLE
Auto-Activate Profile by Deployment Type

### ISSUE THREAD

**Issue by mbeldman** [GoogleContainerTools/skaffold#8749]
### Expected behavior
Auto-activate a profile based on the project's deployment type, e.g.

```profiles:
- name: sync
  activation:
    - deploy: embeddedserver 
  patches:
      - op: add
        path: /build/artifacts/0/sync.auto
        value: ["true"] 
```
### Actual behavior
This currently doesn't exist.
The only options for auto-activate are: skaffold command, kubecontext, and environment variable value

**Comment by ericzzzzzzz** [comment]
Hi @mbeldman , could you clarify what deployment type is?

**Comment by mbeldman** [comment]
> Hi @mbeldman , could you clarify what deployment type is?

Sure - I was thinking embedded server jar vs. war file
