### ISSUE TITLE
`skaffold build --push=false --output-file output.json` changes the tag fields in the output field

### ISSUE THREAD

**Issue by mhill-holoplot** [GoogleContainerTools/skaffold#8759]
### Expected behavior

`skaffold build --push=false --output-file output.json` 
and 
`skaffold build --push=true --output-file output.json` 

both produce the same output e.g.

`{"builds":[{"imageName":"init-db","tag":"example.com/example:tag@sha256:350f22c40ef2eba0b49135f9e79e3db1ed18112ac9f780db6be2c64299e1b486"}`

### Actual behavior

`--push=true` yeild the expected output:

`{"builds":[{"imageName":"init-db","tag":"example.com/example:tag@sha256:350f22c40ef2eba0b49135f9e79e3db1ed18112ac9f780db6be2c64299e1b486"}`

Whereas `--push=false` does not include the tag:

`{"builds":[{"imageName":"init-db","tag":"example.com/example:101a9b41e296016d5783f17c0fa96a0cda0ff873d95d661337972f7173a3ca27"}`

### Information

- Skaffold version:  tried 2.1.0 and 2.4.0
- Operating system: Fedora 37
- Installed via: skaffold.dev

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold build --push=false  --output-file output-no-push.json --default-repo repo-you-can-push.to`
3.  `skaffold build --push=true  --output-file output-push.json --default-repo repo-you-can-push.to`
4. Observe the difference

**Comment by ericzzzzzzz** [comment]
This actually works as intended. 
The tag build output should be able to determine an image.  So later it can be used to replace image fields in k8s manifests for render, deploy. 
For push `true` case, image digest is available from the remote registry, so we can use this to identify an unmodified image. 
For push `false` case, digest is not available in docker daemon, so skaffold uses image ID as the extra tag to locate the image.
