### ISSUE TITLE
skaffold  2.4.1 for windows shows the wrong version

### ISSUE THREAD

**Issue by svzieg** [GoogleContainerTools/skaffold#8785]
we installed the latest skaffold version for windows from github (v2.4.1) but the version command tells a different version.

We don't know if we now have a the skaffold version or if the version command is broken for windows. 

For your interest:  for linux the latest github release shows the correct version.

### Expected behavior

`skaffold.exe version` should display v2.4.1

### Actual behavior

`skaffold.exe version` displays v1.39.6

![MicrosoftTeams-image (1)](https://github.com/GoogleContainerTools/skaffold/assets/5394394/d0468cf0-cf29-460c-96a3-2a2ef59e2195)

**Comment by renzodavid9** [comment]
Hey @svzieg, thanks a lot for opening this issue. The binaries for the v2.4.1 release are already updated with the proper Skaffold version. Thanks! 😄
