### ISSUE TITLE
Feature request for Bazel support: Support containers built with rules_oci 

### ISSUE THREAD

**Issue by aran** [GoogleContainerTools/skaffold#8886]
[rules_oci](https://github.com/bazel-contrib/rules_oci) is a new container builder for Bazel. Compared to rules_docker, it is under active development and recently released 1.0. 

Instead of one container_image rule that also produces a .tar target for docker, rules_oci separates two rules: oci_image and oci_tarball. 

Despite the fact that docker (or in my case, colima) can load and run the output of rules_oci, when using skaffold, something breaks with the following error: `build [hello-image] failed: tagging the image: Error parsing reference: "" is not a valid repository/tag: invalid reference format` See longer version below, and attached small workspace. [rules_oci_demo.tar.gz](https://github.com/GoogleContainerTools/skaffold/files/11761892/rules_oci_demo.tar.gz)

```
aran@MacBook-Air rules_oci % skaffold dev               
Generating tags...
 - hello-image -> hello-image:latest
Checking cache...
 - hello-image: Not found. Building
Starting build...
Found [colima] context, using local docker daemon.
Building [hello-image]...
Target platforms: [linux/arm64]
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //:hello.tar (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:hello.tar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //:hello.tar up-to-date:
  bazel-bin/hello.tar/tarball.tar
INFO: Elapsed time: 0.074s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Loaded image: hello:latest
Cleaning up...
 - No resources found
build [hello-image] failed: tagging the image: Error parsing reference: "" is not a valid repository/tag: invalid reference format
aran@MacBook-Air rules_oci % docker load --input $(bazel cquery --output=files //:hello.tar)     
Loading: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //:hello.tar (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:hello.tar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.070s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
Loaded image: hello:latest
aran@MacBook-Air rules_oci % docker run hello:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023/06/15 19:21:46 Server listening on port 8080
^C%    
```

**Comment by ericzzzzzzz** [comment]
haven't looked into the detail yet, but here is a workaround to use oci rule:

you need to remove the `:`   from `repo_tags = ["hello:latest"]`

**Comment by ericzzzzzzz** [comment]
- If you use a remote registry, oci_rule should just work 
 - If you store your image in local docker daemon, there is a workaround, but quite hacky
   - in `oci_tarball` call, repo_tags should contains a tag in the format `bazel:${target-name-without-.tar}` , example
      
```python
          oci_tarball(
    name = "ccc.tar",
    image = "@hello//:hello",
    repo_tags = ["bazel:ccc", "bazel:bbb"],
)
 ```
   other tags are optional. 

we're currently a bit understaffed, the official support for oci rule may not be prioritized.

**Comment by aran** [comment]
Is there a reason it would be non-deterministic, or dependent on some aspect of docker state? I thought had it working with this workaround, then it stopped working. Using relative targets ":foo" instead of "//abs/path/to:foo" seems to get it to work again. I am wondering if that's because it avoids https://github.com/GoogleContainerTools/skaffold/blob/d019fddff2c3f25a5a0971cb15ba77479ce33e6a/pkg/skaffold/build/bazel/build.go#L163. That makes me wonder if there might be a small and easy fix.

**Comment by a9b3** [comment]
Confirming that the workaround of putting the target on the same level as skaffold.yaml and using the relative target results in a successful build. (Note: it does not work if the target is `//some/path:aaa.tar` must be `//:aaa.tar`)

Example below

```
# ./skaffold.yaml
kind: Config
build:
  artifacts:
    - image: aaa
      bazel:
        target: //:aaa.tar
```

```
# ./BUILD.bazel
oci_tarball(
    name = "aaa.tar",
    image = "//path/to/whatever:image",
    repo_tags = [
        "bazel:aaa",
    ],
)
```

**Comment by ericzzzzzzz** [comment]
> Is there a reason it would be non-deterministic, or dependent on some aspect of docker state? I thought had it working with this workaround, then it stopped working. Using relative targets ":foo" instead of "//abs/path/to:foo" seems to get it to work again. I am wondering if that's because it avoids
> 
Not sure why this part of code was implemented in this way,  I don't know much about bazel, but it looks like that with the original docker build rule, there is no dedicated place to specify image tag when bazel builds a image tarball, it deduces image name/tag from the target name and wrap it in the tarball, when the tarball is loaded to a docker daemon the tag is used, skaffold is kind doing something similar to construct the tag, and then get the imageID with the tag from docker daemon.

For oci_tarball rule, you can specify your tag in `repo_tags`. That's why we need to add an extra tag that skaffold will deduce from target name,  for something like //:abc.tar        `//:` and `.tar`are removed, and `bazel:` is prepend. For name like `//sss/bbb/ccc:abc.tar` , skaffold doesn't remove ":", instead it build a string like `bazel/sss/bbb/ccc:abc` as the tag. 
So for case like this, the extra tag like "/bazel/{package_name}:{targetname_without_.tar}" should be added to repo_tags to make this hack work. 

Also, this feature request has been prioritized, should be available after one or two releases.
