### ISSUE TITLE
Logo as SVG

### ISSUE THREAD

**Issue by userbradley** [GoogleContainerTools/skaffold#8978]
I am trying to get the `skaffold` logo added to `simpleicons`

https://github.com/simple-icons/simple-icons/issues/9138

I need an SVG of the logo. Is there one knocking around anywhere?

**Comment by ericzzzzzzz** [comment]
https://github.com/GoogleContainerTools/skaffold/blob/3a190b3301f597f8d1decdc7b043c3d87b809f17/docs-v2/static/images/skaffold-square.png

**Comment by userbradley** [comment]
Thanks @ericzzzzzzz !
