### ISSUE TITLE
Skaffold fails to patch resources with deploy result labels using Helm deployer

### ISSUE THREAD

**Issue by sean-schaefer** [GoogleContainerTools/skaffold#899]
### Expected behavior
When running `skaffold dev` configured to deploy using Helm with a custom namespace, it should be able to add deployer information to the labels of created resources.

### Actual behavior
After running `skaffold dev` there is a warning for every resource following the successful helm deploy:
```
NAME:   skaffold-helm
LAST DEPLOYED: Wed Aug 15 08:50:14 2018
NAMESPACE: skaffold
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME        TYPE    DATA  AGE
mongo       Opaque  2     4s
jws         Opaque  1     4s
security    Opaque  4     4s

==> v1/Service
NAME            TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)   AGE
api-gateway     ClusterIP  10.97.160.116   <none>       8080/TCP  4s

==> v1beta2/Deployment
NAME            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
api-gateway     1        1        1           0          3s


==> v1/Pod(related)
NAME                             READY  STATUS             RESTARTS  AGE
api-gateway-6cb6877b56-9qw49     0/1    Pending            0         2s

NOTES:
Notes: TBC

WARN[1090] error adding label to runtime object: patching resource /jws: secrets "jws" not found 
WARN[1092] error adding label to runtime object: patching resource /security: secrets "security" not found 
WARN[1093] error adding label to runtime object: patching resource /mongo: secrets "mongo" not found
...
WARN[1107] error adding label to runtime object: patching resource /api-gateway: services "api-gateway" not found 
...
WARN[1116] error adding label to runtime object: patching resource /api-gateway: deployments.apps "api-gateway" not found 
```
This brings my deployment time from ~9seconds to ~45 seconds (there are many other resources being deployed, I truncated the logs).
### Information

- Skaffold version: v.0.11.0
- Operating system: MacOS High Sierra 10.13.6
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
     sha256: {}

  artifacts:
  - imageName: api-gateway
    workspace: ../api-gateway

deploy:
  helm:
     releases:
     - name: skaffold-helm
       chartPath: charts/fathom-universe
       valuesFilePath: charts/fathom-universe/values-dev.yaml
       namespace: skaffold

       values:
         apiGatewayImage: api-gateway
```

### Steps to reproduce the behavior

1. Create a `skaffold.yaml` that uses a helm deployer with the namespace other than default
2. Run `skaffold dev` and notice the warnings

I did some simple logging debugging, and the reason skaffold can't patch the resources is because it's resolving to the default namespace instead of my custom `skaffold` namespace.  I originally grabbed the helm deployer config from https://github.com/GoogleContainerTools/skaffold/blob/master/examples/annotated-skaffold.yaml.
```
...
WARN[0033] Resolved namedspace to default               
WARN[0033] Resolved groupVersionResource to { v1 secrets} 
WARN[0033] error adding label to runtime object: patching resource /mongo: secrets "mongo" not found
```

Skaffold adds the labels appropriately if I set the namespace within my kubectl context, or remove the namespace from the helm deploy configuration in the `skaffold.yaml` altogether and use the default namespace.

**Comment by therealdealneil** [comment]
We're observing the same results using kustomize to deploy.

**Comment by jobets** [comment]
@sean-schaefer I'm facing the same error even though no namespace is mentioned in skaffold.yml.

Helm release app-service not installed. Installing...
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "app-service" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading mysql from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
NAME: app-service
LAST DEPLOYED: Wed Dec 18 13:33:02 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=app-service,app.kubernetes.io/instance=app-service" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
WARN[0041] error adding label to runtime object: patching resource default/app-service-test-connection: pods "app-service-test-connection" not found 
WARN[0042] error adding label to runtime object: patching resource default/app-service-dpsmysql-test: pods "app-service-dpsmysql-test" not found 

 
Helm version: v3.0.1
Skaffold version: v1.0.0-helm3
kubectl version:v1.17.0
minikube version: v1.6.1

Skaffold.yml configuration below:

apiVersion: skaffold/v1
kind: Config

build:
  artifacts:
    - image: eu.gcr.io/projectId/app-service
      context: ./service
      jib: {}

deploy:
  helm:
    releases:
    - name: app-service
      chartPath: helm/app-service/
      values:
        skaffoldImage: eu.gcr.io/projectId/app-service
      setValues:
        image.pullPolicy: Never
        image.tag: local
        skaffold: true
        deployDB: true

Could you suggest the probable fix?
