### ISSUE TITLE
make render output available in post-render hook

### ISSUE THREAD

**Issue by ericzzzzzzz** [GoogleContainerTools/skaffold#9038]
- #7785 implemented render lifecycle hook on per phase basis
 - A user may want to do a custom post-render to add/modify fields on the output manifests with the post-render hook
 - This requires skaffold to pass the render output to the post-render hook(maybe as stdin)?  
 - The command output should be the updated manifests.

**Comment by dannymcerlean1** [comment]
Hi @ericzzzzzzz , I saw that this was merged. Your first comment mentioned passing the render output to a post-render hook so that fields could be added or modified. Is this now possible with your change? I have tried this but it didn't work for me:
`  hooks:
    after:
      - host:
          command: ["sh", "-c", "echo", "$1"]`

**Comment by ericzzzzzzz** [comment]
Hi @alanreynosov , the feature request has not been implemented yet.
