### ISSUE TITLE
skaffold prints upgrade message even on the latest version

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#910]
1. install skaffold via `brew install skaffold`.

2. `skaffold version` says v0.12.0-10-g5d267676

3. `skaffold run prints`:

    `There is a new version (0.12.0) of skaffold available. Download it at https://storage.googleapis.com/skaffold/releases/latest/skaffold-darwin-amd64`

😭

**Comment by ahmetb** [comment]
One thing to note as it might make difference: my Homebrew directory $HOMEBREW is not `/usr/local`; it's `$HOME/.brew`.

This causes all homebrew pkgs to be built from the source as opposed to being downloaded from the Homebrew Bottle (binary build from the cloud). Building locally might be causing the dirty build (`-g5d267676` part).

**Comment by ahmetb** [comment]
Dammit it looks like this was somewhat a building-from-source issue.

`brew uninstall --force` + `brew install` solved it. My bad.

**Comment by ahmetb** [comment]
Correction: this (v0.12.0-10-g5d267676) happened because apparently I previously installed v0.11 with `brew install skaffold --HEAD` which caused the upgrade to happen with `--HEAD` implicitly, which put the build 10 commits ahead of the v0.12.0 tag.

Maybe the version check can be relaxed to check with regexp `"^"+$VERSION+"\w?(.*)$"` so that dirty versions are accepted.

**Comment by balopat** [comment]
Thank you for documenting this!!
