### ISSUE TITLE
"Checking cache..." takes very long unless I delete `node_modules`

### ISSUE THREAD

**Issue by francescortiz** [GoogleContainerTools/skaffold#9118]
### Expected behavior

The "Checking cache..." process speed shouldn't be affected by the presence of directories excluded through `.dockerignore`.

### Actual behavior

The "Checking cache..." process slows down dramatically if the `node_modules` are present, even if they are excluded through `.dockerignore`.

### Information

- Skaffold version: 2.8.0 and 2.1.0
- Operating system: macOS Sonoma Version 14.0
- Installed via: Homebrew and [rtx](https://github.com/jdx/rtx)

**Comment by ericzzzzzzz** [comment]
#9167 should fix this
