### ISSUE TITLE
Skaffold REPL

### ISSUE THREAD

**Issue by bhack** [GoogleContainerTools/skaffold#913]
Can we have a smart way to trigger the rebuild?

Sometime the bootstrap time of the command it is quite heavy (i.e. suppose we are bootstrapping Tensorflow code command). I don't want to waste cycles every time I modify one of the files of an artitifat until "I'am ready".

A solution is to put down and up Skaffold between long and short interactive code change sessions but it is not so pratical.

Also restarting when you are going frequently change args it is not quite practical or triggering [dev to debug mode](https://github.com/GoogleContainerTools/skaffold/issues/94).

How can we approach this "quite standard" dev loop?

Loosely related also to:
https://github.com/GoogleContainerTools/skaffold/issues/477
https://github.com/GoogleContainerTools/skaffold/issues/226

**Comment by bhack** [comment]
Some static file syncing is going to be covered at https://github.com/GoogleContainerTools/skaffold/pull/1039. 
What about interpreted language files? Can we use Skaffold with a bash exec command modality so that the user can interactively launch the commands inside the pod and rebuild and deploy only when he is ready with a checkpoint. This could let him to make a clean room verification/test only when it is needed and not at every line change. What do you think?

**Comment by bhack** [comment]
I think that something like `skaffold dev-bash` or `skaffold dev-intercative` could fit better application that are not related to daemons/web application/services.

**Comment by balopat** [comment]
@bhack - we have now manual triggers - `skaffold dev --trigger manual` that requires a stdin new line to check for file changes - it still rebuilds & redeploys or syncs the changed files.
We are tracking execution of commands after file sync on https://github.com/GoogleContainerTools/skaffold/issues/1312. 
I will keep this issue open to track Skaffold REPL related requests - I think that implementing that with the current Control API would be actually now pretty straightforward - except for the complications of implementing a REPL :) I'll rename this issue to Skaffold REPL.

**Comment by dgageot** [comment]
Hi everyone, I'm going to close this one since we didn't see a lot of demand and we do not plan on working on that subject anytime soon. Feel free to reopen if you really want that feature to be implemented.

**Comment by bhack** [comment]
Currently, after two years, I switched to use Vscode Remote for this interactive development. If you don't see demand in Skaffold you can close the ticket.
