### ISSUE TITLE
Support deploying to multiple kubernetes contexts

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#915]
This came up as an idea in https://github.com/GoogleContainerTools/skaffold/issues/104. 

In a multi-artifact project, skaffold would be able to deploy each artifact to a different namespace/context.  

If you think your use case would need this functionality, please get in touch and describe it for us here!

**Comment by derekperkins** [comment]
We run in a multi-cloud environment, so it's pretty annoying to have to remember which kubectl context you're in before deploying. It's a pretty easy way to accidentally deploy to the wrong region. I'd love to make skaffold cluster aware somehow.

**Comment by tejal29** [comment]
related to #2325.

**Comment by haf** [comment]
I can also chime in that deploying everything with `kustomize` rather than `kubectl` does it right when multiple namespaces are involved, so IMO that could be documented and this issue closed.

**Comment by nkubala** [comment]
I think kustomize opens up enough flexibility to support use cases described here, and I don't think we're going to have time to implement something deeper in skaffold, so I'll close this issue. if you still feel that skaffold needs to support this more fully, please give us some details on your use case and feel free to reopen!

**Comment by msonnleitner** [comment]
We use [GCP's Multi-Cluster Ingress](https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-ingress) to load-balance traffic to multiple GKE clusters. It would be nice if Skaffold could deploy the same application to multiple clusters

**Comment by aaron-prindle** [comment]
@gsquared94 to split this out into multiple issues - multiple contexts vs multiple namespaces
