### ISSUE TITLE
skaffold dev: not cancelling the in-flight build on change

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#916]
(skaffold v0.12.0)

**Observed behavior:** 

- During `skaffold dev`, when I change+save a file, docker build gets kicked off.
- while it's going on, when I change+save a file again, the previous build still goes on, skaffold doesn't cancel/stop the build.

This is significantly noticeable in the user experience.

**Expected:** 
- skaffold cancels the ongoing build when it detects a change to the relevant workspace
- building the old context is no longer useful to me, so I probably should not be waiting for that build to finish as I won't use it.

**Comment by dgageot** [comment]
@ahmetb I'll have a look

**Comment by tejal29** [comment]
shd be closed by https://github.com/dgageot/skaffold/commit/c1708b4f4fc7e099992edc69b8d4831a224ca770
