### ISSUE TITLE
Skaffold fails to clean up multiple artifacts when deploying from JSON k8s manifests

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#921]
### Expected behavior
After running `skaffold dev` and then CTRL+c, all deployed API objects should be removed.

### Actual behavior
The first encountered API object from the manifests is removed successfully, but all others fail.

```
Deploy complete in 2.417336474s
[leeroy-app-d994c955d-bps8z leeroy-app] 2018/08/22 21:40:14 leeroy app server ready
^CCleaning up...
service "leeroy-app" deleted
deployment.apps "leeroy-app" deleted
error: error parsing STDIN: json: line 67: invalid character '-' in numeric literal
WARN[0040] cleanup: delete: kubectl delete: exit status 1 
```

### Information

- Skaffold version: v0.12.0
- Operating system: Debian 4.9.82
- Contents of skaffold.yaml: see `examples/microservices/skaffold.yaml`

### Steps to reproduce the behavior

1. Rewrite the k8s manifests in the `microservices` example in JSON instead of YAML.
2. Run `skaffold dev`, then cancel the loop with CTRL+c.

This is happening because we're creating manifests lists using the YAML document separator (`---`) [here](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl/manifests.go#L32). We should change this to pass each manifest separately to `kubectl delete`.

**Comment by dlorenc** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/5840
