### ISSUE TITLE
Compile errors hard to find in output

### ISSUE THREAD

**Issue by ianlewis** [GoogleContainerTools/skaffold#923]
skaffold dev outputs logs from Pods in the cluster so when updating a service and getting compile errors the errors flow up in the terminal and can be hard to find.

🚀 Moonshot: It would be really cool if you could enter commands into skaffold while it was running to turn off Pod logging dynamically

**Comment by dgageot** [comment]
@ianlewis would a mode that stops all the logs until everything is built make sense?
Like you change some code, it triggers a rebuild that fails, il won't print the logs until you fix the issue. I think it could be the default behaviour

**Comment by ahmetb** [comment]
> would a mode that stops all the logs until everything is built make sense?

+1 for this. Don't stream logs anymore until all builds are succeeding. It can probably even build something like:

    ERROR: docker builds are currently failing for images [gcr.io/foo/bar, gcr.io/foo/quux]

**Comment by balopat** [comment]
I like the idea of stopping the logs too. 
We can create a new issue for the interactive skaffold idea (iSkaffold?:)), I think we need more thoughts/design around that, but could be useful for other use cases too? e.g. maybe #913

**Comment by ahmetb** [comment]
Yeah I've been thinking about some interactive terminal where there are multiple panes: One pane I get to uncheck boxes to stop certains services from being watched/logged, another pane that shows build status, another pane shows logs...
