### ISSUE TITLE
Customized docker push check

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#927]
🚀 This is a moonshot idea. :P

I have 10 microservices in my skaffold.yaml and when I target a remote GKE cluster, a fully cached `skaffold run` takes 60 seconds.

Half (maybe more) of this time is being spent on doing the noop "docker push".

From the output I'm seeing that docker CLI is checking all the layers one by one whether they're pushed. BUT, doesn't it just need to check the topmost layer?

If that's the case, maybe we should use go-dockerregistry, and take a look at just the existence of the topmost layer. We can probably do it in parallel for all images since it's just HTTP (and doesn't rely on docker CLI).

Ideas?

**Comment by dgageot** [comment]
@ahmetb I don't think checking the topmost layer is an option. Summoning @jonjohnsonjr to cast the light on this issue!

**Comment by dlorenc** [comment]
We can't check just the topmost layer, but we can check the manifest itself. Unfortunately docker doesn't always know the digest locally, so computing the sha to check will be slow.

**Comment by balopat** [comment]
Wow, it is fun to find your old moonshot ideas @ahmetb :) 
This got mostly implemented now by artifact caching (`--cache-artifacts=true` by default!)
