### ISSUE TITLE
Loading images into kind cluster nodes just... doesn't

### ISSUE THREAD

**Issue by jamfor999** [GoogleContainerTools/skaffold#9273]
### Expected behavior
When using `skaffold dev` where a local docker image should be built from a directory & loaded, the image should be uploaded into the kind cluster being used.

### Actual behavior
Logs from Skaffold say it's been done:
```
Loading images into kind cluster nodes...
 - myimage:064cffb7ddcc9921c3b1c5caacec7a313771c9cb2c9eb2ca06bd0a9547d4d802 -> Found
```
but when executing into the control plane and using `crictl images`, the image is just... not listed. And the resulting deployment naturally fails with an ImagePullBackoff.

### Information

- Skaffold version: 2.10.0
- Operating system: macOS Sonoma
- Installed via: Homebrew (although issue appears regardless of installation source from testing)
- Kind runtime & Container runtime: podman (which the kind cluster uses)
- Contents of skaffold.yaml: Can't paste due to work related info there

No more info in here, as -vdebug doesn't showcase any information at this particular moment.
Relevant log that implies it has been done, when it clearly hasn't, is this:

```
Loading images into kind cluster nodes...
 - myimage:064cffb7ddcc9921c3b1c5caacec7a313771c9cb2c9eb2ca06bd0a9547d4d802 -> Found
```

**Comment by Evynglais** [comment]
@jamfor352 what did you do to resolve this? I'm having a similar problem...

**Comment by jamfor352** [comment]
> @jamfor352 what did you do to resolve this? I'm having a similar problem...

We just ditched podman, it was causing more issues elsewhere too, this was one of them. Now we use docker + colima which works perfectly.

**Comment by Evynglais** [comment]
Ah, okay. I switched away from podman recently too, so it won't be that, but thanks for the info!
