### ISSUE TITLE
Wrong latest version shown in `skaffold.yaml` documentation page

### ISSUE THREAD

**Issue by ar3s3ru** [GoogleContainerTools/skaffold#9371]
Looking at the current version of the docs, specifically https://skaffold.dev/docs/references/yaml/, the latest schema version is reported to be `v4beta5`, while it should be `v4beta9`.

Screenshot:

<img width="1490" alt="Screenshot 2024-03-31 at 19 58 31" src="https://github.com/GoogleContainerTools/skaffold/assets/6481571/422f64aa-a25e-48d5-92ab-5ff0cb2ca413">

**Comment by renzodavid9** [comment]
Fixed in https://skaffold.dev/docs/references/yaml/. Thanks!
