### ISSUE TITLE
Allow any network to be provided to docker builder

### ISSUE THREAD

**Issue by edwardthiele** [GoogleContainerTools/skaffold#9389]
Under the Skaffold build configuration for docker, you can provide a network to connect the docker container (https://skaffold.dev/docs/references/yaml/#build-artifacts-docker-network), however you are restricted in terms of what network options can be set.

In particular, you cannot set network=cloudbuild, which can be helpful for auth reasons when running inside Google Cloud Build.

### Expected behavior
You should be able to set network=cloudbuild and ideally any other network

### Actual behavior
Validation fails when network=cloudbuild is set

**Comment by idsulik** [comment]
Removed validation within this PR https://github.com/GoogleContainerTools/skaffold/pull/9390, now it supports any network
