### ISSUE TITLE
Label docker images

### ISSUE THREAD

**Issue by danwkennedy** [GoogleContainerTools/skaffold#939]
It'd be great to be able to specify a list of labels to apply to the docker image that gets built every time Skaffold is run. This would allow for a Skaffold-specific label to be set (i.e. `process=skaffold`) which in turn would allow devs to use docker's prune command to clean up unneeded images. In this case `docker image prune --filter label=process=skaffold`.

**Comment by balopat** [comment]
Now that we have automated pruning, I think we can close this. Please reopen if needed!

**Comment by cliffburdick** [comment]
@balopat besides the original scenario, I think there are other use cases for labeling images besides just for image cleanup. Is there a way to do that? Maybe have a label section just as there is buildArgs?

**Comment by nkubala** [comment]
this would currently be possible by using a custom builder that just issues a `docker build` with the labels set on it, but yes we could just add a `labels` section to the docker artifact in the skaffold.yaml and then pass those to the CLI when we do the docker build.

@cliffburdick are you interested in submitting a PR?

also @balopat if we could somehow autogenerate the flag surface into the skaffold config then this would require zero work from us :)

**Comment by cliffburdick** [comment]
@nkubala I'll look into it. It seems fairly easy to do.
