### ISSUE TITLE
Skaffold doesn't deliver the error messages

### ISSUE THREAD

**Issue by CsYang1248** [GoogleContainerTools/skaffold#9434]
After some modifications on my codebase, I ran `skaffold delete` only to receive a simple 'exit status 1' without any informative message.
I escalated the verbosity to INFO and then to DEBUG but found no error message.

```
INFO[0000] Tags generated in 24.25042ms                  subtask=-1 task=Build
INFO[0000] Starting render...                            subtask=-1 task=DevLoop
exit status 1
```

I noticed that the error occurs after `Starting render` so I tried `skaffold render` and it finally displays the full error message (like below)
I think skaffold should give me the full error message.

The same happens when I run `skaffold deploy`. I get no error message until I try `skaffold run`, which fails for the same reason but provides the full error message.
According to my memory, the cause of the error was identical. So, maybe, skaffold just fails to deliver the error messages from the render for some commands?

### Expected behavior
display full error message like below, which `skaffold render` provided
```
running [kubectl --context xxx kustomize overlays/yyy]
 - stdout: ""
 - stderr: "error: loading KV pairs: env source files: [zzz.env]: evalsymlink failure on 'zzz.env' : lstat zzz.env: no such file or directory\n"
 - cause: exit status 1
```

### Actual behavior
displays only the status code

```
exit status 1
```
### Information

- Skaffold version: v2.9.0
- Operating system: 
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
- Installed via:
```bash
  curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
  sudo install /tmp/skaffold /usr/local/bin/
```
- Contents of skaffold.yaml:
I think it's unnecessary

### Steps to reproduce the behavior
I think it's unnecessary

The `-vdebug` didn't provide any useful information.
```
DEBU[0000] Running command: [kubectl --context xxx kustomize yyy]  subtask=0 task=Render
DEBU[0000] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0000] Command output: [256
]                        subtask=-1 task=DevLoop
exit status 1
```

**Comment by idsulik** [comment]
Hi @CsYang1248 
Thank you for the issue, fixed it here https://github.com/GoogleContainerTools/skaffold/pull/9437
