### ISSUE TITLE
skaffold trying to create a bucket and failing

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#947]
### Actual behavior

`skaffold run` failed with

`build step: building [gcr.io/testproject100000/emailservice]: creating bucket if not exists: googleapi: Error 409: You already own this bucket. Please select another name., conflict`

### Expected behavior

v0.13.0

Just tried `skaffold run -p gcb` with googleCloudBuild on a new project. Project had GCB enabled and at least one image already in GCR.

`skaffold` shouldn't be in the business of creating GCS buckets.

### Information

- Skaffold version: v0.13.0
- Operating system: cloud shell

**Comment by r2d4** [comment]
I agree. However, Cloud Build doesn't create the bucket for you afaik, its actually created by gcloud. This might have changed?

**Comment by ahmetb** [comment]
This wasn't on my project so I had no way of reproing this. But I'm seeing

```
pkg/skaffold/build/container_builder.go
128-
129-	cbBucket := fmt.Sprintf("%s%s", cb.ProjectID, constants.GCSBucketSuffix)
130-	buildObject := fmt.Sprintf("source/%s-%s.tar.gz", cb.ProjectID, util.RandomID())
131-
132-	if err := cb.createBucketIfNotExists(ctx, cbBucket); err != nil {
133:		return nil, errors.Wrap(err, "creating bucket if not exists")
```

Sooo maybe the `if not exists` check isn't working correctly.

**Comment by MrTrustor** [comment]
Just ran into this on a brand new project trying to deploy the [hipster shop](https://github.com/GoogleCloudPlatform/microservices-demo/tree/1bab006af1d7d856b41ea67ec1824277120ae549).

GCR, GCB and GKE APIs manually enabled, a single GKE cluster created (as per instructions in the hipster shop README) and ran a `skaffold run -b gcb`.

**Comment by ahmetb** [comment]
it clearly comes from

```
        if err := c.Bucket(bucket).Create(ctx, projectID, &cstorage.BucketAttrs{
                Name: bucket,
        }); err != nil {
                return err
        }
```

but I'm not sure why the following code fails to detect the bucket.

```
        _, err = c.Bucket(bucket).Attrs(ctx)

        if err == nil {
                // Bucket exists
                return nil
        }

        if err != cstorage.ErrBucketNotExist {
                return errors.Wrapf(err, "getting bucket %s", bucket)
        }
```

Eventual consistency???

**Comment by r2d4** [comment]
I'm not actually sure what the right way to check for existence of a bucket is. That was the easiest way I thought would work.

We can 
1. Delete that code, not create buckets ever
2. Figure out a more robust way to check for bucket existence

I think the first option is probably the best for now

**Comment by ahmetb** [comment]
I think your approach is right but why is this happening. 

Maybe something else is creating the bucket at the same time. That would cause ifs to pass then Create to fail.

**Comment by ahmetb** [comment]
Maybe we should capture  429 error from Create (as it always means bucket exists and you own it). SDK makes this possible.

**Comment by ahmetb** [comment]
I just ran `skaffold run -p gcb` (that uses googlecloudbuild to build) **twice** on a clean GCP project and got two different errors:

first time:

```
skaffold run -p gcb
Starting build...
Building [gcr.io/microservices-demo-app/emailservice]...
FATA[0002] build step: building [gcr.io/microservices-demo-app/emailservice]: creating bucket if not exists: googleapi: Error 409: You already own this bucket. Please select another name., conflict
```

wait a few seconds

second time:
```
Starting build...
Building [gcr.io/microservices-demo-app/emailservice]...
Pushing code to gs://microservices-demo-app_cloudbuild/source/microservices-demo-app-cb292ca2f4c014fed9ed3fe09b50a66d.tar.gz

FATA[0007] build step: building [gcr.io/microservices-demo-app/emailservice]: could not create build: googleapi: Error 403: Access Not Configured. Cloud Build has not been used in project microservices-demo-app before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=microservices-demo-app then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., forbidden
```

I think this is a consistency issue. Maybe the bucket is not immediately available after creating.

**Comment by dlorenc** [comment]
> Maybe we should capture 429 error from Create (as it always means bucket exists and you own it). SDK makes this possible.

Just to be clear, you mean 409 not 429 right?

**Comment by ahmetb** [comment]
Yeah 409, my bad.
