### ISSUE TITLE
What's the font used in intro.gif?

### ISSUE THREAD

**Issue by zx8** [GoogleContainerTools/skaffold#949]
From https://github.com/GoogleContainerTools/skaffold/blob/master/docs/img/intro.gif

See ticket title 👇

![image](https://user-images.githubusercontent.com/8544900/44944912-0ea3f480-add7-11e8-82c1-c8100ab35283.png)

**Comment by balopat** [comment]
cc @dgageot

**Comment by dgageot** [comment]
@zx8 I couldn't find which one I used. Why ask?

**Comment by zx8** [comment]
> Why ask?

I liked it and wanted to use it in presentation in a few weeks.

If you manage to find it, please let me know!
