### ISSUE TITLE
Using skaffold + kaniko without GCS

### ISSUE THREAD

**Issue by apobbati** [GoogleContainerTools/skaffold#950]
Is there an example of trying to use Skaffold and Kaniko together without using GCS ?

**Comment by atugade** [comment]
You know I've been wondering myself because I need this feature as well and it looks like gcs is the only way right now:

https://github.com/GoogleContainerTools/skaffold/blob/1354cb4c52f502e87c9c94ddcf980c41698c39f8/pkg/skaffold/build/kaniko/run.go#L61

**Comment by balopat** [comment]
Yes, currently only GCS is available. I assume you would like to use S3?

**Comment by atugade** [comment]
@balopat that and also local directory as well, I have a use case for that as well.

**Comment by atugade** [comment]
@priyawadhwa @balopat , I opened a PR for what I did so I could test out how it feels to use this tool with a local and s3 build context.

https://github.com/GoogleContainerTools/skaffold/pull/972

**Comment by balopat** [comment]
Hi @atugade thank you for sharing your approach we will look to see what we can incorporate from it, as @priyawadhwa already started working on this 5 days ago and is getting pretty close.

**Comment by priyawadhwa** [comment]
@atugade thanks for sharing, I'll definitely take a look!
