### ISSUE TITLE
Builders should build all artifact types

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#953]
Currently some builder types (GCB, Local, Kaniko) are incompatible with artifact types (Bazel, Dockerfile, jib (soon)).

|  | dockerfile | bazel | jib |
|:------:|:----------:|:-----:|:---:|
| local | x | x | x |
| GCB | x |  | x |
| Kaniko | x |  |  |

**How can GCB Support other builder types?**
The generated cloud build YAML should use the skaffold docker image as the builder, which contains bazel and will soon contain jib. 

The context tarball will be generated from the dependencies as normal (in the case of bazel, if the dependencies aren't exactly correct, we'll need to change this).

In addition, we can also upload the skaffold.yaml. The generated cloudbuild.yaml will run a `skaffold run --builder=local` inside the skaffold docker image, which will just build the same artifact types overriding the "builder type" using the local bazel or jib installation in the image.

**How can Kaniko Support other builder types?**

This would be the same strategy as GCB, but instead of creating a cloudbuild.yaml that uses the skaffold image and `skaffold run` inside the image, we would use kaniko in the "dockerfile" case, but generate a pod.yaml with skaffold for the bazel/jib case.

Essentially this would be the "on cluster" build strategy

**Comment by balopat** [comment]
Nesting/restructuring is orthogonal. We can validate the config in its current form too. 

+1 on that validation could be a useful stop-gap until we make a combination supported. 

Whether to support GCB+bazel/jib and kaniko + bazel/jib I think we need more evidence, and this issue would be for collecting user feedback on it. 

If users find these combinations interesting, please upvote, thumbs up here :)

**Comment by dlorenc** [comment]
> Nesting/restructuring is orthogonal to this. We can validate the config in its current form too.
> Added #955 to discuss that further.

Thanks for the explanation, that makes sense to me!

**Comment by dgageot** [comment]
I'm going to close this one.
 + The issue to track Bazel support in GCB is [here](https://github.com/GoogleContainerTools/skaffold/issues/362)
 + Supporting non-Docker artifacts in Kaniko is a non-goal
