### ISSUE TITLE
Auto configure docker auth to push to gcr.io

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#966]
When Skaffold is pushing an image to gcr.io, it would be convenient if it could configure automatically the credential helper.

Otherwise, a user has to follow the guide [here](https://cloud.google.com/container-registry/docs/advanced-authentication). All it does is add those lines to `~/.docker/config.json`:

```
  "credHelpers": {
    "gcr.io": "gcloud",
    "us.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "marketplace.gcr.io": "gcloud"
  }
```

We could add only the line that is required to push the image we want to push. And Skaffold doesn't even have to edit the docker config file, it can all be done with code.

**Comment by r2d4** [comment]
I think it makes sense as a fallback. i.e. if the config.json doesn't have an entry for *.gcr.io, then we can fallback to this hardcoded list. 

The only problem with using ours as the source of truth is that things might get out of sync (I'm not sure how often a new url would get added)
