### ISSUE TITLE
Remove docker-credential-gcr from Dockerfile

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#967]
https://github.com/GoogleContainerTools/skaffold/blob/master/deploy/skaffold/Dockerfile#L37-L42

We can just remove this and use `gcloud auth configure-docker`

**Comment by dgageot** [comment]
@r2d4 What's the simplest way to test the image after the change is made?

**Comment by nkubala** [comment]
https://github.com/GoogleContainerTools/container-structure-test :)

You can run command tests to make sure the credential helper isn't there, to make sure gcloud is there, and to make sure `gcloud auth configure-docker` exits successfully, and maybe check the output to make sure some success string is present.
