### ISSUE TITLE
FATA[0004] watching files for artifact sample-cmd: listing files: unable to stat file (when symlink)

### ISSUE THREAD

**Issue by jsturtevant** [GoogleContainerTools/skaffold#970]
### Expected behavior
`skaffold dev` runs as expected when parsing symlinks.  It appears when a symlink for the [ectd](https://github.com/etcd-io/etcd/tree/v3.3.8) project is parsed skaffold can not follow the link.    

### Actual behavior
```
skaffold dev
Cleaning up...
Cleanup complete in 266.817ms
FATA[0003] watching files for artifact sample-cmd: listing files: unable to stat file vendor/github.com/coreos/etcd/Documentation/README.md: stat vendor/github.com/coreos/etcd/Documentation/README.md: no such file or directory
```

### Information

- Skaffold version: version... v0.13.0
- Operating system: ... ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: sample-cmd
deploy:
  kubectl:
    manifests:
      - deploy.yaml
```

### Steps to reproduce the behavior
I created a minimal project to reproduce the error: https://github.com/jsturtevant/skaffold-symlink-error-example

1. `go get github.com/jsturtevant/skaffold-symlink-error-example`
2. `cd $GOPATH/src/github.com/jsturtevant/skaffold-symlink-error-example`
3.  `skaffold dev`

```
Cleaning up...
Cleanup complete in 266.817ms
FATA[0003] watching files for artifact sample-cmd: listing files: unable to stat file vendor/github.com/coreos/etcd/Documentation/README.md: stat vendor/github.com/coreos/etcd/Documentation/README.md: no such file or directory
```
4. ` ls -la vendor/github.com/coreos/etcd/Documentation/README.md`

```
lrwxrwxrwx 1 7 Sep 11 20:02 vendor/github.com/coreos/etcd/Documentation/README.md -> docs.md
```

## Notes
This did not happen on skaffold v0.10.  I was able to track down the bug to the [watch/changes.go](https://github.com/GoogleContainerTools/skaffold/blob/cfe5a70df358e7422dd837868c2f6341fe05e13e/pkg/skaffold/watch/changes.go#L52) and if I change that to os.Lstat(path) it works.

**Comment by jsturtevant** [comment]
It appears that `dep ensure` does some clean up on files which leaves behind a broken symlink in the vendor folder the etcd project.  Submitted a PR that handles the broken symlink.

**Comment by dgageot** [comment]
@jsturtevant Can you check with master branch. I think it's fixed

**Comment by jsturtevant** [comment]
Yes, fixed on master. Thanks for the update!

**Comment by wstrange** [comment]
I think I am seeing this on 0.15.0.  Has this fix made it into that release?
