### ISSUE TITLE
Port forwarding pods fails on microservices example

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#974]
### Expected behavior
Pods are port forwarded correctly

### Actual behavior
Skaffold fails to port forward both pods, with
```
Port Forwarding leeroy-app-79b99dbc4-4ss4k 50051 -> 50051
WARN[0010] port forwarding pod failed: port forwarding: port forwarding pod: leeroy-app-79b99dbc4-4ss4k, port: 50051, err: error: invalid resource name "pod/leeroy-app-79b99dbc44ss4k": [may not contain '/']
: exit status 1
```

### Information

- Skaffold version: built at commit `abe80329cf875d78257c654d177f297d1a9cf15d`
- Operating system: OS X
- Contents of skaffold.yaml: `microservices` example with skaffold.yaml generated from `skaffold init`

### Steps to reproduce the behavior

1. Run `skaffold init` in microservices example directory
2. Run `skaffold dev` in same directory

**Comment by r2d4** [comment]
Can you post the skaffold.yaml just to make it a little easier to produce?

**Comment by r2d4** [comment]
One other thing, it works for the microservices example without skaffold init right? I think I tested that case.
