### ISSUE TITLE
Proposal: support docker build "--pull" flag

### ISSUE THREAD

**Issue by ahmetb** [GoogleContainerTools/skaffold#980]
As far as I can tell, `build.artifacts.docker` field right now doesn't support `--pull` flag. 

This flag is not so much required for local dev machine iteration but it is essential for picking up security fixes for images going to prod:

- **In local dev:** if I have `FROM alpine:3.8`, I don't want to --pull to cause a "docker pull alpine:3.8" every time I refactor my code.
- **While deploying (in CD environment):** I want my builds to happen with "docker build --pull" so I pick up the lates security fixes on the base image(s).

I think we should have a field like:

```yaml
build:
  artifacts:
  - docker:
      options:
        pull: "{Disabled, Always, DeployOnly}"
```

This `pull` field controls the `docker build --pull` flag.
- `Disabled`: (default value, where we are today), don't use --pull
- `Always`: use --pull for both local dev and deployment builds
- `DeployOnly` use --pull for "skaffold {deploy,run}" commands.

**Comment by dgageot** [comment]
@ahmetb What about running with `--pull` each time we build an image for `skaffold run` and without this flag for `skaffold dev`?

**Comment by balopat** [comment]
It think we can add this as a boolean option and use profile patches to set it up, that are activated by command names.

**Comment by vlindvall** [comment]
Was there ever any progress made on this?
I'm trying to find a way to make sure my build always pulls the latest version of the base image but am having trouble doing so.
I'm looking for the skaffold equivalent of `docker build --pull`

**Comment by tstromberg** [comment]
Thank you for the idea!

I'm closing this issue as it's been open a while, and it is not clear if it's still an open issue. No one has recently stated an interest in addressing this, but if you feel strongly about it, please feel free to add a comment or send us a PR!
