### ISSUE TITLE
Expose Watch API

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#996]
Expose the watch API through either HTTP or gRPC for IDE integration

**Comment by dlorenc** [comment]
SIGHUP is also pretty common to trigger a full config reload on unix systems.

**Comment by r2d4** [comment]
SIGHUP could very well trigger a full config reload across all watchers, but this issue is more about exposing the actual Watch API to get added, modifed, and deleted files to trigger both rebuilds and redeploys. That way, IDEs could take ownership of tracking changes, and let skaffold know when and what has changed.

I imagine a payload like the "watch events" I'm about to add back:

```
{
  "files": {
    "added": ...
    "deleted":..
    "modified": ...
  }
}
```

i.e. instead of filesystem events, we'd listen on a port on a particular endpoint for events

**Comment by balopat** [comment]
We do have the Control API now, closing.
