### ISSUE TITLE
Keyboard shortcuts during skaffold dev

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#997]
During skaffold dev

Press 'b' to rebuild
Press 'd' to redeploy
Press 'r' to reload skaffold.yaml and skaffold run

Future features
Press 's' to resync

**Comment by balopat** [comment]
cc https://github.com/GoogleContainerTools/skaffold/issues/913

**Comment by dlorenc** [comment]
This is awesome.

**Comment by bhack** [comment]
I think that we could a shortcuts also for having a shell interaction. See https://github.com/GoogleContainerTools/skaffold/issues/913#issuecomment-427644045

**Comment by tejal29** [comment]
Skaffold now supports control api with manual trigger mode, which can run a build via sending a request to Control api e.g. for build.
```
curl -X POST http://locahost:50052/v1/execute -d ‘{“build”:true}’
```
I am going to close this request.
